### ISSUE TITLE
Upgrade to pcre2

### ISSUE THREAD

**Issue by rverma-nikiai** [telepresenceio/telepresence#1011]
Creating this issue as downstream action for https://github.com/libfuse/sshfs/issues/171.
If sshfs get upgraded to pcre2 we can release another package with upgraded lib

More specifications here https://www.pcre.org/current/doc/html/pcre2.html. Worth upgrading the dependent package.

**Comment by ark3** [comment]
I do not understand. What does this have to do with Telepresence?
