### ISSUE TITLE
Telepresence fails to kill the user's container if the container has a name set by the user

### ISSUE THREAD

**Issue by davidmichaelkarr** [telepresenceio/telepresence#1014]
I am starting telepresence with the following sample command line:

`telepresence --verbose --swap-deployment cartms-blue --docker-run -p 5005:5005 -p 8080:8080 --name=cartms -e xdebug_enable_env=t -t dockercentral.it.att.com:5100/com.att.idp/cartms:$LOGNAME-latest`

This starts up fine and does what it does.  At some point, I will see something like this in the output:

```
T: Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
T:   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -vv -p 46216 telepresence@127.0.0.1 -L127.0.0.1:39127:127.0.0.1:9050 -R9055:127.0.0.1:39230

T: Recent output was:
T:   debug1: channel 1: free: ::1, nchannels 2
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
...
T:   Timeout, server 127.0.0.1 not responding.


T: Proxy to Kubernetes exited. This is typically due to a lost connection.

T: Exit cleanup in progress
```
However, after this, I find that there are still background processes writing to stdout.  I looked at running processes, and I saw:
`<uid>   19458  0.0  0.6 434812 51800 pts/14   Sl   11:43   0:00 docker run --name=telepresence-1556304181-5809424-18840 ...`

After I manually killed that process, the output to stdout stopped.

**Comment by davidmichaelkarr** [comment]
[telepresence.log](https://github.com/telepresenceio/telepresence/files/3122949/telepresence.log)

**Comment by davidmichaelkarr** [comment]
[telepresence.log](https://github.com/telepresenceio/telepresence/files/3122961/telepresence.log)

**Comment by ark3** [comment]
Thank you for the issue. As an experiment, could you please try your command again without passing any `--name` argument to Docker? I suspect Telepresence is doing something dumb with respect to named containers.

**Comment by davidmichaelkarr** [comment]
Acknowledged.  I'll run some tests today.  Even when it's failing this way, it sometimes takes quite a long time after starting up the process that this happens.

**Comment by davidmichaelkarr** [comment]
I haven't seen it happen yet.  Is there a separate issue to address why it bungles named containers?

**Comment by ark3** [comment]
This issue will be the one.

**Comment by ark3** [comment]
To fix this:
- Always capture the container ID that gets output by `docker run -d`
- Pass the IDs to `docker kill` commands instead of names.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since you can pass docker commands to `--docker-run` so adding `--rm` should fix this problem. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
