### ISSUE TITLE
ssh process fails with no explanation, need more verbosity

### ISSUE THREAD

**Issue by davidmichaelkarr** [telepresenceio/telepresence#1015]
I start up telepresence with a line like this:
`telepresence --verbose --swap-deployment cartms-blue --docker-run -p 5005:5005 -p 8080:8080 --name=cartms -e xdebug_enable_env=t -t <repo>/com.att.idp/cartms:$LOGNAME-latest`

It connects and stays connected for an indeterminate period.

At some point, I see the following on stdout:
```
T: Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
T:   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -vv -p 37724 telepresence@127.0.0.1 -L127.0.0.1:34988:127.0.0.1:9050 -R9055:127.0.0.1:39188

T: Recent output was:
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
...
T:   Timeout, server 127.0.0.1 not responding.


T: Proxy to Kubernetes exited. This is typically due to a lost connection.
```

This is completely repeatable, but not the time it takes to happen.  It could be a couple of minutes or a couple of hours.

There's nothing obviously wrong with the network when this happens.  I see that the "ssh" command emits "-vv".  This might provide more information if it was run as "-vvv", but I see no way to configure that.

**Comment by ark3** [comment]
Thanks for the issue. We'll address your specific request (configurable verbosity) in #985. The problem you're seeing is very similar to the one in #931; my attempt at debugging that did not shed any light so far. As I said there, automatic reconnection #8 may be the best solution.
