### ISSUE TITLE
Add option to delete container if it exists

### ISSUE THREAD

**Issue by davidmichaelkarr** [telepresenceio/telepresence#1016]
Please add a command-line option that will cause an existing container to first be deleted before trying to run the image. I'm sick and tired of forgetting to remove the container since the last time it failed, and then having to wait for the pods to cycle back before I can try it again.

**Comment by ark3** [comment]
Assuming this is due to named containers (`docker run ... --name whatever ...`), I think fixing #1014 will address your real concern.

**Comment by davidmichaelkarr** [comment]
It is from that, yes.
