### ISSUE TITLE
Crash when resolving a non-existing domain on a Mac

### ISSUE THREAD

**Issue by amarchen** [telepresenceio/telepresence#1023]
I see this issue happening once in a while, definitely not a 100% repro, but this time I happened to notice what exactly I was doing when it happened

**Environment**
- Mac OS X Mojave - 10.14.1
- local kubernetes supplied by Docker-for-desktop

**Repro steps**
1. Started telepresence to local kubernetes in `vpn-tcp` mode with port mapping
2. Typed in the Chrome browser address bar "vr" or possibly "vr\" - was going to type "vr.fi", but clicked something wrong on the keyboard
3. Telepresence crashed with the following:
```
   ~/tmp/asg  $ T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one
T:  telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless
T: services with --also-proxy. For a full list of method limitations see
T: https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment companyservice with a proxy
T: Forwarding remote port 80 to local port 9292.


Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 311, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect


Here are the last few lines of the logfile (see /Users/artem/tmp/asg/telepresence.log for the complete logs):

  32.1  21 | 2019-05-02T09:10:25+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 3890
  32.1  21 | 2019-05-02T09:10:25+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fc3e6f97358>
  32.1  21 | 2019-05-02T09:10:25+0000 [-] (UDP Port 3618 Closed)
  32.1  21 | 2019-05-02T09:10:25+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fc3e6f7e9e8>
  32.1  21 | 2019-05-02T09:10:25+0000 [stdout#info] Failed to lookup b'vr' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DNSNameError'>: <Message id=31192 rCode=3 maxSize=0 flags=answer,recDes,recAv queries=[Query('vr', 1, 1)] authority=[<RR name= type=SOA class=IN ttl=86391s auth=False>]>
  32.1  21 | 2019-05-02T09:10:25+0000 [stdout#info] ], falling back to b'vr.bcpapula'
  32.1  21 | 2019-05-02T09:10:25+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 23857
  32.1  21 | 2019-05-02T09:10:25+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fc3e6f97320>
  32.1  21 | 2019-05-02T09:10:25+0000 [-] (UDP Port 3890 Closed)
  32.1  21 | 2019-05-02T09:10:25+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fc3e6f97358>
  32.1  21 | 2019-05-02T09:10:25+0000 [-] (UDP Port 23857 Closed)
  32.1  21 | 2019-05-02T09:10:25+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fc3e6f97320>

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product.
```

P.S.
BTW, I am never able to agree to the suggestion of autocreating the issue - whatever I press, nothing happens. But that's for another bug report.

**Comment by ark3** [comment]
Sorry about the crash. It is _possible_ that your Telepresence session is crashing on startup (by timing out waiting for the VPN to connect) because of that DNS request from your browser, presumably by causing other DNS requests to take longer. We have other outstanding issues about the VPN connect crash/timeout too; I'll keep this in mind.

Thank you for filing this issue manually. Regarding the automatic issue stuff, it relies on the Python `webrowser` module. For example, I can open a new tab in my browser like this:

    python3 -c 'import webbrowser; webbrowser.open_new("https://www.telepresence.io")'

Does that work for you?

**Comment by amarchen** [comment]
Yes, `python3 -c 'import webbrowser; webbrowser.open_new("https://www.telepresence.io")'` opens new page fine.

That is possibly a bit offtopic for this particular issue, but since you are asking, there's second thing that is strange about the crash. Whenever telepresence crashes (with or without an offer to create a ticket), in terminal I cannot see my keyboard input anymore :)
I can actually type (in most of cases I just press Up and then Enter to restart the telepresence connection), but I cannot see what I am typing :)

**Comment by ark3** [comment]
Strange that the webbrowser thing doesn't work from Telepresence, then...

I've seen corruption of the terminal state before, usually from `--docker-run`, but I suppose any application can do that. Telepresence itself does not mess with the terminal. I tried adding a `tput reset` to the exit process, but it didn't work, presumably because I did not hook it up to the terminal correctly.

**Comment by amarchen** [comment]
Guys, you are doing an awesome product that helps me a lot, so if I can measure anything or send logs, just tell what you need :)
I have this issue reproduced often, but don't know what to send about it. If you like, I can even run debug-enabled version of telepresence (assuming it is easy to get and easy to disable if it happens to be too slow)

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
