### ISSUE TITLE
OpenShift not working with unprivileged user

### ISSUE THREAD

**Issue by hypery2k** [telepresenceio/telepresence#1024]
### What were you trying to do?

run this command:
```
telepresence --docker-run --rm -it fedora curl -k https://kubernetes.default/api/
```

### What did you expect to happen?

create a new deployment

### What happened instead?

crash

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--docker-run', '--rm', '-it', 'fedora', 'curl', '-k', 'https://kubernetes.default/api/']`
Version: `0.99`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.14.1 // Server Version: v1.10.0+b81c8f8`
oc version: `oc v3.11.0+0cbc58b // kubernetes v1.11.0+d4cacc0 // features: Basic-Auth //  // Server https://my-cluster.io:8443 // openshift v3.10.83 // kubernetes v1.10.0+b81c8f8`
OS: `Darwin MPB-M1.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 95, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 153, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 100, in get_deployment_json
    )["items"][0]
IndexError: list index out of range

```

Logs:

```
1f
   4.9  10 | No resources found
   4.9 TEL | [10] ran in 0.46 secs.
   4.9 TEL | [11] Running: oc --context mip-dev/my-cluster.io:8443/lc09237 --namespace mip-dev run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1557167743-72711-31635 --image=datawire/telepresence-k8s:0.99 --labels=telepresence=8f683b5d93b14fb1908a6487601a401f
   5.3  11 | deploymentconfig.apps.openshift.io/telepresence-1557167743-72711-31635 created
   5.4 TEL | [11] ran in 0.46 secs.
   5.4 TEL | END SPAN deployment.py:70(create_new_deployment)    0.9s
   5.4 TEL | BEGIN SPAN remote.py:151(get_remote_info)
   5.4 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   5.4 TEL | [12] Capturing: oc --context mip-dev/my-cluster.io:8443/lc09237 --namespace mip-dev get deployment -o json --selector=telepresence=8f683b5d93b14fb1908a6487601a401f
   5.8 TEL | [12] captured in 0.42 secs.
   5.8 TEL | END SPAN remote.py:78(get_deployment_json)    0.4s

```

**Comment by ark3** [comment]
Sorry about the crash. I believe you're hitting this issue: https://github.com/telepresenceio/telepresence/issues/1010#issuecomment-486736557. We'll try to get this fixed soon.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
