### ISSUE TITLE
Error running telepresence

### ISSUE THREAD

**Issue by rfontecha-ob** [telepresenceio/telepresence#1025]
### What were you trying to do?

Expose 8080 port through k8s cluster

### What did you expect to happen?

Redirect k8s port to local port

this exception

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--mount=/tmp/tel_root', '--deployment', 'telepresence', '--expose', '8080', '--run-shell', '--namespace=dev-snow', '--logfile', '/tmp/tele.log']`
Version: `0.99`
Python version: `3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.9.10 // Server Version: v1.9.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux obmate 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 311, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
on3 -c 'import socket; socket.gethostbyname("hellotelepresence-49")'
  31.5 TEL | [123] exit 1 in 0.17 secs.
  31.5 TEL | [124] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-49.a.sanity.check.telepresence.io")'
  31.8 TEL | [124] exit 1 in 0.27 secs.
  31.9 TEL | Wait for vpn-tcp connection: hellotelepresence-50
  31.9 TEL | [125] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-50")'
  32.1 TEL | [125] exit 1 in 0.17 secs.
  32.1 TEL | [126] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-50.a.sanity.check.telepresence.io")'
  32.4 TEL | [126] exit 1 in 0.37 secs.
  33.8  23 | c : DNS request from ('127.0.0.1', 33413) to None: 28 bytes
  33.8  13 | 2019-05-10T13:23:35+0000 [stdout#info] A query: b'google.com'
  33.9  13 | 2019-05-10T13:23:35+0000 [stdout#info] Result for b'google.com' is ['74.125.193.101', '74.125.193.100', '74.125.193.139', '74.125.193.138', '74.125.193.113', '74.125.193.102']

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
