### ISSUE TITLE
Does tp do something smart when attempting to proxy a service that is already tp-proxied?

### ISSUE THREAD

**Issue by davidmichaelkarr** [telepresenceio/telepresence#1026]
I haven't tried to do this, but I'm thinking that it's likely this scenario isn't currently being handled in a helpful way.

I'm finding that running tp and proxying a service works pretty well, when I have exclusive access to the cluster.  I've been working on the prototype of this for my team for a while, and finally got some gateway details fixed yesterday, so I'm going to give a demo next week.  That's when that "exclusive access to the cluster" thing might get a little harder to manage.

I'm now at the point where I can just look at the names (and cardinality) of the pods in my service, to know whether the service is tp-proxied, or whether the normal pods are running.  I imagine I can teach my team members to have the same perception.  I'm also sure I can teach them to talk to each other to coordinate this "exclusive access" thing.

However, I am also virtually certain, beyond a shadow of a doubt, that quite often someone is going to try to proxy a service that someone else has already proxied.  I imagine that's going to kill the tp pod and create another one, proxied to the new local process.

What I WANT to see happen instead, is that when that second proxy attempt starts, it aborts immediately with a message like "hey dude, someone else is already using telepresence to proxy that service, so you can't do that".

I can imagine how this might work.  In fact, as I wrote a small scripting layer to start tp, it would be straightforward to implement it myself in a few lines of shell script. If the service only has a single pod, and is running an image whose name begins with "telepresence/", then I think it's reasonably certain that service is proxied with telepresence. I wonder if I can implement a protocol that would put some sort of metadata in the pod that would make it clear WHO is running the proxied service, and add that to the message. That's probably outside your purview, however.

**Comment by ark3** [comment]
Telepresence does not do anything smart for this case, but it probably could. Tel does not modify the original Deployment except to `kubectl scale` it down to zero replicas. At the very least, Tel should notice that, warn the user, and offer to abort.

Detecting another Telepresence session for a given Deployment might be tricky right now. Tel would have to look through all deployments with the `telepresence` label and try to match up to the original Deployment by looking at the other labels. Of course we could just include the original deployment information in Tel's copy. That seems a worthwhile addition too. The trick is to do this check without slowing down Tel's startup even further.

**Comment by davidmichaelkarr** [comment]
If there were significant "sanity" checks like this, they could be enabled with a "--verify" option.

**Comment by ark3** [comment]
The first part, noticing zero replicas, is pretty straightforward. In deployment.py, just check `deployment_json["spec"]["replicas"]`. If that's zero, there is nothing present to be swapped.

**Comment by donnyyung** [comment]
I believe this problem is solved by selective intercepts in Telepresence 2: https://www.telepresence.io/docs/latest/reference/intercepts/

**Comment by StefanLobbenmeierObjego** [comment]
FYI this is now called personal intercepts: https://www.getambassador.io/docs/telepresence/latest/concepts/intercepts#personal-intercept

(sorry to comment on this old issue, but the links above are dead)
