### ISSUE TITLE
Container is not working "datawire/telepresence-k8s:0.99"

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#1027]
**update**: Same on kubernetes

    docker run --rm datawire/telepresence-k8s:0.99

Is giving the following error:

    Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/twisted/application/app.py", line 674, in run
        runApp(config)
      File "/usr/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 25, in runApp
        runner.run()
      File "/usr/lib/python3.6/site-packages/twisted/application/app.py", line 381, in run
        self.application = self.createOrGetApplication()
      File "/usr/lib/python3.6/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
        application = getApplication(self.config, passphrase)
    --- <exception caught here> ---
      File "/usr/lib/python3.6/site-packages/twisted/application/app.py", line 464, in getApplication
        application = service.loadApplication(filename, style, passphrase)
      File "/usr/lib/python3.6/site-packages/twisted/application/service.py", line 416, in loadApplication
        application = sob.loadValueFromFile(filename, 'application')
      File "/usr/lib/python3.6/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
        eval(codeObj, d, d)
      File "./forwarder.py", line 62, in <module>
        main()
      File "./forwarder.py", line 53, in main
        with open(NAMESPACE_PATH) as f:
    builtins.FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/namespace'
    
    
    Failed to load application: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/namespace'

Setup:
```
docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ark3** [comment]
That `docker run` command is not expected to work. When you say "same on kubernetes," what do you mean? Can you show me what you're doing that's failing? Thanks!

If you want to experiment with that image, pass along a command to run:

```console
$ docker run --rm -it datawire/telepresence-k8s:0.99 sh
~ $ ls
Dockerfile         periodic.py        requirements.txt   run.sh             test_forwarder.py
forwarder.py       podinfo.py         resolver.py        socks.py           test_socks.py
~ $ 
```

**Comment by JCzz** [comment]
Thanks

I am trying to debug into a knative service, and I keep getting a `CrashLoopBackOff`. I then tried to run the image in docker. I did not expect to use `sh` when running the image.

knative service:
```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: datawire/telepresence-k8s:0.99
```

Sorry, it does actually work with your example from [here](https://www.telepresence.io/reference/connecting.html)

Any idea why not with Knative?
