### ISSUE TITLE
Argument parser: error on "--" after "--run"

### ISSUE THREAD

**Issue by alnr** [telepresenceio/telepresence#1028]
Running `telepresence [...] --run node node_modules/.bin/ts-node-dev --inspect -- .` yields an error:
```
telepresence: error: unrecognized arguments: -- .
```
Workarounds with quoting everything or parts after `--run` fail.

Looking at [this](https://github.com/telepresenceio/telepresence/blob/36ecc982b929c2148d9bb3fe9431017d9a5604dd/telepresence/cli.py#L343), Python's `argparse` should stop after `--run` but doesn't.

**Comment by ark3** [comment]
It appears that `argparse.REMAINDER` handles `--` as intended/described only when it is set for a positional argument. Tel uses it for an option (`--run` or `--docker-run`), and that chokes as described above.

Here's the beginnings of a fix that turns `--run` and `--docker-run` into boolean flags and takes the command/args as a positional. This is a pretty big change to command line parsing, so it deserves some significant testing. Plus we would need to do something useful if `--run-shell` is passed arguments.

```diff
diff --git a/telepresence/cli.py b/telepresence/cli.py
index d4bc175..8b2d401 100644
--- a/telepresence/cli.py
+++ b/telepresence/cli.py
@@ -342,9 +342,8 @@ def parse_args(args=None) -> argparse.Namespace:
     )
     group.add_argument(
         "--run",
-        metavar=("COMMAND", "ARG"),
         dest="run",
-        nargs=argparse.REMAINDER,
+        action="store_true",
         help=(
             "Run the specified command arguments, e.g. "
             "'--run python myapp.py'."
@@ -352,15 +351,20 @@ def parse_args(args=None) -> argparse.Namespace:
     )
     group.add_argument(
         "--docker-run",
-        metavar="DOCKER_RUN_ARG",
         dest="docker_run",
-        nargs=argparse.REMAINDER,
+        action="store_true",
         help=(
             "Run a Docker container, by passing the arguments to 'docker run',"
             " e.g. '--docker-run -i -t ubuntu:16.04 /bin/bash'. "
             "Requires --method container."
         )
     )
+    parser.add_argument(
+        "args",
+        nargs=argparse.REMAINDER,
+        help="Command and arguments to run or to pass to Docker.",
+    )
+
     args = parser.parse_args(args)
 
     # Fill in defaults:
```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
