### ISSUE TITLE
telepresence not starting

### ISSUE THREAD

**Issue by rfontecha-ob** [telepresenceio/telepresence#1030]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--mount=/tmp/tel_root', '--deployment', 'telepresence', '--expose', '8080', '--run-shell', '--namespace=dev-ned', '--logfile', '/tmp/tele.log']`
Version: `0.99`
Python version: `3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.9.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux toshibaRaul 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 95, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 211, in get_remote_info
    format(deployment_name)
RuntimeError: Telepresence pod not found for Deployment 'telepresence'.

```

Logs:

```
 json
 114.0 TEL | [102] captured in 0.26 secs.
 115.0 TEL | [103] Capturing: kubectl --context dev-snow --namespace dev-ned get pod -o json
 115.2 TEL | [103] captured in 0.25 secs.
 116.2 TEL | [104] Capturing: kubectl --context dev-snow --namespace dev-ned get pod -o json
 116.5 TEL | [104] captured in 0.27 secs.
 117.5 TEL | [105] Capturing: kubectl --context dev-snow --namespace dev-ned get pod -o json
 117.7 TEL | [105] captured in 0.24 secs.
 118.7 TEL | [106] Capturing: kubectl --context dev-snow --namespace dev-ned get pod -o json
 119.0 TEL | [106] captured in 0.26 secs.
 120.0 TEL | [107] Capturing: kubectl --context dev-snow --namespace dev-ned get pod -o json
 120.3 TEL | [107] captured in 0.28 secs.
 120.9 TEL | [108] Running: sudo -n echo -n
 120.9 TEL | [108] ran in 0.03 secs.
 121.3 TEL | [109] Capturing: kubectl --context dev-snow --namespace dev-ned get pod -o json
 121.6 TEL | [109] captured in 0.27 secs.
 121.6 TEL | END SPAN remote.py:151(get_remote_info)  119.5s

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
