### ISSUE TITLE
Intermittent Error (RuntimeError: SSH to the cluster failed to start)

### ISSUE THREAD

**Issue by jstol** [telepresenceio/telepresence#1031]
### What were you trying to do?

I have a K8s cluster on EKS. I've been attempting to use Telepresence using the following command:

```bash
telepresence --context eks_eks-dev --namespace apps --docker-run --rm -it fedora bash
```

I am using Telepresence v0.99.

### What did you expect to happen?

I'm expecting to be able to use Telepresence consistently.

### What happened instead?

I'm experiencing intermittent errors. Sometimes the container launches successfully and I'm able to access the `bash` console, but other times I receive the following error: `RuntimeError: SSH to the cluster failed to start.`

A Gist with the full logs can be found [here](https://gist.github.com/jstol/1cb92ef18524badd259c622ec26000ab).

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'apps', '--docker-run', '--rm', '-it', 'fedora', 'bash']`
Version: `0.99`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.10.11 // Server Version: v1.12.6-eks-d69f1b`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ip-192-168-1-91.ec2.internal 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 60, in connect
    raise RuntimeError("SSH to the cluster failed to start.")
RuntimeError: SSH to the cluster failed to start.

```

Logs:

```
in/true
 139.0 TEL | [125] exit 255 in 0.02 secs.
 139.3 TEL | [126] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61892 telepresence@127.0.0.1 /bin/true
 139.3 TEL | [126] exit 255 in 0.02 secs.
 139.6 TEL | [127] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61892 telepresence@127.0.0.1 /bin/true
 139.6 TEL | [127] exit 255 in 0.02 secs.
 139.8 TEL | [128] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61892 telepresence@127.0.0.1 /bin/true
 139.8 TEL | [128] exit 255 in 0.02 secs.
 140.1 TEL | [129] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61892 telepresence@127.0.0.1 /bin/true
 140.1 TEL | [129] exit 255 in 0.02 secs.
 140.4 TEL | [130] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61892 telepresence@127.0.0.1 /bin/true
 140.4 TEL | [130] exit 255 in 0.02 secs.

```

**Comment by jstol** [comment]
Wondering if anybody else has encountered this error. Developers across my organization have reported the same issue. I have a feeling it may have to do with how our K8s cluster has been configured, but I'm not totally sure.

**Comment by ark3** [comment]
Sorry I didn't get a chance to look at this earlier. The telepresence.log reference above doesn't show this crash (the [`5709.7 TEL | EXITING successful session.`](https://gist.github.com/jstol/1cb92ef18524badd259c622ec26000ab#file-telepresence-log-L1050) indicates otherwise). However, I can see from that log that nearly every `kubectl` command run by Telepresence takes ~15 seconds (the [`SPAN SUMMARY`](https://gist.github.com/jstol/1cb92ef18524badd259c622ec26000ab#file-telepresence-log-L1109) has a list). A few outliers there could easily lead to a timeout now and then. 

In the future, when we add optional configuration (#985), you might want to try increasing the `ssh` timeout to see whether that helps. I'm not sure there's much you can do until then.

**Comment by xpolb01** [comment]
> Wondering if anybody else has encountered this error. Developers across my organization have reported the same issue. I have a feeling it may have to do with how our K8s cluster has been configured, but I'm not totally sure.

Getting exactly the same error

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
