### ISSUE TITLE
Pod Creation Error - Memory/CPU Request below minimum

### ISSUE THREAD

**Issue by tripptuttle** [telepresenceio/telepresence#1034]
### What were you trying to do?

Initiating a telepresence session. But, our cluster has minimum memory limits higher than telepresence requested, so pod deployment is failing.

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

From the deployment log: 

--> Scaling telepresence-1559064429-966709-44930-1 to 1
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-zjvdf" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-sg97s" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-27p22" is forbidden: [minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Pod is 29m, but request is 25m., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-q27rg" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-nwmc7" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-zk5jm" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-r4h9f" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-lvlfr" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum memory usage per Container is 150Mi, but request is 64Mi., minimum cpu usage per Container is 29m, but request is 25m.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 Error creating: pods "telepresence-1559064429-966709-44930-1-cz4ll" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]
-->  FailedCreate: telepresence-1559064429-966709-44930-1 (combined from similar events): Error creating: pods "telepresence-1559064429-966709-44930-1-nltwt" is forbidden: [minimum cpu usage per Pod is 29m, but request is 25m., minimum memory usage per Pod is 150Mi, but request is 67108864., minimum cpu usage per Container is 29m, but request is 25m., minimum memory usage per Container is 150Mi, but request is 64Mi.]

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'postgres-gis']`
Version: `0.99`
Python version: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.10.11 // Server Version: v1.9.1+a0ce1bc657`
oc version: `oc v3.6.173.0.21 // kubernetes v1.6.1+5115d708d7 // features: Basic-Auth //  // Server https://api.cloudapps.unc.edu:443 // openshift v3.9.51 // kubernetes v1.9.1+a0ce1bc657`
OS: `Darwin dhcp152-54-9-116.europa.renci.org 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 60, in connect
    raise RuntimeError("SSH to the cluster failed to start.")
RuntimeError: SSH to the cluster failed to start.

```

Logs:

```
 by remote host.
  59.9 TEL | [56] exit 255 in 0.65 secs.
  60.0  20 | 2019-05-28T17:39:03+0000 [Poll#error] Failed to contact Telepresence client:
  60.0  20 | 2019-05-28T17:39:03+0000 [Poll#error] Connection was refused by other side: 111: Connection refused.
  60.0  20 | 2019-05-28T17:39:03+0000 [Poll#warn] Perhaps it's time to exit?
  60.1 TEL | [57] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 60246 telepresence@127.0.0.1 /bin/true
  60.1  21 | Handling connection for 60246
  60.7  57 | Connection to 127.0.0.1 closed by remote host.
  60.7 TEL | [57] exit 255 in 0.61 secs.
  61.0 TEL | [58] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 60246 telepresence@127.0.0.1 /bin/true
  61.0  21 | Handling connection for 60246
  61.6  58 | Connection to 127.0.0.1 closed by remote host.
  61.6 TEL | [58] exit 255 in 0.65 secs.
  62.8 TEL | [59] Running: sudo -n echo -n
  62.9 TEL | [59] ran in 0.04 secs.

```

**Comment by machine424** [comment]
AFAIK (for K8s and also for OpenShift) using `--swap-deployment`, Telepresence proxy deployment will use the old deployment's `spec.containers[].resources`; if pods of postgres-gis are already running in the cluster there is no reason for this resources problem. I think the problem occurs when you tried to use `--new-deployment`, in this case, the resources are set to `"--limits=cpu=100m,memory=256Mi",
        "--requests=cpu=25m,memory=64Mi` to avoid the problem you can customize and deploy your own Telepresence proxy deployment using `--doplyment` (see https://www.telepresence.io/reference/connecting --> Running Telepresence manually)

**Comment by donnyyung** [comment]
I think we don't currently have memory limits for the agent or traffic-manager in Telepresence 2 so we should add this.
