### ISSUE TITLE
docker-run not working SSH from local container to the cluster failed to start.

### ISSUE THREAD

**Issue by yelhouti** [telepresenceio/telepresence#1036]
### What were you trying to do?

(please tell us)
Run a container inside the cluster

### What did you expect to happen?
For it run
(please tell us)

### What happened instead?
It failed miserably :)
(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--docker-run', '--rm', 'dbmigration:latest']`
Version: `0.99`
Python version: `3.6.8 (default, Jan 31 2019, 09:38:34) 
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]`
kubectl version: `Client Version: v1.13.4 // Server Version: v1.14.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux yelhouti-p52 4.20.14-100.fc28.x86_64 #1 SMP Tue Mar 5 19:45:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 95, in launch
    mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 155, in run_docker_command
    raise RuntimeError("SSH to the network container failed to start.")
RuntimeError: SSH to the network container failed to start.

```

Logs:

```
27 |   29.6 TEL | [117] exit 255 in 0.01 secs.
  38.7  27 |   29.9 TEL | [118] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  38.7  27 |   29.9 TEL | [118] exit 255 in 0.01 secs.
  38.7  27 | Traceback (most recent call last):
  38.7  27 |   File "/usr/bin/entrypoint.py", line 127, in <module>
  38.7  27 |     main()
  38.7  27 |   File "/usr/bin/entrypoint.py", line 65, in main
  38.7  27 |     proxy(loads(sys.argv[2]))
  38.7  27 |   File "/usr/bin/entrypoint.py", line 83, in proxy
  38.7  27 |     "SSH from local container to the cluster failed to start."
  38.7  27 | RuntimeError: SSH from local container to the cluster failed to start.
  38.7  27 | [INFO  tini (1)] Main child exited normally (with status '1')
  38.8 TEL | [29] exit 255 in 30.15 secs.
  38.9 TEL | [27] Network container: exit 1
  39.7 TEL | (proxy checking local liveness)
  39.7  19 | 2019-05-30T00:27:14+0000 [Poll#info] Checkpoint

```

Not that swap deployement, run, run-shell and other commands work perfectly
Also, I tried disabling firewalld which fails when trying to add the Iptables rule, and with firewalld up after adding `sudo firewall-cmd --permanent --zone=trusted --add-source=172.17.0.0/16` and reload as described in the doc

**Comment by ark3** [comment]
Sorry about the crash. Can you please pass along a full telepresence.log as described above? I'm curious to see what `sshuttle` has to say... Thank you!

**Comment by yelhouti** [comment]
@ark3 thanks in advance for the help.
https://gist.github.com/yelhouti/dca1772fac21672c55e0788cc476bf5c

**Comment by yelhouti** [comment]
@ark3 sorry for repinging, could you check please?

**Comment by ark3** [comment]
Sorry I didn't get to this in time for the 0.100 release. It looks like the `ssh` call in SSH.wait(...) needs a timeout. That might not solve your problem, but it will get us some more information about what's going on. Let me get back to you.

**Comment by ark3** [comment]
Release 0.101 adds a timeout that may solve this, or otherwise will reveal more information about why it might be failing.

**Comment by yelhouti** [comment]
@ark3 it solved it, thanks :)

**Comment by ark3** [comment]
Excellent. Thank you for the bug report!
