### ISSUE TITLE
Telepresence --quiet - Quietly run process?

### ISSUE THREAD

**Issue by DandyDeveloper** [telepresenceio/telepresence#1061]
I'm trying to open a Telepesence process inside of a Golang application using a `tcp-vpn`. 

This is to help improve my overall development process when debugging. 

To confirm: `go app -> tele -> vpn` is the workflow. 

I'm struggling to get this working as the process is being closed by my app due to the behaviors in Telepresence (opening a new terminal as a session). 

I can work around this, but has there been any interest in creating a "quiet" session through Telepresence? 

Calling something like `telepresence --context=test --method=vpn-tcp --quiet` 

Essentially running the process, then detaching from the session, whilst maintaining the VPN.

**Comment by ark3** [comment]
Yes, there has been discussion around this sort of thing, and [https://github.com/datawire/teleproxy](Teleproxy) kind of gets you there. Another workaround is to use something like `telepresence --run sleep 100000 &` to set up the outbound VPN. Can you comment on #455 as well?

**Comment by DandyDeveloper** [comment]
@ark3 I've added my thoughts, Teleproxy might actually do the job based on the README. 

Right now we have some pretty basic requirements for how we want to implement this in our dev workflow, so Teleproxy might even be overkill, but definitely has its place.

**Comment by DandyDeveloper** [comment]
@ark3 Do you ant me to close this?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
