### ISSUE TITLE
Telepresence is getting killed and crashes

### ISSUE THREAD

**Issue by fredmaggiowski** [telepresenceio/telepresence#1064]
### What were you trying to do?

Swap a container, running a simple nginx service, inside a pod by using `swap-deployment` and running a local docker image. 

### What did you expect to happen?

I expect it to actually swap the container and receive connections on my local running container.

### What happened instead?

It crashes and in the cluster I see the following log:

```
root -> telepresence
Killed
```

### Automatically included information

Command line: `['/usr/bin/telepresence', '--namespace', 'demo', '--swap-deployment', 'api-gateway:api-gateway', '--expose', '8080', '--expose', '8081', '--docker-run', 'dockerhub.local/core/api-gateway:4.0.0']`
Version: `0.101`
Python version: `3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]`
kubectl version: `Client Version: v1.15.0 // Server Version: v1.13.6-gke.13`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux rhyno 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 66, in main
    env, pod_info = get_remote_env(runner, ssh, remote_info)
  File "/usr/bin/telepresence/telepresence/remote_env.py", line 34, in get_remote_env
    remote_info.container_name, "--", "python3", "podinfo.py"
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 445, in get_output
    env,
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 399, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['kubectl', '--context', 'gke_mia-platform-pre-prod_europe-west1-d_mia-test', '--namespace', 'demo', 'exec', 'api-gateway-d216efdc531242b6865457cfd4db6cf3-68b5cc547f-wfhnt', '--container', 'api-gateway', '--', 'python3', 'podinfo.py']' returned non-zero exit status 1.

```

Logs:

```
 8080.
  15.4 >>> | Forwarding remote port 8081 to local port 8081.
  15.4 >>> | 
  15.4 TEL | Launching Web server for proxy poll
  15.4 TEL | [34] Launching SSH port forward (socks and proxy poll): ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 36121 telepresence@127.0.0.1 -L127.0.0.1:42537:127.0.0.1:9050 -R9055:127.0.0.1:33675
  15.4 TEL | END SPAN connect.py:36(connect)    3.4s
  15.4 TEL | BEGIN SPAN remote_env.py:28(get_remote_env)
  15.4 TEL | [35] Capturing: kubectl --context gke_mia-platform-pre-prod_europe-west1-d_mia-test --namespace demo exec api-gateway-d216efdc531242b6865457cfd4db6cf3-68b5cc547f-wfhnt --container api-gateway -- python3 podinfo.py
  15.5  25 | Handling connection for 36121
  16.0  35 | Error from server:
  16.0 TEL | [35] exit 1 in 0.55 secs.
  16.0 TEL | END SPAN remote_env.py:28(get_remote_env)    0.6s
  16.2 TEL | [34] SSH port forward (socks and proxy poll): exit 255

```

**Comment by ark3** [comment]
Sorry about the crash! That's a new one for me. Does this happen every time you run Telepresence?

In short, Telepresence is launching this command to grab the pod's environment and configuration:

    kubectl ... exec <pod name> ... -- python3 podinfo.py

and that command is failing. The output is "Error from server:" and then it gets killed.

Can you try replicating this manually to see what happens? Here's how that looks for me; I'm curious to see what happens for you.

```console
$ # Create a Tel deployment

$ kubectl run tel-experiment --image=datawire/telepresence-k8s:0.101 --restart=Always -l telepresence=experiment
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/tel-experiment created

$ # Figure out the pod name

$ kubectl get pods -l telepresence
NAME                              READY   STATUS    RESTARTS   AGE
tel-experiment-65dc864db8-mvw98   1/1     Running   0          20s

$ # Try the kubectl exec

$ kubectl exec tel-experiment-65dc864db8-mvw98 -- python3 podinfo.py
{"env": {"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/b [... JSON blob ...]

$ # Clean up

$ kubectl delete deployment -l telepresence=experiment
deployment.extensions "tel-experiment" deleted
```

Thank you for your help.

**Comment by kregan77** [comment]
@ark3 is there a possibility of a timing issue here?  I'm running into the same thing but I believe there may be some latency issues involved.  If I try to swap out a deployment with telepresence I get the same error as in the original description, but telepresence conveniently pauses and asks me if I want to report the issue, during which time I can run the podinfo.py command against the telepresence pod and it works... i wonder if it's a matter of telepresence not giving enough time for the pod to come up or something?

**Comment by ark3** [comment]
Could you pass along the telepresence.log for your session? Including your manual podinfo run? In other words:

1. Launch Telepresence
2. Tel crashes and waits for you
3. In another window, run `kubectl exec ... podinfo.py`
4. Say "no" to the crash reporter
5. Tel cleans up and quits
6. Share the telepresence.log file as a GitHub Gist

Thank you!

**Comment by kregan77** [comment]
@ark3  so I was attempting this just now, but this time when I manually ran the podinfo script it failed in the same way that telepresence logged with a 137 return code.  It definitely succeeded when I did this last week and returned a bunch of pod info.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
