### ISSUE TITLE
eval $(minikube docker-env) & telepresence wan't work

### ISSUE THREAD

**Issue by bondvt04** [telepresenceio/telepresence#1066]
Recently I tried to run `eval $(minikube docker-env)` and than `telepresence --swap-deployment tasker4-deployment --docker-run --rm -it -v $(pwd):/usr/src/app tasker4-api:latest` and had an error.

Why do I need that eval? https://stackoverflow.com/questions/42564058/how-to-use-local-docker-images-with-minikube?rq=1

### "Stack"
➜  tasker4 git:(master) ✗ ./run-telepresence.sh
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment tasker4-deployment with a proxy
T: Forwarding remote port 3015 to local port 3015.

Looks like there's a bug in our code. Sorry about that!

Background process (Network container) exited with return code 125. Command was:
  docker run --publish=127.0.0.1:54607:38022/tcp --hostname=tasker4-deploymen-bf68ac8cef744e9dbe57bf822b5b0525-66dddd8hkvv2 --dns=10.96.0.10 --dns-search=default.svc.cluster.local --dns-search=svc.cluster.local --dns-search=cluster.local --dns-opt=ndots:5 --rm --privileged --name=telepresence-1561903902-671731-30718 datawire/telepresence-local:0.100 proxy '{"cidrs": ["0/0"], "expose_ports": [[3015, 3015]]}'

Recent output was:
  docker: Post http://192.168.99.100:2376/v1.39/containers/create?name=telepresence-1561903902-671731-30718: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16".
  * Are you trying to connect to a TLS-enabled daemon without TLS?.
  See 'docker run --help'.

Here are the last few lines of the logfile (see /Users/bondvt04/www/tasker4/telepresence.log for the complete logs):

   4.3 TEL | [27] ran in 0.17 secs.
   4.3 TEL | END SPAN mount.py:32(mount_remote_volumes)    0.2s
   4.3 TEL | BEGIN SPAN container.py:139(run_docker_command)
   4.3 TEL | [28] Launching Network container: docker run --publish=127.0.0.1:54607:38022/tcp --hostname=tasker4-deploymen-bf68ac8cef744e9dbe57bf822b5b0525-66dddd8hkvv2 --dns=10.96.0.10 --dns-search=default.svc.cluster.local --dns-search=svc.cluster.local --dns-search=cluster.local --dns-opt=ndots:5 --rm --privileged --name=telepresence-1561903902-671731-30718 datawire/telepresence-local:0.100 proxy '{"cidrs": ["0/0"], "expose_ports": [[3015, 3015]]}'
   4.3 TEL | [29] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54607 root@127.0.0.1 /bin/true
   4.4 TEL | [29] exit 255 in 0.02 secs.
   4.5  28 | docker: Post http://192.168.99.100:2376/v1.39/containers/create?name=telepresence-1561903902-671731-30718: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16".
   4.5  28 | * Are you trying to connect to a TLS-enabled daemon without TLS?.
   4.5  28 | See 'docker run --help'.
   4.5 TEL | [28] Network container: exit 125
   4.6 TEL | [30] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54607 root@127.0.0.1 /bin/true
   4.6 TEL | [30] exit 255 in 0.02 secs.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'tasker4-deployment', '--docker-run', '--rm', '-it', '-v', '/Users/bondvt04/www/tasker4:/usr/src/app', 'tasker4-api:latest']`
Version: `0.100`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.14.1 // Server Version: v1.14.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Anatoliys-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

```
Background process (Network container) exited with return code 125. Command was:
  docker run --publish=127.0.0.1:54607:38022/tcp --hostname=tasker4-deploymen-bf68ac8cef744e9dbe57bf822b5b0525-66dddd8hkvv2 --dns=10.96.0.10 --dns-search=default.svc.cluster.local --dns-search=svc.cluster.local --dns-search=cluster.local --dns-opt=ndots:5 --rm --privileged --name=telepresence-1561903902-671731-30718 datawire/telepresence-local:0.100 proxy '{"cidrs": ["0/0"], "expose_ports": [[3015, 3015]]}'

Recent output was:
  docker: Post http://192.168.99.100:2376/v1.39/containers/create?name=telepresence-1561903902-671731-30718: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16".
  * Are you trying to connect to a TLS-enabled daemon without TLS?.
  See 'docker run --help'.
```

Logs:

```
ult.svc.cluster.local --dns-search=svc.cluster.local --dns-search=cluster.local --dns-opt=ndots:5 --rm --privileged --name=telepresence-1561903902-671731-30718 datawire/telepresence-local:0.100 proxy '{"cidrs": ["0/0"], "expose_ports": [[3015, 3015]]}'
   4.3 TEL | [29] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54607 root@127.0.0.1 /bin/true
   4.4 TEL | [29] exit 255 in 0.02 secs.
   4.5  28 | docker: Post http://192.168.99.100:2376/v1.39/containers/create?name=telepresence-1561903902-671731-30718: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16".
   4.5  28 | * Are you trying to connect to a TLS-enabled daemon without TLS?.
   4.5  28 | See 'docker run --help'.
   4.5 TEL | [28] Network container: exit 125
   4.6 TEL | [30] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54607 root@127.0.0.1 /bin/true
   4.6 TEL | [30] exit 255 in 0.02 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! You are seeing the effects of #873. Given the way Telepresence works, using a non-local Docker daemon cannot work. Can you run your Telepresence command in a shell that doesn't have the Minikube docker-env setup?

**Comment by bondvt04** [comment]
Yep, seems it is possible. Seems I used telepresence in the way it is not designed. I have created some of images manually (docker build -t <name> <dockerfile>) and used minikube docker-env setup so it can find my images locally instead of pulling it from internet. And I used pods with containers built basing on such images along with other pods, created by telepresence

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
