### ISSUE TITLE
RuntimeError: SSH to the network container failed to start.

### ISSUE THREAD

**Issue by david-moven** [telepresenceio/telepresence#1069]
### What were you trying to do?

Connect to a remote k8s cluster using telepresence. Remote connection fulfilled by `export KUBECONFIG=…`

### What did you expect to happen?

Ping a service’s endpoint

### What happened instead?

I was told to expose a port — however, I don’t want to be mucking around in the kubeconf.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--docker-run', '--rm', '-it', 'pstauffer/curl', 'curl', 'http://td-verifier:5050/ping']`
Version: `0.101`
Python version: `3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.15.0 // Server Version: v1.12.8`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Davids-Macbook-Pro-15-Retina 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 120, in launch
    mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 155, in run_docker_command
    raise RuntimeError("SSH to the network container failed to start.")
RuntimeError: SSH to the network container failed to start.

```

Logs:

```
5] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 49763 root@127.0.0.1 /bin/true
  42.5 TEL | [145] exit 255 in 0.02 secs.
  42.8 TEL | [146] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 49763 root@127.0.0.1 /bin/true
  42.8 TEL | [146] exit 255 in 0.01 secs.
  43.0 TEL | [147] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 49763 root@127.0.0.1 /bin/true
  43.0 TEL | [147] exit 255 in 0.01 secs.
  43.3 TEL | [148] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 49763 root@127.0.0.1 /bin/true
  43.3 TEL | [148] exit 255 in 0.01 secs.
  43.6 TEL | [149] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 49763 root@127.0.0.1 /bin/true
  43.6 TEL | [149] exit 255 in 0.01 secs.
  44.2 TEL | (proxy checking local liveness)
  44.2  28 | 2019-07-08T11:48:56+0000 [Poll#info] Checkpoint

```

**Comment by ark3** [comment]
Sorry about the crash. Can you please pass along the full telepresence.log as a GitHub Gist? Thank you.
