### ISSUE TITLE
Telepresence shell crashes directly after start

### ISSUE THREAD

**Issue by sudoapt-getclean** [telepresenceio/telepresence#1071]
### What were you trying to do?
I was trying to start a remote shell to do some debugging

### What did you expect to happen?
get a bash prompt where I could do some curl queries

### What happened instead?
Things crashed instantly

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--method=inject-tcp']`
Version: `0.101`
Python version: `3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]`
kubectl version: `Client Version: v1.15.0 // Server Version: v1.11.8-eks-7c34c0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux senna 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 50, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 99, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 69, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ed Error
  15.6  14 | 	Traceback (most recent call last):
  15.6  14 | 	Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: google.com.
  15.6  14 | 
  15.6  27 | Traceback (most recent call last):
  15.6  27 |   File "<string>", line 1, in <module>
  15.6  27 | socket.gaierror: [Errno -4] Non-recoverable failure in name resolution
  15.7 TEL | [27] exit 1 in 5.20 secs.
  15.8 TEL | [28] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  20.9  14 | 2019-07-09T11:47:11+0000 [-] Unhandled Error
  20.9  14 | 	Traceback (most recent call last):
  20.9  14 | 	Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: google.com.
  20.9  14 | 
  21.0  28 | Traceback (most recent call last):
  21.0  28 |   File "<string>", line 1, in <module>
  21.0  28 | socket.gaierror: [Errno -4] Non-recoverable failure in name resolution
  21.0 TEL | [28] exit 1 in 5.21 secs.
  21.0 TEL | END SPAN local.py:42(set_up_torsocks)   11.9s

```

**Comment by ark3** [comment]
Sorry about the crash. Does your cluster allow access to google.com? Telepresence checks for connectivity by accessing that site.

**Comment by sudoapt-getclean** [comment]
Normally It does,.. but I was actually starting telepresence to debug some connectivity issues. It would be great if that was also possible :-)

**Comment by ark3** [comment]
Agreed! Please keep an eye on issues #389 and #985.

**Comment by sudoapt-getclean** [comment]
I like #985 and it's suggestions. However in this case and in the case of #389 I think there could also be acceptable default behaviour if telepresence simply completes starting and warns that there is no connectivity.

You're welcome to close this issue if you feel it will be solved bij 389 or for any other reason.
thanx for the tool! I'm really happy with it.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
