### ISSUE TITLE
Error after installing from source

### ISSUE THREAD

**Issue by jobomix** [telepresenceio/telepresence#1072]
### What were you trying to do?
`telepresence --docker-run --rm -it pstauffer/curl curl http://hello-world:8000/`

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/home/nono/.local/bin/telepresence', '--docker-run', '--rm', '-it', 'pstauffer/curl', 'curl', 'http://hello-world:8000/']`
Version: `0.101`
Python version: `3.6.5 (default, Jan 17 2019, 09:15:39) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.13.7 // Server Version: v1.15.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux nonos-gentoo 4.19.44-gentoo #2 SMP Wed Jul 10 09:59:00 BST 2019 x86_64 Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz GenuineIntel GNU/Linux`

```
Traceback (most recent call last):
  File "/home/nono/.local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/home/nono/.local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/home/nono/.local/bin/telepresence/telepresence/outbound/setup.py", line 120, in launch
    mount_dir, pod_info
  File "/home/nono/.local/bin/telepresence/telepresence/outbound/container.py", line 169, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/home/nono/.local/bin/telepresence/telepresence/runner/runner.py", line 424, in check_call
    env,
  File "/home/nono/.local/bin/telepresence/telepresence/runner/runner.py", line 399, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1562751590-7568362-14044', '--rm', 'datawire/telepresence-local:0.101', 'wait']' returned non-zero exit status 1.

```

Logs:

```
 18.0  20 | 2019-07-10T09:40:00+0000 [-] SOCKSv5Factory starting on 9050
  18.0  20 | 2019-07-10T09:40:00+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f7d430842b0>
  18.0  20 | 2019-07-10T09:40:00+0000 [-] DNSDatagramProtocol starting on 9053
  18.0  20 | 2019-07-10T09:40:00+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f7d43084668>
  18.0  20 | 2019-07-10T09:40:00+0000 [-] Loaded.
  18.0  20 | 2019-07-10T09:40:00+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.2.1 (/usr/bin/python3.6 3.6.8) starting up.
  18.0  20 | 2019-07-10T09:40:00+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  30.5 TEL | [33] Running: sudo -n echo -n
  30.5 TEL | [33] ran in 0.02 secs.
  41.4  32 | Failed to connect to proxy in remote cluster.
  41.4  32 | [INFO  tini (1)] Main child exited normally (with status '1')
  41.7 TEL | [32] exit 1 in 31.84 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. Could you please pass along the full telepresence.log as a GitHub Gist? Thank you.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
