### ISSUE TITLE
using checkpoint security vpn

### ISSUE THREAD

**Issue by MazyNoc** [telepresenceio/telepresence#1073]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.101`
Python version: `3.7.3 (default, Jun 19 2019, 07:38:49) 
[Clang 10.0.1 (clang-1001.0.46.4)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Mikaels-laptop.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 98, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 312, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
 timed out after 1.01 secs.
  51.1 TEL | Wait for vpn-tcp connection: hellotelepresence-13
  51.1 TEL | [56] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-13")'
  51.2  28 | c : DNS request from ('10.170.0.30', 58557) to None: 53 bytes
  51.2  20 | 2019-07-11T18:50:23+0000 [stdout#info] Result for b'hellotelepresence-13.intra.local.ch' is ['127.0.0.1']
  52.2  28 | c : DNS request from ('10.170.0.30', 58557) to None: 53 bytes
  52.2  20 | 2019-07-11T18:50:24+0000 [stdout#info] Result for b'hellotelepresence-13.intra.local.ch' is ['127.0.0.1']
  56.2 TEL | [56] timed out after 5.02 secs.
  56.2 TEL | [57] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-13.a.sanity.check.telepresence.io")'
  56.2  28 | c : DNS request from ('10.170.0.30', 57972) to None: 69 bytes
  56.2  20 | 2019-07-11T18:50:28+0000 [stdout#info] Sanity check: b'hellotelepresence-13.a.sanity.check.telepresence.io'
  57.2 TEL | [57] timed out after 1.01 secs.

```

**Comment by ark3** [comment]
Yes, [as documented](https://www.telepresence.io/reference/methods#limitations---method-vpn-tcp), the default vpn-tcp method is not compatible with other VPNs. Perhaps the [container method](https://www.telepresence.io/tutorials/docker) would work well for you?
