### ISSUE TITLE
Mac: Fails to replace container in docker-for-desktop

### ISSUE THREAD

**Issue by amarchen** [telepresenceio/telepresence#1080]
### What were you trying to do?

Trying to replace a kubernetes deployment (actually running in docker-for-desktop) with another docker image I have built and tagged locally.

We are developing in groovy, my colleague struggles to build-run on windows, but our code runs fine inside kubernetes on his machine, so I was trying to set up a process for building a debug-enabled version of the image, putting it to k8s and attaching debugger to it. I was doing it on a Mac, he would repeat it on Windows.

I've built image successfully and now was trying to swap one running in docker-for-desktop with the freshly built one.

### What did you expect to happen?

docker-for-desktop run deployment to be replaced with a proxy, my image would run in the local docker and telepresence would somehow make a bridge between these.

### What happened instead?

Well, command line results in the failure output below.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'adminservice', '--namespace', 'services', '--docker-run', '--rm', '-p', '5005:5005', 'adminservice-dev:2019-07-19-1']`
Version: `0.101`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.10.2 // Server Version: v1.10.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin artemlumoa 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`

```
Background process (Network container) exited with return code 125. Command was:
  docker run -p=5005:5005 --publish=127.0.0.1:54138:38022/tcp --hostname=adminservice-2f24a599faa94781825c695f83a3feec-867ddd697b-mg5fh --dns=10.96.0.10 --dns-search=services.svc.cluster.local --dns-search=svc.cluster.local --dns-search=cluster.local --dns-opt=ndots:5 --rm --privileged --name=telepresence-1563548177-2697449-46080 datawire/telepresence-local:0.101 proxy '{"cidrs": ["0/0"], "expose_ports": []}'

Recent output was:
  f5524d020c2a: Download complete
  ca0928ee1da4: Download complete
  f5524d020c2a: Pull complete
  66f2a191dd59: Pull complete
  59e7ceedd2c6: Pull complete
  3e4fd5946f74: Pull complete
  ca0928ee1da4: Pull complete
  Digest: sha256:fdff63a745522dc14a54ce6693d5547c952255634d3efe615792bb0a42c5c762
  Status: Downloaded newer image for datawire/telepresence-local:0.101
  docker: Error response from daemon: driver failed programming external connectivity on endpoint telepresence-1563548177-2697449-46080 (e5abf55b56fa14f38850cb4e28acb54538e14ae2714f3873fa877e2335aae207): Error starting userland proxy: Bind for 0.0.0.0:5005 failed: port is already allocated.
```

Logs:

```
55634d3efe615792bb0a42c5c762
  33.7  30 | Status: Downloaded newer image for datawire/telepresence-local:0.101
  33.7 TEL | [54] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54138 root@127.0.0.1 /bin/true
  33.7 TEL | [54] exit 255 in 0.03 secs.
  34.0 TEL | [55] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54138 root@127.0.0.1 /bin/true
  34.0 TEL | [55] exit 255 in 0.03 secs.
  34.2  30 | docker: Error response from daemon: driver failed programming external connectivity on endpoint telepresence-1563548177-2697449-46080 (e5abf55b56fa14f38850cb4e28acb54538e14ae2714f3873fa877e2335aae207): Error starting userland proxy: Bind for 0.0.0.0:5005 failed: port is already allocated.
  34.2 TEL | [30] Network container: exit 125
  34.3 TEL | [56] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54138 root@127.0.0.1 /bin/true
  34.3 TEL | [56] exit 255 in 0.03 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! The last line of output from Docker says that it tried to bind to your port but failed because that port is already in use:

```
docker: 
 Error response from daemon: 
  driver failed programming external connectivity on endpoint telepresence-1563548177-2697449-46080 (e5abf55b56fa14f38850cb4e28acb54538e14ae2714f3873fa877e2335aae207): 
   Error starting userland proxy: 
    Bind for 0.0.0.0:5005 failed: 
     port is already allocated.
```

Telepresence should report this error clearly rather than crashing.

Anyhow, does this information help you get things running? Maybe you have another process or container using that port already.

**Comment by amarchen** [comment]
Ah, stupid me, indeed the port is already taken indeed and the reason was there in the crash lines :(
Would be great to have a cleaner exit code from telepresence indeed.

**Comment by amarchen** [comment]
Shall I/we change the issue title to something like "Ugly crash instead of a neat message if --docker-run fails to bind the port"?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
