### ISSUE TITLE
Connection to Azure AKS doesn't work

### ISSUE THREAD

**Issue by ElliotJH** [telepresenceio/telepresence#1086]
### What were you trying to do?

I've started a Kubernetes cluster on Azure's AKS service. I was trying to use telepresence
 to work with a silly little service I uploaded to it - mostly just to try it out.

### What did you expect to happen?

Telepresence would set up its proxy.

### What happened instead?

I see the telepresence pod appear in the kubernetes dashoard, but after some pause, the below error occurs.

I've tried quite a few times, please see long log here https://gist.github.com/ElliotJH/f7e4252ba435948663b25993b06634cd

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run', 'curl', 'http://mazes-mazes:8080/']`
Version: `0.101`
Python version: `3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin elliots-mbp.lan 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 98, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 312, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
et.gethostbyname("hellotelepresence-13.a.sanity.check.telepresence.io")'
  49.1 TEL | [56] timed out after 1.01 secs.
  49.2 TEL | Wait for vpn-tcp connection: hellotelepresence-14
  49.2 TEL | [57] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-14")'
  50.5 TEL | (proxy checking local liveness)
  50.6  17 | 2019-07-31T23:23:31+0000 [Poll#info] Checkpoint
  54.2 TEL | [57] timed out after 5.02 secs.
  54.2 TEL | [58] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-14.a.sanity.check.telepresence.io")'
  55.2 TEL | [58] timed out after 1.02 secs.
  55.3 TEL | Wait for vpn-tcp connection: hellotelepresence-15
  55.3 TEL | [59] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-15")'
  60.3 TEL | [59] timed out after 5.01 secs.
  60.3 TEL | [60] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-15.a.sanity.check.telepresence.io")'
  61.3 TEL | [60] timed out after 1.01 secs.

```

I really appreciate this being an open project, let me know if there's anything more I can do help debug.

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
