### ISSUE TITLE
Permit the use of --listen flag on sshuttle-telepresence for making a telepresence node a router

### ISSUE THREAD

**Issue by M0nsieurChat** [telepresenceio/telepresence#1088]
Hi there,

Thanks for your awesome product !

The way we use telepresence is that instead of having everyone run telepresence on their desktop (which can be hard because of kubectl / kubeconfig requirement when the person is not really a developer), we run only one telepresence node on one of our router.

The way it originally works with sshuttle is to introduce the flag `--listen 0.0.0.0:0`  (more documentation : https://sshuttle.readthedocs.io/en/stable/manpage.html#cmdoption-sshuttle-l )
By running the following command (custom telepresence build), we permit everyone to access our clusters service IP range (by defining one big static route on our router to the telepresence node)
```
python3 /usr/local/bin/sshuttle-telepresence -l 0.0.0.0:0 -v --dns --method nat -e ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r telepresence@127.0.0.1:34541 --to-ns 127.0.0.1:9053 10.100.6.0/24 10.100.0.0/24 10.110.0.0/21 10.100.3.0/24 10.100.1.0/24 10.100.7.0/24 10.100.2.0/24
```

Our hack in order to be able to use the `--listen` flag is really dirty.  It would be neat to add this possibility directly in the `teleport` binary instead.

**Comment by donnyyung** [comment]
Telepresence 2 no longer uses sshuttle, so I don't think this issue still applies. Telepresence has been re-architected https://www.telepresence.io/docs/latest/reference/architecture/ which may work better for the permission model you desire. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
