### ISSUE TITLE
Test Homebrew, Ubuntu and Fedora repositories

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#109]
The package repositories are not automatically tested at the moment: there is no validation that uploaded packages/releases are installable.

**Comment by donnyyung** [comment]
We should still do this for Telepresence 2.

**Comment by itamarst** [comment]
For what it's worth in a different project (https://pythonspeedcom/fil) I ended up releasing packages that segfaulted even though all end to end tests passed in CI due to problem with packaging-specific build process, so this is worth doing.
