### ISSUE TITLE
Cannot start telepresence in wsl due to iptables issue

### ISSUE THREAD

**Issue by yangyang919** [telepresenceio/telepresence#1091]
**What were you trying to do?**
I was trying to launch telepresence to proxy remote cluster

**What did you expect to happen?**
Proxy success

**What happened instead?**
T: Quick test of iptables failed:

**Automatically included information**
Command line: ['/usr/local/bin/telepresence']
Version: 0.101
kubectl version: Client Version: v1.10.11 // Server Version: v1.10.11
WSL ubuntu version: 18.04

**Logs:**
yangyang@WDFV41000454D:~$ telepresence
T: How Telepresence uses sudo: https://www.telepresence.io/reference/install#dependencies
T: Invoking sudo. Please enter your sudo password.
[sudo] password for yangyang:
T: Quick test of iptables failed:

> sudo iptables --list
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

T: The vpn-tcp method requires the use of iptables. If you're running Telepresence in a container, add network capabilities (docker run ...
T: --cap-add=NET_ADMIN --cap-add=NET_BIND_SERVICE ...) or use a privileged container (docker run ... --privileged ...).

T: Unable to use iptables

**Comment by ark3** [comment]
Sorry about that. See https://github.com/telepresenceio/telepresence/issues/595#issuecomment-381664067. In short, Tel used to crash on Windows by default (ugh). Now it fails with a misleading `iptables` error. 

Tel should really default to the inject-tcp method or to the container method on Windows, since those two methods work.

**Comment by dmeytin** [comment]
Any news on that?

**Comment by ark3** [comment]
To clarify, all I'll be fixing is the error message and possibly the default. Even now you can use `--method inject-tcp` or `--docker-run` with WSL.

**Comment by ark3** [comment]
Note that the WSL check in runner.py really only checks for WSL1. Perhaps the log file should indicate that more clearly.

See also https://github.com/microsoft/WSL/issues/4555 for some discussion on how to detect WSL 1 and 2.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
