### ISSUE TITLE
Allow Telepresence to set the serviceAccount or serviceAcountName that is used by a deployment.

### ISSUE THREAD

**Issue by billmcmath** [telepresenceio/telepresence#1093]
**Feature Request:**
Allow the service account to be set on a new deployment.

**Rational:**
We purposely run cluster that doesn't have enough permissions on the default service account to launch a new deployment or service.  This would allow Telepresence to start pods in our cluster.

**Comment by omeid** [comment]
As there is a pull request for this, any chance it could be moved from todo? :)
