### ISSUE TITLE
Telepresense installation on RHEL7 seems a issue

### ISSUE THREAD

**Issue by LahiriBellarykar** [telepresenceio/telepresence#1095]
I am trying to install telepresence on RHEL7. I do not see that telepresence supports RHEL. RHEL is one of the most commonly used flavors in the industry. Hope the telepresence starts supporting it soon

**Comment by ark3** [comment]
Agreed! See also https://github.com/telepresenceio/telepresence/issues/719#issuecomment-409619248. In short, we could use your help with this.

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
