### ISSUE TITLE
Allow Telepresence to specify nodeSelector on proxy deployment when using --swap-deployment

### ISSUE THREAD

**Issue by tenitski** [telepresenceio/telepresence#1096]
We are considering using Telepresence in EKS with most of the nodes running on spot instances. Due to the nature of these type of instances, pods are often moved from one node to another by Kubernetes. 

The problem is that if you have Telepresence proxy deployment moved that disrupts the session created with `--swap-deployment` or `--new-deployment`.

A way to solve it could be by adding a flag to Telepresence specifying `nodeSelector` for proxy deployments (https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector). This would allow to run proxy deployments on a long lived non spot EC2 instance, and all other deployments would go onto more ephemeral spot nodes.

**Comment by morganchristiansson** [comment]
Supporting nodeSelector allows us to run pods in correct subnet that has correct connectivity.

can node selector support be added

**Comment by peidong-hu** [comment]
I need this feature too due to some restriction on my k8s cluster subnet.

**Comment by billmcmath** [comment]
I've added a PR for this [1227](https://github.com/telepresenceio/telepresence/pull/1227) as I need it too.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
