### ISSUE TITLE
hostAlias entries are not working in a local docker container injected with --swap-deployment

### ISSUE THREAD

**Issue by MFAshby** [telepresenceio/telepresence#1097]
Steps to reproduce:
Have a kubernetes deployment with some hostAliases configured https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

When you run telepresence with --swap-deployment, the hostAliases are not preserved, so the application running locally cannot use them.

**Comment by MFAshby** [comment]
hmm, looks like they should be, see https://github.com/telepresenceio/telepresence/blob/0d9f33e77e09191c23c4880272c8e8a7d9365554/telepresence/proxy/deployment.py#L281

Not sure why this isn't working

**Comment by MFAshby** [comment]
seems it is, but for some reason the application can't use the host alias.

**Comment by MFAshby** [comment]
Possibly the proxy container that's deployed in the cluster doesn't check it's /etc/hosts file. 

https://github.com/telepresenceio/telepresence/blob/master/k8s-proxy/resolver.py

**Comment by MFAshby** [comment]
I think it's specific to using --docker-run. If I run a local shell using --swap-deployment, I can do `nslookup` and results are returned from the hostAlias entry. If I run a local docker container using --docker-run, and execute nslookup from within that, then the results are not returned.

**Comment by charliecatney** [comment]
I have the same issue, is there a fix or workaround.

Thanks

**Comment by MFAshby** [comment]
Workaround: instead of using a hostAlias entry, I deployed a proxy instance (haproxy) and exposed it to my cluster using a service.

**Comment by ark3** [comment]
To fix this for the container method we could either

1. Grab the proxy pod's `/etc/hosts` file like we do for `/etc/resolv.conf`
2. Process the hostAlias entries in the Pod spec

and then emit the appropriate `--add-host` arguments to `docker run` the way we do for the DNS stuff.

**Comment by charliecatney** [comment]
Pull request submitted.
