### ISSUE TITLE
docker-for-desktop port limitations

### ISSUE THREAD

**Issue by benmullin333** [telepresenceio/telepresence#1099]
Hi!

There's a confusing limitation that docker-for-destop on mac imposes.  It seems that it does not allow for a process within telepresence to run on the same port that a k8s service is running on.

So if I try to replace a deployment running on nodePort 9999 with `telepresence  --swap-deployment mydeployment --expose 9999 --run myserver-local-on-port-9999` it doesn't work.

I bring this up in hopes that others can save time and avoid this trap.  Maybe the docs could note?

The workaround is to run my proxied server through a different port: `telepresence  --swap-deployment mydeployment --expose 9998:9999 --run myserver-local-on-port-9998`
given the limitations with docker-for-destop k8s, I also need to restart my proxy which was exposing the service: `kubectl port-forward service/myservice 9799:9999`  so I can ultimately get to myservice at http://localhost:9799

**Comment by donnyyung** [comment]
I'm not sure if this is still an issue in docker-for-desktop, but adding an `exploration` and `v2` label for now so we can investigate further
