### ISSUE TITLE
Unexpected error, telepresence could not find pod

### ISSUE THREAD

**Issue by scottscott** [telepresenceio/telepresence#1100]
### What were you trying to do?

I was trying to temporarily replace a service on my dev machine with one that included my latest code changes.

### What did you expect to happen?

A successful swap.

### What happened instead?

Something went horribly wrong and you notified me at the command line that there was probably a bug on your end.
(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--context', 'minikube', '--namespace', 'dev', '--swap-deployment', 'app', '--method', 'inject-tcp', '--expose', '30002', '--expose', '31333', '--expose', '31334', '--run', 'yarn', 'run', 'develop']`
Version: `0.101`
Python version: `3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]`
kubectl version: `Client Version: v1.15.1 // Server Version: v1.15.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Scotts-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 102, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 211, in get_remote_info
    format(deployment_name)
RuntimeError: Telepresence pod not found for Deployment 'app-fd01994c37df4af2b5df449e21032684'.

```

Logs:

```
116.2 TEL | [119] Capturing: kubectl --context minikube --namespace dev get pod -o json --selector=telepresence=fd01994c37df4af2b5df449e21032684
 116.3 TEL | [119] captured in 0.07 secs.
 117.3 TEL | [120] Capturing: kubectl --context minikube --namespace dev get pod -o json --selector=telepresence=fd01994c37df4af2b5df449e21032684
 117.4 TEL | [120] captured in 0.07 secs.
 118.4 TEL | [121] Capturing: kubectl --context minikube --namespace dev get pod -o json --selector=telepresence=fd01994c37df4af2b5df449e21032684
 118.4 TEL | [121] captured in 0.07 secs.
 119.4 TEL | [122] Capturing: kubectl --context minikube --namespace dev get pod -o json --selector=telepresence=fd01994c37df4af2b5df449e21032684
 119.5 TEL | [122] captured in 0.07 secs.
 120.5 TEL | [123] Capturing: kubectl --context minikube --namespace dev get pod -o json --selector=telepresence=fd01994c37df4af2b5df449e21032684
 120.6 TEL | [123] captured in 0.07 secs.
 120.6 TEL | END SPAN remote.py:151(get_remote_info)  119.6s

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
