### ISSUE TITLE
Cannot access the host machine in container mode

### ISSUE THREAD

**Issue by mtp1376** [telepresenceio/telepresence#1104]
Hi and thanks for the awesome program,
I'm trying to attach to a python debugger server running on the host machine from my docker container which is running using the following command:
`telepresence --mount /tmp/known --expose 8000 --swap-deployment MY_DEPLOYMENT --docker-run MY_IMAGE`
But I can not ping `host.docker.internal` inside the container so the debugger running on computer is not reachable. Is there any workarounds about this?

**Comment by ark3** [comment]
See also https://github.com/telepresenceio/telepresence/issues/1022

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
