### ISSUE TITLE
11111

### ISSUE THREAD

**Issue by telzhou618** [telepresenceio/telepresence#1106]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--deployment', 'telepresence', '--namespace', 'dev']`
Version: `0.101`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.14.2 // Server Version: v1.14.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin localhost 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 60, in connect
    raise RuntimeError("SSH to the cluster failed to start.")
RuntimeError: SSH to the cluster failed to start.

```

Logs:

```
in/true
  31.0 TEL | [119] exit 255 in 0.05 secs.
  31.3 TEL | [120] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55244 telepresence@127.0.0.1 /bin/true
  31.3 TEL | [120] exit 255 in 0.03 secs.
  31.5 TEL | [121] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55244 telepresence@127.0.0.1 /bin/true
  31.6 TEL | [121] exit 255 in 0.02 secs.
  31.8 TEL | [122] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55244 telepresence@127.0.0.1 /bin/true
  31.9 TEL | [122] exit 255 in 0.03 secs.
  32.1 TEL | [123] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55244 telepresence@127.0.0.1 /bin/true
  32.1 TEL | [123] exit 255 in 0.01 secs.
  32.4 TEL | [124] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55244 telepresence@127.0.0.1 /bin/true
  32.4 TEL | [124] exit 255 in 0.02 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
