### ISSUE TITLE
Telepresence timeouts (and causes all DNS queries to timeout on the system)

### ISSUE THREAD

**Issue by JanMatas** [telepresenceio/telepresence#1107]
Thanks for maintaining this as an open project, it looks awesome. 

### What were you trying to do?

Run telepresence shell

### What did you expect to happen?

Shell to come up.

### What happened instead?

Telepresnece timeouted after some time, and also all DNS lookups failed on the system until telepresence command exited. 

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell']`
Version: `0.101`
Python version: `3.7.4 (default, Jul  9 2019, 18:14:44) 
[Clang 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.10.2 // Server Version: v1.12.7-gke.25`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Marinas-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 98, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 312, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
et.gethostbyname("hellotelepresence-13.a.sanity.check.telepresence.io")'
  49.8 TEL | [58] timed out after 1.01 secs.
  49.9 TEL | Wait for vpn-tcp connection: hellotelepresence-14
  49.9 TEL | [59] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-14")'
  50.8 TEL | (proxy checking local liveness)
  50.9  15 | 2019-09-03T13:44:06+0000 [Poll#info] Checkpoint
  54.9 TEL | [59] timed out after 5.01 secs.
  54.9 TEL | [60] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-14.a.sanity.check.telepresence.io")'
  55.9 TEL | [60] timed out after 1.01 secs.
  56.0 TEL | Wait for vpn-tcp connection: hellotelepresence-15
  56.0 TEL | [61] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-15")'
  61.0 TEL | [61] timed out after 5.02 secs.
  61.0 TEL | [62] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-15.a.sanity.check.telepresence.io")'
  62.0 TEL | [62] timed out after 1.01 secs.

```
Please let me know how to help with debugging or fixing the issue.

**Comment by yogiprogram** [comment]
Same issue happing for me

**Comment by yogiprogram** [comment]
@JanMatas did you got Solution?

**Comment by ark3** [comment]
Sorry about the crash. Could you try again with latest version and, if it still fails, pass along the full telepresence.log as a GitHub gist?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
