### ISSUE TITLE
Telepresence is exiting with error

### ISSUE THREAD

**Issue by rodrimc** [telepresenceio/telepresence#1108]
### What were you trying to do?

`telepresence --new-deployment test --run-shell --namespace <my namespace>`

### What did you expect to happen?

I was expecting to create a pod running a shell on the namespace provided.

### What happened instead?

telepresence exited with the following message:

`Looks like there's a bug in our code. Sorry about that!`

use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--new-deployment', 'test', '--run-shell', '--namespace', 'galp-dev']`
Version: `0.101`
Python version: `3.7.4 (default, Jul  9 2019, 18:15:00) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.14.1 // Server Version: v1.14.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Rodrigos-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 98, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 312, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
resence-38")'
  69.4 TEL | [110] exit 1 in 0.92 secs.
  69.4 TEL | [111] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-38.a.sanity.check.telepresence.io")'
  69.4  32 | c : DNS request from ('192.168.0.9', 55343) to None: 69 bytes
  69.7  15 | 2019-09-04T13:19:18+0000 [stdout#info] Sanity check: b'hellotelepresence-38.a.sanity.check.telepresence.io'
  69.7 TEL | [111] exit 1 in 0.39 secs.
  69.8 TEL | Wait for vpn-tcp connection: hellotelepresence-39
  69.8 TEL | [112] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-39")'
  70.8 TEL | [112] exit 1 in 0.92 secs.
  70.8 TEL | [113] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-39.a.sanity.check.telepresence.io")'
  70.8  32 | c : DNS request from ('192.168.0.9', 59302) to None: 69 bytes
  71.1  15 | 2019-09-04T13:19:20+0000 [stdout#info] Sanity check: b'hellotelepresence-39.a.sanity.check.telepresence.io'
  71.2 TEL | [113] exit 1 in 0.39 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
