### ISSUE TITLE
Telepresence does not handle broken port forwarding

### ISSUE THREAD

**Issue by luisw19** [telepresenceio/telepresence#1109]
After successfully installing telepresence via `kubectl apply` getting the error described in this post when testing the installation with command:

```
telepresence --deployment telepresence --namespace develop --run-shell
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--deployment', 'telepresence', '--namespace', 'develop', '--run-shell']`
Version: `0.101`
Python version: `3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]`
kubectl version: `Client Version: v1.15.0 // Server Version: v1.10.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin dhcp-10-167-124-216.uk.oracle.com 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 59, in connect
    if not ssh.wait():
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 80, in wait
    self.runner.check_call(self.command(["/bin/true"]), timeout=5)
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 424, in check_call
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 388, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.TimeoutExpired: Command '['ssh', '-F', '/dev/null', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-q', '-p', '57005', 'telepresence@127.0.0.1', '/bin/true']' timed out after 5 seconds

```

Logs:

```
.204814   86893 portforward.go:400] an error occurred forwarding 57005 -> 8022: error forwarding port 8022 to pod 5b189e8529bfd42a1ba6bf9ccd7d89dbdda6e768b62ea1793c72b868cd5b860c, uid : unable to do port forwarding: socat not found.
  14.6 TEL | [24] exit 255 in 0.45 secs.
  14.8 TEL | [25] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 57005 telepresence@127.0.0.1 /bin/true
  14.9  14 | Handling connection for 57005
  15.3  14 | E0906 12:16:26.920283   86893 portforward.go:400] an error occurred forwarding 57005 -> 8022: error forwarding port 8022 to pod 5b189e8529bfd42a1ba6bf9ccd7d89dbdda6e768b62ea1793c72b868cd5b860c, uid : unable to do port forwarding: socat not found.
  15.3 TEL | [25] exit 255 in 0.44 secs.
  15.5 TEL | [26] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 57005 telepresence@127.0.0.1 /bin/true
  15.6  14 | Handling connection for 57005
  20.6 TEL | [26] timed out after 5.01 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. I need to figure out how Telepresence can detect this situation and report a useful error message.

The missing `socat` might have to do with how your Kubernetes cluster is set up (does port forwarding work otherwise?), or it might be due to an incompatibility between your very recent `kubectl` and the somewhat older cluster. To diagnose this, maybe start by getting port forwarding to work using the same `kubectl` and cluster.

```console
$ kubectl create deploy hello-world --image=ark3/hello-world
deployment.apps/hello-world created

$ kubectl port-forward deploy/hello-world 8000
Forwarding from 127.0.0.1:8000 -> 8000
Forwarding from [::1]:8000 -> 8000


# switch to another terminal
$ curl localhost:8000
Hello, world!

# back on the first terminal you should now see
$ kubectl port-forward deploy/hello-world 8000
Forwarding from 127.0.0.1:8000 -> 8000
Forwarding from [::1]:8000 -> 8000
Handling connection for 8000
```

**Comment by luisw19** [comment]
Hi @ark3 thanks so much for your prompt reply.

Since I posted this, I also tested with `kubectl port-forward` and got a similar error. So we have requested now to install *socat* in the worder nodes of the k8s cluster hoping this will resolve the issue. 

Will keep you posted.

**Comment by ReSearchITEng** [comment]
@luisw19 afaik socat is required at k8s installation:
```
apt remove socat
...
The following packages will be REMOVED:
  kubeadm kubelet socat
```
kubelet cannot be installed without, which means socat was removed post k8s installation, and other things might be impacted too.

**Comment by luisw19** [comment]
@ReSearchITEng thanks for the info.

Do you now if this also the case for K8s [v1.10.11](https://github.com/kubernetes/kubernetes/releases/tag/v1.10.11)? Reading some posts I was under the impression that some (older?) versions of K8s didn't require socat at installation.

https://github.com/kubernetes/kubernetes/issues/19765

**Comment by ReSearchITEng** [comment]
@luisw19 
That's what it says: https://github.com/kubernetes/kubernetes/blob/release-1.10/build/rpms/kubelet.spec

**Comment by luisw19** [comment]
Excellent @ReSearchITEng thanks for the clarification.

Will have a look at github.com/ReSearchITEng/kubeadm-playbook/

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
