### ISSUE TITLE
Telepresence --run arg doesn't work as expected

### ISSUE THREAD

**Issue by vasili439** [telepresenceio/telepresence#1112]
Hi!  I have a strange issue with --run-shell vs --run commands:
```
@gke_....._europe-west3-xxx|bash-4.3# curl http://service-name.name-space:8080/url
{
  "git" : {
    "branch" : "3cfcd0a7c6ac82d8cefaacca20375e131b1b0cfd",
```
......
but when I'm trying to do the same with --run I got connection refused:
```
telepresence --run curl http://service-name.name-space:8080/url
...
curl: (7) Failed to connect to service-name.name-space port 8080: Connection timed out
```

looks like telepresence tries to run command on my local PC. Here two gists with `--run-shell` and `--run` args:
run-shell: https://gist.githubusercontent.com/vasili439/41c0444b92b178b58737bd9ba5d45c69/raw/358d2ff6054b1f4448d4df32e7e0760a6b30cb70/telepresence-vy-success.log

run: https://gist.githubusercontent.com/vasili439/bfac2834470b46a06230e2d0f90ba6b8/raw/14787bb289fa6a83a9c2c107e9300669c1692e80/telepresence-vy-fail.log

**Comment by ark3** [comment]
In both your logfiles, it looks like Telepresence's connectivity check succeeds immediately, even though it takes several seconds for connectivity to be established. I would guess that if you changed your `--run` command to something like `bash -c "sleep 5; curl http://.../"` it might work.

That doesn't solve the problem, of course. Tel checks for connectivity by looking up DNS names like `hellotelepresence-3`, for which any sensible DNS server should return NXDomain. Are you using a consumer ISP for DNS, like Verizon FIOS, which directs DNS errors to an advertising page?

**Comment by vasili439** [comment]
@ark3 it made the trick. Thank you! As workaround it is acceptable for our case.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
