### ISSUE TITLE
Block swap-deployment for certain namespaces

### ISSUE THREAD

**Issue by dr0l3** [telepresenceio/telepresence#1115]
First of all; I love telepresence! Thank you for building it <3

I would like to block the swap-deployment command from running against certain namespaces. Is there a way to achieve this?

Someone who is definitely not me might have caused a non-trivial amount of downtime for my company's main product by accidentally swapping a production deployment and I am trying to make sure that never happens again :P

**Comment by ark3** [comment]
Telepresence does all its work using `kubectl`/`oc`, so all the usual role-based authorization stuff works as expected. Can you achieve what you want via RBAC? Maybe lock down update of replicasets? Tel uses `kubectl scale` on the original deployment when swapping.

**Comment by dr0l3** [comment]
Sorry for the very late reply. That would probably solve it yes. Thanks for the suggestion! :)
