### ISSUE TITLE
Starting telepresence messes with local machine dns (Mac OS)

### ISSUE THREAD

**Issue by piotr-grosicki** [telepresenceio/telepresence#1116]
Hi,

I'm trying to use `telepresence` to proxy connection to/from cluster and run one of my services locally.

But when I'm running:
`sudo telepresence --expose 8880:8888 --namespace NAMESPACE --swap-deployment SERVICE_NAME --env-json telepresence-SERVICE_NAME.json` 
dns on my local machine is like disabled. Google Chrome cries with: 
```
www.google.com’s server IP address could not be found.
DNS_PROBE_FINISHED_BAD_CONFIG
```

After closing telepresence everything works.

I was trying to reinstall docker/kubernetes/telepresence and even whole operating system (I'm using newest Mac OS).

I ran out of ideas how to fix it, does anyone know what can be wrong? I can attach any logs if needed.

**Comment by ark3** [comment]
It sounds like you're running into a DNS loop. Where is your Kubernetes cluster? This tends to be a problem with local clusters, like Minikube.

**Comment by lbunschoten** [comment]
I am running into the exact same issue when using vpn-tcp. I am using minikube, so it could be a DNS loop indeed. I've already tried quite some things, but I can't figure out what's going wrong. Could it be that it doesn't properly detect that I am using minikube?

Also, do you know an easy way to detect if I am in a DNS lookup loop?

I am trying to find the source code now that is detecting minikube at the moment, to see if I can spot any flaw in there.

Also some version details:
Telepresence version: 0.103
Minikube version: 1.5.2
Kubectl version: v1.16.2

**Comment by lbunschoten** [comment]
Hmm, found the code that does the detecting for the local VM: https://github.com/telepresenceio/telepresence/blob/dc5e4f535e4a81277c477ce5acb95c32f5b9ad41/telepresence/startup.py#L212

I do see the log line: `Looks like we're in a local VM, e.g. minikube.`, so the detection seems to work just fine 🤔 

Here are the full logs:
[telepresence.log](https://github.com/telepresenceio/telepresence/files/3824405/telepresence.log)

**Comment by ark3** [comment]
Thanks for the logfile. This is _not_ a DNS loop after all. Forwarded queries for names that should resolve (like www.google.com) are timing out.

In short, when Telepresence detects a local cluster, it tries to send DNS queries to an unrelated nameserver, i.e. one that your system is _not_ configured to use normally, so that those queries don't get captured again. It's possible that whatever nameserver it picked is not reachable from your system. We would benefit from additional logging to reveal which nameserver it is trying.

It's also possible that some other change in MacOS Catalina is breaking Telepresence. We have not tested against Catalina yet.

I should be able to address the additional logging in a couple of weeks (after KubeCon), which may help us get to the bottom of this. In the meantime, can the container method serve as a workaround?

**Comment by lbunschoten** [comment]
Hello ark3.

Thanks for your quick response. I did debug a bit further. I cloned the telepresence repo and added the logging myself to see which nameserver it picked. On my machine I have the cloudfare DNS IP's configured (1.1.1.1 and 1.0.0.1). Telepresence picked the first available DNS, being 8.8.8.8, which is expected from looking at the code.

On my host mache I tried a few command to see what is going on:
`ping google.com` responds with `ping: cannot resolve google.com: Unknown host`
`ping 8.8.8.8` works just fine. 
`telnet 8.8.8.8` responds with: 
```Trying 8.8.8.8...
telnet: connect to address 8.8.8.8: Operation timed out
telnet: Unable to connect to remote host
```

I also tried restarting the `mDNSResponder`, but that didn't help either unfortunately.

One thing I noticed and find to be a bit supicious, is that the shell that is opened when you do the `swap-deployment` is incredibly slow. Even doing a simple command like `cat /etc/resolv.conf` can take roughly a minute. Does this ring any bell to you?

I haven't tried using the container method yet, but there is also no big rush in fixing this. I am only trying to use telepresence for one of my pet projects. I'll give the container method a go later

**Comment by thehappycoder** [comment]
I am experiencing the same issue. Both the host and Docker containers inside minikube cannot resolve hosts.

```
telepresence --context minikube --swap-deployment dummy --expose 8080 --run yarn dev
T: Warning: kubectl 1.17.0 may not work correctly with cluster version 1.13.12 due to the version discrepancy. See https://kubernetes.io/docs/setup/version-skew-policy/ for more information.

T: How Telepresence uses sudo: https://www.telepresence.io/reference/install#dependencies
T: Invoking sudo. Please enter your sudo password.
Password:
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list 
T: of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment dummy with a proxy
T: Forwarding remote port 8080 to local port 8080.

T: Connected. Flushing DNS cache.
T: Setup complete. Launching your command.
```

Also tried passing `--local-cluster`, which didn't help.

I am running macos 10.15.2 (Catalina). Interesting that my co-workers runs Catalina too, and he doesn't experience this issue.

**Comment by Piste** [comment]
I'm facing the same issue. Wondering if anyone has made progress or was able to solve it somehow.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here is a helpful doc on how networking works in Telepresence 2 which may be helpful: https://www.telepresence.io/docs/latest/reference/tun-device/

Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
