### ISSUE TITLE
Telepresence with GKE and Pod Security enabled does not work

### ISSUE THREAD

**Issue by minhnhupham** [telepresenceio/telepresence#1119]
### What were you trying to do?
We are trying to use telepresence with a GKE cluster with Pod Security setting enabled and there is no way to specify a Kubernetes Service Account to run the telepresence pod as.
`telepresence --run-shell`

### What did you expect to happen?
A telepresence pod should have been deployed to the cluster to establish the 2-way link.

### What happened instead?
The telepresence pod is unable to be created because the default service account doesn't have PSP permissions. With the following error message:

> Error creating: pods "telepresence-1568942685-3534012-1998-6476b9d5ff-" is forbidden: unable to validate against any pod security policy: []

**Comment by ReSearchITEng** [comment]
even if it's k8s, you may want to try the ocp image and confirm if it's working for you.
(the diff between k8s and ocp image is mainly the permissions required by the image. And the ocp one was created for less perms.)
The down side is ocp image is bigger (as it's based on centos).

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
