### ISSUE TITLE
Downgrade Telepresence to version 0.99

### ISSUE THREAD

**Issue by Newbie112222** [telepresenceio/telepresence#1122]
HI,
I have telepresence version 0.101 and i want to downgrade to version 0.99. I tried to downgrade using a pre built copy using the link below but looks like its still takes the latest version.
Is there a way for me to keep both versions but let me choose which version i want to use? If not then should i just delete my existing telepresence and use the link below? Thanks!!

Pre-built link:
https://s3.amazonaws.com/datawire-static-files/telepresence/telepresence-0.99.tar.gz

**Comment by ark3** [comment]
You can keep as many version around as you'd like. That tarball expands into a `telepresence-0.99` directory. You can run Tel right out of there and it'll work fine.

Why are you downgrading? Perhaps we can fix the underlying issue for you.

**Comment by Newbie112222** [comment]
My kubernetes container is running 0.99 version and its complaining about the keeping the version same as mine is 0.101. 
I went in to the directory where i had the folder from the S3 bucket extracted and tried tel. Got the same error to keep the version same.

**Comment by ark3** [comment]
Can you copy-paste the output please?

**Comment by Newbie112222** [comment]
The remote datawire/telepresence-k8s container is running version 0.99, but this tool is version 0.101. Please make sure both are
T: running the same version.

T: Exit cleanup in progress

FYI: this is the entire output. Its not complaining about any log files etc

**Comment by ark3** [comment]
Weird. I cannot replicate that.

```console
$ kubectl run tel99 --image=datawire/telepresence-k8s:0.99
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/tel99 created

$ telepresence --deployment tel99 --run curl hello-world:8000
[...]
T: Starting network proxy to cluster using the existing proxy Deployment tel99

T: The remote datawire/telepresence-k8s container is running version 0.99, but this tool is version 0.101. Please make 
T: sure both are running the same version.

T: Exit cleanup in progress

$ ./telepresence-0.99/bin/telepresence --version
0.99

$ ./telepresence-0.99/bin/telepresence --deployment tel99 --run curl hello-world:8000
[...]
T: Setup complete. Launching your command.
Hello, world!
T: Your process has exited.
T: Exit cleanup in progress

T: Telepresence 0.101 is available (you're running 0.99). https://www.telepresence.io/reference/changelog
```

**Comment by Newbie112222** [comment]
Hmm. So should i just remove telepresence and start from scratch or any recommendations ? Or should i try to replicate the commands you tried above and see if that works?

**Comment by gomesandres** [comment]
I'm also having the same problem, i made a fresh install of telepresence, but now do this:

T: The remote datawire/telepresence-k8s container is running version 0.99, but this tool is version 0.101. Please make 
T: sure both are running the same version.

T: Exit cleanup in progress

**Comment by ark3** [comment]
What does `telepresence --version` tell you? Are you sure you're running the correct Telepresence binary?

**Comment by gomesandres** [comment]
telepresence --version
0.101

in fact there's a difference in versions, i have the 0.101 locally and 0.99 in the k8s. It's mandatoy to use the same version in both places?

**Comment by ark3** [comment]
Yes. Can you suggest how we can make the error message clearer?

```
T: The remote datawire/telepresence-k8s container is running version 0.99, but this tool is version 0.101. Please make
T: sure both are running the same version.
```

**Comment by gomesandres** [comment]
Oh, ok.

Uhm, i don't think it's the message, in my case, before this i was using the version 0.100 and worked fine with the k8s version (0.99) and printed the same message. So i just assumed it wasn't mandatoy.

**Comment by Newbie112222** [comment]
Hi, @ark3 - So what do you suggest on this. Should i just uninstall telepresence completely and try it. I have the 0.99 binary as well and when i run telepresence in the 0.99 directory it reverts back to 0.101. Please suggest on the same. Thanks!!

**Comment by ark3** [comment]
Sure, that seems like it's worth a try. I'm really not clear on how Tel 0.99 would turn into Tel 0.101 by itself; there is no auto-update mechanism in Telepresence.

**Comment by Newbie112222** [comment]
Hi,
Is there any documentation to uninstall telepresence i did telepresence --help but that does not list anything. I have moved all the files and folders to trash and brew cask info telepresence is giving me the below output. Also, i when i type in telepresence --version it shows me the version as 0.101 (even after moving all files and folders to trash)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'telepresence' is unavailable: No Cask with this name exists.

**Comment by ark3** [comment]
You want `brew uninstall telepresence` to remove it, assuming you installed via Homebrew.

After doing that, try `telepresence --version` to see if it's still installed somewhere, and `which telepresence` or `type telepresence` to figure out where.

**Comment by Newbie112222** [comment]
Thanks that worked and i used this link below to get the 0.99 version. The issue now is that i can connect to my cluster by running ./telepresence (after going in the extracted folder) but when doing telepresence --version its giving -bash: telepresence: command not found.
How do i fix this?

Link used for 0.99 version (also it does not have any ./install.sh script):
https://s3.amazonaws.com/datawire-static-files/telepresence/telepresence-0.99.tar.gz

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
