### ISSUE TITLE
Trying to swap a docker to existing Deployment  

### ISSUE THREAD

**Issue by aflatto** [telepresenceio/telepresence#1127]
### What were you trying to do?

I am trying to run a local docker image with a running container on my minikube cluster

### What did you expect to happen?

The telepresence will run the container with the one located on my local repo

### What happened instead?

The execution crashed and exited 

### Automatically included information

Command line: `['/usr/bin/telepresence', '--method', 'container', '--namespace', 'optibus', '--expose', '80', '--docker-run', '-i', '-t', 'mithra']`
Version: `0.101`
Python version: `3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.15.1 // Server Version: v1.15.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux assaf-OptiBus-Laptop 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 120, in launch
    mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 155, in run_docker_command
    raise RuntimeError("SSH to the network container failed to start.")
RuntimeError: SSH to the network container failed to start.

```

Logs:

```
eyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  40.1  36 |   21.5 TEL | [85] exit 255 in 0.00 secs.
  40.4  36 |   21.8 TEL | [86] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  40.4  36 |   21.8 TEL | [86] exit 255 in 0.00 secs.
  40.6  36 |   22.1 TEL | [87] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  40.6  36 |   22.1 TEL | [87] exit 255 in 0.02 secs.
  40.9  36 |   22.3 TEL | [88] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  40.9  36 |   22.3 TEL | [88] exit 255 in 0.00 secs.
  41.1  36 |   22.6 TEL | [89] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  41.2  36 |   22.6 TEL | [89] exit 255 in 0.00 secs.

```

**Comment by ark3** [comment]
Sorry about the crash!

Quick check: are you using the Minikube Docker Daemon? That would be #873.

**Comment by aflatto** [comment]
I am indeed working against Minikube, but the issue in the #873 does not solve my issue

**Comment by ark3** [comment]
Do your Docker builds in one shell, using the Minikube Docker daemon. Run Telepresence from a different shell, using the system Docker daemon. That should work fine.
