### ISSUE TITLE
Unexpected telepresence exit does not kill the process given with --run flag

### ISSUE THREAD

**Issue by azinneera** [telepresenceio/telepresence#1133]
**What were you trying to do?**
I ran a command with telepresence --run command and the telepresence got killed unexpectedly in the middle of that process.

**What did you expect to happen?**

Process executed with --run flag is owned by telepresence and would be killed when telepresence is exited.

**What happened instead?**

telepresence got killed unexpectedly in the middle of that process execution but the command execution continued to run till the end

Please find the command output below.

```
Background process (sshuttle) exited with return code 99. Command was:
T:   sshuttle-telepresence -v --dns --method nat -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null' -r telepresence@127.0.0.1:32861 --to-ns 127.0.0.1:9053 10.96.0.0/12 10.244.0.0/24T: Recent output was:
T:   c : DNS request from ('10.100.7.32', 52410) to None: 50 bytes
T:   c : DNS request from ('10.100.7.32', 40757) to None: 33 bytes
T:   c : DNS request from ('10.100.7.32', 53246) to None: 33 bytes
T:   c : DNS request from ('10.100.7.32', 53155) to None: 50 bytes
T:   c : DNS request from ('10.100.7.32', 35469) to None: 50 bytes
T:   >> iptables -t nat -D OUTPUT -j sshuttle-12300
T:   >> iptables -t nat -D PREROUTING -j sshuttle-12300
T:   >> iptables -t nat -F sshuttle-12300
T:   >> iptables -t nat -X sshuttle-12300
T:   c : fatal: server died with error code 1T: Proxy to Kubernetes exited. This is typically due to a lost connection.T: Exit cleanup in progress
```

**Comment by ark3** [comment]
Can you pass along the telepresence.log file for that run as a Gist?

**Comment by azinneera** [comment]
Sorry for the late response. Please find the telepresence log for the issue at https://gist.github.com/azinneera/68bd260e4472e5daabf11b925855a48c

**Comment by ark3** [comment]
Argh. There is not enough logging in the output. Can you reproduce this issue easily? Would you be able to try with a specially-crafted Telepresence that has additional logging?

**Comment by azinneera** [comment]
Yes, this can reproduced by just running it in a local cluster with the --run-shell flag. Please let me know the instructions to reproduce it with the required logs.

**Comment by ark3** [comment]
Sorry for the delay. Could you please try the Telepresence executable in this zipfile? 

[tel-0.102-55-g5505f67.zip](https://github.com/telepresenceio/telepresence/files/3772990/tel-0.102-55-g5505f67.zip)

This version will perform a bit more logging around main process termination.

Thank you for your help debugging this!

**Comment by azinneera** [comment]
I have reproduced the issue with the custom Telepresence executable you shared. Please find the new log file at https://gist.github.com/azinneera/68bd260e4472e5daabf11b925855a48c#file-tel-0-102-55-g5505f67-telepresence-log. Let me know if anything more is required. 

Thanks for looking into this @ark3!!

**Comment by azinneera** [comment]
@ark3 Can I get an update on the cause for this?
