### ISSUE TITLE
New `--docker-mount` feature does not work on MacOS

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#1135]
... because the `sshfs` call connects to localhost:(port) in the Docker VM, while the SSH daemon is on localhost:(port) on the host machine.

Possible solutions
- use host.docker.internal instead of localhost only on the Mac, and adjust the `sshuttle` command so it's reachable
- figure out how to set up port forwarding for the sshfs container and/or the Docker VM, again only on the Mac

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
