### ISSUE TITLE
telepresence won't start

### ISSUE THREAD

**Issue by KimStebel** [telepresenceio/telepresence#1144]
### What were you trying to do?

Run `telepresence` without any parameters against minikube started with `--vm-driver=none`.

### What did you expect to happen?

telepresence starts without error

### What happened instead?

I got an error saying "Looks like there's a bug in our code. Sorry about that!"
Here's the telepresence.log:
https://gist.github.com/KimStebel/ef5d3bf670e438dee8105eff0aa2b33e

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.102`
Python version: `3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.16.1 // Server Version: v1.16.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux flexys-laptop-1 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 113, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 69, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
ne>
  58.0  84 | Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
  58.0  84 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  58.0  84 | Events:
  58.0  84 |   Type    Reason     Age        From               Message
  58.0  84 |   ----    ------     ----       ----               -------
  58.0  84 |   Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned default/telepresence-1570793706-1937592-14615-58596bc9cb-lmhnc to minikube
  58.0  84 |   Normal  Pulling    51s        kubelet, minikube  Pulling image "datawire/telepresence-k8s:0.102"
  58.0  84 |   Normal  Pulled     35s        kubelet, minikube  Successfully pulled image "datawire/telepresence-k8s:0.102"
  58.0  84 |   Normal  Created    34s        kubelet, minikube  Created container telepresence-1570793706-1937592-14615
  58.0  84 |   Normal  Started    34s        kubelet, minikube  Started container telepresence-1570793706-1937592-14615
  58.0 TEL | [84] ran in 0.17 secs.

```

**Comment by ark3** [comment]
Sorry about the crash, and thanks for the detailed bug report. In short, this is #1131. The way Telepresence adjusts networking is not compatible with Minikube with `--vm-driver=none`, but Telepresence doesn't know how to detect this situation and provide a useful error message. Can you please use an alternate setup for your local cluster? I made some suggestions in #1131.

I'll close this issue as a duplicate.
