### ISSUE TITLE
split telepresence and shuttle

### ISSUE THREAD

**Issue by desaintmartin** [telepresenceio/telepresence#1146]
Hello,
Would it be possible to split installation of sshuttle and installation of telepresence? I can see from the build scripts that sshuttle is bundled as "sshuttle-telepresence", is there a specific reason appart from having the same version installed?

We maintain a python wheel and we would like to be able to depend on telepresence so that we control the version of telepresence installed.

**Comment by ark3** [comment]
Certainly. The [Install from source](https://www.telepresence.io/reference/install#install-from-source) section and the subsequent dependencies section should hopefully have enough information to proceed.

In particular, if you look at the [install.sh](https://github.com/telepresenceio/telepresence/blob/0.102/install.sh) script, you'll see that it runs two Python invocations, one to build Telepresence, and one to download/build sshuttle. You can run those manually to construct the individual binaries, or inspect the underlying Python code to see how they work.

For what it's worth, we don't really work on our sshuttle fork, so it has remained unchanged for a long time. We have considered distributing it separately, but it isn't particularly useful outside of Telepresence.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since Telepresence no longer uses sshuttle. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
