### ISSUE TITLE
issue of deployment to openshift 

### ISSUE THREAD

**Issue by hzhangse** [telepresenceio/telepresence#1147]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--run-shell']`
Version: `0.102`
Python version: `3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.11.5 // Server Version: v1.11.0+d4cacc0`
oc version: `oc v3.10.0+0c4577e-1 // kubernetes v1.10.0+b81c8f8 // features: Basic-Auth GSSAPI Kerberos SPNEGO //  // Server https://okd-internal.iotbull.com:8443 // openshift v3.11.0+82a43f6-231 // kubernetes v1.11.0+d4cacc0`
OS: `Linux ryan-Precision-M4700 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 125, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 152, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 99, in get_deployment_json
    )["items"][0]
IndexError: list index out of range

```

Logs:

```
356b85fbab22f9a
   2.3  12 | No resources found
   2.3 TEL | [12] ran in 0.33 secs.
   2.3 TEL | [13] Running: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1571108887-2836478-5494 --image=datawire/telepresence-k8s:0.102 --labels=telepresence=5fec29a1a45947bba356b85fbab22f9a
   2.5  13 | deploymentconfig "telepresence-1571108887-2836478-5494" created
   2.5 TEL | [13] ran in 0.24 secs.
   2.5 TEL | END SPAN deployment.py:105(create_new_deployment)    0.6s
   2.6 TEL | BEGIN SPAN remote.py:150(get_remote_info)
   2.6 TEL | BEGIN SPAN remote.py:77(get_deployment_json)
   2.6 TEL | [14] Capturing: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas get deployment -o json --selector=telepresence=5fec29a1a45947bba356b85fbab22f9a
   2.8 TEL | [14] captured in 0.24 secs.
   2.8 TEL | END SPAN remote.py:77(get_deployment_json)    0.2s

```

**Comment by hzhangse** [comment]
0.0 TEL | Telepresence 0.102 launched at Tue Oct 15 10:09:52 2019
   0.0 TEL |   /usr/bin/telepresence
   0.0 TEL | Platform: linux
   0.0 TEL | Python 3.5.2 (default, Oct  8 2019, 13:06:37)
   0.0 TEL | [GCC 5.4.0 20160609]
   0.0 TEL | [1] Running: uname -a
   0.0   1 | Linux ryan-Precision-M4700 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   0.0 TEL | [1] ran in 0.00 secs.
   0.0 TEL | BEGIN SPAN main.py:40(main)
   0.0 TEL | BEGIN SPAN startup.py:73(__init__)
   0.0 TEL | Found kubectl -> /usr/local/bin/kubectl
   0.0 TEL | Found oc -> /usr/bin/oc
   0.0 TEL | [2] Capturing: kubectl version --short
   0.1 TEL | [2] captured in 0.13 secs.
   0.1 TEL | [3] Capturing: kubectl config current-context
   0.2 TEL | [3] captured in 0.09 secs.
   0.2 TEL | [4] Capturing: kubectl config view -o json
   0.3 TEL | [4] captured in 0.10 secs.
   0.3 TEL | [5] Capturing: kubectl --context default/okd-internal-iotbull-com:8443/system:admin get ns saas
   0.5 TEL | [5] captured in 0.15 secs.
   0.5 TEL | Command: oc 1.11.5
   0.5 TEL | Context: default/okd-internal-iotbull-com:8443/system:admin, namespace: saas, version: 1.11.0+d4cacc0
   0.5 TEL | [6] Capturing: minishift ip
   0.5 TEL | [6] [Errno 2] No such file or directory: 'minishift'
   0.5 TEL | END SPAN startup.py:73(__init__)    0.5s
   0.5 TEL | [7] Running: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas get dc/None
   0.8   7 | Error from server (NotFound): deploymentconfigs.apps.openshift.io "None" not found
   0.8 TEL | [7] exit 1 in 0.24 secs.
   0.8 >>> | Failed to find OpenShift deploymentconfig None:
   0.8 >>> |   Error from server (NotFound): deploymentconfigs.apps.openshift.io "None" not found
   0.8 >>> | Will try regular Kubernetes Deployment.
   0.8 TEL | Found ssh -> /usr/bin/ssh
   0.8 TEL | [8] Capturing: ssh -V
   0.8 TEL | [8] captured in 0.01 secs.
   0.8 TEL | Found bash -> /bin/bash
   0.8 TEL | Found sshuttle-telepresence -> /usr/libexec/sshuttle-telepresence
   0.8 TEL | Found conntrack -> /usr/sbin/conntrack
   0.8 TEL | Found iptables -> /sbin/iptables
   0.8 TEL | Found sudo -> /usr/bin/sudo
   0.8 TEL | [9] Running: sudo -n echo -n
   0.8 TEL | [9] ran in 0.02 secs.
   0.8 TEL | [10] Capturing: sudo iptables --list
   0.8 TEL | [10] captured in 0.01 secs.
   0.8 >>> | Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
   0.8 TEL | Found sshfs -> /usr/bin/sshfs
   0.8 TEL | Found fusermount -> /bin/fusermount
   0.8 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   0.8 TEL | [11] Running: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas get pods telepresence-connectivity-check --ignore-not-found
   1.0 TEL | [11] ran in 0.22 secs.
   1.9 TEL | Scout info: {'application': 'telepresence', 'notices': [], 'latest_version': '0.102'}
   1.9 TEL | BEGIN SPAN deployment.py:105(create_new_deployment)
   1.9 >>> | Starting network proxy to cluster using new Deployment telepresence-1571105392-923361-3018
   1.9 TEL | [12] Running: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas delete --ignore-not-found svc,deploy --selector=telepresence=ef66fb784fa04525ae987cb7b12741a8
   2.1  12 | No resources found
   2.1 TEL | [12] ran in 0.24 secs.
   2.1 TEL | [13] Running: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1571105392-923361-3018 --image=datawire/telepresence-k8s:0.102 --labels=telepresence=ef66fb784fa04525ae987cb7b12741a8
   2.4  13 | deploymentconfig "telepresence-1571105392-923361-3018" created
   2.4 TEL | [13] ran in 0.24 secs.
   2.4 TEL | END SPAN deployment.py:105(create_new_deployment)    0.5s
   2.4 TEL | BEGIN SPAN remote.py:150(get_remote_info)
   2.4 TEL | BEGIN SPAN remote.py:77(get_deployment_json)
   2.4 TEL | [14] Capturing: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas get deployment -o json --selector=telepresence=ef66fb784fa04525ae987cb7b12741a8
   2.6 TEL | [14] captured in 0.24 secs.
   2.6 TEL | END SPAN remote.py:77(get_deployment_json)    0.2s
   4.6 TEL | CRASH: list index out of range
   4.6 TEL | Traceback (most recent call last):
   4.6 TEL |   File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
   4.6 TEL |     yield
   4.6 TEL |   File "/usr/bin/telepresence/telepresence/main.py", line 60, in main
   4.6 TEL |     remote_info = start_proxy(runner)
   4.6 TEL |   File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 125, in start_proxy
   4.6 TEL |     run_id=run_id,
   4.6 TEL |   File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 152, in get_remote_info
   4.6 TEL |     runner, deployment_name, deployment_type, run_id=run_id
   4.6 TEL |   File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 99, in get_deployment_json
   4.6 TEL |     )["items"][0]
   4.6 TEL | IndexError: list index out of range
   4.6 TEL | (calling crash reporter...)
   8.5 >>> | Exit cleanup in progress
   8.5 TEL | (Cleanup) Delete new deployment
   8.5 >>> | Cleaning up Deployment telepresence-1571105392-923361-3018
   8.5 TEL | [15] Running: oc --context default/okd-internal-iotbull-com:8443/system:admin --namespace saas delete --ignore-not-found svc,deploy --selector=telepresence=ef66fb784fa04525ae987cb7b12741a8
   8.8  15 | No resources found
   8.8 TEL | [15] ran in 0.23 secs.
   8.8 TEL | (Cleanup) Kill sudo privileges holder
   8.8 TEL | (Cleanup) Stop time tracking
   8.8 TEL | END SPAN main.py:40(main)    8.8s
   8.8 TEL | (Cleanup) Remove temporary directory
   8.8 TEL | (Cleanup) Save caches
   8.8 TEL | (sudo privileges holder thread exiting)

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
