### ISSUE TITLE
swap deployment error

### ISSUE THREAD

**Issue by ostlerc** [telepresenceio/telepresence#1159]
### What were you trying to do?
run `telepresence --swap-deployment <dep>`

### What did you expect to happen?
for it to work?

### What happened instead?
i didn't do anything else. just got this auto ticket creation.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'router']`
Version: `0.102`
Python version: `3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]`
kubectl version: `Client Version: v1.9.1 // Server Version: v1.10.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin MBP-400044112 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 54895 telepresence@127.0.0.1 -L127.0.0.1:54908:127.0.0.1:9050 -R9055:127.0.0.1:54909

```

Logs:

```
47.9 TEL | [184] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-71.a.sanity.check.telepresence.io")'
  48.0 TEL | [184] exit 1 in 0.12 secs.
  48.1 TEL | Wait for vpn-tcp connection: hellotelepresence-72
  48.1 TEL | [185] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-72")'
  48.2 TEL | [185] exit 1 in 0.07 secs.
  48.2 TEL | [186] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-72.a.sanity.check.telepresence.io")'
  48.3 TEL | [186] exit 1 in 0.13 secs.
  48.4 TEL | [34] SSH port forward (socks and proxy poll): exit 255
  48.4 TEL | Wait for vpn-tcp connection: hellotelepresence-73
  48.4 TEL | [187] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-73")'
  48.5 TEL | [187] exit 1 in 0.07 secs.
  48.5 TEL | [188] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-73.a.sanity.check.telepresence.io")'
  48.6 TEL | [188] exit 1 in 0.12 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! Could you please pass along a link to the telepresence.log in a GitHub Gist?

I hope we did not break compatibility with older clusters/commands. We test against Kubernetes 1.12 and newer in CI.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
