### ISSUE TITLE
Telepresence fails to start when running on inject-tcp method

### ISSUE THREAD

**Issue by mtp1376** [telepresenceio/telepresence#1161]
### What were you trying to do?

I was running telepresence on inject-tcp method(no additional arguments passed other than the `--method inject-tcp`

### What did you expect to happen?

I was expecting to get a shell other than the error below.

### What happened instead?

Got the following error:

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'inject-tcp']`
Version: `0.102`
Python version: `3.7.4 (default, Jul  9 2019, 18:15:00) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.14.1 // Server Version: v1.14.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Mohammads-MacBook-Pro-4.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 50, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 101, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
re: twisted.internet.error.DNSLookupError: DNS lookup failed: kubernetes.default.svc.cluster.local.
  96.0  16 | 
  96.0  77 | Traceback (most recent call last):
  96.0  77 |   File "<string>", line 1, in <module>
  96.0  77 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  96.0 TEL | [77] exit 1 in 0.16 secs.
  96.2 TEL | [78] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default.svc.cluster.local'"'"', 443))'
  96.3  16 | 2019-10-23T06:16:45+0000 [-] Unhandled Error
  96.3  16 | 	Traceback (most recent call last):
  96.3  16 | 	Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: kubernetes.default.svc.cluster.local.
  96.3  16 | 
  96.3  78 | Traceback (most recent call last):
  96.3  78 |   File "<string>", line 1, in <module>
  96.3  78 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  96.3 TEL | [78] exit 1 in 0.16 secs.
  96.3 TEL | END SPAN local.py:42(set_up_torsocks)   15.2s

```

**Comment by ark3** [comment]
Sorry about the crash. Telepresence is trying to connect to kubernetes.default.svc.cluster.local from the Telepresence proxy pod. Most Kubernetes clusters have that Service defined and accessible under that name. Is your cluster configured differently?

**Comment by mtp1376** [comment]
`root@project-grpc-staging-xx-xxx:/home/modir/Project# curl kubernetes.default.svc.cluster.local
curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local`
Seems so.

**Comment by ark3** [comment]
How about just `kubernetes.default`? That's the other obvious option.

**Comment by mtp1376** [comment]
It does work with the latter.
```bash
$> kubectl run curl-from-cluster -it --rm --image=pstauffer/curl --restart=Never -- curl -svk https://kubernetes.default/api/
*   Trying 10.233.0.1...
* TCP_NODELAY set
* Connected to kubernetes.default (10.233.0.1) port 443 (#0)
```

**Comment by ark3** [comment]
Excellent. As I said in #1141, I'll switch to using just `kubernetes.default` for this test. Thanks for your help.

**Comment by mtp1376** [comment]
@ark3 Thank you for your attention. I am interested on contributing to Telepresence myself. Can you guide me into this so that I can fix this issue myself and give you a PR?
