### ISSUE TITLE
Telepresence local Docker check gives a misleading message if docker fails for other reasons

### ISSUE THREAD

**Issue by mtp1376** [telepresenceio/telepresence#1162]
I am running Telepresence on a mac machine, and Docker for desktop is running in the background as well. But when I try to execute the telepresence swap-deployment command with `docker-run` method, it keeps telling me that the local docker check failed. The error I get(although it may not be much of a help) is this:
```
T: Local Docker check failed:

T: Telepresence's container method requires using a local Docker daemon. Connecting to a remote daemon or a daemon running in a
T: VM does not work at this time. If you are using Minikube's Docker daemon, launch Telepresence in a separate shell that does
T: not have the Minikube Docker environment variables set.

T: Error: Local Docker daemon required
```

**Comment by ark3** [comment]
Telepresence does roughly this check on startup:

```console
$ echo "Hello world" > hello.txt
$ docker run --rm -it -v $(pwd):/asdf alpine:3.6 cat /asdf/hello.txt
Hello world
```

Does this work on your machine?

**Comment by mtp1376** [comment]
Oops. I think I figured out the problem. I live in Iran(which is a country blocked by Docker), so running the command `docker run --rm -it -v $(pwd):/asdf alpine:3.6 cat /asdf/hello.txt` without VPN turned on(since the image is not already downloaded on my system) returns a non-zero code.
In order to fix the problem, I switched my VPN on, then pulled the needed images(`alpine:3.6` & `datawire/telepresence-local:0.102`) and then it seems to be OK.

**Comment by ark3** [comment]
Telepresence can do a better job with error reporting. Let's keep this issue open to track that. Thank you for the explanation!

**Comment by ark3** [comment]
- [ ] Better error reporting. If this fails, explain what it was trying to check and how it failed.
- [ ] Make this check optional. In other words, if it fails, explain what may go wrong, but proceed anyway.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
