### ISSUE TITLE
Telepresence command not Found

### ISSUE THREAD

**Issue by ContraBoy9999** [telepresenceio/telepresence#1168]
HI,
I was able to download telepresence 0.99 using the link below but 
the problem is that i can connect to my cluster by running ./telepresence. telepresence --version its giving -bash: telepresence: command not found. Any solution to this issue?

FYI- I have a requirement to use this version hence did not download the latest version.

Link used for 0.99 version (also it does not have any ./install.sh script):
https://s3.amazonaws.com/datawire-static-files/telepresence/telepresence-0.99.tar.gz

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
