### ISSUE TITLE
errors command telepresence

### ISSUE THREAD

**Issue by quyetnguyen0989** [telepresenceio/telepresence#1173]
### What were you trying to do?
I trie run test with command : telepresence

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.102`
Python version: `3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.13.1 // Server Version: v1.13.7-gke.24`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin BE-LMP13-06.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Background process (kubectl port-forward) exited with return code 1. Command was:
  kubectl --context gke_gam-project---namespace default port-forward telepresence-1572236390-118369-83630-567c897b45-nff5m 62840:8022

Recent output was:
  error: error upgrading connection: error dialing backend: EOF
```

Logs:

```
 DNSDatagramProtocol starting on 9053
  20.9  39 | 2019-10-28T04:20:43+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fc239c3c828>
  20.9  39 | 2019-10-28T04:20:43+0000 [-] Loaded.
  20.9  39 | 2019-10-28T04:20:43+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.7.0 (/usr/bin/python3.6 3.6.8) starting up.
  20.9  39 | 2019-10-28T04:20:43+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  21.0 TEL | [42] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 62840 telepresence@127.0.0.1 /bin/true
  21.0 TEL | [42] exit 255 in 0.02 secs.
  21.0  40 | error: error upgrading connection: error dialing backend: EOF
  21.0 TEL | [40] kubectl port-forward: exit 1
  21.3 TEL | [43] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 62840 telepresence@127.0.0.1 /bin/true
  21.3 TEL | [43] exit 255 in 0.02 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
