### ISSUE TITLE
PermissionError: [Errno 13] in WSL

### ISSUE THREAD

**Issue by akeyboardlife** [telepresenceio/telepresence#1175]
### What were you trying to do?

Following the Quick example.

### What did you expect to happen?

hello world

### Automatically included information

Command line: `['/usr/bin/telepresence', '--docker-run', '--rm', '-it', 'pstauffer/curl', 'curl', 'http://hello-world:8000/']`
Version: `0.103`
Python version: `3.7.4 (default, Jul 11 2019, 10:43:21) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.15.1 // Server Version: v1.12.6-aliyun.1`
oc version: `(error: [Errno 13] Permission denied: 'oc')`
OS: `Linux Razer-blade-pro-19 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 39, in main
    runner = Runner(args.logfile, args.verbose)
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 135, in __init__
    self.temp = Path(mkdtemp(prefix="tel-", dir=tmp_dir))
  File "/usr/lib/python3.7/tempfile.py", line 505, in mkdtemp
    _os.mkdir(file, 0o700)
PermissionError: [Errno 13] Permission denied: '/c/temp/tel-2mvr0s7i'

```

### PS

 I think maybe the right path for temp_dir is:

```
tmp_dir = "/mnt/c/temp"
```
Though I don't know if the path is changed in WSL2? Or it's varies with different distro?
I am using a debian based distro called Pengwin, and I also checked the Ubuntu distro.

Maybe it's better to provide a config option?

After I change the temp_dir:

```
0.9 >>> |  
0.9 TEL | END SPAN startup.py:83(set_kube_command)    0.9s  
0.9 TEL | Found ssh -> /usr/bin/ssh   
0.9 TEL | [6] Capturing: ssh -V   
0.9 TEL | [6] captured in 0.03 secs.   
0.9 TEL | Found docker -> /usr/bin/docker   
0.9 TEL | [7] Capturing: docker run --rm -v /mnt/c/temp/tel-g_fan0lr:/tel alpine:3.6 cat /tel/session_id.txt       
1.6   7 | cat: can't open '/tel/session_id.txt': No such file or directory   
2.1 TEL | [7] exit 1 in 1.20 secs.   
2.1 >>> | Local Docker check failed:   
2.1 >>> |   
2.1 >>> | Telepresence's container method requires using a local Docker daemon. Connecting to a remote daemon or a daemon running in a VM does not work at this time. If you are using Minikube's Docker daemon, launch Telepresence in a separate shell that does not have the Minikube Docker environment variables set.
2.1 >>> |  
2.1 >>> | Error: Local Docker daemon required  
2.1 >>> |   
2.1 TEL | EXITING with status code 255   
2.1 >>> | Exit cleanup in progress
```

I failed at Local Docker check.

I use telepresence in WSL with docker client connect to docker daemon in windows Docker Desktop.

Maybe I must wait for the native support of Docker in WSL 2.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
