### ISSUE TITLE
Support Ubuntu 19.10 Eoan

### ISSUE THREAD

**Issue by strigona-worksight** [telepresenceio/telepresence#1177]
From the install script,
https://packagecloud.io/install/repositories/datawireio/telepresence/config_file.list?os=ubuntu&dist=eoan&source=script

Returns: 

```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/datawireio/telepresence

deb https://packagecloud.io/datawireio/telepresence/ubuntu/ eoan main
deb-src https://packagecloud.io/datawireio/telepresence/ubuntu/ eoan main
```
However, `apt update` fails with:
```
...
Err:5 https://packagecloud.io/datawireio/telepresence/ubuntu eoan Release                                           
  404  Not Found [IP: 54.219.157.61 443]  
E: The repository 'https://packagecloud.io/datawireio/telepresence/ubuntu eoan Release' does not have a Release file.
...
```

**Comment by ark3** [comment]
And Fedora 31.

**Comment by ReSearchITEng** [comment]
does telepresence indeed depend on the version?
Maybe make the repo like k8s did, so there won't be issues every new ubuntu version:
`cat /etc/apt/sources.list.d/apt_kubernetes_io.list`

> deb http://apt.kubernetes.io/ kubernetes-xenial main

**Comment by tvvignesh** [comment]
@ark3 Hi. Any fallback which I can use till its published for 19.10? Thanks.

**Comment by softberries** [comment]
On 19.10 you can use 'disco' urls:
```
deb https://packagecloud.io/datawireio/telepresence/ubuntu/ disco main
deb-src https://packagecloud.io/datawireio/telepresence/ubuntu/ disco main
```
just remember to remove all other datawireio repos you have added trying to install telepresence. Then you can proceed with `sudo apt install --no-install-recommends telepresence
` and all works fine.

**Comment by ark3** [comment]
Fixed in #1240

**Comment by sherbang** [comment]
@ark3 while you're at it, you might want to add 20.04 since that's dropping this week.  :-)

**Comment by ark3** [comment]
I added Ubuntu Focal and Fedora 32, but commented them out, as neither is functioning with our release machinery yet. Should be quick to enable them in the near future.
