### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by nathanshurte** [telepresenceio/telepresence#1179]
### What were you trying to do?

proxy into a dev cluster

### What did you expect to happen?

to proxy into the cluster

### What happened instead?

got a stack trace instaed of the docker image spining up a JVM. no other unusual behavior.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'edb', '--swap-deployment', 'cloud-file-service', '--expose', '8080:8080', '--docker-run', '-it', '-e', 'APPLICATION_AWS_S3_BUCKET=cloud-file.public.aapedb2.com', '-e', 'APPLICATION_AWS_S3_HOST=s3.amazonaws.com', '-e', 'APPLICATION_AWS_S3HOST=s3.amazonaws.com', '--rm', 'aap/cloud-file-service:latest']`
Version: `0.99`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.14.7-eks-e9b1d0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Nathan-Shurte-MBP.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 95, in launch
    mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 155, in run_docker_command
    raise RuntimeError("SSH to the network container failed to start.")
RuntimeError: SSH to the network container failed to start.

```

Logs:

```
=/dev/null -q -p 58940 root@127.0.0.1 /bin/true
  51.5 TEL | [144] exit 255 in 0.02 secs.
  51.8 TEL | [145] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 58940 root@127.0.0.1 /bin/true
  51.8 TEL | [145] exit 255 in 0.02 secs.
  52.1 TEL | [146] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 58940 root@127.0.0.1 /bin/true
  52.1 TEL | [146] exit 255 in 0.02 secs.
  52.3 TEL | [147] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 58940 root@127.0.0.1 /bin/true
  52.4 TEL | [147] exit 255 in 0.02 secs.
  52.6 TEL | [148] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 58940 root@127.0.0.1 /bin/true
  52.6 TEL | [148] exit 255 in 0.02 secs.
  52.9 TEL | [149] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 58940 root@127.0.0.1 /bin/true
  52.9 TEL | [149] exit 255 in 0.02 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. Could you try again with the latest version (0.103 at the moment)? There's more logging for SSH failures in newer versions.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
