### ISSUE TITLE
Telepresence fails to attach to existing K8s deployments with TELEPRESENCE_NAMESERVER env var set

### ISSUE THREAD

**Issue by nadundesilva** [telepresenceio/telepresence#1180]
**What were you trying to do ?**
I have a K8s deployment running on Docker for Mac (should apply for minikube and other local setups) named `my-deployment` with the `TELEPRESENCE_NAMESERVER` env var set. I ran `telepresence --deployment my-deployment` command.

**What did you expect to happen ?**
Telepresence to start up using `my-deployment` k8s deployment.

**What happened instead ?**
Got the following error message.
`vpn-tcp method doesn't work with minikube/minishift when using --deployment. Use --swap-deployment or --new-deployment instead`

**Comment by ark3** [comment]
Note that fixing this will give us a path to running the test suite in a local cluster.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
