### ISSUE TITLE
connectivity test using kubernetes.default.svc

### ISSUE THREAD

**Issue by ReSearchITEng** [telepresenceio/telepresence#1181]
Thanks for 0.103
From Release Notes:
"The connectivity test for the inject-tcp method is able to succeed in more cluster configurations. The test hostname is now kubernetes.default instead of kubernetes.default.svc.cluster.local. Thanks to Mohammad Teimori Pabandi for the patch. (#1141) (#1161)"

It is believed `kubernetes.default.svc` is best option (neither kubernetes.default nor kubernetes.default.svc.cluster.local )

Rationale: `kubernetes.default.svc` is the balance between these 2 cases:
1. kubernetes.default.svc.cluster.local -> not good, as someone can name his cluster differently
2. kubernetes.default : in advanced setups, if proxy is defined, people will have a `no_proxy=localhost;.corp.example.com;.svc;.local`

This way we believe kubernetes.default.svc is the right middle ground.
We did not face point 2. right now, as in the pods we have telepresence proxy vars are not defined, but at some point it might happen.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
