### ISSUE TITLE
Swapped pod is unable to communicate with other services in cluster

### ISSUE THREAD

**Issue by shai2017** [telepresenceio/telepresence#1184]
I have started exploring Telepresence for first time.  My Setup is as follows

1. Using Istio 1.15 in GKE Cluster (image-type : Ubuntu)
2. Using Microservice Gateway API pattern.
3. Using CloudSQL for database.
4. Running several services (keeping two for below issue)
5. I am running IDE Intellij in MacOS (High Sierra 10.13.6)

A) So my gateway pod, let's call it myApp pod, is having three container 
      a) MyApp Container
      b) Istio Sidecar
      c) CloudSql proxy container
B) Service is products which provide me products API.

In my first attempt, i am able to successfully swap gateway service with local running gateway service for debugging. But unable to connect to products (other service) in the cluster. It seems Istio Sidecar logic of routing my calls is not working after swapping.

**Comment by ark3** [comment]
Sorry things aren't working out-of-the-box, and thank you for the detailed issue.

Does this work without Istio? Can you try using the `--to-pod` option to forward the appropriate localhost port(s) to the Istio sidecar?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
