### ISSUE TITLE
Doesn't resolve services from nodejs but works fine when hitting directly from telepresense shell

### ISSUE THREAD

**Issue by yagnesh-y** [telepresenceio/telepresence#1185]
I have kubernetes cluster(3 services) on GKE.  I wanted to test a single service from local connecting to the other remote services. I spawned a new shell using the below command on my local machine.

`telepresence --new-deployment test --run-shell`

I can see newly created test deployment on my remote cluster. I can even do
`$ curl http://redis-master.default.svc.cluster.local:6379` and it gets resolved to the proper service from local.  But the same doesn't get resolved when i start my service(nodejs) locally. Fails with below error.

`[stdout#info] A query: b'http://redis-master.default.svc.cluster.local'
2019-11-11T05:21:09+0000 [stdout#info] getaddrinfo error: [Errno -2] Name does not resolve`

Tried with `telepresence -n test -m inject-tcp --run-shell`. This also fails to resolve service and gives the below error(test pod logs). Even here it is able to resolve the service from shell.

` Unhandled Error
	Traceback (most recent call last):
	Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: http://redis-master.default.svc.cluster.local.`

`$ telepresence --version
0.103, Application using FROM node:11.5.0`

**Comment by ark3** [comment]
Interesting. I'm curious to see what's going on under the hood. Could you please pass along the telepresence.log file from that session as a GitHub Gist? I want to see what happens (in the log file) when you `curl` manually and when Node does the same request. Also, is your service a headless service, with `ClusterIP: None` set?

Thank you for your help debugging this.

**Comment by yagnesh-y** [comment]
Hi @ark3 . PFB the telepresense logs for hitting directly from shell and hitting through nodejs respectively.

`2019-11-11T05:20:12+0000 [stdout#info] A query: b'redis-master.default.svc.cluster.local'
 101.6  17 | 2019-11-11T05:20:12+0000 [stdout#info] Result for b'redis-master.default.svc.cluster.local' is ['x.y.z.123']`

`2019-11-11T05:21:04+0000 [stdout#info] A query: b'http://redis-master.default.svc.cluster.local'
 153.5  17 | 2019-11-11T05:21:04+0000 [stdout#info] getaddrinfo error: [Errno -2] Name does not resolve`

I am trying to resolve the service with its fully qualified name as below in my nodejs server.
`'http://redis-master.default.svc.cluster.local`.

Hope this is what you want to check in telepresense logs. Can't share you the entire logs because of private information.

Both my service on my local and the service i'm trying to hit from my local aren't headless services instead exposed by `ClusterIP`. Sorry if i missed this, Does this setup only works for headless services?

Thanks for helping out.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
