### ISSUE TITLE
Error connecting to cluster

### ISSUE THREAD

**Issue by xpolb01** [telepresenceio/telepresence#1188]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'development', '--swap-deployment', 'graphql-gateway', '--expose', '1688:3000', '--run-shell', '--method=inject-tcp']`
Version: `0.103`
Python version: `3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 17:02:57) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]`
kubectl version: `Client Version: v1.16.2 // Server Version: v1.13.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Bogdans-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```

  80.4  45 | Node-Selectors:  node-type=development-entry
  80.4  45 | Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
  80.4  45 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  80.4  45 | Events:
  80.4  45 |   Type    Reason     Age   From                                  Message
  80.4  45 |   ----    ------     ----  ----                                  -------
  80.4  45 |   Normal  Scheduled  49s   default-scheduler                     Successfully assigned development/graphql-gateway-748eab83e67f4c45899d1823b99e2d71-657894f5968wlp to ip-10-11-41-98.ec2.internal
  80.4  45 |   Normal  Pulled     48s   kubelet, ip-10-11-41-98.ec2.internal  Container image "datawire/telepresence-k8s:0.103" already present on machine
  80.4  45 |   Normal  Created    48s   kubelet, ip-10-11-41-98.ec2.internal  Created container
  80.4  45 |   Normal  Started    48s   kubelet, ip-10-11-41-98.ec2.internal  Started container
  80.4 TEL | [45] ran in 4.61 secs.

```

**Comment by xpolb01** [comment]
I tried to remove ::1 from `etc/hosts` as shown here, but it did not help:
https://github.com/telepresenceio/telepresence/issues/783#issuecomment-422850842

**Comment by joaquindiez-taiger** [comment]
I go the same problem, any solution?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since we don't use ssh. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
