### ISSUE TITLE
Telepresence container method fails local Docker check when running inside a container

### ISSUE THREAD

**Issue by townsendduong** [telepresenceio/telepresence#1196]
I'm running Telepresence inside a Docker container using the container method and the Docker daemon on the host system (exposed via socket inside my container).  This used to work before, but now it fails with this error (taken from the log file for more detail):

```
   1.7 TEL | Found docker -> /usr/bin/docker
   1.7 TEL | Found sudo -> /usr/bin/sudo
   1.7 TEL | [7] Running: sudo -n echo -n
   1.7 TEL | [7] ran in 0.01 secs.
   1.7 TEL | [8] Capturing: sudo docker run --rm -v /tmp/tel-c6aamhkx:/tel alpine:3.6 cat /tel/session_id.txt
   2.4   8 | cat: can't open '/tel/session_id.txt': No such file or directory
   2.9 TEL | [8] exit 1 in 1.23 secs.
   2.9 >>> | Local Docker check failed:
   3.0 >>> | 
   3.0 >>> | Telepresence's container method requires using a local Docker daemon. Connecting to a remote daemon or a daemon running in a VM does not work at this time. If you are using Minikube's Docker daemon, launch Telepresence in a separate shell that does not have the Minikube Docker environment variables set.
   3.0 >>> | 
   3.0 >>> | Error: Local Docker daemon required
```

Telepresence correctly determines that sudo is needed for running Docker commands. The local Docker check included in the 0.102 release tries to mount a temp directory (`/tmp/tel-c6aamhkx` in the logs above) as a volume in a new alpine container, but the temp directory is created inside my container while the path that is mounted as a volume is on the host file system. The directory /tel inside the alpine container should be empty, so the result is the error message.

One workaround is to mount the /tmp from the host file system in my container so that the temp directory will be available at the same path on the host, and then the session_id.txt file will be found in the alpine container. This isn't a great solution since it shares a general use directory between the host system and the container.

**Comment by townsendduong** [comment]
Related to #1162 but different root cause

**Comment by an-tex** [comment]
same issue when running directly in mac os, make sure to have /tmp added in file sharing

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
