### ISSUE TITLE
telepresence can't run  with openshift 4.2

### ISSUE THREAD

**Issue by xpflying** [telepresenceio/telepresence#1197]
I tried to run telepresence with openshift4.2, but it was failed.
I was already ran these command.
```
oc adm policy add-scc-to-user anyuid -z default
oc adm policy add-scc-to-user privileged -z default
```
But telepresence work fine with openshift 3.11.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--verbose']`
Version: `0.103`
Python version: `3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.14.0+724e12f93f // Server Version: v1.14.6+76aeb0c`
oc version: `Client Version: openshift-clients-4.2.2-201910250432 // Kubernetes Version: v1.14.6+76aeb0c`
OS: `Darwin mamama 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
---     ----  ----                                     -------
  56.3  50 |   Normal  Scheduled  43s   default-scheduler                        Successfully assigned devtest/telepresence-1574062877-984462-22384-1-8nkz4 to worker-2.jd.example.com
  56.3  50 |   Normal  Pulled     35s   kubelet, worker-2.jd.example.com  Container image "datawire/telepresence-ocp:0.103" already present on machine
  56.3  50 |   Normal  Created    35s   kubelet, worker-2.jd.example.com  Created container telepresence-1574062877-984462-22384
  56.3  50 |   Normal  Started    35s   kubelet, worker-2.jd.example.com  Started container telepresence-1574062877-984462-22384
  56.3 TEL | [50] ran in 2.06 secs.
  56.6  39 | 2019-11-18T07:42:14+0000 [Poll#error] Failed to contact Telepresence client:
  56.6  39 | 2019-11-18T07:42:14+0000 [Poll#error] Connection was refused by other side: 111: Connection refused.
  56.6  39 | 2019-11-18T07:42:14+0000 [Poll#warn] Perhaps it's time to exit?

```

**Comment by xpflying** [comment]
I think I found out where the problem is. Openshift 4.2 uses Kubernetes 1.14 with CRI-O runtime, But the default_capabilities of CRI-O do not include AUDIT_WRITE.
When the openssh server running inside the telepresene container, telepresene cli failed to connect using ssh unless set the container's security context to AUDIT_WRITE capability or privilege=true
```
securityContext:
  capabilities:
    add:
      - AUDIT_WRITE
```
```
securityContext:
  privileged: true
```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 and users have been able to use it with openshift. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
