### ISSUE TITLE
Provide official telepresene cli docker container

### ISSUE THREAD

**Issue by skwasiborski** [telepresenceio/telepresence#1198]
It would be beneficial to be able to run telepresence from within docker container. The main rationale for such container is to use telepresence on windows dev machines (given the development targets linux containers). Another potential use case is to use [vscode develop in container](https://code.visualstudio.com/docs/remote/containers) feature. It can also be used to simplify development setup in some cases.

Currently it is possible to build such container (e.g. [like this](https://github.com/kamil-mrzyglod/DevelopersDays2019/blob/master/Dockerfile)) but it would be great if it would be maintained as part of telepresence. Additionally the issue #1197 requires `/tmp` to be mounted into the container which is not optimal.

**Comment by donnyyung** [comment]
We have instructions about how to run telepresence in a container here: https://www.telepresence.io/docs/latest/reference/inside-container/. 

Please re-open if you run into any issues!
