### ISSUE TITLE
Can't swap a DeploymentConfig on OpenShift

### ISSUE THREAD

**Issue by ebratb** [telepresenceio/telepresence#1200]
### What were you trying to do?

Trying to debug a pod running in OpenShift

### What did you expect to happen?

That telepresence routed all connections to my workstation and then be able to fix code locally before commiting it to git and build a new container for the deploymentconfig in question.

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'api-images', '--run-shell']`
Version: `0.103`
Python version: `3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.16.3 // Server Version: v1.9.1+a0ce1bc657`
oc version: `Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+b4261e0", GitCommit:"b4261e07ed", GitTreeState:"clean", BuildDate:"2019-07-06T03:16:01Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"} // Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`
OS: `Darwin Katara.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64`

```
Background process (sshuttle) exited with return code 1. Command was:
  sshuttle-telepresence -v --dns --method auto -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null' -r telepresence@127.0.0.1:58132 --to-ns 127.0.0.1:9053 172.30.0.0/16

Recent output was:
  self.got_packet(channel, cmd, data)
    File "/Users/username/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/ssnet.py", line 431, in got_packet
      callback(cmd, data)
    File "/Users/username/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/client.py", line 412, in <lambda>
      chan, data, method, listener, srcip=dstip, dstip=srcip, mux=mux)
    File "/Users/username/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/client.py", line 398, in dns_done
      method.send_udp(sock, srcip, dstip, data)
    File "/Users/username/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/methods/__init__.py", line 57, in send_udp
      sock.sendto(data, dstip)
  PermissionError: [Errno 1] Operation not permitted
```

Logs:

```
49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/client.py", line 412, in <lambda>
  57.3  34 |     chan, data, method, listener, srcip=dstip, dstip=srcip, mux=mux)
  57.3  34 |   File "/Users/username/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/client.py", line 398, in dns_done
  57.3  34 |     method.send_udp(sock, srcip, dstip, data)
  57.3  34 |   File "/Users/username/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/methods/__init__.py", line 57, in send_udp
  57.3  34 |     sock.sendto(data, dstip)
  57.3  34 | PermissionError: [Errno 1] Operation not permitted
  57.4 TEL | [34] sshuttle: exit 1
  58.1 TEL | [44] timed out after 1.01 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since we don't use sshuttle. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
