### ISSUE TITLE
EISCONN error on macOS Catalina

### ISSUE THREAD

**Issue by mauriceackel** [telepresenceio/telepresence#1202]
Hi everyone,

I'm facing some issues while using telepresence (0.103) on macOS Catalina. I'm running the following telepresence command:
`telepresence --mount=/tmp/tel_root --swap-deployment user-service --expose 8080 --method inject-tcp`
to connect to my kubernetes cluster. Once connected, I want to start my microservice, which in turn tries to establish a connection to a mongoDB that runs in the cluster. When the service tries to connect, I always get the following error:
```
error: Connection to database failed: failed to connect to server [mongo-0.mongo-gvr.development.svc.cluster.local:27017] on first connect [Error: connect EISCONN **<POD_IP>**:27017 - Local (0.0.0.0:0)
    at internalConnect (net.js:908:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1051:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:63:10) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
```
I can't really figure out what the issue is. The EISCONN error in general should mean that there is already a connection established but I don't get how this could be. Google is not that much of a help in this case.
I tried it from a different machine and it worked there, hence it seems to not be related to my cluster.

Do you guys have any ideas?
Cheers, Maurice

**Comment by Maurice22** [comment]
Anyone else with a similar issue?

**Comment by LipingSun** [comment]
Getting same issue after upgrading nodejs to [v10.20.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.20.0)

Any update for this?

**Comment by LipingSun** [comment]
Any update?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
