### ISSUE TITLE
Cannot connect to forwarded port after swaping the deployment

### ISSUE THREAD

**Issue by adibrastegarnia** [telepresenceio/telepresence#1203]
@ark3 
For a project, we have a set of microservices deployed in a k8s cluster. Each microservice exposes a grpc port that can be used by other microservices to communicate with each other in the cluster. When I swap the deployment using a command like this the new pod does not respond to the requests however it listening to that port when I checked inside its container using netstat:
`telepresence --swap-deployment my-app --run-shell --expose 5150`

Also each service is exposed as ClusterIP. I don't think there should be problem but please let me know. 

P.S. I got it working but I lose the connection frequently, in other words It does not work properly

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
