### ISSUE TITLE
RBAC Problem

### ISSUE THREAD

**Issue by yelhouti** [telepresenceio/telepresence#1204]
This commit https://github.com/telepresenceio/telepresence/commit/7d6388e2ffdbca53a87963df77e315508777a864
 form a year ago introduced a breaking change, that made the documentation wrong (list of required permissions...). A cluster permission (get namespace) is needed for this error message to disappear, I would rather have an error later than have to provide permission to get namespace for all users.

Can this be removed please?

I would gladly make a PR.

Thanks

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, see our updated RBAC docs here: https://www.telepresence.io/docs/latest/reference/rbac/. 

Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
