### ISSUE TITLE
vpn-tcp tunnel did not connect

### ISSUE THREAD

**Issue by eran-davidi-optibus** [telepresenceio/telepresence#1206]
### What were you trying to do?

Swap a deployment with  telepresence --namespace development -m vpn-tcp --also-proxy optibus-redis-master -s optibus-local-euclid-http:euclid-http --expose 5000 --env-json pod-env.json

### What did you expect to happen?

Will not crash and do the vpn tunneling

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--namespace', 'development', '-m', 'vpn-tcp', '--also-proxy', 'optibus-redis-master', '-s', 'optibus-local-euclid-http:euclid-http', '--expose', '5000', '--env-json', 'pod-env.json']`
Version: `0.103`
Python version: `3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.16.1 // Server Version: v1.12.10`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux eran-Latitude-5480 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 310, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
("hellotelepresence-58")'
  45.5 TEL | [152] exit 1 in 0.17 secs.
  45.5 TEL | [153] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-58.a.sanity.check.telepresence.io")'
  45.8 TEL | [153] exit 1 in 0.32 secs.
  45.9 TEL | Wait for vpn-tcp connection: hellotelepresence-59
  45.9 TEL | [154] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-59")'
  46.0 TEL | [154] exit 1 in 0.17 secs.
  46.0 TEL | [155] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-59.a.sanity.check.telepresence.io")'
  46.3 TEL | [155] exit 1 in 0.27 secs.
  46.4 TEL | Wait for vpn-tcp connection: hellotelepresence-60
  46.4 TEL | [156] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-60")'
  46.6 TEL | [156] exit 1 in 0.17 secs.
  46.6 TEL | [157] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-60.a.sanity.check.telepresence.io")'
  46.8 TEL | [157] exit 1 in 0.27 secs.

```

**Comment by eran-davidi-optibus** [comment]
[telepresence.log](https://github.com/telepresenceio/telepresence/files/3883362/telepresence.log)

**Comment by jwestboston** [comment]
I'm seeing this issue as well.  Just a standard `telepresence --method vpn-tcp` and it fails with similar errors.  This is after upgrading from Fedora 30 to Fedora 31 on my desktop.

**Comment by cryptox31** [comment]
I saw this issue as well. I fixed it by adding a DNS server to `/etc/resolv.conf` file. Note that the DNS server lookup worked with ipv6 format and not the ipv4 format. 
```
$ nslookup
> set q=any
> <hostname>
## Should show something like this.
Server:		2002:552:feed::1 <- Add this DNS server to resolv.conf file
Address:	2002:552:feed::1#44
```

**Comment by kodeninja** [comment]
Any movement on this issue?

I installed the latest telepresence on my Mac (`Mojave v10.14.5`). I'm on the company's full VPN tunnel (need to be, to access various internal services). Ran into the same problem as above.

**System Information**

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'rs', '--env-json', 'rs_env.json']`
Version: `0.105`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}`
OS: `Darwin my.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

**Exception**

```python
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 328, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect
```

**Logs**

```bash
play.google.com' is ['172.217.13.78']
 111.8 TEL | [90] timed out after 1.01 secs.
 112.3  73 | c : DNS request from ('172.17.133.176', 53340) to None: 33 bytes
 112.3  73 | c : DNS request from ('172.17.133.176', 50977) to None: 33 bytes
 112.5  40 | 2020-06-09T22:23:39+0000 [stdout#info] A query: b'play.google.com'
 112.5  40 | 2020-06-09T22:23:39+0000 [stdout#info] AAAA query, sending back A instead: b'play.google.com'
 112.5  40 | 2020-06-09T22:23:39+0000 [stdout#info] A query: b'play.google.com'
 112.5  40 | 2020-06-09T22:23:39+0000 [stdout#info] Result for b'play.google.com' is ['172.217.13.78']
 112.5  40 | 2020-06-09T22:23:39+0000 [stdout#info] Result for b'play.google.com' is ['172.217.13.78']
 113.0  73 | c : DNS request from ('172.17.133.176', 53867) to None: 47 bytes
 113.1  40 | 2020-06-09T22:23:40+0000 [stdout#info] A query: b'clientservices.googleapis.com'
 113.1  40 | 2020-06-09T22:23:40+0000 [stdout#info] Result for b'clientservices.googleapis.com' is ['172.217.7.163']
```

In the current situation, where everyone's WFH for the foreseeable future, need to be on the VPN pretty much all the time. Please fix this!

**Comment by donnyyung** [comment]
We have made improvements with Telepresence 2 to work with various VPNs. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version and include which VPN you are using! Thank you!
