### ISSUE TITLE
Working with cronjobs/jobs in kubernetes

### ISSUE THREAD

**Issue by RSWilli** [telepresenceio/telepresence#1208]
I'm using telepresence with Docker to improve my Kubernetes workflow.

When I'm developing a cronjob, I have the following scripts to help me proxy it to the cluster:

```
#!/bin/bash

DEPLOYMENT_NAME=my-job
CONTAINER_NAME=my-org/$DEPLOYMENT_NAME

#
#   Docker Build
#

docker build -f Dockerfile.dev -t $CONTAINER_NAME .

#
#   Environment Variables
# "ENV1",
# "ENV2",
# ....

export ENV1=$(kubectl get configmaps config-env -o=jsonpath='{.data.env1}')
export ENV2=$(kubectl get configmaps config-env -o=jsonpath='{.data.env2}')
# ....


telepresence --method container --docker-run --rm -it -e ENV1 -e ENV2 $CONTAINER_NAME
```

This works flawlessly! I only have one question:

since this is a job which exits after a short time, telepresence cleans up the proxy, which leads to a way bigger startup time compared to the run time of the job. Is there any way to either:

1. keep the proxy open, so i can restart the container in it?
2. change the script so telepresence can startup faster?

thanks in advance!

**Comment by ark3** [comment]
Sorry I didn't respond sooner. You can run a Tel deployment manually and leave it there. Would that help? https://www.telepresence.io/reference/connecting#running-telepresence-manually

**Comment by RSWilli** [comment]
That could help with a little bit of scripting. I assume that `--docker-run` still works this way?

**Comment by ark3** [comment]
Yes

**Comment by RSWilli** [comment]
Nice, Thanks for your help!
