### ISSUE TITLE
Telepresence should not create github issues without user confirmation

### ISSUE THREAD

**Issue by feydan** [telepresenceio/telepresence#1214]
### What were you trying to do?

I encountered an exception in telepresence on my local command line.  This automatically triggered opening the browser to this github issue without asking me.  It included a lot of potentially privileged context that was already sent over the internet to github.

### What did you expect to happen?

I did not expect triggering a command in my local command line with telepresence to automatically send potentially privileged information over the internet to github when encountering an exception.  I would have at the very least expected a prompt to ask if this action should be taken.

### What happened instead?

Encountering an exception in telepresence on my local command line automatically triggered opening the browser to this github issue without asking me.  It included a lot of potentially privileged context that was already sent over the internet to github.

### Automatically included information

[removed]

**Comment by feydan** [comment]
I see this message - maybe I hit enter twice, and since Y is the default it opened before I had a chance to read/affirm.

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]: T: Exit cleanup in progress

**Comment by donnyyung** [comment]
We don't have this feature in Telepresence 2, but if we do add it we'll keep your comments in mind Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/).
