### ISSUE TITLE
Issues with Cloud SQL proxy

### ISSUE THREAD

**Issue by havard024** [telepresenceio/telepresence#1215]
What were you trying to do?
----------------------------
Swap out deployment with local server using the below command:

First I build the docker image locally:
`docker build -t <container> .`

Then I start the container using teleprecence:
`telepresence --namespace stage --swap-deployment <deployment> --docker-run --rm -it -v $(pwd)/src:/src/src <container>`

What did you expect to happen?
---------------------------------
That the server would start locally as normal

What happened instead?
----------------------------
The server failed to start because it could not connect to the database. The postgresql databases is hosted in and by google cloud. To connect to the database the pod is running with a sidecare proxy called `cloud_sql_proxy`.

More information
-----------------

The cloudsql-proxy deployment configuration is taken straight from the [documentation](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine)

Below is a snippet from the documentation above no how to setup the cloudsql-proxy as a side car

```
- name: cloudsql-proxy
  image: gcr.io/cloudsql-docker/gce-proxy:1.16
  command: ["/cloud_sql_proxy",
            "-instances=<INSTANCE_CONNECTION_NAME>=tcp:5432",
            # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
            # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
            # "-ip_address_types=PRIVATE",
            "-credential_file=/secrets/cloudsql/credentials.json"]
  securityContext:
    runAsUser: 2  # non-root user
    allowPrivilegeEscalation: false
  volumeMounts:
    - name: cloudsql-instance-credentials
      mountPath: /secrets/cloudsql
      readOnly: true
```
Below you'll find logs from the `cloudsql-proxy` when it starts successfully:

```
2019/12/10 15:01:10 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2019/12/10 15:01:10 using credential file for authentication; email=<service account>
2019/12/10 15:01:11 Listening on 127.0.0.1:5432 for <google cloud db>
2019/12/10 15:01:11 Ready for new connections
```

Below are the logs from the `cloudsql-proxy` after telepresence swaps the deployment:

```
Retrieving this pod's namespace from the process environment
Pod's namespace is 'stage'
Listening...
2019-12-11T14:14:51+0000 [-] Loading ./forwarder.py...
2019-12-11T14:14:55+0000 [-] /etc/resolv.conf changed, reparsing
2019-12-11T14:14:55+0000 [-] Resolver added ('10.64.0.10', 53) to server list
2019-12-11T14:14:55+0000 [-] SOCKSv5Factory starting on 9050
2019-12-11T14:14:55+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f514c71cdd8>
2019-12-11T14:14:55+0000 [-] DNSDatagramProtocol starting on 9053
2019-12-11T14:14:55+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f514c726198>
2019-12-11T14:14:55+0000 [-] Loaded.
2019-12-11T14:14:55+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.7.0 (/usr/bin/python3.6 3.6.8) starting up.
2019-12-11T14:14:55+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2019-12-11T14:15:24+0000 [-] Received SIGTERM, shutting down.
2019-12-11T14:15:24+0000 [socks.SOCKSv5Factory] (TCP Port 9050 Closed)
2019-12-11T14:15:24+0000 [socks.SOCKSv5Factory#info] Stopping factory <socks.SOCKSv5Factory object at 0x7f514c71cdd8>
2019-12-11T14:15:24+0000 [DNSDatagramProtocol (UDP)] (UDP Port 9053 Closed)
2019-12-11T14:15:24+0000 [DNSDatagramProtocol (UDP)] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f514c726198>
2019-12-11T14:15:24+0000 [-] Main loop terminated.
2019-12-11T14:15:24+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
```

I do not completely understand how telepresence or cloudqsl-proxy works, but from what I can gauge, it seems like the cloudsql-proxy is unable to create the proxy to google cloud which leads me to believe that the port it uses (I've read it uses 3307 to setup the connection to the proxy sever from [here](https://cloud.google.com/sql/docs/mysql/sql-proxy#troubleshooting) the bottom part of the section.) is blocked or proxied to the container I am running or to the local machine where I am running telepresence.

I've tried a couple of solutions, but they were all related to getting the traffic between my pod and the sidecar flowing, which wouldn't help if the cloudsql-proxy isn't starting in the first place.

The database configuration used to connect to the cloud database:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': f'core{POSTFIX}',
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
```

The dockerfile I build and run
**Dockerfile**
```
FROM python:3.6
# Use the full python image to make sure that we are able to compile (if needed)
# any installs

# Make sure all packages have been updated, and the latest pip
# before installing production requirements
RUN apt-get update
RUN apt-get install -y python3-pip python3-dev build-essential libxml2-dev libxslt-dev libffi-dev graphviz

RUN adduser --disabled-password --gecos '' uwsgi
WORKDIR /src
COPY requirements.txt /src/
RUN pip install --upgrade --extra-index-url <private url> -r requirements.txt

COPY requirements_experimental.txt /src/
RUN pip install --upgrade --extra-index-url <private url> -r requirements_experimental.txt

COPY . /src
# Use the base image for production
WORKDIR /src/src

# Expose the default port for Hudya microservices
EXPOSE 9000

# Run the entrypoint file using "prod" default as command (and thus passed in as parameter)

CMD python ./manage.py runserver_plus --nopin 0.0.0.0:9000 --settings=settings.prod
```

I would be most grateful with any tips or hints to help me solve or better my understanding of telepresence. I'm happy to supply more information if needed.

**Comment by ark3** [comment]
Thanks for the detailed issue. Assuming you are using Telepresence 0.103, can you please try adding `--to-pod 5432` to your Telepresence invocation? See also [this documentation](https://www.telepresence.io/reference/limitations#localhost-and-the-pod).

**Comment by havard024** [comment]
Thanks for answering!

Yes, that's correct:
```sh
telepresence --version
0.103
```

I've tried to add `--to-poo 5432` unfortunately no difference the `cloudsql-proxy` is not able to setup the connection to the `proxy-server`. I'll try to create a clean reproducible setup tomorrow, to rule out other factors.

**Comment by havard024** [comment]
I've done some more testing and managed to get it working at last.

`telepresence --to-pod 5432 --from-pod 9000 --namespace stage --swap-deployment <deployment>:<container> --docker-run --rm -it -v $(pwd)/src:/src/src <local container tag>`

Instead of swapping the whole deployment, I only swapped the server container and left the `cloudsql-proxy` sidecar alone. That way the proxy will still work and the only thing I need to do, is as you suggested, `to-pod 5432` to route the database traffic to the `cloudsql-proxy` sidecar and a `--from-pod 9000` to allow traffic to the server container from the outside as normal.

Everything I needed was in the documentation already.

Thank you for the quick answer, I'll close this issue since it's not really an issue with telepresence.
