### ISSUE TITLE
Issue trying to run telepresence

### ISSUE THREAD

**Issue by Jolley71717** [telepresenceio/telepresence#1222]
### What were you trying to do?

I have a cluster set up with services and pods that are able to run a login, gateway, and regular api stuff for users.

I am trying to setup the proxy for my auth service so that I can run the service on my computer and have kubernetes call to my localhost rather than running the service in the cluster.

I scaled the pods down to zero so that I don't have a kubernetes pod that is causing the problem. I have the service running locally on port 6003. The service in kubernetes looks healthy.

I also have init containers that make sure that my db pod is up and functional.

On mac, I was first asked to provide access to the file system. I wasn't quick enough, so the local access was denied, but the telepresence process continued and opened a shell like it was working, but then I granted it access to the file system and I get the error below

When I run `telepresence --container-to-host 6003:6003 --method=vpn-tcp --swap-deployment auth` I get the error included below.

### What did you expect to happen?

I expect a shell to open up that allows for the traffic to flow from the k8s server to my locally running service

### What happened instead?

It appears to fail on image pull. when I look at the unready pods while telepresence is trying to initialize, I see something like this:
```
NAME                                                     READY   STATUS              RESTARTS   AGE
auth-ef029c2b12f54d11b093f5a27cebbcc7-6c46867bd7-k5qwj   0/1     Init:ErrImagePull   0          22s
```

when I describe the pod, I get this
```
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  <unknown>          default-scheduler  Successfully assigned default/auth-ef029c2b12f54d11b093f5a27cebbcc7-6c46867bd7-k5qwj to minikube
  Warning  Failed     30s                kubelet, minikube  Failed to pull image "busybox": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     30s                kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    29s                kubelet, minikube  Back-off pulling image "busybox"
  Warning  Failed     29s                kubelet, minikube  Error: ImagePullBackOff
  Normal   Pulling    14s (x2 over 45s)  kubelet, minikube  Pulling image "busybox"
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--container-to-host', '6003:6003', '--method=vpn-tcp', '--swap-deployment', 'auth']`
Version: `0.103`
Python version: `3.7.6 (default, Dec 27 2019, 09:51:21) 
[Clang 11.0.0 (clang-1100.0.33.16)]`
kubectl version: `Client Version: v1.17.0 // Server Version: v1.17.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Lukes-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 125, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2019-12-31T04:29:40Z', 'message': 'containers with incomplete status: [init-mysql]', 'reason': 'ContainersNotInitialized', 'status': 'False', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-12-31T04:29:40Z', 'message': 'containers with unready status: [auth]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-12-31T04:29:40Z', 'message': 'containers with unready status: [auth]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-12-31T04:29:40Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.103', 'imageID': '', 'lastState': {}, 'name': 'auth', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '192.168.64.2', 'initContainerStatuses': [{'image': 'busybox', 'imageID': '', 'lastState': {}, 'name': 'init-mysql', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'message': 'Back-off pulling image "busybox"', 'reason': 'ImagePullBackOff'}}}], 'phase': 'Pending', 'podIP': '172.17.0.2', 'podIPs': [{'ip': '172.17.0.2'}], 'qosClass': 'BestEffort', 'startTime': '2019-12-31T04:29:40Z'}

```

Logs:

```
-f80baf7c1c534d22aa1c49140a0047ee-5c45564d4c-qpkzz -o json
 119.8 TEL | [363] captured in 0.12 secs.
 120.1 TEL | [364] Capturing: kubectl --context minikube --namespace default get pod auth-f80baf7c1c534d22aa1c49140a0047ee-5c45564d4c-qpkzz -o json
 120.2 TEL | [364] captured in 0.07 secs.
 120.4 TEL | [365] Capturing: kubectl --context minikube --namespace default get pod auth-f80baf7c1c534d22aa1c49140a0047ee-5c45564d4c-qpkzz -o json
 120.7 TEL | [365] captured in 0.24 secs.
 120.8 TEL | [366] Running: sudo -n echo -n
 120.9 TEL | [366] ran in 0.03 secs.
 120.9 TEL | [367] Capturing: kubectl --context minikube --namespace default get pod auth-f80baf7c1c534d22aa1c49140a0047ee-5c45564d4c-qpkzz -o json
 121.0 TEL | [367] captured in 0.10 secs.
 121.3 TEL | [368] Capturing: kubectl --context minikube --namespace default get pod auth-f80baf7c1c534d22aa1c49140a0047ee-5c45564d4c-qpkzz -o json
 121.4 TEL | [368] captured in 0.16 secs.
 121.4 TEL | END SPAN remote.py:104(wait_for_pod)  119.8s

```

**Comment by xujiyou** [comment]
I also encountered this mistake

**Comment by ark3** [comment]
@Jolley71717 Thank you for the detailed report, and my apologies for taking so long to get back to you. 

1. The image pull backoff for "busybox" is weird. Are you able to run that image in your cluster manually? 
2. That issue is with the init container. The Telepresence proxy code never gets a chance to run.
3. The `--container-to-host` option is for the container method only; you're using the vpn-tcp method, so it will have no effect. (This is a bug; Telepresence should tell you that, rather than silently ignoring the option). What are you trying to do with this?

A couple of things could be going wrong here.

1. It's possible that you've run into an incompatibility between Telepresence and macOS Catalina. Are you able to run something much simpler, like
   ```
   telepresence --docker-run --rm -it pstauffer/curl curl -svk https://kubernetes.default/api/
   ```
2. The failure to pull "busybox" might be caused by a DNS loop or a network forwarding loop, if Telepresence somehow failed to detect that you're running with a local cluster. A similar test might shed some light:
   ```
   telepresence --run curl -svk https://kubernetes.default/api/
   ```
