### ISSUE TITLE
Cannot insert sudo password after telepresence crash (iTerm2/macOS)

### ISSUE THREAD

**Issue by cauli** [telepresenceio/telepresence#1224]
This is a weird/unconventional bug, not from telepresence but there might be a workaround :)

It happens on iTerm2 + zsh + macOS for me, haven't tested in other places.

### Summary
Cannot reinsert sudo password after telepresence crashes/exits, in the same terminal session.

### Overview
1. When telepresence is active, it requires you to insert the sudo password.
2. After the connection is lost, telepresence exits and goes back to the shell t erminal.
3. The most common action is to run `telepresence` again
4. Password is asked again if Sudo Password `timestamp_timeout` is expired
5. Cannot insert new password

### How to reproduce
1. `sudo visudo`, edit/add `Defaults     timestamp_timeout = 0` to set the sudo password timeout to `0`
2. Run `telepresence`, insert sudo password
3. Kill the telepresence pod to force a `Connection closed by remote host`
4. Run `telepresence` and *try* to insert sudo password again — my result is that I can never press Return (see image)

![Screen Shot 2020-01-07 at 10 40 20](https://user-images.githubusercontent.com/284283/71885256-442ebf80-313a-11ea-9085-78a46ac51c09.png)

**Comment by potsbo** [comment]
I have a similar problem. And I found out running `reset` before running `telepresence` can mitigate this problem.

**Comment by Rylab** [comment]
> I have a similar problem. And I found out running `reset` before running `telepresence` can mitigate this problem.

Thank you so much! This was driving me crazy. Much better fix than starting a new shell.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
