### ISSUE TITLE
Expose PodIP to swapped deployment

### ISSUE THREAD

**Issue by hkerkhoff** [telepresenceio/telepresence#1232]
Background: we are using a spring/netflix based microservice architecture running on kubernetes. Most of the services are only being used internally and therefore there are no kubernetes-Services. The applications register themself to a Eureka-Server (https://github.com/Netflix/eureka/wiki/Eureka-at-a-glance)

To register a service, spring uses either the IP Address (of the Pod) or the hostname. Its possible to overwrite the hostname and 'fake' another IP address. But if I use telepresence with 'swap-deployment' it looks that there is no chance to get the PODs IP Address. 

https://www.telepresence.io/reference/limitations shows a way to inject the PODs IP from the Downward API

It would be totally great, if you could add the PODs IP as an environment variable like e.g. 'TELEPRESENCE_POD_IP' for 'swapped-deployments'.

Thanks and cheers,
Hendrik

**Comment by donnyyung** [comment]
Telepresence 2 requires there to be Kubernetes Services, but I'll mark this as an `exploration` since maybe it is a feature we want to add in the future.
