### ISSUE TITLE
Can't install on Fedora 31

### ISSUE THREAD

**Issue by serge-wq** [telepresenceio/telepresence#1236]
Apparently there are several packages which are not available in the newest version of Fedora.
```
➜  ~ curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.rpm.sh | sudo bash
Detected operating system as fedora/31.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/datawireio/telepresence/config_file.repo?os=fedora&dist=31&source=script
done.
Installing pygpgme to verify GPG signatures...
datawireio_telepresence-source                                                        549  B/s | 819  B     00:01    
No match for argument: pygpgme
Error: No se pudo encontrar ningún resultado: pygpgme

WARNING: 
The pygpgme package could not be installed. This means GPG verification is not possible for any RPM installed on your system. 
To fix this, add a repository with pygpgme. Usualy, the EPEL repository for your system will have this. 
More information: https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F

Installing yum-utils...
datawireio_telepresence-source                                                        964  B/s | 951  B     00:00    
El paquete dnf-utils-4.0.13-1.fc31.noarch ya está instalado.
Dependencias resueltas.
Nada por hacer.
¡Listo!

WARNING: 
The yum-utils package could not be installed. This means you may not be able to install source RPMs or use other yum features.

Generating yum cache for datawireio_telepresence...
Generating yum cache for datawireio_telepresence-source...

The repository is setup! You can now install packages.
➜  ~ 

```

**Comment by jasonh-logic2020** [comment]
Same here. 

I took the extra step of installing pygpgme by hand using ```pip install``` but still no joy. 

The replacement for ```yum-utils``` is ```dnf-utils```, which I have installed. 

Both  ```datawireio_telepresence``` and ```datawireio_telepresence-source``` repos show up in ```dnf repolist```, and I see the .repo file in ```/etc/yum.repos.d```.

When I try to use ```dnf```, whether to list or to install, it logs that it is updating the repo metadata, but no packages from either repo appear to be available.

HTH

**Comment by ark3** [comment]
To clarify and summarize

1. You get errors from the PackageCloud script (`curl ... | sudo bash`)
2. After that, `sudo dnf install telepresence` doesn't work: no package found

Is that correct?

**Comment by jasonh-logic2020** [comment]
Hello ark3,

Yes, that's it exactly. I get the same errors as serge-wq (with en.us localization).

**Comment by ark3** [comment]
Regrettably we may not be able to fix problem 1. That script is managed by the folks at PackageCloud. That said, I will investigate this further.

The second item will be addressed in the next release. I've added support for Fedora 31 and Ubuntu Eoan. In the meantime, you should be able to tell the PackageCloud script to pretend that you're using Fedora 30. The same packages will work.

**Comment by artsilenkov** [comment]
Cheating fedora fersion to 30
`[~@mylaptop ~]# curl -s0 https://packagecloud.io/install/repositories/datawireio/telepresence/script.rpm.sh > script.rpm.sh
 [~@mylaptop ~]# env os=fedora dist=30 bash script.rpm.sh
`
Works for me, thanks

**Comment by uberbrodt** [comment]
This is still an issue. The workaround does still work, but it's certainly not ideal

**Comment by ark3** [comment]
I'm having trouble replicating this. As in, I see the warnings from the Package Cloud script, but the subsequent installation appears to work fine.

**Comment by ChristianCiach** [comment]
This is still an issue on Fedora 34.

**Comment by khoulyy** [comment]
This is still an issue on Fedora 35.

**Comment by yuowo39** [comment]
This is still an issue on Fedora 38.

I am trying installing pygpgme.

**Comment by Lovinoes** [comment]
This problem also exists under Fedora 39.

Have a nice day, folks!

**Comment by avoidik** [comment]
just in case, `dnf` uses its own implementation via `libdnf` to be able to verify RPM signatures, not `pygpgme` anymore

**Comment by zyrian-nova** [comment]
This is still an issue on Fedora 40.

Good luck!

**Comment by thallgren** [comment]
Please note that the current version of Telepresence (version 2) has never been distributed to a Linux package manager. Whatever is available on packagecloud.io is for Telepresence 1 and no longer supported or maintained.
