### ISSUE TITLE
Weired issue while using istio.

### ISSUE THREAD

**Issue by rverma-jm** [telepresenceio/telepresence#1237]
### What were you trying to do?
Trying to replace a deloyment with envoy injected (through istio)

### What did you expect to happen?
Should be able to replace the required pod keeping envoy proxy intact

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'conductor-ms-cluster', '--env-json', 'conductor.json']`
Version: `0.104`
Python version: `3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)]`
kubectl version: `Client Version: v1.17.1 // Server Version: v1.14.9-eks-c0eccc`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin rohitverma.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 319, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
23 | 2020-01-28T07:14:47+0000 [stdout#info] A query: b'api.github.com'
  75.5  23 | 2020-01-28T07:14:47+0000 [stdout#info] Result for b'api.github.com' is ['13.233.76.15']
  75.6  38 | c : DNS request from ('10.240.0.14', 64565) to None: 60 bytes
  75.6  38 | c : DNS request from ('10.240.0.14', 51286) to None: 33 bytes
  75.7  23 | 2020-01-28T07:14:47+0000 [stdout#info] A query: b'ip-192-168-1-8.ap-south-1.compute.internal'
  75.7  23 | 2020-01-28T07:14:47+0000 [stdout#info] Result for b'ip-192-168-1-8.ap-south-1.compute.internal' is ['192.168.1.8']
  75.7  23 | 2020-01-28T07:14:47+0000 [stdout#info] A query: b'ssl.gstatic.com'
  75.7  23 | 2020-01-28T07:14:47+0000 [stdout#info] Result for b'ssl.gstatic.com' is ['216.58.203.163']
  75.8  38 | c : DNS request from ('10.240.0.14', 50979) to None: 33 bytes
  75.9  23 | 2020-01-28T07:14:47+0000 [stdout#info] A query: b'ssl.gstatic.com'
  75.9  23 | 2020-01-28T07:14:47+0000 [stdout#info] Result for b'ssl.gstatic.com' is ['216.58.203.163']

```

**Comment by ark3** [comment]
Interesting. Could you please pass along the full telepresence.log as a Gist?

**Comment by carlosreyna-bread** [comment]
@ rverma-jm, we are seeing this error while trying to test telepresence with Istio. Network traffic does not seem to be passing through properly and even database connections timeout. Were you able to get any idea as to what was causing your issues?

**Comment by carlosreyna-bread** [comment]
Our issue has to do with the local VPN we run in our machines not been compatible with `vpn-tcp` used my telepresence. Does anyone know of a solution?

**Comment by ipleten** [comment]
Unfortunately, if you use VPN for access you cluster you can't use `vnp-tcp` (at least I haven't managed to make it working) so you could try use either `container` or `inject-tcp` networking methods.

**Comment by ipleten** [comment]
Btw. I've spent some time adapting telepresence to our needs (we need a lot of pre-hooks and pre-run logics, like getting vault tokens and secret, exposing other datasources, implement simple copy-deployment feature), 
So I've managed to run TP with VPN on MacOS using https://github.com/stormbeta/telepresence-wrapper via vpn-tcp docker-wrapper. Give it a try.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
