### ISSUE TITLE
Ctrl + C does not stop running process

### ISSUE THREAD

**Issue by moudidx** [telepresenceio/telepresence#1239]
Telepresence terminal does not stop the running process in the container when you hit Ctrl + C,it seems like it does not able to receive this signal from keyboard.
So, to do, i use Ctrl + Z then ps -ef to list running processes and finally i kill the process manually with kill -9 <pid>

**Comment by ark3** [comment]
Sorry things are not working as described. Can you please provide some more information? What operating system and version are you using? What version of Telepresence? What command are you running? Thank you.

**Comment by moudidx** [comment]
> Sorry things are not working as described. Can you please provide some more information? What operating system and version are you using? What version of Telepresence? What command are you running? Thank you.

**Operating system**: ubuntu 18.04
**Telepresence version**: 0.103
**Command**: a python thread application (micro-service).
[here an image of the issue](https://i.imgur.com/rzwJtgI.png)

**Comment by ark3** [comment]
Okay, that helps. What is the telepresence command? Something like 

    telepresence [some stuff] --docker-run [some stuff]

or whatever it might be. Thank you!

**Comment by moudidx** [comment]
I use Telepresence to swap a kubernetes deployment which uses a docker image uploaded on a provaye registry:

1- Login to docker private registry
`docker <private registry url>`
2- Swap kubernetes deployement
`telepresence --namespace <namespace> --swap-deployment <deployement name> --docker-run --rm -it -v $(pwd in local project):/app -v ~/.pip:/root/.pip <docker private registry url/image:latest> bash`
3-  in my local service session
3.1 `ln -s $TELEPRESENCE_ROOT/var/run/secrets/ /var/run/secrets`
3.2 `pip install -e .`
3.3 run the service thread
`<service_name>  run`
and here Telepresence cannot kill the thread process with ctrl +c

**Comment by ark3** [comment]
Great, that's what I was looking for. Going from there, can you try running your Telepresence command as always, but instead of starting your app, can you try just starting Python and hitting Ctrl-C? You should see `KeyboardInterrupt`. Or try something like `python -c "import time; time.sleep(1000)"` and see whether you can interrupt that with Ctrl-C? Both of those work for me, and get me back to the Bash prompt in my container -- the Telepresence session itself is not interrupted.

**Comment by moudidx** [comment]
I tested what you has suggested to me, Ctrl + C works fine for this kind of scripts. but still not working for python threaded apps if the thread 'run' method execute an infinite loop, you can test it by executing the example below:

`import logging

import threading

import time


def thread_function(name):

    logging.info("Thread %s: starting", name)

    while True:
        a=5

    logging.info("Thread %s: finishing", name)


if __name__ == "__main__":

    format = "%(asctime)s: %(message)s"

    logging.basicConfig(format=format, level=logging.INFO,

                        datefmt="%H:%M:%S")


    logging.info("Main    : before creating thread")

    x = threading.Thread(target=thread_function, args=(1,))

    logging.info("Main    : before running thread")

    x.start()

    logging.info("Main    : wait for the thread to finish")

    # x.join()

    logging.info("Main    : all done")
`

**Comment by ark3** [comment]
I wasn't able to replicate this with my example:

```console
$ telepresence --docker-run --rm -it fedora bash
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Deployment telepresence-1580940854-8033051-9818

T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to
T: specify which ports you want to forward.

T: Setup complete. Launching your container.
[root@telepresence-1580940854-8033051-9818-799f59c78f-wrmdc /]# python3
Python 3.7.4 (default, Aug 12 2019, 14:45:07)
[GCC 9.1.1 20190605 (Red Hat 9.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import threading
>>> import time
>>> t = threading.Thread(target=time.sleep, args=(1000,))
>>> t.start()
>>>
KeyboardInterrupt
>>> t.join()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
>>> def foo():
...   while True:
...     pass
...
>>> t2 = threading.Thread(target=foo)
>>> t2.start()
>>>
>>>
KeyboardInterrupt
>>> t2.join()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
>>>
```

Can you post your example as a [GitHub Gist](https://gist.github.com/)? Then I'll be able to give it a try exactly as you wrote it. Thank you.
