### ISSUE TITLE
Permission denied for Telepresence access

### ISSUE THREAD

**Issue by anshuman2601** [telepresenceio/telepresence#1242]
### What were you trying to do?

Trying to access the application

### What did you expect to happen?

Accessing the help section for the program

### What happened instead?

Flashed me an error giving access denial.

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `(error: [Errno 2] No such file or directory: 'kubectl': 'kubectl')`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux DESKTOP-DTDU5PS 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 39, in main
    runner = Runner(args.logfile, args.verbose)
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 122, in __init__
    os.makedirs(cache_dir, exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/theanshumansahu/.cache/telepresence'

```

Logs:

```
Not available
```

**Comment by ark3** [comment]
Sorry about the crash. It looks like at some point you ran Telepresence using `sudo`, or some other command created a `~/.cache/` directory that is not writeable by you. Or perhaps it's a regular file instead of a directory. Can you please take a look at the permissions for that path? In my case:

```console
$ ls -ld ~/.cache
drwxr-xr-x 46 ark3 ark3 4096 Feb  3 14:34 /home/ark3/.cache
```

shows that `~/.cache` is a directory owned by me and writeable by me.

**Comment by SophiyaYO** [comment]
Hey there :) 
Issue is still here in version 0.109. All is fresh installed but if I want to use anything with `$ telepresence ..` it gets this error:
`Failed to open logfile (/git/telepresence.log): [Errno 13] Permission denied: '/git/telepresence.log'`
