### ISSUE TITLE
Mount permission denied when using in container

### ISSUE THREAD

**Issue by abizerlokhandwala** [telepresenceio/telepresence#1243]
Hey,
I am using vscode's remote containers feature, and I am installing telepresence inside a container instead of my local machine (to basically abstract the concept of telepresence from the user).
Inside my container, when I run the telepresence swap deployment command, this is the error I face
```
 82.0 TEL | [48] Running: sshfs -p 44229 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null telepresence@127.0.0.1:/ /tmp/tel-yna3n1lj/fs
  82.0  48 | fuse: failed to open /dev/fuse: Permission denied
  82.0 TEL | [48] exit 1 in 0.01 secs.
  82.0 >>> | Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see https://github.com/datawire/telepresence/issues/115, otherwise please report a bug, attaching telepresence.log to the bug report: https://github.com/datawire/telepresence/issues/new
  82.1 >>> |
  82.1 >>> | Mount error was: fuse: failed to open /dev/fuse: Permission denied
  82.1 TEL | END SPAN mount.py:30(mount_remote_volumes)    0.0s
```
my `$TELEPRESENCE_ROOT/var/run/secrets/` directory is also empty.
I read about the problems sshfs has with working in containers, but could not understand how to get this workaround to run successfully (https://github.com/vieux/docker-volume-sshfs).

**Comment by ark3** [comment]
First thought: Are you using a privileged container? 

    docker run --rm -it --privileged fedora bash

The resulting container lets me run `sshfs` on my Linux box. That said, if other stuff is working, you're probably already using a privileged container. Just want to confirm that first.

**Comment by abizerlokhandwala** [comment]
Hey Abhay,
Yes I am using a privileged container. I'm using vscode's devcontainer, added the relevant commands in the dockerfile to install telepresence in my container. This the exact run command that vscode automatically runs:
```
docker run -a STDOUT -a STDERR -p 127.0.0.1:8000:8000 --mount type=bind,source=/Users/abizerlokhandwala/projects/mock_repo/hello_world,target=/workspaces/hello_world,consistency=cached --mount source=/Users/abizerlokhandwala/.aws,target=/home/vscode/.aws,type=bind,consistency=cached,readonly --mount source=/Users/abizerlokhandwala/.kube,target=/home/vscode/.kube,type=bind,consistency=cached,readonly -l vsch.quality=stable -l vsch.remote.devPort=0 -l vsch.local.folder=/Users/abizerlokhandwala/projects/mock_repo/hello_world --privileged --entrypoint /bin/sh vsc-hello_world-a202b5895a5ec3c0da113e45f2f26cc2 -c echo Container started ;  while sleep 1; do :; done
```

**Comment by ark3** [comment]
Okay, that makes sense. Could you please share the Dockerfile as well? I'd like to try to replicate this at my end.

**Comment by abizerlokhandwala** [comment]
This dockerfile lies in the `.devcontainer` folder for vscode to detect
[Dockerfile.txt](https://github.com/telepresenceio/telepresence/files/4162475/Dockerfile.txt)

**Comment by abizerlokhandwala** [comment]
Hey, any progress with this issue?
