### ISSUE TITLE
Install from source instructions should explain when `sudo` is needed

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#1244]
Generally speaking, `sudo` is not required to install from source, as long as you have write permission to the target directory. Without bloating that section too much, it would be good to get that across.

**Comment by himanshu007-creator** [comment]
i would like to work on this issue.Can you guide me how to get started?

**Comment by ark3** [comment]
By "install from source documentation" I'm referring to [this section](https://www.telepresence.io/reference/install#install-from-source). You might expect the source for that page to be in `docs/reference/install.md` in this repository, but it's actually in a separate file that gets included into a couple of pages by the website builder: Look at `docs/macros.html` and search for "from source" to see the original.

Does that get you started? Please feel free to ask further questions; I'll try to answer with less delay.

**Comment by donnyyung** [comment]
This shouldn't be an issue in telepresence 2 since you don't need `sudo` for make. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
