### ISSUE TITLE
Initial cluster check failure should say that `kubectl` needs to work

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#1250]
Right now we emit a message like

    T: Error: Unable to find cluster information
    T: No current-context set. Please use the --context option to 
    T: explicitly set the context.

This is all fine, but some higher-level explanation would be helpful as well, probably linking to documentation:

    T: Telepresence uses kubectl/oc to access your Kubernetes/OpenShift
    T: cluster. Please make sure kubectl or oc are able to connect.
    T: See https://www.telepresence.io/discussion/overview#cluster

That link doesn't exist yet (no cluster section), so we'll need to write that too.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since I don't believe you need to use sudo to run `make build`. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
