### ISSUE TITLE
Option to run .bashrc

### ISSUE THREAD

**Issue by rbren** [telepresenceio/telepresence#1256]
Per https://github.com/telepresenceio/telepresence/pull/127, running `.bashrc` had the potential to cause issues.

A couple years later, @LukeShu hypothesizes:
> not running .bashrc is a hack for a problem that no longer exists.

It would be good to at least add a CLI flag that would allow users to run `.bashrc` if they so choose.

**Comment by rbren** [comment]
Yes - this is still a request

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since we don't use torsocks. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
