### ISSUE TITLE
What happens when other devs (concurrent multiple users ) is using ` - swap-deployment`?

### ISSUE THREAD

**Issue by mokeddes** [telepresenceio/telepresence#1265]
We are faced with a machine limitation for working locally, and we are looking for a solution not to launch everything (docker-compose) on our machine to be able to work locally.

Telepresence seems to answer our problem, however we would like to know if it is possible to use it with several developers at the same time on the same cluster ?

**Comment by donnyyung** [comment]
You're in luck! Telepresence 2 was designed this this in mind. Here's a doc talking about your specific issue: https://www.telepresence.io/docs/latest/howtos/preview-urls/ Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/)!
