### ISSUE TITLE
start telepresence on mac requires approval on Mojave 

### ISSUE THREAD

**Issue by jrgwv** [telepresenceio/telepresence#1267]
### What were you trying to do?
Start telepresence on Mac, requires sudo and then opens system preferences to add an approval. However in looking through each item available for approval telepresence is not listed. The Mounting remote volumes failed, they will be unavailable in this session   
(please tell us)

### What did you expect to happen?
Only to enter sudo credentials and have the command succeed 

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.17.3 // Server Version: v1.14.9-eks-502bfb`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin C02NP2D7G3QN-gainesjr 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 319, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
("hellotelepresence-68")'
  70.3 TEL | [177] exit 1 in 0.17 secs.
  70.3 TEL | [178] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-68.a.sanity.check.telepresence.io")'
  70.4 TEL | [178] exit 1 in 0.13 secs.
  70.5 TEL | Wait for vpn-tcp connection: hellotelepresence-69
  70.5 TEL | [179] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-69")'
  70.7 TEL | [179] exit 1 in 0.19 secs.
  70.7 TEL | [180] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-69.a.sanity.check.telepresence.io")'
  70.9 TEL | [180] exit 1 in 0.13 secs.
  71.0 TEL | Wait for vpn-tcp connection: hellotelepresence-70
  71.0 TEL | [181] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-70")'
  71.1 TEL | [181] exit 1 in 0.18 secs.
  71.1 TEL | [182] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-70.a.sanity.check.telepresence.io")'
  71.3 TEL | [182] exit 1 in 0.12 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
