### ISSUE TITLE
running telepresense command

### ISSUE THREAD

**Issue by shubhamyelikar** [telepresenceio/telepresence#1269]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.104`
Python version: `3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.15.1 // Server Version: v1.13.12`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux EMPID19029 4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
by a Secret)
  66.2  42 |     SecretName:  default-token-4bj42
  66.2  42 |     Optional:    false
  66.2  42 | QoS Class:       Burstable
  66.2  42 | Node-Selectors:  <none>
  66.2  42 | Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
  66.2  42 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  66.2  42 | Events:
  66.2  42 |   Type    Reason     Age   From                 Message
  66.2  42 |   ----    ------     ----  ----                 -------
  66.2  42 |   Normal  Scheduled  43s   default-scheduler    Successfully assigned triliovault-integration/telepresence-1584167395-9819498-9741-7d86db8d5c-8mgn5 to nodes-pcbt
  66.3  42 |   Normal  Pulled     43s   kubelet, nodes-pcbt  Container image "datawire/telepresence-k8s:0.104" already present on machine
  66.3  42 |   Normal  Created    43s   kubelet, nodes-pcbt  Created container
  66.3  42 |   Normal  Started    42s   kubelet, nodes-pcbt  Started container
  66.3 TEL | [42] ran in 5.26 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since we don't use ssh. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
