### ISSUE TITLE
Nodename nor servname provided, or not known error

### ISSUE THREAD

**Issue by shahakash28** [telepresenceio/telepresence#1271]
### What were you trying to do?

To proxy local service to a Kubernetes cluster

### What did you expect to happen?

Expected to succeed

### What happened instead?

It failed due to  socket.gaierror: [Errno 8] nodename nor servname provided, or not known
(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--verbose', '--logfile', './telepresence.log', '--namespace', '<name-space>', '--swap-deployment', '<swap_container>', '--expose', '5556', '--run', './bin/iam', 'serve', './config/config-telepresence.yaml']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.14.2 // Server Version: v1.14.10-gke.17`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin C02XT4NVJHD3 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

```
Background process (sshuttle) exited with return code 99. Command was:
  sshuttle-telepresence -v --dns --method auto -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null' -r telepresence@127.0.0.1:49450 --to-ns 127.0.0.1:9053 10.0.0.0/20 10.12.7.0/24 10.12.1.0/24 10.12.5.0/24 10.12.9.0/24 10.12.8.0/24 10.12.2.0/24

Recent output was:
  DNS enabled: True
  TCP redirector listening on ('::1', 12300, 0, 0).
  TCP redirector listening on ('127.0.0.1', 12300).
  DNS listening on ('::1', 12300, 0, 0).
  DNS listening on ('127.0.0.1', 12300).
  Starting client with Python version 3.7.7
  c : connecting to server...
  Warning: Permanently added '[127.0.0.1]:49450' (ECDSA) to the list of known hosts.
  Connection to 127.0.0.1 closed by remote host.
  c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

Logs:

```
pn-tcp connection: hellotelepresence-34
  46.9 TEL | [103] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-34")'
  47.0 103 | Traceback (most recent call last):
  47.0 103 |   File "<string>", line 1, in <module>
  47.0 103 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  47.0 TEL | [103] exit 1 in 0.13 secs.
  47.0 TEL | [104] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-34.a.sanity.check.telepresence.io")'
  47.1 104 | Traceback (most recent call last):
  47.1 104 |   File "<string>", line 1, in <module>
  47.1 104 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  47.2 TEL | [104] exit 1 in 0.13 secs.
  47.2  30 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  48.4  30 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  48.4  29 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1

```

**Comment by jsingh310** [comment]
Did you ever get this resolved?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since we don't use sshuttle. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
