### ISSUE TITLE
RuntimeError: vpn-tcp tunnel did not connect during following first tutorial with VPN

### ISSUE THREAD

**Issue by davix** [telepresenceio/telepresence#1272]
### What were you trying to do?
Following this:
https://www.telepresence.io/tutorials/kubernetes

The kubernetes cluster is inside Corporate network. I was using VPN to connect to Corporate network.

### What did you expect to happen?

below should succeed:

> $ curl $HELLOWORLD/file.txt
> hello from your laptop

### What happened instead?

Got below info from my laptop telepresence.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'hello-world', '--expose', '8000', '--run', 'python3', '-m', 'http.server', '8000']`
Version: `0.104`
Python version: `3.7.6 (default, Dec 30 2019, 19:38:28) 
[Clang 11.0.0 (clang-1100.0.33.16)]`
kubectl version: `Client Version: v1.17.1 // Server Version: v1.14.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin pekwhuang-mba-92.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 319, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
c : DNS request from ('10.240.134.23', 57359) to None: 55 bytes
  93.3  16 | 2020-03-18T03:55:20+0000 [stdout#info] Result for b'hellotelepresence-7.arubanetworks.com' is ['127.0.0.1']
  93.9  48 | c : DNS request from ('10.240.134.23', 57359) to None: 55 bytes
  94.3  16 | 2020-03-18T03:55:21+0000 [stdout#info] Result for b'hellotelepresence-7.arubanetworks.com' is ['127.0.0.1']
  95.9  48 | c : DNS request from ('10.240.134.23', 57359) to None: 55 bytes
  96.3  16 | 2020-03-18T03:55:23+0000 [stdout#info] Result for b'hellotelepresence-7.arubanetworks.com' is ['127.0.0.1']
  97.9 TEL | [64] timed out after 5.02 secs.
  97.9 TEL | [65] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-7.a.sanity.check.telepresence.io")'
  97.9  48 | c : DNS request from ('10.240.134.23', 56922) to None: 68 bytes
  98.4  16 | 2020-03-18T03:55:25+0000 [stdout#info] Sanity check: b'hellotelepresence-7.a.sanity.check.telepresence.io'
  98.9 TEL | [65] timed out after 1.02 secs.

```

**Comment by donnyyung** [comment]
We have tried a number of VPNs on Telepresence 2 and have been successful. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please create an issue if our latest version doesn't work with your VPN, as well as which VPN your company uses.

**Comment by davix** [comment]
Great to know there's new version 2! will try it
