### ISSUE TITLE
ignis proxy --rebuild

### ISSUE THREAD

**Issue by tinder-yueminyu** [telepresenceio/telepresence#1273]
### What were you trying to do?

rebuild?

### What happened instead?

yueminyu~/src/palo(hw_3|✚1) % ignis proxy --rebuild
Starting your proxy at nostalgic-franklin.yuemin-yu.svc.cluster.local
T: Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom DNS implementations are not supported.
T: For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using the existing proxy Deployment nostalgic-franklin

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 125, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 201, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 133, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-03-22T18:48:03Z', 'message': "0/220 nodes are available: 1 Insufficient pods, 219 node(s) had taints that the pod didn't tolerate.", 'reason': 'Unschedulable', 'status': 'False', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'BestEffort'}

Here are the last few lines of the logfile (see /Users/yyu/.ignis/telepresence.log for the complete logs):

 124.6 TEL | [56] captured in 1.84 secs.
 124.8 TEL | [57] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 126.6 TEL | [57] captured in 1.84 secs.
 126.9 TEL | [58] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 128.8 TEL | [58] captured in 1.85 secs.
 129.0 TEL | [59] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 130.8 TEL | [59] captured in 1.84 secs.
 131.1 TEL | [60] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 133.1 TEL | [60] captured in 2.05 secs.
 133.4 TEL | [61] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 135.0 TEL | [61] captured in 1.65 secs.
 135.0 TEL | END SPAN remote.py:112(wait_for_pod)  121.2s

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]: y
T: Exit cleanup in progress

T: Telepresence 0.104 is available (you're running 0.102). https://www.telepresence.io/reference/changelog

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--logfile', '/Users/yyu/.ignis/telepresence.log', '-d', 'nostalgic-franklin', '--method', 'inject-tcp', '--expose', '12000', '--namespace', 'yuemin-yu', '--context', 'd1-ue1', '--mount', '/tmp/20200322114802', '--run-shell']`
Version: `0.102`
Python version: `3.7.4 (default, Oct 12 2019, 18:55:28) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.13.4 // Server Version: v1.15.10-eks-bac369`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin yueminyu 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 125, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 201, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 133, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-03-22T18:48:03Z', 'message': "0/220 nodes are available: 1 Insufficient pods, 219 node(s) had taints that the pod didn't tolerate.", 'reason': 'Unschedulable', 'status': 'False', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'BestEffort'}

```

Logs:

```
yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 124.6 TEL | [56] captured in 1.84 secs.
 124.8 TEL | [57] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 126.6 TEL | [57] captured in 1.84 secs.
 126.9 TEL | [58] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 128.8 TEL | [58] captured in 1.85 secs.
 129.0 TEL | [59] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 130.8 TEL | [59] captured in 1.84 secs.
 131.1 TEL | [60] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 133.1 TEL | [60] captured in 2.05 secs.
 133.4 TEL | [61] Capturing: kubectl --context d1-ue1 --namespace yuemin-yu get pod nostalgic-franklin-67fbcbd96-frggz -o json
 135.0 TEL | [61] captured in 1.65 secs.
 135.0 TEL | END SPAN remote.py:112(wait_for_pod)  121.2s

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
