### ISSUE TITLE
failed to swap deployment with inject-tcp method

### ISSUE THREAD

**Issue by pacogomez** [telepresenceio/telepresence#1274]
### What were you trying to do?

swap a deployment in k3s for a local process for debugging

### What did you expect to happen?

be able to route the requests to the local process

### What happened instead?

for a few seconds the routing happened but after a few moments, the error below happened

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'my-microservice', '--expose', '8090:8080', '--run-shell', '--method', 'inject-tcp']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.17.4 // Server Version: v1.16.3-k3s.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ws.company.com 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 104, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
fault'"'"', 443))'
  19.3  82 | Traceback (most recent call last):
  19.3  82 |   File "<string>", line 1, in <module>
  19.3  82 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  19.3 TEL | [82] exit 1 in 0.16 secs.
  19.4 TEL | [83] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  19.6  83 | Traceback (most recent call last):
  19.6  83 |   File "<string>", line 1, in <module>
  19.6  83 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  19.6 TEL | [83] exit 1 in 0.15 secs.
  19.7 TEL | [84] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  19.8  84 | Traceback (most recent call last):
  19.8  84 |   File "<string>", line 1, in <module>
  19.8  84 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  19.8 TEL | [84] exit 1 in 0.16 secs.
  19.8 TEL | END SPAN local.py:42(set_up_torsocks)   15.1s

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
