### ISSUE TITLE
not working with kubectl 1.18

### ISSUE THREAD

**Issue by yoeldovidcohen** [telepresenceio/telepresence#1279]
### What were you trying to do?

try out telepresence

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--docker-run', '--rm', '-it', 'pstauffer/curl', 'curl', 'http://hello-world:8000/']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.18.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin yoeldovids-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
ault delete --ignore-not-found svc,deploy --selector=telepresence=c3754e9d47724f4f9ac704c4accafa40
   1.5  10 | No resources found
   1.5 TEL | [10] ran in 0.06 secs.
   1.5 TEL | [11] Running: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1585494857-9828548-2026 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=c3754e9d47724f4f9ac704c4accafa40
   1.5  11 | pod/telepresence-1585494857-9828548-2026 created
   1.5 TEL | [11] ran in 0.07 secs.
   1.5 TEL | END SPAN deployment.py:108(create_new_deployment)    0.1s
   1.5 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   1.5 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   1.5 TEL | [12] Capturing: kubectl --context minikube --namespace default get deployment -o json --selector=telepresence=c3754e9d47724f4f9ac704c4accafa40
   1.6 TEL | [12] captured in 0.06 secs.
   1.6 TEL | END SPAN remote.py:75(get_deployment_json)    0.1s

```

**Comment by biosugar0** [comment]
I had the same problem.
maybe, telepresence does not work with kubectl v1.18.0. 
I had to downgrade to v1.17.0.

**Comment by imic07** [comment]
执行 kubectl version  查看客户端和服务端的版本号。客户端不能高于服务端。

**Comment by davix** [comment]
> 执行 kubectl version 查看客户端和服务端的版本号。客户端不能高于服务端。我的就是服务端是v1.17.4而客户端是最新的，导致异常。

Actually client version can be higher. My cluster is 1.14 while kubectl is 1.17. They work fine. Issue appears when using kubectl 1.18.
BTW. Using English here is better.

**Comment by donnyyung** [comment]
I think this should work in Telepresence 2 but we should verify.
