### ISSUE TITLE
crash on first run

### ISSUE THREAD

**Issue by jlgeering** [telepresenceio/telepresence#1280]
### What were you trying to do?

start telepresence

### What did you expect to happen?

it not to crash

### What happened instead?

it crashed and very politely asked me to submit a bug report

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.15.9-gke.22`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ufg-jlg-15 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
 play --namespace jlg delete --ignore-not-found svc,deploy --selector=telepresence=131433b0aa684c3f932cec6e76246626
   1.5   9 | No resources found
   1.5 TEL | [9] ran in 0.13 secs.
   1.5 TEL | [10] Running: kubectl --context play --namespace jlg run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1585547639-954758-79410 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=131433b0aa684c3f932cec6e76246626
   1.7  10 | pod/telepresence-1585547639-954758-79410 created
   1.7 TEL | [10] ran in 0.25 secs.
   1.7 TEL | END SPAN deployment.py:108(create_new_deployment)    0.4s
   1.7 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   1.7 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   1.7 TEL | [11] Capturing: kubectl --context play --namespace jlg get deployment -o json --selector=telepresence=131433b0aa684c3f932cec6e76246626
   1.8 TEL | [11] captured in 0.11 secs.
   1.8 TEL | END SPAN remote.py:75(get_deployment_json)    0.1s

```

**Comment by jlgeering** [comment]
most probably a duplicate of #1279

**Comment by jlgeering** [comment]
possible cause: I had an openvpn (using Viscosity) tunnel active, and if this is really the problem, then that would change this issue to either:

allow telepresence to be run when another tunnel is already active

or

better error message when crashing due to other tunnel being active

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since we have had success with openvpn. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
