### ISSUE TITLE
SSH to the cluster failed to start

### ISSUE THREAD

**Issue by tinder-shivagopalan** [telepresenceio/telepresence#1282]
### What were you trying to do?
ignis proxy -p 12001 sketchservice
(please tell us)

### What did you expect to happen?
Proxied container was expected to start
(please tell us)

### What happened instead?
SSH to the cluster failed to start
(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--logfile', '/Users/shivagopalan/.ignis/telepresence.log', '-d', 'sketchservice', '--method', 'container', '--expose', '12001:12100', '--namespace', 'shiva-gopalan', '--context', 'd1-ue1', '--mount', '/tmp/20200331111254', '--docker-run', '-it', '--rm', '-v', '/Users/shivagopalan:/Users/shivagopalan', '-v', '/Users/shivagopalan/.m2:/root/.m2:cached', '-v', '/Users/shivagopalan/.ivy2:/root/.ivy2:cached', '-v', '/tmp/20200331111254:/tmp/20200331111254', '-e', 'HOME=/Users/shivagopalan', '-v', '/var/run/docker.sock:/var/run/docker.sock', '--workdir', '/Users/shivagopalan/palo', '-p', '12001:12001', '--name', 'sketchservice', 'sketchservice', '/bin/bash']`
Version: `0.102`
Python version: `3.7.6 (default, Jan 13 2020, 15:10:26) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.15.5 // Server Version: v1.15.10-eks-bac369`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin shivagopalan 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 113, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 69, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
106 |   Normal  Pulled     104s  kubelet, ip-10-48-16-76.ec2.internal  Container image "405753365262.dkr.ecr.us-east-1.amazonaws.com/k8s/envoy:v1.13.1" already present on machine
  45.8 106 |   Normal  Created    104s  kubelet, ip-10-48-16-76.ec2.internal  Created container mesh
  45.8 106 |   Normal  Started    104s  kubelet, ip-10-48-16-76.ec2.internal  Started container mesh
  45.8 106 |   Normal  Pulling    104s  kubelet, ip-10-48-16-76.ec2.internal  Pulling image "405753365262.dkr.ecr.us-east-1.amazonaws.com/deploy/envoyhotrestart:latest"
  45.8 106 |   Normal  Pulled     104s  kubelet, ip-10-48-16-76.ec2.internal  Successfully pulled image "405753365262.dkr.ecr.us-east-1.amazonaws.com/deploy/envoyhotrestart:latest"
  45.8 106 |   Normal  Created    103s  kubelet, ip-10-48-16-76.ec2.internal  Created container envoy-hot-restarter
  45.8 106 |   Normal  Started    103s  kubelet, ip-10-48-16-76.ec2.internal  Started container envoy-hot-restarter
  45.8 TEL | [106] ran in 3.14 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
