### ISSUE TITLE
telepresence breaks with kubectl v1.18.0

### ISSUE THREAD

**Issue by rr0hit** [telepresenceio/telepresence#1283]
### What were you trying to do?

Run telepresence with kubectl 1.18.0

### What did you expect to happen?

telepresence to work

### What happened instead?

telepresence exits with attached stack trace

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.14.9-eks-502bfb`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin CAP-LAP-1102.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
resources found
  16.3 TEL | [9] ran in 2.67 secs.
  16.3 TEL | [10] Running: kubectl --context <REDACTED> --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1585680454-2528372-16186 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=a069342d287c4284b22f2e588febf6e0
  18.6  10 | pod/telepresence-1585680454-2528372-16186 created
  18.6 TEL | [10] ran in 2.24 secs.
  18.6 TEL | END SPAN deployment.py:108(create_new_deployment)    4.9s
  18.6 TEL | BEGIN SPAN remote.py:142(get_remote_info)
  18.6 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
  18.6 TEL | [11] Capturing: kubectl --context <REDACTED> --namespace default get deployment -o json --selector=telepresence=a069342d287c4284b22f2e588febf6e0
  20.6 TEL | [11] captured in 2.04 secs.
  20.6 TEL | END SPAN remote.py:75(get_deployment_json)    2.0s

```

**Comment by rr0hit** [comment]
"kubectl run" now only generates pods and not deployment as telepresence expects.

https://kubernetes.io/docs/setup/release/notes/#kubectl

**Comment by rr0hit** [comment]
Duplicate of #1279

**Comment by Linxi-brave** [comment]
kubectl 版本太高了。客户端的版本不能比服务端的大。要降低 kubectl的版本。
macbook执行如下：
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/darwin/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
kubectl version --client

**Comment by donnyyung** [comment]
Closing in favor of #1279
