### ISSUE TITLE
Try to run new deployment

### ISSUE THREAD

**Issue by Mohamed-Adel-H** [telepresenceio/telepresence#1285]
### What were you trying to do?

run new deployment

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--new-deployment', 'mohamedconnectio']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.17.4 // Server Version: v1.15.8-gke.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux trender 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
rstable
  88.7  61 | Node-Selectors:  <none>
  88.7  61 | Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
  88.7  61 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  88.7  61 | Events:
  88.7  61 |   Type    Reason     Age   From                                    Message
  88.7  61 |   ----    ------     ----  ----                                    -------
  88.7  61 |   Normal  Scheduled  53s   default-scheduler                       Successfully assigned default/mohamedconnectio-6fd4869bf6-d77s4 to gke-dev-nodes-2-d3cfe86e-bx9s
  88.7  61 |   Normal  Pulled     52s   kubelet, gke-dev-nodes-2-d3cfe86e-bx9s  Container image "datawire/telepresence-k8s:0.104" already present on machine
  88.7  61 |   Normal  Created    52s   kubelet, gke-dev-nodes-2-d3cfe86e-bx9s  Created container mohamedconnectio
  88.7  61 |   Normal  Started    52s   kubelet, gke-dev-nodes-2-d3cfe86e-bx9s  Started container mohamedconnectio
  88.7 TEL | [61] ran in 6.90 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since we don't use SSH. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
