### ISSUE TITLE
SSH to the network container failed to start

### ISSUE THREAD

**Issue by GinoPane** [telepresenceio/telepresence#1286]
### What were you trying to do?

Run telepresence connection to the instance 

### What did you expect to happen?

Successful run and connection

### What happened instead?

(the traceback is automatically included, see below)

Fixed by re-running of the command

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'backend', '--docker-run', '-it', '--rm', '--env-file=.env.local', '-w', '/application', '-v', '/home/...', 'container']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.15.10-eks-bac369 // Server Version: v1.14.9-eks-502bfb`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux s-karavai-nix 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 169, in launch
    pod_info,
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 141, in run_docker_command
    raise RuntimeError("SSH to the network container failed to start.")
RuntimeError: SSH to the network container failed to start.

```

Logs:

```
=/dev/null -q -p 46103 root@127.0.0.1 /bin/true
  46.3 TEL | [139] exit 255 in 0.02 secs.
  46.6  28 | dd1da303dc2c: Verifying Checksum
  46.6  28 | dd1da303dc2c: Download complete
  46.6 TEL | [140] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 46103 root@127.0.0.1 /bin/true
  46.6 TEL | [140] exit 255 in 0.02 secs.
  46.9 TEL | [141] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 46103 root@127.0.0.1 /bin/true
  46.9 TEL | [141] exit 255 in 0.02 secs.
  47.1 TEL | [142] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 46103 root@127.0.0.1 /bin/true
  47.2 TEL | [142] exit 255 in 0.01 secs.
  47.4 TEL | [143] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 46103 root@127.0.0.1 /bin/true
  47.4 TEL | [143] exit 255 in 0.02 secs.
  49.0  28 | 01c35bd6e758: Verifying Checksum
  49.0  28 | 01c35bd6e758: Download complete

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since we don't use SSH. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
