### ISSUE TITLE
Unable to find image 'alpine:3.6' locally

### ISSUE THREAD

**Issue by GinoPane** [telepresenceio/telepresence#1287]
### What were you trying to do?

To run the telepresence connection 

### What did you expect to happen?

To connect successfully 

### What happened instead?

(the traceback is automatically included, see below)

Fixed by running `docker run --rm -v /tmp/tel-ajwjo_ly:/tel alpine:3.6` locally

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'backend', '--docker-run', '-it', '--rm', '--env-file=.env.local', '-w', '/application', '-v', '/home/...', 'image']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.15.10-eks-bac369 // Server Version: v1.14.9-eks-502bfb`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux s-karavai-nix 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 52, in main
    launch = outbound.setup(runner, args)
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 183, in setup
    return setup_container(runner, args)
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 141, in setup_container
    reveal=True,
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 483, in get_output
    env,
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 426, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.TimeoutExpired: Command '['docker', 'run', '--rm', '-v', '/tmp/tel-ajwjo_ly:/tel', 'alpine:3.6', 'cat', '/tel/session_id.txt']' timed out after 30 seconds

```

Logs:

```
7 secs.
   0.7 TEL | [4] Capturing: kubectl --context arn:aws:eks:eu-west-2:375550435474:cluster/dev get ns siarhei-karavai
   1.3 TEL | [4] captured in 0.53 secs.
   1.3 TEL | [5] Capturing: kubectl --context arn:aws:eks:eu-west-2:375550435474:cluster/dev api-versions
   1.8 TEL | [5] captured in 0.57 secs.
   1.8 TEL | Command: kubectl 1.15.10-eks-bac369
   1.8 TEL | Context: arn:aws:eks:eu-west-2:375550435474:cluster/dev, namespace: siarhei-karavai, version: 1.14.9-eks-502bfb
   1.8 TEL | END SPAN startup.py:83(set_kube_command)    1.8s
   1.8 TEL | Found ssh -> /usr/bin/ssh
   1.8 TEL | [6] Capturing: ssh -V
   1.8 TEL | [6] captured in 0.01 secs.
   1.8 TEL | Found docker -> /usr/bin/docker
   1.8 TEL | [7] Capturing: docker run --rm -v /tmp/tel-ajwjo_ly:/tel alpine:3.6 cat /tel/session_id.txt
   1.9   7 | Unable to find image 'alpine:3.6' locally
  21.9   7 | 3.6: Pulling from library/alpine
  23.8   7 | 5a3ea8efae5d: Pulling fs layer
  31.9 TEL | [7] timed out after 30.01 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
