### ISSUE TITLE
deploy telepresence to a raspberry pi / k3s cluster

### ISSUE THREAD

**Issue by costap** [telepresenceio/telepresence#1301]
### What were you trying to do?

telepresence --run ng serve

### What did you expect to happen?

start angular app proxying requests to service in my remote cluster

### What happened instead?

Failed to start

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run', 'ng', 'serve']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.17.3 // Server Version: v1.17.2+k3s1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin PCOSTA-MB.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
ault-scheduler  Successfully assigned windstats/telepresence-1586708668-932211-28628-56b57d68dc-h2bh9 to kube02
  73.8 136 |   Normal   Pulling    54s                kubelet, kube02    Pulling image "datawire/telepresence-k8s:0.104"
  73.8 136 |   Normal   Pulled     35s                kubelet, kube02    Successfully pulled image "datawire/telepresence-k8s:0.104"
  73.8 136 |   Normal   Pulled     16s (x2 over 31s)  kubelet, kube02    Container image "datawire/telepresence-k8s:0.104" already present on machine
  73.8 136 |   Normal   Created    16s (x3 over 32s)  kubelet, kube02    Created container telepresence-1586708668-932211-28628
  73.8 136 |   Normal   Started    15s (x3 over 32s)  kubelet, kube02    Started container telepresence-1586708668-932211-28628
  73.8 136 |   Warning  BackOff    2s (x4 over 29s)   kubelet, kube02    Back-off restarting failed container
  73.9 TEL | [136] ran in 0.39 secs.
  75.5 TEL | [137] Running: sudo -n echo -n
  75.5 TEL | [137] ran in 0.03 secs.

```

**Comment by marun** [comment]
@costap Can you get the logs from the container (e.g. `kubectl logs windstats/telepresence-1586708668-932211-28628-56b57d68dc-h2bh9`)? It's difficult to diagnose a pod failure without more detail.

**Comment by cerebrate** [comment]
I am also attempting to use telepresence with my pi/k3s cluster, and can tell you the problem: the error the container logs is "exec format error", because the telepresence-k8s image is only available for _amd64_ architecture, not _arm_.

So... consider this a feature request for adding an _arm_ arch image to telepresence-k8s?

**Comment by cerebrate** [comment]
I have also tried building a local ARM image and using that, as per #753 (although I see the build process has changed since that time); in this case, the build fails when attempting to build the _telepresence-ocp_ image, with step 12/24 failing with the following error:

```
/bin/sh: line 0: source: scl_source: file not found
The command '/bin/sh -c yum -y install gcc &&     source scl_source enable rh-python36 &&     pip3 install --no-cache-dir incremental &&     pip3 install --no-cache-dir -r requirements.txt &&     yum -y remove gcc &&     yum clean all &&     rm -rf /var/cache/yum' returned a non-zero code: 1
make: *** [Makefile:72: docker-build] Error 1
```
and with only the other three images (_telepresence-local_, _telepresence-k8s_, _telepresence-k8s-priv_) built. Seems to work so far, though, not that I've tried every feature.

**Comment by costap** [comment]
build a image for arm locally and patched the deployement with it and its working, image available here: https://hub.docker.com/repository/docker/pedrofcosta/telepresence-k8s

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!

**Comment by Pentusha** [comment]
Facing similar issue on raspberry pi 4 (arm64) cluster.
```sh
➜  ~ sudo telepresence version                                              
Client         : v2.10.4
Root Daemon    : v2.10.4
User Daemon    : v2.10.4
Traffic Manager: not connected
```
```sh
➜  ~ kubectl logs -n ambassador traffic-manager-7c457bd45-5c4xc
exec /usr/local/bin/traffic: exec format error
```
This error means that the binary in container is not compatible with arm64 architecture.

```sh
➜  ~ docker manifest inspect datawire/ambassador-telepresence-manager:2.10.4
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 1349,
		"digest": "sha256:a7703c490b430a7429a94e7e061df1de1384cb10ec63f114bbf2943d4150990d"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 3370628,
			"digest": "sha256:8921db27df2831fa6eaa85321205a2470c669b855f3ec95d5a3c2b46de0442c9"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 766990,
			"digest": "sha256:df2192d3c86bd0a4348ec00317ad1bb8ec9d241802a2bf6553421e041500f00b"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 35591429,
			"digest": "sha256:88afe6a41140555e682f047b595878317c42d2f9a46ca79e1ae2610a85227a15"
		}
	]
}
```
That mean the docker image not annotated for arm64 architecture.
You can call similar command for any other image that works on arm64:
```sh
docker manifest inspect nginx | jq '.manifests[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm",
  "os": "linux",
  "variant": "v5"
}
{
  "architecture": "arm",
  "os": "linux",
  "variant": "v7"
}
{
  "architecture": "arm64",
  "os": "linux",
  "variant": "v8"
}
{
  "architecture": "386",
  "os": "linux"
}
{
  "architecture": "mips64le",
  "os": "linux"
}
{
  "architecture": "ppc64le",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
```

**Comment by Pentusha** [comment]
@thallgren, @costap, can you reopen this issue please?

**Comment by thallgren** [comment]
The issue seems to be that we don't support clusters running on arm64, which makes this a duplicate of #2926 and several other tickets.
