### ISSUE TITLE
Failed to connect to proxy in remote cluster

### ISSUE THREAD

**Issue by ZolotarenkoM** [telepresenceio/telepresence#1307]
### What were you trying to do?

`telepresence --mount=/tmp/known --swap-deployment app_deployment --namespace provisioners --docker-run --rm -it -v=/tmp/known/var/run/secrets:/var/run/secrets app_new_image`

### What did you expect to happen?

expected to get an interactive shell in the context of the running pod

### What happened instead?

It crashed with issue `Failed to connect to proxy in remote cluster.`

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--mount=/tmp/known', '--swap-deployment', 'app_deployment', '--namespace', 'provisioners', '--docker-run', '--rm', '-it', '-v=/tmp/known/var/run/secrets:/var/run/secrets', 'app_new_image']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.14.3 // Server Version: v1.15.9`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin mykhailozolotarenko-r 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 169, in launch
    pod_info,
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 165, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 462, in check_call
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 437, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1587039544-016141-58062', '--rm', 'datawire/telepresence-local:0.104', 'wait']' returned non-zero exit status 1.

```

Logs:

```
e: 36 bytes
  76.4  42 | c : DNS request from ('172.17.0.2', 40417) to None: 36 bytes
  76.8  42 | c : DNS request from ('172.17.0.2', 36686) to None: 36 bytes
  77.2  42 | c : DNS request from ('172.17.0.2', 38889) to None: 36 bytes
  77.6  42 | c : DNS request from ('172.17.0.2', 43460) to None: 36 bytes
  78.0  42 | c : DNS request from ('172.17.0.2', 56539) to None: 36 bytes
  78.4  42 | c : DNS request from ('172.17.0.2', 57031) to None: 36 bytes
  78.8  42 | c : DNS request from ('172.17.0.2', 47389) to None: 36 bytes
  79.2  42 | c : DNS request from ('172.17.0.2', 56000) to None: 36 bytes
  79.6  42 | c : DNS request from ('172.17.0.2', 53728) to None: 36 bytes
  80.0  42 | c : DNS request from ('172.17.0.2', 50097) to None: 36 bytes
  80.4  42 | c : DNS request from ('172.17.0.2', 39497) to None: 36 bytes
  80.8  49 | Failed to connect to proxy in remote cluster.
  80.9  49 | [INFO  tini (1)] Main child exited normally (with status '1')
  81.0 TEL | [49] exit 1 in 30.81 secs.

```

Notes:
It happens when we have `ndots: 1` in our app_deployment. If we change DNS config for app_deployment to `ndots: 5` - everything fine

**Comment by adamglang** [comment]
That's probably because your cluster has a name like kubernetes.default.svc.cluster.local or similar. If ndots is set to one hosts with more than one 'dot' in the name will not be accessable

**Comment by ipleten** [comment]
We do use such dcluster name, but we also use `ndots:1` on all deployments and telepresence is copying `ndots` value to docker container if we use 'container' method. I changed ndots back to 5 and it works again now.
1) Why telepresence tries  to respect ndots?
2) Should it be an option like `--ndots 5` for TP cli? or "--use-default-ndots" value?
