### ISSUE TITLE
kubectl 1.18.1 breaks telepresence

### ISSUE THREAD

**Issue by dmarkwat** [telepresenceio/telepresence#1311]
### What were you trying to do?

Just trying to get telepresence running on Ubuntu 19.10 against a minikube cluster.

### What did you expect to happen?

No errors :)

### What happened instead?

I ran `telepresence` with the `kubectl` config set correctly and this error happened.

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.104`
Python version: `3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]`
kubectl version: `Client Version: v1.18.1 // Server Version: v1.15.10`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux dan-desktop 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
efault delete --ignore-not-found svc,deploy --selector=telepresence=561ba9c46e684b23b1bd41052bb9deef
   5.8  10 | No resources found
   5.8 TEL | [10] ran in 0.08 secs.
   5.8 TEL | [11] Running: kubectl --context concourse --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1587246096-0487-14291 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=561ba9c46e684b23b1bd41052bb9deef
   5.9  11 | pod/telepresence-1587246096-0487-14291 created
   5.9 TEL | [11] ran in 0.09 secs.
   5.9 TEL | END SPAN deployment.py:108(create_new_deployment)    0.2s
   5.9 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   5.9 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   5.9 TEL | [12] Capturing: kubectl --context concourse --namespace default get deployment -o json --selector=telepresence=561ba9c46e684b23b1bd41052bb9deef
   6.0 TEL | [12] captured in 0.08 secs.
   6.0 TEL | END SPAN remote.py:75(get_deployment_json)    0.1s

```

**Comment by dmarkwat** [comment]
I reverted `kubectl` to the same version as my cluster (`1.16.9`) and it worked. After looking at the commands invoked, it looks like `kubectl run` may be using a pod by default, resulting in the `items` being empty and causing the `IndexError`.

**Comment by dmarkwat** [comment]
Bingo; I think this is it: https://kubernetes.io/docs/setup/release/notes/#kubectl
> kubectl run has removed the previously deprecated generators, along with flags unrelated to creating pods. kubectl run now only creates pods. See specific kubectl create subcommands to create objects other than pods. (#87077, @soltysh) [SIG Architecture, CLI and Testing]

**Comment by marun** [comment]
Duplicates #1297, which also includes workarounds.
