### ISSUE TITLE
Telepresence stopped working

### ISSUE THREAD

**Issue by iirekm** [telepresenceio/telepresence#1316]
Same system, same apps, same telepresence version. Worked few weeks ago now doesnt!!!

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--method', 'inject-tcp', '--swap-deployment=...']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.17.0 // Server Version: v1.17.3+k3s1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux ... 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
hable:NoExecute for 300s
  35.9  32 | Events:
  35.9  32 |   Type    Reason     Age        From                 Message
  35.9  32 |   ----    ------     ----       ----                 -------
  35.9  32 |   Normal  Scheduled  <unknown>  default-scheduler    Successfully assigned ... to ...
  35.9  32 |   Normal  Pulled     33s        kubelet, ...  Container image "datawire/telepresence-k8s:0.104" already present on machine
  35.9  32 |   Normal  Created    33s        kubelet, ...  Created container ...
  35.9  32 |   Normal  Started    33s        kubelet, ...  Started container ...
  35.9  21 | 2020-04-21T08:44:23+0000 [Poll#error] Failed to contact Telepresence client:
  35.9  21 | 2020-04-21T08:44:23+0000 [Poll#error] An error occurred while connecting: 99: Address not available.
  35.9  21 | 2020-04-21T08:44:23+0000 [Poll#warn] Perhaps it's time to exit?
  35.9 TEL | [32] ran in 0.12 secs.

```

**Comment by iirekm** [comment]
After investigation I found the reason: somehow `kubectl port-forward` didn't work, until I added `127.0.0.1 localhost` to `/etc/hosts`.

But anyway, Telepresence shouldn't use `kubectl port-forward` when kubernetes is on `localhost` (like k3s, microk8s, and so on). It can access pod's ports directly.

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
