### ISSUE TITLE
Error starting telepresence

### ISSUE THREAD

**Issue by deepaksood619** [telepresenceio/telepresence#1317]
### What were you trying to do?
Follow getting started guide. Ran command telepresence

### kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:03:29) 
[Clang 9.0.1 ]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.14.9-eks-502bfb`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Deepaks-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
4ebafff3e51d
  27.9  10 | No resources found
  27.9 TEL | [10] ran in 0.84 secs.
  27.9 TEL | [11] Running: kubectl --context deepak.sood@stashfin.com@stashfin.ap-south-1.eksctl.io --namespace apps run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1587476319-157104-71017 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=42bc0072823744dab4474ebafff3e51d
  28.6  11 | pod/telepresence-1587476319-157104-71017 created
  28.6 TEL | [11] ran in 0.78 secs.
  28.6 TEL | END SPAN deployment.py:108(create_new_deployment)    1.6s
  28.6 TEL | BEGIN SPAN remote.py:142(get_remote_info)
  28.6 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
  28.6 TEL | [12] Capturing: kubectl --context deepak.sood@stashfin.com@stashfin.ap-south-1.eksctl.io --namespace apps get deployment -o json --selector=telepresence=42bc0072823744dab4474ebafff3e51d
  29.1 TEL | [12] captured in 0.46 secs.
  29.1 TEL | END SPAN remote.py:75(get_deployment_json)    0.5s

```

**Comment by marun** [comment]
Duplicate of #1297, which was fixed by #1312. Should be resolved in the next release, and until then #1297 documents a number of workarounds.
