### ISSUE TITLE
Telepresence starts to crash

### ISSUE THREAD

**Issue by marcusdahlstein** [telepresenceio/telepresence#1321]
### What were you trying to do?

Tried running `telepresence` without arguments (also tried with various arguments)
### What did you expect to happen?

The program not to crash.
This has worked in the passed. Now .. not at all

### What happened instead?

It just crashes. During each attempt 
Tried removing all telepresence deployments in the cluster. But to no avail.
Uninstalled using brew and reinstalled. No difference.

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.15.9-gke.24`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin gol-vxo-pc0016 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
37d749edaed9b
   2.5   9 | No resources found
   2.5 TEL | [9] ran in 0.29 secs.
   2.5 TEL | [10] Running: kubectl --context gke_leo-dev-payment_europe-west1-b_leo-backend --namespace dev-payment-2 run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1587557058-18264-31303 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=fea9158b20604fe99df37d749edaed9b
   2.8  10 | pod/telepresence-1587557058-18264-31303 created
   2.8 TEL | [10] ran in 0.27 secs.
   2.8 TEL | END SPAN deployment.py:108(create_new_deployment)    0.6s
   2.8 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   2.8 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   2.8 TEL | [11] Capturing: kubectl --context gke_leo-dev-payment_europe-west1-b_leo-backend --namespace dev-payment-2 get deployment -o json --selector=telepresence=fea9158b20604fe99df37d749edaed9b
   3.0 TEL | [11] captured in 0.20 secs.
   3.0 TEL | END SPAN remote.py:75(get_deployment_json)    0.2s

```

**Comment by marun** [comment]
@marcusdahlstein Duplicate of #1297, which was fixed by #1312. Should be resolved in the next release, and until then #1297 documents a number of workarounds.
