### ISSUE TITLE
catalina 10.5.4 with localhost/vpn-tcp stopped working after upgrade to 0.105

### ISSUE THREAD

**Issue by johnha** [telepresenceio/telepresence#1338]
### What were you trying to do?

Trying to debug local golang application on catalina (10.5.4).   Using --local-cluster.  It was 
working on catalina until yesterday when I upgraded to latest telepresence (from 0.99).   I tried to revert back and run old version but problem still occurs and fails to establish tcp-vpn connection to the cluster.   I am using docker/kubernetes locally.

### What did you expect to happen?

establish connection to the cluster to enable local golang app to work in the cluster.

### What happened instead?

ssh port forward exited with return code 255.

  23.5 TEL | CRASH: 1 background process(es) crashed
  23.5 TEL | Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  23.5 TEL |   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -vv -p 49252 telepresence@127.0.0.1 -L127.0.0.1:49264:127.0.0.1:9050 -R9055:127.0.0.1:49265
  23.5 TEL |
  23.5 TEL | Recent output was:
  23.5 TEL |   debug1: Requesting no-more-sessions@openssh.com
  23.5 TEL |   debug1: Entering interactive session.
  23.5 TEL |   debug1: pledge: network
  23.5 TEL |   debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
  23.5 TEL |   debug1: Remote: Forwarding listen address "localhost" overridden by server GatewayPorts
  23.5 TEL |   debug1: remote forward success for: listen 9055, connect 127.0.0.1:49265
  23.5 TEL |   debug1: All remote forwarding requests processed
  23.5 TEL |   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  23.5 TEL |   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  23.5 TEL |   Timeout, server 127.0.0.1 not responding.

I have tried a host of things others have tried.  RE high port number problem in osx, removing ip6 ::1, increasing ssh timeout in ssh config (although I think this is ignored because of /dev/null switch in call etc.  

I thought it was DNS as the python verification calls indicate server not responding - but think it is because the VPN connection to cluster is dropped and these DNS lookups cannot complete:

  15.5 TEL | [46] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-6")'
  15.5  33 | c : DNS request from ('fd5b:afc9:9cb1:0:15bd:c856:41cb:f753', 52160, 0, 0) to None: 82 bytes
  16.4  33 | c : Accept TCP: 127.0.0.1:49303 -> 127.0.0.1:8001.
  16.5  33 | c : DNS request from ('fd5b:afc9:9cb1:0:15bd:c856:41cb:f753', 52160, 0, 0) to None: 82 bytes
  18.4  21 | Timeout, server 127.0.0.1 not responding.

Other connections (e.g. google.com etc) also fail so this I think indicates the shuttle connection to the cluster has failed.

I was wondering if the issue could be down to the ssh requests being translated in the request to localhost alias....  e.g.  the logs shows SSH:

  23.5 TEL |   debug1: Remote: Forwarding listen address "localhost" overridden by server GatewayPorts

but the secure connection was previously established where the 127.0.0.1 was added to a list of known hosts:

 5.4  21 | Warning: Permanently added '[127.0.0.1]:49252' (ECDSA) to the list of known hosts.

Any advice is appreciated!

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'vpn-tcp', '--verbose', '--also-proxy', 'nodlinnats', '--run-shell', '--local-cluster']`
Version: `0.105`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin iMac-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

```
Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -vv -p 49252 telepresence@127.0.0.1 -L127.0.0.1:49264:127.0.0.1:9050 -R9055:127.0.0.1:49265

Recent output was:
  debug1: Requesting no-more-sessions@openssh.com
  debug1: Entering interactive session.
  debug1: pledge: network
  debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
  debug1: Remote: Forwarding listen address "localhost" overridden by server GatewayPorts
  debug1: remote forward success for: listen 9055, connect 127.0.0.1:49265
  debug1: All remote forwarding requests processed
  debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  Timeout, server 127.0.0.1 not responding.
```

Logs:

```
 Wait for vpn-tcp connection: hellotelepresence-6
  15.5 TEL | [46] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-6")'
  15.5  33 | c : DNS request from ('fd5b:afc9:9cb1:0:15bd:c856:41cb:f753', 52160, 0, 0) to None: 82 bytes
  16.4  33 | c : Accept TCP: 127.0.0.1:49303 -> 127.0.0.1:8001.
  16.5  33 | c : DNS request from ('fd5b:afc9:9cb1:0:15bd:c856:41cb:f753', 52160, 0, 0) to None: 82 bytes
  18.4  21 | Timeout, server 127.0.0.1 not responding.
  18.4 TEL | [21] SSH port forward (socks and proxy poll): exit 255
  18.5  33 | c : DNS request from ('192.168.0.10', 52160) to None: 82 bytes
  19.5  33 | c : DNS request from ('192.168.0.10', 52160) to None: 82 bytes
  20.5 TEL | [46] timed out after 5.01 secs.
  20.5 TEL | [47] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-6.a.sanity.check.telepresence.io")'
  20.5  33 | c : DNS request from ('192.168.0.10', 58581) to None: 68 bytes
  21.5 TEL | [47] timed out after 1.01 secs.

```

**Comment by johnha** [comment]
telepresence --run curl -svk https://kubernetes.default/api
[telepresence.log](https://github.com/telepresenceio/telepresence/files/4570287/telepresence.log)

**Comment by brtasavpatel** [comment]
I am also having same issue. Any luck finding a fix for this?

**Comment by johnha** [comment]
> I am also having same issue. Any luck finding a fix for this?

no I am afraid not.   In the end I switched to kubefwd - https://github.com/txn2/kubefwd - a simpler solution - but worked for me and can still perform local debugging etc.   Have not had any problems since switching to this.
