### ISSUE TITLE
Auto exposure of containerPorts only work for swapDeployment

### ISSUE THREAD

**Issue by aslakknutsen** [telepresenceio/telepresence#1356]
##### Issue Overview

Telepresence support to auto expose the container ports defined in the Deployment/DeploymentConfig. This behavior would be useful regardless of the chosen deployment handling strategy.

##### Expected Behaviour

Should work with  `--new-deployment`, `--deployment` and `--swap-deployment`

##### Current Behaviour

Only `--swap-deployment` is currently supported.

**Comment by mruoss** [comment]
Hey there, is it possible to disable this behaviour somehow?

**Comment by ark3** [comment]
No, not at the moment. Why do you want to disable it?

**Comment by mruoss** [comment]
Might be a misconception but I tried to run telepresence more than once, trying to expose a different port for each process => it would map all the ports all the time, overwriting the mapping of another telepresence process
