### ISSUE TITLE
nodejs service debugging with telepresence and Windows

### ISSUE THREAD

**Issue by robross0606** [telepresenceio/telepresence#1361]
I've been trying to figure out how to use wsl and telepresence to debug a node.js service on a cluster via VSCode.  I have been successful at launching telepresence and injecting the service into a remote cluster several ways (manually, vscode launcher and vscode task).  However, I have been thus far unsuccessful at being able to attach the local VSCode debugger to the running service even if I run with --inspect(-brk).  If I use it in a launch script in vscode, the debugger appears to attach and then simply detaches a couple seconds later without any errors.  If I enter a telepresence terminal either manually or through a task, and then attempt to use auto-attach, that doesn't work at all.  I've been over the instructions several times, but most of them seem to focus on if you're using a local docker container which I'm not.

**Comment by marun** [comment]
@robross0606 Have you tried the node.js [remote debugger](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging)?

**Comment by robross0606** [comment]
Yes, that quasi worked but had issues setting breakpoints in anything other than the main JavaScript file. Turns out this only seems to work at all if you run vscode inside wsl rather than just running a wsl term inside vscode.

**Comment by marun** [comment]
Maybe test with a docker container if that's a better documented path, and use the knowledge gained to figure out a non-docker path? Not using windows, vscode or nodejs I'm afraid I'm not much help.

**Comment by ericgrings-asapp** [comment]
@robross0606 could you make this work in the end? making this work would be awesome...

**Comment by robross0606** [comment]
Sorta.  Not well as automated through VSCode launch.json.  

- There is considerable overhead in injecting a telepresence environment into a cluster and breaking it down afterwards.  Ideally this should not be performed each time you launch a debug session. 
-  VSCode is currently somewhat limited in ways you can configure custom terminals.  You can neither configure fully custom terminal types, nor configure individual launchers to use a specific terminal type.

The only thing I came up with was to create custom tasks in tasks.json:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "telepresence:new",
      "detail": "Launch new terminal as injected instance to K8S cluster via telepresence.",
      "isBackground": false,
      "promptOnClose": true,
      "type": "shell",
      "command": "telepresence",
      "args": ["--method", "inject-tcp", "--swap-deployment", "study-design-service"],
      "presentation": {
        "reveal": "always",
        "revealProblems": "never",
        "panel": "dedicated"
      },
      "windows": {
        "options": {
          "shell": {
            "executable": "wsl.exe",
            "args": ["--"]
          }
        }
      },
      "problemMatcher": []
    },
    {
      "label": "telepresence:existing",
      "detail": "Launch terminal into previously injected telepresence instance.",
      "isBackground": false,
      "promptOnClose": true,
      "type": "shell",
      "command": "telepresence",
      "args": [
        "--method",
        "inject-tcp",
        "--swap-deployment",
        "study-design-service",
        "--deployment",
        "${input:telepresenceDeploymentName}"
      ],
      "presentation": {
        "reveal": "always",
        "revealProblems": "never",
        "panel": "dedicated"
      },
      "windows": {
        "options": {
          "shell": {
            "executable": "wsl.exe",
            "args": ["--"]
          }
        }
      },
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "telepresenceDeploymentName",
      "type": "promptString",
      "description": "Telepresence deployment (starts with 'study-design-serv-') name:",
      "default": "study-design-serv-"
    }
  ]
}
```

This example configures two custom tasks:

1. **telepresence:new**
This launches telepresence with effectively the same command line arguments as shown in the example above.
3. **telepresence:existing**
This will prompt the user to enter the name of an existing telepresence instance already injected on the cluster and launch into that same instance.

Once these are configured, they can be access via the global menu bar (Terminal → Run Task...) or via the Command Palette then typing "task<space>" 

![image](https://user-images.githubusercontent.com/2965467/91340314-ce996180-e7a5-11ea-8eb2-0d57277d8c3a.png)

**Comment by ericgrings-asapp** [comment]
this is awesome will see if I can modify it for OSX

**Comment by robross0606** [comment]
Just an update on this.  I'm having issues with breakpoints again.  Haven't figured out how to run telepresence via a `wsl` session while running vscode in Windows, and still attaching via remote debugger.  It breaks on the main entrant file as expected, but refuses to bind to breakpoints in any other file.

**Comment by robross0606** [comment]
Further update, this has gotten even worse.  Now I cannot even attach to the debug instance via Port, auto-attach or any other method I can find.  I'm dead in the water again since VSCode appears to keep updating their debugger engine and breaking things completely.
