### ISSUE TITLE
A broken network connection on a swapped deployment leaves orphaned deployment in cluster

### ISSUE THREAD

**Issue by robross0606** [telepresenceio/telepresence#1362]
I am able to successfully swap out a deployment using the `--swap-deployment` argument.  However, from time to time, a network hiccup causes loss of connection which leaves the orphaned telepresence deployment out on the cluster and the original swapped container stuck.

I am even able to reconnect to that existing telepresence instance using the `--deployment` argument and the name of the orphaned deployment.  However, at that point, telepresence no longer knows it was a "swapped" deployment so there's no way to swap back the original deployment.

**Comment by robross0606** [comment]
There needs to be a way to renegotiate a `--swap-deployment` session with an existing telepresence container.

**Comment by marun** [comment]
@robross0606 What do you think of specifying a new argument instead - e.g. `--recover`? Overloading existing arguments would seem to be potentially confusing (e.g. if this state, then that behavior. If that state, then this behavior).

**Comment by robross0606** [comment]
Works for me. I'm not picky as long as there's a way to do it.

**Comment by lpakula** [comment]
As a workaround you can use the following:

```
kubectl delete deployment -l telepresence
kubectl scale --replicas=1 deployment <name>
```
to revert to the initial state
