### ISSUE TITLE
Error using concurrent docker mounts

### ISSUE THREAD

**Issue by lpakula** [telepresenceio/telepresence#1379]
## What were you trying to do?
Use `--docker-mount` flag for multiple telepresence deployments on the same host

## What did you expect to happen?
Being able to swap multiple deployments with `--docker-mount` flag

## What happened instead?
It's  failing with the following error:

```
docker: Error response from daemon: error while mounting volume '': VolumeDriver.Mount: sshfs command execute failed: exit status 1 (fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option)
```

**Comment by lpakula** [comment]
any workaround for this?

**Comment by marun** [comment]
Can you please provide more detail as to what you're trying to accomplish and why?

**Comment by lpakula** [comment]
@marun 

I have a cluster with two services, I'm trying to swap them both from the same host machine. Both swaps are docker containers and using mounts (`--docker-mount`) to fix volumes

It's impossible to do it because vieux/sshfs mount directory is static in telepresence I believe. So it's pointing to the same directory (in host) for every swap

**Comment by lpakula** [comment]
any workaround for this?

**Comment by lpakula** [comment]
@marun is this description any better now?

**Comment by marun** [comment]
> @marun is this description any better now?

I think the description is fine. I'm afraid I don't use telepresence with docker, though, so someone else will need to help you.

**Comment by ark3** [comment]
In the [vieux/sshfs source code](https://github.com/vieux/docker-volume-sshfs/blob/master/main.go#L105) I see 

```go
	v.Mountpoint = filepath.Join(d.root, fmt.Sprintf("%x", md5.Sum([]byte(v.Sshcmd))))
```

where `v.Sshcmd` is something like `telepresence@127.0.0.1:/`. So the mount point is computed as a hash of a value that never changes for Telepresence's usage. It also appears that it's not possible to specify that mount point explicitly, unless I missed something... I guess we'll need to ask the plugin folks to add optional configuration for that mount point.

**Comment by lpakula** [comment]
@ark3 I think vieux/sshfs project is dead since the main developer left the docker company (last commit in May 2018). Is there any consideration to replace this package? Or what would you suggest to overcome this problem?

It's quite a common scenario to swap more than one container I guess? in the microservice world, you need to swap more than one service to develop one feature

**Comment by lpakula** [comment]
@ark3 any thoughts?
