### ISSUE TITLE
i cant use telepresence on my mac while using vpn ?

### ISSUE THREAD

**Issue by shachardevops** [telepresenceio/telepresence#1381]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.105`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: Command '['oc', 'version']' returned non-zero exit status 1.)`
OS: `Darwin Shachars-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 328, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
ne: 38 bytes
 154.1 TEL | [65] timed out after 1.01 secs.
 154.1  16 | 2020-06-11T10:57:53+0000 [stdout#info] A query: b'beacons.gcp.gvt2.com'
 154.2  16 | 2020-06-11T10:57:53+0000 [stdout#info] Result for b'beacons.gcp.gvt2.com' is ['172.217.8.3']
 154.3  40 | c : DNS request from ('10.10.10.3', 22951) to None: 37 bytes
 154.7  16 | 2020-06-11T10:57:54+0000 [stdout#info] A query: b'clients4.google.com'
 154.7  16 | 2020-06-11T10:57:54+0000 [stdout#info] Result for b'clients4.google.com' is ['172.217.13.238']
 155.3  40 | c : DNS request from ('10.10.10.3', 55452) to None: 52 bytes
 155.7  16 | 2020-06-11T10:57:55+0000 [stdout#info] A query: b'easylist-downloads.adblockplus.org'
 155.7  16 | 2020-06-11T10:57:55+0000 [stdout#info] Result for b'easylist-downloads.adblockplus.org' is ['136.243.150.198', '94.130.104.87', '178.63.70.146', '178.63.50.140', '213.239.192.206', '195.201.59.240', '144.76.137.80', '176.9.139.5', '78.46.66.108', '195.201.59.236', '144.76.137.234', '78.46.39.215']

```

**Comment by tipok** [comment]
Hi, you can try using other two methods `--method inject-tcp` or `--method container`. 
The method `container` is automatically selected if you start a container with `--docker-run` and is mainly used just for that.
There is no 100% guaranty it will work, but give it a try.

**Comment by shachardevops** [comment]
--method inject-tcp works thank you very much
