### ISSUE TITLE
Fail to start network proxy to cluster using the existing proxy Deployment tools-telepresence

### ISSUE THREAD

**Issue by ricoardiya** [telepresenceio/telepresence#1382]
### What were you trying to do?

start network proxy to cluster using the existing proxy Deployment tools-telepresence

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'tools', '--deployment', 'tools-telepresence', '--run-shell']`
Version: `0.105`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.15.9-gke.24`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin 001-0335.local 19.5.0 Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
        True
  38.2  25 |     Restart Count:  0
  38.2  25 |     Environment:    <none>
  38.2  25 |     Mounts:
  38.2  25 |       /var/run/secrets/kubernetes.io/serviceaccount from default-token-hgf9k (ro)
  38.2  25 | Conditions:
  38.2  25 |   Type              Status
  38.2  25 |   Initialized       True
  38.2  25 |   Ready             True
  38.2  25 |   ContainersReady   True
  38.2  25 |   PodScheduled      True
  38.2  25 | Volumes:
  38.2  25 |   default-token-hgf9k:
  38.2  25 |     Type:        Secret (a volume populated by a Secret)
  38.2  25 |     SecretName:  default-token-hgf9k
  38.2  25 |     Optional:    false
  38.2  25 | QoS Class:       BestEffort
  38.2  25 | Node-Selectors:  <none>
  38.2  25 | Tolerations:     group=tool:NoSchedule
  38.2  25 |                  node.kubernetes.io/not-ready:NoExecute for 300s
  38.2  25 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  38.2  25 | Events:          <none>
  38.2 TEL | [25] ran in 0.18 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
