### ISSUE TITLE
kubectl command causes telescence crashing

### ISSUE THREAD

**Issue by lockercho** [telepresenceio/telepresence#1389]
### What were you trying to do?
I am on Mac OS X, using Docker Desktop's k8s cluster to test my istio setting.
I use one terminal to call `telepresence`, then I keep calling `kubectl get all` in another terminal to check if the telepresence deployment successfully launched. 

### What did you expect to happen?

Guess I should be able to use `kubectl` and `teleprescence` at the same time?

### What happened instead?
The first few `kubectl` attempts were successful, but afterward the command hangs, then it failed and shows `Unable to connect to the server: net/http: TLS handshake timeout`.
Switching back to the `teleprescene` screen, this issue happened.

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.105`
Python version: `3.8.0 (default, May 28 2020, 22:44:25) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin lalala.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

```
Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 56514 telepresence@127.0.0.1 -L127.0.0.1:56527:127.0.0.1:9050 -R9055:127.0.0.1:56528

```

Logs:

```
72] timed out after 1.01 secs.
  22.6 TEL | Wait for vpn-tcp connection: hellotelepresence-12
  22.6 TEL | [73] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-12")'
  22.6  48 | c : DNS request from ('172.20.10.12', 57168) to None: 38 bytes
  23.6  48 | c : DNS request from ('172.20.10.12', 57168) to None: 38 bytes
  25.6  48 | c : DNS request from ('172.20.10.12', 63819) to None: 34 bytes
  26.0 TEL | [45] SSH port forward (socks and proxy poll): exit 255
  26.4  48 | c : Accept TCP: 127.0.0.1:56541 -> 127.0.0.1:6443.
  27.2  48 | c : Accept TCP: 172.20.10.12:56542 -> 65.55.44.109:443.
  27.6 TEL | [73] timed out after 5.01 secs.
  27.6 TEL | [74] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-12.a.sanity.check.telepresence.io")'
  27.6  48 | c : DNS request from ('172.20.10.12', 64960) to None: 69 bytes
  28.6 TEL | [74] timed out after 1.01 secs.
  29.6  48 | c : DNS request from ('172.20.10.12', 63819) to None: 34 bytes

```

**Comment by marun** [comment]
@lockercho Given that running that telepresence command will configure the networking environment to mimic that of the pod, I'm guessing your kubectl server configuration (i.e. url) doesn't work both within the pod and outside of it. I think you'll either want to figure out what the appropriate apiserver url is when telepresence is running, or run telepresence with `--docker-run` so that the pod environment is in a container: 

https://www.telepresence.io/tutorials/docker
