### ISSUE TITLE
SSH port forward fails with exit code 255

### ISSUE THREAD

**Issue by martijnvanderwoud** [telepresenceio/telepresence#1394]
### What were you trying to do?

Swap deployment: `telepresence --swap-deployment portal-app --namespace dev-1 --env-json portal_env.json`

### What did you expect to happen?

swap the deployment with a proxy that will forward all network communications to/from the service that I will run locally

### What happened instead?

Process exited and with the below error information

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'portal-app', '--namespace', 'dev-1', '--env-json', 'portal_env.json']`
Version: `0.105`
Python version: `3.8.1 (default, Jan 21 2020, 19:37:00) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.16.6-beta.0 // Server Version: v1.18.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Martijn-MBP-2106.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

```
Background process (SSH port forward (exposed ports)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50433 telepresence@127.0.0.1 -R '*:8080:127.0.0.1:8080'


Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50433 telepresence@127.0.0.1 -L127.0.0.1:50443:127.0.0.1:9050 -R9055:127.0.0.1:50444

```

Logs:

```
bytes
  13.5 TEL | [52] timed out after 1.00 secs.
  13.6 TEL | Wait for vpn-tcp connection: hellotelepresence-11
  13.6 TEL | [53] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-11")'
  13.6  30 | c : DNS request from ('2001:1c02:b22:ec00:5589:4b6d:c3db:cee3', 54902, 0, 0) to None: 43 bytes
  14.6  30 | c : DNS request from ('2001:1c02:b22:ec00:5589:4b6d:c3db:cee3', 54902, 0, 0) to None: 43 bytes
  16.0  30 | c : DNS request from ('2001:1c02:b22:ec00:5589:4b6d:c3db:cee3', 51068, 0, 0) to None: 46 bytes
  18.2 TEL | [26] SSH port forward (exposed ports): exit 255
  18.2 TEL | [27] SSH port forward (socks and proxy poll): exit 255
  18.6 TEL | [53] timed out after 5.01 secs.
  18.6 TEL | [54] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-11.a.sanity.check.telepresence.io")'
  18.6  30 | c : DNS request from ('2001:1c02:b22:ec00:5589:4b6d:c3db:cee3', 49464, 0, 0) to None: 69 bytes
  19.6 TEL | [54] timed out after 1.00 secs.

```

**Comment by ovovchuk** [comment]
Same for me with 0.105, please investigate the issue. Reverted back to 0.104

**Comment by ark3** [comment]
0.105 on MacOS Catalina fails, 0.104 works? Just trying to clarify. Thank you.

**Comment by ovovchuk** [comment]
Correct, I have tried different options "--run-shell", "--swap-deployment" all failed with same error, but works well with 0.104.

**Comment by ovovchuk** [comment]
@ark3 After revert to 0.104 the same error appeared so looks like the problem in dependency.

**Comment by dekelev** [comment]
Same issue with brew installed telepresense v0.105 on Mac OS Catalina v10.15.5 and latest version of Docker for Mac with enabled Kubernetes cluster. I never used an older version of telepresense on this OS.

**Comment by bananetomate** [comment]
Issue is present with MacOS 10.15.6 as well.

**Comment by jaredgorski** [comment]
Same issue on MacOS 10.14.6 with Docker 2.2.0.0 and a local K8s cluster.

Worked on Friday. Only thing I did over the weekend was begin using `pyenv` to manage my python versions, but that shouldn't cause problems. I also set up `opencv` with python bindings, but that's the only difference between my computer Friday and my computer Monday.

As of Monday, I'm experiencing this issue. The only way I've found to make things work is to include the `--method inject-tcp` option to route through the cluster instead of the DNS. Not sure what's gone wrong here.

**Comment by jaredgorski** [comment]
Is anyone else on this thread using `pyenv`?

**Comment by parthshah-mt** [comment]
`Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
T:   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 50050 telepresence@127.0.0.1 -L127.0.0.1:50065:127.0.0.1:9050 -R9055:127.0.0.1:50066`


The same issue on a Mac. What could be a potential solution for the same?
