### ISSUE TITLE
j

### ISSUE THREAD

**Issue by arcana261** [telepresenceio/telepresence#1395]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--context', 'afra', '--namespace', 'divar-communications', '--swap-deployment', 'new-post-api-staging', '--method', 'container', '--docker-run', '-it', '--rm', '-p', '8098:8098', '-p', '5678:5678', '--envfile', 'telepresence.env', '--entrypoint', '/bin/bash', 'postapi:mehdi', '-c', 'python -m debugpy --listen 0.0.0.0:5678 main.py']`
Version: `0.105`
Python version: `3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.18.3 // Server Version: v1.14.8`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux mehdi-zenbook 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Background process (Network container) exited with return code 125. Command was:
  docker run -p=8098:8098 -p=5678:5678 --publish=127.0.0.1:44831:38022/tcp --hostname=new-post-api-stag-40e6d1f2e3e144dbab1fb1b7c9d314cb-849f745bvgt6 --dns=10.233.0.3 --dns-search=divar-communications.svc.kube.roo.cloud --dns-search=svc.kube.roo.cloud --dns-search=kube.roo.cloud --dns-opt=ndots:5 --rm --privileged --name=telepresence-1593611485-7283118-2646650 datawire/telepresence-local:0.105 proxy '{"cidrs": ["0/0"], "expose_ports": [[9000, 9000], [8098, 8098]], "to_pod": [], "from_pod": []}'

Recent output was:
  docker: Error response from daemon: driver failed programming external connectivity on endpoint telepresence-1593611485-7283118-2646650 (d6c409e860587a836f4a299be6e9a356a4a3413f8f32e9798f932d0d4af37005): Bind for 0.0.0.0:5678 failed: port is already allocated.
```

Logs:

```
divar-communications.svc.kube.roo.cloud --dns-search=svc.kube.roo.cloud --dns-search=kube.roo.cloud --dns-opt=ndots:5 --rm --privileged --name=telepresence-1593611485-7283118-2646650 datawire/telepresence-local:0.105 proxy '{"cidrs": ["0/0"], "expose_ports": [[9000, 9000], [8098, 8098]], "to_pod": [], "from_pod": []}'
  26.5 TEL | [30] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 44831 root@127.0.0.1 /bin/true
  26.5 TEL | [30] exit 255 in 0.02 secs.
  26.7  29 | docker: Error response from daemon: driver failed programming external connectivity on endpoint telepresence-1593611485-7283118-2646650 (d6c409e860587a836f4a299be6e9a356a4a3413f8f32e9798f932d0d4af37005): Bind for 0.0.0.0:5678 failed: port is already allocated.
  26.8 TEL | [29] Network container: exit 125
  26.8 TEL | [31] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 44831 root@127.0.0.1 /bin/true
  26.8 TEL | [31] exit 255 in 0.01 secs.

```

**Comment by ipleten** [comment]
It's says that something on port 5678 is listening on your machine.

**Comment by arcana261** [comment]
@ipleten 

Thanks! I know I was running another telepresence instance at the time.. However I didn't wanted to submit an issue I must have hit `Enter` when it prompts to submit a github issue... And probably I hit `Enter` multiple times on keyboard too :( I'm soooooo sorry... I was careless! Closing the issue now!
