### ISSUE TITLE
Install script support for PopOS focal

### ISSUE THREAD

**Issue by gregbacchus** [telepresenceio/telepresence#1397]
Detected operating system as Pop/focal.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/datawireio_telepresence.list...curl: (22) The requested URL returned error: 404 

Unable to download repo config from: https://packagecloud.io/install/repositories/datawireio/telepresence/config_file.list?os=Pop&dist=focal&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.

**Comment by ark3** [comment]
Thank you for the issue. Unfortunately, we cannot fix this directly; the folks at Package Cloud would have to do that.

Were you able to get the installation to work by overriding OS detection, as suggested in the output? With your help, we can document the correct overrides so that other users of PopOS will have a better experience.

**Comment by gregbacchus** [comment]
Thanks for the response. Yes, I managed to get it going :)

**Comment by gregbacchus** [comment]
I have just sent Package Cloud an email as well.

**Comment by FaKod** [comment]
`curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | sudo os=ubuntu dist=focal bash`

**Comment by jellz** [comment]
Thanks @FaKod that saved me with a different package!
