### ISSUE TITLE
telepresence swap-deployment fails to find context

### ISSUE THREAD

**Issue by dspenard** [telepresenceio/telepresence#1407]
### What were you trying to do?

I'm trying to run swap-deployment to debug a service running in an Azure Kubernetes cluster.  I confirmed the name of the deployment and the name of the current context, and I get the same error with or without the --context dev-k8s setting.  I'm running the Linux subsystem on Windows 10.

### What did you expect to happen?

I expected the proxy to be swapped for the flex-reporter deployment.

### What happened instead?

sudo telepresence --context dev-k8s --swap-deployment flex-reporter --env-json flex-reporter_env.json

**contents of the telepresence.log file:**

   0.0 TEL | Telepresence 0.105 launched at Fri Jul 24 15:23:24 2020
   0.0 TEL |   /usr/bin/telepresence --context dev-k8s --swap-deployment flex-reporter --env-json flex-reporter_env.json
   0.0 TEL | uname: uname_result(system='Linux', node='PA01WD04', release='4.4.0-18362-Microsoft', version='#836-Microsoft Mon May 05 16:04:00 PST 2020', machine='x86_64', processor='x86_64')
   0.0 TEL | Platform: linux
   0.0 TEL | WSL: True
   0.0 TEL | Python 3.8.2 (default, Mar 13 2020, 10:14:16)
   0.0 TEL | [GCC 9.3.0]
   0.0 TEL | BEGIN SPAN main.py:40(main)
   0.0 TEL | BEGIN SPAN startup.py:83(set_kube_command)
   0.0 TEL | Found kubectl -> /usr/local/bin/kubectl
   0.0 TEL | [1] Capturing: kubectl --context dev-k8s version --short
   **0.1   1 | error: context "dev-k8s" does not exist**
   0.1 TEL | [1] exit 1 in 0.07 secs.
   0.1 TEL | [2] Capturing: kubectl --context dev-k8s config view -o json
   0.2 TEL | [2] captured in 0.07 secs.

### Automatically included information

Command line: `['/usr/bin/telepresence', '--context', 'dev-k8s', '--swap-deployment', 'flex-reporter', '--env-json', 'flex-reporter_env.json']`
Version: `0.105`
Python version: `3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux PA01WD04 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 42, in main
    set_kube_command(runner, args)
  File "/usr/bin/telepresence/telepresence/startup.py", line 145, in set_kube_command
    for context_setting in kubectl_config["contexts"]:
TypeError: 'NoneType' object is not iterable

```

Logs:

   0.0 TEL | Telepresence 0.105 launched at Fri Jul 24 15:23:24 2020
   0.0 TEL |   /usr/bin/telepresence --context dev-k8s --swap-deployment flex-reporter --env-json flex-reporter_env.json
   0.0 TEL | uname: uname_result(system='Linux', node='PA01WD04', release='4.4.0-18362-Microsoft', version='#836-Microsoft Mon May 05 16:04:00 PST 2020', machine='x86_64', processor='x86_64')
   0.0 TEL | Platform: linux
   0.0 TEL | WSL: True
   0.0 TEL | Python 3.8.2 (default, Mar 13 2020, 10:14:16)
   0.0 TEL | [GCC 9.3.0]
   0.0 TEL | BEGIN SPAN main.py:40(main)
   0.0 TEL | BEGIN SPAN startup.py:83(set_kube_command)
   0.0 TEL | Found kubectl -> /usr/local/bin/kubectl
   0.0 TEL | [1] Capturing: kubectl --context dev-k8s version --short
   **0.1   1 | error: context "dev-k8s" does not exist**
   0.1 TEL | [1] exit 1 in 0.07 secs.
   0.1 TEL | [2] Capturing: kubectl --context dev-k8s config view -o json
   0.2 TEL | [2] captured in 0.07 secs.
```

**Comment by ark3** [comment]
Sorry about the crash! Please don't run Telepresence using `sudo`. Tel will call `sudo` for you if necessary.

**Comment by dspenard** [comment]
When running without sudo I get a permissions error:

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 39, in main
    runner = Runner(args.logfile, args.verbose)
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 135, in __init__
    self.temp = Path(mkdtemp(prefix="tel-", dir=tmp_dir))
  File "/usr/lib/python3.8/tempfile.py", line 498, in mkdtemp
    _os.mkdir(file, 0o700)
PermissionError: [Errno 13] Permission denied: '/c/temp/tel-l3sctbu1'

**log file:**

   0.0 TEL | Telepresence 0.105 launched at Fri Jul 24 16:00:50 2020
   0.0 TEL |   /usr/bin/telepresence --swap-deployment flex-reporter --env-json flex-reporter_env.json
   0.0 TEL | uname: uname_result(system='Linux', node='PA01WD04', release='4.4.0-18362-Microsoft', version='#836-Microsoft Mon May 05 16:04:00 PST 2020', machine='x86_64', processor='x86_64')
   0.0 TEL | Platform: linux
   0.0 TEL | WSL: True
   0.0 TEL | Python 3.8.2 (default, Mar 13 2020, 10:14:16)
   0.0 TEL | [GCC 9.3.0]

**Comment by ark3** [comment]
Ah, that's an incompatibility with WSL; your user can't write to the temp directory.

1. Which WSL is this? How should we detect this particular WSL?
2. What's the correct location for temporary files and directories for this WSL?

Thank you for your help!

**Comment by dspenard** [comment]
I'm using WSL 1 (4.4.0-18362-Microsoft), as I ran into issues updating to WSL 2.  Should I be using WSL 2 for running telepresence or does it not matter?

It looks like the location for WSL 1 temp files is /c/temp/

Sorry if I can't provide more info.  I'm more of a Windows guy and have used Linux, but not the WSL before.
