### ISSUE TITLE
Crashes when `kubectl run` doesn't create deployment

### ISSUE THREAD

**Issue by zwobill** [telepresenceio/telepresence#1411]
### What were you trying to do?

I am following the tutorial to run Telepresence proxy by simply running `telepresence` command locally. 

### What happened instead?

Telepresence crashes on `IndexError: list index out of range` exception. It seems that the Python script is looking for the first deployment returned by the `kubectl --context arn:aws:eks:us-east-1:xxxxxxxxxx:cluster/staging-6 --namespace default get deployment -o json --selector=telepresence=db2215375def4816bfd2114d9c0facba` command. This command returns empty list as the following. It seems that the `kubectl run` command is deprecated and it doesn't create deployment. 

```
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.15.11-eks-af3caf`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Yunfeis-MacBook-Pro-2.local 17.7.0 Darwin Kernel Version 17.7.0: Wed May 27 17:00:02 PDT 2020; root:xnu-4570.71.80.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
114d9c0facba
  25.5  10 | No resources found
  25.5 TEL | [10] ran in 4.26 secs.
  25.5 TEL | [11] Running: kubectl --context arn:aws:eks:us-east-1:xxxxxxxxxx:cluster/staging-6 --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1597113721-25075-79035 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=db2215375def4816bfd2114d9c0facba
  27.5  11 | pod/telepresence-1597113721-25075-79035 created
  27.5 TEL | [11] ran in 2.02 secs.
  27.5 TEL | END SPAN deployment.py:108(create_new_deployment)    6.3s
  27.5 TEL | BEGIN SPAN remote.py:142(get_remote_info)
  27.5 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
  27.5 TEL | [12] Capturing: kubectl --context arn:aws:eks:us-east-1:xxxxxxxxxx:cluster/staging-6 --namespace default get deployment -o json --selector=telepresence=db2215375def4816bfd2114d9c0facba
  28.7 TEL | [12] captured in 1.24 secs.
  28.7 TEL | END SPAN remote.py:75(get_deployment_json)    1.2s

```

**Comment by marun** [comment]
@zwobill Using kubectl >= 1.18 with telepresence 0.104 is unsupported as per https://github.com/telepresenceio/telepresence/issues/1297. Closing as duplicate.

You'll need to downgrade either kubectl to a version pre-1.18 or upgrade to telepresence >= 0.105.
