### ISSUE TITLE
Support swapping deployment in non-default namespace 

### ISSUE THREAD

**Issue by zwobill** [telepresenceio/telepresence#1412]
We are running our services in non-default namespaces. However, Telepresence is looking for the deployment in the default namespace even I use `--namespace` argument to specify the namespace. [This function](https://sourcegraph.com/github.com/telepresenceio/telepresence/-/blob/telepresence/proxy/deployment.py#L289) seems not accept namespace as an input argument at all.

**Comment by marun** [comment]
telepresence works fine for me targeting a deployment in a non-default namespace indicated by  `--namespace`. I think it unlikely that what you are experiencing represents a problem with telepresence internals given how well-used this feature is.  Please provide more detail as to what you are attempting and the telepresence logs of that attempt to aid in diagnosing your issue.

**Comment by ipleten** [comment]
I bet you set `--namespace` as the last argument with `--run`.
If it's true instead of:
`telepresence --run curl ifconfig.me --namespace my-ms`
run it as:
`telepresence --namespace my-ms --run curl ifconfig.me`
