### ISSUE TITLE
Following video example had problems - version 0.105

### ISSUE THREAD

**Issue by saltybaker** [telepresenceio/telepresence#1417]
### What were you trying to do?

Follow the demo in the video

### What did you expect to happen?

It to work

### What happened instead?

It didn't

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--deployment', 'myserver', '--expose', '8080', '--run-shell']`
Version: `0.105`
Python version: `3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin ip-10-12-224-5.us-west-2.compute.internal 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 328, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
presence-5")'
 138.4  69 | c : DNS request from ('10.12.224.5', 60601) to None: 51 bytes
 138.5  14 | 2020-08-14T22:56:14+0000 [stdout#info] Result for b'hellotelepresence-5.saltstack.net' is ['127.0.0.1']
 139.4  69 | c : DNS request from ('10.12.224.5', 60601) to None: 51 bytes
 139.5  14 | 2020-08-14T22:56:15+0000 [stdout#info] Result for b'hellotelepresence-5.saltstack.net' is ['127.0.0.1']
 143.2 TEL | (proxy checking local liveness)
 143.3 TEL | [81] timed out after 5.01 secs.
 143.3 TEL | [82] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-5.a.sanity.check.telepresence.io")'
 143.3  14 | 2020-08-14T22:56:19+0000 [Poll#info] Checkpoint
 143.4  69 | c : DNS request from ('10.12.224.5', 51436) to None: 68 bytes
 143.5  14 | 2020-08-14T22:56:19+0000 [stdout#info] Sanity check: b'hellotelepresence-5.a.sanity.check.telepresence.io'
 143.5 TEL | [83] Running: sudo -n echo -n
 143.5 TEL | [83] ran in 0.03 secs.
 144.3 TEL | [82] timed out after 1.01 secs.

```

**Comment by marun** [comment]
@saltybaker A requirement of telepresence is to have `kubectl` or `oc` binaries in the path (depending on whether the target cluster is kubernetes or openshift), and it appears from the log output provided that neither binary is in the path.

**Comment by marun** [comment]
@saltybaker Separate from invoking telepresence, can you execute `kubectl version --short` without error?  The log output indicates an error condition when executing this command.

**Comment by saltybaker** [comment]
saltybob:raas-docker rbaker$ kubectl version --short

Client Version: v1.16.6-beta.0

Server Version: v1.16.8-eks-e16311

saltybob:raas-docker rbaker$

   -
   - Robert Baker
   Sr. Software Developer II
      - *■ CISSP*
   - *M: *801.691.9761
   saltstack.com <https://www.saltstack.com/>

**Comment by marun** [comment]
@saltybaker Does the shell environment in which you invoked kubectl manually match the one in which you invoked telepresence? The log output you posted suggests not:

```
kubectl version: (error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)
```

**Comment by saltybaker** [comment]
Different shell, but same box and same env variables


   -
   - Robert Baker
   Sr. Software Developer II
      - *■ CISSP*
   - *M: *801.691.9761
   saltstack.com <https://www.saltstack.com/>
