### ISSUE TITLE
Telepresence has issues with swapping a deployment in a GKE cluster

### ISSUE THREAD

**Issue by dimberman** [telepresenceio/telepresence#1421]
### What were you trying to do?

I am attempting to replace one pod in an existing deployment with a telepresence pod in a GKE cluster

### What did you expect to happen?

(please tell us)

### What happened instead?

Telepresence seems to be unable to ssh into the pod. I did not run into this issue with a a basic "myapp" deployment.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--mount', '/tmp/known', '--swap-deployment', 'extraterrestrial-cosmic-8920-scheduler:scheduler', '--docker-run', '--rm', '-v/Users/danielimberman/code/open-source/airflow/ha-private:/code', '-v=/tmp/known/var/run/secrets:/var/run/secrets', '-i', '-t', 'dimberman/airflow-ha-testing:0.0.3', '/entrypoint', 'bash']`
Version: `0.105`
Python version: `3.7.4 (default, Aug  2 2020, 15:13:34) 
[Clang 11.0.3 (clang-1103.0.32.62)]`
kubectl version: `Client Version: v1.16.6-beta.0 // Server Version: v1.14.10-gke.42`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Daniels-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
1-08--f261bb71-9sfw  Started container scheduler
 116.9 131 |   Normal  Pulled     47s   kubelet, gke-staging-cluster-staging-mt-01-08--f261bb71-9sfw  Successfully pulled image "registry.staging.astronomer.io/extraterrestrial-cosmic-8920/airflow:deploy-6"
 116.9 131 |   Normal  Created    34s   kubelet, gke-staging-cluster-staging-mt-01-08--f261bb71-9sfw  Created container scheduler-gc
 116.9 131 |   Normal  Started    34s   kubelet, gke-staging-cluster-staging-mt-01-08--f261bb71-9sfw  Started container scheduler-gc
 116.9 131 |   Normal  Pulled     34s   kubelet, gke-staging-cluster-staging-mt-01-08--f261bb71-9sfw  Container image "docker.io/istio/proxyv2:1.4.3" already present on machine
 116.9 131 |   Normal  Created    34s   kubelet, gke-staging-cluster-staging-mt-01-08--f261bb71-9sfw  Created container istio-proxy
 116.9 131 |   Normal  Started    33s   kubelet, gke-staging-cluster-staging-mt-01-08--f261bb71-9sfw  Started container istio-proxy
 116.9 TEL | [131] ran in 0.80 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
