### ISSUE TITLE
Default telepresence pod is too slow

### ISSUE THREAD

**Issue by dnlsndr** [telepresenceio/telepresence#1422]
The resource limits given to the default telepresence pod are extremely low. I understand that this is intentionally so that these pods don't impact the cluster in a big way. But working with the pod is extremely slow and often results in timeouts. Is there any way of manually setting the resource limits of a pod? That would be really useful for e.g. big database uploads to the server through a telepresence pod.

**Comment by onmyflow** [comment]
Nvm. I oversaw the pod limits which is "1" meaning one whole CPU is used for the pod. So the limits are not the issue. It would still be really nice to have more configuration options like @ark3 mentioned in his issue #985 .
