### ISSUE TITLE
Have the documentation reflect possibility to add more hosts to --also-proxy

### ISSUE THREAD

**Issue by blacksab** [telepresenceio/telepresence#1440]
It was far from obvious for me that the argParser for --also-proxy was of type append. The documentation could say something about the following possibility. Had to fork the code to figure this out.

```
  telepresence --run-shell --method vpn-tcp \
    --also-proxy example1.com \
    --also-proxy example2.com \
    --also-proxy example3.com

```

**Comment by divbhasin** [comment]
Hi, new contributor here :wave:.  I can work on this.
