### ISSUE TITLE
Unable to connect with telepresence when using WSL over a VPN to a remote cluster

### ISSUE THREAD

**Issue by gerhardlr** [telepresenceio/telepresence#1454]
### What were you trying to do?

connect a shell session via telepresence to a remote cluster over a VPN. 
command: telepresence --run-shell --method inject-tcp

### What did you expect to happen?

the shell should startup

### What happened instead?

SSH to the cluster failed to start
 14.8 TEL | [22] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 45729 telepresence@127.0.0.1 /bin/true
  14.8  11 | Handling connection for 45729
  15.5  11 | E1022 17:50:39.227498   23438 portforward.go:400] an error occurred forwarding 45729 -> 8022: error forwarding port 8022 to pod eddf271e666c0767db892049d808582037301b30383b787118f98e2f5fe7dafd, uid : signal: aborted (core dumped): nsenter: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
  15.5 TEL | [22] exit 255 in 0.67 secs.
  15.7 TEL | [23] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 45729 telepresence@127.0.0.1 /bin/true
  15.7  11 | Handling connection for 45729
  16.4  11 | E1022 17:50:40.155200   23438 portforward.go:400] an error occurred forwarding 45729 -> 8022: error forwarding port 8022 to pod eddf271e666c0767db892049d808582037301b30383b787118f98e2f5fe7dafd, uid : signal: aborted (core dumped): nsenter: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
  16.4 TEL | [23] exit 255 in 0.67 secs.

### Automatically included information

Command line: `['/usr/bin/telepresence', '--run-shell', '--method', 'inject-tcp']`
Version: `0.108`
Python version: `3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.19.3 // Server Version: v1.19.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux DESKTOP-JGK475M 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
d by a Secret)
  44.1  51 |     SecretName:  default-token-9ntqk
  44.1  51 |     Optional:    false
  44.1  51 | QoS Class:       Burstable
  44.1  51 | Node-Selectors:  <none>
  44.1  51 | Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
  44.1  51 |                  node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
  44.1  51 | Events:
  44.1  51 |   Type    Reason     Age   From               Message
  44.1  51 |   ----    ------     ----  ----               -------
  44.1  51 |   Normal  Scheduled  37s   default-scheduler  Successfully assigned tmcmid/telepresence-1603381823-7558825-23301 to devenv4
  44.1  51 |   Normal  Pulled     35s   kubelet            Container image "datawire/telepresence-k8s:0.108" already present on machine
  44.1  51 |   Normal  Created    35s   kubelet            Created container telepresence
  44.1  51 |   Normal  Started    35s   kubelet            Started container telepresence
  44.1 TEL | [51] ran in 2.08 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
