### ISSUE TITLE
Failed to restart after telepresence crashed.

### ISSUE THREAD

**Issue by welsonjr** [telepresenceio/telepresence#1458]
### What were you trying to do?

Trying to restart telepresence after it crashed.

### What did you expect to happen?

telepresence starts again without issue.

### What happened instead?

After having my telepresence crashed I was stuck on the root prompt, and it only managed past this phase after i used the "reset" command on my terminal.
And then telepresence is failing to start with the error listed below.

running from zsh on i-term2.

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.108`
Python version: `3.8.2 (default, Sep 24 2020, 19:37:08) 
[Clang 12.0.0 (clang-1200.0.32.21)]`
kubectl version: `Client Version: v1.18.8 // Server Version: v1.15.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin FLC0136.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
 3.6.8) starting up.
  78.0  12 | 2020-10-30T09:29:36+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  78.0  12 | 2020-10-30T09:30:07+0000 [Poll#error] Failed to contact Telepresence client:
  78.0  12 | 2020-10-30T09:30:07+0000 [Poll#error] An error occurred while connecting: 99: Address not available.
  78.1  12 | 2020-10-30T09:30:07+0000 [Poll#warn] Perhaps it's time to exit?
  80.8 TEL | [89] timed out after 5.03 secs.
  80.8 TEL | SSH timed out. Pod info follows.
  80.8 TEL | [90] Running: kubectl --context welson.costa --namespace welson-costa describe pod telepresence-1604050147-783714-55695
  89.7  12 | 2020-10-30T09:30:37+0000 [Poll#error] Failed to contact Telepresence client:
  89.7  12 | 2020-10-30T09:30:37+0000 [Poll#error] An error occurred while connecting: 99: Address not available.
  89.7  12 | 2020-10-30T09:30:37+0000 [Poll#warn] Perhaps it's time to exit?
  90.8 TEL | [90] timed out after 10.01 secs.

```

**Comment by yuswift** [comment]
I'm facing the same problem also. I installed `socat` all of the nodes. Then I solved the problem.
See [stackoverflow](https://stackoverflow.com/questions/60335754/runtimeerror-ssh-to-the-cluster-failed-to-start-when-using-telepresence).

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
