### ISSUE TITLE
Failed to contact Telepresence client：No route to host: 101: Network unreachable.

### ISSUE THREAD

**Issue by ronwxy** [telepresenceio/telepresence#1461]
### What were you trying to do?

I'm using win10 with ubuntu16 subsystem to run telepresense locally

### What did you expect to happen?

connect to k8s cluster in local area network

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.108`
Python version: `3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.16.0 // Server Version: v1.16.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux PC-20201029LNZQ 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
               node.kubernetes.io/unreachable:NoExecute for 300s
  58.5 133 | Events:
  58.5 133 |   Type    Reason     Age        From               Message
  58.5 133 |   ----    ------     ----       ----               -------
  58.5 133 |   Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned default/telepresence-1604472848-672215-1417 to knode3
  58.5 133 |   Normal  Pulled     34s        kubelet, knode3    Container image "datawire/telepresence-k8s:0.108" already present on machine
  58.5 133 |   Normal  Created    34s        kubelet, knode3    Created container telepresence
  58.5 133 |   Normal  Started    33s        kubelet, knode3    Started container telepresence
  58.5 TEL | [133] ran in 0.44 secs.
  58.8  13 | 2020-11-04T06:55:05+0000 [Poll#error] Failed to contact Telepresence client:
  58.8  13 | 2020-11-04T06:55:05+0000 [Poll#error] No route to host: 101: Network unreachable.
  58.8  13 | 2020-11-04T06:55:05+0000 [Poll#warn] Perhaps it's time to exit?

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
