### ISSUE TITLE
telepresence fail with inject-tcp mode on mac os bigsur

### ISSUE THREAD

**Issue by arielhernandezmusa** [telepresenceio/telepresence#1478]
### What were you trying to do?

Runnin K3S cluster on multipass on mac and then running:

telepresence --method inject-tcp --swap-deployment api --namespace local --expose 8080:8080

### What did you expect to happen?

(please tell us)

### What happened instead?
telepresence log:

https://gist.github.com/arielhernandezmusa/dac07a7c592a9b9025c6db34d07f16b4

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'inject-tcp', '--swap-deployment', 'api', '--namespace', 'local', '--expose', '8080:8080']`
Version: `0.108`
Python version: `3.8.6 (default, Nov 20 2020, 23:57:10) 
[Clang 12.0.0 (clang-1200.0.32.27)]`
kubectl version: `Client Version: v1.19.0 // Server Version: v1.19.3+k3s3`
oc version: `oc v3.11.0+0cbc58b // kubernetes v1.11.0+d4cacc0 // features: Basic-Auth //  // Server https://192.168.64.17:6443 // kubernetes v1.19.3+k3s3`
OS: `Darwin NTBK-UY178.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 104, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  18.5 TEL | [109] exit -11 in 0.06 secs.
  18.6 TEL | [110] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  18.6 TEL | [110] exit -11 in 0.06 secs.
  18.7 TEL | [111] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  18.8 TEL | [111] exit -11 in 0.06 secs.
  18.9 TEL | [112] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  19.0 TEL | [112] exit -11 in 0.05 secs.
  19.1 TEL | [113] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  19.1 TEL | [113] exit -11 in 0.06 secs.
  19.2 TEL | [114] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  19.3 TEL | [114] exit -11 in 0.06 secs.
  19.3 TEL | END SPAN local.py:42(set_up_torsocks)   15.0s

```

**Comment by arielhernandezmusa** [comment]
By running the same command with vpn-tcp mode all works, but the multipass instances are left without internet

**Comment by sourceplayer** [comment]
I have same exact issue after upgrading to Big Sur. Any developments on this case for you?

**Comment by vfried** [comment]
I am having the same problem, anyone found a solution for this?

**Comment by leandroyalet** [comment]
same here, the issue is related to torsocks lib and Big Sur compatibility https://gitlab.torproject.org/tpo/core/torsocks/-/issues/40005 so I imagine that's why is crashing with "RuntimeError: SOCKS network proxying failed to start..."
