### ISSUE TITLE
Failed to use Telepresence to debug a golang k8s operator 

### ISSUE THREAD

**Issue by zohar-mizrahi** [telepresenceio/telepresence#1480]
### What were you trying to do?

I was trying to debug a golang operator locally using Telepresence. Just followed the instructions in: https://www.telepresence.io/tutorials/intellij 

### What did you expect to happen?

Be able to run the operator controller locally via IntelliJ

### What happened instead?

The shell exited with an error.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--namespace', 'datarobot-lrs', '--swap-deployment', 'lrs-controller-manager-datarobot-lrs', '--env-json', 'lrs-operator.json']`
Version: `0.108`
Python version: `3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.18.1 // Server Version: v1.16.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux zohar-Ubuntu 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
eachable:NoExecute for 300s
  38.5 128 | Events:
  38.5 128 |   Type    Reason     Age   From                    Message
  38.5 128 |   ----    ------     ----  ----                    -------
  38.5 128 |   Normal  Scheduled  32s   default-scheduler       Successfully assigned datarobot-lrs/lrs-controller-ma-3e731a96cd744d3cb4f3086c81725a23 to node.localdev
  38.5 128 |   Normal  Pulled     32s   kubelet, node.localdev  Container image "datawire/telepresence-k8s:0.108" already present on machine
  38.5 128 |   Normal  Created    31s   kubelet, node.localdev  Created container manager
  38.5 128 |   Normal  Started    31s   kubelet, node.localdev  Started container manager
  38.5 TEL | [128] ran in 0.07 secs.
  39.1  14 | 2020-11-26T16:46:47+0000 [Poll#error] Failed to contact Telepresence client:
  39.1  14 | 2020-11-26T16:46:47+0000 [Poll#error] An error occurred while connecting: 99: Address not available.
  39.1  14 | 2020-11-26T16:46:47+0000 [Poll#warn] Perhaps it's time to exit?

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
