### ISSUE TITLE
Having problems running telepresence in macOS big sur

### ISSUE THREAD

**Issue by vfried** [telepresenceio/telepresence#1491]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'virginia-renku-ui', '--namespace', 'virginia', '--method', 'inject-tcp', '--expose', '3000:8080', '--run', 'npm', 'start']`
Version: `0.108`
Python version: `3.9.1 (default, Dec 10 2020, 11:11:14) 
[Clang 12.0.0 (clang-1200.0.32.27)]`
kubectl version: `Client Version: v1.19.4 // Server Version: v1.15.12`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin staff-net-vpn-dhcp-6409.ethz.ch 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 104, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  27.5 TEL | [108] exit -11 in 0.07 secs.
  27.6 TEL | [109] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  27.7 TEL | [109] exit -11 in 0.06 secs.
  27.8 TEL | [110] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  27.9 TEL | [110] exit -11 in 0.06 secs.
  28.0 TEL | [111] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  28.0 TEL | [111] exit -11 in 0.06 secs.
  28.1 TEL | [112] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  28.2 TEL | [112] exit -11 in 0.06 secs.
  28.3 TEL | [113] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  28.4 TEL | [113] exit -11 in 0.06 secs.
  28.4 TEL | END SPAN local.py:42(set_up_torsocks)   15.0s

```

**Comment by Maartz** [comment]
Got the same issue here. With the exact same output for this command:

```
telepresence --method=inject-tcp --run-shell --expose 8080
```

I first thought it was related to OSXFuse but it isn't.

**Comment by Maartz** [comment]
Seems to be duplicated with this one:
https://github.com/telepresenceio/telepresence/issues/1487
