### ISSUE TITLE
install    error: 'fuse_lowlevel.h' file not found

### ISSUE THREAD

**Issue by a123993930** [telepresenceio/telepresence#1526]
==> Installing telepresence from datawire/blackbird
==> Downloading https://github.com/libfuse/sshfs/commit/667cf34622e2e873db776791df275c7a582d6295.patch?full_index=1
Already downloaded: /Users/tony/Library/Caches/Homebrew/downloads/cdcad74dd3989c7992d0df5c9d06cabde2b6d7523ddbb551712a3733e0ba4b02--667cf34622e2e873db776791df275c7a582d6295.patch
==> Downloading https://github.com/libfuse/sshfs/releases/download/sshfs-2.10/sshfs-2.10.tar.gz
Already downloaded: /Users/tony/Library/Caches/Homebrew/downloads/530b903f02c905bfdb15b1859c391f8383cfaac570656f7396ed07ca0817fd93--sshfs-2.10.tar.gz
==> Downloading https://s3.amazonaws.com/datawire-static-files/telepresence/telepresence-0.109.tar.gz
Already downloaded: /Users/tony/Library/Caches/Homebrew/downloads/8efc5a58e92ea9b539fbe473e4433ef5574a1735161041386c4c102f6fbdc4cf--telepresence-0.109.tar.gz
==> Installing dependencies for datawire/blackbird/telepresence: sshfs
Warning: sshfs has been deprecated because it requires FUSE!
==> Installing datawire/blackbird/telepresence dependency: sshfs
==> Patching
==> Applying 667cf34622e2e873db776791df275c7a582d6295.patch
patching file sshfs.c
Hunk #1 succeeded at 3862 (offset -58 lines).
==> ./configure --prefix=/opt/homebrew/Cellar/sshfs/2.10_2
==> make install
Last 15 lines from /Users/tony/Library/Logs/Homebrew/sshfs/02.make:
make
install

Making install in test
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
clang -DHAVE_CONFIG_H -I.  -D_REENTRANT -DFUSE_USE_VERSION=26 -DLIBDIR=\"/opt/homebrew/Cellar/sshfs/2.10_2/lib\" -DIDMAP_DEFAULT="\"user\""  -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse -I/opt/homebrew/Cellar/pcre/8.44/include -I/opt/homebrew/Cellar/glib/2.66.4_1/include -I/opt/homebrew/Cellar/glib/2.66.4_1/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.66.4_1/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -g -O2 -Wall -W -I./compat -c -o sshfs-sshfs.o `test -f 'sshfs.c' || echo './'`sshfs.c
clang -DHAVE_CONFIG_H -I.  -D_REENTRANT -DFUSE_USE_VERSION=26 -DLIBDIR=\"/opt/homebrew/Cellar/sshfs/2.10_2/lib\" -DIDMAP_DEFAULT="\"user\""  -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse -I/opt/homebrew/Cellar/pcre/8.44/include -I/opt/homebrew/Cellar/glib/2.66.4_1/include -I/opt/homebrew/Cellar/glib/2.66.4_1/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.66.4_1/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -g -O2 -Wall -W -I./compat -c -o sshfs-cache.o `test -f 'cache.c' || echo './'`cache.c
sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
#include <fuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sshfs-sshfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

-------------

<img width="571" alt="image" src="https://user-images.githubusercontent.com/14154742/106864682-2f3daa80-6705-11eb-9f49-c6653a156425.png">

**Comment by jonbern** [comment]
I got the same problem on my Mac Mini with Apple Silicone, but got around it by installing the latest MacFUSE version directly (https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.5), and building Telepresence from source:

https://www.telepresence.io/reference/install

```
sudo env PREFIX=/usr/local ./install.sh
```

Make sure you have all the other dependencies already installed before building Telepresence from source: https://www.telepresence.io/reference/install#dependencies
