### ISSUE TITLE
Improve handling of default action for mounting remote volumes

### ISSUE THREAD

**Issue by thallgren** [telepresenceio/telepresence#1562]
## Background

Mounting remote volumes requires that `sshfs` is installed on the laptop. On a MacOS, the installed version must also be fairly recent. Some problems arise when this prerequisite is combined with having mounts being the default behaviour. What should happen in case the prerequisites aren't fulfilled? The current approach is to print an error and ask the user to change the default by adding the `--mount=false` flag and that isn't very appealing to new users who haven't even thought about mounting volumes yet (or other users who are not using mounts).

## Proposal

* Let `--mount=true` remain the default, but only if the above mentioned prerequisite is fulfilled. If it isn't, then silently change the default to `--mount=false` and continue the intercept.
* Add an additional text to the intercept status summary that informs the user that the volume mounts are disabled and for what reason. This status should only be shown when mounts are prevented due to unfulfilled prerequisites (we already display mounted volumes when things are OK).

**Comment by khussey** [comment]
This has been fixed in the 2.1.1 release, which is now available.
