### ISSUE TITLE
[v2] cluster domain is hardcoded to cluster.local

### ISSUE THREAD

**Issue by an-tex** [telepresenceio/telepresence#1572]
Services can be resolved using not only "service.namespace" but also "service.namespace.svc.cluster-domain". By default "cluster-domain" is "cluster.local" but it can be [configured in the kubelet](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/).

This configuration is obayed in telepresence 1 but ignored in telepresence 2, where the cluster domain seems to be hardcoded to "cluster.local". This breaks existing workflows when migrating from telepresence 1.

**Comment by an-tex** [comment]
There's actually a workaround using `dns/include-suffixes` as documented here https://www.telepresence.io/docs/latest/reference/config/ . I guess it'd still be nice to not have it manually defined but automatically included as in t1

**Comment by thallgren** [comment]
This is no longer the case.
