### ISSUE TITLE
[v2] feature request -- improve handling for file directories when using volume mounts

### ISSUE THREAD

**Issue by peteroneilljr** [telepresenceio/telepresence#1602]
Problem: For files mounted in a specific directory in the k8s cluster, references to this folder/file cannot be automatically used when mounted locally. 

Let's say you have an env var `KUBE_SETTINGS_FILE=/var/folder/config.yaml` this works in the cluster, but once it is mounted with Telepresence this file now lives under the assigned directory. 

Could we find a way to make this process more seamless? Such as adding a flag to prepend the mounted directly to any file paths we see in the environment variables?

**Comment by cindymullins-dw** [comment]
Thanks, @peteroneilljr! This particular problem should go away if you run the intercept handler as a docker container.  But to somehow modify the environment retrieved from the pod is an interesting idea so we'll leave this feature request open.
