### ISSUE TITLE
[v2] - Feature request - Develop an ability to intercept several ports of deployment

### ISSUE THREAD

**Issue by andreykrupskii** [telepresenceio/telepresence#1607]
First of all, I'm a big fan of telepresence as it's making the development process more convenient and saves my time. While I'm still not able to migrate to Telepresence 2 because of two problems. And this issue is about one of them. 

**Problem**: In our infrastructure micro-services listen two ports: one for public and one for internal requests (inside kubernetes network). When I'm intercepting deployment - the traffic should be proxied for all ports.

**Comment by andreykrupskii** [comment]
Just a kind reminder, are there any updates on this issue? =)

**Comment by jceb** [comment]
It would be great to get a solution for this issue. It's currently hindering me from using version 2.

**Comment by davemaier** [comment]
Pushing this a bit. Would really nice to have!

**Comment by PopChicken** [comment]
Really need this feature :D. It cannot be used on the cluster of my company because of this.

**Comment by r-mironov** [comment]
+1

**Comment by elig-salt** [comment]
This would be incredible !

Unfortunately, this causes us to only use Telepresence for about 50% of our services (which only use gRPC).
Most of our services are moving to gRPC (so we have both HTTP and gRPC), but even then - 
many of our services will always have both (some have legacy TCP protocols like `Akka` as well - a third protocol) so if we run `Telepresence intercept` some of the functionality is just broken when debugging locally.

**Comment by zzbennett** [comment]
In the meantime, if multiple ports are not supported, it would be great if telepresence could throw an error if multiple `--port` args are passed, instead of just taking the last one in the list

(also throwing on to the pile that lack of multiple port support is a blocker for as well as our services expose both http and grpc ports, both of which need to be intercepted)

**Comment by SomaticIT** [comment]
👍  Would be awesome!

**Comment by mumayuan** [comment]
I wrote a feature request #2318 for the same thing :)
(So I closed the other one when found out this)

It will be the key feature for adoption to our project !  Please let us know when this is scheduled for delivery!

**Comment by gersp** [comment]
+1
My service has two ports GRPC and HTTP and I need to intercept both of them
