### ISSUE TITLE
error Failed to contact Telepresence client

### ISSUE THREAD

**Issue by anhongyang125** [telepresenceio/telepresence#1609]
win10-wsl(ubuntu 18.04) run telepresence, Error is as follows

root@PC:~/telepresence$ telepresence
T: Using a Pod instead of a Deployment for the Telepresence proxy. If you experience problems, please file an issue!
T: Set the environment variable TELEPRESENCE_USE_DEPLOYMENT to any non-empty value to force the old behavior, e.g.,
T:     env TELEPRESENCE_USE_DEPLOYMENT=1 telepresence --run curl hello

T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with T:  --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Pod telepresence-1617009859-353349-11098

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

Here are the last few lines of the logfile (see /root/telepresence/telepresence.log for the complete logs):

  55.1 104 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  55.1 104 | Events:
  55.1 104 |   Type    Reason     Age   From               Message
  55.1 104 |   ----    ------     ----  ----               -------
  55.1 104 |   Normal  Scheduled  72s   default-scheduler  Successfully assigned default/telepresence-1617009859-353349-11098 to ubuntu
  55.1 104 |   Normal  Pulled     70s   kubelet, ubuntu    Container image "datawire/telepresence-k8s:0.109" already present on machine
  55.1 104 |   Normal  Created    70s   kubelet, ubuntu    Created container telepresence
  55.1 104 |   Normal  Started    70s   kubelet, ubuntu    Started container telepresence
  55.2 TEL | [104] ran in 0.24 secs.
  56.6  12 | 2021-03-29T09:24:36+0000 [Poll#error] Failed to contact Telepresence client:
  56.6  12 | 2021-03-29T09:24:36+0000 [Poll#error] An error occurred while connecting: 99: Address not available.
  56.6  12 | 2021-03-29T09:24:36+0000 [Poll#warn] Perhaps it's time to exit?

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
