### ISSUE TITLE
vpn-tcp (sshuttle) method doesn't work with fully qualified .local domains on Linux

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#161]
sshuttle works by capturing DNS packets. `.local` domains are often handled (on Linux) earlier than DNS, via mDNS nss plugin, so sshuttle never captures them. This is only a problem on Linux.

Potential solution: bind mount (in mount namespace) a new /etc/nss.conf that disable mDNS for the telepresence subprocess.

**Comment by jascott1** [comment]
@itamarst This appears to be a requirement for my current project but .local DNS also seems worthwhile in general. I started looking into the potential solution you suggested but can you please share more details?

**Comment by itamarst** [comment]
On Ubuntu 16.04:

```
$ cat /etc/nsswitch.conf  | grep hosts
hosts:          files mdns4_minimal [NOTFOUND=return] dns
```

What that says is: "When looking up DNS hosts, check local files (e.g. /etc/hosts), then mDNS, then DNS."

You can use `mount --bind` to override any file for a particular process, given a new mount namespace (which you can create with `unshare`). So, this approach is something like:

1. Create new mount namespace for telepresence and its subprocesses using `unshare`.
2. Create nsswitch.conf version that doesn't list `mDNS`.
3. Use `mount --bind` to override `/etc/nsswitch.conf` in the mount namespace.

That's the theory.

There may be other, simpler approaches.

**Comment by jascott1** [comment]
@itamarst Thanks for the reply. Which host needs the nsswitch.conf modifications? I looked in minikube and it has no mDNS entries. I have a dumb Ubuntu 16.04 (running /sbin/init) deployment that I swap with telepresence for my local. That container also does not have mDNS in its nsswitch.conf. 

My goal is to develop an operator on minikube and run the operator code (golang) locally on mac using telepresence. I was successful in getting the operator to run in this way but it closed after failing to resolve DNS. Is this golang related?

**Comment by ark3** [comment]
@jascott1 This issue concerns running Telepresence (and your own code) on a Linux host, i.e. the development machine is Linux. When your code performs a DNS lookup for `blah.blah.local` Telepresence fails to capture/redirect it on Linux. If you're running Telepresence on a Mac, you will not hit this particular issue. 

That said, we should figure out what's going wrong and get you productive. Can you open a new issue and/or poke us on Gitter? Thanks.

@itamarst Thanks for expanding on the potential solution.

**Comment by mornindew** [comment]
Any update on this issue, I think that i have hit this when trying to access my redis cluster via telepresence.   Works fine when I port-forward a specific pod or when I deploy into K8s.   

Developing locally and attempting to use the service wont allow me to access redis cache via service name.   I can probably work around by manually using port-forwarding locally and then use the URL localhost:<port> when connecting to redis.   This seems to work but isn't really using the service properly

I am developing on ubuntu (18.04) and let me know if you have any questions.

**Comment by LukeShu** [comment]
I wonder if proxying `/run/avahi-daemon/socket` would make mDNS work.

**Comment by LukeShu** [comment]
This works with nss-mdns 1.11 or newer.  Unfortunately, many users (including @rhs) are still running 1.10.  Users running 1.10 or older can work around the issue by removing changing `mdns_minimal [NOTFOUND=return]` to `mdns_minimal` (or `mdns4_minimal`, if they would not like to use mDNS with IPv6) in their `/etc/nsswitch.conf`.

@ofpiyush Drop `[NOTFOUND=return]`, don't move it. Things in brackets are settings for the *preceding* item; `mdns4_minimal [NOTFOUND=return] dns` sets the `mdns4_minimal` module's `NOTFOUND` setting, and leaves the `dns` module's settings as their defaults.  Changing it to `mdns4_minimal dns [NOTFOUND=return]` instead sets the `dns` module's `NOTFOUND` setting, which you almost certainly do NOT want.

**Comment by imic07** [comment]
if you use ubuntu, use this view nss-mdns version:
```
root@ubuntu:/home/imic/data/soft#  dpkg -l | grep nss-mdns
ii  libnss-mdns:amd64                          0.10-8ubuntu1                                amd64        NSS module for Multicast DNS name resolution
```
you must use  [nss-mdns≥0.11](https://github.com/lathiat/nss-mdns/blob/master/NEWS.md#mon-jan-22-2018) 

install newest nss-mdns:
```
cd /data/soft
wget http://kr.archive.ubuntu.com/ubuntu/pool/main/n/nss-mdns/libnss-mdns_0.14.1-1_amd64.deb
sudo dpkg -i libnss-mdns_0.14.1-1_amd64.deb
```

**Comment by robertaramar** [comment]
Same for me, dns before mdns4_minimal fixed the issue. I guess, as I am not using really local .local addresses a lot, it will not make a big difference to my system, to leave that this way.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
