### ISSUE TITLE
How can I run this in the background?

### ISSUE THREAD

**Issue by helloguille** [telepresenceio/telepresence#1613]
I think this is so great that I want to start telepresence everytime I log into my MacOSX.

- Is that advisable?
- How could I do that?

**Comment by cindymullins-dw** [comment]
Hi @helloguille, you’d have to create a process so it starts up when you log in but that's outside of our product scope.  We do have users who have incorporated Telepresence commands into the CLIs, as in this [Voiceflow case study](https://www.getambassador.io/learn/case-studies/voiceflow).
