### ISSUE TITLE
[v2] The daemon ignores errors from `iptables`

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1618]
The daemon logs errors from `iptables`, but does nothing with them, the daemon continues running even though a core part of its operation has failed.  `telepresence status` will tell you that everything is fine and operational, but things will mysteriously not work.  This can happen when run without the appropriate capabilities (i.e. in a container), or when the netfilter kernel module could not be loaded (i.e. the user needs to reboot).

The daemon should treat errors from iptables as errors, and report them as such.

**Comment by khussey** [comment]
This is fixed in the 2.3.0 release, which is now available.
