### ISSUE TITLE
[v2] Errors from ssh are poorly detected

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1620]
If the connector is unable to start `ssh` (perhaps `ssh` isn't even installed!), it just retries indefinitely, instead of reporting an error.  So `telepresence status` says everything's good, but things mysteriously don't work.

There are two parts to this, really:
- We don't distinguish between errors of type `*dexec.ExecError` and other error types (such as `*dexec.LookError` in the "not installed" case).
- The infinite retry is good, _after_ we've established it working at least once; it shouldn't inhibit us from detecting "it doesn't work at all" (related: https://github.com/telepresenceio/telepresence/issues/1621).

**Comment by khussey** [comment]
This is fixed in the 2.3.0 release, which is now available.
