### ISSUE TITLE
[v2] Can't detect when there's a problem with the SOCKS server

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1621]
If `ssh` has a problem running the SOCKS server (perhaps because of https://github.com/telepresenceio/telepresence/issues/1619), OpenSSH doesn't report that as an error (despite `-oExitOnForwardFailure=yes`), and so Telepresence doesn't detect it, and `telepresence status` says everything's fine, but things are mysteriously not working.

Telepresence needs an internal health check on the SOCKS server.

**Comment by khussey** [comment]
This is fixed in the 2.3.0 release, which is now available.
