### ISSUE TITLE
[v2] Replace OpenSSH with Go code

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1623]
We originally used OpenSSH for some port-forwarding tasks and for its built-in SOCKS server, because it was expedient to do so.  We should rip it out and replace those tasks with Go code.  OpenSSH (and it's dependency on OpenSSL), pulls in a bunch of _unneeded_ machinery that increases the attack surface.  I don't want to have to do security releases because of  CVEs in a product we're not on the embargo list for. And this should improve our error handling and such to reduce the number of edge cases.

**Comment by thallgren** [comment]
Resolved by #1686
