### ISSUE TITLE
Running Telepresence in WSL1 errors out

### ISSUE THREAD

**Issue by zaf187** [telepresenceio/telepresence#1624]
### What were you trying to do?

Use Telepresence to swap a deployment running on a remote kubernetes cluster. K8s cluster was configured to run on metal.

I ran the command from within a WSL1 session, with my machine connected to a corporate VPN.

### What did you expect to happen?

NOT see an error, a valid env.json file to be generated

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'foo-deployment', '--env-json', 'foo-deployment_env.json']`
Version: `0.109`
Python version: `3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]`
kubectl version: `Client Version: v1.18.6 // Server Version: v1.20.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux Wkhan3510 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
("hellotelepresence-41")'
  53.3 TEL | [110] exit 1 in 0.34 secs.
  53.3 TEL | [111] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-41.a.sanity.check.telepresence.io")'
  53.7 TEL | [111] exit 1 in 0.35 secs.
  53.8 TEL | Wait for vpn-tcp connection: hellotelepresence-42
  53.8 TEL | [112] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-42")'
  54.1 TEL | [112] exit 1 in 0.30 secs.
  54.1 TEL | [113] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-42.a.sanity.check.telepresence.io")'
  54.4 TEL | [113] exit 1 in 0.30 secs.
  54.5 TEL | Wait for vpn-tcp connection: hellotelepresence-43
  54.5 TEL | [114] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-43")'
  54.8 TEL | [114] exit 1 in 0.35 secs.
  54.8 TEL | [115] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-43.a.sanity.check.telepresence.io")'
  55.1 TEL | [115] exit 1 in 0.30 secs.

```

**Comment by cindymullins-dw** [comment]
Closing since V1 is deprecated.  If issues persist on newer versions please let us know.
