### ISSUE TITLE
[v2] Intercepting Headless Services doesn't quite work

### ISSUE THREAD

**Issue by donnyyung** [telepresenceio/telepresence#1632]
When intercepting a workload with a Headless Service, the intercept actions will still work, but service doesn't appear to be intercepted when accessing it on the containerPort.  This is because headless services don't use the port information in the service and instead resolve to a list of IPs for the pods associated with the service. 

So if you accessing your service with port 9900 (the port the traffic-agent uses), then you will see the intercept behave as expected.  It would be better if intercepting headless services would ~ just work ~ the way intercepts of non-headless services do.

**Comment by thallgren** [comment]
We have two alternatives:
1. Prevent that the intercept is allowed to proceed and report a false success. Instead, show an error and inform the user of possible alternatives.
2. Automatically replace the headless service with a service that acts as a proxy.

I think the second alternative is rather intrusive so my preference would be the first.

**Comment by iTaybb** [comment]
I would like that feature as well.
Would like to help with the implementation if needed.

**Comment by khussey** [comment]
This was fixed in the 2.4.5 release, which is now available.
