### ISSUE TITLE
[v2] Cannot access service.namespace after `telepresence connect`

### ISSUE THREAD

**Issue by sp0cket** [telepresenceio/telepresence#1649]
After upgrade to telepresence 2.1.4, I cannot access service via `${service-name.namespace}` in cluster any more. And 2.1.3 works fine, So I have to degrade to 2.1.3 right now.

* macOS 11.2.3

**Comment by thallgren** [comment]
Can you please try with the latest Telepresence and see if this problem persists? And if it does, can you please provide the connector.log and daemon.log from the failing session. You'll find the logs under `~/Library/Logs/telepresence`

**Comment by tinawu0603** [comment]
@thallgren I'm getting the same thing on version 2.2.2.

I'm able to `curl -ik https://kubernetes.default` (get an expected 401 unauthorized response) but not the hello service in v2's readme. DNS resolution works but getting the following:
```
 → curl hello.default
curl: (52) Empty reply from server
```

The cluster is hosted on AKS and I'm also on a company VPN if those helps to contextualize the problem.

**Comment by thallgren** [comment]
Hi @sp0cket  @tinawu0603. Can you please try 2.3.0 and see if it resolves this issue? The 2.3.0 release contains a lot of improvements that should make Telepresence play better with various VPNs.

**Comment by sp0cket** [comment]
I tested on 2.3.0 and this bug seems not fixed. 
logs from `connector.log`
```
2021/06/08 02:19:23.3178 info    connector/background-manager/intercept-port-forward/:33085 : Mounting file system for intercept "xxxxx" at "/tmp/telfs-583559993" (from pkg/client/connector/intercept.go:405)
2021/06/08 02:19:23.3181 debug   connector/background-manager/intercept-port-forward/:33085 : sshfs waiting 3s before retrying after error: dial tcp :33085: connect: connection refused (from pkg/client/retry.go:48)
2021/06/08 02:19:26.3220 debug   connector/background-manager/intercept-port-forward/:33085 : sshfs waiting 6s before retrying after error: dial tcp :33085: connect: connection refused (from pkg/client/retry.go:48)
2021/06/08 02:19:32.3266 debug   connector/background-manager/intercept-port-forward/:33085 : sshfs waiting 6s before retrying after error: dial tcp :33085: connect: connection refused (from pkg/client/retry.go:48)
...
```

**Comment by sp0cket** [comment]
And 2.1.3 works fine for me, right now

**Comment by thallgren** [comment]
That log suggests a different problem than "Cannot access service.namespace" though. Here, apparently you succeed with the intercept but then the sshfs isn't mounted correctly. Are you using a service mesh of some sort? E.g. Istio or Kiam?

**Comment by thallgren** [comment]
@sp0cket do you get any output from `kubectl  get nodes -o jsonpath={..spec.podCIDR}` on your workstation?

**Comment by sp0cket** [comment]
Yes, I'm using Istio.
output from `podCIDR`:`10.42.10.0/24 10.42.6.0/24 10.42.7.0/24 10.42.8.0/24 10.42.3.0/24 10.42.5.0/24 10.42.9.0/24 10.42.0.0/24 10.42.2.0/24 10.42.1.0/24`

**Comment by sp0cket** [comment]
So maybe that's a different issue with `access service.namespace`?
I tested connect redis by redis-cli after `telepresence  --mapped-namespaces redis connect`
Output:`Could not connect to Redis at redis.redis:6379: Operation timed out`

**Comment by thallgren** [comment]
It's likely that DNS is blocked because you have an active intercept that Istio prevents from communicating. We are working on a solution for this in #1747.

**Comment by sp0cket** [comment]
Tested on 2.3.2,  This issue seems not fixed

**Comment by sp0cket** [comment]
Update:
```
nc -vz redis.redis 6379
Connection to redis.redis port 6379 [tcp/*] succeeded!
```
```
nslookup redis.redis
Server:		198.18.0.2
Address:	198.18.0.2#53

Non-authoritative answer:
Name:	redis.redis
Address: 198.18.2.91
```
```
redis-cli redis.redis
redis.redis:6379>
redis.redis:6379> keys *
Error: Connection reset by peer
```

**Comment by sneko** [comment]
Just here to say I'm also concerned by this with `Telepresence v2.4.9` (mentioned this in an issue asking for Istio support https://github.com/telepresenceio/telepresence/issues/1705#issuecomment-1000243251).

Did someone find a work around since then?

Thank you,

**Comment by sp0cket** [comment]
It works fine,Thx
