### ISSUE TITLE
[v2] Telepresence gets confused when something else edits a workload

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1669]
This is an offshoot of https://github.com/telepresenceio/telepresence/issues/1658

Telepresence doesn't (can't?) quite know how to undo injecting the traffic-agent sidecar to a Deployment if something else has since edited the Deployment in a conflicting way.  To resolve #1658, we're working on improving diagnostic messages and documentation, but aren't addressing the underlying issue; that is what this ticket is being created for.

I believe we can address the issue by bringing back Service Preview's admissions-controller approach; rather than having the connector do all the work.

**Comment by thallgren** [comment]
This doesn't apply anymore since we now inject our agent using a mutating webhook.
