### ISSUE TITLE
Failed to install telepresence on my redhat 7.9 

### ISSUE THREAD

**Issue by Ibn-coulibaly** [telepresenceio/telepresence#1675]
Hello, 

By trying to install telepresence using the [installation from source](https://www.telepresence.io/reference/install) method, I got this error when running this command with the install.sh script : 

**sudo env PREFIX=/usr/local ./install.sh**
Installing Telepresence in /usr/local
python3: can't open file 'packaging/build-telepresence.py': [Errno 2] No such file or directory

my python version is : 
python --version 
**Python 3.6.8**

Could someone please help me resolve this issue? 

BR.

**Comment by gll910802** [comment]
check out your source code version 
and the file 'packaging/build-telepresence.py' exist or not in the path
