### ISSUE TITLE
[v2] Unable to build telepresence binary for OSX

### ISSUE THREAD

**Issue by pankrator** [telepresenceio/telepresence#1677]
I am trying to build telepresence on my Mac with the following command:

```sh
make install
```

The result is as follows
```
Building TELEPRESENCE_VERSION=v2.1.6-39-g69d6b381-1618907788
go install -ldflags=-X=github.com/telepresenceio/telepresence/v2/pkg/version.Version=v2.1.6-39-g69d6b381-1618907788 ./cmd/telepresence
# github.com/datawire/pf
vendor/github.com/datawire/pf/address.go:11:11: fatal error: 'net/pfvar.h' file not found
 #include <net/pfvar.h>
          ^~~~~~~~~~~~~
1 error generated.
make: *** [install] Error 2
```

I have search for the header file, but did not find anything that would help. Any sugesstions would be helpful?

**Comment by thallgren** [comment]
We're building Telepresence on MacOS everyday, so this is surprising. Not sure how to figure out what's causing the error. What version of MacOS are you on? Are you using Xcode command line tools? Do you have an up-to-date `brew` install?

**Comment by pankrator** [comment]
Sorry for the late response. 
My Mac version is:

```sh
sw_vers                    
ProductName:	macOS
ProductVersion:	11.2.3
```

Yes, I am using Xcode command line tools and updated them. 
As far as I know and found out, there is no brew for telepresence v2.

**Comment by cindymullins-dw** [comment]
Brew install is available for [macOS installation](https://www.getambassador.io/docs/telepresence/latest/install).
