### ISSUE TITLE
[v2] Can't connect to a new namespace until telepresence connect is restarted

### ISSUE THREAD

**Issue by scottillogical** [telepresenceio/telepresence#1692]
I often destroy & recreate namespaces and observed that I frequently need to quit & reconnect telepresence to route requests to a new namespace.       

To reproduce:
1. Start `telepresence connect`
2. Deploy a new namespace  (e.g. sandbox-scott) and deploy something there (e..g. postgres)  `helm -n sandbox-scott1 install  --create-namespace redis  bitnami/redis `
3. Observe that you cannot route via telepresence to the new k8s namespace  ```telnet redis-headless.sandbox-scott1 6379``` returns `redis-headless.sandbox-scott1: nodename nor servname provided, or not known`
4. Restart telepresence `telepresence quit && telepresence connect`
5. Observe that you can make requests via tp to new namespace `telnet redis-headless.sandbox-scott1 6379 Connected to redis-headless.sandbox-scott1.`

**Comment by thallgren** [comment]
The DNS is different on different platforms and versions of telepresence. Can you please convey info about what OS you're running on and what version of Telepresence you're using?

**Comment by scottillogical** [comment]
@thallgren  OSX.  I also frequently use a cisco VPN

**Comment by thallgren** [comment]
Ok. We know that we have some issues when VPNs are in use. Is there an easy way for you to check if it works without the VPN?

**Comment by scottillogical** [comment]
I tried to reproduce this and was not able to this time on or off vpn.  Closing for now will reopen or open a new issue if I have more clarity on whats happening, sorry!
