### ISSUE TITLE
Cluster type incorrectly detected as OpenShift

### ISSUE THREAD

**Issue by betterphp** [telepresenceio/telepresence#1696]
When running a telepresence command we get the following error even though we are not using OpenShift.
```
T: OpenShift does not support ports <1024.
```

After a bit of investigation it seems that the check for OpenShift/kubectl looks for "openshift.io" in the output of `kubectl api-versions`, here https://github.com/telepresenceio/telepresence/blob/master/telepresence/startup.py#L173

For our setup the output of this command is
```
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
ceph.rook.io/v1
certificates.k8s.io/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
discovery.k8s.io/v1beta1
events.k8s.io/v1
events.k8s.io/v1beta1
extensions/v1beta1
flowcontrol.apiserver.k8s.io/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1
node.k8s.io/v1beta1
objectbucket.io/v1alpha1
policy/v1beta1
rabbitmq.com/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
replication.storage.openshift.io/v1alpha1
rook.io/v1alpha2
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

`replication.storage.openshift.io/v1alpha1` comes from our rook-ceph storage deployment, I think this file https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml

Seems like the check for OpenShift needs to be made more specific or a special case added for if only this one api type is found. My python skills are not really up to a pull request for either of those :(

**Comment by betterphp** [comment]
Workaround that works for our devs

```
kubectl delete -f https://raw.githubusercontent.com/rook/rook/release-1.6/cluster/examples/kubernetes/ceph/crds.yaml
```
Maybe do `common.yaml` and `operator.yaml` too

Obviously that won't help if you need to use rook locally.

**Comment by cindymullins-dw** [comment]
V1 is no longer supported. The latest release of Telepresence is available [here](https://www.getambassador.io/docs/telepresence/latest/install).
