### ISSUE TITLE
[v2] Intercepts not resilient to pod restarts

### ISSUE THREAD

**Issue by donnyyung** [telepresenceio/telepresence#1698]
When a service is intercepted, if pod(s) of the intercepted service are killed or restarted, telepresence list will still say the intercept is active, but traffic to the new pod actually goes to the pod instead of to the intercept on the local machine.  However, the intercept isn't completely dead bc if you have have **n** pods in your intercepted service and only one is killed, traffic goes to the pod ~1/n% of the time and the intercepted service the rest of the time.

To simply reproduce this, apply `k8s/echo-easy.yaml` to the cluster and then intercept echo-easy.  
```
$ curl echo-easy
< output comes from intercepted service >

$ kubectl delete pods echo-easy-<hash>
pod "echo-easy-<hash>" deleted

$ curl echo-easy
Request served by echo-easy-<hash>

HTTP/1.1 GET /

Host: echo-easy
User-Agent: curl/7.64.1
Accept: */*


$ telepresence list
echo-easy: intercepted
    Intercept name: echo-easy
    State         : ACTIVE
    Workload kind : Deployment
    Destination   : 127.0.0.1:3000
    Intercepting  : all TCP connections

**Comment by efunk** [comment]
Resolved in Telepresence 2.3.3
