### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by samthehai** [telepresenceio/telepresence#1703]
### What were you trying to do?

telepresence-swap-local: ## [TELEPRESENCE] Replace the existing deployment with the Telepresence proxy for local process. Example: `make telepresence-swap-local BIN=user PORT=3000 DEPLOYMENT=***`
	go build -o cmd/$(BIN)/$(BIN) cmd/$(BIN)/main.go
	telepresence \
	--namespace lengames \
	--swap-deployment $(DEPLOYMENT) \
	--expose 3000 \
	--run ./cmd/$(BIN)/$(BIN) \
	--port=$(PORT) \
	--method vpn-tcp

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'lengames', '--swap-deployment', 'lengames-user', '--expose', '3000', '--run', './cmd/user/user', '--port=3000', '--method', 'vpn-tcp']`
Version: `0.109`
Python version: `3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.20.1 // Server Version: v1.19.7`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Hais-MacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
53] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-59.a.sanity.check.telepresence.io")'
  91.0 TEL | [153] exit 1 in 0.18 secs.
  91.1 TEL | Wait for vpn-tcp connection: hellotelepresence-60
  91.1 TEL | [154] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-60")'
  91.3 TEL | [154] exit 1 in 0.18 secs.
  91.3 TEL | [155] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-60.a.sanity.check.telepresence.io")'
  91.4 TEL | [155] exit 1 in 0.18 secs.
  91.5 TEL | Wait for vpn-tcp connection: hellotelepresence-61
  91.5 TEL | [156] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-61")'
  91.7 TEL | [156] exit 1 in 0.17 secs.
  91.7 TEL | [157] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-61.a.sanity.check.telepresence.io")'
  91.9 TEL | [157] exit 1 in 0.23 secs.
  92.3 TEL | [158] Running: sudo -n echo -n
  92.3 TEL | [158] ran in 0.06 secs.

```

**Comment by cindymullins-dw** [comment]
V1 is no longer supported. The latest release of Telepresence is available [here](https://www.getambassador.io/docs/telepresence/latest/install).
