### ISSUE TITLE
[parity] Add functionality similar to TP1's --to-pod flag.

### ISSUE THREAD

**Issue by thallgren** [telepresenceio/telepresence#1708]
TP1 has a `--to-pod <port>` option that maps a specific port on `localhost` to an intercepted pod. This is useful when intercepting a container that communicates with other containers in the same pod using fixed `localhost` port numbers. Similarly, a `--from-pod <port>` will map all calls to `localhost` on that port number in the pod to the client.

A `--to-pod <port>` is simple to achieve (telepresence would just listen to that port and forward it).

Implementing`--from-pod` is not possible without a complete shutdown of the intercepted container currently listening on that port.

**Comment by efunk** [comment]
Released in Telepresence 2.3.3.
