### ISSUE TITLE
[v2]k3s traffic-manager failed

### ISSUE THREAD

**Issue by liuquanhao** [telepresenceio/telepresence#1715]
https://gist.github.com/liuquanhao/e9fc75342de994884521e4776e6eb8f8

**Comment by thallgren** [comment]
This seems very similar to #1710 that your reported before. The traffic-manager isn't allowed to connect to anything and you get lots of errors related to traefik. Can you please provide some info of your setup? How can we reproduce this?

**Comment by liuquanhao** [comment]
> This seems very similar to #1710 that your reported before. The traffic-manager isn't allowed to connect to anything and you get lots of errors related to traefik. Can you please provide some info of your setup? How can we reproduce this?

Here.
https://gist.github.com/liuquanhao/9320072eee11185c4554fbe1f4acbb32

**Comment by thallgren** [comment]
How do you install `helm` and `traefik`? A plain `get.k3s.io` install just gets me this:
```
vagrant@ubuntu-focal:~$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   coredns-854c77959c-pbllg                  0/1     Pending   0          0s
kube-system   local-path-provisioner-5ff76fc89d-46b2h   0/1     Pending   0          0s
kube-system   metrics-server-86cbb8457f-nbdjg           0/1     Pending   0          0s
```

**Comment by thallgren** [comment]
Thanks. I'm able to reproduce the problem. Will continue and investigate.

**Comment by thallgren** [comment]
This is related to how we configure `iptables` on Linux. From the looks of it, our configuration somehow clashes with k3s so that k3s attempts to use our routing rules to connect to things in the cluster. The problem goes away when using a TUN-device to do the routing (hence the dependency on #1653).

**Comment by thallgren** [comment]
Actually, I misspoke. The problem does not go away when using the TUN-device. I don't think Telepresence can be used this way, on the same host as the CNI for the pods. For now, I'd recommend running k3s as a docker container instead of installing it directly on the same host.
