### ISSUE TITLE
Handle lingering sockets better.

### ISSUE THREAD

**Issue by thallgren** [telepresenceio/telepresence#1723]
This error message pops up from time to time when attempting to connect:
```
Launching Telepresence Daemon v2.2.1 (api v3)
Telepresence Daemon quitting...done
telepresence: error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/telepresence-connector.socket: connect: connection refused"
```
It is caused by ungraceful termination of the user daemon process which leaves a lingering socket with no listener. This should be handled more gracefully. If no connector is listening, the socket should be removed and the connector restarted.

**Comment by chrisvfabio** [comment]
Just adding to this, seems to only affect WSL for my team. The current workaround suggested by @thallgren is running the following command: 

```bash
rm /tmp/telepresence-connector.socket
```

**Comment by leoll2** [comment]
Any update on this? I observe sporadically failing sockets causing telepresence to stop working until it's fully restarted.

**Comment by cindymullins-dw** [comment]
Closing as the issue has been resolved.
