### ISSUE TITLE
Cannot run --method inject-tcp in macos bigsur

### ISSUE THREAD

**Issue by mkmik** [telepresenceio/telepresence#1724]
### What were you trying to do?

```
telepresence --method inject-tcp
```

### What did you expect to happen?

it to work

### What happened instead?

it failed, see automatically included information below

### Extra info

I ran `brew install torsocks` because it a previous run of telepresence told me that that was a dependency.

With `--method vpn-tcp` it works, but I was trying to use `inject-tcp` in the hope it would let me connect to kafka
(since kafka tooling tries to access fully qualified domain names like 

```
2021/05/12 11:10:24 dial tcp: lookup kafka-1.kafka-svc.myns.svc.mycluster.a.mydomain.net: no such host
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'inject-tcp']`
Version: `0.109`
Python version: `3.9.5 (default, May  4 2021, 03:36:27) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.20.4 // Server Version: v1.16.15`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin MacBook-Pro.localdomain 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  36.3 TEL | [105] exit -11 in 0.07 secs.
  36.4 TEL | [106] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  36.4 TEL | [106] exit -11 in 0.07 secs.
  36.5 TEL | [107] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  36.6 TEL | [107] exit -11 in 0.06 secs.
  36.7 TEL | [108] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  36.8 TEL | [108] exit -11 in 0.07 secs.
  36.9 TEL | [109] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  36.9 TEL | [109] exit -11 in 0.06 secs.
  37.0 TEL | [110] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  37.1 TEL | [110] exit -11 in 0.07 secs.
  37.1 TEL | END SPAN local.py:42(set_up_torsocks)   14.9s

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
