### ISSUE TITLE
 Background process keeps exiting with return code 255

### ISSUE THREAD

**Issue by pavanfhw** [telepresenceio/telepresence#1727]
Running this command:
`telepresence --verbose --namespace <namespace>  --swap-deployment <deployment> --expose 80   --run npm start`

The process go up and I can access the telepresence deployment fine. But after a small period (seconds, minutes) I always get:
```
T: Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
T:   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -vv -p 40475 telepresence@127.0.0.1 -L127.0.0.1:40785:127.0.0.1:9050 -R9055:127.0.0.1:33039

T: Recent output was:
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   debug1: client_input_channel_req: channel 2 rtype keepalive@openssh.com reply 1
T:   Timeout, server not responding.


T: Proxy to Kubernetes exited. This is typically due to a lost connection.

T: Exit cleanup in progress
T: Cleaning up Pod
```

I'm running telepresence from inside a docker container.
My internet connection is stable, it does not make sense to be always loosing the connection as the logs says.

This is the [telepresence.log](https://gist.github.com/pavanfhw/eb77f047fc4496d8b93f45b3ea96647e) from this run, if it helps

**Comment by donnyyung** [comment]
Hey there, I see that you are using our legacy Telepresence, have you had a change to give our newer version a shot? https://www.getambassador.io/docs/telepresence/latest/quick-start/ There's also a link to installation on that page!

**Comment by cindymullins-dw** [comment]
V1 (legacy Telepresence) has been deprecated. You can try the latest version at our [QuickStart here](https://www.getambassador.io/docs/telepresence/latest/quick-start).
