### ISSUE TITLE
[v2] --docker-run should exit when intercept name is already in use

### ISSUE THREAD

**Issue by peteroneilljr** [telepresenceio/telepresence#1728]
Problem: If an intercept name is already in use and you start an intercept with --docker-run for the same service, telepresence still tries to start the container and then the terminal becomes unresponsive.

To reproduce open 2 terminals:

Terminal 1 normal intercept: `telepresence intercept dataprocessingservice --port=3000`
Terminal 2 --docker run: `telepresence intercept dataprocessingservice --port 3000 --docker-run -- --rm data:orange`

Output: the container is created in the second terminal but doesn't run, causing the terminal window to stop responding.

<img width="762" alt="Screen Shot 2021-05-13 at 9 54 17" src="https://user-images.githubusercontent.com/33669114/118143646-34c82200-b3d1-11eb-94ed-f4b02c5fbe76.png">

**Comment by thallgren** [comment]
This is no longer the case.
