### ISSUE TITLE
Telepresence is crashing when trying to connect to cluster.

### ISSUE THREAD

**Issue by omkarmahadar** [telepresenceio/telepresence#1731]
### What were you trying to do?

Trying to connect to cluster via IDEs as I usually do.

### What did you expect to happen?

The connection is successfully made to cluster via IDEs. This has always happened without any issues. This is the first time it is giving such problems. 

### What happened instead?

The process stopped and threw the respective errors after the below message-

"T: Starting network proxy to cluster using new Pod telepresence-1621098549-9038951-9846"

Then it did an exit cleanup of the pod.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.108`
Python version: `3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.21.0 // Server Version: v1.15.12`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin CAP-LAP-556.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 135, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 140, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2021-05-15T17:09:15Z', 'message': "0/2 nodes are available: 1 Insufficient cpu, 1 node(s) had taints that the pod didn't tolerate.", 'reason': 'Unschedulable', 'status': 'False', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'Burstable'}

```

Logs:

```
1-9846 -o json
 184.6 TEL | [354] captured in 0.09 secs.
 184.8 TEL | [355] Capturing: kubectl --context kind-cc-local --namespace default get pod telepresence-1621098549-9038951-9846 -o json
 184.9 TEL | [355] captured in 0.09 secs.
 185.1 TEL | [356] Capturing: kubectl --context kind-cc-local --namespace default get pod telepresence-1621098549-9038951-9846 -o json
 185.2 TEL | [356] captured in 0.10 secs.
 185.5 TEL | [357] Capturing: kubectl --context kind-cc-local --namespace default get pod telepresence-1621098549-9038951-9846 -o json
 185.6 TEL | [357] captured in 0.09 secs.
 185.8 TEL | [358] Capturing: kubectl --context kind-cc-local --namespace default get pod telepresence-1621098549-9038951-9846 -o json
 185.9 TEL | [358] captured in 0.09 secs.
 186.2 TEL | [359] Capturing: kubectl --context kind-cc-local --namespace default get pod telepresence-1621098549-9038951-9846 -o json
 186.3 TEL | [359] captured in 0.09 secs.
 186.3 TEL | END SPAN remote.py:109(wait_for_pod)
  180.2s

```

My telepresence version is - 0.108
Terraform version is - 0.15.3
Helm version is - v3.5

![image](https://user-images.githubusercontent.com/47652825/118372792-e6817180-b5d0-11eb-9439-d160fd326d55.png)
![image](https://user-images.githubusercontent.com/47652825/118372806-f39e6080-b5d0-11eb-96f2-e568cef35fbf.png)

**Comment by donnyyung** [comment]
Hey there, have you been able to try our latest version of Telepresence (https://www.getambassador.io/docs/telepresence/latest/quick-start/). The version you are currently using is our legacy version and we've since put a lot of work into our new one and that's where most of our future efforts are going!

**Comment by cindymullins-dw** [comment]
V1 (legacy Telepresence) has been deprecated.  You can try the latest version at our [QuickStart here](https://www.getambassador.io/docs/telepresence/latest/quick-start).
