### ISSUE TITLE
[v2] Telepresence 2 problem when intercepting pod using Kiam

### ISSUE THREAD

**Issue by jhalleeupgrade** [telepresenceio/telepresence#1734]
Requesting support for using Telepresence 2 with a Kubernetes cluster using Kiam (or similar).

Since Kiam validates auth based on source IP of the pod, authentication with aws fails in intercepted pods (authentication based on ec2 instance metadata).
Adding a traffic-manager role in Kiam's configuration would not work since we need fine-grained access on a "per-service" basis.

Thank you for the help,

Jean-Lou

**Comment by cindymullins-dw** [comment]
We do have a working solution for IRSA.  But kiam is deprecated so will not be supported.
