### ISSUE TITLE
[v1] --expose LOCAL:REMOTE is ignored if LOCAL matches default (k8s) remote port

### ISSUE THREAD

**Issue by mildmojo** [telepresenceio/telepresence#1736]
## Expected

- If I have a remote kubernetes deployment whose pod listens on port 8000
- And I run telepresence: `telepresence --expose 8000:9001 --swap-deployment my-service ...`
- Telepresence [should forward](https://www.telepresence.io/reference/proxying.html) remote port 9001 to local port 8000

## Actual

Telepresence ignores the `--expose` option and forwards remote port 8000 to local port 8000:

```
T: Starting network proxy to cluster by swapping out Deployment xometry-app-apiv2 with a proxy Pod
T: Forwarding remote port 8000 to local port 8000.
```

## Workaround

You may be able to modify your local service to use a port that matches the remote port you want to use, then add `--from-port <REMOTE_PORT>` to map that port from the cluster to your PC:

```
$ telepresence --from-pod 9001 --swap-deployment my-service ...
...
T: Forwarding remote port 8000 to local port 8000.
T: Forwarding localhost:9001 from the pod
```

This isn't great because you have to modify your local service configuration. It may only be working for me because:

- My pod listens on port 8000
- Inside the pod, the container on port 8000 is a sidecar proxy...
- ...to a second container hosting my app, listening on port 9001
- When telepresence swaps the app container, the default (incorrect) 8000:8000 port forward is a no-op since the original container wasn't listening on 8000 anyway

## Solution

`--expose` should override any automatic port detection. If an automatically-detected port appears in either the local or remote part of an `--expose` argument, it should take precedence over the automatic behavior.

It looks like the bug is in [PortMapping#merge_automatic_ports](https://github.com/telepresenceio/telepresence/blob/master/telepresence/cli.py#L47), with a test [here](https://github.com/telepresenceio/telepresence/blob/master/tests/local/test_unit.py#L292) that shows it's a design flaw.

**Comment by donnyyung** [comment]
Hey there, I see that you are using the legacy version of Telepresence. Have you been able to try our newer version of Telepresence (https://www.getambassador.io/docs/telepresence/latest/quick-start/), it supports --port LOCAL:REMOTE as well.

**Comment by mildmojo** [comment]
I have existing tooling built on top of v1, and I do plan to check out v2 but haven't been able to find the time yet. I understand if dev resources are going to v2 right now.

**Comment by thallgren** [comment]
@mildmojo In the latest 2.2.2 version of Telepresence, we provide a legacy mode that makes it possible to use commonly used commands from v1. Not sure if that makes it compatible enough for your tooling, but it could be worth looking at.

**Comment by cindymullins-dw** [comment]
The expose flag was in Version1 which is now deprecated.  The `--from-pod` flag is available in newer versions.
