### ISSUE TITLE
[v2] Telepresence support automountServiceAccountToken feature

### ISSUE THREAD

**Issue by msenmurugan** [telepresenceio/telepresence#1737]
**Feature description:**

Every pod that will run in Kubernetes cluster will be associated with the service account. If the service account is not specified, then default service account will be used. 

Service account will automatically mounted to the pod at _/var/run/secrets/kubernetes.io/token_. This feature can be disabled via automountServiceAccountToken: false. By default, it is true.

As part of our application, we are using Vault. Kubernetes auth method will be used to talk with Vault. For Kubernetes auth method, the Vault will use Kubernetes tokenReview API to validate the service account token. 

When we run the service locally, there are issues with talking with Vault because the Kubernetes service account token is missing in _/var/run/secrets/kubernetes.io/token_

**Workaround:**
To overcome this issue, manually copying the service account from the pod and storing it in a file and then added as volume mount to Docker container in my local. 

_-v /tmp/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount_

**Comment by thallgren** [comment]
So, are you saying that this folder isn't automatically mounted when you do an intercept? It is for me:
```
$ telepresence intercept echo -p 9000    
Using Deployment echo
intercepted
    Intercept name    : echo
    State             : ACTIVE
    Workload kind     : Deployment
    Destination       : 127.0.0.1:9000
    Volume Mount Point: /tmp/telfs-567116033
    Intercepting      : all TCP connections
$ ls /tmp/telfs-567116033/var/run/secrets/kubernetes.io/serviceaccount   
ca.crt  namespace  token
```

**Comment by msenmurugan** [comment]
Hi @thallgren 

Thanks for your verification. For some reason, Volume mount is not working for my intercepted service. Is there any specific command/flag should I need to add to intercept in order to get the existing volume mounts for the remote service to my local.

**Comment by thallgren** [comment]
Volume mounts are enabled by default (you can disable them using `--mount=false`) and should work if you have `sshfs` installed. On a Mac, you'll also need macFUSE of version >= 4.0.5. The intercept or list command should tell you why you don't get your volumes mounted.

**Comment by fentas** [comment]
Having the same issue. (working right now with `wsl2`). telepresence notified me that sshfs was not present I installed it but folder are still empty.

```
# envs from local docker container
TELEPRESENCE_MOUNTS='/var/run/secrets/kubernetes.io'
TELEPRESENCE_ROOT='/tmp/telfs-2575426184'
```

interestingly telepresence recognizes the kubernetes.io folder but nowhere to be fond (`/tmp/telfs..` is empty, `/var/run/secrets` is empty)

**Comment by fentas** [comment]
ok. after some issue digging (lots of `mount` issues) I found the relevant for me
https://github.com/telepresenceio/telepresence/issues/2169#issuecomment-1006087683

This fixed it -- would be nice if telepresence would expose this error (as it is already captured)
