### ISSUE TITLE
[v2] Telepresence list is too slow

### ISSUE THREAD

**Issue by mausch** [telepresenceio/telepresence#1739]
I have a namespace `xx` with 41 deployments.
When I run `telepresence list -n xx` it takes 80 seconds to respond.

When I run it against my `default` namespace (8 deployments) it takes 3 seconds.

```
$ telepresence version
Client v2.2.1 (api v3)
Daemon v2.2.1 (api v3)
```

**Comment by thallgren** [comment]
Fixed in 2.3.7
