### ISSUE TITLE
Swaping deployment with local image failed on "SSH to cluster failed to start"

### ISSUE THREAD

**Issue by isitinme** [telepresenceio/telepresence#1742]
### What were you trying to do?

Swap deployment into the cluster with local image

### What did you expect to happen?

Successful substitution

### What happened instead?

Python exception has been thrown

### Automatically included information

Command line: `[
  '/usr/local/bin/telepresence',
  '--swap-deployment',
  'galaxy',
  '--namespace',
  'ABC',
  '--docker-run',
  '--rm',
  '-it',
  '-v',
  '/Users/user/ABC/app:/usr/src/app',
  'galaxy',
  '/bin/sh'
]`
Version: `0.109`
Python version: `3.9.2 (default, Feb 24 2021, 13:30:36) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.19.7 // Server Version: v1.19.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin alexanders-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
l  Pulled     41s   kubelet            Container image "docker.artifactory.sisense.com/busybox:1.30.1" already present on machine
  63.5  40 |   Normal  Created    41s   kubelet            Created container init-configuration
  63.5  40 |   Normal  Started    41s   kubelet            Started container init-configuration
  63.5  40 |   Normal  Pulled     40s   kubelet            Container image "docker.artifactory.sisense.com/busybox:1.30.1" already present on machine
  63.5  40 |   Normal  Created    40s   kubelet            Created container check-activation
  63.5  40 |   Normal  Started    39s   kubelet            Started container check-activation
  63.5  40 |   Normal  Pulled     39s   kubelet            Container image "datawire/telepresence-k8s:0.109" already present on machine
  63.5  40 |   Normal  Created    39s   kubelet            Created container galaxy
  63.5  40 |   Normal  Started    38s   kubelet            Started container galaxy
  63.5 TEL | [40] ran in 4.23 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
