### ISSUE TITLE
SSHFS additional arg / option

### ISSUE THREAD

**Issue by gnanderson** [telepresenceio/telepresence#1745]
In my setup (Ubuntu 20.04 + latest patches)

I am unable to use `telepresence intercept [...] --docker-run [...]` - I receive a notification from the docker daemon that the operation has been denied with reason "file exists".

After reviewing some material around SSHFS the following patch to the SSHFS opts allows the `--docker-run` arg to be successful.

    diff --git a/pkg/client/connector/intercept.go b/pkg/client/connector/intercept.go
    index 4445edd9..d9c149fc 100644
    --- a/pkg/client/connector/intercept.go
    +++ b/pkg/client/connector/intercept.go
    @@ -466,6 +466,7 @@ func (tm *trafficManager) workerMountForwardIntercept(ctx context.Context, mf mo
                                    "-p", localPort,                  // port to connect to
                                    // mount directives
    +                               "-o", "allow_other",
                                    "-o", "follow_symlinks",
                                    "telepresence@localhost:" + telAppMountPoint, // remote user and what to mount
                                    mountPoint, // where to mount it
                                    
Since the local tele daemon asks for elevated permissions I'm mildly surprised this option was required to succeed - though I should mention my user is in the docker system group.

I'm not necessarily proposing this as a fix - I'm personally unclear on what issues passing that opt to SSHFS might raise.

**Comment by gnanderson** [comment]
I missed this system conf change I applied , which may complicate things:

    # /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

    # Set the maximum number of FUSE mounts allowed to non-root users.
    # The default is 1000.
    #mount_max = 1000

    # Allow non-root users to specify the allow_other or allow_root mount options.
    user_allow_other

**Comment by gnanderson** [comment]
I guess it's a little unclear for me without being familiar with FUSE internals but this would seem to be overly permissive? (in terms of applying those options). 

If I set `user_allow_other` at the system level to allow the `-o allow_other` option, it would appear to allow user(me) access to something they already have.

So that leads me back to why I need `-o allow_other` - if I want to mount the remote SSFS as my local user (through the local tele daemon) does that also trigger the user domain crossover denial from user to root (docker running under root)?

**Comment by thallgren** [comment]
I discovered this a couple of days ago and created PR #1744. So a fix is underway.

**Comment by khussey** [comment]
This is fixed in the 2.3.0 release, which is now available.
