### ISSUE TITLE
Install traffic-manager in selected namespace [v2]

### ISSUE THREAD

**Issue by nadilas** [telepresenceio/telepresence#1751]
Based on the thread: https://datawire-oss.slack.com/archives/CAUBBJSQZ/p1621976587109400

> Ah okay I see, currently we only support the traffic-manager running in the ambassador namespace .  In the meantime, we do have a section on rbac in case your cluster administrator wants to help you out (https://www.getambassador.io/docs/telepresence/latest/reference/rbac/).

> If talking to the cluster administrator for rbac changes isn’t feasible and/or you want to open an issue in github for supporting selecting the namespace where the traffic-manager is installed, you may also do that!

In our clusters we can't have cluster wide roles, so in order to use Telepresence I need to be able to install traffic-manager in a specific namespace and not default to `ambassador`

**Comment by trendsoa** [comment]
same request here, we can not create clusterRole

**Comment by thallgren** [comment]
As a workaround, try setting the environment variable TELEPRESENCE_MANAGER_NAMESPACE=xxx prior to installing the traffic-manager and agents. The env is primarily for testing and I don't think it's well documented. The proper way to do this ought to be a cluster specific configuration setting.

**Comment by efunk** [comment]
Released with Telepresence 2.3.3

**Comment by nadilas** [comment]
@efunk where can I find the documentation on the final implementation and it’s usage?

**Comment by efunk** [comment]
@nadilas apologies for taking so long to reply. You can find the latest release notes here: https://www.getambassador.io/docs/telepresence/latest/release-notes/
Scroll down to 2.3.3 and you will see "Feature: Traffic-manager in custom namespace"

Please let us know if you encounter any issues!
