### ISSUE TITLE
[v2] daemon shutdown is racy

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1752]
I'd have sworn that there was a ticket that came out of this conversation with @esmet, but I can't find it, so I'm creating it now:

[Apr 7th at 13:48](https://datawire.slack.com/archives/C019LLD99K7/p1617824917382800):
> @esmet:
> > after running `telepresence quit`, how long should one expect before the side effects of telepresence are gone? is anything cleaned up asynchronously?
> 
> @LukeShu:
> > I'd have to check if it's async, but a few seconds should be plenty.
> >
> > I know the connection to the cluster is cleaned up async, but idk about the root daemon that does all the actual side effects stuff.
> >
> > OK, so the daemon shuts down async
> >
> > but the cli waits for the socket to go away
> >
> > darn, it looks like the daemon cleans up the socket once the gRPC server quits, which is probably pretty quick; before all of the cleanup has happened.  But that shouldn't be much work to change it to make it block
> 
> @esmet:
> > gotcha. I had a 2 second sleep but I will try a 10 second sleep.
> 
> @LukeShu:
> > :disappointed: I'm sorry
> 
> @esmet:
> > I'm hoping this is the reason `test_scout` is behaving weirdly sometimes, anyway :smile:

**Comment by efunk** [comment]
Resolved in Telepresence 2.3.2 GA
