### ISSUE TITLE
[v2] How to resolve + route connections to external service when connected to cluster

### ISSUE THREAD

**Issue by ig0rsky** [telepresenceio/telepresence#1755]
In the docs, it says that the as soon as you connect to a cluster, you can reach the services living in the cluster.
However, I'm unable to reach an external service living outside the k8s cluster I'm connected to, but inside the same network, so there's connectivity. I can test this connectivity by execing into one of the pods and sending an HTTP request with curl. Is there a reason why this is not doable when proxying?  Keep in mind that this external service is inaccessible from my laptop; hence I'm proxying.

**Comment by efunk** [comment]
Delivered in the Telepresence 2.3.1 GA release.

**Comment by ig0rsky** [comment]
@efunk Thanks!
