### ISSUE TITLE
Explicitly allow telepresence to not use cloud login

### ISSUE THREAD

**Issue by hudelgado** [telepresenceio/telepresence#1781]
Hello, Is it possible to use custom intercepts without login to the embassador cloud?

The current v2 of telepresence allows to be configured in a airgap cluster but this logic only runs if the cluster determines it cannot reach the ambassador cloud.

Is it possible to add a way to explicitly tell telepresence to not use internet?

Thanks

**Comment by efunk** [comment]
Resolved in Telepresence 2.3.5 GA

Please see: https://www.getambassador.io/docs/telepresence/latest/reference/config/#cloud .
