### ISSUE TITLE
Newbie very confused: Is "intercepting" with telepresence supported on Windows WSL 2 (or 1)? Prefer telepresence 0.x or 2.x?

### ISSUE THREAD

**Issue by pmorch** [telepresenceio/telepresence#1787]
I've used a lot of open source projects, but as a newbie I find telepresence very confusing.

I'd like to humbly ask:

* Is "intercepting" a deployment running in k8s and replacing it with a local docker container supported/reliable with WSL2? `telepresence --swap-deployment hello-world --docker-run --rm -it myimage` seems to be working, but is documented as not being supported.
* Should I prefer using telepresence 1 (0.x) or 2 (2.x) for WSL2 (or, less desirably, WSL1) support, when interfacing with Docker for Windows?

There is a *very* confusing [Windows support](https://www.telepresence.io/reference/windows) page. It doesn't mention WSL1 vs WSL2 at all, but it does say:

>    Only the inject-tcp method is supported.

This seems to indicate that `--method container` as used by `--docker-run` is documented to be not supported on Windows. Is that correct? I got it to work, but if there is some good reason why it isn't supported, we'd like to know because then we won't use it.

-------------------------

The rest of that [Windows support](https://www.telepresence.io/reference/windows) is also confusing and looks like it needs an update:

> To run Telepresence inside WSL:
>
>   Install Windows Subsystem for Linux.
>   Start the BASH.exe program.
>   Install Telepresence by following the Ubuntu instructions above.

* I've installed both WSL1 and WSL2 ages ago.
* There is no `BASH.exe` program in WSL1 or WSL2. Does the page mean `/bin/bash`?
* There are no Ubuntu instructions "above" that sentence. There are installation instructions [elsewhere](https://www.telepresence.io/reference/install), that I've followed. I got `telepresence` installed fine.

> Caveats:
>    At the moment volumes are not supported on Windows, but [we plan on fixing this](https://github.com/telepresenceio/telepresence/issues/115).

The [we plan on fixing this](https://github.com/telepresenceio/telepresence/issues/115) issue, #115, seems to have been fixed by #1079.

>    Network proxying won't affect Windows binaries. You can however edit your files in a Windows program (and compile Java or .NET packages), and then run them with the Linux interpreters or VMs.

Windows binaries? What does the second sentence even mean in a WSL context?

**Comment by cindymullins-dw** [comment]
We've made a lot of improvements to Telepresence and Windows is now supported.  You can download the latest Windows compatible version [here](https://www.getambassador.io/docs/telepresence/latest/install).
