### ISSUE TITLE
[v2] telepresence uninstall --everything Does nothing

### ISSUE THREAD

**Issue by nnqq** [telepresenceio/telepresence#1790]
Hi

When i run (telepresence2)

```
telepresence uninstall --everything
```

Namespace `ambassador` and it pods was not deleted

**Comment by thallgren** [comment]
The `ambassador` namespace is not supposed to be deleted. It may contain resources that are related to ambassador but not to telepresence. But the `traffic-manager` service, deployment, and pod should be removed. If they aren't, then it's likely that there's some clue to why it didn't happen in the `connector.log` file.

**Comment by nnqq** [comment]
@thallgren ok, thank you. Is there a method to cleanup all things telepresence2 created on first start (namespace, maybe RBAC, etc) ?

**Comment by thallgren** [comment]
The `telepresence uninstall --everything` is that method. But we cannot know if `telepresence` actually created the namespace.
