### ISSUE TITLE
Traffic Agent injector doesn't support multiple ports

### ISSUE THREAD

**Issue by maxlegault** [telepresenceio/telepresence#1796]
I have a service that exposes multiple ports and I'm trying to intercept it in combination with the new mutating webhook that automatically injects the traffic agent as a sidecar. It was working previously because the name of the port was specified when I executed the `telepresence intercept`, but it doesn't work anymore with the webhook because the port name resolution seems to be required during the injection, which happens before the `intercept` command gets executed.

Here's the error I'm seeing in the traffic manager logs:
```
time="2021-06-16 19:15:41.1220" level=error msg="found matching Service with multiple matching ports.\nPlease specify the Service port you want to intercept by passing the --port=local:svcPortName flag." func=github.com/telepresenceio/telepresence/v2/cmd/traffic/cmd/manager/internal/mutator.agentInjector file="github.com/telepresenceio/telepresence/v2/cmd/traffic/cmd/manager/internal/mutator/agent_injector.go:89" THREAD=/agent-injector
```

My pod gets created with only one container.

**Comment by efunk** [comment]
Resolved in Telepresence 2.3.2 GA
