### ISSUE TITLE
[v2] fail to accessed my remote Kubernetes API server even if connect to cluster via telepresence

### ISSUE THREAD

**Issue by zoechou** [telepresenceio/telepresence#1800]
I have use `telepresence connect` to connect to my remote kubernetes cluster,
my status is as below

```
Root Daemon: Running
  Version     : v2.3.1 (api 3)
  DNS : ""
User Daemon: Running
  Version           : v2.3.1 (api 3)
  Ambassador Cloud  : Logged out
  Status            : Connected
  Kubernetes server : https://＊＊＊＊＊
  Kubernetes context: default
  Telepresence proxy: ON (networking to the cluster is enabled)
  Intercepts        : 0 total
```

but when i try apiServer

curl -ik https://kubernetes.default

i still receive "curl: (7) Failed to connect to kubernetes.default port 443: Operation timed out" error

**Comment by LukeShu** [comment]
Does the IP of `kubernetes.default` resolve correctly (compare `getent hosts kubernetes.default` (GNU/Linux) or `dscacheutil -q host -a name kubernetes.default` (macOS) match the IP in `kubectl get services`?)

And what's your routing table look like? (`route -n` on GNU/Linux, `netstat -rn` on macOS)

**Comment by zoechou** [comment]
hi,
after checking ip address

`
kubectl get services kubernetes -n default
`
|  NAME |   TYPE|  CLUSTER-IP |   EXTERNAL-IP|   PORT(S)|
|---|---|---|---|---|
|  kubernetes | ClusterIP  |   172.20.0.1 |  <none>  |  443/TCP |


`dscacheutil -q host -a name kubernetes.default`

|  NAME |   ip_address| 
|---|---|
|  kubernetes.default | 172.20.0.1  |




and after connecting, i found my `ifconfig` had attach nif
```
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
inet 172.20.0.0 --> 172.20.0.1 netmask 0xffff0000
inet 10.0.0.0 --> 10.0.0.1 netmask 0xfffff800
inet 172.32.0.0 --> 172.32.0.1 netmask 0xffff8000
```

but when inspecting `netstat -rn`, not route attach on utun2 nif

**Comment by zoechou** [comment]
is it possible to use telepresence when needs to access kubernetes under VPN connection?

I've try to connect to local kubernetes with docker-desktop and perform intercepting without VPN connection, it works fine.
However, if i want to connect to remote kubernetes server on AWS EKS, which needs to access over `anyconnect VPN`,
i can perform `telepresence connect`, but none of the dns records are working.

Due to COVID-19, most of us need to access resources over VPN connection,
please help inspect this issue, thx

**Comment by cindymullins-dw** [comment]
You can now use the [test-vpn command ](https://www.getambassador.io/docs/telepresence/latest/reference/vpn#the-test-vpn-command)to check if your VPN is compatible with Telepresence.
