### ISSUE TITLE
How to add resources for traffic-agent to allow running in namespace with resource quotas

### ISSUE THREAD

**Issue by hmoravec** [telepresenceio/telepresence#1806]
Traffic agent container which is injected by telepresence to deployment for intercepted service does not specify resources so it is not possible to use it in namespace with resource quotas set where specifying resources is mandatory. 

Is it possible to set the resources for traffic agent container?

**Comment by LukeShu** [comment]
Something coming soon is the ability to install via a Helm chart in order to have more control over the install.  This would be a very good thing for us to include in that.

**Comment by aldycool** [comment]
Hi, is this feature already configurable in the Helm chart?

**Comment by cindymullins-dw** [comment]
If your cluster requires you to set resource limits, this is now available by setting `[agent.resources](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config#resources)`
