### ISSUE TITLE
issue connecting to remote cluster

### ISSUE THREAD

**Issue by gaughen** [telepresenceio/telepresence#1808]
Trying to 'telepresence connect' to my remote cluster and I get the following error:

`% telepresence connect`
`Launching Telepresence Daemon v2.3.2 (api v3)`
`telepresence: error: daemon service did not start (see /Users/patgaughen/Library/Logs/telepresence/daemon.log for more info)`
`% tail /Users/patgaughen/Library/Logs/telepresence/daemon.log`
`2021/06/21 16:42:57.3218 info     : No config found. Using default (from pkg/client/config.go:373)`
`telepresence: error: resource busy`

I'm using telepresence v2.3.2 (api v3) on a mac (running MacOS Catalina 10.15.7) and openvpn connect v3.2.5, let me know if you need any additional system info or if there's something I can do to give more useful debug output.

I did see that someone reported this issue - https://github.com/telepresenceio/telepresence/issues/1760 - which made me wonder if it was my VPN client so I turn off my VPN and I was able to connect to the cluster.  I am not sure if it's the same issue, so I'm filing this one.

**Comment by LukeShu** [comment]
That's all `daemon.log` says?  Are there other `daemon-{timestamp}.log` files that have more info?

Yeah, this is separate from #1760; telepresence v2 (and especially v2.3.0 and newer) work differently enough from v1 that we expect v2 to work with VPNs.

**Comment by gaughen** [comment]
the timestamped version of the log says the very same thing.  I'm happy to try and grab some additional info if you have any suggestions.  Let me know, will try and respond sooner this time :-)

**Comment by skataboina** [comment]
I am also facing the same issue, using telepresence version 2.3.x
I see below daemon logs during the operation
 debug   daemon/server-dns/Server : LookupHost "service1.namespace1" (from pkg/client/daemon/outbound.go:218)
 debug   daemon/server-dns/Server : QUERY[1] service1.namespace1. -> 192.168.10.27 (from pkg/client/daemon/dns/dns.go:83)
 debug   daemon/server-dns/Server : QUERY[28] service1.namespace1. -> EMPTY (from pkg/client/daemon/dns/dns.go:93)
 info    daemon/watch-cluster-info : Adding service subnet 192.168.0.0/16 (from pkg/client/daemon/tunrouter.go:248)
info    daemon/watch-cluster-info : Adding pod subnet 172.16.2.0/24 (from pkg/client/daemon/tunrouter.go:254)

**Comment by cindymullins-dw** [comment]
You can now use the [test-vpn command ](https://www.getambassador.io/docs/telepresence/latest/reference/vpn#the-test-vpn-command)to check if your VPN is compatible with Telepresence.
