### ISSUE TITLE
tswap with kubectl if failed on macOs

### ISSUE THREAD

**Issue by MatanTubul** [telepresenceio/telepresence#1813]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--context', 'development', '--expose', '80', '--mount', '/tmp/for_testing', '--swap-deployment', 'microservice-field-jobs']`
Version: `0.108`
Python version: `3.8.2 (default, Apr  8 2021, 23:19:18) 
[Clang 12.0.5 (clang-1205.0.22.9)]`
kubectl version: `Client Version: v1.20.0 // Server Version: v1.19.10-gke.1600`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Matans-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

```
Background process (SSH port forward (exposed ports)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 56551 telepresence@127.0.0.1 -R '*:3000:127.0.0.1:3000' -R '*:80:127.0.0.1:80' -R '*:9020:127.0.0.1:9020'


Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 56551 telepresence@127.0.0.1 -L127.0.0.1:56566:127.0.0.1:9050 -R9055:127.0.0.1:56567

```

Logs:

```
.168.1.19', 40648) to None: 32 bytes
  86.0  25 | c : DNS request from ('192.168.1.19', 48504) to None: 32 bytes
  86.1  25 | c : DNS request from ('192.168.1.19', 52911) to None: 38 bytes
  87.0 TEL | [21] SSH port forward (exposed ports): exit 255
  87.2  25 | c : DNS request from ('192.168.1.19', 52911) to None: 38 bytes
  87.4 TEL | [22] SSH port forward (socks and proxy poll): exit 255
  88.0 TEL | [117] timed out after 5.01 secs.
  88.0 TEL | [118] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-45.a.sanity.check.telepresence.io")'
  88.0  25 | c : DNS request from ('192.168.1.19', 37297) to None: 32 bytes
  88.0  25 | c : DNS request from ('192.168.1.19', 18486) to None: 32 bytes
  88.0  25 | c : DNS request from ('192.168.1.19', 65224) to None: 69 bytes
  89.0 TEL | [118] timed out after 1.01 secs.
  89.1  25 | c : DNS request from ('192.168.1.19', 65224) to None: 69 bytes
  89.3  25 | c : DNS request from ('192.168.1.19', 62477) to None: 38 bytes

```

**Comment by LukeShu** [comment]
Please fill in the "please tell us" fields, so we know what to make of this.

**Comment by cindymullins-dw** [comment]
Telepresence v1 is no longer supported. The latest version is available [here](https://www.getambassador.io/docs/telepresence/latest/install). Please let us know if issues persist on newer versions.
