### ISSUE TITLE
Connecting to Internal K8s API server

### ISSUE THREAD

**Issue by keithpenrod** [telepresenceio/telepresence#1819]
I have a cluster with an internal load balancer for the kubernetes API server. This means I need to be on my VPN in order to access the cluster (ie, use kubectl). Is there a way to have telepresence connect to the cluster through the VPN?

**Comment by thallgren** [comment]
Telepresence (v2) connects to the cluster using a `kubectl port-forward`. If that works when you are on your VPN, then Telepresence should work too unless your VPN somehow collides with the TUN-device that telepresence is using.

Are you seeing any specific problems when trying to use `telepresence connect`?

**Comment by thallgren** [comment]
Closing this due to lack of info.

**Comment by keithpenrod** [comment]
I've been using telepresence 0.105. I just tried 2.3.2 and after running telepresence connect, I tried to visit a site using a cluster name but it didn't seem to resolve. Does telepresence v2 allow cluster names to resolve locally, like with 0.105?
