### ISSUE TITLE
apple time out

### ISSUE THREAD

**Issue by youzeliang** [telepresenceio/telepresence#1824]
I type it in my terminal .   kubectl apply -f https://raw.githubusercontent.com/telepresenceio/telepresence/master/docs/tutorials/hello-world.yaml 

but it always show time out .

**Comment by thallgren** [comment]
I have no problem applying that manifest. Can you curl it from your mac? If so, can you do a `kubectl get pod`?

**Comment by thallgren** [comment]
Closing this due to lack of more info.
