### ISSUE TITLE
Failed with docker-desktop as k8s cluster 

### ISSUE THREAD

**Issue by tschmidt64-SC** [telepresenceio/telepresence#1830]
### What were you trying to do?

I was trying to run telepresence locally using docker-desktop as my k8s cluster

### What did you expect to happen?

I expected a pod to be created 

### What happened instead?

Not entirely sure to be honest. Seems like it failed

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '-n', 'skygrid-hub-api', '--run', 'sleep', '10000']`
Version: `0.109-16-g601cad65`
Python version: `3.9.5 (default, May  4 2021, 03:36:27) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.15.11-dispatcher // Server Version: v1.19.7`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Taylors-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
k.telepresence.io'
  57.2  22 | c : DNS request from ('192.168.200.2', 55719) to None: 38 bytes
  57.3  12 | 2021-06-29T22:20:47+0000 [stdout#info] Result for b'hellotelepresence-11' is ['127.0.0.1']
  59.2 TEL | [46] timed out after 5.01 secs.
  59.2 TEL | [47] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-11.a.sanity.check.telepresence.io")'
  59.2  22 | c : DNS request from ('192.168.200.2', 63538) to None: 69 bytes
  59.2  12 | 2021-06-29T22:20:49+0000 [stdout#info] Sanity check: b'hellotelepresence-11.a.sanity.check.telepresence.io'
  60.2 TEL | [47] timed out after 1.01 secs.
  60.2  22 | c : DNS request from ('192.168.200.2', 63538) to None: 69 bytes
  60.2  12 | 2021-06-29T22:20:50+0000 [stdout#info] Sanity check: b'hellotelepresence-11.a.sanity.check.telepresence.io'
  61.2  22 | c : DNS request from ('192.168.200.2', 55719) to None: 38 bytes
  61.3  12 | 2021-06-29T22:20:51+0000 [stdout#info] Result for b'hellotelepresence-11' is ['127.0.0.1']

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
