### ISSUE TITLE
Telepresence v1 with VPN and `inject-tcp`

### ISSUE THREAD

**Issue by elliott-king** [telepresenceio/telepresence#1847]
### What were you trying to do?

Trying to telepresence while on a VPN using `--method inject-tcp`.

### What did you expect to happen?

I expected it to connect

### What happened instead?

It did not mount successfully. I also tried with telepresence v2. No luck - but V2 failed silently.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--mount', 'false', '--method', 'inject-tcp']`
Version: `0.109`
Python version: `3.8.8 (default, Apr 20 2021, 11:38:42) 
[Clang 12.0.0 (clang-1200.0.32.28)]`
kubectl version: `Client Version: v1.19.7 // Server Version: v1.17.17-gke.4900`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Elliotts-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  22.6 TEL | [109] exit -11 in 0.05 secs.
  22.7 TEL | [110] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  22.7 TEL | [110] exit -11 in 0.05 secs.
  22.8 TEL | [111] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  22.9 TEL | [111] exit -11 in 0.05 secs.
  23.0 TEL | [112] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  23.0 TEL | [112] exit -11 in 0.06 secs.
  23.1 TEL | [113] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  23.2 TEL | [113] exit -11 in 0.05 secs.
  23.3 TEL | [114] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  23.3 TEL | [114] exit -11 in 0.05 secs.
  23.3 TEL | END SPAN local.py:42(set_up_torsocks)   15.0s

```
[telepresence.log](https://gist.github.com/elliott-king/a32576b0ffd987c381499890d9a912a5)

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
