### ISSUE TITLE
Can't join community Slack

### ISSUE THREAD

**Issue by mattrussell-sonocent** [telepresenceio/telepresence#1850]
Attempting to follow the link to the community slack given on https://www.telepresence.io/docs/latest/faqs/:

https://a8r.io/slack

Doesn't allow signups for emails outside of certain specific domains:

![image](https://user-images.githubusercontent.com/45822724/124898496-27957100-dfd7-11eb-91fc-b54d8454a16c.png)

**Comment by richarddli** [comment]
Thanks for the report! This should be fixed now.

**Comment by mattrussell-sonocent** [comment]
👍 Thanks, I was able to join.
