### ISSUE TITLE
error: Failed to establish intercept: the apply timed out.

### ISSUE THREAD

**Issue by mattrussell-sonocent** [telepresenceio/telepresence#1851]
I get an error running `telepresence intercept`:

```
$ telepresence intercept app-frontend --service app-frontend --port 3000:http --env-file telepresence.env
telepresence: error: Intercept: Failed to establish intercept: the apply timed out.  The current timeout 1m0s can be configured as "timeouts.apply" in "/Users/matt/Library/Application Support/telepresence/config.yml"
```

(I don't think the timeout length is the issue, I've tried upping it with no luck)

Is there any way to get logs or additional debugging from telepresence to understand the problem?

```
$ telepresence version
Client: v2.3.3 (api v3)
Root Daemon: v2.3.3 (api v3)
User Daemon: v2.3.3 (api v3)
```

**Comment by josecv** [comment]
@mattrussell-sonocent thanks for opening an issue.

Could you set the logging level to [debug](https://www.telepresence.io/docs/latest/reference/config/#log-levels) and upload the telepresence logs? You can find the logs in `/Users/$USER/Library/Logs` on MacOS or `/home/$USER/.cache/telepresence/logs` on Linux.
In addition, could you also add the `traffic-manager` logs? You can get them from the `traffic-manager` pod in the `ambassador` namespace in your cluster.

**Comment by mattrussell-sonocent** [comment]
@josecv thanks - here are the logs:
[connector.log](https://github.com/telepresenceio/telepresence/files/6789663/connector.log)
[daemon.log](https://github.com/telepresenceio/telepresence/files/6789664/daemon.log)
[traffic-manager.log](https://github.com/telepresenceio/telepresence/files/6789665/traffic-manager.log)

**Comment by thallgren** [comment]
I wonder why the `traffic-manager`s watch of `Nodes` is triggered over and over again at a fairly high pace.

**Comment by thallgren** [comment]
I see a tremendous amount of UDP calls to port 54915. I googled that port and found `"54915 | tcp,udp | logitech | Logitech Gaming Software - LCore.exe uses port 54915/udp. Disabling Arx control may stop the broadcasts."`. It shouldn't matter much, besides that it causes a lot of debug-level logging. It might have a negative impact on a limited network. Makes me wonder if we should recognize such broadcasts and skip them.

**Comment by thallgren** [comment]
@mattrussell-sonocent would it be possible to also check what's going on with the traffic agent? A `kubectl describe pod app-frontend-xxx` may give some hints. Sometimes a `kubectl logs app-frontend-xxx traffic-agent` is useful as well. With or without a `-p`.

**Comment by mattrussell-sonocent** [comment]
Info on the agent:
[glean-frontend-7488c77bf9-9vk9r.log.txt](https://github.com/telepresenceio/telepresence/files/6790850/glean-frontend-7488c77bf9-9vk9r.log.txt)
[glean-frontend-7488c77bf9-9vk9r.pod.txt](https://github.com/telepresenceio/telepresence/files/6790851/glean-frontend-7488c77bf9-9vk9r.pod.txt)

Is it expected the original pod remains up?

```
glean-frontend-7488c77bf9-9vk9r           1/2     Running     0          3h46m
glean-frontend-d757b9f77-zb9tj            1/1     Running     0          3h58m
```

> I see a tremendous amount of UDP calls to port 54915.

There was indeed some Logitech driver software installed, I've removed it just on the off-chance it wasn't helping.

**Comment by thallgren** [comment]
From the looks of it, the `traffic-agent` gets stuck somewhere before it creates the file that the readiness probe is looking for. A normal `traffic-agent` startup should log the message `Talking to manager v2.3.3` but it never does. In order to find out why that's happening, it would be helpful if you could turn on debug level logging for both the `traffic-manager` and `traffic-agent`.

For the `traffic-manager`, use `kubectl -n ambassador edit deploy/traffic-manager` and change the value of `spec/template/containers/-/env/name/LOG_LEVEL` from `info` to `debug`.
For the `traffic-agent`, do the same thing for the `<workload>/glean-frontend` (replace \<workload> with "deploy", "replicaset" or what's applicable).

Edit the `traffic-manager` first as the edit will cause the pods to restart. Then please convey the logs for both.

**Comment by mattrussell-sonocent** [comment]
Attached (although there's not much coming out at debug level for either):
[traffic-agent.log](https://github.com/telepresenceio/telepresence/files/6799426/traffic-agent.log)
[traffic-manager.log](https://github.com/telepresenceio/telepresence/files/6799428/traffic-manager.log)

**Comment by thallgren** [comment]
Ok, that was disappointing. Can you please try with 2.3.4 (released on Friday)? I will give at least one additional piece of information in the traffic-manager log.

**Comment by mattrussell-sonocent** [comment]
[traffic-manager-2.3.4.log](https://github.com/telepresenceio/telepresence/files/6807123/traffic-manager-2.3.4.log)

**Comment by mcmarkj** [comment]
Jumping on the back of this, I think this could be because the cluster's that Matt and I are trying to use are GKE clusters using Konnectivity instead of ssh tunnels. Is Telepresence capable of using [Konnectivity](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/#konnectivity-service)?

**Comment by thallgren** [comment]
@mcmarkj thanks for the info. I'll investigate but I don't think Telepresence cares much about if ssh tunnels or Konnectivety is used. The only connection that is made between the telepresence client and the cluster nowadays is using gRPC over a kubectl port-forward. We are not using ssh tunnels anywhere.

**Comment by thallgren** [comment]
The #1921 PR will lessen the amount of data that the `traffic-manager` sends to the client as the result of watching the `Node` subnets. It will also lessen the amount of log output that the `traffic-manager` emits.

**Comment by cindymullins-dw** [comment]
Closing as resolved.
