### ISSUE TITLE
Do not auto-update traffic manager if it is managed by Helm

### ISSUE THREAD

**Issue by sichapman** [telepresenceio/telepresence#1858]
I had a traffic manager 2.3.3 installed via Helm chart, but when I connected to it with a 2.3.4 client the pod got upgraded automatically, which threw the Helm resources out of sync. Not only might that result in chart upgrade issues in future, but, depending on how the client does the upgrade, customisations made through Helm values may get undone ( I didn't check).

Since Helm is meant to be in charge of providing a consistent configuration, it makes more sense for the client to exit with an error in this scenario.

**Comment by chenaoxd** [comment]
Agree that the traffic manager deployment shouldn't be auto-updated.

There're some example situations when not auto-updating is necessary:
1. When you're using linkerd multi-cluster, you need the `traffic-manager` to be linkerd injected to make the cross-cluster service mirror working. So you need to add a `linkerd.io/inject: enabled` annotation to the `traffic-manager` deployment. And this annotation will be removed when auto-updating.
2. When it's slow to access `docker.io`, you need to use a different image registry. And in China, `docker.io` is not stable and slow.
3. As @sichapman said, Helm is meant to be in charge of providing a consistent configuration.

For the ones who need a not auto-updating client, it's easy to make this change. Just one line of code change is needed: https://github.com/chenaoXD/telepresence/commit/152f7ec9300e6d3c5b5553365daf4d95749860d2

**Comment by josecv** [comment]
Thanks for opening an issue! This will actually be fixed by #1845 which includes changes to keep the deployment from being updated if it is managed by Helm. I believe this should also cover scenarios 1 and 2 outlined by @chenaoXD which could be implemented by deploying the traffic manager through helm.

**Comment by efunk** [comment]
Resolved in Telepresence 2.3.5 GA
