### ISSUE TITLE
Slight error in documentation for Helm Chart

### ISSUE THREAD

**Issue by benfdking** [telepresenceio/telepresence#1865]
It appears that there is a slight error in the documentation. The description or property name is flipped. 

`clientRbac.namespaces`
and 
`clientRbac.namespaced`

![image](https://user-images.githubusercontent.com/9087625/125441093-495b0676-4aad-4a85-a999-38e9c893b71f.png)

**Comment by efunk** [comment]
Resolved in Telepresence 2.3.5 GA

**Comment by benfdking** [comment]
Hey,

Sorry to be a nuisance and wish I was more competent so I could actually provide the solution rather than just the problem. Amazing and thank you for the quick turnaround.

I am wondering if one of the little errors was missed? (Not 100% sure I understand release and everything)

![image](https://user-images.githubusercontent.com/9087625/125921631-29b0feb2-ba8a-4e49-af11-ae7e5a7afd96.png)

The managerRbac section seems to be correct but not the clientRbac.

**Comment by efunk** [comment]
@benfdking thank you for bringing it to our attention. We will make sure this is fixed in our next release (2.3.6).
