### ISSUE TITLE
Not able to completely automate the installation of telepresence using shell script

### ISSUE THREAD

**Issue by ksripathi** [telepresenceio/telepresence#1872]
Hello team,

there is no way to automate below command through shell script as its prompts for browser
`telepresence login`

also 

when intercepting service it prompts for various inputs
`telepresence intercept`

is there a way in which we can set some ENV variables and avoid interrupts so that it can be fully automated

**Comment by cakuros** [comment]
Hi!

With telepresence 2.3.7, you can now use `telepresence login --apikey <apikey>` to automate logins.  In your cloud account profile, there should be a new field for API keys where you can generate one.

The link is here: https://app.getambassador.io/cloud/settings/api-keys

**Comment by cindymullins-dw** [comment]
Closing as answered.
