### ISSUE TITLE
Telepresence disconnects from cluster after multiple intercepts 

### ISSUE THREAD

**Issue by skataboina** [telepresenceio/telepresence#1874]
Facing issue with telepresence(v2.2.2) connection
step 1: "telepresence connect"
step 2: Perform telepresence intercept multiple times
step 3: After some time "telepresence intercept" command doesn’t give any response
step 4: Reconnecting telepresence to cluster (telepresence quit & telepresence connect) to resolve the issue

**Comment by thallgren** [comment]
Can you replicate this with the latest (2.3.7) version?
