### ISSUE TITLE
Traffic agent sidecar configuration issue

### ISSUE THREAD

**Issue by dmanchon** [telepresenceio/telepresence#1901]
Hi Team, really cool project, i was playing with minikube and everything was fine, i could intercept traffic and
it makes everything so easy, but when i try against our dev cluster i got the following error:
- after: `telepresence intercept -n XX XXXX --port 8000 --env-file remote.env  # redacted`
- traffic-agent sidecar logs:
```
time="2021-07-20 10:57:40.6683" level=debug msg="Logging at this level (LOG_LEVEL=\"debug\")" func=main.makeBaseLogger file="github.com/telepresenceio/telepresence/v2/cmd/traffic/logger.go:39"
time="2021-07-20 10:57:40.6684" level=info msg="Traffic Agent v2.3.4 [pid:1]" func=github.com/telepresenceio/telepresence/v2/cmd/traffic/cmd/agent.Main file="github.com/telepresenceio/telepresence/v2/cmd/traffic/cmd/agent/agent.go:113"
time="2021-07-20 10:57:40.6685" level=error msg="quit: ManagerPort(\"tcp://10.6.228.134:8080\"): strconv.ParseInt: parsing \"tcp://10.6.228.134:8080\": invalid syntax" func=main.doMain file="github.com/telepresenceio/telepresence/v2/cmd/traffic/main.go:20"
```
When i manually edit the deployment to add the "MANAGER_PORT" = 8081 to the sidecar container then it starts, but the intercept already failed and
telepresence (i guess because i manually edited the deployment) is not tracking it anymore and apparently is not able to redirect the traffic.
This is also forcing me to manually remove the sidecar since `telepresence uninstall --everything` has no effect.

Thanks a lot!!

**Comment by amora-ut** [comment]
Hi, same issue here!

**Comment by thallgren** [comment]
I don't understand why the `MANAGER_PORT` would be set to `"tcp://10.6.228.134:8080"` in the `traffic-agent` container. That seems like some kind of misconfiguration. Any idea where that value comes from? `telepresence` will not set that environment variable in the agent.

Telepresence will not perform an uninstall if a manifest that has been edited manually in a way that creates mismatches between the annotation that is added and the modifications that the annotation actions refer to. If such modifications has been made, then that might explain why an uninstall has no effect.

**Comment by cindymullins-dw** [comment]
Closing as answered.
