### ISSUE TITLE
Support telepresence version --client

### ISSUE THREAD

**Issue by iTaybb** [telepresenceio/telepresence#1902]
When running `telepresnse version`, the cli attempts to get the local and remote server versions.
If there's no remote server configured, the cli might fail with:
```
INFO[0000] No config found. Using default
Client: v2.3.5 (api v3)
Root Daemon: error: connection error: desc = "transport: error while dialing: dial unix /var/run/telepresence-daemon.socket: connect: connection refused"; this usually means that the process has terminated ungracefully
User Daemon: error: connection error: desc = "transport: error while dialing: dial unix /tmp/telepresence-connector.socket: connect: connection refused"; this usually means that the process has terminated ungracefully
telepresence: error: connection error: desc = "transport: error while dialing: dial unix /tmp/telepresence-connector.socket: connect: connection refused"; this usually means that the process has terminated ungracefully
```

Sometimes we only need the client information.
kubectl, for example, supports cli like `kubectl version --client`. It would be nice for telepresense to support the same.

**Comment by cindymullins-dw** [comment]
If you run telepresence version it should give you the client only.  You don’t necessarily need to have the traffic manager installed.  If you’re connected then this command will give you the daemon and traffic manager versions as well.  However if not connected it’ll give you just the client version.
