### ISSUE TITLE
Unable to override telepresence deployment spec

### ISSUE THREAD

**Issue by s-silvius** [telepresenceio/telepresence#1906]
"telepresence connect" is not able to spawn "traffic-manager" deployment to cluster not having yet telepresence resources.

According to instructions user can just download binary 
```
sudo curl -fL https://app.getambassador.io/download/tel2/linux/amd64/latest/telepresence -o /usr/local/bin/telepresence
sudo chmod a+x /usr/local/bin/telepresence
```
and run "telepresence connect" and it should install needed resources?

When I run "telepresence connect" traffic-manager POD get's installed but it fails to

"**Error: container has runAsNonRoot and image will run as root**"

According to charts dir https://github.com/telepresenceio/telepresence/tree/release/v2/charts/telepresence **securityContext** should be correct. But when checking traffic-manager pod it has empty securityContext.

How I can override deployment Spec? In ~.config/telepresence/config.yml 
```
samuli@test:~$ cat .config/telepresence/config.yml 
images:
  registry:
    registry1-my.company.proxy/datawire

logLevels:
  userDaemon: debug
  rootDaemon: debug
samuli@test:~$ 

```
I can override image and loglevel and that's all??
Why telepresence is not using it's own Helm files? Or how it should be done?

**Comment by thallgren** [comment]
You can [install with Helm](https://www.telepresence.io/docs/latest/install/helm/) if you like. Using `telepresence connect` is convenient if you run your own cluster or if you have admin rights on the cluster. Read more about the permission needed in the [Telepresence RBAC](https://www.telepresence.io/docs/latest/reference/rbac/) documentation.

**Comment by thallgren** [comment]
Closing this. Feel free to reopen if you think more is functionality is needed.  Documentation issues can be filed [here](https://github.com/telepresenceio/telepresence.io/issues)
