### ISSUE TITLE
Telepresence v2.3.x mutating webhook annotation results in ReplicaSet controller error

### ISSUE THREAD

**Issue by frankgu968** [telepresenceio/telepresence#1907]
When the [mutating webhook](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config/) is enabled with the annotation `telepresence.getambassador.io/inject-traffic-agent: enabled`, the cluster `replicaset-controller` throws error due to incorrect key: 

```
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  14m (x20 over 53m)  replicaset-controller  Error creating: Internal error occurred: replace operation does not apply: doc is missing path: /spec/containers/0//livenessProbehttpGet/port/name: missing value
```

It is clear that there is a string substitution problem in the resource path. 

Upon closer inspection of the source, the problem can be narrowed down to the `hidePorts` function in `cmd/traffic/manager/internal/mutator/agent_injector.go`. Specifically, 2 problems exist: 
1. The slash on the livenessProbe path is in the wrong position
2. k8s livenessProblem named ports use the `ports: <name>` notation rather than having a `/port/name` path. 
The correct k8s resource path should be `/spec/containers/0/livenessProbe/httpGet/port` in this case. [Reference](/spec/containers/0//livenessProbehttpGet/port)

**Comment by thallgren** [comment]
Resolved in 2.3.7. Thanks @frankgu968 for the fix!
