### ISSUE TITLE
Telepresence connect command fails due to internet proxy issues

### ISSUE THREAD

**Issue by petermant** [telepresenceio/telepresence#1923]
My work computer runs MacOS BigSur and connects via a VPN and an internet proxy.

When running `telepresence connect`, the command fails due to an error - which appears to involve some automatic reporting which fails. The reporting failure causes / appears to cause the connect command to fail.

Terminal output appears as follows:

```
% telepresence connect
INFO[0000] No config found. Using default
Launching Telepresence User Daemon
Telepresence User Daemon quitting... done
telepresence: error: rpc error: code = Unknown desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:
```
(The above is the entire content - i.e. there is no debug data supplied at the end despite the colon implying there's more to come)

In the connector logs, the following appears:

```
2021/07/26 11:21:40.2841 error   connector/background-metriton : report failed: Post "https://metriton.datawire.io/scout": dial tcp 35.193.8.157:443: i/o timeout
scout report
github.com/telepresenceio/telepresence/v2/pkg/client.(*Scout).Report
        github.com/telepresenceio/telepresence/v2/pkg/client/scout.go:196
github.com/telepresenceio/telepresence/v2/pkg/client/connector.run.func8
        github.com/telepresenceio/telepresence/v2/pkg/client/connector/command.go:460
github.com/datawire/dlib/dgroup.(*Group).goWorkerCtx.func1
        github.com/datawire/dlib@v1.2.4-0.20210629021142-e221f3b9c3b8/dgroup/group.go:385
github.com/datawire/dlib/derrgroup.(*Group).Go.func2
        github.com/datawire/dlib@v1.2.4-0.20210629021142-e221f3b9c3b8/derrgroup/errgroup.go:132
runtime.goexit
        runtime/asm_amd64.s:1374 (from pkg/client/connector/command.go:462)
```

I suspect the above might be because the reporting URL is blocked by our internet proxy, although I am able to visit https://metriton.datawire.io/ within Firefox on the same internet connection so it might not be that.

After this happened, I then ran the following and with the --no-report, the command was successful:

```
% telepresence connect --no-report
INFO[0000] No config found. Using default
Launching Telepresence User Daemon
Connected to context docker-desktop (https://kubernetes.docker.internal:6443)
```

**Comment by petermant** [comment]
This is still causing us a problem - and is worse in 2.4.9. Please can --no-report (or some other option) ensure that no external reports are sent?

**Comment by cindymullins-dw** [comment]
Can you try the most recent version?  Would [alsoProxy](https://www.getambassador.io/docs/telepresence/latest/reference/config#routing) help here?  It might be blocked by the internet proxy so is having Telepresence proxy it instead.  But results on a more recent version would be helpful.
