### ISSUE TITLE
telepresence leave / telepresence status does not show shutdown status

### ISSUE THREAD

**Issue by petermant** [telepresenceio/telepresence#1924]
If you have a service running, and call telepresence leave, there is no feedback to show the 'leave' request was submitted, or that it is in progress, it simply returns you to the terminal as follows:

```
% telepresence leave pi-rest-server-pete
INFO[0000] No config found. Using default
```

Attempting to setup the intercept again (immediately) shows that there is an issue because it conflicts with the intercept which was just left:

```
% telepresence intercept pi-rest-server --port 9010:8080 -n pete
INFO[0000] No config found. Using default
telepresence: error: Intercept "989def17-082c-4364-aea8-c1c054523927:pi-rest-server-pete": Failed to establish intercept: intercept in error state AGENT_ERROR: Conflicts with the currently-served intercept "e2b83647-a65c-4111-92d4-fb582e4a7e5c:pi-rest-server-pete"
```

Calling status shows that the intercept actually hasn't quit - but it doesn't show a "Shutting down" / leaving status, or let you know that the 'leave' command actually did anything:

```
% telepresence status
INFO[0000] No config found. Using default
Root Daemon: Running
  Version   : v2.3.7 (api 3)
  DNS       : ... snip..
User Daemon: Running
  Version           : v2.3.7 (api 3)
  ...snip
  Intercepts        : 1 total
    pi-rest-server-pete: username@machinename
```

It would be useful if the leave command could wait while the intercept was fully removed, and/or if the status command could show that the intercept was still in the process of being removed.

Waiting a short while and repeating the status command does eventually show the intercept being removed, so it does work - but to a new user it is not obvious the leave request is in progress.

**Comment by thallgren** [comment]
This code has since been rewritten completely. The `leave` command waits until the traffic-manager has removed the intercept.
