### ISSUE TITLE
[v2] command --new-deployment from telepresence v1 is missing in v2

### ISSUE THREAD

**Issue by zoechou** [telepresenceio/telepresence#1929]
according to [migrate-from-legacy](https://www.telepresence.io/docs/latest/install/migrate-from-legacy/)
there're only intercept commands migrated to v2,
is there any command related to --new-deployment ?

**Comment by cindymullins-dw** [comment]
Telepresence uses the intercept command as you noted.  The --new-deployment flag was not implemented on v2.
