### ISSUE TITLE
--run-shell doesn't need to suppress shell startup script in vpn-tcp mode

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#193]
`inject-tcp` needs to suppress shell startup script on OS X since DYLD_INSERT_LIBRARIES breaks Go programs like `kubectl`. `vpn-tcp` does not have that problem.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
