### ISSUE TITLE
[v2] MacOs mount doesn't work due to nodes PodCIDR differs form CIDR set by weave-net

### ISSUE THREAD

**Issue by ipleten** [telepresenceio/telepresence#1930]
I have installed MacFUse 4.1.2 with sshfs 2.10
TP intercept says mount is created by it's empty.

> 
> intercepted
>     Intercept name    : test-14137
>     State             : ACTIVE
>     Workload kind     : Deployment
>     Destination       : 127.0.0.1:8080
>     Volume Mount Point: /var/folders/4w/wbpcrlcx2p1b0g1tb5xjpn0h0000gp/T/telfs-412318992
>     Intercepting      : all TCP connections
> 
> The default interactive shell is now zsh.
> To update your account to use zsh, please run `chsh -s /bin/zsh`.
> For more details, please visit https://support.apple.com/kb/HT208050.
> bash-3.2$ ls -la /var/folders/4w/wbpcrlcx2p1b0g1tb5xjpn0h0000gp/T/telfs-412318992/
> total 0

mount shows nothing related to sshfs.
But I'm able to sshfs to my test linux box.

Connector.log has a bunch of:

>  49 2021/07/27 14:08:05.2346 debug   connector/background-manager/intercept-port-forward/100.xxx.xxx.xxx:41306 : sshfs waiting 6s before retrying after error: dial tcp 100.xxx.xxx.xxx:41306: i/o timeout (from pkg/client/retry.go:48)

'ip route get' route shows it should  be available via my default gateway and not any tunnel.

Cluster CIDR  is '100.96.0.0/11'  I see daemon was trying to add  some subntes but 100.123.x.x  is absent, therefore routing table  isn't updated.

**Comment by ipleten** [comment]
I believe bad routing happens due to we use weave-net  and I noticed that CIDR reported by nodes via k8s api is from different  range than pod gets.

**Comment by thallgren** [comment]
@ipleten I have no experience with weave-net. Do you have any idea how to find the correct pod CIDRs?

**Comment by ipleten** [comment]
It can be read from weave output but it's really wonky and would require access to kube-system NS. I wonder if it's possible to set whole `cluster-cidr` to be routed via tunnel instead of each subnet (like service-cidr)? Is there any limitations?  `--also-proxy cidr` would help but it was removed in tp2.

**Comment by ipleten** [comment]
Ok also-proxy available (RTFM https://www.getambassador.io/docs/telepresence/latest/reference/config/#alsoproxy).
I see it in status output as:

>   Also Proxy: (1 subnets)
    - 100.96.0.0/11

And mount works now. But it's not very stable and often hangs up.

**Comment by thallgren** [comment]
@ipleten , I guess it would be enough to give the traffic-manager access to the kube-system NS, since that's the service responsible for finding the CIDRs, so I don't think that would be a blocker. What "weave-output" are you referring to?

**Comment by ipleten** [comment]
Weave creates daemonset and there is an `weave --local report` CLI command. I'm not sure if there is an endpoint which might be queries directly. 
UPDATE:
`curl 127.0.0.1:6784/report  -H 'Accept: application/json`
https://github.com/weaveworks/weave/blob/master/weave#L1352

It returns a lot of things and one of them is a:

>     "IPAM": {
>         "Paxos": null,
>         "Range": "100.96.0.0/11",
>         "RangeNumIPs": 2097152,
>         "ActiveIPs": 46,
>         "DefaultSubnet": "100.96.0.0/11",
>         "Entries": [
>             {
>                 "Token": "100.96.0.0",
>                 "Size": 32768,
>                 "Peer": "int_mac1",
>                 "Nickname": "nodeip1",
>                 "IsKnownPeer": true,
>                 "Version": 36233
>             },
>             {
>                 "Token": "100.96.128.0",
>                 "Size": 32768,
>                 "Peer": "int_mac2",
>                 "Nickname": "nodeip2",
>                 "IsKnownPeer": true,
>                 "Version": 36686
>             },....
>        }

And `token` here is a subnet. Unfortunately weave docs are not fully at all.


Anyway I still believe that using `cluster-cidr` is better way (weave range should be the same as k8s cluster-cidr according to their docs), but not sure how to get it without parsing whole cluster-info.

**Comment by ipleten** [comment]
It might be solved via https://github.com/telepresenceio/telepresence/issues/2135
I'd need to recheck it.
