### ISSUE TITLE
[v2] Provide a way to ensure mount is available already.

### ISSUE THREAD

**Issue by ipleten** [telepresenceio/telepresence#1937]
I believe mount is async operation and quite often I'm able to get shell before (and run scripts to obtain secrets before actual service start) mount is available leading to "file not found" error.

How about to check if serviceaccount mount is available via TELEPRESENCE_ROOT/var/run/secret/

**Comment by cindymullins-dw** [comment]
You should be able to export it as an environment variable and then check that the mount is there.
` export mount_var_name=$TELEPRESENCE_ROOT/var/run/secret/ `
After setting this you should be able to refer to the mount as `$mount_var_name` in commands like` telepresence intercept <mysvc> --port <port> --mount=true -- $mount_var_name .`
