### ISSUE TITLE
Feature: ARM64 builds of the Telepresence client

### ISSUE THREAD

**Issue by scottslowe** [telepresenceio/telepresence#1947]
As the use of ARM64-based platforms increases (in particular, Apple's M-based Macs), it would be great to be able to offer native ARM64 binaries for those platforms.

**Comment by scottslowe** [comment]
As a data point: I was just able to compile a Darwin ARM64 build from the master branch with no apparent issues. I'll spend some time testing the build to make sure it works as expected.

**Comment by efunk** [comment]
Fixed and released in Telepresence 2.4.6 GA
