### ISSUE TITLE
[v2] Inconsistent performance for large requests

### ISSUE THREAD

**Issue by BjornM111** [telepresenceio/telepresence#1953]
# Description
The performance of big GET responses (>300KB) keeps dipping for us, with some services we even get incomplete responses. We've tested this on on two completely different machines (one running Ubuntu through WSL2 and one running Arch natively, in both cases we're connecting to a local kind cluster however) and we're getting similar results on both. Interestingly the problem goes away almost completely when we set the logging level for the "rootDaemon" to "debug"

# How to reproduce
Unfortunately we haven't been able to make a reproduceable case where it always fails but this seems to show the problem almost every time. We just do a bunch of GET requests and then output the time it took for each request to finish.
```bash
kubectl create ns tmp
kubectl run -n tmp --image kennethreitz/httpbin --expose server --port 80
for each in $(seq 0 100); do /bin/time -f %es curl -s server.tmp/bytes/500000 --output tmp; done
```

With this config...
```yaml
# ~/.config/telepresence/config.yml
logLevels:
  rootDaemon: debug
```
```bash
$ for each in $(seq 0 100); do /bin/time -f %es curl -s server.tmp/bytes/500000 --output tmp; done
...
0.07s
0.07s
0.07s
0.07s
0.07s
```
...everything seems fine, the request takes the same amount of time every time. When using this config however...
```yaml
# ~/.config/telepresence/config.yml
logLevels:
  rootDaemon: info
```
```bash
$ for each in $(seq 0 100); do /bin/time -f %es curl -s server.tmp/bytes/500000 --output tmp; done
0.07s
...
0.06s
0.06s
2.10s
0.06s
0.06s
...
0.06s
0.06s
2.10s
0.06s
...
0.06s
2.10s
0.06s
0.06s
0.06s
```
...we keep getting spikes of substantially longer request times.

In some cases we've had to run the command several times to make it happen, sorry for this somewhat "janky" setup but it was the best we could come up with.

**Comment by khussey** [comment]
This is fixed in the 2.4.5 release, which is now available.
