### ISSUE TITLE
how to mount oidc tokens when using irsa in eks

### ISSUE THREAD

**Issue by 0x6a77** [telepresenceio/telepresence#1966]
any pods that do [this](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) cannot get the aws automatic rotating oidc web identity token mounted to the local machine. this issue serves two purposes:

1. share a workaround (that will show up in the google search index for anyone else up against this)
```
telepresence connect
telepresence intercept --namespace my_namespace --env-json telepresence.json my_workload
telepresence leave my_workload 
```

(now we know the agent is running)

```
kubectl exec -it -n my_namespace my_workload -c traffic-agent -- ln -s /var/run/secrets/eks.amazonaws.com /tel_app_mounts/var/run/secrets/
telepresence intercept --namespace my_namespace --env-json telepresence.json  my_workload
```

now the rotating token is locally mounted and updated at `$TELEPRESENCE_ROOT/var/run/secrets/eks.amazonaws.com/serviceaccount/token`. any project that uses boto3 or any aws sdk will "just work" because `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` will be in the env vars file (and point to the right place if you do the magic with local env vars)

2. propose a fix

the simplest fix is in `container.go` to treat `/var/run/secrets/eks.amazonaws.com` the same way as `/var/run/secrets/kubernetes.io`. a more advanced solution might be to do this for anything in `/var/run/secrets`, or maybe even just projected volume mounts in `/var/run/secrets`. eks seems to be the only service that uses a web token file for irsa, and eks seems to be the dominant player so maybe the simplest solution gets 90% of the benefit for 5% of the effort.

i probably can take on item 2, but it seems like it's enough of a change that it warrants discussion first

**Comment by mentos1386** [comment]
Workaround sadly didn't work for me.

Accessing other secrets than just `kubernetes.io` should work out of the box. I think this was the behavior of telepresence v1.

**Comment by cindymullins-dw** [comment]
Per tech support mtg, we’re assuming you want a way to add AWS IAM roles to specific K8s pods and to have k8s service accounts be able to act as IAM users and use IAM permissions. Are you running an intercept or just trying to access the service directly through outbound, not utilizing the intercept?  It should work out of the box if you have an intercept running.  When you’re running an intercept, the DNS and actual routing behavior goes through the pod as opposed to bypassing it. It is supposed to get picked up by the Secure Token Service (STS) web hook that injects the AWS identity information (credentials) - that said, we’re not 100% sure about the IAM web hook.

**Comment by 0x6a77** [comment]
stepping back a bit: let's make the use case a data scientist using boto3 (amazon's python sdk for aws) to access cloudwatch and redshift. the simplest, safest way to do this is assume-role with a web identity provider: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-with-web-identity-provider

coincidentally, earlier this year eks offered irsa so that service accounts can assume an iam role via an oidc-based web identity token: [irsa](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/). how this happens practically is that eks detects an oidc provider and adds a mutating webhook based on an admission review. the webhook detects a `eks.amazonaws.com/role-arn` annotation in a pod's service account and mutates the pod to include standard environment variables and a rotating web-token file.

this perfectly aligns to the form of boto3-based access above (i think _all_ aws sdk's support this). 

so now the data scientist can call sts AssumeRoleWithwebIdentity without any explicit config, secrets, etc. and get a token that allows access to cloudwatch, redshift and so on (if the iam role allows that).

what i don't follow in the question you're asking: how sts knows about this oidc-based identity by having the intercept contact sts directly. keep in mind that the cluster's oidc provider might be google oauth, keycloak so something has to generate a token sts trusts. the eks irsa webhook does exactly this, and puts that token in a well-known place using standard environment variables that say where it is

i did a lot of research on how the sts intercept thing you mentioned might work and i don't see how. i mean if it works and we don't change the data scientist's code (that uses boto3) then great! can you show us an example?

the problem is that the traffic-agent doesn't link anything except the cluster secrets, so the irsa web-identity token is not visible to sshfs and therefore the local code running in, say, pycharm. (the workaround i mentioned above does link this token and the result is code works 100% the same in pycharm as it does the eks cluster. tho' i suspect it fails for anyone with a read-only fs or wrong permissions.)

if it doesn't work, i see a fairly straightforward change to `container.go` that allows all `var/run/secrets` to get mounted to the local session via sshfs. i don't remember if this was the v1 behavior, but @mentos1386 says that was the case.

**Comment by 0x6a77** [comment]
ps: i can chase this to a committed pr if you all agree on the strategy
