### ISSUE TITLE
telepresence uninstall --everything does not Uninstall Traffic Agents Injected via Mutating Webhook

### ISSUE THREAD

**Issue by iNoahNothing** [telepresenceio/telepresence#1970]
## Summary

`telepresence uninstall --everything` is supposed to remove all Telepresence components from the cluster and revert it back to a pre-Telepresence state. 

This works well when injecting the traffic agent via the normal injection mechanism but does not seem to correctly remove the traffic agent if it is installed via the [mutating webhook](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config/#mutating-webhook).

You just need to run
```
kubectl rollout restart deploy {{SERVICE}}
```
to revert the service back after uninstalling the traffic manager since the admissions controller has nothing telling it to inject the sidecar but that is a step that could/should be handled by telepresence.

## Replicator 

1. install telepresence and connect to the cluster

```
telepresence connect
```

2. Edit a `Deployment` that has not already been intercepted and add the `telepresence.getambassador.io/inject-traffic-agent: enabled` annotation to it
3. Watch the pods spin up and check to make sure that the traffic-agent container has been added
```
kubectl get pod
NAME                       READY   STATUS    RESTARTS   AGE
quote-5d785f4f6f-dg7h4     2/2     Running   0          8m7s
```
4. Run `telepresence uninstall --everything` and see that the quote pod is not removed
```
telepresence uninstall --everything

kubectl get pod -n ambassador
NAME                               READY   STATUS        RESTARTS   AGE
traffic-manager-75cc4c5b7b-z8xfm   0/1     Terminating   0          5m26s
kubectl get pod
NAME                       READY   STATUS    RESTARTS   AGE
quote-7d69cd6447-58jv4     2/2     Running   0          8m7s
```

5. Run `kubectl rolllout restart deploy {{SERVICE}}` to restart the deployment and uninstall the agent
```
kubectl rolllout restart deploy quote

kubectl get po
NAME                       READY   STATUS    RESTARTS   AGE
quote-758cfcdb67-6c4wx     1/1     Running   0          8m7s
```

**Comment by efunk** [comment]
Resolved in Telepresence 2.4.3 GA.
