### ISSUE TITLE
Telepresence should have a mechanism for updating the traffic manager after changing config.yml

### ISSUE THREAD

**Issue by iNoahNothing** [telepresenceio/telepresence#1971]
The [`config.yml`](https://www.getambassador.io/docs/telepresence/latest/reference/config/#global-configuration) file contains configurations that change how things on the laptop and cluster side are installed. 

Some of these things affect the traffic manager `Deployment` (ex: setting the `image.webhookAgentImage` sets the `TELEPRESENCE_AGENT_IMAGE` env var in the `Deployment`) and require a redeploy of the `Deployment` to take effect. At the moment, you must manually make this happen by disconnecting, removing the `Deployment`, and reconnecting to the cluster. There should be a mechanism that makes this happen automatically.

**Comment by cindymullins-dw** [comment]
Hi @iNoahNothing! :) Is this still the case?  We believe if you `telepresence quit` and `telepresence connect` after making your config.yaml change that should override the Traffic Manager values as needed without having to remove the Deployment.

**Comment by iNoahNothing** [comment]
> Hi @iNoahNothing! :) Is this still the case? We believe if you `telepresence quit` and `telepresence connect` after making your config.yaml change that should override the Traffic Manager values as needed without having to remove the Deployment.

I haven't used Telepresence much since reporting this when I was debugging it at Ambassador. I'm not sure if this is still the case or not but we can go ahead and close this issue 🙂
