### ISSUE TITLE
ll

### ISSUE THREAD

**Issue by gc70ki** [telepresenceio/telepresence#1981]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'default', '--method', 'inject-tcp', '--new-deployment', 'sml-subscription-shiji', '--expose', ':', '--run', 'bash', '-c', " SMARTMAT_AUTH_SIGNING_KEY= AWS_XRAY_DAEMON_ADDRESS='xray-service.kube-system:2000' K8SENV_TELEPRESENCE=1 reflex -d fancy -r '(\\.go$|go\\.mod)' -s -- bash -c 'GODEBUG=netdns=cgo go run -v main.go -env '"]`
Version: `0.109`
Python version: `3.7.4 (default, Sep 25 2019, 16:42:29) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.20.4 // Server Version: v1.20.7-eks-d88609`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin shiji.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 37, in main
    args = parse_args()  # tab-completion stuff goes here
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 488, in parse_args
    args.expose = PortMapping.parse(args.expose)
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 41, in parse
    local_port, remote_port = map(int, port_string.split(":"))
ValueError: invalid literal for int() with base 10: ''

```

Logs:

```
Not available
```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
