### ISSUE TITLE
How can I intercept the traffic which accesss deployment  via pod Ip directly?

### ISSUE THREAD

**Issue by Euthpic** [telepresenceio/telepresence#1983]
Some of our deployments register pod ips in zookeeper and other deployments access them via pod ip instead of svc.
Therefore the traffic won't go through svc,loadbalance is under control of zookeeper.

It seems that telepresence only intercepts traffic when they go thourgh svc.Could u please consider that supporting intercept traffic which access deployment via pod ip directly?

**Comment by ileixe** [comment]
+1. I am looking for a way to intercept controller pod which does not have svc either.
