### ISSUE TITLE
Mysql service connection issue

### ISSUE THREAD

**Issue by ta-shi** [telepresenceio/telepresence#1988]
Environment: 

- MacOS 11.4
- Minikube v1.22
- api-service framework: Spring boot

Kubernetes services: 
 - mysql-service
 - api-service
 
`telepresence intercept api-services --port=8888`

The rest call works for a while but after few seconds MySQL connection fails with this error

`HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6046ae26 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.`

This issue is introduced after upgrading from telepresence 1 to 2.

This could be related to https://github.com/telepresenceio/telepresence/issues/1967

**Comment by thallgren** [comment]
If the timeout happens after 60 seconds, I think this will be fixed by #1994.

**Comment by efunk** [comment]
This should be fixed in Telepresence 2.4.1. Please reopen if you still see the issue.
