### ISSUE TITLE
Don't require kubernetes credentials

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#2]
Currently `telepresence` requires `kubectl` and corresponding credentials to access the remote Kubernetes cluster. It would be nice if there was another access control mechanism that didn't require giving users full Kubernetes access.

Interested in this feature? Add a "thumbs up" or comment below.

**Comment by binocarlos** [comment]
Would it be possible to somehow use SSH to tunnel the raw HTTP traffic into a sidecar container that could proxy the request onto the api server adding credentials on the way.   Then you are hiding k8s credentials and replacing it with ssh keys which are common and so perhaps a good candidate for `another access control mechanism`?

**Comment by itamarst** [comment]
SSH keys seem like a reasonable mechanism, yes. A more fundamental issue is the user experience.

Current workflow has two variants:

1. "Getting started quickly:" Creation of a new Deployment automatically by Telepresence.
2. "Realistic entrypoint:" Manual creation, ideally with a Deployment that is closely related to the production one (same env variables, volumes) for realism.

In a mode where there's a pre-existing service in the Kubernetes cluster to authenticate against, perhaps realism could be done in a more automated fashion allowing for getting started quickly experience for the developer using telepresence. E.g. for Deis Workflow copying an existing application's setup somehow...

**Comment by thallgren** [comment]
Closing this ticket. Telepresence no longer require `kubectl`. Access to the cluster is required in order to establish an intercept. There's no way around that, but we do provide a helm-chart so that an admin can pre-install the traffic-manager and thereby limit the type of access that is required.
