### ISSUE TITLE
Redact sensitive log information

### ISSUE THREAD

**Issue by thallgren** [telepresenceio/telepresence#2007]
Users that provide logs with a bug report often redact things in the log, such as IP-addresses, host names, and other information that they consider sensitive. Telepresence should provide a way to do that automatically. Part of this work could be to avoid or change how we log such info. For instance, instead of logging the IP of the traffic-manager, we could log `IP("traffic-manager", 10.20.12.11)` and then change that into `IP("traffic-manager", <redacted>)` in the redacted version. Similar constructs could be used for other things that are subject to redaction such as `SUBNET`, `CLUSTER`, etc.

**Comment by khussey** [comment]
Support for this was added in the 2.4.5 release, which is now available.
