### ISSUE TITLE
Telepresence issue

### ISSUE THREAD

**Issue by summersculture** [telepresenceio/telepresence#2012]
### What were you trying to do?
Telepresence and run `kickback`

(please tell us)

### What did you expect to happen?
start telepresence 

(please tell us)

### What happened instead?
Show this error message

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'kickback', '--expose', '30080:30080', '--logfile', '/var/folders/zk/2w95pmhj5932c4qhzjqd4qrw0000gn/T/tmp.h9DmvlGB', '--mount', 'false', '--run', 'scli', 'service', 'run', '--environment', 'development', '--name', 'kickback', '--env-vars', 'PORT=30080,LISTEN_PORT=30080']`
Version: `0.108`
Python version: `3.9.0 (default, Oct 27 2020, 14:15:17) 
[Clang 12.0.0 (clang-1200.0.32.21)]`
kubectl version: `Client Version: v1.19.4 // Server Version: v1.19.13-eks-8df270`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin 192-168-1-102.tpgi.com.au 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
ubernetes.io/not-ready:NoExecute op=Exists for 300s
  92.7  50 |                  node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
  92.7  50 |                  node_purpose=microservices:NoSchedule
  92.7  50 | Events:
  92.7  50 |   Type    Reason     Age   From               Message
  92.7  50 |   ----    ------     ----  ----               -------
  92.7  50 |   Normal  Scheduled  56s   default-scheduler  Successfully assigned bsa2/kickback-30800d2bedbb46aaa91d4ab742800797 to ip-10-59-35-4.ap-southeast-2.compute.internal
  92.7  50 |   Normal  Pulling    53s   kubelet            Pulling image "datawire/telepresence-k8s:0.108"
  92.7  50 |   Normal  Pulled     46s   kubelet            Successfully pulled image "datawire/telepresence-k8s:0.108" in 6.430377219s
  92.7  50 |   Normal  Created    46s   kubelet            Created container microservice
  92.7  50 |   Normal  Started    46s   kubelet            Started container microservice
  92.7 TEL | [50] ran in 8.01 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
