### ISSUE TITLE
TELEPRESENCE failure 24-8-2021

### ISSUE THREAD

**Issue by shemlar** [telepresenceio/telepresence#2013]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.109`
Python version: `3.9.2 (default, Feb 19 2021, 17:09:53) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.20.4 // Server Version: v1.18.20-eks-8c579e`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Roeys-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
 126 |     SecretName:  default-token-ghgn4
  80.2 126 |     Optional:    false
  80.2 126 | QoS Class:       Burstable
  80.2 126 | Node-Selectors:  <none>
  80.2 126 | Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
  80.2 126 |                  node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
  80.2 126 | Events:
  80.2 126 |   Type    Reason     Age   From               Message
  80.2 126 |   ----    ------     ----  ----               -------
  80.2 126 |   Normal  Scheduled  39s   default-scheduler  Successfully assigned roey-dev/telepresence-1629805784-67272-7317 to ip-172-40-43-60.ec2.internal
  80.2 126 |   Normal  Pulled     38s   kubelet            Container image "datawire/telepresence-k8s:0.109" already present on machine
  80.2 126 |   Normal  Created    38s   kubelet            Created container telepresence
  80.2 126 |   Normal  Started    38s   kubelet            Started container telepresence
  80.3 TEL | [126] ran in 3.92 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
