### ISSUE TITLE
DNS resolution fails when running in docker

### ISSUE THREAD

**Issue by ming08108** [telepresenceio/telepresence#2018]
```bash
user@host:~$ telepresence intercept someservice --docker-run -- -it --rm rancher/curl someotherservice
Using Deployment someservice
intercepted
    Intercept name    : someservice 
    State             : ACTIVE
    Workload kind     : Deployment
    Destination       : 127.0.0.1:8080
    Volume Mount Error: sshfs is not installed on your local machine
    Intercepting      : all TCP connections
curl: (6) Couldn't resolve host 'someotherservice'
```

```
telepresence version

Client: v2.4.0 (api v3)
Root Daemon: v2.4.0 (api v3)
```

Running in an Ubuntu 20.04 WSL2 environment. DNS resolution works fine when intercepting outside the docker image.

**Comment by cindymullins-dw** [comment]
Is this persisting on newer versions, like 2.11?

**Comment by cindymullins-dw** [comment]
There can be issues when trying to use the Docker network and your host network in hybrid mode as noted [here.](https://www.getambassador.io/docs/telepresence/latest/reference/docker-run#using-docker-run-flag-without-docker) But you can use the [`--docker-run` flag](https://www.getambassador.io/docs/telepresence/latest/reference/docker-run#the-docker-run-flag) to have your intercept go to another Docker container, running [`telepresence connect --docker `first](https://www.getambassador.io/docs/telepresence/latest/reference/docker-run#the-docker-flag).
