### ISSUE TITLE
Make kubernetesZone configurable

### ISSUE THREAD

**Issue by brookelynne** [telepresenceio/telepresence#2021]
DNS routing is partially broken for my cluster due to our cluster suffix not being `.local`. Please make the kubernetesZone configurable:
https://github.com/telepresenceio/telepresence/blob/64e6bb8e30a0389cd4ac8f992b89a414167382a1/pkg/client/daemon/outbound.go#L22

**Comment by thallgren** [comment]
This should be a per-cluster setting in our kubeconfig extension.

**Comment by thallgren** [comment]
We will retrieve the correct kubernetesZone from the cluster instead of making it configurable.
