### ISSUE TITLE
Subnet retrieval should be more flexible

### ISSUE THREAD

**Issue by johnlanni** [telepresenceio/telepresence#2023]
Hi, when I enable the Calico CNI in k8s , the subnet of the pods’ IPs can’t be obtained by telepresence exactly.  I found some information about the Pod’s CIDR and Calico:

https://docs.projectcalico.org/networking/get-started-ip-addresses
https://github.com/projectcalico/calico/issues/2592#issuecomment-489233638

It seems we must enable the Host-local IPAM, then Calico will use the Node.Spec.PodCIDR for pod.
I think the logic of  `Deriving subnets from IPs of pods`  should be configureable, then we no need to enable the Host-local IPAM plugin.

![image](https://user-images.githubusercontent.com/6763318/131061920-8424e976-8371-458f-8448-d3d8e592aa09.png)

Or check whether Calico is deployed in the cluster, and obtain the CIDR from Calico’s blockaffinities, then adding to the pods' CIDRs.

![image](https://user-images.githubusercontent.com/6763318/131062065-8f6e059a-eecd-490a-9907-7bd189d71cf9.png)

**Comment by efunk** [comment]
Resolved in Telepresence 2.4.4 GA
