### ISSUE TITLE
telepresence 2.4 version Request pod timeout

### ISSUE THREAD

**Issue by yinxiulong** [telepresenceio/telepresence#2049]
After the telepresence connect connection is successful, the kubernetes service can be accessed, but the pod cannot be accessed through IP. This causes the spingcloud feign to request other microservices time out

**Comment by thallgren** [comment]
How do you obtain the IP of the pod?
What does the URL look like when you try to access the pod?

**Comment by yinxiulong** [comment]
Pod IP obtained by kubernetes command

```
kubectl get pod  -o wide
```
The previous telepresence version 0.109 can be accessed through the IP of the pod. Now version 2.4 cannot be accessed through pod IP.

**Comment by yinxiulong** [comment]
Assume that the pod IP is 10.58.153.187. Telepresence version 0.109 can be accessed in this way
```
http://10.58.153.187:8888/user/login
```
Telepresence version 2.4 cannot be accessed through this address.

**Comment by cindymullins-dw** [comment]
In testing we're able to access the pod via the IP.  Could you try upgrading to a newer version?
