### ISSUE TITLE
The service is accessed through the IP address and port of the pod container

### ISSUE THREAD

**Issue by yinxiulong** [telepresenceio/telepresence#2050]
After the telepresence connect connection is successful, I want to directly access the services in the container through the IP and port of the pod, rather than through the service. What should I do?

**Comment by cindymullins-dw** [comment]
To clarify, you can curl the ip of the pod and the port of the pod using the ip of the service.   Is this scenario for example that you have a local service running and want that local service to be able to access other services in the cluster via pod IP?
