### ISSUE TITLE
Debugging java app in a K8S pod using telepresence

### ISSUE THREAD

**Issue by saurav28** [telepresenceio/telepresence#2054]
I am trying to debug a java application deployed in K8S cluster in Kyma.
https://kyma-project.io/

I am trying to use telepresence for this

I have installed telepresence and have swapped the deployment.

Below are the logs while connecting

    T: Forwarding remote port 8080 to local port 8080.

T: Connected. Flushing DNS cache.
T: Setup complete. Launching your command.

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
@cba47a8.kyma-stage.shoot.live.k8s-hana.ondemand.com|bash-3.2$
Now when i try to create a remote debug configuration in Eclipse by giving localhost:8080 i am getting connection refused error.

I understood with the logs above that the port forwarding has happened and available as local port.

Best Regards,

Saurav

**Comment by thallgren** [comment]
It sounds like you're trying to use port 8080 for the debugger to connect to the process. The debugged process must serve its http requests on that port, not the debugger.
It also sounds like you're using an older version of telepresence (the current version will intercept, not "swap" a deployment).
You can find examples on how to debug a java application here: https://www.telepresence.io/docs/latest/quick-start/
