### ISSUE TITLE
Too many steps to deal with expired login

### ISSUE THREAD

**Issue by efunk** [telepresenceio/telepresence#2062]
Reported by Matt Turner:

Telepresence friction point. Telepresence 2.4.2
Telepresence login state =  Ambassador Cloud  : Login expired (or otherwise no-longer-operational)

As a user I would expect telepresence login  would resolve this state.

Instead the user must:
telepresence login
telepresence quit
telepresence logout
telepresence login
to resolve.

**Comment by danielbryantuk** [comment]
I bumped into the same issue today. Running `telepresence login` did not open my browser and appeared to do nothing. 

After Thomas mentioned this ticket and I followed the steps above, the issue was resolved

**Comment by donnyyung** [comment]
In 2.4.7, `telepresence login` will get you a new token once your token is expired.  There is an issue with the refresh tokens that we still need to debug + find a fix for (so login frequency will decrease once we fix that), but this UX should be better than getting stuck in this weird semi-logged-in state

**Comment by donnyyung** [comment]
This has been resolved!
