### ISSUE TITLE
Json output

### ISSUE THREAD

**Issue by xakraz** [telepresenceio/telepresence#2076]
We have embedded telepresence in our tool belt.

For ease of use, it would be nice if `telepresence` cli was able **to format it's output in json** like many tools already do (`kubectl`, aws, gcloud, ...)

**Comment by zopanix** [comment]
Hey, I have the "same" request but will take the time to develop a bit more:

We're currently happily using telepresence at my company. The tool is great and works very well. Thank you for providing this :)

As a feature request, we have the following use case:

We want our developers to be ready ASAP when they join the company. We don't want them to necessarily have to suffer the learning curve of every single tool we use. Therefore we provide everybody with an internal tool that wraps most developer's use cases with an interactive CLI corresponding to our context. It would be a great addition if `telepresence` coud output machine readable output (ex: json, yaml, or something else). This would allow us to easily read and parse it's output for use in our internal tooling.

I do understand that this is fairly low priority but it seems it would be a nice addition to telepresence and should be relatively simple to implement.

Thanks a lot anyways :)

**Comment by thallgren** [comment]
All commands support `--output json`.
