### ISSUE TITLE
Can't install older versions of Telepresence

### ISSUE THREAD

**Issue by Hiroki111** [telepresenceio/telepresence#2086]
According to [this page](https://www.telepresence.io/docs/v2.2/install/), an older version of Telepresence can be installed from `https://app.getambassador.io/download/tel2/darwin/amd64/x.y.z/telepresence` (for Mac OS), where `x.y.z` is supposed to be the version you need.

However, when I visited `https://app.getambassador.io/download/tel2/darwin/amd64/0.109/telepresence`, I got `403 Forbidden` error.

Can someone please look into this? I really need this particular version of Telepresence in my machine.

FYI
Here's the command I used in terminal:
```
sudo curl -fL https://app.getambassador.io/download/tel2/darwin/amd64/0.109/telepresence  -o /usr/local/bin/telepresence
```

And the result was:
```
curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by thallgren** [comment]
You are looking at the docs for Telepresence v2. For v1 installs, you'll need to consult in the old docs:
https://www.telepresence.io/docs/v1/reference/install/.
