### ISSUE TITLE
Can't install version 1 of Telepresence

### ISSUE THREAD

**Issue by Hiroki111** [telepresenceio/telepresence#2087]
https://www.telepresence.io/docs/v1/reference/install/

This page says that v1 of telepresence can be installed to Mac by

```
brew install --cask osxfuse
brew install datawire/blackbird/telepresence-legacy
```

The 1st command didn't throw any error, but running `brew install datawire/blackbird/telepresence-legacy` gave me the error below

```
Error: sshfs-mac is already installed from homebrew/core!
Please `brew uninstall sshfs-mac` first."
```
When I ran `brew uninstall sshfs-mac`:

```
Error: No available formula or cask with the name "sshfs-mac". Did you mean s3fs-mac?
```

When I ran `brew uninstall s3fs-mac`,
```
Error: No available formula or cask with the name "s3fs-mac". Did you mean mp3fs-mac, s3ql-mac or sshfs-mac?
```

When I ran `brew uninstall mp3fs-mac`:
```
Error: No available formula or cask with the name "mp3fs-mac". Did you mean s3fs-mac?
```

Can someone please look into this? I feel that `datawire/blackbird/telepresence-legacy` has an error

**Comment by thallgren** [comment]
I think v1 suffers from the same problem as v2 when it comes to sshfs/osxfuse. Perhaps [the same solution](https://www.telepresence.io/docs/latest/troubleshooting/#volume-mounts-are-not-working-on-macos) can be applied?

**Comment by Hiroki111** [comment]
@thallgren 
That solution worked. Thank you!
