### ISSUE TITLE
Not able to telepresence to a remote cluster

### ISSUE THREAD

**Issue by mastery-sanket-nagare** [telepresenceio/telepresence#2109]
Trying to telepresence to a remote cluster on windows as well WSL2 and failing miserably to do so.

Getting the following errors in connector.log

![image](https://user-images.githubusercontent.com/64788037/134333984-007bc475-2af3-468b-897b-1a697bff8a47.png)

Although the current context is set, telepresence always tries to connect to the ambassador namespace.

Here is the command that I am trying.
telepresence --namespace <namespace name that I have access to> --run-shell

Client: v2.4.2 (api v3)
Root Daemon: v2.4.2 (api v3)
User Daemon: not running

**Comment by mastery-sanket-nagare** [comment]
@thallgren Could you please help me out here?

**Comment by josecv** [comment]
@mastery-sanket-nagare Are you trying to set up telepresence in a different namespace? If so, check out [this doc](https://www.telepresence.io/docs/latest/reference/config/#manager) which should help you set the namespace to connect to -- at that point it should stop trying the `ambassador` namespace and try the one you're setting.

Of course, you'll need `secrets` permissions on that namespace
