### ISSUE TITLE
Cannot change service port without uninstalling traffic-agent from the deployment

### ISSUE THREAD

**Issue by tobiasfriden** [telepresenceio/telepresence#2120]
**Describe the bug**
I am running a service with multiple ports. According to the telepresence documentation [here](https://www.telepresence.io/docs/latest/reference/intercepts/) it is possible to change the port using the `--port` flag.

However, everytime I change the port I get the error message:
```
telepresence: error: Failed to establish intercept: Deployment already being used for intercept with a different service
configuration. To intercept this with your new configuration, please use
telepresence uninstall --agent SERVICE_NAME This will cancel any intercepts that
already exist for this service: Deployment name="SERVICE_NAME" namespace="default": port changed from "80" to "rpc-web-SERVICE_NAME"
```
meaning I have to reinstall the traffic-agent (which takes several minutes) everytime I want to listen to another port. Also, it is not possible to run multiple intercepts listening to one port each (in telepresence v1 it was simple to run just one `--swap-deployment` which would get the traffic from all the ports.

**To Reproduce**
Run `telepresence intercept` with different values of `--port` for the same service.

**Expected behavior**
I should be able to change `--port` without reinstalling `traffic-agent`

**Versions (please complete the following information):**
 - Output of `telepresence version`:  Client: v2.4.3 (api v3) Root Daemon: v2.4.3 (api v3) User Daemon: v2.4.3 (api v3)
 - Operating system of workstation running `telepresence` commands: Mac OS 10.15.6
 - Kubernetes environment and Version: AWS EKS, output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by tobiasfriden** [comment]
To make matters worse, sometimes the command to uninstall traffic-agent fails with:
```
telepresence: error: 1 error occurred:
        * Deployment name="deployName" namespace="default": unable to locate port "tm-servicePortName" in container "containerName"
```
It seems like the prefix `tm-` is for some reason added to the serviceName which I have specified. The only solution in this case is to recreate the deployment which is not feasible to do in a production environment

**Comment by donnyyung** [comment]
Hey @tobiasfriden , I think the problem you are surfacing here is essentially this issue: https://github.com/telepresenceio/telepresence/issues/1607

We made some changes to our architecture that should enable us to add this feature soon!

**Comment by tobiasfriden** [comment]
@donnyyung yes that's exactly what I would need, great news! Closing this then.
