### ISSUE TITLE
telepresence fails on Mac (docker for Mac + Kubernetes)

### ISSUE THREAD

**Issue by waffle999** [telepresenceio/telepresence#2122]
I followed the tutorial to install telepresence on https://www.telepresence.io
But it always fails at the "verifying" part.

1. `telepresence connect`
2. `curl -ik https://kubernetes.default.svc.cluster.local` / `curl -ik https://kubernetes.default`

this will result in `curl: (7) Failed to connect to kubernetes.default.svc.cluster.local port 443: Operation timed out`

this is also the behaviour when i try to access any of my services  

**Expected behavior**
From the tutorial it seems that the expected output should be
```
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, private
Content-Type: application/json
...
```

Client: v2.4.4 (api v3)
Root Daemon: v2.4.4 (api v3)
User Daemon: v2.4.4 (api v3)
Mac + Docker Mac Kubernetes
Kube:
-     Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
-     Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
[](url)

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7252184/telepresence_logs.zip)

**Comment by Ethan-99** [comment]
I am experiencing the same issue. In my case I can confirm that the curl is hitting the correct Cluster IP of the default kubernetes service and then times out:

```
kubectl get svc -n default

NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)                      AGE
kubernetes                           ClusterIP      172.20.0.1       <none>                                                                    443/TCP
```

```
curl -ikv https://kubernetes.default
*   Trying 172.20.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 172.20.0.1 port 443 failed: Operation timed out
* Failed to connect to kubernetes.default port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to kubernetes.default port 443: Operation timed out
```

I am on a VPN that is necessary to remotely access the cluster. 

i should also note that I tried this with several versions of telepresence, not just v2.4.4, all with the same results.
[daemon.log](https://github.com/telepresenceio/telepresence/files/7281382/daemon.log)

**Comment by PopChicken** [comment]
Same issue. It works sometimes, but I found no regularity. I'm using fresh Ubuntu 20.04 LTS with all VPNs or proxies turned off.

**Comment by PopChicken** [comment]
Seems like the DNS service didn't auto-fallback for an unknown name. Everything works with DNS created by Telepresence specified.

**Comment by Ethan-99** [comment]
> Seems like the DNS service didn't auto-fallback for an unknown name. Everything works with DNS created by Telepresence specified.

@PopChicken Can you elaborate on how you specified to use DNS created on Telepresence if that solved the issue on your machine?

**Comment by PopChicken** [comment]
**For Ubuntu**, try to edit /etc/resolv.conf. You can first use the command `resolvectl status` to see your DNS list and find whether the DNS of Telepresence was created.
However, Telepresence won't fall back too. All DNS resolutions will be invalid except Telepresence's.

**Comment by cindymullins-dw** [comment]
We've improved DNS resolution in recent releases and VPN compatibility can be checked with the [test-vpn command](https://www.getambassador.io/docs/telepresence/latest/reference/vpn#the-test-vpn-command).  If this issue persists on 2.11 please let us know.
