### ISSUE TITLE
`telepresence connect` fails - `failed to scan connector logs`

### ISSUE THREAD

**Issue by KimDoubleB** [telepresenceio/telepresence#2124]
**Describe the bug**

Hi. I have recently learned Telepresence and applied it to the development environment.

Currently, alpine linux are being used. I installed telepresence and executed the command `telepresence connect`, but the following error occurred.

```
❯ telepresence version
teClient: v2.4.4 (api v3)
lRoot Daemon: not running
User Daemon: not running

❯ telepresence status
Root Daemon: Not running
User Daemon: Not running

$ ~ ❯ telepresence connect
Launching Telepresence Root Daemon
telepresence: error: daemon service did not start: timeout while waiting for daemon to start
failed to scan connector logs: open /root/.cache/telepresence/logs/connector.log: no such file or directory
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue.

$ ~ ❯ cd /root/.cache/telepresence/logs/

$ ~/.cache/telepresence/logs ❯ ls
daemon-20211001T141059.log  daemon.log

$ ~/.cache/telepresence/logs ❯ cat daemon.log
2021-10-01 14:10:59.1820 info    Logging at this level "info"
2021-10-01 14:10:59.1822 info    ---
2021-10-01 14:10:59.1823 info    Telepresence daemon v2.4.4 (api v3) starting...
2021-10-01 14:10:59.1823 info    PID is 457
2021-10-01 14:10:59.1823 info
telepresence: error: failed to open TUN device /dev/net/tun: no such file or directory
```

There was no telepresence error for the same kubernetes environment in Mac Big Sur, not alpine linux.

Is it an error because telepresence don't support alpine linux?

- It seems to be similar to the problem that occurred [at the end of this issue](https://github.com/telepresenceio/telepresence/issues/1916#issuecomment-917202018)(#1916).

-----

**To Reproduce**
1. When I run `telepresence connect` at alpine linux
2. I see
```
Launching Telepresence Root Daemon
telepresence: error: daemon service did not start: timeout while waiting for daemon to start
failed to scan connector logs: open /root/.cache/telepresence/logs/connector.log: no such file or directory
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue.
```

**Expected behavior**
```
Launching Telepresence Daemon
...
Connected to context default (https://<cluster public IP>)
```

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
❯ telepresence version
teClient: v2.4.4 (api v3)
lRoot Daemon: not running
User Daemon: not running
```
Additionally, it was performed in telepresence version `2.3.7`/`2.4.0`/`2.4.1`/`2.4.2`/`2.4.3`, but an error occurred.

 - Operating system of workstation running `telepresence` commands
alpine linux `3.14.2`

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
v1.21.4 (vcluster in EKS)

**Comment by KimDoubleB** [comment]
I solved this problem through `Running Telepresence inside a container` among official documents. 
There must be a difference in the network kernel interface(`/dev/net/tun`). I've solved it, so I'll close the issue.

**Comment by openJT** [comment]
Only way I was able to run it was inside a container also... On a mac
https://www.getambassador.io/docs/telepresence/latest/reference/inside-container/
Thanks for the tip @KimDoubleB
