### ISSUE TITLE
Telepresence gather logs fails because telepresence itself fails

### ISSUE THREAD

**Issue by petermant** [telepresenceio/telepresence#2126]
Running telepresence 2.4.4 fails, so I tried running gather logs to add them to an existing issue which I was testing ([1916](https://github.com/telepresenceio/telepresence/issues/1916)).

Gather logs then fails with the same error as the telepresence command itself. Output and reproduction commands are below.

```
% telepresence connect --no-report
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /Users/pxmante/Library/Logs/telepresence '/Users/pxmante/Library/Application Support/telepresence' ''
Password:
Launching Telepresence User Daemon
Telepresence Root Daemon quitting... done
telepresence: error: connector.Connect: failed to start traffic manager: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/Users/pxmante/Library/Application Support/telepresence/config.yml"

See logs for details (3 errors found): "/Users/pxmante/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue.

% telepresence gather-logs
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Telepresence Root Daemon quitting... done
telepresence: error: error getting logs from kubernetes components: connector.Connect: failed to start traffic manager: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/Users/pxmante/Library/Application Support/telepresence/config.yml"

See logs for details (3 errors found): "/Users/pxmante/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue.
```

**Expected behavior**
The logs are collected without errors

**Versions (please complete the following information):**
 - Output of `telepresence version` **2.4.4**
 - Operating system of workstation running `telepresence` commands: **MacOS BigSur**
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine] **Docker desktop 3.6.0 with kubernetes 1.21.3**

**Comment by donnyyung** [comment]
Hey there, will try to improve this behavior but the command without any flags does try to collect logs from things in the cluster which does require the traffic-manager to be present (which seems like it the issue here).

In the meantime, if you use:
```
# Get all logs for the daemons only
telepresence gather-logs --traffic-agents=None --traffic-manager=False
```
It will get the logs from the daemons only.

**Comment by petermant** [comment]
That does help, certainly:

```
% telepresence gather-logs --traffic-agents=None --traffic-manager=False
Logs have been exported to /Users/pxmante/telepresence_logs.zip
```

Thanks. Perhaps it could catch the exception and fall back to operating if those options were selected.

**Comment by donnyyung** [comment]
Yup, that's what I'm going to add :) It will make it into our next release that will be happening next week.

**Comment by cindymullins-dw** [comment]
Closing as resolved.
