### ISSUE TITLE
Windows 10 DNS resolver works wrong

### ISSUE THREAD

**Issue by dmitriy0404** [telepresenceio/telepresence#2127]
**Steps to reproduce**

1. I connected to telepresence via `telepresence connect` command
2. I try to make a curl request to service1 (from default namespace) `curl http://service1` it fails because I need to specify the namespace
3. I try to make a curl request to service `curl http://service1.default` it passed
4. I intercept service2 (service1 and service2 are in default namespace) via the command `telepresence intercept service2 --port 80`
5. I try to make a curl request to service1 again but without specifying namespace `curl http://service1` it fails again

How can I configure DNS resolver to skip specifying default namespace after start intercepting?
I need it because in env variables of my service2 there is variable `Service1Url=http://service1` (I want to consume service1 from service2) how can I fix it?

**Versions:**

v2.4.4
Window 10

**Comment by andrewnazarov** [comment]
It looks quite similar to my issue(https://github.com/telepresenceio/telepresence/issues/2144). However, I'm on MacOS.

**Comment by tbocinec** [comment]
same problem on windows 10 in 2.8.5 version

**Comment by tbocinec** [comment]
same problem on windows 10 in 2.9.5 version

**Comment by cindymullins-dw** [comment]
Testing on Mac with 2.11, you don’t need to specify the namespace to access Service2 from Service1.  If it persists it might be a Windows issue.

**Comment by cindymullins-dw** [comment]
Please reopen if this issue persists on the latest version.
