### ISSUE TITLE
[v2] Windows 10 cli commands never terminate 

### ISSUE THREAD

**Issue by JuanRamino** [telepresenceio/telepresence#2132]
Hi,

After upgrading from 2.4.3 to 2.4.4 all commands used in CLI never terminate.
For example `telepresence version`  remains hanging.
Downgrade to 2.4.3 solve the issue.

Thanks

**Comment by thallgren** [comment]
@JuanRamino I'm not able to reproduce this on Windows with any of the versions. Can you please test with the latest version (2.4.9) and see if the problem persist?

**Comment by JuanRamino** [comment]
Thanks @thallgren but is hard to reproduce again because happens randomly.
I think it happens when telepresence processes doesn't close properly. I remember there were more then 4. Kill process let telepresence works again.
