### ISSUE TITLE
Can telepresence be made to work with Flagger?

### ISSUE THREAD

**Issue by edude03** [telepresenceio/telepresence#2133]
**Please describe your use case / problem.**
We use [flagger](https://flagger.app/) for canary deployments in staging and production, but in staging we use Telepresence for debugging. 

The problem is that both flagger and telepresence patch the service / deployment to work, and after they apply their patches telepresence doesn't work anymore. 

**Describe the solution you'd like**
There are two ways I can see this being solved: 

1) Is there a way to manually add traffic agent to the deployment? That way we could configure the ports and such to work correctly. 

2) I've tried injection with `telepresence.getambassador.io/inject-traffic-agent: enabled`, and I can't remember why right now (I'd have to reproduce it) but telepresence is unable to connect to the correct port inside the pod after injection and being deployed with flagger. 

I'm open to suggestions of course :)

**Comment by cindymullins-dw** [comment]
Hi @edude03 , is Flagger similar to Argo rollouts?  I don't find any past references w/regards to Telepresence. We've made improvements on how the traffic agent is injected.  More recent versions of Telepresence might work better for this.
