### ISSUE TITLE
After connect dns wont work. Lost all connection to cluster and Internet until quit.

### ISSUE THREAD

**Issue by andrey-gava** [telepresenceio/telepresence#2136]
**Describe the bug**
Traffic Manager installed with HELM:
`helm install --create-namespace  traffic-manager -n ambassador ./telepresence-2.4.4.tgz --set agentInjector.webhook.admissionReviewVersions="{v1,v1beta1}" --atomic --debug`

When run 
`telepresence connect `
it report that connected to cluster. But after that all dns query cant be resolved. Any kubectl commands to cluster timed out
Curl to cluster dns names return dns error
```
curl -ik https://kubernetes.default
curl: (6) Could not resolve host: kubernetes.default
```
Additionally I lost ability to open pages in Internet. Seems its somehow overlaps with my host network.
my routes
![изображение](https://user-images.githubusercontent.com/59727632/136209190-7bd9735c-041b-473c-bb94-e4ccc157f739.png)

**Expected behavior**
Expect to curl resources inside cluster and get response

**Versions (please complete the following information):**
 - Output of `telepresence version`
 Client: v2.4.4 (api v3)
 - Operating system of workstation running `telepresence` commands
 Ubuntu 18.04.5 LTS
 - Kubernetes environment and Version 
Server Version: v1.16.10 bare metal

[connector-20211006T161516.log](https://github.com/telepresenceio/telepresence/files/7294167/connector-20211006T161516.log)
[daemon-20211006T161516.log](https://github.com/telepresenceio/telepresence/files/7294169/daemon-20211006T161516.log)

**Comment by andrey-gava** [comment]
![изображение](https://user-images.githubusercontent.com/59727632/136214929-86d4cd07-c890-4af5-882f-8daecb75e977.png)

![изображение](https://user-images.githubusercontent.com/59727632/136214972-ae96d712-6db4-49b0-88a8-726795560cd8.png)
```
cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0
search cluster.local
```

**Comment by thallgren** [comment]
From the looks of it, the DNS server sends LookupHost requests to the traffic-manager that then times out. It would be interesting to see the log (with loglevel debug turned on) for the `traffic-manager` pod in the ambassador namespace.

**Comment by andrey-gava** [comment]
> From the looks of it, the DNS server sends LookupHost requests to the traffic-manager that then times out. It would be interesting to see the log (with loglevel debug turned on) for the `traffic-manager` pod in the ambassador namespace.

[connector.log](https://github.com/telepresenceio/telepresence/files/7321059/connector.log)
[daemon.log](https://github.com/telepresenceio/telepresence/files/7321060/daemon.log)
[pod.log](https://github.com/telepresenceio/telepresence/files/7321065/pod.log)

**Comment by andrey-gava** [comment]
And this one after full delete of traffic-manager helm package from cluster, and trying to connect from scratch 
[connector.log](https://github.com/telepresenceio/telepresence/files/7321109/connector.log)
[daemon.log](https://github.com/telepresenceio/telepresence/files/7321110/daemon.log)
[pod.log](https://github.com/telepresenceio/telepresence/files/7321111/pod.log)

**Comment by FedericoJurio** [comment]
Today I started with this same issue in MacOS

**Comment by thallgren** [comment]
The traffic-manager pod isn't able to resolve any of the lookups. It seems to go into a loop where the pod queries your workstation's DNS resolver (which would assume that your cluster is using the same DNS resolver as your workstation), which in turn sends the query to the pod. Could that be the case?

**Comment by andrey-gava** [comment]
@thallgren 
I'm not an expert in networks. 
As far as I can tell my laptop use the same DNS IP (nmcli device show "main_interface") as the K8S nodes in /etc/resolv.conf
My laptop use systemd-resolver.
K8S nodes doesn't use systemd-resolver.

And kubelet on nodes have in config this lines:
```
clusterDNS:
- 10.96.0.10
resolvConf: /etc/resolv.conf
```

But I don't understand how it matters? Doesn't DNS queries from my laptop should go to the traffic-manager pod which then must resolve it on kubernetes internal DNS?
By the way he can do it:
Inside traffic-manager pod 
```
nslookup kubernetes.default
Server:		10.96.0.10
Address:	10.96.0.10:53

nslookup google.com
Server:		10.96.0.10
Address:	10.96.0.10:53

Non-authoritative answer:
Name:	google.com
Address: 142.250.180.238

Non-authoritative answer:
Name:	google.com
Address: 2a00:1450:400d:80a::200e
```

**Comment by thallgren** [comment]
It's not entirely clear to me what your setup looks like. Are you running the cluster locally on your laptop? If so, then it would be at least theoretically possible that the Kubernetes DNS falls back to using your laptops DNS.

Can you do the `nslookup kubernetes.default` from the traffic-manager pod while telepresence is connected?

**Comment by andrey-gava** [comment]
> It's not entirely clear to me what your setup looks like. Are you running the cluster locally on your laptop? If so, then it would be at least theoretically possible that the Kubernetes DNS falls back to using your laptops DNS.
> 
> Can you do the `nslookup kubernetes.default` from the traffic-manager pod while telepresence is connected?

My cluster running on separate vm's in another subnet. 
After telepresence is connected I lost connection to cluster. Cluster API become unresponsive. Cant reach cluster API IP:PORT with telnet. I had try to do it from another host, but still no luck either.

**Comment by thallgren** [comment]
So, when telepresence is connected, you cannot reach your cluster from another host? That's very odd.

When you talk about separate VM's, are those VM's hosted on the same machine that runs telepresence? If so, what's the output of `ip a` on that host?

**Comment by andrey-gava** [comment]
I run telepresence cli on my laptop and connect to remote cluster(installed on vm's on standalone vspehere machine). And yes, after execute` telepresence connect` kubernetes api unreachable. 
More, I just tried to enter container from the node by doing `docker exec`, but cant do it either, because ssh connections wont work. Not just to k8s nodes, but what is strange to any host. So its not just DNS resolve problem, but network too (at least for ssh connections) 

And additionally I asked my coworker to try it from his laptop and he experience same problems.

**Comment by rzseattle** [comment]
Got the same symptoms. After the "telepresence connect" command computer losing connection with the kubernetes master node server. It's impossible to connect  via ssh or http. Even if I check user daemon it has the status "Not connected, error talking to cluster". After telepresence quit everything is getting back to a normal state.

**Comment by FedericoJurio** [comment]
From my side, I was able to fix it by upgrading everything in brew (`brew upgrade`) but the scenario could be different since I'm using a legacy version of telepresence (0.109). My guess is that an update in the system screwed the DNS resolution while using telepresence.

**Comment by andrey-gava** [comment]
I have an update. After upgrading to v2.4.6 part of functionality works
After execute `telepresence connect` ssh works and I can even `curl -ik https://kubernetes.default` which return the answer.
```
HTTP/2 403 
cache-control: no-cache, private
content-type: application/json
x-content-type-options: nosniff
content-length: 233
date: Wed, 03 Nov 2021 13:24:06 GMT

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
```
But I can only curl svc by its IP despite nslookup of this svc are resolves successful.
```
$nslookup product-catalog.default.svc.cluster.local
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	product-catalog.default.svc.cluster.local
Address: 10.97.146.218

$ curl product-catalog.default.svc.cluster.local:8080/api/health/ping
curl: (6) Could not resolve host: product-catalog.default.svc.cluster.local

$ curl 10.97.146.218:8080/api/health/ping
{"data":{"pong":"OK","name":"Project 'artifact id' not found","version":"Project 'version' not found","commit":null,"host":"10.44.0.5","profiles":"[prod]","timestamp":null}}
```
[connector.log](https://github.com/telepresenceio/telepresence/files/7467862/connector.log)
[daemon.log](https://github.com/telepresenceio/telepresence/files/7467863/daemon.log)

Intercept by svc dns name works without issue.

**Comment by cindymullins-dw** [comment]
We suggest upgrading to a recent version to take advantage of improved functionality.  Please let us know if issues persist.
