### ISSUE TITLE
Can't download Telepresence CLI for Linux, SSL_ERROR_ZERO_RETURN

### ISSUE THREAD

**Issue by joelhoisko** [telepresenceio/telepresence#2139]
**Describe the bug**
I tried to install the Telepresence CLI as per the [docs](https://www.telepresence.io/docs/latest/howtos/intercepts/). I tried to download the binary with the supplied `curl` command, but nothing downloads and it fails with `SSL_ERROR_ZERO_RETURN`:
```shell
$ sudo curl -fL https://app.getambassador.io/download/tel2/linux/amd64/latest/telepresence -o /usr/local/bin/telepresence

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   105  100   105    0     0      4      0  0:00:26  0:00:24  0:00:02    26
  0     0    0     0    0     0      0      0 --:--:--  0:00:48 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to datawire-static-files.s3.amazonaws.com:443 
```

**To Reproduce**
1. When I run `sudo curl -fL https://app.getambassador.io/download/tel2/linux/amd64/latest/telepresence -o /usr/local/bin/telepresence
`
2. I see `curl: (35) OpenSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to datawire-static-files.s3.amazonaws.com:443`

**Expected behavior**

The `curl` command to successfully download the binary.

**Versions (please complete the following information):**
 - Ubuntu 20.04
 - `curl --version`:
 `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`

**Comment by joelhoisko** [comment]
Actually it just started to download for a bit, but then stopped. It seems to be going up and down.
![image](https://user-images.githubusercontent.com/10163775/136367768-b4fe6e74-84bd-4a61-bfbf-92c988f26a48.png)

**Comment by cindymullins-dw** [comment]
We don't think this is happening on newer versions, but if you find otherwise please reopen.
