### ISSUE TITLE
Add an option to disable public/tcp intercept 

### ISSUE THREAD

**Issue by rishinair19** [telepresenceio/telepresence#2140]
**Please describe your use case / problem.**

We're looking to implement telepresence but have a concern that running services will be impacted by mistake. Basically, we want to disable the public intercept which intercepts all requests. I’m aware that we can login to telepresence and create a personal intercept but we're worried that a user might just forget to login and interrupt the service completely

**Describe the solution you'd like**

Any way we can ensure that the user will not be able to create an intercept without logging in?

**Describe alternatives you've considered**

None till now

**Versions (please complete the following information)**

Client: v2.4.3 (api v3)
Root Daemon: v2.4.3 (api v3)
User Daemon: v2.4.3 (api v3)
Kuberenetes version: 1.18

**Comment by thallgren** [comment]
Closed by #2832 and released in Telepresence 2.8.3.
