### ISSUE TITLE
DNS resolution failure

### ISSUE THREAD

**Issue by velykanov** [telepresenceio/telepresence#2142]
Hello everyone!

I'm not sure if that's a bug but feels like it is.

I'm trying to send a grpc query from code which I'm debugging in intellij to another pod in cluster which always fails with the same "DNS resolution error".
Telepresence status however shows networking to the cluster is enabled:
```
Root Daemon: Running
  Version   : v2.4.3 (api 3)
  DNS       :
    Remote IP       : 10.96.0.10
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 4s
  Also Proxy: (0 subnets)
User Daemon: Running
  Version           : v2.4.3 (api 3)
  Ambassador Cloud  : Logged out
  Status            : Connected
  Kubernetes server : https://192.168.99.102:8443
  Kubernetes context: minikube
  Telepresence proxy: ON (networking to the cluster is enabled)
  Intercepts        : 1 total
    <service>-<namespace>: mykyta.velykanov@mvelykanov-PC
```

I'm intercepting service using the following command (was also playing with `--context` and `--cluster` flags but nothing seems to differ):
`telepresence intercept <service> --namespace <namespace> --env-json tele.json`

The query I'm trying to execute is toward the url in a form `<pod_name>.<service_name>.<namespace>` which is unreachable from the code I'm debugging (and also unreachable with `telepresence connect -- curl <URL>` but it resolves IP address correctly) but is reachable if I perform `kubectl exec -it <pod> -- curl <URL>` (this conforms to what's written here https://github.com/telepresenceio/telepresence/issues/560#issuecomment-380558420).

That makes me think `intercept` function does only one way traffic interception (from other services inside cluster to the service which I'm debugging but not sending request back to the cluster from the service).

STR:
1. start minikube
2. `telepresence connect`
3. `telepresence intercept <service> --namespace <namespace> --env-json tele.json`
4. run code in debug mode in intellij using envplugin with env vars from tele.json file
5. perform action to send grpc call to other pod
6. get "DNS resolution failed" error

I'm using
```
minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5
```

Again, I'm not sure if that's a bug or lack of flags I'm using to intercept a service. Anyways I'd love to hear some feedback on that since I'm struggling for more that a week to find an answer..

I was also checking prior versions of telepresence (0.1.0.9) which contains `--local-cluster` flag that should resolve this DNS resolution failure (as per help description) but it's not.

**Comment by thallgren** [comment]
Would it be possible for you to try the 2.4.4 release, turn on debug logging with `telepresence loglevel debug` and then gather all logs using the `telepresence gather-logs` command?

**Comment by velykanov** [comment]
Sure, I'll upgrade tp and will share logs early next week

**Comment by velykanov** [comment]
Good day @thallgren 
Can you please tell me if there is a way to increase maximum message size?
`telepresence gather-logs` command throws the following error `telepresence: error: error getting logs from kubernetes components: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8133251 vs. 4194304)` and size of logs is growing and I cannot even send you a gathered zip file

**Comment by thallgren** [comment]
@velykanov you can try setting [maxReceiveSize](https://www.telepresence.io/docs/latest/reference/config/#grpc) to something larger and see if that helps.
@donnyyung I think we might want to consider sending splitting large logs into a stream of messages.

**Comment by velykanov** [comment]
@thallgren after finding that pod needs to have `telepresence.getambassador.io/inject-traffic-agent: enabled` annotation I've tried once again and that didn't help yet

Please find file with gathered logs here https://mega.nz/file/Q6pQVBCC#zqR3oznzKyQ7ojI1hg17R8609c41xJvFuQ8AhUXDx4o

**Comment by velykanov** [comment]
Hi @thallgren, sorry for bothering you but I wonder if there is some kind of solution you can provide me with in this case?

**Comment by jiezhang0917** [comment]
Same issue here. And my logs look similar to velykanov's.

**Comment by thallgren** [comment]
I believe this DNS issue has since been resolved.
