### ISSUE TITLE
[v2] Can't resolve DNS names during telepresence intercept and after telepresence leave

### ISSUE THREAD

**Issue by andrewnazarov** [telepresenceio/telepresence#2144]
**Describe the bug**
I can't resolve any DNS names after doing a successful intercept. Neither `<service_name>` nor `<service_name>.<namespace_name>` can't be resolved. All curl requests end up with a `Could not resolve host` error. In addition, the DNS resolution of `<service_name>.<namespace_name>` doesn't work even after `telepresence leave`.

**To Reproduce**
Initially after doing `telepresence connect` I can resolve DNS names as stated in docs, i.e. `<service_name>.<namespace_name>`. Then I want to intercept my service. I'm doing `telepresence intercept ...` and DNS resolution stops working for both `<service_name>` as it is supposed to be and for `<service_name>.<namespace_name>` as well.

```
> curl devops-iris-backend.devops:8080/actuator/health
curl: (6) Could not resolve host: devops-iris-backend.devops
```
Even if I drop the interception the resolution will fail. To be able to resolve `<service_name>.<namespace_name>` names again I have to do `telepresence quit` and then `telepresence connect again`.

```
❯ telepresence connect --mapped-namespaces devops
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context ...

❯ curl devops-iris-backend.devops:8080/actuator/health
{
  "status" : "UP",
  "groups" : [ "liveness", "readiness" ]
}

❯ telepresence intercept notifications --port 8080:http --env-file notif.cloud.env
Using Deployment notifications
intercepted
    Intercept name         : notifications
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:8080
    Service Port Identifier: http
    Volume Mount Error     : macFUSE 4.0.5 or higher is required on your local machine
    Intercepting           : all TCP connections

❯ telepresence list
...
notifications                       : intercepted
    Intercept name         : notifications
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:8080
    Service Port Identifier: http
    Intercepting           : all TCP connections
    
❯ curl devops-iris-backend:8080/actuator/health
curl: (6) Could not resolve host: devops-iris-backend

❯ telepresence leave notifications

❯ curl devops-iris-backend.devops:8080/actuator/health
curl: (6) Could not resolve host: devops-iris-backend.devops
```

**Expected behavior**
<service_name> resolved during `telepresence interceprt`. After `telepresence leave` DNS resolution of `<service_name>.<namespace_name>` should still work

**Versions (please complete the following information):**
 - telepresence v2.4.4
 - MacOS Mojave 10.14.5
 - GKE 1.20.9-gke.1001

**Comment by thallgren** [comment]
The fact that you need to restart telepresence makes me suspect that the DNS cache isn't flushing correctly. Did this behavior change from 2.4.3 to 2.4.4?

**Comment by andrewnazarov** [comment]
@thallgren I haven't tried 2.4.3. I skipped some versions and started playing with the most recent.

**Comment by andrewnazarov** [comment]
It seems that v2.4.7 doesn't have this problem. I'm looking forward to getting this working.
