### ISSUE TITLE
Telepresence intercept times out [v2.4.5]

### ISSUE THREAD

**Issue by linnal** [telepresenceio/telepresence#2163]
This started with the new version, in 2.4.4 it was working. 
I am able to connect to my local kubernetes cluster. When I do intercept it times out, I increased the configuration timeout to 2m but it did not change anything. 

```
> telepresence connect 
Launching Telepresence User Daemon
Connected to context docker-desktop (https://kubernetes.docker.internal:6443)

> telepresence intercept myservice --port 4000:4000
telepresence: error: Failed to establish intercept: the agent install timed out.  The current timeout 2m0s can be configured as "timeouts.agentInstall" in "/Users/XXXX/Library/Application Support/telepresence/config.yml"

See logs for details (126 errors found): "/Users/XXXX/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

Even though telepresence times out, the agent is being created and this is the logs:
```
2021-10-20 08:44:38.7988 info    Logging at this level "info"
2021-10-20 08:44:38.7989 info    Traffic Agent v2.4.5 [pid:1]
2021-10-20 08:44:38.7990 info    {Name:myservice Namespace:sbs PodIP:10.1.0.66 AgentPort:9900 AppMounts:/tel_app_mounts AppPort:4000 ManagerHost:traffic-manager.ambassador ManagerPort:8081}
2021-10-20 08:44:38.7996 info    new agent secrets mount path: /var/run/secrets/kubernetes.io
2021-10-20 08:44:38.8039 info    client : Connected to Manager 2.4.5
```

Telepresence connector Logs
```
2021-10-20 09:55:57.0502 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = NotFound desc = session "6b4d45c6-c8e3-41f0-be85-d9bb476a12b2" not found
2021-10-20 09:55:59.5129 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "6b4d45c6-c8e3-41f0-be85-d9bb476a12b2" not found
2021-10-20 09:56:00.0569 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = NotFound desc = session "6b4d45c6-c8e3-41f0-be85-d9bb476a12b2" not found
2021-10-20 09:56:00.0569 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = NotFound desc = session "6b4d45c6-c8e3-41f0-be85-d9bb476a12b2" not found
```

**Versions (please complete the following information):**
 - Output of `telepresence version` **v2.4.5**
 - Operating system of workstation running `telepresence` commands **MACOS Big Sur 11.5.2**
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine] **K8s Docker Desktop v1.21.2**

Config.yaml
```
timeouts:
  intercept: 1m
  proxyDial: 30s
  trafficManagerConnect: 30s
  trafficManagerAPI: 30s
logLevels:
  userDaemon: debug
```

**Comment by luminoso** [comment]
I have the same behavior, but using Fedora Linux.

The connection hang starts to happen inside the cluster too, containter-to-cointainer, not just on the from the "remote" telepresence to the cluster

**Comment by jiezhang0917** [comment]
Same issue here. I'm using `ambassador-telepresence-agent:1.11.3` as the traffic agent image. My telepresence versions are:
Root Daemon: v2.4.4 (api v3)
User Daemon: v2.4.4 (api v3)

**Comment by josecv** [comment]
hi @linnal could you share some more logs please? it'd be great if you could do something like the following:

```
telepresence loglevel debug

# Run your intercept command

telepresence gather-logs --output-file /tmp/telepresence_logs.zip
```
And then upload the `telepresence_logs.zip` file


It looks as though the local end is disconnecting from the cluster (hence the `session "6b4d45c6-c8e3-41f0-be85-d9bb476a12b2" not found` errors), so i'd like to get some more info on why that's happening

**Comment by jiezhang0917** [comment]
> Same issue here. I'm using `ambassador-telepresence-agent:1.11.3` as the traffic agent image. My telepresence versions are: Root Daemon: v2.4.4 (api v3) User Daemon: v2.4.4 (api v3)

I didn't realize that the traffic manager of mine is on version 2.4.5. So I downgraded it to 2.4.4 and then intercept timeout issue was resolved. Thanks for @josecv's help from the telepresence channel.

**Comment by rchenzheng** [comment]
I'm having the same problems with `Client: v2.4.10 (api v3)`

**Comment by thallgren** [comment]
It would be really helpful if someone having this problem with `v2.4.10` could follow @josecv's advice above and attach some logs here.

**Comment by thallgren** [comment]
I encountered [this issue](/kubernetes/minikube/issues/13370) when using `minikube` because the agent will indeed call the pod's own service. The problem went away when I started minikube with `--cni=bridge`.

**Comment by rchenzheng** [comment]
My issues went away after I forcefully uninstalled the agent and restarted the daemon in MacOS Monterey.

**Comment by Messhias** [comment]
> My issues went away after I forcefully uninstalled the agent and restarted the daemon in MacOS Monterey.

It's not a solution, it's a workaround. I'm on OSX too, in theory, we should not be forced to uninstall everything, restart services e, etc...

Sounds like we're dealing with a windows default software.

**Comment by thallgren** [comment]
@Messhias you're dealing with a fairly new technology that is evolving rapidly and we try our best to prioritise to meet our users needs. There's no doubt room for improvement in the area of updating, and we will address that. Meanwhile, I'd like to point out that "windows default software" rarely is open source that you can use, free of charge, _and_ contribute to. So if you think there are areas that can be improved, we are very happy to accept contributions ;-)

**Comment by cindymullins-dw** [comment]
Closing this issue for lack of logs/data to investigate.  Please feel free to reopen if the issue persists.
