### ISSUE TITLE
Telepresence DNS resolution fails in containers run with --docker-run in WSL2

### ISSUE THREAD

**Issue by actualrockstar** [telepresenceio/telepresence#2167]
**Describe the bug**
When running a Telepresence intercept with the `--docker-run` flag in WSL2, all cluster-based DNS resolution fails. Containers run with `--docker-run` are not able to perform outbound service calls. 

**To Reproduce**
1. In WSL2 Ubuntu terminal, I ran `telepresence connect`.
2. I ran `telepresence intercept {service} -p 8080 --docker-run -- -it --rm alpine`
3. Then `apk add curl`
4. Finally I ran `curl https://kubernetes.default:443` and get:
```curl: (6) Could not resolve host: kubernetes.default:443```

**Expected behavior**
Expecting to get a 401 unauthorized error or some response that shows we're able to contact the API, but getting _could not resolve host_ error. 

**Versions (please complete the following information):**
- Telepresence version:
```
telepresence version
An update of telepresence from version 2.4.4 to 2.4.5 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client: v2.4.4 (api v3)
Root Daemon: v2.4.4 (api v3)
User Daemon: v2.4.4 (api v3)
```
- kubernetes version: Kubeception
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17+k3s1", GitCommit:"e8c9484078bc59f2cd04f4018b095407758073f5", GitTreeState:"clean", BuildDate:"2021-01-14T22:16:57Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.17) exceeds the supported minor version skew of +/-1
```
-Windows 10, WSL2 Ubuntu 20.04

**Additional context**
Most relevant logs are from 10/20/2021: [telepresence_logs1.zip](https://github.com/telepresenceio/telepresence/files/7383633/telepresence_logs1.zip)

**Comment by cindymullins-dw** [comment]
Telepresence should work with the `--docker-run` flag.  Please reopen if issue persists on newer versions.
