### ISSUE TITLE
`telepresence leave` doesn't recognize an intercepted service shown in `telepresence list`

### ISSUE THREAD

**Issue by Nitaym** [telepresenceio/telepresence#2174]
**Describe the bug**
Telepresence is intercepting a service on the cluster, but it seems that there is no way to stop the interception 
`telepresence leave map-proxy` returns that there is no intercept named map-proxy.

See attached image:
![image](https://user-images.githubusercontent.com/19125/138889101-cf619223-6c79-445e-9f76-2b377eabe693.png)

I ended up reinstalling the cluster (luckily it's not a big issue) to remove any telepresence containers and changes.

**reproduce the error**
I can't upload the logs due to business disclosure, but we can do a screen share and look at the logs together.

**Expected behavior**

`telepresence leave` should stop the interception

**Versions (please complete the following information):**
 - Output of `telepresence version`:
Client: v2.4.5 (api v3)
Root Daemon: v2.4.5 (api v3)
User Daemon: v2.4.5 (api v3)
 
 - Operating system of workstation running `telepresence` commands
macOC Big Sur 11.6

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
k3s v1.18.3+k3s1

**Additional context**

**Comment by Nitaym** [comment]
I think I found the issue. It seems my Root & User Daemon were running on a previous version, and did not update. 
I've ran `telepresence version` after I restarted my computer.

I did not manage to restore the cluster though.


Maybe add a feature request to verify that versions match when running any telepresence command.

**Comment by thallgren** [comment]
Adding a version match check is a good idea so I created #2198.
