### ISSUE TITLE
telepresence leave or quit does not clean up the container that's brought up with --docker-run when intercept

### ISSUE THREAD

**Issue by jiezhang0917** [telepresenceio/telepresence#2178]
**Describe the bug**
I usually run telepresence intercept with a docker container by attaching `--docker-run` option. The issue is when quit telepresence or leave an intercept, it doesn't cleanup the container that's running automatically. 

**To Reproduce**
1. Run telepresence intercept with `--docker-run` option.
2. Then leave the intercept or just do telepresence quit
3. Check your containers that's running with `docker ps`. You'll still see the intercept container running.

**Expected behavior**
Telepresence quit or leave should automatically cleanup the running container that's brought by telepresence intercept.

**Versions (please complete the following information):**
 - Root Daemon: v2.4.4 (api v3), User Daemon: v2.4.4 (api v3)
 - Macos Bigsur (intel)
 - EKS

**Comment by thallgren** [comment]
A normal invocation using `--docker-run` should not be followed by a `telepresence leave` or `telepresence quit`. It ends when the container run ends. A `telepresence leave` (presumably from another terminal?) will leave the docker container running. This is consistent with how telepresence handles any other local process that acts as an interceptor.

Example:
This command will intercept `myscv` and start the docker container `myapp:latest`. The run will remain active until it is terminated by a `<ctrl>-C`:
```
$ telepresence intercept mysvc --docker-run --port 9070:8080 -- --rm -v /Users/myappfolder:/usr/src/app myapp:latest
Using Deployment echo-easy
intercepted
    Intercept name         : mysvc
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:9070
    Service Port Identifier: proxied
    Intercepting           : all TCP connections

```
Hit a `<ctrl>-C` and the following happens:
```
^Creceived signal interrupt (triggering graceful shutdown)
telepresence: error: docker run --dns-search tel2-search --env-file /tmp/tel-4193215487.env --name intercept-mysvc-9070 -p 9070:8080 --rm -v /Users/myappfolderr:/usr/src/app myapp:latest: exited with 1
```
A subsequent `docker ps` shows that the container is no longer running.

**Comment by thallgren** [comment]
I can see two improvements that would help with this issue.
1. Improve the documentation. Add an example that shows how to use <ctrl>-C
2. Ensure that the error exit doesn't prompt the user to look in the daemon and connector log files.
