### ISSUE TITLE
Unable to intercept traffic

### ISSUE THREAD

**Issue by mouniraboud** [telepresenceio/telepresence#2190]
1. when I do telepresence intercept xxxxx -n xxxxxx --port 9081:http --env-file <FILE>--mount=false
2. the traffic is not getting intercepted at all  (it used to run with the same command but suddenly it stopped) 
1. When I run 'telepresence uninstall --everything'
2. I see 'telepresence: error: 1 error occurred:
        * Deployment name="xxxx" namespace="xxxxx": unable to locate port "tm-http" in container "xxxxx"'
3. So I did the telepresence leave <interceptor-name> and deleted the ns and still this is happening 

**Expected behavior**
being able to uninstall --everything and the intercept to work as expected 

**Versions (please complete the following information):**
 - Telepresence version: 2.4.5
 - OS:Windows
 - EKS

**Comment by thallgren** [comment]
What does `telepresence list` show after the first step? Do you see anything of interest in the logs?

(` --env-file --mount=false` looks odd as `--env-file` requires an argument, but I guess you forgot to write that).

**Comment by mouniraboud** [comment]
I managed to make work again but i still think there is a bug in telepresence 
I edited deployment yaml file deleted the side car manually than re-intercept it worked fine but still have no idea why this happened

**Comment by thallgren** [comment]
I'm closing this ticket since there's no information here that we can act on. Feel free to reopen it with more details around the problem if it happens again. If you're uncertain that you've encountered a bug, please join #telepresence on our [Slack channel](https://datawire-oss.slack.com/).

**Comment by mouniraboud** [comment]
> What does `telepresence list` show after the first step? Do you see anything of interest in the logs?
> 
> (` --env-file --mount=false` looks odd as `--env-file` requires an argument, but I guess you forgot to write that).

the list give the interceptor that i create and seems to be working fine but when I hit the svc it is not sending the traffic to my pc and yeah i m including the path in the command 
as i said i managed to solve the issue but in a weird way
