### ISSUE TITLE
Outgoing connection stalls indefinitely when particular service has not been contacted in over 60 seconds, subsequent connection succeeds

### ISSUE THREAD

**Issue by rkrzewski** [telepresenceio/telepresence#2193]
I am very impressed with Telepresence and it's really great when it works, alas it does not work reliably for me. My initial observation was that some time after running `telepresence connect` some requests to te services in the cluster start to fail, but issuing a couple retires usually fixes the problem for some time. Running `telepresence quit; telepresence connect` also temporarily fixes the problem. I was able to distill it down to the following scenario:

- `telepresence connect`
- access a service in the clustrer (request succeeds)
- wait > 60 seconds
- observe that `error   connector/server-grpc/conn=2 : Tunnel manager.Send() failed: EOF` appears in `connector.log`
- try accessing the same service again (request stalls and eventually times out)
- access the service the third time (request succeeds)
- wait > 60 seconds
- access the service again (request stalls and times out)

I have verified that using port-forward directly does not exhibit this problem: repeated requests to the service succeed, even with >60s delays between them.

Please find the attached logs: [telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7462073/telepresence_logs.zip)

Telepresence version: 2.4.5 for both server (installed through Helm) and client.
Cluster is 1 node microk8s v1.20.11, running on Ubuntu 20.04.2 LTS, Linux x86_64 5.4.0-81-generic. I tried on another microk8s cluster - same problem.
Client machine is Ubuntu 20.04.3 LTS, Linux x86_64 5.4.0-88-generic. My coworkers using Windows machines had same connectivity problems.

This sounds like variation of #1993 but version 2.4.5 should already have the fix for this problem.

**Comment by thallgren** [comment]
I'm looking at the logs and I see that the service that Telepresence connects to closes the connection after 60 seconds. The traffic-manager log shows this line:
```
2021-11-02 15:30:13.4451 debug   httpd/conn=127.0.0.1:8081 :    CONN tcp 10.152.183.0:42146 -> 10.152.183.228:80 conn-to-stream loop ended because EOF was encountered
```
The conn-to-stream loop reads from the connection and writes things on the stream that sends the message to your workstation.

In essence, this means that the peer closed the connection. So that raises the question, what is it that you are connecting to? Does that service have an idle timeout of some sort?

**Comment by rkrzewski** [comment]
In this particular instance the server was a HTTP service, more precisely JAX-RS endpoint in a Wildfly server, and the client was Postman (API testing tool). I suppose the connection might stay open because of HTTP/1.1 pipelining, but I highly doubt that Postman is using that, since modern browsers don't.

I was trying to find the simplest reproduction, but my experience with Telepresence on my local microk8s cluster so far is that all connectivity is that nothing works reliably. For example, when pushing a Docker image to the registry running in the cluster, first one or two layers are pushed successfully, but the pushing other layer stalls and timeouts. Running `telepresence quit; telepresence connect` allows pushing one more layer, then it stalls again. I've had stalling connections with various other HTTP services than I tried. Another thing is that sometimes DNS resolution over Telepresence also failed after a while after connecting: I saw the query succeeding in traffic-manager logs, but I was getting a NXDOMAIN on client side after a 4s timeout. Unfortunately the logs were really messy because I was trying ton of different stuff, and then I wasn't able to reproduce it cleanly.

I see great value in Telepresence and I would love to use it with my team. I am willing to put time and effort into resolving this issue, just tell me how can I help you in helping me!

**Comment by thallgren** [comment]
@rkrzewski Here are a couple of things that you could try.
1. Install the new 2.4.6 release (released yesterday). It contains modifications that might be significant if you run a local API server.
2. Directly after `telepresence connect`, and before you try accessing the service, enter `telepresence loglevel trace`. This will result in an abundance of network related logging in the `daemon.log` and the logs of the `traffic-manager-xxx` pod that might be helpful (it will reveal things like TCP keep-alive polls). The logging will be active for 30 minutes by default (can be controlled using `--duration <duration>` where duration is something like 10s, 1m30s, etc.

Your help is very much appreciated.

**Comment by rkrzewski** [comment]
I did an update to 2.4.6 and tried reproduce the bug I've encountered earlier.
There seems to be an improvement because I was able to push images to docker images in the cluster without problems, which was failing really badly before. I did the test in the office over LAN, and I'll retry it from home over a VPN to check if that is a factor.
However I as able to reproduce the problem with connection to a HTTP service stalling after leaving telepresence idle for a while.
[telepresence_logs_1.zip](https://github.com/telepresenceio/telepresence/files/7474857/telepresence_logs_1.zip) minimal reproduction (1st request, delay, 2nd request stalls, 3rd request succeeds)
[telepresence_logs_3.zip](https://github.com/telepresenceio/telepresence/files/7474861/telepresence_logs_3.zip) a larger log with more services and more requests
I've used `trace` log level as suggested.

**Comment by thallgren** [comment]
Judging from the logs, the client sends TCP keep-alive probes every second. The dialer in the traffic-manager that we forward to will send such probes every 15 second, so it's hard to understand why the service decides to disconnect after 60 seconds. Is there anyway you can find out at what rate the service needs the keep-alives to stay happy and not close the connection?

I have no problem keeping a connection idle and alive for a longer duration than 60 seconds as long as the service isn't closing it.
```console
$ kubectl create deploy echo --image jmalloc/echo-server
deployment.apps/echo created
$ kubectl expose deploy echo --port 80 --target-port 8080
service/echo exposed
$ telepresence connect
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context default (https://127.0.0.1:6443)
$ REQ="GET / HTTP/1.1\nHost: echo.default\nAccept: *\n\n"
(echo -ne $REQ; sleep 70; echo -ne $REQ) | netcat echo.default 80
```
works fine and the same connection is reused for both requests.
```

**Comment by rkrzewski** [comment]
Initially I was confused about the TCP keep-alives you wrote about, because I had a mistaken belief that modern browsers don't use use a  single TCP connection for sending multiple HTTP requests to the server (HTTP `Connection: keep-alive`). Browsers actually do that, and what they don't use, is HTTP pipelining ie sending a sequence of multiple HTTP requests over a TCP socket without waiting for a response to each in turn.

Next, the flood of TCP keepalives you've seen in the log is a feature (?) of Postman https://github.com/postmanlabs/postman-app-support/issues/4574 that thankfully can be disabled manually on per-request basis.

Knowing the above, I moved on to more realistic testcase: issuing the requests with Chrome browser. I also used Wireshark to monitor traffic on `tel0` interface to get a better picture of what was happening. The following archive contains `tel0.pcap` file with the packet dump. [telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7487626/telepresence_logs.zip) 

The test went as follows: I've invoked the service once, waited >60s (Chrome issued a TCP keep-alive at 45s mark), invoked the service the second time: the request stalled. I can see the request going out and being ACKed but the response does not come back. After some time I've pressed stop button in chrome (I can see the connection is FINed) and then refreshed the tab in Chrome again: a new connection is opened, request is sent and response arrives propmptly.

For comparison, I've disconnected Telepresence, exposed the same service at `localhost:8080` using `kubectl port-forward` and tried to replicate the above scenario. I can see the keep-alives issued by Chrome, but all of the requests succeed. Here's a packet dump od that session: [port-forward.zip](https://github.com/telepresenceio/telepresence/files/7487787/port-forward.zip)

Because Chrome can talk to the service using persistent connections over k8s port-forwad, I still suspect that something is amiss inside Telepresence. I'm a bit out of my depth here, but here's a question: assuming that it's the remote service is closing the connection on it's side, should Telepresence send a FIN on RST packet to the client? I'm not seeing this in the packet dump. The client thinks the connection is still open and issues next request using the same port number and it's getting lost somewhere. Another question: if the remote service is ignoring the 15s keep-alives sent by TrafficManager and closing the connection from it's side, why doesn't it do that when Chrome is talking to it over a port-forward and issuing 45s keep-alives?

**Comment by rkrzewski** [comment]
I took another look at the packet dumps attached above, and I think that there's some merit to my hypothesis that Telepresence does not forward the information about remote service closing the connection to the client.

First of all, the remote service is running on Wildfly, and the HTTP component, undertow does close connections afer 60s of inactivity. I believe that `no-request-timeout` property of [`http-listener`](https://docs.wildfly.org/25/wildscribe/subsystem/undertow/server/http-listener/index.html) controls this.

When looking at `port-forward.pcap` I can see 8080 => 42170 [FIN, ACK] packet that I understand is the signal that Wildlfy/Undertow closed the connection on it's end, meanwhile looking `tel0.pcap` I see no such packet arriving from Telepresence at 68s mark (60s after the original request). The connection only is closed at 154s from Chrome's end when I clicked stop button in.

 @thallgren, please tell me what you think.

**Comment by thallgren** [comment]
@rkrzewski I'll look into this first thing on Monday. Great research!

**Comment by wasd171** [comment]
We encountered a similar issue but with Node.js: connection get closed on one side but it's not propagated via telepresence, subsequent reconnections work. PR https://github.com/telepresenceio/telepresence/pull/2202 seems to fix it!

**Comment by rkrzewski** [comment]
Can I test this change using a nightly build? I was looking at the docs but it's not clear to me how to discover which nightly builds are published (what is the git hash), also https://www.telepresence.io/docs/latest/install/ mentions installing the client, but I have installed TrafficManager using Helm. All I was able to find is an open issue https://github.com/telepresenceio/telepresence.io/issues/56 for the website...
