### ISSUE TITLE
Optional image flag for connect command

### ISSUE THREAD

**Issue by Danny-m08** [telepresenceio/telepresence#2194]
**Please describe your use case / problem.**
Being behind corporate VPN often prohibits the ability to pull from dockerhub. To get around this we must log off VPN, pull from dockerhub, push the image to an docker registry internal to corporate proxy and use this image tag. This feature request is to support an optional --image flag to telepresence connect command in order for us to specify which image we want to deploy telepresence with.

**Describe the solution you'd like**
Telepresence connect will have an optional --image flag and deploy the pod with this image.

**Describe alternatives you've considered**
Manually deploying telepresence using the helm chart. Though this can be tedious and can be immediately resolved with this optional flag

**Versions (please complete the following information)**
Client: v2.4.2 (api v3)
Root Daemon: v2.4.2 (api v3)
User Daemon: not running

**Comment by cindymullins-dw** [comment]
The Helm chart is the norm for the traffic manager deployment but it is now more straightforward.  You can specify an image in the Docker registry and pass in the values you need to pull the image from that registry.  You can also use the Telepresence command or Helm install command.
