### ISSUE TITLE
kuma support

### ISSUE THREAD

**Issue by mayaaravotwm** [telepresenceio/telepresence#2206]
hello,
we have kong ingress as our ingress controller on our aws eks cluster, and kuma as our service mesh - we have kuma sidecar added to each pod in the namespace.

whenever we intercept a service (without preview url), we can access only the local service from outside and not the remotely. 
is there a way that we can intercept the local service with some header (or something else) so we can still use the remote service without interrupting other developers? 

in addition, when we tried to use the preview url we get this error: 
telepresence: error: Failed to establish intercept: intercept in error state NO_AGENT: Agents for "cryptosamlsigner" are not consistent

the logs are attached.
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7498459/telepresence_logs.zip)

what can we do?

**Comment by cindymullins-dw** [comment]
You might get that error if the agent was injected in one session then perhaps another session was started and got out of sync.  Reinstalling the traffic agent should help.  [Personal intercepts](https://www.getambassador.io/docs/telepresence/latest/concepts/intercepts#personal-intercept) would be the solution for using the remote service without interrupting other devs.
