### ISSUE TITLE
Telepresence fail to connect to traffic manager gRPC timed out

### ISSUE THREAD

**Issue by guillaumed-unity** [telepresenceio/telepresence#2207]
Facing an issue trying to use telepresence on a GKE Cluster:
When  Running `telepresence --connect`
Telepresence fails to establish the gRPC connection with the Traffic Manager.

I can confirm that the traffic manager and ambassador namespace are correctly deployed in the cluster.

I looked around the docs but did not find anything related to that issue

The GKE cluster is only accessible by connecting to a VPN which is connected when trying to connect to the cluster via Telepresence

[connector.log](https://github.com/telepresenceio/telepresence/files/7500977/connector.log)

**Comment by jagitch** [comment]
I install socat on every k8s node solved this problem
`yum install -y socat`

**Comment by cindymullins-dw** [comment]
We believe this issue to be resolved.  Please reopen if it persists on newer versions.
