### ISSUE TITLE
Failing to swap (macOs Big Sur 11.6, Tele 0.108)

### ISSUE THREAD

**Issue by TomerG2** [telepresenceio/telepresence#2208]
### What were you trying to do?

Tried swapping a pod.

### What did you expect to happen?

Swap successfully. 

### What happened instead?

The telepresence fails to swap

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--context', 'dev', '--expose', '80', '--swap-deployment', 'backend']`
Version: `0.108`
Python version: `3.7.7 (default, Dec 27 2020, 16:49:33) 
[Clang 12.0.0 (clang-1200.0.26.2)]`
kubectl version: `Client Version: v1.21.3 // Server Version: v1.19.14-gke.1900`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin tgolan-macos.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64`

```
Background process (SSH port forward (exposed ports)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 50396 telepresence@127.0.0.1 -R '*:3000:127.0.0.1:3000' -R '*:9020:127.0.0.1:9020' -R '*:80:127.0.0.1:80'


Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 50396 telepresence@127.0.0.1 -L127.0.0.1:50410:127.0.0.1:9050 -R9055:127.0.0.1:50411

```

Logs:

```
| Listening...
  81.4  20 | 2021-11-10T10:10:30+0000 [-] Loading ./forwarder.py...
  81.4  20 | 2021-11-10T10:10:32+0000 [-] /etc/resolv.conf changed, reparsing
  81.4  20 | 2021-11-10T10:10:32+0000 [-] Resolver added ('10.22.0.10', 53) to server list
  81.4  20 | 2021-11-10T10:10:32+0000 [-] SOCKSv5Factory starting on 9050
  81.4  20 | 2021-11-10T10:10:32+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f5fb8305400>
  81.4  20 | 2021-11-10T10:10:32+0000 [-] DNSDatagramProtocol starting on 9053
  81.4  20 | 2021-11-10T10:10:32+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f5fb83056d8>
  81.4  20 | 2021-11-10T10:10:32+0000 [-] Loaded.
  81.4  20 | 2021-11-10T10:10:32+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 20.3.0 (/usr/bin/python3.6 3.6.8) starting up.
  81.4  20 | 2021-11-10T10:10:32+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.

```

**Comment by TomerG2** [comment]
I noticed the issue occurs only when I'm connected to my home Wifi,
If I use my iPhone's hotspot the swap works.

Note: 
I've doubled checked my home wifi has an internet connection with good speeds (250Mbs D/50Mbs U)

**Comment by VitalyArt** [comment]
@TomerG2 Hi, where did you download version 0.108 or older? I can't find. Please share

**Comment by cindymullins-dw** [comment]
Closing as Version 1 is no longer supported. If you have similar issue or question on recent versions of Telepresence please let us know.
