### ISSUE TITLE
Handle path redirect, path regex

### ISSUE THREAD

**Issue by BogdanAndreiRoman** [telepresenceio/telepresence#2216]
**Please describe your use case / problem.**
I'm using Ambassador Stack Edge Hello with the name of the branch as a context URL (example.com/feature1/web/, example.com/feature2/web/) and do path_redirect, this breaks traffic agent routing and Telepresence can't be used.

AES mapping example:                                                                                                              
getambassador.io/config: |
              ---
              apiVersion: ambassador/v2
              kind: Mapping
              name: webapi-redirect
              prefix: /development/webapi
              service: mydomain.westeurope.cloudapp.azure.com
              prefix_regex: true
              host_redirect: true
              path_redirect: /development/webapi/
              ---
              apiVersion: ambassador/v2
              kind: Mapping
              name: webapi
              prefix: /development/webapi/
              service: webapi.development

**Describe the solution you'd like**
Intercepts are working without eliminating the path_redirect, prefix_regex from the service mapping. 
**Describe alternatives you've considered**
I've tried intercepting at different levels: on the ingress service (ambassador.ambassador) and at the service level (webapi.development) using the preview url method and also the change of the headers without success.

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)
Client: v2.4.6 (api v3)
Root Daemon: v2.4.6 (api v3)
User Daemon: v2.4.6 (api v3)
  - Kubernetes Environment and Version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
AKS
**Additional context**
Add any other context about the feature request here.

**Comment by cindymullins-dw** [comment]
Sorry to have not responded on this issue and thanks for reporting.  If still relevant, we'd be interested to know the commands used and errors received in more detail.  Does 'telepresence list' show the Service?
