### ISSUE TITLE
Panic on slice bounds out of range

### ISSUE THREAD

**Issue by chongkai** [telepresenceio/telepresence#2225]
**Describe the bug**
Telepresence intercept terminates unexpectedly, and this panic is seen in the daemon.log:

panic: runtime error: slice bounds out of range [:28275] with capacity 1520
goroutine 845 [running]:
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.Header.Payload(...)
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/header.go:57
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).writeLoop(0xc000025b60, {0x2d72228, 0xc0004ebc80})
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:122 +0x6be
created by github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).Start
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:99 +0xbd

**Comment by patrick-steadman** [comment]
I'm having the same issue, were you able to resolve or work around this issue @chongkai ?

```
panic: runtime error: slice bounds out of range [:26990] with capacity 1520

goroutine 202 [running]:
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.Header.Payload(...)
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/header.go:57
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).writeLoop(0x140002816e0, {0x10405a480, 0x14000644900})
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:122 +0x698
created by github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).Start
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:99 +0x88
```

**Comment by ptsteadman** [comment]
I'm having the same issue, were you able to resolve or work around this issue @chongkai ?

```
panic: runtime error: slice bounds out of range [:26990] with capacity 1520

goroutine 202 [running]:
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.Header.Payload(...)
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/header.go:57
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).writeLoop(0x140002816e0, {0x10405a480, 0x14000644900})
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:122 +0x698
created by github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).Start
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:99 +0x88
```

**Comment by klerick** [comment]
I have this problem too.
```
panic: runtime error: slice bounds out of range [:28015] with capacity 1520

goroutine 271 [running]:
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.Header.Payload(...)
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/header.go:57
github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).writeLoop(0xc0007605f0, {0x5e76720, 0xc000399580})
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:106 +0x531
created by github.com/telepresenceio/telepresence/v2/pkg/vif/udp.(*handler).Start
        github.com/telepresenceio/telepresence/v2/pkg/vif/udp/handler.go:87 +0xbd
```

I get it randomly. When try to get some data from external service such us db or http service.

**Comment by carlos19960601** [comment]
same issue

**Comment by francoisminaud** [comment]
@thallgren may I reopen this issue?
This was reproduced today using Telepresence v2.6.8

I believe there is no sensitive information in the daemon.log so here it goes.
For information the machine is a mac, not sure if you are interested in particular information about the hw/sw etc?

[daemon.log](https://github.com/telepresenceio/telepresence/files/9377402/daemon.log)

Let me know if I should open another issue instead and thanks again for the great product.
