### ISSUE TITLE
Issue running telepresence

### ISSUE THREAD

**Issue by levitomer** [telepresenceio/telepresence#2234]
### What were you trying to do?

run `bin/tele tomerlevi-dev --swap-deployment tomerlevi-dev-web-api`

### What did you expect to happen?

running telepresence with `--swap-deployment tomerlevi-dev-web-api`

### What happened instead?

use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'tomerlevi-dev', '--also-proxy', 'D96BC27839D53442386F257B2A194993.gr7.us-east-1.eks.amazonaws.com', '--also-proxy', 'tomerlevi-dev-api.dev.internal.bigpanda.io', '--also-proxy', 'tomerlevi-dev.dev.internal.bigpanda.io', '--swap-deployment', 'tomerlevi-dev-web-api']`
Version: `0.109`
Python version: `3.9.7 (default, Oct 13 2021, 06:45:31) 
[Clang 13.0.0 (clang-1300.0.29.3)]`
kubectl version: `Client Version: v1.21.5 // Server Version: v1.20.7-eks-d88609`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin tlevi-MacBookPro 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 71, in main
    env, pod_info = get_remote_env(runner, ssh, remote_info)
  File "/usr/local/bin/telepresence/telepresence/remote_env.py", line 38, in get_remote_env
    pod_info = loads(json_data)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
27.0.0.1 -L127.0.0.1:62485:127.0.0.1:9050 -R9055:127.0.0.1:62486
  30.4  14 | Handling connection for 62454
  30.4 TEL | END SPAN connect.py:37(connect)    5.9s
  30.4 TEL | BEGIN SPAN remote_env.py:29(get_remote_env)
  30.4 TEL | [35] Capturing: kubectl --context dev-us-east-1 --namespace tomerlevi-dev exec tomerlevi-dev-web-7cd9e9afd53f4c23b4d176cff61b470c --container web-api -- python3 podinfo.py
  30.4  14 | Handling connection for 62454
  39.9 TEL | [36] Running: sudo -n echo -n
  39.9 TEL | [36] ran in 0.04 secs.
  51.3 TEL | (proxy checking local liveness)
  70.0 TEL | [37] Running: sudo -n echo -n
  70.0 TEL | [37] ran in 0.05 secs.
  81.3 TEL | (proxy checking local liveness)
 100.1 TEL | [38] Running: sudo -n echo -n
 100.1 TEL | [38] ran in 0.04 secs.
 107.9  13 | 2021-11-23T09:44:56+0000 [Poll#info] Checkpoint
 107.9  13 | 2021-11-23T09:45:26+0000 [Poll#info] Checkpoint
 108.1 TEL | [35] captured in 77.70 secs.
 108.1 TEL | END SPAN remote_env.py:29(get_remote_env)   77.7s

```

**Comment by cindymullins-dw** [comment]
Closing as Version 1 is no longer supported.  If you have similar issue or question on recent versions of Telepresence please let us know.
