### ISSUE TITLE
Switch to newer detect-Docker-host-IP mechanism on Mac

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#224]
Currently on OS X we add a special IP alias to `lo0` loopback interface, so that Docker containers can find the `kubectl port-forward` port when using `--method container`. Newer versions of Docker support a special DNS record `docker.for.mac.localhost` instead (this may obviate need for root, while we're at it.)

See https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds

We can't use this mechanism immediately since it's only present in absolute latest version of Docker, but eventually could switch.

**Comment by ark3** [comment]
Something like 

    docker run --rm -it --entrypoint "" $TELEPRESENCE_LOCAL_IMAGE nslookup docker.for.mac.localhost

should be pretty quick to query; the exit status is sufficient to know whether `docker.for.mac.localhost` is usable.

**Comment by ark3** [comment]
The latest (edge) release makes this a bit more complicated. The release notes say:

> DNS name `docker.for.mac.host.internal` shoud be used instead of `docker.for.mac.localhost` (still valid) for host resolution from containers, since since there is an RFC banning the use of subdomains of localhost (See https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06).

**Comment by ark3** [comment]
[Newest release notes](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18030-ce-rc1-mac54-2018-02-27-edge) say

> DNS name `host.docker.internal` shoud be used for host resolution from containers. Older aliases (still valid) are deprecated in favor of this one.

**Comment by ark3** [comment]
If they ever fix https://github.com/docker/for-linux/issues/264, we could avoid the `route -n` nonsense entirely.

**Comment by ark3** [comment]
Fixing this will move us closer to Windows support for the container method.

**Comment by duizendnegen** [comment]
Indications for possible solutions are https://dev.to/bufferings/access-host-from-a-docker-container-4099

**Comment by ark3** [comment]
Telepresence 0.95 includes #726, and thus does not try to connect to the host from within the container. As such, this is no longer an issue. Closing.
