### ISSUE TITLE
Config.yaml configuration not applied

### ISSUE THREAD

**Issue by s1apped** [telepresenceio/telepresence#2242]
**Describe the bug**
Intercept timeouts every time.

>  Failed to establish intercept: the apply timed out.  The current timeout 1m0s can be configured as "timeouts.apply" in "/Users/test/Library/Application Support/telepresence/config.yml"

I have updated the config.yaml with below but it's not working. I have deleted everything and started from scratch but intercept still times out after default 2m

![image](https://user-images.githubusercontent.com/32245059/143833376-fc6469c5-c59e-46ae-8e56-1dacffd9f863.png)

**Versions (please complete the following information):**

Client: v2.4.4 (api v3)
Root Daemon: v2.4.4 (api v3)
User Daemon: v2.4.4 (api v3)
macOS Monterey
k3d version v5.1.0

**Comment by thallgren** [comment]
Could it be that you're using "config.yaml" instead of "config.yml" as the message suggests?
