### ISSUE TITLE
[v2] A network outage or sleep mode during telepresence intercept makes all Internet addresses unreachable

### ISSUE THREAD

**Issue by andrewnazarov** [telepresenceio/telepresence#2245]
**Describe the bug**
Basically, if I disconnect from the network or get into sleep mode, all Internet network addresses will become unreachable until I do `telepresence quit`. As a side effect, the intercepting also stops working.

**To Reproduce**
1. Run `telepresence intercept my_service --port my_port`
2. Go to the sleep mode or disconnect from the network
3. Get connected again or go back to the normal mode
4. Visit any site or try to reach any Internet address

**Expected behavior**
All Internet addresses resolvable and reachable. Not sure about intercepting, it would be great to have it working (also see [!2244](https://github.com/telepresenceio/telepresence/issues/2244))

**Versions (please complete the following information):**
telepresence version
Client: v2.4.7 (api v3)
Root Daemon: v2.4.7 (api v3)
User Daemon: v2.4.7 (api v3)

MacOS Mojave 10.14.5
GKE 1.21.5-gke.1802

**Comment by saaryehudai** [comment]
We've also experienced this behavior.

Some additional context about what happens after a network disconnection:
1. When invoking `telepresence status`, everything seems to be connected.
2. Invoking `telepresence list` shows all my intercepts as if they are active.
3. Connecting to services with fully-qualified names works (e.g. `<service>.<namespace>`)

**Comment by thallgren** [comment]
Fixed by #2545.
