### ISSUE TITLE
Have to use --kubeconfig ~/.kube/config with all commands

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#2249]
I need to use `--kubeconfig ~/.kube/config` with all commands.

And in "telepresence connect"  if I dont use  "--kubeconfig ~/.kube/config" I get:
`telepresence: error: connector.Connect: initial cluster check failed: the server has asked for the client to provide credentials`

So I keep adding "--kubeconfig ~/.kube/config":
`telepresence connect --kubeconfig ~/.kube/config`
`telepresence list --kubeconfig ~/.kube/config`

etc?

**Comment by josecv** [comment]
@JCzz do you have a `$KUBECONFIG` environment variable set, and if so is it set to something different than `~/.kube/config`?

**Comment by JCzz** [comment]
@josecv 

Yes, I do have multiple files in my $KUBECONFIG like:

echo $KUBECONFIG
`~/.kube/config:~/.kube/ubuntu_local:~/.kube/ubuntu_internet`

I have tried making `~/.kube/config` only containing my local KinD cluster - but same result.

**Comment by josecv** [comment]
oh interesting, I don't think we have any logic to handle cases with multiple kubeconfigs, so that's probably what's causing this

**Comment by thallgren** [comment]
Perhaps somehow related to what we see in #2425 ?

**Comment by cindymullins-dw** [comment]
@JCzz , looks like this issue was addressed in [v2.6.1](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.6.1).   Please let us know if it doesn't work for you.
