### ISSUE TITLE
Deployment already being used for intercept with a different service - Knative

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#2252]
Env:
telepresence version
```
Client: v2.4.8 (api v3)
Root Daemon: v2.4.8 (api v3)
User Daemon: v2.4.8 (api v3)
```

kubectl version --short
```
Client Version: v1.22.2
Server Version: v1.21.1

```

# Trying to intercept Knative service

curl http://helloworld-go.default.127.0.0.1.sslip.io
Hello Hello Knative Serving is up and running with Kourier!!!

```
apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: helloworld-go # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go # The URL to the image of the app
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Hello Knative Serving is up and running with Kourier!!"
```

telepresence list
```
telepresence list                                              
helloworld-go-tj7sc-deployment: ready to intercept (traffic-agent not yet installed)

```

intercept
```
telepresence intercept helloworld-go-tj7sc-deployment --port=5050:8080
telepresence: error: Failed to establish intercept: Deployment already being used for intercept with a different service
configuration. To intercept this with your new configuration, please use
telepresence uninstall --agent helloworld-go-tj7sc-deployment This will cancel any intercepts that
already exist for this service: Deployment name="helloworld-go-tj7sc-deployment" namespace="default": port changed from "80" to "8080"

See logs for details (2 errors found): "/Users/christian/Library/Logs/telepresence/daemon.log"

See logs for details (607 errors found): "/Users/christian/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

Tried:
```
telepresence uninstall --agent helloworld-go-tj7sc-deployment
telepresence: error: unable to find a workload named helloworld-go-tj7sc-deployment.default with an agent installed

```
Ok  checked, as it says it is already in use  running, so I try to run the following on my local machine in the same terminal.
```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", HelloServer)
	http.ListenAndServe(":5050", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello, %s!", r.URL.Path[1:])
}
```

But it still returns the same:
```
curl http://helloworld-go.default.127.0.0.1.sslip.io
Hello Hello Knative Serving is up and running with Kourier!!!

```

Note: the intercepted port 5050:8080 as the deployment shows: ` PORT:                      8080`

Also tried to intercept --port=5050:80 as the deployment says 
kubectl describe deployment helloworld-go-tj7sc-deployment 
Name:                   helloworld-go-tj7sc-deployment
Namespace:              default
CreationTimestamp:      Sat, 04 Dec 2021 17:54:07 +0100
Labels:                 app=helloworld-go-tj7sc
                        serving.knative.dev/configuration=helloworld-go
                        serving.knative.dev/configurationGeneration=1
                        serving.knative.dev/revision=helloworld-go-tj7sc
                        serving.knative.dev/revisionUID=f601d971-a250-4e66-a202-099ac1ab8418
                        serving.knative.dev/service=helloworld-go
Annotations:            deployment.kubernetes.io/revision: 7
                        serving.knative.dev/creator: kubernetes-admin
                        telepresence.getambassador.io/actions:
                          {"version":"2.4.8","ReferencedService":"helloworld-go-tj7sc-private","referenced_service_port":"80","referenced_service_port_name":"http",...
Selector:               serving.knative.dev/revisionUID=f601d971-a250-4e66-a202-099ac1ab8418
Replicas:               0 desired | 0 updated | 0 total | 0 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=helloworld-go-tj7sc
                serving.knative.dev/configuration=helloworld-go
                serving.knative.dev/configurationGeneration=1
                serving.knative.dev/revision=helloworld-go-tj7sc
                serving.knative.dev/revisionUID=f601d971-a250-4e66-a202-099ac1ab8418
                serving.knative.dev/service=helloworld-go
  Annotations:  serving.knative.dev/creator: kubernetes-admin
  Containers:
   user-container:
    Image:      gcr.io/knative-samples/helloworld-go@sha256:5ea96ba4b872685ff4ddb5cd8d1a97ec18c18fae79ee8df0d29f446c5efe5f50
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      TARGET:                    Hello Knative Serving is up and running with Kourier!!
      PORT:                      8080
      K_REVISION:                helloworld-go-tj7sc
      K_CONFIGURATION:           helloworld-go
      K_SERVICE:                 helloworld-go
      K_INTERNAL_POD_NAME:        (v1:metadata.name)
      K_INTERNAL_POD_NAMESPACE:   (v1:metadata.namespace)
    Mounts:
      /var/log from knative-var-log (rw)
   queue-proxy:
    Image:       gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:713bd548700bf7fe5452969611d1cc987051bd607d67a4e7623e140f06c209b2
    Ports:       8022/TCP, 9090/TCP, 9091/TCP, 8012/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Requests:
      cpu:      25m
    Readiness:  exec [/ko-app/queue -probe-period 0] delay=0s timeout=10s period=1s #success=1 #failure=3
    Environment:
      SERVING_NAMESPACE:                      default
      SERVING_SERVICE:                        helloworld-go
      SERVING_CONFIGURATION:                  helloworld-go
      SERVING_REVISION:                       helloworld-go-tj7sc
      QUEUE_SERVING_PORT:                     8012
      CONTAINER_CONCURRENCY:                  0
      REVISION_TIMEOUT_SECONDS:               300
      SERVING_POD:                             (v1:metadata.name)
      SERVING_POD_IP:                          (v1:status.podIP)
      SERVING_LOGGING_CONFIG:                 {
                                                "level": "info",
                                                "development": false,
                                                "outputPaths": ["stdout"],
                                                "errorOutputPaths": ["stderr"],
                                                "encoding": "json",
                                                "encoderConfig": {
                                                  "timeKey": "ts",
                                                  "levelKey": "level",
                                                  "nameKey": "logger",
                                                  "callerKey": "caller",
                                                  "messageKey": "msg",
                                                  "stacktraceKey": "stacktrace",
                                                  "lineEnding": "",
                                                  "levelEncoder": "",
                                                  "timeEncoder": "iso8601",
                                                  "durationEncoder": "",
                                                  "callerEncoder": ""
                                                }
                                              }
      SERVING_LOGGING_LEVEL:                  
      SERVING_REQUEST_LOG_TEMPLATE:           
      SERVING_REQUEST_METRICS_BACKEND:        prometheus
      TRACING_CONFIG_BACKEND:                 none
      TRACING_CONFIG_ZIPKIN_ENDPOINT:         
      TRACING_CONFIG_STACKDRIVER_PROJECT_ID:  
      TRACING_CONFIG_DEBUG:                   false
      TRACING_CONFIG_SAMPLE_RATE:             0.1
      USER_PORT:                              8080
      SYSTEM_NAMESPACE:                       knative-serving
      METRICS_DOMAIN:                         knative.dev/internal/serving
      DOWNWARD_API_LABELS_PATH:               /etc/podinfo/labels
      SERVING_READINESS_PROBE:                {"tcpSocket":{"port":8080,"host":"127.0.0.1"},"successThreshold":1}
      ENABLE_PROFILING:                       false
      SERVING_ENABLE_PROBE_REQUEST_LOG:       false
    Mounts:                                   <none>
  Volumes:
   knative-var-log:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   helloworld-go-tj7sc-deployment-648cc6fb47 (0/0 replicas created)
Events:
  Type    Reason             Age                   From                   Message
  ----    ------             ----                  ----                   -------
  Normal  ScalingReplicaSet  132m                  deployment-controller  Scaled up replica set helloworld-go-tj7sc-deployment-66b49676bd to 1
  Normal  ScalingReplicaSet  132m                  deployment-controller  Scaled down replica set helloworld-go-tj7sc-deployment-66b49676bd to 0
  Normal  ScalingReplicaSet  116m (x10 over 164m)  deployment-controller  Scaled up replica set helloworld-go-tj7sc-deployment-648cc6fb47 to 1
  Normal  ScalingReplicaSet  114m (x10 over 163m)  deployment-controller  Scaled down replica set helloworld-go-tj7sc-deployment-648cc6fb47 to 0
  Normal  ScalingReplicaSet  108s (x5 over 15m)    deployment-controller  Scaled up replica set helloworld-go-tj7sc-deployment-648cc6fb47 to 1
  Normal  ScalingReplicaSet  17s (x5 over 14m)     deployment-controller  Scaled down replica set helloworld-go-tj7sc-deployment-648cc6fb47 to 0

## Logs: (cat /Users/<user>/Library/Logs/telepresence/connector.log )...
```
2021-12-05 18:52:09.5169 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found
2021-12-05 18:52:09.9345 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = NotFound desc = session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found
2021-12-05 18:52:09.9345 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = NotFound desc = session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found
2021-12-05 18:52:12.9439 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = NotFound desc = session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found
2021-12-05 18:52:12.9466 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = NotFound desc = session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found
2021-12-05 18:52:14.5199 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found
2021-12-05 18:52:15.9545 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = NotFound desc = session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found
2021-12-05 18:52:15.9598 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = NotFound desc = session "be63ffcf-1cc1-4dd1-bfd9-97c866ff2dc9" not found

```

**Comment by cindymullins-dw** [comment]
Hi @JCzz, it may be the issue was [addressed here](https://github.com/telepresenceio/telepresence/issues/2120) and is not Knative specific.  Does this persist on newer versions of Telepresence?

**Comment by dsyer** [comment]
I don't think this issue was addressed. Definitely not working for me anyway, and I'd almost be suspicious if it did, but I'd like to be able to intercept a Knative service.

**Comment by cindymullins-dw** [comment]
Hi @JCzz , Hi @dsyer , this may have been a problem with the intercept cleanup, which has been improved in more recent versions.  We doubt this would happen now, unless there’s a Knative-specific problem we're not aware of.  
Would you mind upgrading and trying again?  It'd be great to know if this is still happening.
