### ISSUE TITLE
Connection hands after inspect

### ISSUE THREAD

**Issue by 0x2C6** [telepresenceio/telepresence#2261]
**Describe the bug**
On the M1 MacBook pro sometimes when connecting to telepresence it blocks all the network activity. You can even cant curl to inner services or use browsers connections as well. when it happens, telepresence-related commands also hang (ex: telepresence list). But it's definitely there is no issue with internet connectivity. Have the same problem with one of my coworkers as well. Sorry, will not provide any logs. If I get anything helpful I will put the log here

**Versions (please complete the following information):**
 2.4.8

**Comment by cindymullins-dw** [comment]
Hi @0x2C6, we've made a lot of improvements to Telepresence over the past year.  If you find this persists on a more recent version please let us know.
