### ISSUE TITLE
Compatibility with KIND ( kind.sigs.k8s.io )

### ISSUE THREAD

**Issue by raphaelauv** [telepresenceio/telepresence#2262]
**Please describe your use case / problem.**

is telepresence compatible with local kubernetes : KIND ?

https://github.com/kubernetes-sigs/kind/issues/2571

**Describe the solution you'd like**

I would like to acces a service inside KIND

**Versions (please complete the following information)**

Client: v2.4.9 (api v3)
Root Daemon: v2.4.9 (api v3)
User Daemon: v2.4.9 (api v3)

Thank you

**Comment by thallgren** [comment]
I can't see why it shouldn't be compatible. Have you tried using it?

This issue tracker intended for bug reports and feature requests. If you have questions about Telepresence, I recommend you to use our [Slack](https://a8r.io/slack).
