### ISSUE TITLE
connecting to my telepresence dev deployment failed

### ISSUE THREAD

**Issue by ChardyT** [telepresenceio/telepresence#2263]
### What were you trying to do?
i was trying to connect t o my dev environment 
(please tell us)

### What did you expect to happen?
i was expecting to start my project
(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'terajobapi-bossia', '--docker-run', '-p', '19011:19011', '-e', 'MONGO_CLUSTER_URL=mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/terajobapidev\xa0', '--rm', '-it', '-v', '/home/bossia/Documents/JA_CONSULTING/back-end/terajobapi:/usr/src/app', '--name', 'terajobapi', 'terajobapi']`
Version: `0.109`
Python version: `3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.22.4 // Server Version: v1.19.14-gke.1900`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux bossia-VivoBook-ASUSLaptop-X712EA-S712EA 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 44867 telepresence@127.0.0.1 -L127.0.0.1:42377:127.0.0.1:9050 -R9055:127.0.0.1:33069

```

Logs:

```
ce@127.0.0.1 /bin/true
  48.8  44 |    0.5 TEL | [4] exit 255 in 0.01 secs.
  49.0  44 |    0.8 TEL | [5] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 38023 telepresence@127.0.0.1 /bin/true
  49.0  44 |    0.8 TEL | [5] exit 255 in 0.01 secs.
  49.3  44 |    1.0 TEL | [6] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 38023 telepresence@127.0.0.1 /bin/true
  49.3  44 |    1.0 TEL | [6] exit 255 in 0.00 secs.
  49.6  44 |    1.3 TEL | [7] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 38023 telepresence@127.0.0.1 /bin/true
  49.6  44 |    1.3 TEL | [7] exit 255 in 0.01 secs.
  49.8  44 |    1.5 TEL | [8] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 38023 telepresence@127.0.0.1 /bin/true
  49.8  44 |    1.5 TEL | [8] exit 255 in 0.00 secs.

```

**Comment by cindymullins-dw** [comment]
HI @ChardyT, have you tried the new version of Telepresence available [here](https://www.getambassador.io/docs/telepresence/latest/quick-start)?  We're closing this issue as v1 is no longer supported.
