### ISSUE TITLE
Can't connect to mysql in k8s cluster

### ISSUE THREAD

**Issue by beyonderyue** [telepresenceio/telepresence#2264]
**Describe the bug**
telepresence: 2.4.9
k8s: 1.21.0
mysql in k8s: 5.7.32

After telepresence connect, I try to connect mysql locally with navicat, but I can't connect it

**To Reproduce**
1 Deploy mysql in k8s, and mysql works well
2 telepresence connect to k8s
3 Try to connect to mysql using navicat locally
4 Always timeout

**Expected behavior**
connect to mysql in k8s using local navicat

**Versions (please complete the following information):**
 - telepresence 2.4.9
 - Windows10
 - k8s:1.21.0

[Uploading telepresence_logs.zip…]()

**Comment by thallgren** [comment]
@beyonderyue you made a mistake with the upload. The link to the logs just point right back to this ticket.

**Comment by thallgren** [comment]
How does navicat connect to mysql? What URL does it use?

**Comment by beyonderyue** [comment]
> How does navicat connect to mysql? What URL does it use?

I use the service IP address or internal domain name.

**Comment by beyonderyue** [comment]
I create a service and endpoint is mysql outside, I use navicat to connect the svc,  maybe not the problem of tele2, so I close this issue.

**Comment by ofey404** [comment]
I encounter this problem too.

I use the service name: `mysql-primary-headless.default`

```
telepresence version
Client             : v2.14.2
Root Daemon        : v2.14.2
User Daemon        : v2.14.2
OSS Traffic Manager: v2.14.4
```

I suspect the issue roots in MySQL's protocol - It use TCP rather than HTTP

**Comment by thallgren** [comment]
Telepresence will normally use TCP unless you're trying to use personal intercepts on the mysql service. Is the subnet that this service uses part of your cluster? Or is it a service that is external to your cluster? If so, you might want to look at the [alsoProxySubnets](https://www.getambassador.io/docs/telepresence/latest/reference/config#alsoproxysubnets) setting.
