### ISSUE TITLE
crash during telepresence swap command 

### ISSUE THREAD

**Issue by MichZem** [telepresenceio/telepresence#2267]
### What were you trying to do?

telepresence --swap-deployment csp-onboarding --namespace ara-csp-mzamir --expose 8210:8210 --run-shell --method inject-tcp

### What did you expect to happen?

to debug from IDEA (intelliJ) 

### What happened instead?

It crashed  .... 

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'csp-onboarding', '--namespace', 'ara-csp-mzamir', '--expose', '8210:8210', '--run-shell', '--method', 'inject-tcp']`
Version: `0.109`
Python version: `3.9.9 (main, Nov 21 2021, 03:23:42) 
[Clang 13.0.0 (clang-1300.0.29.3)]`
kubectl version: `Client Version: v1.19.7 // Server Version: v1.19.9+vmware.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin mzamir-a01.vmware.com 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  54.7 TEL | [110] exit -11 in 0.07 secs.
  54.9 TEL | [111] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  54.9 TEL | [111] exit -11 in 0.08 secs.
  55.0 TEL | [112] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  55.1 TEL | [112] exit -11 in 0.07 secs.
  55.2 TEL | [113] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  55.3 TEL | [113] exit -11 in 0.08 secs.
  55.4 TEL | [114] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  55.5 TEL | [114] exit -11 in 0.08 secs.
  55.6 TEL | [115] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  55.7 TEL | [115] exit -11 in 0.08 secs.
  55.7 TEL | END SPAN local.py:42(set_up_torsocks)   15.0s

```

**Comment by MichZem** [comment]
Seems  similar to  https://github.com/telepresenceio/telepresence/issues/1501 (MacOS Big Sur inject-tcp method does not work) but I dont find any workaround 

My OS version is Mac Bis Sur 11.6.2

**Comment by cindymullins-dw** [comment]
Hi @MichZem , version 1 of Telepresence is no longer supported. You can upgrade to the latest version using [the steps noted here](https://www.getambassador.io/docs/telepresence/latest/install/upgrade).
