### ISSUE TITLE
telepresence: error: remote volume mounts are disabled: sshfs is not installed on your local machine

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#2270]
telepresence  arm64 MacOs 12.1 version
```
Client: v2.4.9 (api v3)
Root Daemon: v2.4.9 (api v3)
User Daemon: v2.4.9 (api v3)

```

Mount not working
```
telepresence intercept micro-one --port 8080:http --mount=true 
telepresence: error: remote volume mounts are disabled: sshfs is not installed on your local machine

```

Tried installing MAcFusion 
Manually from: https://osxfuse.github.io
brew:  brew install macFUSE

Do you know how to get this working?

Thanks - Telepresence is awesome

**Comment by thallgren** [comment]
You need to install `gromgit/fuse/sshfs-mac`. Take a look at our [troubleshooting guide](https://www.telepresence.io/docs/latest/troubleshooting/) under heading "Volume mounts are not working on macOS".

Feel free to reopen if that doesn't solve your problem.
