### ISSUE TITLE
context

### ISSUE THREAD

**Issue by ksmiller-dispatch** [telepresenceio/telepresence#2284]
### What were you trying to do?

trying to swap a service to point to my local box.  the last. thing i did was add the '--context' option, before that it was gracefully exiting
### What did you expect to happen?

the service should have pointed to my machine

### What happened instead?
I got this stack trace back immediately. 

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/Telepresence', '--swap-deployment', 'travel-reporting-service', '--context', 'dev-01']`
Version: `0.109`
Python version: `3.9.9 (main, Nov 21 2021, 03:23:44) 
[Clang 13.0.0 (clang-1300.0.29.3)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Admins-MacBook-Pro-3.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/Telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/Telepresence/telepresence/main.py", line 42, in main
    set_kube_command(runner, args)
  File "/usr/local/bin/Telepresence/telepresence/startup.py", line 145, in set_kube_command
    for context_setting in kubectl_config["contexts"]:
TypeError: 'NoneType' object is not iterable

```

Logs:

```
   0.0 TEL | Telepresence 0.109 launched at Thu Jan  6 16:56:30 2022
   0.0 TEL |   /usr/local/bin/Telepresence --swap-deployment travel-reporting-service --context dev-01
   0.0 TEL | uname: uname_result(system='Darwin', node='Admins-MacBook-Pro-3.local', release='21.2.0', version='Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64', machine='x86_64')
   0.0 TEL | Platform: darwin
   0.0 TEL | WSL: False
   0.0 TEL | Python 3.9.9 (main, Nov 21 2021, 03:23:44)
   0.0 TEL | [Clang 13.0.0 (clang-1300.0.29.3)]
   0.0 TEL | BEGIN SPAN main.py:40(main)
   0.0 TEL | BEGIN SPAN startup.py:83(set_kube_command)
   0.0 TEL | Found kubectl -> /usr/local/bin/kubectl
   0.0 TEL | [1] Capturing: kubectl --context dev-01 version --short
   0.2   1 | error: context "dev-01" does not exist
   0.2 TEL | [1] exit 1 in 0.15 secs.
   0.2 TEL | [2] Capturing: kubectl --context dev-01 config view -o json
   0.2 TEL | [2] captured in 0.04 secs.



```

**Comment by cindymullins-dw** [comment]
Hi @ksmiller-dispatch , version 1 of Telepresence is no longer supported. You can upgrade to the latest version using [the steps noted here](https://www.getambassador.io/docs/telepresence/latest/install/upgrade).
