### ISSUE TITLE
Allow to specify container, from which env vars should be imported during intercept

### ISSUE THREAD

**Issue by petr-buchin** [telepresenceio/telepresence#2292]
**Please describe your use case / problem.**
I have a pod that consisting from 2 containers - `nginx` and `php-frpm`.
I'd like to intercept calls to service behind this pod and have env variables from `php-fpm` container.
`php-fpm` container itself does not expose any ports (nginx and php are connected via unix-socket).

If I run `telepresence intercept my-php-service -- /bin/bash` and trying to print all env variables via `env` command - I don't see variables from `php-fpm` container - probably because I have env from `nginx` container.

It would be awesome if I could specify, env from which container I want to get.

**Describe the solution you'd like**
Possible solution would be to add `--container | -c` option to `telepresence intercept`, so that it would be possible to choose container.

**Describe alternatives you've considered**
Don't see any alternatives.

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)
       Client: v2.4.9 (api v3)
       Root Daemon: v2.4.9 (api v3)
       User Daemon: not running
  - Kubernetes Environment and Version
       Docker Desktop 4.3.2, Kubernetes v1.22

**Comment by niksauer** [comment]
We would love this too. Right now, the only solution is to expose the other service's port and start another intercept. See https://github.com/telepresenceio/telepresence/issues/1935#issuecomment-1536818101

**Comment by niksauer** [comment]
Bump
