### ISSUE TITLE
jn-kim

### ISSUE THREAD

**Issue by JungnamKim-dev** [telepresenceio/telepresence#2294]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--new-deployment', 'frontend-local-cluster-alpha-jn-kim', '--context', 'local-cluster', '--namespace', 'telepresence', '--expose', '3000', '--method=inject-tcp']`
Version: `0.109`
Python version: `3.9.9 (main, Nov 21 2021, 03:23:42) 
[Clang 13.0.0 (clang-1300.0.29.3)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin jnkim-2 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  23.4 TEL | [107] exit -11 in 0.07 secs.
  23.5 TEL | [108] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  23.5 TEL | [108] exit -11 in 0.06 secs.
  23.6 TEL | [109] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  23.7 TEL | [109] exit -11 in 0.07 secs.
  23.8 TEL | [110] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  23.9 TEL | [110] exit -11 in 0.07 secs.
  24.0 TEL | [111] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  24.0 TEL | [111] exit -11 in 0.07 secs.
  24.1 TEL | [112] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  24.2 TEL | [112] exit -11 in 0.07 secs.
  24.2 TEL | END SPAN local.py:42(set_up_torsocks)   15.0s

```

**Comment by cindymullins-dw** [comment]
Hi @JungnamKim-dev , version 1 of Telepresence is no longer supported. You can upgrade to the latest version using [the steps noted here](https://www.getambassador.io/docs/telepresence/latest/install/upgrade).
