### ISSUE TITLE
Telepresence bug

### ISSUE THREAD

**Issue by gadicohen** [telepresenceio/telepresence#2313]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--mount', '/tmp/known', '--swap-deployment', 'compute-service', '--namespace', 'sisense', '--docker-run', '--rm', '-it', '-v', '/Users/gadicohen/Development/compute-service:/usr/src/app', '-v=/tmp/known/var/run/secrets:/var/run/secrets', 'compute-service', '-p', '8080:8080', '/bin/sh']`
Version: `0.109`
Python version: `3.8.0 (default, Sep  9 2021, 16:50:20) 
[Clang 12.0.5 (clang-1205.0.22.11)]`
kubectl version: `Client Version: v1.21.4 // Server Version: v1.19.9`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin MACUS-Gadi-Cohen.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 52, in main
    launch = outbound.setup(runner, args)
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 183, in setup
    return setup_container(runner, args)
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 135, in setup_container
    id_in_container = runner.get_output(
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 479, in get_output
    output = self._run_command_sync(
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 426, in _run_command_sync
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['docker', 'run', '--rm', '-v', '/tmp/tel-6unqvlkh:/tel', 'alpine:3.6', 'cat', '/tel/session_id.txt']' timed out after 30 seconds

```

Logs:

```
 |             },
   1.8   5 |             {
   1.8   5 |                 "lastTransitionTime": "2022-01-12T00:12:40Z",
   1.8   5 |                 "lastUpdateTime": "2022-01-18T23:40:07Z",
   1.8   5 |                 "message": "ReplicaSet \"compute-service-7df799949c\" has successfully progressed.",
   1.8   5 |                 "reason": "NewReplicaSetAvailable",
   1.8   5 |                 "status": "True",
   1.8   5 |                 "type": "Progressing"
   1.8   5 |             }
   1.8   5 |         ],
   1.8   5 |         "observedGeneration": 31
   1.8   5 |     }
   1.8   5 | }
   1.8 TEL | [5] captured in 0.45 secs.
   1.8 TEL | Found ssh -> /usr/bin/ssh
   1.8 TEL | [6] Capturing: ssh -V
   2.1 TEL | [6] captured in 0.30 secs.
   2.1 TEL | Found docker -> /usr/local/bin/docker
   2.1 TEL | [7] Capturing: docker run --rm -v /tmp/tel-6unqvlkh:/tel alpine:3.6 cat /tel/session_id.txt
  92.2   7 | 661a21f3bfdf4b348aed92f368c04577
  92.2 TEL | [7] timed out after 90.18 secs.

```

**Comment by cindymullins-dw** [comment]
Hi @gadicohen , version 1 of Telepresence is no longer supported.  You can upgrade to the latest version using [the steps noted here](https://www.getambassador.io/docs/telepresence/latest/install/upgrade).
