### ISSUE TITLE
traffic-manager cannot be installed as part of a subchart when namespaced mode

### ISSUE THREAD

**Issue by rchenzheng** [telepresenceio/telepresence#2329]
**Describe the bug**
The issue is with the chart, when the chart is defined as a chart dependency, it fails to deploy as it's enforcing `Release.Name` to be traffic-manager https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/templates/_helpers.tpl#L20-L29

* reproduce the error *

```
helm upgrade -i my-app --set 'telepresence.managerRbac.namespaces={test}' --set telepresence.managerRbac.namespaced=true
...
The name of the release MUST BE traffic-manager
```

**To Reproduce**
1. When I run `helm upgrade -i my-app --set 'telepresence.managerRbac.namespaces={test}' --set telepresence.managerRbac.namespaced=true`
2. I see 'The name of the release MUST BE traffic-manager'
3. So I look at https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/templates/_helpers.tpl#L8-L18

Also when `isCI=true` is defined then the traffic-manager chart gets installed in the ambassador namespace which is not something I want. https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/templates/_helpers.tpl#L20-L29

**Expected behavior**

The chart should have the ability to deploy to 

**Additional context**
The intention is to have one traffic-manager per namespace

**Comment by rchenzheng** [comment]
Fix pending review https://github.com/telepresenceio/telepresence/pull/2330

**Comment by thallgren** [comment]
The traffic-manager must indeed be named "traffic-manager" or the CLI won't find it.

Installing one traffic-manager per namespace is possible. The process is [described here](https://www.getambassador.io/docs/telepresence/latest/install/helm/#installing-a-namespace-scoped-traffic-manager).

**Comment by rchenzheng** [comment]
> The traffic-manager must indeed be named "traffic-manager" or the CLI won't find it.
> 
> 
> 
> Installing one traffic-manager per namespace is possible. The process is [described here](https://www.getambassador.io/docs/telepresence/latest/install/helm/#installing-a-namespace-scoped-traffic-manager).

I need to define it as a chart dependency. When deploying as part of an app.

Maybe a refactor of the cli is an order? An alternative is to find the resources by labels rather than release names.

**Comment by thallgren** [comment]
Isn't it possible to create dependencies to something with the same name but in different namespaces? E.g. `traffic-manager.alpha` is different from `traffic-manager.bravo` ?

**Comment by rchenzheng** [comment]
> Isn't it possible to create dependencies to something with the same name but in different namespaces? E.g. `traffic-manager.alpha` is different from `traffic-manager.bravo` ?

It's not supported to be in a separate namespace.

My use case is for ephemeral applications and namespaces so ideally they'd go in the same namespace. This is also needed since the telepresence relies on RBAC from the same namespace.

**Comment by thallgren** [comment]
@rchenzheng not sure what you're saying here. Do you want to install more than one traffic-manager in the same namespace?

**Comment by rchenzheng** [comment]
> @rchenzheng not sure what you're saying here. Do you want to install more than one traffic-manager in the same namespace?

No, one per application per namespace but in my case, I need the RBAC rules to be scoped per namespace.

**Comment by thallgren** [comment]
So you need [namespace scoped RBAC](https://www.getambassador.io/docs/telepresence/latest/install/helm/#namespace-scoped-user-permissions) for the traffic-manager? What is it that prevents you from doing that?

**Comment by rchenzheng** [comment]
> So you need [namespace scoped RBAC](https://www.getambassador.io/docs/telepresence/latest/install/helm/#namespace-scoped-user-permissions) for the traffic-manager? What is it that prevents you from doing that?

I actually needed so each ephemeral application had its own traffic manager and managed its own scope, I just find it weird that the release name had to be hardcoded hence the fix.

**Comment by JuanRamino** [comment]
Hi,

we have the same use case but we do not put the traffic-manager in the same chart of the application.
So, we deploy the application and then we deploy the traffic-manager in the same namespace.

I Hope it helps!

**Comment by thallgren** [comment]
@rchenzheng one reason to hardcode the name of the traffic-manager is that it will allow for stricter RBAC rules. An RBAC rule can be constrained to a resource name but it cannot be constrained to label selection.

**Comment by cindymullins-dw** [comment]
Looks like this question has been answered.
