### ISSUE TITLE
I want to be able to run kubectl commands to my GKE cluster directly from my local development CLI. 

### ISSUE THREAD

**Issue by bskrishna60** [telepresenceio/telepresence#2333]
**Please describe your use case / problem.**

I have a GKE/kubernetes/k8s cluster in GCP. I have a bastion host (Compute Engine VM Instance) in GCP. I have allowlisted my bastion host's IP in the GKE cluster's  authorized networks section. Hence, in order to run kubectl commands to my GKE, I first need to SSH into my bastion host by running the gcloud beta compute ssh command; then I run the gcloud container clusters get-credentials command to authenticate with GKE, then from there I can run kubectl commands like usual.

**Describe the solution you'd like**

I want to be able to run kubectl commands to my GKE cluster directly from my local development CLI so that I can use telepresence

**Comment by cindymullins-dw** [comment]
Hi @bskrishna60 , in order to use Telepresence you will need to get kubectl working with your cloud provider. Once that works, then Telepresence is likely to work too.  If you'd like assistance, you're welcome to join a help session via our Slack at a8r.io/slack.  Or you can let me know here.
