### ISSUE TITLE
Sidecar Limits For HPA

### ISSUE THREAD

**Issue by sonicSW** [telepresenceio/telepresence#2356]
Dear community,
thank you for this fantastic tool! Loving it.

I was not able to find any annotations to define requests and limits for the sidecar.
The result is that the HPA is not starting for the given deployment

"the HPA was unable to compute the replica count: failed to get memory utilization: missing request for memory"

In Linkerd there are some annotation like
        config.linkerd.io/proxy-cpu-limit: "1"
        config.linkerd.io/proxy-cpu-request: "0.2"
        config.linkerd.io/proxy-memory-limit: 128Mi
        config.linkerd.io/proxy-memory-request: 64Mi

to overcome this warning, wondering if there is something alike in telepresence?
I was thinking to also run telepresence in production to be able to debug some calls directly if need be, or is this not a recommended method?

Thank you in advance!

**Comment by cindymullins-dw** [comment]
HPA requires that any sidecar that’s injected or any container you're using has to have the resource limits specified in the container.  You can configure the limits in the Helm chart using [value : agent.resources].(https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/values.yaml#L200)
