### ISSUE TITLE
Intercept stop working after some time and won't work until traffic-agent removed

### ISSUE THREAD

**Issue by oriser** [telepresenceio/telepresence#2378]
**Describe the bug**
I intercept a service, listen with netcat and call the service with cURL. After some cURL callings I get redirected to the service in the cluster, then back to my workstation and then again to the service on the cluster until it stops to redirect to my workstation at all. When it happens, `leave` and `intercept` again won't work anymore (the command is successful, but it always sends the request to the cluster and not to my local machine).
I tried: restarting the traffic-agent container inside the service pod, restarting the pod - still intercept doesn't work.
The only way I got it to work again is by deleting the traffic-agent manually from the service's deployment, then when intercepting I get the traffic, but again it stops working after some requests.

I suspect that it may be related to the fact that the requests I'm sending to the service are terminated not gracefully (because I'm sending them with cURL and hit ctrl+c)

**To Reproduce**
1. Run `nc -lk 8081`
2. Run `telepresence intercept <service> -p 8081:8081`
3. Run `curl <service>.default.svc.cluster.local:8081`
4. You'll see the request in the netcat session
5. Keep closing and resending requests with cURL, some of the requests will start redirected to the cluster, until all of the requests will be redirected
6. Run `telepresence leave <service>` and `telepresence intercept <service> -p 8081:8081`
7. All cURL requests will be redirected to the cluster
8. Run `telepresence leave <service>`
9. Delete `traffic-agent` container from the deployment of the service
10. Run `telepresence intercept <service> -p 8081:8081`
11. Send requests with cURL, you'll get it to the netcat server but the bug will reproduce after some requests

**Expected behavior**
Intercept will continue to work

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
Client: v2.4.11 (api v3)
Root Daemon: v2.4.11 (api v3)
User Daemon: v2.4.11 (api v3)
```
 - Operating system of workstation running `telepresence` commands
` macOS Monterey 12.2`
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 GKE
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

**VPN-related bugs:**
Not using VPN

**Additional context**
I had old telepresence 2.4.9 which the bug was reproduced, I uninstalled all including going over all resources and making sure there are no leftovers of traffic-agent. Then installed again the 2.4.11.

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8048759/telepresence_logs.zip)
The bug can be clearly seen in the log
traffic-manager-7d748f66df-q2lc8.ambassador.log
See that sometimes it proxied the requests to 127.0.0.1:8081 and sometimes to 10.51.252.32:8081.

**Comment by thallgren** [comment]
The traffic-manager log shows calls from your local workstation to the `step-manager` agent at 10.51.252.32:8081 and then calls from that agent to the intercepted process in your local workstation at `127.0.0.1:8081`. This is is normal. Your curl call origins from your workstation, is routed by the traffic-manager to the agent. The agents react to the intercept and routes it back to your local workstation and the `nc` that listens at port 8081.

If you have an ongoing intercept and that intercept for some reason isn't proxied, then your curl calls would only show one of those two. Like it does after 11:57:53.6293.

I'm not able to repro this with the [service I'm using](https://github.com/telepresenceio/telepresence/blob/release/v2/k8s/echo-easy.yaml). If you can reproduce using that service then we can use that as a base. If not, I'll need more info about your `step-manager` so that I can find out what it is doing that is different.

**Comment by oriser** [comment]
> The traffic-manager log shows calls from your local workstation to the `step-manager` agent at 10.51.252.32:8081 and then calls from that agent to the intercepted process in your local workstation at `127.0.0.1:8081`. This is is normal. Your curl call origins from your workstation, is routed by the traffic-manager to the agent. The agents react to the intercept and routes it back to your local workstation and the `nc` that listens at port 8081.
> 
> If you have an ongoing intercept and that intercept for some reason isn't proxied, then your curl calls would only show one of those two. Like it does after 11:57:53.6293.
> 
> I'm not able to repro this with the [service I'm using](https://github.com/telepresenceio/telepresence/blob/release/v2/k8s/echo-easy.yaml). If you can reproduce using that service then we can use that as a base. If not, I'll need more info about your `step-manager` so that I can find out what it is doing that is different.

Ah OK, I understood the logs from the agent to the local machine, thanks for the explanation.
I'll try to reproduce it with the service you are testing against and will write here the findings.

**Comment by oriser** [comment]
@thallgren I'm not able to reproduce it with the service you provided. The `step-manager` I'm testing is a microservice that basically has a gRPC server and I want to run it on my local machine.
I think the problem is not with the service (as nothing on the service should affect it, it should be transparent to it, no?), I think it may be related to the fact that our microservices deployments are managed by flux and it may change some configuration related to the traffic agent.

Can you please explain at a high level what happens when I run `telepresence intercept`? It may help me to understand if flux is related and how to fix it

**Comment by thallgren** [comment]
First of all, there's the agent install. Assuming that the workload pod is created from a workload (Deployment, ReplicaSet, or StatefulSet) that doesn't have an annotation like "telepresence.getambassador.io/inject-traffic-agent" (and hence is auto-injected using a mutating webhook), the `traffic-agent` will be installed the very first time you intercept by modifying the workload, adding the container to the pod template, and reapplying it. The `traffic-agent` will then remain until you explicitly uninstall using `telepresence uninstall --agent xxx` (this rollbacks the modification to the workload and reapplies it again). During the install, the port of the original app container is modified (typically renamed with the prefix "tm-" as the installed `traffic-agent` "steals" the original port. The `traffic-agent` will then forward all traffic from the "stolen" port to the new port of the app container. This forwarding is made using localhost and never visible outside the pod.

Now, for each `telepresence intercept`, the `traffic-agent` will instead forward traffic on the "stolen" port to your local workstation. This forwarding uses a gRPC tunnel to the `traffic-manager` which then forwards it again using another gRPC tunnel to the workstation (this is what you see in the logs). This forwarding stops once you do `telepresence leave`. At that time, the traffic is again forwarded to the app container using the port on localhost.

**Comment by oriser** [comment]
@thallgren Thanks a lot for taking the time to write it.
I think I understand the problem. Flux is overriding the `tm-` prefix from the port. I'll see how to overcome it and will update

**Comment by oriser** [comment]
Hi @thallgren, so indeed the problem was that flux edited the `tm-` prefix. Once disabling it the intercept is working as expected. Thanks again :)
