### ISSUE TITLE
traffic-agent container: sftp-server errors when deployment has pod security context

### ISSUE THREAD

**Issue by HerrInformatiker** [telepresenceio/telepresence#2391]
**Describe the bug**
Intercepting a service that had the following pod security context defined in its deployment:
```
securityContext:
    fsGroup: 1000
    runAsUser: 1000
```
Generated the following errors in the traffic-agent container (See attached logs):
```
sftp-server : No user found for uid 1000
sftp-server : exit status 1
```

The interception itself, however, worked well.

**To Reproduce**
1. When I run `telepresence intercept pxlt-repo-setter --port 63278 --env-file ~/pixellot/repos/devops-il/pxlt-repo-setter/service.env` for a service that has a pod security context in its deployment
2. I see sftp-server errors in the traffic-agent container's logs

**Expected behavior**
Traffic agent should take into account the pod's security context might cause all container's processes within that pod to run with a different user ID 

**Versions (please complete the following information):**
 - Client: v2.4.11 (api v3)
 - Root Daemon: v2.4.11 (api v3)
 - User Daemon: v2.4.11 (api v3)

 - Operating system of workstation running `telepresence` commands: Ubuntu 20.04
 - Kubernetes environment and Version: EKS 1.21

**Additional context**
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8067451/telepresence_logs.zip)

**Comment by emoyly** [comment]
I am facing this issue as well.

It seems that this is related to (or the same really) #2169

**Comment by cindymullins-dw** [comment]
Closing this issue to consolidate on #2169.
