### ISSUE TITLE
How to isolate completely a service intercepted?

### ISSUE THREAD

**Issue by jaudiger** [telepresenceio/telepresence#2408]
**Describe the bug**

I'm trying to use Telepresence to intercept a service deployed in a Kubernetes Cluster. Find below the interaction between the services.
 
```mermaid
flowchart
    subgraph Cluster
        Service1 <--> Kafka
        Service1 --> MongoDB
        Service2 <--> Kafka
        Service2 --> |HTTP| Service1
   end
```

In this scenario I want to intercept `Service1` and deploy it locally to debug with IDE:

```mermaid
flowchart
    subgraph Cluster
        Kafka
        MongoDB
        Service2
        Service1                
   end
 
   subgraph Local
       LocalService1
   end

   Service2 --> |HTTP| LocalService1
   Service2 <--> Kafka
   LocalService1 <--> Kafka
   LocalService1 --> MongoDB
```

I'm able to connect on the cluster with telepresence, to intercept a service, generate an env file and run it locally. And HTTP requests are forwarded as expected to my local service.

The problem is, after interception, Service1 continues to run remotely and thus, is connected to both Kafka and MongoDB services as shown below:

```mermaid
flowchart
    subgraph Cluster
        Kafka
        MongoDB
        Service2
        Service1            
   end
 
   subgraph Local
       LocalService1
   end

   Service2 --> |HTTP| LocalService1
   Service2 <--> Kafka
   Service1 <--> Kafka
   Service1 <--> MongoDB
   LocalService1 <--> Kafka
   LocalService1 --> MongoDB
```

As a consequence, `Service1` continues to consume message from Kafka topics. Is there a possibility to break the communication from Kafka and MongoDB with `Service1` once it is intercepted. My main concern is to isolate the remote service to debug it locally:

```mermaid
flowchart
    subgraph Cluster
        Kafka
        MongoDB
        Service2
        Service1            
   end
 
   subgraph Local
       LocalService1
   end

   Service2 --> |HTTP| LocalService1
   Service2 <--> Kafka
   Service1 x--x Kafka
   Service1 x--x MongoDB
   LocalService1 <--> Kafka
   LocalService1 --> MongoDB
```

I think I miss something in the documentation, if someone could help me to resolve that issue. I already lost a few hours trying to overcome it. Thanks in advance !

**Comment by thallgren** [comment]
We do have a ticket requesting the ability to [stop the intercepted container](/telepresenceio/telepresence/issues/1646) during an intercept. I guess that's what you're looking for here. Doing that will however create problems in case other users are accessing the service. We've added the Telepresence [RestFUL API service](https://www.getambassador.io/docs/telepresence/latest/reference/restapi/) as one way to mitigate this. It will allow your `Service1` to create a Kafka filter based on headers (assuming that original request headers are propagated in your messages) to decide whether the message should be consumed.

**Comment by cindymullins-dw** [comment]
Appears to be resolved, please let us know if this is still an issue
