### ISSUE TITLE
Mounting remote volumes failed

### ISSUE THREAD

**Issue by omnilinguist** [telepresenceio/telepresence#241]
Was advised by @itamarst to file a bug here.

Command run was `telepresence -m inject-tcp --swap-deployment my-service --expose 8080:80 --run-shell`, with a Flask app running locally on 8080.

```
Mounting remote volumes failed, they will be unavailable in this session. This is a known issue when running inside Docker or on Windows Subystem for Linux. See https://github.com/datawire/telepresence/issues/115 for details. If you are not running in those environments then please report a bug, attaching telepresence.log to the bug report.
```

OS: macOS Sierra 10.12.4
telepresence version: 0.60

Logs (for security purposes as this is public, the log has been edited to replace the domain name with `my-domain` and the service name with `my-service`, but I am guessing this shouldn't materially affect the issue report.
[telepresence.log.txt](https://github.com/datawire/telepresence/files/1169601/telepresence.log.txt)

**Comment by itamarst** [comment]
Relevant error in logs is "mount_osxfuse: the OSXFUSE file system is not available (255)".

Potential reasons:

1. You need to reboot. OSXFuse *claims* you need to reboot for it to work. In my experience this hasn't been the case, but perhaps Sierra is different. So as a first step, could you reboot your computer and see if it works?
2. Your OSXFuse doesn't support Sierra. It seems like any OSXFuse installed after September 2016 would do fine, but perhaps you have an older version. Can  you trying upgrading? `brew cask upgrade osxfuse` maybe? I forget exact syntax.
3. Probably other reasons. Do you have any system configuration that might break 3rd party filesystems?

**Comment by itamarst** [comment]
Once we've nailed down the issue will respectively:

1. Add more explanatory text about need for reboot.
2. Add better detection of minimal version of OSXFuse.
3. We'll see.

**Comment by itamarst** [comment]
On newly installed Sierra machine I didn't need to reboot to start using OSXFuse. I installed version 3.6.3.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
