### ISSUE TITLE
Intercept throws 404 on /api routes when local nginx container is used

### ISSUE THREAD

**Issue by seunggs** [telepresenceio/telepresence#2412]
**Describe the bug**
Running a React/Express app using 3 local docker containers - frontend (port 3001), backend (port 4001), and nginx (which routes traffic from port 80 to frontend for path `/` and to backend for path `/api`. This setup works fine when running all containers locally and not using the intercept (i.e. all routes work fine).

When using the intercept, `/api` routes return 404. Here's the nginx conf.

```
upstream frontend {
    server frontend:3001;
}

upstream api {
    server api:4001;
}

server {
    listen 80;

    location /p/app {
        proxy_pass  http://frontend;
        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
    }
   
    location /p/app/api {
        rewrite /api/(.*) /$1 break;
        proxy_pass  http://api;
        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
        client_max_body_size 50m;
    }

    location /ping {
      add_header Content-Type text/plain;
      return 200 'OK';
    }
}
```

**To Reproduce**
1. Run all 3 local containers
2. Once connected to Telepresence, run `telepresence intercept app-staging-svc --service app-staging-svc --port 80:80 --env-file .env.intercept`
3. Visit `https://app-staging.my-domain.com` which exposes `app-staging-svc` via Emissary Ingress
4. Frontend routes (i.e. `/`) seem to be working correctly, but all api routes (i.e. `/api`) return 404

Please note that Telepresence seems to be working fine, since when I hit the live endpoint that it's intercepting (e.g. `app-staging.my-domain.com`), it forwards the services correctly for the frontend app (i.e. `/`). It's just the backend `/api` routes that are returning 404 which is why I'm assuming nginx is the issue.

**Expected behavior**
Telepresence intercept should route the `/api` routes correctly without modifying the local setup

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
Client: v2.4.11 (api v3)
Root Daemon: v2.4.11 (api v3)
User Daemon: v2.4.11 (api v3)
```
 - Operating system of workstation running `telepresence` commands
 MacOS Monterey (12.2.1)

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
Amazon EKS (1.21)

**Comment by thallgren** [comment]
You write that "Telepresence seems to be working fine" and "I'm assuming nginx is the issue" so it's not clear to me what behavior that you want us to change. Please note that the 2.4.11 version of Telepresence isn't capable of routing based on paths. It never looks at them.

The current version of Telepresence (2.5.1) is capable of doing personal intercepts that are [limited by path](https://www.getambassador.io/docs/telepresence/latest/concepts/intercepts/#intercepting-a-specific-endpoint). Not sure if that'll help your use case, but perhaps it's worth taking a look?

**Comment by seunggs** [comment]
Hi @thallgren - thanks for the response. I'm not sure if path-based routing is the solution for my use case though. 

The problem is that Telepresence doesn't seem to respect the routing configurations of nginx. Nginx is running on port 80 and I'm intercepting at port 80 which means traffic should be forwarded to nginx, which should take care of routing to frontend container or backend container. But this nginx routing does not work when I use Telepresence. It works fine if I just run local containers so it seems like Telepresence bug?

Is there any reference use case for local nginx containers? I think this is a very common setup for React/Express apps?

**Comment by thallgren** [comment]
Telepresence has no knowledge of what it is that it's intercepting. It doesn't care if it's nginx or some other process. It just redirects the intercepted port to something that runs on your local workstation. It has no concept of "routing configurations in nginx". You need to explain more about your setup. Are you intercepting the nginx process? Do you have an nginx running on your local workstation?

**Comment by seunggs** [comment]
Right - so I do have my nginx container running on my local workstation at port 80. And yes, I'm intercepting the nginx process (`telepresence intercept app-staging-svc --service app-staging-svc --port 80:80 --env-file .env.intercept`). 

The nginx is set up to route the traffic based on path (`/` to frontend container at port 3001 and `/api` to backend container at port 4001). 

But when I try to reach the api, (i.e. `http://localhost:4001/api/xxx`), it gives a `404` error. Without Telepresence, it returns the correct response.

**Comment by thallgren** [comment]
Ok, so the nginx on your local machine makes an attempt to open `localhost:4001`. That's a port on your local workstation. Do you have anything listening on that port, or do you expect the request to be routed back to the pod? For the latter to happen, you must tell Telepresence to route that port on your local machine to your pod. You do that with `--to-pod <port>`.

**Comment by seunggs** [comment]
Yes, on port 4001, I have an ExpressJs server running in a docker container listening on that port. But it doesn't seem to work. So I shouldn't need to set up anything with Telepresence? I assume Telepresence work is done when it intercepts traffic to nginx and nginx is responsible for routing to my 4001 container. But strangely, this setup works fine without Telepresence but 404 is thrown when I turn on the intercept.

As an alternative, I'll look into `--to-pod` solution you mentioned - thanks for pointing that out.

**Comment by cindymullins-dw** [comment]
Appears to be resolved, please let us know if this is still an issue
