### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by amh4r** [telepresenceio/telepresence#2417]
**Describe the bug**

`telepresence connect` fails:

```
$ telepresence connect
telepresence: error: connector.Connect: no Auth Provider found for name "gcp"
```

I see this in the logs:

```
2022-02-18 22:49:35.5696 info    connector/session : Connecting to k8s cluster...
2022-02-18 22:49:35.5710 error   connector/session : unable to track k8s cluster: no Auth Provider found for name "gcp"
```

**Versions (please complete the following information):**

```
$ telepresence version
Client: v2.5.0 (api v3)
Root Daemon: v2.5.0 (api v3)
User Daemon: v2.5.0 (api v3)
```

macOS 12.1 (M1 Max)

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

K8s cluster is running in GKE.

**Comment by thallgren** [comment]
Can you connect to the cluster using `kubectl get pod` or similar?

**Comment by thallgren** [comment]
Also, it would be of interest to see what your logs look like, the `connector.log` especially. Can you try:
```
$ telepresence loglevel debug
$ telepresence connect
$ telepresence gather-logs
```

**Comment by maxlegault** [comment]
I reproduced the issue with a fresh GKE cluster, also on version 1.21.6-gke.1500. I'm able to list pods, so the auth looks good.
Here is my connector.log output:
```
2022-02-19 07:04:45.7383 trace   Logging at this level "trace"
2022-02-19 07:04:45.7388 debug   Listener opened
2022-02-19 07:04:45.7389 info    ---
2022-02-19 07:04:45.7389 info    Telepresence Connector v2.5.0 (api v3) starting...
2022-02-19 07:04:45.7389 info    PID is 48204
2022-02-19 07:04:45.7389 info
2022-02-19 07:04:45.7860 info    connector/server-grpc : Starting additional daemon service reverse-conn
2022-02-19 07:04:45.7865 info    connector/server-grpc : Starting additional daemon service pro-version-checker
2022-02-19 07:04:45.7866 info    connector/server-grpc : Currently using Telepresence Pro Version: v1.0.0
2022-02-19 07:04:45.7869 info    connector/server-grpc : gRPC server started
2022-02-19 07:04:45.8164 debug   connector/server-grpc/conn=1/UserNotifications-1 : called
2022-02-19 07:04:45.8166 debug   connector/server-grpc/conn=1/Connect-2 : called
2022-02-19 07:04:45.8167 info    connector/session : Connecting to root daemon...
2022-02-19 07:04:45.8179 info    connector/session : Connecting to k8s cluster...
2022-02-19 07:04:45.8289 error   connector/session : unable to track k8s cluster: no Auth Provider found for name "gcp"
2022-02-19 07:04:45.8289 debug   connector/server-grpc/conn=1/Connect-2 : returned
2022-02-19 07:04:45.8315 debug   connector/server-grpc/conn=1/UserNotifications-1 : returned
```

**Comment by maxlegault** [comment]
This seems related: https://github.com/kubernetes/client-go/issues/839
With the suggested fix being to import the auth plugins: https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L33-L40

**Comment by amh4r** [comment]
> Can you connect to the cluster using kubectl get pod or similar?

Yep! I'm connected to the cluster.

> With the suggested fix being to import the auth plugins

@maxlegault sorry, I'm a little confused. I'm just using the `telepresence` bin installed via `brew`, so I don't have any Go files at all

**Comment by amh4r** [comment]
I found these instructions and followed them just in case:

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

But the `telepresence` error persists

**Comment by maxlegault** [comment]
Thanks for the update @goodoldneon. I think I have a fix in #2419, we're planning a 2.5.1 release to fix this issue.

**Comment by amh4r** [comment]
Damn! You beat me to it. I was just about to post about that same change working for me! I made that change, built `telepresence`, and was able to connect. Thank you!

**Comment by maxlegault** [comment]
Great! Thanks for testing :)

**Comment by maxlegault** [comment]
@goodoldneon Telepresence 2.5.1 is out. When you have the chance to test it, it would be great to hear back from you!

**Comment by amh4r** [comment]
It works 😎. Thanks so much for the quick fix!

I'm really excited to play around with Telepresence. Our local dev story is... difficult. It'll be cool if Telepresence gets us to a low-friction cloud-based dev experience. Have a great weekend!

**Comment by stevenbarlow** [comment]
@goodoldneon Awesome, I am glad the fix addressed your issue. 

I am the engineering manager for the team that works on Telepresence, and if you are willing, I would love to chat with you sometime about the challenges you have with your local dev story. It would be great feedback on the types of problems we are trying to address and would help me make sure we are thinking about different real-world pain points. If you have time for that, let me know.

**Comment by amh4r** [comment]
We have a few big issues with local dev:
1. Resource usage for running our entire platform in Minikube.
2. AFAICT, there isn't a way to run BigQuery locally.
3. Keeping locally-running services up-to-date.

So ideally, we'd just run the whole platform in the cloud and engineers would only need to run services ad hoc locally (which Telepresence enables!). This approach also makes it easy to solve issue 3, since we can auto-deploy to each engineer's cluster. I'm also a believer that dev environments should be nearly identical to prod, and that's extremely difficult (if not impossible) to do with pure local dev.

I'm still new at my company, so the above blurb is about as helpful I can be at this point. There are probably other big issues with local dev right now, but I'm still getting acquainted.
