### ISSUE TITLE
No build target available to only build the client binary?

### ISSUE THREAD

**Issue by johanneskastl** [telepresenceio/telepresence#2418]
I might be confused by the multiple Makefiles I found, but is there no way to only build the client binary?

https://github.com/telepresenceio/telepresence/blob/release/v2/Makefile
https://github.com/telepresenceio/telepresence/blob/release/v2/build-aux/main.mk

I tried multiple incantations of `go build` but it always ended with something like `pattern telepresence-chart.tgz: no matching files found`.

I tried to package the client binary as an RPM for openSUSE, but as the build process happens within a VM without network access, I need to supply all dependencies beforehand. And of course, it would be good to only have the ones that are really needed...

Thanks in advance!

**Comment by thallgren** [comment]
The client binary is built using `make build` and ends up under `build-output/bin`. The binary embeds the generated `telepresence-chart.tgz`, so that's part of what needs to be built.

**Comment by johanneskastl** [comment]
Thanks for the fast reply! Looks like I need to supply all of the dependencies beforehand, I was hoping the client binary had less of them... :-)

**Comment by thallgren** [comment]
@johanneskastl  I'm closing this issue. Feel free to reopen if you have suggestions on how to improve the build process.
