### ISSUE TITLE
User Daemon Version Mismatch

### ISSUE THREAD

**Issue by maxlegault** [telepresenceio/telepresence#2421]
**Describe the bug**
After upgrading from Telepresence 2.5.0 to 2.5.1, I get the following error:

```
❯ telepresence connect
telepresence: error: version mismatch. Client v2.5.1 != User Daemon v2.5.0, please run 'telepresence quit -u' and reconnect
```

After running `telepresence quit -u`, I get the same error again.

# To see all options, run the following command
telepresence gather-logs --help
```

**To Reproduce**
1. Install Telepresence 2.5.0
2. Run `telepresence login` to download the pro daemon
3. Install Telepresence 2.5.1
4. Run `telepresence connect`

**Expected behavior**
A compatible daemon version should automatically be downloaded

**Versions (please complete the following information):**
2.5.0

**Comment by maxlegault** [comment]
As a workaround, manually deleting the `telepresence-pro` binary and then running `telepresence login` again will get the new pro daemon version and fix the issue.

For reference, the `telepresence-pro` binary is downloaded in the `<cache>/telepresence` directory, where `<cache>` is usually:
- `$XDG_CONFIG_HOME` or `~/.config` on linux
- `~/Library/Application\ Support` on mac
- `%AppData%` on windows

So on mac: `rm ~/Library/Application\ Support/telepresence/telepresence-pro` should do the trick.

**Comment by thallgren** [comment]
I'm working on a fix for this.

**Comment by AndiRudi** [comment]
I still have this issue. When upgrading from `2.6.6` to `2.8.2` the following error appears

`telepresence: error: version mismatch. Client v2.8.2 != User Daemon v2.6.6, please run 'telepresence quit -s' and reconnect`

I also tried `telepresence quit -s` and `rm ~/Library/Application\ Support/telepresence/telepresence-pro` and both did not help. Is there anything else I can do?

**Comment by AndiRudi** [comment]
Actually after restarting the mac it did work...
