### ISSUE TITLE
multiple entries in KUBECONFIG broken since 2.5.0

### ISSUE THREAD

**Issue by an-tex** [telepresenceio/telepresence#2425]
before 2.5.0 I could run e.g.:

`KUBECONFIG=.kube/prod.yaml:.kube/staging.yaml telepresence connect --context staging`

since 2.5.0 (including 2.5.1) I get:
`telepresence: error: connector.Connect: stat .kube/prod.yaml:.kube/staging.yaml: no such file or directory`

running it with a single entry like 
`KUBECONFIG=.kube/staging.yaml telepresence connect --context staging`
or 
`KUBECONFIG=.kube/prod.yaml telepresence connect --context prod`
works

relevant `connector.log` entries:
```
2022-02-21 09:36:57.9777 info    connector/session : Connecting to k8s cluster...
2022-02-21 09:36:57.9778 error   connector/session : unable to track k8s cluster: stat .kube/prod.yaml:.kube/staging.yaml: no such file or directory
```

Client: v2.5.1 (api v3)
Root Daemon: v2.5.1 (api v3)
User Daemon: v2.5.1 (api v3)

[gather logs](https://easyupload.io/m0wk9f)

**Comment by PashCracken** [comment]
Would be good to get a fix for this. I typically have a long list of config files in my KUBECONFIG variable

**Comment by seagle0128** [comment]
Same issue with 2.5.3.

**Comment by dtmirizzi** [comment]
Recently upgraded to 2.5.4 and seeing this issue as well. Any reason why we will not support this going forward?

**Comment by an-tex** [comment]
I really would like to update. Still stuck on `Client: v2.4.11 (api v3)` :( Can you point me by any chance to a commit / code where this issue arises @thallgren ? Then I could try my luck with a PR. Unfortunately all by myself I'm lost here

**Comment by mariussoutier** [comment]
Same issue here.

**Comment by an-tex** [comment]
thanks a lot @thallgren ! I've just upgraded to 2.6.1 and it works like a charm :)

**Comment by thallgren** [comment]
Good to hear!
