### ISSUE TITLE
Consul connect support

### ISSUE THREAD

**Issue by amh4r** [telepresenceio/telepresence#2426]
**Please describe your use case / problem.**

Telepresence doesn't seem to support intercepting services that communicate via Consul connect (i.e. an Envoy sidecar proxy). The `traffic-agent` sidecar successfully attaches to pods, but no traffic is intercepted. I'm guessing this is because Telepresence works by modifying the K8s service endpoint, but Consul Connect doesn't care about the K8s service endpoint (AFAICT).

Does this functionality already exist? I wasn't able to find any references to Consul within Telepresence's docs. I _do_ see Consul within the Edge Stack docs, but that seems to be a different product than Telepresence.

**Versions**

```
$ telepresence version
Client: v2.5.1 (api v3)
Root Daemon: v2.5.1 (api v3)
User Daemon: v2.5.1 (api v3)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cindymullins-dw** [comment]
Telepresence now uses the mutating web hook as the default starting with v2.6, and does not modify the service endpoint.  Pls try 2.6or later and reopen if issues persist.
