### ISSUE TITLE
[Question] Telepresence DNS problems under Linux with docker

### ISSUE THREAD

**Issue by mschmidt291** [telepresenceio/telepresence#2428]
Hello. I'm running telepresence 2.5.1 under Arch Linux and got some DNS Problems in the docker container specified with --docker-run while intercepting a service.

When running the following command, the intercept happens and on my local machine I can reach the cluster services correctly. But in the docker container, the cluster services are not resolving
`telepresence intercept service-xy --docker-run --port 8000:80 -- -ti --entrypoint=bash image-xy

Is this intended or a bug, or is this known under linux? When using `--net=host` the dns resolution is working as intended, but according to the documentation it seems like this is not needed.

**Comment by wasd171** [comment]
We also experienced it

**Comment by suravikumar** [comment]
My team is also experiencing this issue. We are using an ubuntu and debian based VMs that are intercepting our components. Both are able to intercept and resolve services as expected, but when we are trying to take a DB dump within a mysql container, we are not able to resolve our DB service.

**Comment by jceb** [comment]
Same here. Using `--network host` as a docker parameter solves the issue.

**Comment by cindymullins-dw** [comment]
Thanks for the workaround, @jceb .  We don't think this can be fixed with Telepresence and is likely a Docker issue but we can add this workaround to the docs.
