### ISSUE TITLE
Telepresence failureed

### ISSUE THREAD

**Issue by vishalbhuva7** [telepresenceio/telepresence#2433]
### What were you trying to do?

run telepresence to map interceptor

### What did you expect to happen?

map local pod[image/code] to aws kubernates to test

### What happened instead?

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--expose', '8080', '--namespace', 'app', '--swap-deployment', 'c-dbs', '--run', './start_debug.sh']`
Version: `0.109`
Python version: `3.9.9 (main, Nov 21 2021, 03:23:44) 
[Clang 13.0.0 (clang-1300.0.29.3)]`
kubectl version: `Client Version: v1.22.2 // Server Version: v1.19.10`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Vishals-MacBook-Pro-2.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
-k8s:0.109" already present on machine
  95.3  50 |   Normal   Created    53s   kubelet            Created container c-dbs
  95.3  50 |   Normal   Pulled     52s   kubelet            Container image "docker.io/datawire/tel2:2.4.4" already present on machine
  95.3  50 |   Normal   Started    52s   kubelet            Started container c-dbs
  95.3  50 |   Normal   Created    52s   kubelet            Created container traffic-agent
  95.3  50 |   Normal   Started    52s   kubelet            Started container traffic-agent
  95.3  50 |   Normal   Pulled     52s   kubelet            Container image "docker.io/istio/proxyv2:1.4.8" already present on machine
  95.3  50 |   Normal   Created    52s   kubelet            Created container istio-proxy
  95.3  50 |   Normal   Started    52s   kubelet            Started container istio-proxy
  95.3  50 |   Warning  Unhealthy  51s   kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
  95.4 TEL | [50] ran in 3.68 secs.

```

**Comment by cindymullins-dw** [comment]
V1 is deprecated.  Please upgrade to the latest version which should work better for you.
