### ISSUE TITLE
quit/reconnect leads to failures on v2.5.x

### ISSUE THREAD

**Issue by ableuler** [telepresenceio/telepresence#2447]
**Describe the bug**
After running `telepresence quit` and reconnecting through `telepresence connect`, telepresence is not functional. See for example the following command sequence. The same sequence works as expected when using version 2.4.11 of telepresence.
```
 ~ ▶ % ▶ telepresence loglevel debug
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context renku-dev (https://<redacted>)
 ~ ▶ % ▶ telepresence status
Root Daemon: Running
  Version   : v2.5.3 (api 3)
  DNS       :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 4s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - 86.119.39.190/32
User Daemon: Running
  Version           : v2.5.3 (api 3)
  Executable        : /usr/local/bin/telepresence
  Ambassador Cloud  : Logged out
  Status            : Connected
  Kubernetes server : <redacted>
  Kubernetes context: renku-dev
  Intercepts        : 0 total
 ~ ▶ % ▶ curl -ik  https://kubernetes.default
HTTP/2 401
audit-id: 85e76aa5-1a2a-4113-9913-f7ae03fd15a2
cache-control: no-cache, private
content-type: application/json
content-length: 165
date: Wed, 02 Mar 2022 18:45:23 GMT

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}%
 ~ ▶ % ▶ telepresence quit
Telepresence Network disconnecting...done
Telepresence Traffic Manager disconnecting...done
 ~ ▶ % ▶ telepresence connect
Connected to context renku-dev (https://<redacted?)
 ~ ▶ % ▶ curl -ik -vvv https://kubernetes.default
*   Trying 10.43.0.1:443...
* Connected to kubernetes.default (10.43.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
^C
```
The logs generated by the above sequence can be found here: [telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8172182/telepresence_logs.zip)

**To Reproduce**
See steps above.

**Expected behavior**
I'd expect the same 401 response on the curl command after quit/connect.

**Versions**

The telepresence version is:
```
 ~ ▶ % ▶ telepresence version
Client: v2.5.3 (api v3)
Root Daemon: v2.5.3 (api v3)
User Daemon: v2.5.3 (api v3)
```
The workstation is an Apple M1 Pro with the following OS version:
```
 ~ ▶ % ▶ sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```
The cluster is an rke cluster:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:00:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Comment by thallgren** [comment]
The `https://kubernetes.default` should always give you status 401 (which it does. The first attempt is not a 403). Your second attempt uses a verbose output and the actual status code isn't visible. What does the actual JSON response look like in the second attempt?

**Comment by ableuler** [comment]
Sorry, I don't know why I typed 403, meant 401. I updated the description. On the second attempt I don't get any response, the request just hangs indefinitely.

**Comment by thallgren** [comment]
What type of cluster is it? Does it run in a virtual machine on your laptop? If that's the case, what kind of network configuration does that VM have?

**Comment by ableuler** [comment]
It's an rke (v1.3.0) cluster (v1.20.13) which ships with calico (v3.17.2) as networking plugin.

**Comment by Gikkman** [comment]
I've experienced the same, using 2.5.3 on a M1 Mac, against an Openshift cluster managed by our internal IT team. 

The first connect after a reboot works just fine, but if I quit and reconnect, subsequent requests doesn't work and just hangs indefinitely.

**Comment by cindymullins-dw** [comment]
@ableuler , can you try running `telepresence -ur `which removes the telepresence daemons and kills the pods.
