### ISSUE TITLE
Telepresence tests leak Services, probably

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#245]
Cleaning up old Services in testing cluster and there's a *lot*.

Conceivably `telepresence` leaks services when used with `--new-deployment`, so check that as well.

**Comment by exarkun** [comment]
Currently, CI cleans up sufficiently old stuff it finds.  This should limit the amount of stuff left over from test runs but a lot can still collect before CI cleanup gets to it.  CI only cleans up fairly old stuff to be sure it isn't still in use by anything.  Possibly we could cut the age requirement down here a bit now that the test suite is a bit faster but we still probably want to leave a lot of headroom to avoid causing problems.

Other possibilities:

  * Register `Probe.cleanup` as an atexit handler as soon as the `Probe` is created.  This will cause cleanup to happen in the case that pytest is interrupted in a way that skips its built-in fixture cleanup but that doesn't interrupt Python's normal shutdown logic (Ctrl-C at the right time, for example).
  * Make `build` resistant to interruption by Ctrl-C (but still pass it along to the pytest process) and add cleanup logic to `build` itself that follows the pytest run.
  * Early on in the test process, create a Job that cleans up the resources and then itself.  The Job could have a delay before it performs the cleanup (but this makes it a lot like the existing time-based CI cleanup).  It could also have a connection from the test process and perform cleanup a short while after that connection is broken (then have the test process keep the connection open for its entire run time).

**Comment by ark3** [comment]
The Kubernetes Job idea, or more generally launching some agent in the cluster that cleans up, seems like it would be the least intrusive to the tests and would avoid messing with signals. The test process could submit cleanup commands to the agent during test setup. When new commands stop coming in for long enough, the agent can execute all the queued-up cleanup commands, ignoring errors, run the generic cleanup script for leaks, and then self-terminate. The test process should continue to clean up proactively on its own, so testing uses minimal cluster resources. The agent would be a backup to address interrupted test runs and to keep leaks managed somewhat more tightly.

**Comment by donnyyung** [comment]
I've only seen these leaks on interrupted test runs in v2.  Probably still worth ensuring there's some automatic cleanup of _all_ test objects created in the cluster.
