### ISSUE TITLE
The headless service dns cannot be mapped

### ISSUE THREAD

**Issue by ismart-yuxi** [telepresenceio/telepresence#2451]
![J@L1Z@NW}2G}S2 )8N51CSB](https://user-images.githubusercontent.com/7867513/156726544-82a27773-7061-46d3-bf03-2783bdb60dc9.png)
![UXJN)7TRTJP B@_U`V$B3ZL](https://user-images.githubusercontent.com/7867513/156726558-11dfa361-0924-4bad-8f52-44def2659663.png)

**Comment by thallgren** [comment]
@ismart-yuxi you'll need to describe your problem in more detail. Please take a look at the [issue template](https://github.com/telepresenceio/telepresence/issues/new?assignees=&labels=&template=Bug_report.md).

**Comment by thallgren** [comment]
Closing, as no more info was provided.
