### ISSUE TITLE
Equivalent command

### ISSUE THREAD

**Issue by darthzyklus** [telepresenceio/telepresence#2465]
Hi there!

Hey I have a question, I don't know how to use the following command, in the version v2:

TELEPRESENCE_USE_DEPLOYMENT=1 telepresence --namespace SOME_NAMESPACE --also-proxy SOME_URL

Can you help me with this?

**Comment by thallgren** [comment]
Please use our [OSS-forum](http://a8r.io/slack) for questions. Tickets are for bug-reports or feature requests.

**Comment by darthzyklus** [comment]
Thanks  I will!
