### ISSUE TITLE
please bring  "--swap-deployment"  back

### ISSUE THREAD

**Issue by oojikoo** [telepresenceio/telepresence#2466]
**Please describe your use case / problem.**
A clear and concise description of your use case / problem. The "why" is really valuable to us. For example, "I have a set of services whose clients have long-lived connections."

I've been using telepresence since v1.  our infra use api gateway at front and all micro-services are connected via message broker(such as redis, nats and stuffs) so no ports are used in container. I liked using telepresence to develop via swapping deployment. but after v2, it seems that swapping isn't not possible.

**Describe the solution you'd like**
I'd like to see alternative to --swap-deployment or clear doc about this

**Describe alternatives you've considered**

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)
  - Kubernetes Environment and Version

**Additional context**
Add any other context about the feature request here.

**Comment by thallgren** [comment]
Intercepting without logging in or by using `--http-header=all` will intercept all requests to the pod, but it will not stop the containers from running (and hence consume messages from message queues etc.). Would a solution where you could actually stop the intercepted container solve your use-case?

**Comment by oojikoo** [comment]
> Intercepting without logging in or by using `--http-header=all` will intercept all requests to the pod, but it will not stop the containers from running (and hence consume messages from message queues etc.). Would a solution where you could actually stop the intercepted container solve your use-case?

we are using nats(http://nats.io/) as our message queue. It seems that containers still consume messages after using 
```
telepresence intercept svc-name -n namespace --http-header=all
```

am I doing anything wrong?

**Comment by thallgren** [comment]
@oojikoo no, you're not doing anything wrong. But as I wrote, that option will not actually stop the container. Hence my question.

**Comment by oojikoo** [comment]
> @oojikoo no, you're not doing anything wrong. But as I wrote, that option will not actually stop the container. Hence my question.

oh.. stopping the intercepted container actually solved my case! thanks. there gotta be a better solution(maybe auto deploy and undeploy?)

**Comment by oojikoo** [comment]
I will close this issue! but there gotta be some option to stop(or scale to 0) existing deployment while intercepting

**Comment by bcouetil** [comment]
@oojikoo how do you stop the intercepted container ? can you provide example commands ? thanks :pray:
