### ISSUE TITLE
Version 2.5.3 on WSL2 (Ubuntu 21.10) failed to intercept

### ISSUE THREAD

**Issue by PetrSilar** [telepresenceio/telepresence#2467]
**Describe the bug**
Telepresence 2.5.3 failed to start intercept on WSL2 with Ubuntu 21.10. Kuberntes cluster is on local Docker Desktop.

**To Reproduce**
1. When I run ```telepresence intercept echo --namespace test -p 50051 -- bash```
2. I see 
```
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context docker-desktop (https://kubernetes.docker.internal:6443)
Telepresence Network disconnecting...done
Telepresence Traffic Manager is already disconnected
telepresence: error: connector.CreateIntercept: rpc error: code = Unavailable desc = no active session

See logs for details (6 errors found): "/home/psilar/.cache/telepresence/logs/daemon.log"

See logs for details (3 errors found): "/home/psilar/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```
3. IMO relevant lines of ```daemon.log```:
```
2022-03-14 10:47:00.3230 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "172.21.210.153" "--sport" "36611" "-j" "RETURN"] : dexec.pid="11706"
2022-03-14 10:47:00.3231 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="11706" dexec.stream="stdin" dexec.err="EOF"
2022-03-14 10:47:00.3241 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="11706" dexec.stream="stdout+stderr" dexec.data="iptables v1.8.7 (nf_tables): unknown option \"--sport\"\n"
2022-03-14 10:47:00.3242 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="11706" dexec.stream="stdout+stderr" dexec.data="Try `iptables -h' or 'iptables --help' for more information.\n"
2022-03-14 10:47:00.3242 info    daemon/session/dns/legacy/NAT-redirect : finished with error: exit status 2 : dexec.pid="11706"
2022-03-14 10:47:00.3243 error   daemon/session/dns/legacy/NAT-redirect : goroutine "/daemon/session/dns/legacy/NAT-redirect" exited with error: exit status 2
```
4. Full logs attached.

**Expected behavior**
Obviously, to intercept the deployment.

**Versions (please complete the following information):**
 - Output of `telepresence version`: 
```
Client: v2.5.3 (api v3)
Root Daemon: v2.5.3 (api v3)
User Daemon: v2.5.3 (api v3)
```
 - Operating system of workstation running `telepresence` commands: ```Ubuntu 21.10```
 - WSL: 
```
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```
 - Windows: ```10.0.19044.1586```
 - Kubernetes: ```v1.21.2```
 - Docker Desktop: ```4.5.1```

**VPN-related bugs:**
N/A

**Additional context**
BTW: Neither ```telepresence gather-logs``` works:
```
Connected to context docker-desktop (https://kubernetes.docker.internal:6443)
Telepresence Network disconnecting...done
Telepresence Traffic Manager is already disconnected
error getting logs from kubernetes components: rpc error: code = Unavailable desc = error reading from server: file already closed
telepresence: error: open /usr/local/bin/telepresence_logs.zip/usr/local/bin: no such file or directory
```
[logs.zip](https://github.com/telepresenceio/telepresence/files/8244137/logs.zip)

**Comment by thallgren** [comment]
@PetrSilar the logs aren't produced with loglevel debug, so they don't contain any info that will help trace network issues.

I suspect that your problem is that the cluster have access to your host's network and DNS. So things that it doesn't resolve get routed back to the host and back into the Telepresence TUN-device, which of course routes it to the cluster, and an endless recursion is a fact.

I've written a [Network considerations for locally hosted clusters](/telepresenceio/telepresence/blob/release/v2/docs/v2.5/howtos/cluster-in-vm.md) that hasn't been released yet that might shed some light on this.

**Comment by PetrSilar** [comment]
Thank you for your answer.

> @PetrSilar the logs aren't produced with loglevel debug, so they don't contain any info that will help trace network issues.
> 
My bad, attaching new logs.

> I suspect that your problem is that the cluster have access to your host's network and DNS. So things that it doesn't resolve get routed back to the host and back into the Telepresence TUN-device, which of course routes it to the cluster, and an endless recursion is a fact.
> 
Does it mean that failure in setting of iptables' rule because of invalid arguments is not a problem? (See log part bellow 3. in the original post).
Also it worked for me with some older version (still 2.x) of telepresence. Unfortunately I don't know which one. 
It also works in Windows (i.e. the same machine but intercepting from Windows instead of from WSL).
[logs.zip](https://github.com/telepresenceio/telepresence/files/8304782/logs.zip)

**Comment by thallgren** [comment]
@PetrSilar, please take a look at https://github.com/telepresenceio/telepresence/issues/2456#issuecomment-1065893583 regarding the `iptables` problem.

**Comment by PetrSilar** [comment]
> @PetrSilar, please take a look at [#2456 (comment)](https://github.com/telepresenceio/telepresence/issues/2456#issuecomment-1065893583) regarding the `iptables` problem.

Yes, that helped. Thank you.
I.e. the problem is that telepresence does not consider nf_tables.
This issue may be marked as duplicate of #2456.

**Comment by cindymullins-dw** [comment]
Closing to consolidate on issue #2456 .
