### ISSUE TITLE
Submit sshuttle LLMNR changes upstream

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#247]
Currently the `llmnr` branch in https://github.com/datawire/sshuttle has code that captures packets sent to the LLMNR DNS address. Instead of maintaining our own fork we should submit a better implementation upstream.

A few possible patches I can imagine:

1. sshuttle automatically detects systemd-resolved, and if it's there and `--dns` option is passed then it enables capturing LLMNR.
2. sshuttle always captures LLMNR packets if `--dns` is set.
3. sshuttle adds ability to accept port numbers of DNS servers in `--ns-hosts` and then adds LLMNR IP and port that way. This presumes `--ns-hosts` gets *added* to automatically parsed /etc/resolv.conf so maybe not a good idea?

1 or 2 seem better.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
