### ISSUE TITLE
telepresence uninstall --agent removes it from all agents

### ISSUE THREAD

**Issue by 0x2C6** [telepresenceio/telepresence#2479]
**Describe the bug**
According to documentation, telepresence uninstall can accept 
`--agent`
`--all-agents`
`--everything`

If single-agent name passed, it should remove traffic-agent from a specific workload. When you use uninstall --agent on cluster side it behave expected, however on local it removes all workload access and requires re-intercepting workloads.

**To Reproduce**
1. Start 2 interception process on different workloads
2. List intercepted workloads to verify 2 of them is running 
3. Uninstall one of them by using `telepresence uninstall --agent workload-name`
4. List again and you will see nothing intercepting

**Expected behavior**
It should not close connection to intercepted services

**Versions (please complete the following information):**
v2.5.3

**Comment by cindymullins-dw** [comment]
@0x2C6 , we haven’t seen this issue recently, where there are two separate intercepts and the uninstall agent uninstalls both of them.  Have you seen this persist on a more recent version?
