### ISSUE TITLE
Intercept does not work anymore migrating from 2.4.8 to 2.5.3

### ISSUE THREAD

**Issue by JuanRamino** [telepresenceio/telepresence#2482]
**Describe the bug**

When using telepresence with a remote cluster  I can no more start an intercept with telepresence version 2.5.3
Using version 2.4.8 works as expected.
Using telepresence with a local cluster works fine with both versions.

**To Reproduce**
1. When I run 'telepresence intercept...'
2. I see 'telepresence: error: Failed to establish intercept: the agent install timed out.'

**Expected behavior**
Start an intercept

**Versions (please complete the following information):**
 - teleprsence v2.5.3
 - workstation windows 10
 - kubernetes v1.18.6 

**VPN-related bugs:**
We use Zscaler for VPN. Testing VPN with `telepresence test-vpn` has no errors

**Other**
When starting the intercerpt I see the cluster is connected and the traffic-agent sidecar is deployed as expected

Thanks a lot!

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8323173/telepresence_logs.zip)

**Comment by thallgren** [comment]
I'm afraid the logs are all just log-level info, which isn't very helpful when trying to isolate a problem like this. Can you please run `telepresence loglevel debug` and then try the `telepresence intercept`? Ideally, remove all logs before you do that to get rid of all logs that are of no interest.

**Comment by JuanRamino** [comment]
Hello,

Thanks for quick reply!

Here are new clean debug logs

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8331385/telepresence_logs.zip)

**Comment by JuanRamino** [comment]
I see many errors in connector.log like

`
2022-03-23 09:45:42.5250 error   connector/session/agent-watcher : manager.WatchAgents recv: rpc error: code = NotFound desc = session "1f795113-4c41-4d2a-922b-eef03ed86c16" not found
`
`
2022-03-23 09:45:42.5250 error   connector/session/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = NotFound desc = session "1f795113-4c41-4d2a-922b-eef03ed86c16" not found
`
Could it be the issue?

**Comment by JuanRamino** [comment]
Hi,

I close the issue because it seems resolved with latest version, v2.5.6

Thanks
