### ISSUE TITLE
Have CI run on modern OS with systemd-resolved

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#249]
Ubuntu 17.04 has very different resolution method, so we should have a CI run there.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since our CI runs on vm-linux, ubuntu-2004 in circle. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
