### ISSUE TITLE
telepresence: error: connector.Connect: failed to ensure traffic manager: the helm operation timed out.

### ISSUE THREAD

**Issue by DoneSpeak** [telepresenceio/telepresence#2492]
I have never success to run `telepresenc connect` in my macbook pro.

![image](https://user-images.githubusercontent.com/16522248/160413207-68477986-e445-45ef-89ac-c816fa0d7ef1.png)

telepresence version
```
Client: v2.5.3 (api v3)
Root Daemon: v2.5.3 (api v3)
User Daemon: v2.5.3 (api v3)
```

The k8s cluster is start with [microk8s](https://microk8s.io/)

The log files: 
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8363368/telepresence_logs.zip)

```
% telepresence connect                                                                                                      
telepresence: error: connector.Connect: failed to ensure traffic manager: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/Users/ygr/Library/Application Support/telepresence/config.yml"

See logs for details (11 errors found): "/Users/ygr/Library/Logs/telepresence/daemon.log"

See logs for details (18 errors found): "/Users/ygr/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
 ~
% vim /Users/ygr/Library/Logs/telepresence/connector.log                                                                     
 ~
% telepresence version                                                                                                       
Client: v2.5.3 (api v3)
Root Daemon: v2.5.3 (api v3)
User Daemon: v2.5.3 (api v3)
 ~
% telepresence uninstall --everything                                                                                       
telepresence: error: connector.Connect: failed to ensure traffic manager: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/Users/ygr/Library/Application Support/telepresence/config.yml"

See logs for details (11 errors found): "/Users/ygr/Library/Logs/telepresence/daemon.log"

See logs for details (21 errors found): "/Users/ygr/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
 ~
```

**Comment by mschmidt291** [comment]
@DoneSpeak According to your log it says `Unable to connect to TrafficManager: failed to ensure traffic manager: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/Users/ygr/Library/Application Support/telepresence/config.yml"` . Can you try setting the timeout higher? Alternatively you could check your microk8s instance if there are issues with the connector deployment (e.g. image not pulling, connector crashloop etc.). Maybe it's only a timeout problem.

**Comment by XiNiHa** [comment]
I'm having the same issue while trying to connect to AWS EKS (even with increased timeouts). The error changes to `telepresence: error: connector.Connect: the traffic manager gRPC API timed out.` if I [install traffic manager by myself](https://www.telepresence.io/docs/latest/install/helm). Connecting to `minikube` works without any problem. I'm also on M1 Macbook Air with macOS 12.3.

(+ timeouts don't go over 1m even when I have longer values)

(++ I guess the problem was having the EKS cluster on EC2 ARM64(Graviton2) instances, `kubectl logs -n ambassador pods/traffic-manager-....` outputs `standard_init_linux.go:228: exec user process caused: exec format error`)

**Comment by edeandrea** [comment]
I'm seeing this too...

```
╰─ telepresence connect                       
telepresence: error: connector.Connect: failed to ensure traffic manager: failed to clean up leftover release history: the helm operation timed out.  The current timeout 1m0s can be configured as "timeouts.helm" in "/Users/edeandre/Library/Application Support/telepresence/config.yml"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

![image](https://user-images.githubusercontent.com/363447/176010059-eb96991a-db2e-4bc5-bf9a-89ea2d5a1ac3.png)

I'm seeing this in the pod logs in the `ambassador` namespace:

```
Error creating: pods "traffic-manager-5d6bcf4df7-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000700000, 1000709999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

Any thoughts?

**Comment by Sher-Chowdhury** [comment]
> I'm seeing this too...
> 
> ```
> ╰─ telepresence connect                       
> telepresence: error: connector.Connect: failed to ensure traffic manager: failed to clean up leftover release history: the helm operation timed out.  The current timeout 1m0s can be configured as "timeouts.helm" in "/Users/edeandre/Library/Application Support/telepresence/config.yml"
> If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
> ```
> 
> ![image](https://user-images.githubusercontent.com/363447/176010059-eb96991a-db2e-4bc5-bf9a-89ea2d5a1ac3.png)
> 
> I'm seeing this in the pod logs in the `ambassador` namespace:
> 
> ```
> Error creating: pods "traffic-manager-5d6bcf4df7-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000700000, 1000709999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
> ```
> 
> Any thoughts?

I suspect you need to run some `oc adm` commands to get past this, but I can't figure out what they should be. I had thought it's something along the lines of:

```
oc adm policy add-scc-to-user privileged -z default -n ambassador
oc adm policy add-scc-to-group ibm-anyuid-scc system:serviceaccounts:traffic-manager
```

This article might help with troubleshooting this - http://www.freekb.net/Article?id=4200

**Comment by Sher-Chowdhury** [comment]
Actually, this seems to have worked for me:

```
oc project ambassador
oc adm policy add-scc-to-user anyuid -z traffic-manager
```

After doing that, I deleted the deployment's replicaset, to get it refreshed.

**Comment by cindymullins-dw** [comment]
Can you let us know if this is still an issue on MicroK8s on a newer version? The way the traffic manger is installed has changed and uses Helm rather than relying on the CLI.

**Comment by drewfish** [comment]
I just ran into the same "failed to clean up leftover release history" error when using `telepresence helm upgrade` on an AWS EKS cluster. I was able to work around this with `telepresence helm uninstall` then `telepresence helm install`.

**Comment by cindymullins-dw** [comment]
Suggest deleting any former secrets from previous installs as well, since that _may_ also be contributing to this issue.
