### ISSUE TITLE
Agent Install timeout

### ISSUE THREAD

**Issue by nidyaonur** [telepresenceio/telepresence#2504]
**Describe the bug**
telepresence: error: Failed to establish intercept: the agent install timed out. 

**To Reproduce**
1. When I run
```
telepresence intercept service-name--port 8000 --env-file=.env
```

2. I see 
```
telepresence: error: Failed to establish intercept: the agent install timed out.  The current timeout 2m0s can be configured as "timeouts.agentInstall" in "/Users/onur/Library/Application Support/telepresence/config.yml"

See logs for details (99 errors found): "/Users/onur/Library/Logs/telepresence/daemon.log"

See logs for details (4370 errors found): "/Users/onur/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```
4. So I look at connector.log and daemon.log
5. See error
[connector.log](https://github.com/telepresenceio/telepresence/files/8416162/connector.log)
[daemon.log](https://github.com/telepresenceio/telepresence/files/8416163/daemon.log)

I can also share the gather-logs privately when requested by a maintainer

**Expected behavior**
A successful intercepted output

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
Client: v2.5.4 (api v3)
Root Daemon: v2.5.4 (api v3)
User Daemon: v2.5.4 (api v3)
```
 - Operating system of workstation running `telepresence` commands: MAC OS m1 chip
 - Kubernetes environment and Version : aws eks

**Additional context**
I am able to connect to the telepresence, the only problem is in the intercept stage, and sometimes it doesn't timeout after 2 minutes. If doesn't. it continues indefinetely. Largest run before I interrupt took 37m

**Comment by thallgren** [comment]
What does the logs from the intercepted pod show? Can you view the logs from its `traffic-agent` container?
