### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#251]
Here is a first pass at what would make Telepresence ready for 1.0.

Big picture, basic functionality is done. The remaining problems are confidence in how well it works in a variety of environments. Confidence can be increased by more users using it, and by having better automated test coverage.

* Expand CI to have better coverage, with some level of cost/benefit analysis:
  * [ ] Docker on Mac (not currently possible on Travis)
  * [ ] OpenShift, via OpenShift Online paid account or our own cluster
  * [ ] Ubuntu 17.04 (#249)
  * [ ] minikube, minishift (not possible on Travis since it's VM inside VM)
* [ ] Better tests (#259)
* [ ] All current "I can't get started at all" bugs fixed.
* [ ] No severe wide-impact "I can't get started at all" bugs filed for some period of time. Period of time depends on how many users we're getting. A month, perhaps?

**Comment by donnyyung** [comment]
We have since released Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/).
