### ISSUE TITLE
Intermittent connection

### ISSUE THREAD

**Issue by akarokr** [telepresenceio/telepresence#2516]
**Describe the bug**
The connection seems to be very inconsistent, when I first installed, it was working, but when I connect again, connector returns me following error:

`2022-04-08 13:04:53.3625 error   connector/session/agent-watcher : manager.WatchAgents recv: rpc error: code = NotFound desc = session "202c506a-cac5-482c-ac00-b27521cc3ad6" not found
2022-04-08 13:04:53.5062 error   connector/session/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = NotFound desc = session "202c506a-cac5-482c-ac00-b27521cc3ad6" not found
2022-04-08 13:04:55.3973 error   connector/session/remain : rpc error: code = NotFound desc = Session "202c506a-cac5-482c-ac00-b27521cc3ad6" not found`

The traffic-manager pod doesn't show any errors. When I run "telepresence status" it shows everything "working". 

**To Reproduce**
1. Install telepresence locally and inside the cluster (using the default Heml doc)
2. telepresence connect
3. Do some tests for validade the connection
4. telepresence quit
5. telepresence connect

**Expected behavior**
Cluster network accessible through my local env and deployment intercepting working.

**Versions (please complete the following information):**
 - telepresence 2.5.4 (local and server)
 - Linunx Mint 20.3 (local machine)
 - OpenShift Cluster 4.7.38

**Additional context**
I am cluster admin, so it shouldn't have any permission (or anything related to) problems. 

**Logs**
[traffic-manager-5c56f5bc95-dqzzs-traffic-manager.log](https://github.com/telepresenceio/telepresence/files/8453692/traffic-manager-5c56f5bc95-dqzzs-traffic-manager.log) - local logs (I couldn't save the logs when it was working)

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8453686/telepresence_logs.zip) - pod logs

**Comment by thallgren** [comment]
In versions < 2.5.7, the "NotFound desc = Session "202c506a-cac5-482c-ac00-b27521cc3ad6" not found" message is displayed after the client loses connection with the traffic-manager for a duration longer than 15 seconds. The connection loss can be due to flakey network or that the user closes the lid on the laptop. In any case, was fixed in #2545, so I'm closing this ticket.
