### ISSUE TITLE
Openshift: Telepresence 2 pod security context CreateContainerConfigError issue

### ISSUE THREAD

**Issue by ilovechai** [telepresenceio/telepresence#2518]
**Please describe your use case / problem.**
I have installed traffic-manager on namespace A where all my deployments/services reside.
``` helm install traffic-manager --namespace A datawire/telepresence --set securityContext=null```
> securityContext is set to null for openshift (is not specifically documented on the docs)

telepresence connect works fine

So, I tried intercepting my service, but I get the following error
```
telepresence intercept test --port 9080:443 --env-file ./test.env
telepresence: error: Failed to establish intercept: the apply timed out.  The current timeout 1m0s can be configured as "timeouts.apply" in "/Users/user/Library/Application Support/telepresence/config.yml"
```
Looking at the pods it shows CreateContainerConfigError error and after describing the pod, the events in the pod
```
 Type     Reason          Age               From                                              Message
  ----     ------          ----              ----                                              -------
  Warning  Failed          4s (x9 over 90s)  kubelet, worker1.com  Error: container has runAsNonRoot and image will run as root
```
**Describe the solution you'd like**
After debugging, I added the non root ids in securityContext of traffic agent and that made the above error go away
```
securityContext:      
      runAsUser: 65534 # nobody user (the main point it isn't root)
      runAsGroup: 65534 # nobody group (the main point it isn't root)
```
If telepresence is supporting openshift in the future, it would be great if we have a documentation section for openshift as extra configurations are needed for openshift environments. 

**Describe alternatives you've considered**

**Versions (please complete the following information)**
```
 > oc version

Client Version: v4.2.0-alpha.0-657-g51011e4
Server Version: 4.6.52
Kubernetes Version: v1.19.16+3d19195 
> telepresence version
Client: v2.5.4 (api v3)
Root Daemon: v2.5.4 (api v3)
User Daemon: v2.5.4 (api v3)
```
**Additional context**
Add any other context about the feature request here.

**Comment by thallgren** [comment]
Doesn't OpenShift always assign a random, non-root UID when it runs the pod? Or do you have some specific UID ranges assigned? https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids

**Comment by ilovechai** [comment]
@thallgren By default, it does assign random UIDs, but I installed the traffic manager `--set securityContext=null`(which is needed in openshift), without the `securityContext=null` the traffic manager does not install on the env.

**Comment by xhu-cloudera** [comment]
OCP requires scc (SecurityContextConstraint) for traffic manager. I plan to submit a PR to patch the issue for OCP.
