### ISSUE TITLE
Bypass crossorigin

### ISSUE THREAD

**Issue by boehb-efs** [telepresenceio/telepresence#2520]
**Please describe your use case / problem.**
When developing and testing a frontend locally, the backend must provide certain crossorigin rules (allow localhost). 

**Describe the solution you'd like**
Is it possible to run the backend "locally" with telepresence *without* connecting the cluster to the ambassador cloud?

**Describe alternatives you've considered**
CrossOrigin-Rules in every backend that allow localhost (at least in dev-stage).

**Versions (please complete the following information)**
Root Daemon: v2.5.5 (api v3)
User Daemon: v2.5.5 (api v3)

**Additional context**
Spring Boot backends in AKS-Cluster, React frontends

**Comment by thallgren** [comment]
Please redirect questions to our [OSS-forum](http://a8r.io/slack). Tickets are for feature requests and bug reports.
