### ISSUE TITLE
v2.4.11 - Intermittently not able to access services

### ISSUE THREAD

**Issue by suravikumar** [telepresenceio/telepresence#2522]
**Describe the bug**
My team and I are running into an issue where we are able to connect to my cluster through telepresence, but after some time, we get errors when trying to access our services. For context, whenever I finish development when using telepresence, I leave the intercept, and when I want to use it again, I am able to create it again successfully. However after I make the new intercept, I am sometimes not able to get a response from my services, and instead, I get connection timeouts or 'not able to resolve host'. Some other members on my team ran into this issue was well. I tried to clear the DNS cache on my computer, but that didn't resolve this issue. I am only able to get past this after I restart my computer.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/100324086/162836572-df02ab16-e8fb-4887-8594-b4628821774e.png">

I have attached some logs to this report, but I will add more as I am able to reproduce the other behaviors.
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8467876/telepresence_logs.zip)

**To Reproduce**
This issue happens intermittently, but this is the behavior I have noticed when I encounter it:
1. Make initial intercept.
2. Close intercept after development.
3. Change networks (changing location between home and office)
4. Intercept. (telepresence connect and intercept works as expected)
5. Try to use curl command on any service (ex. curl mysql.default)
6. I will not be able to get an empty response (Usually not able to resolve host or connection timed out.)
7. Only able to move past this issue after restarting my computer.

**Expected behavior**
We expect to be able to access our services without any issues. 

**Versions (please complete the following information):**
 -v2.4.11
 - MacOS 12.2.1
 - Google Kubernetes Engine - 1.20.15-gke.1000

**Additional Context**
I mainly notice this issue when I am moving locations between my home and office, but it does sometime happen while I am on the same network. Also, we can only connect to our cluster through a VPN, but we made sure to update our service IP ranges.

**Comment by thallgren** [comment]
Does it make any difference if you do a `telepresence quit` before you change the network?

**Comment by suravikumar** [comment]
I tried that out, but I am still getting the same behavior.

**Comment by prpa** [comment]
[](url)I'm also having these intermittent DNS issues as well. 

I'm using telepresence v2.5.6 in a Windows 10 box.

```bash
> telepresence version
Client: v2.5.6 (api v3)
Root Daemon: v2.5.6 (api v3)
User Daemon: v2.5.6 (api v3)
```

I've captured network traffic with wireshark, and noticed that when valid host names can't be resolved by telepresence DNS is when responses from other DNS servers arrive before telepresence DNS responds. 

**Example 1 - Unsuccessful name resolution by telepresence DNS**

1. host sends DNS query for `kubernetes.default` to telepresence-dns
2. host sends DNS query for `kubernetes.default` to external-dns
3. external-dns sends DNS response `No such name A kubernetes.default SOA a.root-servers.net`
4. telepresence-dns sends DNS response `No such name A kubernetes.default`
5. telepresence-dns sends DNS response `kubernetes.default A 10.43.0.1`

**Example 2 - Successful name resolution by telepresence DNS**

1. host sends DNS query for `kubernetes.default` to telepresence-dns
2. host sends DNS query for `kubernetes.default` to external-dns
3. telepresence-dns sends DNS response `kubernetes A 10.43.0.1`
4. external-dns sends DNS response `No such name A kubernetes SOA a.root-servers.net`


The image below is a screenshot from wireshark for Example 1(red box), and Example 2(green box)

![image](https://user-images.githubusercontent.com/133481/164946588-ff2a152c-d4a6-44e5-b8f8-67229ea11690.png)

And here is the output from telepresence [daemon.log](https://github.com/telepresenceio/telepresence/files/8548680/daemon.log):

![image](https://user-images.githubusercontent.com/133481/164946855-54564a2b-d352-4923-ace7-f06edb6a05a5.png)

**Comment by thallgren** [comment]
@prpa, I think your problem is solved by #2541.

**Comment by prpa** [comment]
@thallgren, thanks a lot! I've downloaded the `release/v2` branch with the fixes, and it worked! I mean, the intermmitment DNS issues are not happening anymore. And I could confirm it quite easily by analyzing the captured traffic with wireshark. 

I think #2541 may also fix @suravikumar issue, and a few other ones related to dns that are currently sitting as open in the backlog.

**Comment by thallgren** [comment]
@prpa thanks for confirming! It helps us a lot.

**Comment by KatieLo** [comment]
@thallgren awesome stuff. Can we close this one as resolved?

**Comment by cakuros** [comment]
> @thallgren awesome stuff. Can we close this one as resolved?

The fix posted looks windows specific, are we sure the fix @thallgren sent will also resolve the top issue?

**Comment by thallgren** [comment]
@cakuros, @KatieLo  it doesn't solve the top issue. That happens on a macOS. and is a different issue altogether.

**Comment by KatieLo** [comment]
correct - I misread the windows-only part of the PR - apologies. We'll still need a a macOS fix, got it.

**Comment by suravikumar** [comment]
I tested v2.5.8 for majority of this week, and I still run into the same issue, but less frequently. I gathered the logs, and I am attaching it to this comment. When looking at the logs, I am seeing that I am able to resolve the service properly, but intermittently, it is thinking my local machine is a service in the cluster and tries to resolve it. Since it is not a service, the DNS resolution is returning NXDOMAIN.

We are also noticing another issue with the traffic manager when testing this version of telepresence. When I am at home, I was able to set up my application locally and redirect traffic from my cluster to my computer, but when I go to the office and do the same, the traffic manager is not able to redirect the traffic. After restarting the traffic manager that was deployed on my cluster, my locally running application was receiving the redirected traffic. It looks like my network change is causing this issue, and I am not sure if this is related to the current issue. 

Please refer to the latest logs: [telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8643860/telepresence_logs.zip)

**Comment by stevenbarlow** [comment]
@suravikumar I wanted to give you an update since there has not been activity on this ticket for awhile. We finally managed to setup a test environment where we can reproduce what we think you are seeing. Now we are trying to figure out what is going on.
