### ISSUE TITLE
Unable to connect local environment to Minikube

### ISSUE THREAD

**Issue by s1apped** [telepresenceio/telepresence#2526]
**Describe the bug**
Unable to connect local environment using IntelliJ and EnvFile plugin to pod deployed on Minikube.

Based on below commands everything seems to be intercepted properly but when I start application in IntelliJ it fails to start.
Im running consul and application fails to connect:
`Connect to consul-server.product-pricing.svc.cluster.local:8500 [consul-server.myns.svc.cluster.local/172.17.0.13] failed: connect timed out`

`telepresence intercept myapp --port 8081:8081 --env-file ./myapp-intercept.env`

```
Launching Telepresence User Daemon
Connected to context test-local (https://192.168.205.26:8443)
Using Deployment international
intercepted
    Intercept name         : myapp
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:8081
    Service Port Identifier: 8081
    Volume Mount Error     : macFUSE 4.0.5 or higher is required on your local machine
    Intercepting           : all TCP connections
```

`telepresence status`

```
Root Daemon: Running
  Version   : v2.5.4 (api 3)
  DNS       :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (0 subnets)
User Daemon: Running
  Version         : v2.5.4 (api 3)
  Executable      : /usr/local/bin/telepresence
  Install ID      : 1b5995fc-1426-468d-9964-037b48a1ddfe
  Ambassador Cloud:
    Status    : Logged out
    User ID   :
    Account ID:
    Email     :
  Status            : Connected
  Kubernetes server : https://192.168.205.26:8443
  Kubernetes context: test-local
  Intercepts        : 1 total
    myapp: mateusz@MacBook-Pro.local
```

Versions (please complete the following information)
Root Daemon: v2.5.4 (api v3)
User Daemon: v2.5.4 (api v3)

Additional context
Spring Boot, Minikube, MacOS

**Comment by thallgren** [comment]
Please run `telepresence loglevel debug`, then reproduce the problem. After that, run `telepresence gather-logs`. You can post your logs here or examine them yourself, they might give you a clue.

**Comment by s1apped** [comment]
@thallgren was able to make it work. I had to set --cni=bridge.

**Comment by thallgren** [comment]
@s1apped Can you please tell us where you set that? The reason I ask is that this might be a good item to include in our troubleshooting guide.

**Comment by s1apped** [comment]
@thallgren it's one of the options available when starting minikube and by default it's set to `auto`
`minikube start --driver=hyperkit  --cni=bridge`
