### ISSUE TITLE
telepresence: error: Failed to establish intercept: intercept in error state NO_AGENT

### ISSUE THREAD

**Issue by damianesteban** [telepresenceio/telepresence#2528]
**Describe the bug**

After updating to the most recent version of Telepresence 2 I'm having an issue creating an intercept. I uninstalled the previously installed agents and created a new one just in case.

**To Reproduce**

run `telepresence intercept my-service --port 3000:1688 --mount=true --namespace=staging`

**Expected behavior**

The intercept should be created.

**Comment by thallgren** [comment]
`NO_AGENT` generally means that there's no pod running for the workflow that you're trying to intercept. Please check how many pods that are running. A `kubectl describe replicaset xxx` is sometimes helpful to check what went wrong.

**Comment by ccchord** [comment]
@thallgren 
I can ensure that my pod is running normally, and traffic agent is injected into the pod.
But it still made a mistake

**Comment by cindymullins-dw** [comment]
We'd suggest upgrading to the latest version.  Please let us know if issues persist.
