### ISSUE TITLE
UDP inbound support

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#255]
Currently telepresence does not support UDP; it ought to if possible.

For `vpn-tcp` mode:

* On Linux we currently use sshuttle's `nat` mode. sshuttle `tproxy` mode supports UDP, I believe. It has issues on older Linux, but if it works on newer Linux we can just use it there and then get UDP support there for free.
* On OS X, not sure. There's a ticket someone filed: https://github.com/sshuttle/sshuttle/issues/155

(For `inject-tcp` mode UDP support would involve patching torsocks: possible but involves writing a bunch of low-level finicky C code.)

**Comment by Ryuzaki42** [comment]
No news about this?

**Comment by donnyyung** [comment]
We currently support routing outbound of UDP, but don't yet support inbound (https://www.getambassador.io/docs/telepresence/latest/reference/tun-device/#both-tcp-and-udp).

**Comment by thallgren** [comment]
Imiplemented
