### ISSUE TITLE
DNS resolution stopped working after updating

### ISSUE THREAD

**Issue by emoyly** [telepresenceio/telepresence#2550]
**Describe the bug**
DNS resolution stopped for all k8s "domains" after updating from like ~~2.3 or so~~ 2.4.11 to 2.5.7.
Curl for example, just spits out a `Could not resolve host` error, and for example with Node.JS it says `getaddrinfo ENOTFOUND`. No matter what i try, it just doesn't seem to work. I haven't changed anything else, apart from updating the version.

**Versions (please complete the following information):**
 - Output of `telepresence version`:
```
Client: v2.5.7 (api v3)
Root Daemon: v2.5.7 (api v3)
User Daemon: v2.5.7 (api v3)
```
 - OS: Ubuntu 20.04
 - Kubernetes environment: Bare metal
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8567317/telepresence_logs.zip)

I am half asleep as of writing this, so apologies for any mistakes.

**Comment by thallgren** [comment]
The only DNS lookup I see in the logs (since the 2.5.7 install) is the one for "authbackend.strairecloud.svc.cluster.local". The client routes that request to the cluster and the the DNS resolver in the cluster fails to resolve it. So telepresence does what I'd expect it to do.

The logs of interest here is the `daemon.log` and the `traffic-manager.log`. In the `daemon.log` you'll see if the request is received and if it's routed to the traffic-manager.

The "bare-metal" cluster, is that running on your workstation? If so, perhaps there's a network collision somehow? Perhaps `telepresence test-vpn` can provide some valuable info.

**Comment by emoyly** [comment]
The bare-metal cluster is running as multiple VMs on a Proxmox server. The development machine (the one running the Telepresence client) is also a VM on that Proxmox server. So there should be no way for the networks to collide. 
Accessing a k8s service through just the service IP seems to work fine. Downgrading to 2.4.11 makes the DNS work.
![Code_PyoiTSbUfd](https://user-images.githubusercontent.com/24597604/166124988-a42f7262-f9bf-421c-9233-13d5c11a8e37.png)
(The 404 error is the expected behavior of that service)

The test-vpn command also returns no issues.

**Comment by thallgren** [comment]
What does the first curl call show? Is `10.110.32.152` the known IP of the authbackend service?
Did you try any other 2.5.x version and found all to fail, or did you try directly with 2.4.11 (I'm trying to pinpoint what it could be that makes a difference for you)?

**Comment by thallgren** [comment]
Also, are you sure that the different VMs on the Proxmox server are running on different isolated networks?

**Comment by emoyly** [comment]
> What does the first curl call show? Is `10.110.32.152` the known IP of the authbackend service?
Yes, sorry, I forgot to mention. That is the authbackend service IP.

I only tried the latest 2.5.7 and the 2.4.11 so far.

The VMs all are connected to each other on a local network (through a pfSense VM), as the proxmox machine only has one external IP.

**Comment by thallgren** [comment]
Telepresence seems to route the DNS queries to the cluster correctly. Then the lookup performed in the cluster fails. The traffic-manager's log show this:
```
LookupHost on traffic-manager: authbackend.strairecloud.svc.cluster.local -> NOT FOUND
```
which means that not even the traffic-manager is able to resolve that name. Would it be possible for you to run a curl command from a pod in the traffic-manager's namespace ("ambassador" unless you've changed it)?

**Comment by emoyly** [comment]
> Would it be possible for you to run a curl command from a pod in the traffic-manager's namespace ("ambassador" unless you've changed it)?

Works through just a test container i deployed using the ubuntu Docker image

```
root@testy-deployment-76bc7f65c9-gtjr8:/# curl http://authbackend.strairecloud.svc.cluster.local:8080
[{"type":"/errors/defaults/4xx/notfound","title":"Not Found","status":404,"detail":"No API endpoints exist on / for request method GET","instance":"/","__problemVersion":"4.0.0"}]
```

**Comment by emoyly** [comment]
This seems to still be happening on the latest version.
Any updates on this issue? @thallgren

**Comment by thallgren** [comment]
Closing this, as I believe all DNS issues have since been resolved.
