### ISSUE TITLE
Better Document: explain root daemon and user daemon

### ISSUE THREAD

**Issue by DanielYWoo** [telepresenceio/telepresence#2568]
**Please describe your use case / problem.**
The README says we can quit with -r or -u, but never explains what they are.

**Describe the solution you'd like**
A clear and concise description of what they are in README

**Describe alternatives you've considered**
N/A

**Versions (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by thallgren** [comment]
You'll find a better description [in our documentation](https://www.getambassador.io/docs/telepresence/latest/reference/architecture/).
