### ISSUE TITLE
How to use multi-port intercept

### ISSUE THREAD

**Issue by caedo960** [telepresenceio/telepresence#2570]
How can I use multi-port intercept (https://github.com/telepresenceio/telepresence/pull/2483) using the latest nightly build `Client: v2.6.0-nightly-d76f7e87 (api v3)` ?

The description of the intercept command only shows how to intercept one port from a service which has multiple ports:

>  -p, --port string               Local port to forward to. If intercepting a service with multiple ports, use <local port>:<svcPortIdentifier>, where the identifier is the port name or port number. With --docker-run, use <local port>:<container port> or <local
                                  port>:<container port>:<svcPortIdentifier>. (default "8080") 

And when using e.g. `telepresence intercept test -p 8000:8000 -p 8001:8001` it only intercepts the latest port.

**Comment by thallgren** [comment]
The `--port` cannot be repeated. Doing so would mean that the repetition must be grouped with `--service`. Also, different ports in a Deployment may use different containers, which in turn may have different sets of environments and volume mounts. So the grouping would also need to include `--mount` and `--env-file`.

Instead of grouping, you'll need to create several intercepts. One for each service/port combination that you want. All intercepts except the first one must also be named differently (use --workload to make intercepts with different name point to the same workload).

**Comment by caedo960** [comment]
Thank you for the explanation.

I tried to create several intercepts one for each service/port combination like this:

```
telepresence intercept -n test test -p 8000:8000
telepresence intercept -n test test-1 --workload test -p 8001:8001
telepresence intercept -n test test-2 --workload test -p 8002:8002
```
However it fails to an error:

`telepresence: error: Failed to establish intercept: intercept in error state AGENT_ERROR: Conflicts with the currently-served intercept "31e8ad5d-c625-4326-8d2b-570914667600:test-test"`

Traffic-agent logs:

```
traffic-agent 2022-05-11 08:06:07.0994 info    client/handleIntercept : Setting intercept "dad689f6-aa46-4df4-979d-d0a608b4945d:test" as ACTIVE                                                                                                                                                                                                                   
traffic-agent 2022-05-11 08:06:07.9454 info    client/handleIntercept : Setting intercept "dad689f6-aa46-4df4-979d-d0a608b4945d:test-1" as AGENT_ERROR; as it conflicts with "dad689f6-aa46-4df4-979d-d0a608b4945d:test" as the current chosen-to-be-ACTIVE intercept
```

Traffic-manager logs:

```
2022-05-11 08:06:04.1913 info    agent-configs : Successfully rolled out test.test                                                                                                                                                                                                                                                                           
2022-05-11 08:06:04.2261 info    agent-injector : Injecting 2 patches into pod test-8487c8f88-.test                                                                                                                                                                                                                                                        
2022-05-11 08:06:04.3579 info    agent-injector : Pod test-8487c8f88-.test already has container traffic-agent and it isn't modified
```

Did I do something wrong here?

**Comment by thallgren** [comment]
No, you're not doing anything wrong. You're hitting a limitation in the OSS-agent. It is only capable of doing one intercept at a time.

**Comment by caedo960** [comment]
Okay, by next release do you mean 2.6?

**Comment by thallgren** [comment]
It will work correctly in 2.6.0 provided that you do `telepresence login` first. That too will change in the near future.

**Comment by ventsislav-georgiev** [comment]
In the case with a single container listening on multiple ports, running the intercept command more than once which in turn starts the same app locally twice is really inconvenient, redundant and also causes issues with collisions (using same local files and ports). The multiple intercepts with grouping of services, volumes, env vars arguments, should be only if the intercepted ports are targeted against different containers.

**Comment by ventsislav-georgiev** [comment]
The debugging of a single app listening on two ports also becomes a hurdle as you will have to open two separate IDEs and attaching to the separate locally running intercepted targets. Which in the case of VSCode is not supported, as you cannot open the same source code in two separate windows. Which means you will also need to copy paste the project twice in order to debug it concurrently for the requests on both ports.

**Comment by aliashahi** [comment]
> It will work correctly in 2.6.0 provided that you do `telepresence login` first. That too will change in the near future.

still not fixed? is there any solution now ?

**Comment by lkoniecz** [comment]
> No, you're not doing anything wrong. You're hitting a limitation in the OSS-agent. It is only capable of doing one intercept at a time. The situation will improve in the near future, but you will need to wait for the next release.

@thallgren any updates?

telepresence version
OSS Client         : v2.16.1
OSS Root Daemon    : v2.16.1
OSS User Daemon    : v2.16.1
OSS Traffic Manager: v2.16.1

still does not work

**Comment by utamas** [comment]
HI @thallgren 

I'm on latest available version ATM (2.17.0) and intercepting a single service that has multiple port is not working.

I'm following the instruction on https://www.getambassador.io/docs/telepresence/latest/reference/intercepts/cli#intercepting-multiple-ports.

This feature is really critical for our use case. 

Context:
we have a k8s deployment with a single container. That container exposes extra port(s) during development so our test infra can do it's job (e.g.: control time). when I start the application locally it also exposes those ports, so what I really need is just really bi-directional proxy between my local and remote ports.

**Comment by utamas** [comment]
So here is what I'm doing:
 - Deploy an app to k8s as deployment with only a single container that exposes four ports (http, grpc, and two tcp based ones to allow our test infra to interact with our app).
 - Correspondingly there is a k8s service with the same ports defined (type ClusterIP).

Then I run:
```shell
telepresence --kubeconfig ~/.kube/config --context microk8s helm install
telepresence connect --kubeconfig ~/.kube/config --context microk8s --namespace test
telepresence intercept --address <my_private_ip> --workload webapp --service webapp --port 8080:80 --mount ./mnt --env-file ./.env webapp

# so far everything works like a charm...

telepresence intercept --address <my_private_ip> --workload webapp --service webapp --port 48090:48090 grpc

telepresence intercept: error: connector.CreateIntercept: Failed to establish intercept: intercept in error state AGENT_ERROR: Conflicts with the currently-served intercept "93fe5d6c-8c74-437c-ad93-b9167ad483dd:webapp"
```

BTW: on some older version this HAS worked.

**Comment by thallgren** [comment]
As I wrote in earlier comment:

> You're hitting a limitation in the OSS-agent. It is only capable of doing one intercept at a time. 

If this feature is critical for your use-case, then I strongly suggest that you switch to a [payed version](https://www.getambassador.io/editions) of Telepresence. Not only will you get much better support that way, you will also get rid of limitations like this.

**Comment by utamas** [comment]
@thallgren Thank you for taking the time to respond and clearing up this question.

> It will work correctly in 2.6.0 provided that you do `telepresence login` first.

Confused me. But It's clear now.

**Comment by jboykin-bread** [comment]
It would be great if this documentation was updated to make it clear that this is a paid feature: https://www.getambassador.io/docs/telepresence/latest/reference/intercepts/cli#intercepting-multiple-ports
