### ISSUE TITLE
Telepresence connect should not reinstall existing traffic manager

### ISSUE THREAD

**Issue by josecv** [telepresenceio/telepresence#2573]
**Please describe your use case / problem.**
If I set up Telerpesence via `telepresence connect` it'll install a traffic manager. I can do the same via `helm` at which point `telepresence connect` will not touch the existing traffic manager installed by helm. However, if I install the helm chart's resources via ArgoCD, or otherwise set up a traffic manager, Telepresence will behave as though there were no traffic manager and try to install its own, which will fight with the existing one.

**Describe the solution you'd like**
There should be an annotation, or another way to communicate to Telepresence that existing resources should not be modified.

**Versions (please complete the following information)**
  - 2.5.8
  - All kubernetes environemnts

**Comment by thallgren** [comment]
Closing this, as it was fixed a long time ago when we introduced Helm. A helm install was never overridden by an auto-install. Today, there's not even an auto-install. You must install explicitly using `telepresence helm install`.
