### ISSUE TITLE
Telepresence is not intercepting

### ISSUE THREAD

**Issue by mostafizurhimself** [telepresenceio/telepresence#2580]
When I try to intercept, I get and error:
`telepresence: error: PANIC: assignment to entry in nil map`

My intercept command is : 
`telepresence intercept dashboard-depl --service dashboard-svc --port 3000:3000 --http-header=name=shakil `

**Comment by thallgren** [comment]
What version of Telepresence are you using?
Where do you see the panic message? Is it in the logs? If so, is there a stack-trace?
