### ISSUE TITLE
Write end-to-end tests that match tutorials

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#259]
#253 was a regression that wasn't caught because the tests didn't exactly match the tutorials. We should have a test doing step-by-step what each tutorial does, just to make sure we're covering new users' first encounter with Telepresence.

**Comment by donnyyung** [comment]
We almost have this with the smoke tests w/ the main exception that we don't check the preview-url since we had no way to authenticate at the time.  We should fix that in our tests.

**Comment by nrv-96** [comment]
@donnyyung , Do we have any update on for end-to-end tests?
