### ISSUE TITLE
Migrating from legacy telepresence 1 to 2: Unable to connect to google cloud sql private ip

### ISSUE THREAD

**Issue by Martin-4Spaces** [telepresenceio/telepresence#2605]
I have been using telepresence 1 for some time now. Very helpful! Thank you.
I'm now trying to migrate to telepresence 2. 
I'm using docker on local machine. 

My old command is
`export TELEPRESENCE_USE_DEPLOYMENT=1 && telepresence --namespace <namespace name> --swap-deployment <deployment name> --expose 80 --docker-run --rm -v$(pwd):/var/www/html <local docker container name>`

New command is
`telepresence intercept <deployment name> --namespace <namespace name> --port 80 --docker-run -- --rm -v$(pwd):/var/www/html <local docker container name>`

It spins up fine.
```
Using Deployment portal
intercepted
    Intercept name         : ...
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:80
    Service Port Identifier: http
    Volume Mount Point     : /var/folders/wl/rc49xrc974zfznrs66mdnm340000gn/T/telfs-2438105631
    Intercepting           : all TCP connections
```

I can reach other containers in the remote cluster. But I can't reach the cloud sql private ip. It worked perfectly with the legacy telepresence. All incoming traffic are fine. 
My cluster has everything setup to use google cloud private ip as connection. It has worked for years now. Its only when I use the new telepresence that I cannot connect.

Any ideas out there?

**Comment by intxcc** [comment]
Hi @Martin-4Spaces 

with telepresence 2 not all outgoing traffic is routed through the VPC.

Did you try to add the IP (range) to also-proxy in telepresence 2?

https://www.telepresence.io/docs/latest/reference/config/#alsoproxy

**Comment by Martin-4Spaces** [comment]
@intxcc 
I did not know about this. Thank you!
It works now - after adding the ip to "also-proxy".
