### ISSUE TITLE
Telepresence fails to connect with no error in logs 

### ISSUE THREAD

**Issue by NingGelin** [telepresenceio/telepresence#2612]
Note：Translate via Google
Hi，first of all thank you for taking your time to help me with the problem，The connection error timeout on win7, there is no log, the same operation process is successful on win10.

os：win7
version：v2.6.4
network：no network

![image](https://user-images.githubusercontent.com/42860920/170157105-c4f03d49-ee1a-47f7-9f9e-d5b73130c32b.png)

**Comment by NingGelin** [comment]
It seems to be because there is no network。

**Comment by thallgren** [comment]
Our Windows binaries are for Windows 10 and up. We don't build binaries for Windows 7 and that's unlikely to change, given that Microsoft ended the support for it in January 2020.
