### ISSUE TITLE
Permission denied problem during execute on Ubunu

### ISSUE THREAD

**Issue by Lxrdknows77** [telepresenceio/telepresence#2619]
**Describe the bug**
When i try to run telepresence on my Ubuntu 18.06 i got Permission denied error.

1. When I run ./bin/telepresence connect
2. I get error

```
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
telepresence: error: failed to launch the connector service: /vagrant/Projects/postgresql-service-operator/bin/telepresence connector-foreground: fork/exec /vagrant/Projects/postgresql-service-operator/bin/telepresence: permission denied

See logs for details (22 errors found): "/home/vagrant/.cache/telepresence/logs/daemon.log
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8785280/telepresence_logs.zip)

```

**Expected behavior**
Telepresence runs as expected.

**Versions (please complete the following information):**
 - Client: v2.6.4 (api v3)
 - Ubuntu 18.04.6 LTS
 - kind v0.12.0 go1.17.8 linux/amd64
 - Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by thallgren** [comment]
I don't think this is a telepresence problem given that it's a simple command exec that fails on a permission denied. How did you install telepresence on your vagrant client?

**Comment by Lxrdknows77** [comment]
@thallgren thanks for the answer, i installed it like this:
```
curl -fL https://app.getambassador.io/download/tel2/${GOHOSTOS}/amd64/latest/telepresence,telepresence -o $(GOBIN)/telepresence 
chmod u+x $(GOBIN)/telepresence  
```

**Comment by thallgren** [comment]
Please try:
```
curl -fL https://app.getambassador.io/download/tel2/${GOHOSTOS}/amd64/latest/telepresence -o $(GOBIN)/telepresence
chmod u+x $(GOBIN)/telepresence
```
I.e. without an additional `,telepresence` in the URL.

What is `$(GOBIN)` and `$(GOHOSTOS)` set to? And what is the current directory when you run `./bin/telepresence connect` ?
I'm just trying to figure out what it could be that causes the permission denied. Seems you have a bad executable somewhere that gets picked over the one that you start (which is odd, it should really be the same binary).

**Comment by Lxrdknows77** [comment]
@thallgren yes, sorry there is no one more telepresence in curl, only one as you mentioned above. 
`curl -fL https://app.getambassador.io/download/tel2/${GOHOSTOS}/amd64/latest/telepresence -o $(GOBIN)/telepresence`

Where
```
GOBIN - path of current GO project dir, therefore full install path is something like $pwd/bin/telepresence
GOHOSTOS=linux
```
ls -all
```
total 109280
drwxrwxrwx 1 vagrant vagrant        0 Jun  4 13:26 .
drwxrwxrwx 1 vagrant vagrant     8192 Jun  3 09:41 ..
-rwxrwxrwx 1 vagrant vagrant 20422420 Jun  3 09:41 controller-gen
-rwxrwxrwx 1 vagrant vagrant 21070424 Jun  3 09:42 kustomize
-rwxrwxrwx 1 vagrant vagrant 70397353 Jun  4 13:27 telepresence
```
And also works good 
```
`./bin/telepresence version`
Client: v2.6.5 (api v3)
Root Daemon: not running
User Daemon: not running
```

But when i want connect 
```
 `./bin/telepresence  connect
```

I got this error as above.

**Comment by thallgren** [comment]
Do you get the same error if you do
```
/vagrant/Projects/postgresql-service-operator/bin/telepresence connect
```
?

**Comment by Lxrdknows77** [comment]
@thallgren  Yep

**Comment by thallgren** [comment]
Can you please try moving the `telepresence` binary to some other directory (`/tmp` perhaps?) and try executing it from there? I suspect that the filesystem somehow imposes an exec restriction.

**Comment by Lxrdknows77** [comment]
@thallgren Interesting, but in tmp i got this one:

`telepresence: error: connector.Connect: failed to ensure traffic manager: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/home/vagrant/.config/telepresence/config.yml"`

**Comment by thallgren** [comment]
Then there's some restrictions on the other folder that prevents a process from doing fork/exec on itself.

The helm timeout can be configured in the file that is mentioned in the error message. Add something like:
```
timeouts:
  helm: 60s
```
