### ISSUE TITLE
Need earlier sudo with clear/better prompt

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#262]
If a `sudo` will be required, it should happen as early as possible. Rather than producing a bare password prompt, the prompt should be something very clear, like "sudo for Telepresence."

- [x] `sudo` as early as possible
- [x] Clear/explicit prompt (#720)

**Comment by ark3** [comment]
- `SUDO_FOR_DOCKER`
- `MAC_LOOPBACK_IP`
- sshfs (only with Docker?)
- sshuttle (vpn_tcp)

**Comment by ark3** [comment]
If a password is required, we should make it clear that Telepresence has initiated the `sudo` command and explain why. One approach would be to set/override the environment variable `SUDO_PROMPT` with that information.  However, I'd rather not make the user's `sudo` workflow surprising or confusing. 

To avoid messing with `SUDO_PROMPT`, use something like `sudo -n true` to test whether privileged execution will require a password. This command will succeed if no password is required (either because it's never required, or because the user typed it recently enough). Otherwise, the command will fail. Upon failure, spew some explanatory text ("Telepresence requires your password for `sudo` to run Docker/sshfs/whatever") and then prompt with something like `sudo -v`. 

This latter approach won't help if the OS configuration requires a password for _every_ `sudo` command. Let's hope that is an uncommon configuration.

**Comment by ddehghan** [comment]
Yeah. this is pretty scary to ask for a password without any context. also it is not clear what password it needs. local machine or remote machine, kubernetes, docker root password etc.

**Comment by ark3** [comment]
I believe this was completed as a side effect of #732.

**Comment by Imunhatep** [comment]
Not sure what was fixed.. but sudo pass promt still does not explain what for it asks for root:
> T: Invoking sudo. Please enter your sudo password.

**Comment by ark3** [comment]
Agreed. Let’s add a link to appropriate docs at that prompt.
