### ISSUE TITLE
GKE Autopilot Issue?

### ISSUE THREAD

**Issue by screenvidio** [telepresenceio/telepresence#2634]
**Describe the bug**
I was going through the exercise in https://cloud.google.com/community/tutorials/telepresence-and-gke for telepresence.  
From what I can tell, a Standard GKE cluster worked fine but an Autopilot one did not.

The couple of times I tried this I got the following sort of message.
`telepresence: error: connector.Connect: failed to ensure traffic manager: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm"`.

So what I did in this was the following.

1. I first created an Autopilot GKE Cluster.2. 
2. I followed the instructions in the tutorial listed above.  (There were some errors in the document, such as --port being needed that I adjusted for.)   I was able to get the services and pods created just fine, it was when trying to connect that things went haywire.

I am using a Mac M1 computer and for Standard Cluster the example **WORKS FANTASTICALLY**.

**Comment by screenvidio** [comment]
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8836269/telepresence_logs.zip)
Here is the log file I generated to try to help get info for your crew.

**Comment by alon7** [comment]
From my experience telepresence doesn't work on GKE Autopilot because it doesn't have the NET_ADMIN capability.
https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#linux_workload_limitations

Although I didn't see the exact same error I think it might be the same reason.

**Comment by thallgren** [comment]
@alon7 There are two things in Telepresence that will require `NET_ADMIN` privileges. I don't think @screenvidio encounters any of them:
1. The telepresence root daemon (running in the client) must have `NET_ADMIN` privileges to configure the VIF (the TUN device). Judging from the logs, there's no problem with that.
2. A telepresence init container may be inserted into an intercepted pod under certain circumstances, and that is when the service's `targetPort` is numeric. This can often be circumvented by using a symbolic `targetPort` instead. Won't work if the service is headless (`ClusterIP: None`) though, and that's the only known case when `NET_ADMIN` is required in the cluster.

This might be as simple as following the advice in the error output and configure the timeout. Add this to the `config.yml` file:
```
timeouts:
  helm: 60s
```

**Comment by alon7** [comment]
@thallgren thanks for the explanation. So there should be no issue running telepresence on GKE Autopilot? 
I can try to re-create the issue I've seen and share.

**Comment by thallgren** [comment]
@alon7 please do. We will try and figure it out and, if possible, solve the problem.

**Comment by screenvidio** [comment]
I created another Autopilot cluster to try this.
I tried connecting after it failed again and this time I see the services for Telepresence installed.
However, now, with the Go sample app running and all, when I try to do the intercept I get the following.

`❯ telepresence intercept dataprocessingservice --port 3000
telepresence: error: rpc error: code = DeadlineExceeded desc = request timed out while waiting for agent dataprocessingservice.default to arrive`

Is this a case of Autopilot being slower at startup things?
Is there a way to prevent this?
Is it maybe something else?

The curl command for the example works fine.

BTW, my config.yaml is blank by default and I struggled to find where documentation for that setting. 
When I tried in the YAML I got the following before.
`WARN[0000] file /Users/rollin.crittendon/Library/Application Support/telepresence/config.yml, line 1: unknown key "timeouts.helm"`

Thanks again for discussion on this.

**Comment by thallgren** [comment]
Seems you entered that key verbatim as `timeouts.helm`. It's a hierarchical name and you need to reflect that:
```
timeouts:
  helm: 60s
```

**Comment by alon7** [comment]
Hi @thallgren I just noticed the GKE Autopilot error happened again.
![Screen Shot 2022-06-19 at 18 56 36](https://user-images.githubusercontent.com/176762/174489745-4e4b38b2-87df-4cd6-9476-496f3e151c12.png)

It happened when I tried to `telepresence connect` and it failed. 

Let me know if there's anything else that I can attach that'll be helpful

**Comment by thallgren** [comment]
@alon7 are you using numeric ports, but not on headless services? If so, [this section](https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#injected-init-container-doesnt-function-properly) in the docs might be helpful.

**Comment by alon7** [comment]
@thallgren just an update here - it seemed to work, I didn't see that known issue before thank you for pointing it out.

**Comment by juanfbl9307** [comment]
@alon7 I'm dealing with the same issue, how did you solve it?

**Comment by gbajson** [comment]
@alon7 
I also have a problem with:

`telepresence intercept: error: connector.CreateIntercept: Error creating: admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-default-linux-capabilities]":["linux capability 'NET_ADMIN' on container 'tel-agent-init' not allowed; Autopilot only allows the capabilities: 'AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT,SYS_PTRACE'. Requested by user: 'system:serviceaccount:kube-system:replicaset-controller', groups: 'system:serviceaccounts,system:serviceaccounts:kube-system,system:authenticated'."]}
Hint: if the error mentions resource quota, the traffic-agent's requested resources can be configured by providing values to telepresence helm install`

Have you solved it?

**Comment by krisztiansala** [comment]
I could solve this by using a named port. Let's say the port is 8080.

The deployment should look like:
```yaml
...
ports:
    - name: http
      containerPort: 8080
      protocol: TCP
...
```
The service should look like:
```yaml
...
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
...
```

After this, simply run: `telepresence intercept <deployment-name> --port 8080 --env-file <file> -n <namespace>`

**Comment by alon7** [comment]
Sorry for the late reply here, but yeah, @krisztiansala is absolutely right!

**Comment by sourceful-karlson** [comment]
In summary, does Telepresence works on GKE Autopilot or not?

**Comment by thallgren** [comment]
Telepresence works with GKE Autopilot.
