### ISSUE TITLE
Having issues with connecting

### ISSUE THREAD

**Issue by jeremyw-dobeu** [telepresenceio/telepresence#2637]
**Describe the bug**

Additionally, if you are using Telepresence 2.4.4 and above, please use
`telepresence loglevel debug` to ensure we have the most helpful logs,
reproduce the error, and then run `telepresence gather-logs` to create a
zip file of all logs for Telepresence's components (root and user daemons,
traffic-manager, and traffic-agents) and attach it to this issue. See an
example command below:
```
telepresence loglevel debug

* reproduce the error *

telepresence gather-logs --output-file /tmp/telepresence_logs.zip

# To see all options, run the following command
telepresence gather-logs --help
```

Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /home/jeremyw/.cache/telepresence/logs /home/jeremyw/.config/telepresence
[sudo] password for jeremyw:
telepresence: error: connector.Connect: the traffic manager gRPC API timed out.  The current timeout 15s can be configured as "timeouts.trafficManagerAPI" in "/home/jeremyw/.config/telepresence/config.yml"

See logs for details (12 errors found): "/home/jeremyw/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .

**To Reproduce**
1. When I run '...'
2. I see '....'
3. So I look at '....'

**Expected behavior**

**Versions (please complete the following information):**
 - Output of `telepresence version`
 - Operating system of workstation running `telepresence` commands
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
 - Which VPN client are you using?
 - Which VPN server are you using?
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf

**Additional context**

**Comment by thallgren** [comment]
@jeremyw-dobeu may I suggest that instead of just including the template, you actually follow its instructions? I'm closing this tiecket because it contains absolutely nothing that we can act on. Try following the suggestion in the error message. If that doesn't work, file a proper ticket.
