### ISSUE TITLE
Support specifying allow-cidr and deny-cidr via command line

### ISSUE THREAD

**Issue by mindw** [telepresenceio/telepresence#2641]
**Please describe your use case / problem.**
Support specifying allow-cidr and deny-cidr via command line.  Patching kubeconfig is hard:
1. Which kubeconfig? the default? one the ones specified KUBECONFIG?
2. Kubeconfig may be autogenerated needing re-patching every time.
3. patching YAML is hard - even with tools like yq

**Describe the solution you'd like**
Add `--allow-cidr` and `--deny-cidr` command line options to `telepresence connect`.

**Describe alternatives you've considered**
Environment variables.

**Versions (please complete the following information)**
Client: v2.6.4 (api v3)
Root Daemon: v2.6.4 (api v3)
User Daemon: v2.6.4 (api v3)
EKS 1.21

**Comment by thallgren** [comment]
I can see how we could add these flags to the `telepresence connect` command. @mindw  Is that what you're envisioning?

**Comment by mindw** [comment]
> I can see how we could add these flags to the `telepresence connect` command. @mindw Is that what you're envisioning?

@thallgren indeed it is. Tx!

**Comment by mindw** [comment]
dup of #2950 , fixed in #2987
