### ISSUE TITLE
Conflicts with the currently-served intercept

### ISSUE THREAD

**Issue by GuyCarmy** [telepresenceio/telepresence#2645]
**Describe the bug**
Getting ```elepresence: error: Failed to establish intercept: intercept in error state AGENT_ERROR: Conflicts with the currently-served intercept "44db34b9-2267-4663-80f8-7b3b3b396759:deployment-name"``` often.

*logs were provided and examined by @thallgren already

**To Reproduce**
1. Running an intercept
2. losing connectivity (shutting down wifi, commuting from office to home, etc)
3. trying to intercept same service again, but the local client creates a new id for the intercept
4. See the conflict error above (the traffic-manager is locked on the intercept that the local client already lost)

**Expected behavior**
The local client should persist the id and then try to intercept again with the same id.
Another option is that there will be a way to manually close the currently served intercept (uninstalling the agent doesnt do the trick, killing the traffic-manager's pod, does.)

**Versions (please complete the following information):**
 - Output of `telepresence version` - Client: v2.6.6 (api v3)
 - Operating system of workstation running `telepresence` commands - MacOS, both 11 and 12
 - Kubernetes environment and Version - happens both GKE and AKS, 1.21 and 1.22

**Additional context**
Everything was discussed in this thread in slack
https://datawire-oss.slack.com/archives/CAUBBJSQZ/p1654771736018089

**Comment by sambrex** [comment]
@GuyCarmy how did you kill the traffic managers pod? I'm running into the same issue

**Comment by GuyCarmy** [comment]
> 

Just deleted the pod

**Comment by richardscarrott** [comment]
I got this, had to kill traffic manager

```
Client: v2.6.6 (api v3)
Root Daemon: v2.6.6 (api v3)
User Daemon: v2.6.6 (api v3)
```
