### ISSUE TITLE
is it possible to let the telepresence output verbose information

### ISSUE THREAD

**Issue by jiangxiaoqiang** [telepresenceio/telepresence#2657]
When I using this command to connect the remote cluster, is it possible to make the telepresence output the verbose information?

`telepresence connect verbose
`

**Comment by thallgren** [comment]
We don't have a specific `verbose` flag but we do log a log of information, and it easily avaliable. You can view it using a command like this (log file location is different on different platforms, see docs for more info):
```console
$ tail -n400 -F /home/thhal/.cache/telepresence/logs/connector.log
```
and control the verbosity with:
```
$ telepresence loglevel debug # or warn, info, trace
```
You may also use kubectl to log what's happening in the traffic-manager and the intercepted pod.
