### ISSUE TITLE
is it possible to make the telepresence compatible for each verison

### ISSUE THREAD

**Issue by jiangxiaoqiang** [telepresenceio/telepresence#2658]
every time upgrade the telepresence, it will make some breaking changes!! Is it possible to make the telepresence compatible for each version? or compatible for most of the features. do not make it break after upgrade please.

**Comment by thallgren** [comment]
There has been one breaking change, in one direction, and it is well explained in our documentation.
Traffic managers >= 2.6.0 will not accept clients older than 2.6.0. That's about it.

What breaking changes besides that are you experiencing?
