### ISSUE TITLE
login to ambassador cloud on each action

### ISSUE THREAD

**Issue by danikp** [telepresenceio/telepresence#2667]
**Describe the bug**
after upgrade to v2.6.7 and running `telepresence dashboard`, each and every command triggers tab of login to ambassador cloud

**To Reproduce**
1. When I run any teleprsence command
2. I see new tab opened in browser to login to https://app.getambassador.io/auth/realms/production/protocol/openid-connect/auth?client_id=telepresence-cli&code_challenge=0v8iC7_Sndpn18k7B82-hteTIdXf5zZPUFdjdR1tLzA&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A51461%2Fcallback&response_type=code&scope=openid+profile+email&state=0c044271-20da-4381-a935-ac0b8e349bcc
3. command finishes as expected

**Expected behavior**
not to open new tab on each command

**Versions (please complete the following information):**
 - Output of `telepresence version` 
 - An update of telepresence from version 2.6.7 to 2.6.8 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client: v2.6.7 (api v3)
Root Daemon: v2.6.7 (api v3)
User Daemon: v2.6.7 (api v3)
 - Operating system of workstation running `telepresence` commands
 - MacOS 12.4
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Azure cloud

**Additional context**
at some point saw line "installing encanced free client". what does that mean and where it located ?

**Comment by yildizbilal** [comment]
You can find the "enhanced free client", where also the `config.yaml` is located. For MacOS it is under `~/Library/Application\ Support/telepresence/` - [for other OS](https://www.telepresence.io/docs/latest/reference/config/). You fill find it there named `telepresence-pro`. If you dont want to use it anymore you can delete it and also the related entry in the `config.yaml` then the "normal" CLI of telepresence will be used.

**Comment by danikp** [comment]
thanks, removed whole content of that directory and everything works like a charm. I think worth adding documentation on that, cause that "upgrade" was unexpected and unclear how to solve it

thanks for solution

**Comment by nextlevelshit** [comment]
FYI, for linux navigate to: `/home/<USER>/.config/telepresence` and I've added also this to my config.yml:

```yml:config.yml
cloud:
  skipLogin: true
```

Btw, super annoying @thallgren @LukeShu and so on ...

**Comment by thallgren** [comment]
This issue was fixed some time ago. The traffic-manager can be configured to run in single-user mode, and will then not require a login. It can also run in team-mode where a license is required, but once installed in the cluster, there will be no need to login. A login can also be made using an api-key which gets automatically renewed as long as the client is connected.

Another option is to download the free OSS client from this repository's release page. It doesn't even have a login command.

Closing this ticket. Feel free to reopen if you feel that we should provide more options in this area.
