### ISSUE TITLE
Telepresence - aws jump host - many environments

### ISSUE THREAD

**Issue by przelew** [telepresenceio/telepresence#2668]
Hi 

Sorry for posting this is bug section but it also not a feature.
I work in a bank and I'm trying to convince my DevOps team to install Telepresence on our Kubernetes Server on AWS.
I did my prove of concept locally on DigitalOcean and debug in local Intelij - worked well.
But I see 2 differencies between my local development and my banking dev environment.
1) I dont have locally kubectl available. I have to log via Jump Host. - I mean I log to server, and then from that server I log to another one, and then I have - kubectl available on that server.  
Question - How Telepresence can work in this situation ?? I read about Telepresence proxying but before I dig in it I wanted to ask is it a right way.

2) I have 3 separate envs - dev, test, prod. I have a lot of integrations. So now, if teoretically DevOps will install Telepresence on DEV and TEST  and I dont have this all Integrations ULRS/Credentials - all this security stuff 
Question - In my prove of concept it was easy - every credential was known. When I would switch to different environment like DEV or TEST will it work easily ?? I know that there is option to export 'envs' to file.

Thank you for Your help :)

**Comment by Patrick0308** [comment]
Same question about jump server.

**Comment by Patrick0308** [comment]
Making jump server  as a socks proxy can solve my problem.
1. `ssh -gfTND 9999 jumphost` Creating a SOCKS tunnel by ssh 
2. Set `.kube/config` cluster.proxy-url:
```
apiVersion: v1
clusters:- cluster:
    certificate-authority-data: ****
    proxy-url: socks5://127.0.0.1:9999 ## local proxy port
    server: https://api-server
  name: eks-1
```
3. Finally executing `telepresence connect`

**Comment by cindymullins-dw** [comment]
Closing as there seems to be a workaround available for this issue/use case.
