### ISSUE TITLE
telepresence: error: rpc error: code = Canceled desc = grpc: the client connection is closing

### ISSUE THREAD

**Issue by magiskboy** [telepresenceio/telepresence#2680]
**Describe the bug**
```
telepresence loglevel debug

telepresence: error: unable to parse manager.Version: rpc error: code = Canceled desc = grpc: the client connection is closing

telepresence gather-logs --output-file /tmp/telepresence_logs.zip

# To see all options, run the following command
telepresence gather-logs --help
```

**To Reproduce**
1. When I run 'telepresence connect' and connect succesfully
2. I see 'Root Daemon: Running
  Version   : v2.6.8 (api 3)
  DNS       :
    Remote IP       : <nil>
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - ***
User Daemon: Running
  Version         : v2.6.8 (api 3)
  Executable      : ***
  Install ID      : 6aeee3f1-9217-4069-a86c-fa215fbbf87f
  Ambassador Cloud:
    Status    : Logged out
    User ID   :
    Account ID:
    Email     :
  Status            : Connected
  Kubernetes server : ***
  Kubernetes context: dev
  Intercepts        : 0 total'
3. Then I run 'telepresence intercept website-management-core-app --port 8000:http --env-file ~/Development/teko-web/sites/website-management/.env.dev'
4. See error 'telepresence: error: unable to parse manager.Version: rpc error: code = Canceled desc = grpc: the client connection is closing'

**Expected behavior**
Intercept service succesfully

**Versions (please complete the following information):**
 - Telepresence version: Client: v2.6.8 (api v3)
Root Daemon: v2.6.8 (api v3)
User Daemon: v2.6.8 (api v3)
 - K8s version: Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"archive", BuildDate:"2022-02-18T22:31:12Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
- OS: arch linux

**Comment by ciyer** [comment]
I had this problem and was able to fix it by running 
```
telepresence quit -ur
```

And then 
```
telepresence connect
```

**Comment by cindymullins-dw** [comment]
If Telepresence gets into this state, it is recommended to run the commands above.  Thanks, @ciyer .  @magiskboy if that doesn't help feel free to reopen.
