### ISSUE TITLE
PodInitializing

### ISSUE THREAD

**Issue by ccchord** [telepresenceio/telepresence#2691]
**To Reproduce**
1. When I run 'telepresence intercept nginx-deployment --port 80 -n temp'
2. I see 'telepresence: error: rpc error: code = DeadlineExceeded desc = request timed out while waiting for agent nginx-deployment.temp to arrive
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .'
3. traffice-manager Error：'agent-configs : Issuing a systema request without ApiKey or InstallID may result in an error'
4.Container Error：'Failed to load logs: container "nginx" in pod "nginx-deployment-67b85b6cd-gv28b" is waiting to start: PodInitializing'

**Comment by cindymullins-dw** [comment]
Sorry to have missed this.  I think we'd need to know your OS, any VPN in place to make suggestions.  As this is pretty old now, you could try 2.19.  We've made some recent fixes that might help with this error.
