### ISSUE TITLE
Integration test suite is overriding cluster installation even if installed via helm

### ISSUE THREAD

**Issue by raphaelreyna** [telepresenceio/telepresence#2698]
The integration test suite does not seem to be respecting installations via helm.
Running the test suite against a cluster with tp already installed leaves it in a bad state which can be resolved by resetting the TLS cert and the mutating webhook.

**To Reproduce**
1. Install tp via helm.
2. Run integration test.
3. Observe the the tp installation in the cluster is in a bad state.

**Expected behavior**
For the tp installation in the cluster to left in a clean state.

**Versions (please complete the following information):**
v2.6.8

**Comment by cindymullins-dw** [comment]
Apologies for not replying on this issue.  If it persists on recent versions please let us know.
