### ISSUE TITLE
telepresence no error ouput when connect failed

### ISSUE THREAD

**Issue by jiangxiaoqiang** [telepresenceio/telepresence#2701]
**Describe the bug**

when the second time(the previous connect disconnect for some reason) I use the `telepresence connect` command to connect the k8s cluter, there is no message output:

```
➜  ~ telepresence connect
➜  ~

```

actually the connection did not success.

**To Reproduce**
1.  connect to k8s cluster
2. wait the disconnect for some reason(for example a long time no interaction or when you go out for lanuch and return back to your PC)
3. reconnect to cluster but failed with no error

**Expected behavior**

connection failed without any error message.

**Versions (please complete the following information):**

```
➜  ~ telepresence version
Client: v2.6.8 (api v3)
Root Daemon: v2.6.8 (api v3)
User Daemon: v2.6.8 (api v3)

```

BTW: I have already change the loglevel to trace but still no information output when uisng `telepresence connect` command.

**Comment by thallgren** [comment]
What makes you think that the connect failed?
