### ISSUE TITLE
[Kind] During microservices tests with telepresence always show error with connection

### ISSUE THREAD

**Issue by gawsoftpl** [telepresenceio/telepresence#2703]
## What happend
1. I have kubernetes cluster run in docker via KIND
2. When I run integration tests with multiple microservices I received errors while one microservice try connect with other 
2.1 sometimes return error dns cant resolve host dns:apidata.default -> this microservice is grpc headless
 ```
Error: 14 UNAVAILABLE: Name resolution failed for target dns:apidata.default:4770
```
 2.2 sometimes throw timeout error while connect with REST microservices dashboard-data
 2.3 sometimes throw error disconnect with microserice rabbitmq
 2.4 sometimes throw error disconnect with microservice redis 
 2.5 sometimes when I run command:
 ```sh
 curl dashboard-data.default:3000
```
curl will show response after 3-4 seconds. 

## After reset telepresence
When I reset telepresence connection, everything works fine.

## In k8s cluster
Test is full working while run it direct in cluster without telepresence. 
With telepresence tests, always show error with connection

## My system
```sh
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

```sh
cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad
search home
```
```
telepresence version
Client: v2.6.8 (api v3)
Root Daemon: v2.6.8 (api v3)
User Daemon: v2.6.8 (api v3)
```

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9200432/telepresence_logs.zip)

**Comment by cindymullins-dw** [comment]
Apologies for having missed this issue.  Please upgrade to the latest version and let us know if you're still running into this error for your use case.
