### ISSUE TITLE
Conflict with traffic-agent and envoy sidecars

### ISSUE THREAD

**Issue by arkpoah** [telepresenceio/telepresence#2704]
**Describe the bug**
We use consul connect in ours pods that deploys an envoy sidecar, and we get a conflict with telepresence.
When we try to intercept a service, traffic-agent sidecar is deployed in the new pod and brings an envoy service on port 19000, then envoy-sidecar (for consul connect) container tries to start but it fails due to port 19000 already in use.

Process in traffic-agent container : 
```
➜ kctl exec -it documentation-c5977cff7-j9zpt -c traffic-agent sh
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 app-sidecar agent
   15 root      0:00 {ld-musl-x86_64.} ld-linux-x86-64.so.2 --argv0 envoy --preload /lib/libgcompat.so.0  -- /usr/local/bin/envoy -l warn -c bootstrap-ads.pb --base-id 1
```

And the port uses by this process :
`tcp        0      0 127.0.0.1:19000         0.0.0.0:*               LISTEN      15/ld-linux-x86-64.`

Errors logs in envoy sidecar : 
```
➜ kctl logs documentation-c5977cff7-j9zpt -c envoy-sidecar 
[2022-07-28 14:09:12.081][1][info][main] [source/server/server.cc:353]   response trailer map: 168 bytes: grpc-message,grpc-status
[2022-07-28 14:09:12.084][1][info][main] [source/server/server.cc:500] admin address: 127.0.0.1:19000
[2022-07-28 14:09:12.084][1][critical][main] [source/server/server.cc:113] error initializing configuration '/consul/connect-inject/envoy-bootstrap.yaml': cannot bind '127.0.0.1:19000': Address already in use
[2022-07-28 14:09:12.084][1][info][main] [source/server/server.cc:815] exiting
cannot bind '127.0.0.1:19000': Address already in use
```

**To Reproduce**
Use telepresence with a pod using consul connect

**Expected behavior**
Having a configurable port for the envoy process in traffic-agent container

**Comment by thallgren** [comment]
This sounds like a very reasonable request.

**Comment by thallgren** [comment]
The traffic-agent side of this was addressed in the smart-agent version 1.12.10.

**Comment by arkpoah** [comment]
I upgraded chart to 2.7.6 version and traffic-agent to 1.12.12 but envoy port still binds on 19000 port in traffic-agent container.
I also don't find any parameter in chart about it, how can I change the port ?
Thanks

**Comment by thallgren** [comment]
Sorry if I was unclear. There's a traffic manager part of this that hasn't been released just yet. Keep an eye out for the 2.8.0 release.

**Comment by arkpoah** [comment]
It works fine with 2.8.0 version, thx !

**Comment by cindymullins-dw** [comment]
Closing as resolved.
