### ISSUE TITLE
Intercept generates an invalid `.env` file when multiline variables are present

### ISSUE THREAD

**Issue by jfmyers9** [telepresenceio/telepresence#2718]
**Describe the bug**
When intercepting a deployment with a multi-line environment variable, `telepresence intercept` generates an invalid `.env` file which results in a failure when paired with `--docker-run`.

**To Reproduce**
1. When I run `telepresence intercept <deployment> --docker-run -- ...`
2. I see `docker: poorly formatted environment: variable '"keys": [' contains whitespaces.`

**Expected behavior**

I don't really know because of https://github.com/moby/moby/issues/12997, but it would be great if we could at least have an `.env` file that is parseable and then document the multiline limitation.

I was thinking about this approach in which we escape the environment variable as `ENV="..."`: https://github.com/jfmyers9/telepresence/commit/8dfb4599ec9d192208ab5fd2fcb14ff79d5d6f90 but it doesn't work as expected as Docker treats anything after the `=` literally.

Other options include:
* Collapsing it to one line with literal `\n` that need to be evaluated with `echo -e` or equivalent inside the container.
* Skipping multiline environment variables and logging a warning.
* Passing multiline environment variables using `-e` instead of the `.env` file.

**Versions (please complete the following information):**
 - Output of `telepresence version` 
 ```
 Client: v2.7.0 (api v3)
Root Daemon: v2.7.0 (api v3)
User Daemon: v2.7.0 (api v3)
```
 - Operating system of workstation running `telepresence` commands
 MacOS
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 1.20, EKS

**Additional context**
Just looking for ideas.

**Comment by cindymullins-dw** [comment]
Hi @jfmyers9 , thanks for noting this.  Telepresence will try to grab the env variables from the pod you’re intercepting and put that into an env file but may be problematic with multi-line variables.  If you use Docker Desktop you might try running your container separately rather than using the Telepresence command, to break up those processes.

**Comment by jfmyers9** [comment]
Hi @cindymullins-dw, I agree there are workarounds, but I am wondering if there is anything we can do to make the experience less jarring. For example, printing a warning line that we are skipping a specific environment variable but still successfully launching the docker container. At the moment this command just fails in an obscure fashion that requires some digging to understand what went wrong.

**Comment by cindymullins-dw** [comment]
This issue was also reported by another user [here.](https://github.com/telepresenceio/telepresence/issues/2837)

**Comment by deedubs** [comment]
So I've tracked this problem down to the implementation here [pkg/client/userd/commands/intercept.go#L1026-L1039](https://github.com/telepresenceio/telepresence/blame/3e38e275f343446915459a0a60f9cf9e4583a1f4/pkg/client/userd/commands/intercept.go#L1026-L1039).  It looks to be well factored so I don't imagine it being difficult to make it able to handle some of the more pathological cases.

I volunteer @andrew-clarkson and myself to take a look at this.

**Comment by jfmyers9** [comment]
@deedubs I think the core of the issue is that it's not clear what the desired behavior is, which is why I opened an issue.

From the original description:

I was thinking about this approach in which we escape the environment variable as `ENV="..."`: https://github.com/jfmyers9/telepresence/commit/8dfb4599ec9d192208ab5fd2fcb14ff79d5d6f90 but it doesn't work as expected as Docker treats anything after the `=` literally.

Other options include:
* Collapsing it to one line with literal `\n` that need to be evaluated with `echo -e` or equivalent inside the container.
* Skipping multiline environment variables and logging a warning.
* Passing multiline environment variables using `-e` instead of the `.env` file.

I was hoping we could get consensus is on the right way to handle this.

**Comment by deedubs** [comment]
I think there is a lot of prior art on how to handle multi-line env variables:

- https://github.com/bkeepers/dotenv#multi-line-values
- https://docs.docker.com/compose/env-file/#syntax

Of these it feels like you're first option is the closest.

**Comment by jfmyers9** [comment]
I agree, but it doesn't actually work. The environment ends up coming out like: 
```
root@71ec5f234582:/# echo $FOO
"this\na\nvariable"
root@71ec5f234582:/# exit

~/workspace/scratch/foobar 19s
❯ cat envfile
FOO="this\na\nvariable"
```

As far as I'm aware there isn't a fix for this in docker: https://github.com/moby/moby/issues/12997

**Comment by thallgren** [comment]
Closing this, since no further input on how to solve it (if indeed, it is solvable) was provided.

**Comment by alextricity25** [comment]
I would like to re-open this issue, as it's preventing telepresence from properly intercepting my service. 
I have an environment variable that stores a multi-line string i.e.
```
$ env
MY_ENV_VAR=hello
world
HOST=localhost
```
When I try to intercept this service, telepresence throws the following error:
docker: poorly formatted environment: variable 'hello' contains whitespaces.
See 'docker run --help'.
telepresence intercept: error: exit status 125


Telepresence version
```OSS Client             : v2.18.0
OSS Daemon in container: v2.18.0
Traffic Manager        : v2.18.0
Traffic Agent          : not reported by traffic-manager
```

**Comment by jfmyers9** [comment]
I don't use telepresence anymore, but I agree this issue should be reopened.

The current behavior is probably the worst case scenario as it just breaks and there isn't really anything you can do.

I listed out some alternatives here: https://github.com/telepresenceio/telepresence/issues/2718#issuecomment-1298916995 but never got any input on which one would be accepted.

**Comment by thallgren** [comment]
This #3206 was merged last year. It doesn't solve the problem with multi-line environment variables, but it does provide a way to exclude such variables.
