### ISSUE TITLE
Telepresence fails at startup

### ISSUE THREAD

**Issue by richarddli** [telepresenceio/telepresence#272]
Mac OS X 10.12.6, kubectl 1.7.3, GKE kube 1.7.2.

telepresence fails with:

`subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence131')"]' returned non-zero exit status 1.`

however, `telepresence -m inject-tcp` works.

**Comment by richarddli** [comment]
log is here https://gist.github.com/ninnemana/bf3d823c251dd0daeb9f7a733eb473ad

**Comment by ark3** [comment]
It appears that the DNS server running on the T proxy pod does not receive the "hellotelepresence##" DNS requests from Python, even though it sees and correctly responds to some other DNS requests, such as lookups of Github and CircleCI. I think this is what happens on one of our Macs here too. I'll take a look and update.

**Comment by ark3** [comment]
Argh. DNS behaves differently on different networks. I'm not seeing that behavior on the current network, though I'm pretty sure I've seen it on Datawire's usual network. Sadly, this means I won't be able to pursue this until Monday.

**Comment by sha1sum** [comment]
**Note:** I work with @ninnemana so the issues are occurring with the same cluster setup. Probably a good thing to keep in mind.

I am having the same issue, here is [the log file from my machine](https://gist.github.com/sha1sum/0bb563dab8189153a454478d392962e8).

**Comment by ark3** [comment]
@sha1sum Thank you! Is your log file from a Linux machine?

**Comment by sha1sum** [comment]
@ark3 it is not. It is also from a Mac (Sierra 10.12.6). These are the developer machines issued to us so all of us are using these for most of our daily work. I can give it a shot, actually, on my personal Ubuntu laptop and let you know how it goes, but from the Python `socket` documentation, my guess would be that it is a Mac OS-specific issue (and maybe even Sierra, because Sierra is cropping up on most of the searches I am doing for DNS issues with the `socket` library on Mac).

**Comment by sha1sum** [comment]
@ark3 So actually was completely wrong. The same thing happens on my Ubuntu machine. The [previous log gist has been updated to add the Ubuntu log file as well (along with release info)](https://gist.github.com/sha1sum/0bb563dab8189153a454478d392962e8).

**Comment by ark3** [comment]
Thanks for the update. It looks like this is not the Mac-specific issue I was thinking. I need to land some logging improvements to investigate further. I'll ask you to update and run again in a few days, once I have that update released. We appreciate your patience.

**Comment by sha1sum** [comment]
@ark3 no problem. I appreciate your quick support!

**Comment by ark3** [comment]
Sorry for the not-so-quick support. Telepresence 0.67 has the logging improvements I mentioned above. Could you please share a telepresence.log generated by 0.67? Thank you.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
