### ISSUE TITLE
[2.7.1] telepresence intercept not working with --no-report

### ISSUE THREAD

**Issue by mruell** [telepresenceio/telepresence#2725]
I'm using telepresence 2.7.1 and when trying to run `telepresence intercept` with the `--no-report` flag (which should be global) it tells me the flag does not exist.

Was this removed?

`telepresence --help` shows the flag as global, but `telepresence intercept --help` doesn't show it

Thanks a lot in advance and best,
Marvin

**Comment by cindymullins-dw** [comment]
HI @mruell , I see a change to the help menu in 2.7.2 (not sure if related) but we tested this on 2.7.6 and it works.  Could you try upgrading and let us know if it persists?

**Comment by mruell** [comment]
Yeah this seems to be fixed now :)
Thanks!
