### ISSUE TITLE
runAsUser setting for traffic-agent

### ISSUE THREAD

**Issue by MHoinkaBS** [telepresenceio/telepresence#2730]
Hi 
I'm working at my DEV cluster with PodSecurityPolicies enforcing pods to run as nonRoot.
In order to do that I've created a custom image for traffic-agent using user 1000 (since the original image will run as a root).  
I could not use the name of the user since otherwise I've got an error: 
`Error: container has runAsNonRoot and image has non-numeric user (tp_user), cannot verify user is non-root`

Also, my image registry is bound this way: namespace <-> repo in the registry. 
For this reason, to use a custom traffic-agent image in each namespace I have to push it to each repository corresponding with namespace. 
Currently, in sidecar part of the manifest I can see only `runAsNonRoot: true`. 

I tried with values.yaml fields but to no avail: 
securityContext
hooks.podSecurityContext

Being able to set specific non-root user (through values.yml)  for traffic-agent would probably solve the problem. 
Also being able to set imagePullPolicy for the sidecar would be nice (for what i can tell we cannot set this now). 

Please, If there is already such a setting, please let me know where or which. 

I'm working with images: 
traffic-agent 1.12.9
tel2:2.7.0

**Comment by cindymullins-dw** [comment]
Hi @MHoinkaBS , this is available for the traffic manager but not for the traffic agent.  I'll label this as a feature request.

**Comment by malagant** [comment]
I would need this too. Would it make sense to contribute this change as a PR or do you prefer working on this internally?

**Comment by Shrizo** [comment]
I could also really use this.  Pod level security policies that prevent running as root are required as part of our enterprise development, and it would be a big help to be able to use telepresence 2 for shared cluster development.

**Comment by denysvitali** [comment]
See:
https://github.com/telepresenceio/telepresence/pull/2903 (WIP)

**Comment by mhmdhelmy28** [comment]
Blocked on this feature, any updates ?

**Comment by cindymullins-dw** [comment]
We don't provide a way to do this currently.  Solution would be to provide a helm chart value to set the agent's securityContext as one of our engineers suggested [here](https://github.com/telepresenceio/telepresence/pull/2903#pullrequestreview-1197013553).  If contributors are able to work on this please join the telepresence-dev channel in our Slack (a8r.io/slack) and you're welcome to attend the [monthly contributors meeting](https://github.com/telepresenceio/telepresence/blob/release/v2/MEETING_SCHEDULE.md#monthly-contributors-meeting) as well.

**Comment by thallgren** [comment]
Support for an agent `securityContext` was added in PR #3563
