### ISSUE TITLE
Telepresence doesn't see workload on newly created namespace

### ISSUE THREAD

**Issue by psemeniuk** [telepresenceio/telepresence#2736]
**Describe the bug**
Hi,
it seems that telepresence doesn't show workload from namespaces created after `telepresence connect`. 

**To Reproduce**
1. Run `telepresence connect`
2. Create namespace `new-namespace`
3. Create some workload taken into account by telepresence.
4. Run `telepresence list -n new-namespace`
5. It returns `No Workloads (Deployments, StatefulSets, or ReplicaSets)`

**Expected behavior**
Workload deployed in `new-namespace` should be visible by telepresence.

**Versions:**
- Client: v2.7.1 (api v3)
- Root Daemon: v2.7.1 (api v3)
- User Daemon: v2.7.1 (api v3)
- Traffic manager 2.7.1
 - MacOS
 - EKS 1.21

**Additional context**
Probably some local cache, because after `telepresence quit -ur` + `telepresence connect` sequence everything is visible again.

**Comment by cindymullins-dw** [comment]
Hi @psemeniuk , we tested this on 2.7.6 and it works for us.  Could you please try upgrading and see if that resolves it?

**Comment by cieplakm** [comment]
Checked on 2.7.6. Still occurs.

**Comment by cindymullins-dw** [comment]
I don't think this is the expected behavior.  Telepresence will identify workloads on '`telepresence connect`', not afterwards, so if new workloads are added a new connect is required.
