### ISSUE TITLE
DNS resolution broken on MacOS after restart - Files under /etc/resolver are deleted and not recreated

### ISSUE THREAD

**Issue by g-guirado** [telepresenceio/telepresence#2740]
**Describe the bug**
A restart of my Macbook breaks Telepresence's domain resolution. I tracked that to the disappearance of files under `/etc/resolver`.

**To Reproduce**
1. After restarting my Macbook Pro
2. I can no longer resolve any domain from the cluster

```
curl -ik https://kubernetes.default
curl: (6) Could not resolve host: kubernetes.default
```

I have noticed that `/etc/resolver/` folder is empty.

Tried many combinations of `telepresence connect` and`telepresence quit` but problem persists. Files do not get recreated.
Why do the files disappear? Why isn't the daemon recreating them?

**Expected behavior**
I would expect DNS resolution to work after restart.

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)
```
 - Operating system of workstation running `telepresence` commands: MacOs Monterey 12.5
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]: Docker Desktop
 ```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Additional context**
Workaround found: uninstall and reinstall the helm component after every restart
```
telepresence helm uninstall
telepresence helm install
```
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9372539/telepresence_logs.zip)

**Comment by thallgren** [comment]
You seem to have some kind of certificate problem. The logs are full of `"x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes""`. This is related to how the Kubernetes client connects to the cluster so you should see similar problems when you use `kubectl` to create a port-forward.
