### ISSUE TITLE
Version 2.7.1 fails when running `telepresence intercept` and specifying a command

### ISSUE THREAD

**Issue by ezzatron** [telepresenceio/telepresence#2745]
**Describe the bug**

In version `2.6.8`, running a command like `telepresence intercept <name> --port <port> -- zsh` would result in a sub-shell being created. The intercept would persist until the sub-shell was terminated. This is broken under version `2.7.1`.

**To Reproduce**
1. When I run `telepresence intercept <name> --port <port> -- zsh`, then `echo $SHLVL`
2. I see `1`, and the intercept is immediately removed.

**Expected behavior**
- I should see `2`, and the intercept should remain open until I terminate the sub-shell.

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)
```
 - Operating system of workstation running `telepresence` commands: `macOS 12.5.1 (Monterey)`
 - Kubernetes environment and Version: `EKS v1.22.10-eks-84b4fe6`

**VPN-related bugs:**
_N/A_

**Additional context**
I'm also seeing similar issues with commands other than `zsh`. I think something more general is broken with how the specified command is being run. It's _probably_ the same issue as #2724.

I typically run a development web server directly with a command like `telepresence intercept <name> --port <port> -- npx next dev --port <port>`. With version `2.6.8` this works perfectly, and I can see the dev server's log output in my terminal. When I interrupt (control+c) the process, the intercept also gets removed. With version `2.7.1`, I can't see the log output, and after interrupting the process, my dev server is still running in the background but with no output whatsoever.

**Comment by ezzatron** [comment]
Here is the expected behaviour (from `2.6.8`):

https://user-images.githubusercontent.com/100152/185877693-6e7dbf4a-7b04-4e9f-a39e-1bc8e550e4cf.mov

Here is the buggy behaviour (from `2.7.1`):

https://user-images.githubusercontent.com/100152/185877809-5884c817-8f88-4128-b215-c39a6fdea852.mov

**Comment by raphaelreyna** [comment]
hmm it looks like this is affecting interactive commands and ones with streaming output; thanks for submitting this issue :+1:

**Comment by ahaw023** [comment]
was this fixed in version 2.7.3 ??

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/106289240/189024391-f72e42b3-d7b9-4a65-9a91-17827eed0065.png">

**Comment by thallgren** [comment]
@ahaw023 that'd be my guess. @ezzatron It would be great to get it verified.

**Comment by ezzatron** [comment]
While the situation has improved, unfortunately it seems like there are still some issues. For example, running `zsh`, the process never becomes interactive:

https://user-images.githubusercontent.com/100152/189099457-4fc29ac9-338d-4a97-95bb-42f951ccdcfd.mov

In addition, when running something non-interactive that typically produces colored output (like a development web server) under Telepresence `v2.7.3`, the output is not colored:

https://user-images.githubusercontent.com/100152/189102243-56b4bb2c-3757-478b-89cf-839d586c8731.mov

Here's the same exercise under Telepresence `v2.6.8` showing that colored output used to work:

https://user-images.githubusercontent.com/100152/189103007-b5710280-7582-48f4-9b1c-be8dcf1a68b1.mov

**Comment by mruell** [comment]
I can comfirm that the issue is gone in `2.9.0`

Thanks a lot!

**Comment by ezzatron** [comment]
I re-tried my use cases, and the problem does indeed appear to be fixed. Probably in `v2.9.0`, but I tried with `v2.9.2` and that worked for me. Thanks!
