### ISSUE TITLE
Sometimes cannot quit due to permission problems

### ISSUE THREAD

**Issue by DanielYWoo** [telepresenceio/telepresence#2748]
**Describe the bug**
Telepresence often breaks although the `telepresence status` reports `connected`. So I have to quit and connect again. However, sometimes I see the error below:
```
❯ telepresence quit
Telepresence Network Telepresence Traffic Manager disconnecting...done
telepresence: error: connection error: desc = "transport: error while dialing: dial unix /var/run/telepresence-daemon.socket: connect: connection refused" (socket rm failed with remove /var/run/telepresence-daemon.socket: permission denied); this usually means that the process has terminated ungracefully

See logs for details (2 errors found): "/Users/xxx/Library/Logs/telepresence/daemon.log"

See logs for details (2 errors found): "/Users/xxx/Library/Logs/telepresence/connector.log"
```

See the collected log:
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9401386/telepresence_logs.zip)
I can `sudo rm` and fix it but it's a little annoying to do that everyday.

**To Reproduce**
hard to reproduce, occasionally

**Expected behavior**
It should just work.

**Versions (please complete the following information):**
```
❯ telepresence version
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)
```
 - Operating system: MacOSX
 - Kubernetes environment and Version: Docker desktop, K8s 2.24

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
 - Which VPN client are you using? F5 Access
 - Which VPN server are you using? F5
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf: On Mac, this file is not used.
 VPN test result:
```
---------- Test Results:
✅ pod subnet 10.1.0.0/24 is clear of VPN
✅ pod subnet 192.168.65.0/24 is clear of VPN
✅ svc subnet 10.96.0.0/12 is clear of VPN
```

**Additional context**

**Comment by thallgren** [comment]
This problem was fixed in 2.7.2.
