### ISSUE TITLE
Intercept Fail. Readiness probe failed: stat: can't stat '/tmp/agent/ready'

### ISSUE THREAD

**Issue by leanalcabasa** [telepresenceio/telepresence#2755]
**Describe the bug**

I am trying to intercept using the following command:

`telepresence intercept -n dev tenant-api-tele --port 9000:grpc -env-file ~/example-service-intercept.env`

But receive the following error:

`telepresence: error: rpc error: code = DeadlineExceeded desc = request timed out while waiting for agent tenant-api-tele.dev to arrive`

When I check the pods, it creates the pod with the agent successfully, but there is a warning when I do a describe pod:

![image](https://user-images.githubusercontent.com/20421932/186623145-9618a721-ef14-462c-86df-b45c15ef2c94.png)

The error specifically is:

`Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory`

I check connector.log, it doesn't seem to have any error message.

![image](https://user-images.githubusercontent.com/20421932/186623952-c0e6c866-0e74-470a-81fc-7e1e0fb09f2c.png)

**Expected behavior**
Can connect successfully with Intercept

**Versions (please complete the following information):**
 - Output of `telepresence version`
![image](https://user-images.githubusercontent.com/20421932/186624600-12e0774d-bc16-4f0c-9ad9-e4f42360f655.png)

 - Operating system of workstation running `telepresence` commands = Windows 
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine] = AKS

**Additional context**

- AKS cluster has different IP subnet compared to my host machine. But I can run kubectl fine from my machine
- Using telepresence for Windows. I had to manually install the trafficmanager and sshfs-win manually
- port 9000 and grpc (port 9000 in cluster) are grpc endpoints
- AKS is within internal network; need a VPN

**Comment by leanalcabasa** [comment]
It was my error; forgot we had a network policy applied to the kubernetes. Adding the appropriate rules worked.

**Comment by leanalcabasa** [comment]
Actually, I can't seem to figure out the IP / Port to unblock. I tried it successfully by removing the network policy.

Is there a document somewhere I can refer to for it?

**Comment by shivam-sood89-admin** [comment]
I am getting the same error while trying to implement readme 

in my aks cluster.

**Comment by cindymullins-dw** [comment]
Hi @leanalcabasa , Telepresence [2.7.6](https://www.getambassador.io/docs/telepresence/2.7/release-notes/) has been released. We've love for users who encountered the "Deadline Exceeded error" to try it and let us know if any improvement, or if more information about the error is output.
