### ISSUE TITLE
attempts to create an intercept always timesout

### ISSUE THREAD

**Issue by tomschreck** [telepresenceio/telepresence#2758]
I've been trying to create an intercept using the following command:

`telepresence intercept -n app --http-header=Personal-Intercept=ac29d8d7-2632-444-af86-c93ff8916194 contacts-api-v2`

I also try creating an intercept via Ambassador Cloud, but get a generic error: 
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9426539/telepresence_logs.zip)

![image](https://user-images.githubusercontent.com/2521463/186716519-87bc2a0a-50f4-42f7-bf02-634cccfb27af.png)

It seems the creation of an intercept always timesout.

Attached are logs.
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9426543/telepresence_logs.zip)

**Comment by cindymullins-dw** [comment]
Thanks for reporting this, @tomschreck.  Are you still getting this error?  Other users have reported solving this issue by adjusting their GKE cluster firewall rules fix.  We've found that private clusters have with firewall rules that can block things like webhook controllers, by blocking traffic from the API server directly to the pods (as opposed to the service ClusterIP).

If applicable, you can follow [this guide](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules) with the port and protocol for the firewall rule being set to tcp:8443 --which is the port that the traffic-manager container uses to serve webhooks.

**Comment by cindymullins-dw** [comment]
Closing this in favor of #2798 which has a lot more info things that may cause this error.
