### ISSUE TITLE
Unqualified service names do not resolve when using `--docker-run`

### ISSUE THREAD

**Issue by rhs** [telepresenceio/telepresence#2777]
**Describe the bug**

Unqualified services names do not resolve when using the `--docker-run` flag of the `telepresence intercept` command. See attached logs.

**To Reproduce**
1. Run telepresence intercept with the `--docker-run` flag on a container that does an `nslookup` of an unqualified service name.
2. The nslookup will fail.
3. The same nslookup on the host succeeds.
4. The same nslookup with manually launched docker containers succeeds.

The workaround is to use a background intercept and run the docker container by hand instead of using the --docker-run flag.

**Expected behavior**

**Versions (please complete the following information):**

Telepresence version:

```
Client: v2.7.2 (api v3)
Root Daemon: v2.7.2 (api v3)
User Daemon: v2.7.2 (api v3)
```

Workstation version: Fedora 36

Kubernetes flavor is GKE.

Kubectl version output:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14-gke.700", GitCommit:"1781919224b267c523fd76047cebf7b14c6aa1d9", GitTreeState:"clean", BuildDate:"2022-06-28T09:30:29Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

**VPN-related bugs:**

I am not using a VPN.

**Additional context**

I'm running Fedora 36 and I am using the `systemd-resolved-docker` utility to get docker dns lookup to go through the stub resolver. Note that before using the `systemd-resolver-docker` utility, even fully qualified service name lookups did not work inside docker containers.

Here is the full transcript demonstrating the bug. The dnsutils docker image is a fedora image with the dnsutils package installed so that nslookup is available. Any docker image with nslookup will suffice for reproducing the problem, however I'd recommend avoiding busybox nslookup since that behaves differently due to a significant bug.

In the first invocation the nslookup of just the service name fails. In the second invocation the nslookup of the service name qualified by the namespace does not fail.

```
[rhs@venture saas-auth-keycloak]$ telepresence intercept keycloak --preview-url=false --http-header=test-$USER=1 --env-file=keycloak.env --docker-run -- --rm -p 8787:8787 -e "DEBUG=true" -e "DEBUG_PORT=*:8787" dnsutils nslookup keycloak-postgresql
Using StatefulSet keycloak
intercepted
    Intercept name         : keycloak
    State                  : ACTIVE
    Workload kind          : StatefulSet
    Destination            : 127.0.0.1:8080
    Service Port Identifier: http
    Volume Mount Error     : sshfs is not installed on your local machine
    Intercepting           : HTTP requests with headers
        'test-rhs =~ 1'
Server:		172.17.0.1
Address:	172.17.0.1#53

** server can't find keycloak-postgresql: SERVFAIL

telepresence: error: /usr/bin/docker docker run --dns-search tel2-search --env-file keycloak.env --name intercept-keycloak-8080 -p 8080:8080 --rm -p 8787:8787 -e DEBUG=true -e 'DEBUG_PORT=*:8787' dnsutils nslookup keycloak-postgresql: exited with 1
[rhs@venture saas-auth-keycloak]$ telepresence intercept keycloak --preview-url=false --http-header=test-$USER=1 --env-file=keycloak.env --docker-run -- --rm -p 8787:8787 -e "DEBUG=true" -e "DEBUG_PORT=*:8787" dnsutils nslookup keycloak-postgresql.saas-auth-staging
Using StatefulSet keycloak
intercepted
    Intercept name         : keycloak
    State                  : ACTIVE
    Workload kind          : StatefulSet
    Destination            : 127.0.0.1:8080
    Service Port Identifier: http
    Volume Mount Error     : sshfs is not installed on your local machine
    Intercepting           : HTTP requests with headers
        'test-rhs =~ 1'
Server:		172.17.0.1
Address:	172.17.0.1#53

Non-authoritative answer:
Name:	keycloak-postgresql.saas-auth-staging
Address: 10.40.14.126

[rhs@venture saas-auth-keycloak]$ 
```
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9531323/telepresence_logs.zip)

**Comment by thallgren** [comment]
This is fixed in #2787
