### ISSUE TITLE
Client rate limiter

### ISSUE THREAD

**Issue by cstripling-brex** [telepresenceio/telepresence#2781]
**Describe the bug**
This error happens almost everytime I use telepresence.
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9557968/telepresence_logs.zip)

```


**To Reproduce**
Steps to reproduce the behavior:
1. Run `telepresence connect`
2. error appears immediately.
```

**Versions (please complete the following information):**

```
An update of telepresence from version 2.6.0 to 2.7.3 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client: v2.6.0 (api v3)
Root Daemon: v2.6.0 (api v3)
User Daemon: v2.6.0 (api v3)
```

- MacOS monterey

**Comment by cindymullins-dw** [comment]
Hi @cstripling-brex, we didn’t see the error related to rate limits in the logs, although we do see a mismatch between your Telepresence agent and traffic manager versions.  However we doubt that would be causing this issue.  Could you extract the error you’re getting so we could review it?

**Comment by jrusso1020** [comment]
@cindymullins-dw I believe the error is something along the lines of below
```
agent-injector/conn=10.8.124.113:8443 : mutating function error: client rate limiter Wait returned an error: context canceled
Waited for 4.995157494s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/apps/v1/namespaces/<namespace>/statefulsets/<statefulset>
```

Is there a way to increase the timeout, we may be able to resolve the issue with an increased timeout when the k8s api is under load

**Comment by cindymullins-dw** [comment]
We see this error from time to time.  It's more of a Kubernetes warning and not a Telepresence error per se.  
You can increase the timeout by following the [example here](https://www.getambassador.io/docs/telepresence/latest/reference/config#timeouts).
Upgrading to a version later than 2.6 should also help reduce this error and we made some improvements in [2.7.2](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.7.2).
