### ISSUE TITLE
Telepresence --run-shell --inject-tcp fails

### ISSUE THREAD

**Issue by plombardi89** [telepresenceio/telepresence#279]
### What were you trying to do?

`telepresence --run-shell --method inject-tcp`

### What did you expect to happen?

I get a shell.

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--run-shell', '--method', 'inject-tcp']`
Version: `0.65`
Python version: `3.5.3 (default, May 10 2017, 15:05:55) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]`
kubectl version: `Client Version: v1.7.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux palwork 4.9.9-200.fc25.x86_64 #1 SMP Thu Feb 9 17:28:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/bin/telepresence", line 2327, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/bin/telepresence", line 2072, in run_local_command
    setup_torsocks(runner, env, socks_port, unsupported_tools_path)
  File "/usr/bin/telepresence", line 2030, in setup_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
resolve_reply() at socks5.c:666)
[Aug 30 13:33:48] WARNING torsocks[25147]: [syscall] Unsupported syscall number 217. Denying the call (in tsocks_syscall() at syscall.c:465)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -4] Non-recoverable failure in name resolution
Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)... [Aug 30 13:33:53] ERROR torsocks[25148]: Unable to resolve. Status reply: 4 (in socks5_recv_resolve_reply() at socks5.c:666)
2017-08-30T17:33:53+0000 [-] Unhandled Error
	Traceback (most recent call last):
	Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: google.com.
	
[Aug 30 13:33:53] WARNING torsocks[25150]: [syscall] Unsupported syscall number 217. Denying the call (in tsocks_syscall() at syscall.c:465)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -4] Non-recoverable failure in name resolution

```

**Comment by ark3** [comment]
@plombardi89 Could you gist me the telepresence.log from running your command with `--verbose` added please? Thanks!

**Comment by ark3** [comment]
Or, if you run into this again, can you try to `kubectl exec -it <pod> -- sh` and try name resolution manually from the pod? I just ran into this myself and found that name resolution was not working from in the cluster.
