### ISSUE TITLE
Unable to connect to services inside cluster

### ISSUE THREAD

**Issue by vbode** [telepresenceio/telepresence#2801]
**Describe the bug**
After a successful telepresence connect, I am initially able to connect to a service in my cluster. After a short time this stops working.

**To Reproduce**
1. Run telepresence connect, I see that it connected succesfully
2. Curl to a service in my cluster. I get a 400 (expected)
`PS C:\Users\VincentB> curl internal-tas-proxy.default
curl : The remote server returned an error: (400) Bad Request.`
3. Wait a short time. Then try again:
`PS C:\Users\VincentB> curl internal-tas-proxy.default
curl : The remote name could not be resolved: 'internal-tas-proxy.default'`

**Expected behavior**
I should be able to reach my internal service consistently.

**Versions (please complete the following information):**
 - Output of `telepresence version`
Client: v2.7.6 (api v3)
Root Daemon: v2.7.6 (api v3)
User Daemon: v2.7.6 (api v3)

 - Windows 10 (up to date)
 - minikube version: v1.25.2 with kubernetes: 
 `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`

Here are my logs:
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9704391/telepresence_logs.zip)

**Comment by cindymullins-dw** [comment]
Hi @vbode , there are some limitations with Minikube and the disconnect or reconnect could interfere with DNS resolution.  Minikube uses localhost and doesn’t expose network device that lets you connect to it and you do need to be able to connect to your cluster to be able to port forward.  We do have weekly help sessions with Support so could help troubleshoot, and please join our Slack at a8r.io/slack.

**Comment by KoltesDigital** [comment]
I have the same issue with k3d, both in Windows and in WSL (envs are distinct), it sometimes works but most often not. `nslookup` resolves correctly, but curl directly says either `curl: (56) Recv failure: Connection reset by peer` or `curl: (52) Empty reply from server`. It may be the same issue as https://github.com/telepresenceio/telepresence/issues/2575, because when curling on another port, it times out there, so I believe traffic not going back could explain the symptoms.

I also notice other issues in name resolutions (`ping: google.com: Temporary failure in name resolution`) but I can't tell whether they're related.

**Comment by vbode** [comment]
Hi @cindymullins-dw, thanks again for the support session yesterday. 
I have done some more testing following your recommendations. I am now using telepresence 2.8.5. 
When I inspect the traffic-manager pod in my cluster, I see this is set:
CLIENT_CONNECTION_TTL:24h

However, I am still running into the same issue. After a successful connect, I am only initially able to connect to a service in the cluster from my local machine:
![image](https://user-images.githubusercontent.com/81425543/200770103-564c5df7-c147-4758-97bc-0d97ed665f1c.png)

I have attached new logs. Any other ideas what I could try, or should we rule out minikube for our local development environment?
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9968667/telepresence_logs.zip)

**Comment by vbode** [comment]
I just tried the same with kind (kubernetes in docker), with the same result.

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9969378/telepresence_logs.zip)

**Comment by vbode** [comment]
I managed to find a workaround for this. Telepresence seems to work correctly when connecting under WSL.
This does mean our devs then need to run their IDE's from WSL.

This does mean however that the issue seems to be isolated to Windows or Docker Desktop.

**Comment by thallgren** [comment]
@vbode I looked at the logs that you provided. They don't contain much, because they are produced with the default log-level (info). Can you please try the following:
```console
$ telepresence connect
$ telepresence loglevel debug
*** reproduce the problem ***
$ telepresence gather-logs
```

**Comment by vbode** [comment]
Hi @thallgren. Thanks for having a look.
I have done as requested. I also updated to the latest version of telepresence in the meantime. This time I also ran a little script to 'curl hello.default' every 1 second for 60 seconds. The first 20 requests are fine, but then after that it starts failing.
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10133044/telepresence_logs.zip)

**Comment by vbode** [comment]
I've tested this some more and have an interesting finding. 
If I start minikube with the flag _--ports=36759:8443_ then minikube exposes two ports for the internal 8443 (k8s api) port. The first port is the given 36759, while the second is a randomly assigned port by minikube. 
If I then `telepresence connect`, I get the behavior described above, when I set my .kube file to connect on the port assigned by minikube. If I use the 36759, then reaching internal services does not work at all.

If I don't set the ports flag, then I only get one random exposed port for the 8443 port by minikube. If I know `telepresence connect`, then I cannot reach internal services at all.

For all scenarios I have tested, I have no problems at all when using telepresence from WSL.

**Comment by vbode** [comment]
Hi, my last comment can be disregarded. The behavior is the same on either of the 8443 exposed ports.
I did try this out again today with telepresence v2.10.4, and the problem is still present.
@thallgren any ideas as to what is going on?

Here are some new logs:
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10491816/telepresence_logs.zip)

**Comment by vbode** [comment]
Seems like the issue is no longer present. I believe it was fixed by the latest Docker Desktop update.

**Comment by cindymullins-dw** [comment]
Thanks for confirming.
