### ISSUE TITLE
never-proxy detection fails to parse routes having a local prefix

### ISSUE THREAD

**Issue by davidecavestro** [telepresenceio/telepresence#2809]
**Describe the bug**
_never-proxy_ detection doesn't support _local_ prefixes such as with _local 127.0.0.1 dev lo src 127.0.0.1 ..._.

**To Reproduce**
1. When I run `telepresence connect` having a local microk8s as k8s context
2. I see _unable to get route for never-proxied subnet ...._ within daemon logs
3. So I issue the command `ip route get 127.0.0.1` (or any other _local_ ip used)
4. And see that it starts with a _local_ keyword that is not supported by the regex used for parsing that data

**Expected behavior**
When using a k8s cluster with api exposed to a local ip, its subnet should be among never-proxied ones.

**Versions (please complete the following information):**
 - Output of `telepresence version`

> Client: v2.7.6 (api v3)
> Root Daemon: v2.7.6 (api v3)
> User Daemon: v2.7.6 (api v3)

 - Operating system of workstation running `telepresence` commands: Ubuntu 20.04 LTS
 - Kubernetes environment and Version: MicroK8s v1.25.2

**Additional context**
Issue filled after a [Slack message](https://datawire-oss.slack.com/archives/CAUBBJSQZ/p1665418007349829) discussed at the weekly help session.

Download [this Vagrantfile](https://gist.github.com/davidecavestro/bee90919f6ac3c43c2122088d3186393) to easily spin-up an Ubuntu vm and check the issue on a live box, After the `vagrant up` command completes, you get a fresh telepresence_logs.zip and a running vm you can play with using `vagrant ssh`

See also related issue #2811  
#
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9763695/telepresence_logs.zip)

**Comment by thallgren** [comment]
Fixed in 2.9.0.
