### ISSUE TITLE
Add ability to specify port for the webhook

### ISSUE THREAD

**Issue by actualrockstar** [telepresenceio/telepresence#2819]
**Please describe your use case / problem.**
The prospect uses a private GKE cluster and needs to create a firewall rule to allow the webhook to work, but if they could have the webhook use port 443 instead of port 8443 they wouldn't need to wait for their dev/ops team to create the firewall rule for them. 

**Describe the solution you'd like**
Make the port for the webhook use port 443 instead of 8443 and have this configurable through the helm chart.

**Describe alternatives you've considered**
The alternative is to add the firewall rule for their private cluster. 

**Versions (please complete the following information)**
  - TP v2.7.6
  - GKE 1.22

**Additional context**
This is related to prospect Commscope

**Comment by thallgren** [comment]
Fixed by #2822.
