### ISSUE TITLE
Failed Intercept -- the server could not find the requested resource (get events.events.k8s.io)

### ISSUE THREAD

**Issue by thorntonmc** [telepresenceio/telepresence#2820]
**Describe the bug**

this works in my `kind` cluster running 1.25.3 -- but not on my microk8s cluster running 1.18.20 -- is there a particular version of kubernetes this requires?

When trying to intercept a service, I receive the following error 

```
telepresence: error: the server could not find the requested resource (get events.events.k8s.io)

See logs for details (20 errors found): "/var/home/mthornton/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

1. I deploy the following deployment
```
Name:                   sleep
Namespace:              default
CreationTimestamp:      Wed, 19 Oct 2022 20:45:21 +0300
Labels:                 app=test
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=sleep
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=sleep
  Containers:
   sleep:
    Image:      alpine:3.14.2
    Port:       8088/TCP
    Host Port:  0/TCP
    Command:
      /bin/sleep
      infinity
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   sleep-b9dd85895 (1/1 replicas created)
Events:          <none>
```

2. I expose said service
```
kubectl -n default expose deployment sleep --type=LoadBalancer --port=8088
mthornton@fedora:~/work/envoy-admissions-controller/deploy [init-spec]
$ kubectl -n default describe service sleep
Name:                     sleep
Namespace:                default
Labels:                   app=sleep
Annotations:              <none>
Selector:                 app=sleep
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.97.237.180
IPs:                      <none>
Port:                     <unset>  8088/TCP
TargetPort:               8088/TCP
NodePort:                 <unset>  64721/TCP
Endpoints:                192.168.29.255:8088
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
3. I run 
```
$ telepresence -n default list
autoenv: ready to intercept (traffic-agent not yet installed)
sleep  : ready to intercept (traffic-agent not yet installed)
mthornton@fedora:~/work/envoy-admissions-controller/deploy [init-spec]
$ telepresence -n default intercept sleep
telepresence: error: the server could not find the requested resource (get events.events.k8s.io)

See logs for details (22 errors found): "/var/home/mthornton/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

**Expected behavior**
I expect the intercept to work -- 

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
$ telepresence version
Client: v2.8.2 (api v3)
Root Daemon: v2.8.2 (api v3)
User Daemon: v2.8.2 (api v3)
```

 - Operating system of workstation running `telepresence` commands
 ubuntu 18.04
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 microk8s
```
tracking:     1.18/stable
refresh-date: 2022-07-07
````
**Additional context**

**Comment by thallgren** [comment]
My guess is that since you don't use a symbolic port name, telepresence is forced to inject an init-container to modify iptables. That is known to fail in some situations. Please see t[his section](https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#injected-init-container-doesnt-function-properly) in our troubleshooting guide.

**Comment by liming92309** [comment]
> My guess is that since you don't use a symbolic port name, telepresence is forced to inject an init-container to modify iptables. That is known to fail in some situations. Please see t[his section](https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#injected-init-container-doesnt-function-properly) in our troubleshooting guide.

I have the same issue and tried to solve it refering your section.  Seems no help.
the deployment and service configuration are as below:

apiVersion: v1
kind: Service
metadata:
  namespace: myer
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: http

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myer
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 80

And I saw there is error " unable to get Ambassador Cloud preferred agent image: rpc error:" in traffic-manager log, so I installed traffic-manager following your comments to add config in config.yml, and the same error when intercept the service:

images:
  agentImage: ambassador-telepresence-agent:1.13.1

**Comment by thallgren** [comment]
Please run `telepresence loglevel debug`, then reproduce the problem and provide the logs from `telepresence gather-logs`.

**Comment by liming92309** [comment]
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9874747/telepresence_logs.zip)

This is the logs.

**Comment by thallgren** [comment]
@liming92309 I see that the `PrepareIntercept` arrives to the traffic-manager and then nothing happens. This is usually caused by a firewall blocking access from the mutating webhook to the agent injector. The agent injector is currently using port 8443 ([subject to change](#2822) in the next release). You will find some more info about this in our [troubleshooting guide](https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#no-sidecar-injected-in-gke-private-clusters).

**Comment by liming92309** [comment]
> @liming92309 I see that the `PrepareIntercept` arrives to the traffic-manager and then nothing happens. This is usually caused by a firewall blocking access from the mutating webhook to the agent injector. The agent injector is currently using port 8443 ([subject to change](#2822) in the next release). You will find some more info about this in our [troubleshooting guide](https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#no-sidecar-injected-in-gke-private-clusters).

Thanks for the reply!
I am confued for the work flow and architecture.
in my env, i updated it to 2.8.3.  and there is only one pod,  and only one container in it.
where are the mutating webhook and agent injectoer?  I used telepresence to connect one k8s created by me, so I think there is no firewall issue in the k8s cluster.

oot@clab3126node01:~# kubectl get pod -n ambassador
NAME                               READY   STATUS    RESTARTS   AGE
traffic-manager-58bf45497d-vs2zr   1/1     Running   0          3m13s

root@clab3126node01:~# kubectl describe pod traffic-manager-58bf45497d-vs2zr -n ambassador
Name:         traffic-manager-58bf45497d-vs2zr
Namespace:    ambassador
Priority:     0
Node:         clab3126node04/10.92.136.25
Start Time:   Mon, 31 Oct 2022 03:13:41 -0400
Labels:       app=traffic-manager
              pod-template-hash=58bf45497d
              telepresence=manager
Annotations:  cni.projectcalico.org/podIP: 192.168.242.172/32
              cni.projectcalico.org/podIPs: 192.168.242.172/32
Status:       Running
IP:           192.168.242.172
IPs:
  IP:           192.168.242.172
Controlled By:  ReplicaSet/traffic-manager-58bf45497d
Containers:
  traffic-manager:
    Container ID:   docker://ab9113b6fbf43af84a12ed9a28ce9f5e02f0d763f4b17fb84c352b315f5ab853
    Image:          docker.io/datawire/tel2:2.8.3
    Image ID:       docker-pullable://datawire/tel2@sha256:f0d0398eac2ebfa5da6c915246db655eeded036111ac723beaf20c4ff94981ff
    Ports:          8081/TCP, 443/TCP, 15766/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 31 Oct 2022 03:13:49 -0400
    Ready:          True
    Restart Count:  0
    Environment:
      LOG_LEVEL:                    info
      SERVER_PORT:                  8081
      POD_CIDR_STRATEGY:            auto
      SYSTEMA_HOST:                 app.getambassador.io
      SYSTEMA_PORT:                 443
      MUTATOR_WEBHOOK_PORT:         443
      TRACING_GRPC_PORT:            15766
      GRPC_MAX_RECEIVE_SIZE:        4Mi
      INTERCEPT_DISABLE_GLOBAL:     false
      AGENT_INJECT_POLICY:          OnDemand
      AGENT_PORT:                   9900
      AGENT_APP_PROTO_STRATEGY:     http2Probe
      AGENT_REGISTRY:               docker.io/datawire
      AGENT_ENVOY_LOG_LEVEL:        warning
      AGENT_ENVOY_SERVER_PORT:      18000
      AGENT_ENVOY_ADMIN_PORT:       19000
      MANAGER_NAMESPACE:            ambassador (v1:metadata.namespace)
      POD_IP:                        (v1:status.podIP)
      CLIENT_CONNECTION_TTL:        24h
      CLIENT_DNS_EXCLUDE_SUFFIXES:  .com .io .net .org .ru
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from traffic-manager-token-8sd4z (ro)
      /var/run/secrets/tls from tls (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mutator-webhook-tls
    Optional:    false
  traffic-manager-token-8sd4z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  traffic-manager-token-8sd4z
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From                     Message
  ----    ------     ----       ----                     -------
  Normal  Scheduled  <unknown>  default-scheduler        Successfully assigned ambassador/traffic-manager-58bf45497d-vs2zr to clab3126node04
  Normal  Pulling    4m54s      kubelet, clab3126node04  Pulling image "docker.io/datawire/tel2:2.8.3"
  Normal  Pulled     4m48s      kubelet, clab3126node04  Successfully pulled image "docker.io/datawire/tel2:2.8.3"
  Normal  Created    4m47s      kubelet, clab3126node04  Created container traffic-manager
  Normal  Started    4m47s      kubelet, clab3126

**Comment by mausch** [comment]
Hi, having the same issue here. 
Same "PrepareIntercept" in the logs apparently hanging.
Tried using a named port, no joy.
Running version 2.8.5, agent-injector's service is on port 443.
No firewall anywhere.
k8s 1.17 launched via kind.
telepresence client running on Windows 10.
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9936458/telepresence_logs.zip)

> PrepareIntercept arrives to the traffic-manager and then nothing happens. This is usually caused by a firewall blocking access from the mutating webhook to the agent injector.

Shouldn't there be an error/timeout in the logs about this?
The current error about not finding events.events.k8s.io is misleading and doesn't show up in the log files.

**Comment by mickdelaney** [comment]
I'm also getting this error, but running on Linux 

Client: v2.8.5 (api v3)
Root Daemon: v2.8.5 (api v3)
User Daemon: v2.8.5 (api v3)

 "PrepareIntercept" in the logs.
named port did not work
no firewall
k8s 1.17 launched via kind.

telepresence intercept api --port 5405:http -n local
telepresence: error: the server could not find the requested resource (get events.events.k8s.io)

**Comment by thallgren** [comment]
@mickdelaney you're cluster is 1.17. That's old enough to only have a beta for the events resource. I'd recommend an update if that's possible.

If the problem persists with a more recent cluster, please install 2.9.3 and try the following:
```
$ telepresence uninstall agent api
```
Then try the intercept again.
