### ISSUE TITLE
telepresence CLI requires traffic-manager to have been installed with helm

### ISSUE THREAD

**Issue by jsalem-brex** [telepresenceio/telepresence#2824]
**Describe the bug**
We're in the process of adding traffic-manager to our gitops platform to automate management of the service and prevent CLI users from accidentally changing the version installed in the clusters.

The telepresence CLI requires the traffic-manager to have been installed with helm. Using a GitOps platform, e.g., fluxcd, will not necessarily create a `helm.sh/release.v1` secret. Telepresence specifically looks for a helm release (equivalent of `helm list --all-namespaces` as I understand it) to verify that the traffic-manager has been installed:
https://github.com/telepresenceio/telepresence/blob/eefede9394e9b7dea6591ceac056058ce497bc06/pkg/install/helm/install.go#L155-L163

This check will fail and exit early even if the traffic-manager is up and running in the cluster.

Example:
```
$ telepresence connect --mapped-namespaces [redacted] --context [redacted]

telepresence: error: connector.Connect: traffic manager not found, if it is not installed, please run 'telepresence helm install'
```

Even though everything is up and running in the cluster
```
$ k get all -n ambassador --context [redacted]
NAME                                   READY   STATUS      RESTARTS   AGE
pod/traffic-manager-5864b86c55-lv7fh   1/1     Running     0          12h
pod/traffic-manager-test-connection    0/1     Completed   0          22h
pod/upgrade-legacy-4nzrd               0/1     Completed   0          22h

NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
service/agent-injector    ClusterIP   [redacted]   <none>        443/TCP              22h
service/traffic-manager   ClusterIP   None             <none>        8081/TCP,15766/TCP   22h

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/traffic-manager   1/1     1            1           22h

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/traffic-manager-5864b86c55   1         1         1       22h

NAME                         COMPLETIONS   DURATION   AGE
job.batch/uninstall-agents   1/1           3s         22h
job.batch/upgrade-legacy     1/1           6s         22h
```

Manually adding a `helm.sh/release.v1` secret that I copied from another cluster that was installed via `telepresence helm install` made the CLI work.

For reference, we are installing traffic-manager by `helm template ...`-ing the helm chart and then customizing it for our clusters before tracking it with our GitOps platform.

**To Reproduce**
1. Install traffic-manager using a gitops platform that won't create a helm release.
2. Successfully deploy traffic-manager and see logs indicating it is alive
3. `telepresence connect ...` -> `... Traffic manager not found ...`

**Expected behavior**
Telepresence shouldn't use helm as a mechanism for detecting whether the traffic-manager is installed. The traffic-manager can successfully be installed and maintained by means other than helm. Usage of telepresence should not be gated on the installation method.

**Versions (please complete the following information):**
2.7.6

**Comment by josecv** [comment]
Thanks for the bug report! This has now been fixed in #2823, and the fix will be released with 2.8.3
