### ISSUE TITLE
telepresence: error: executable mismatch. Connector using, add ignore case

### ISSUE THREAD

**Issue by borgez** [telepresenceio/telepresence#2829]
telepresence version
Client: v2.8.2 (api v3)
Root Daemon: v2.8.2 (api v3)
User Daemon: v2.8.2 (api v3)

telepresence connect
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
telepresence: error: executable mismatch. Connector using C:\src\Tools\telepresence\telepresence.exe, configured to use c:\src\Tools\telepresence\telepresence.exe, please run 'telepresence quit -s' and reconnect

https://github.com/telepresenceio/telepresence/blob/614c6e111b19fe20fa9974503527c027567bc7b3/pkg/client/cli/cliutil/version_check.go#L29

**Comment by cindymullins-dw** [comment]
Hi @borgez , just to confirm did you try the 'telepresence quit -s' command and did the error persist after that?

**Comment by borgez** [comment]
> Hi @borgez , just to confirm did you try the 'telepresence quit -s' command and did the error persist after that?

Yes, quit -s, kill service, reboot
now i purge old user profile (windows) and now it works

**Comment by borgez** [comment]
After update  v2.8.2->v2.9.5 hapens again

**Comment by thallgren** [comment]
Do you have a `daemons.userDaemonBinary` entry in your `config.yml` file? If so, please remove it.

**Comment by borgez** [comment]
i dont have config.yml, where it must be?

check in:
c:\src\Tools\telepresence\
%userprofile%\AppData\Local\telepresence\
%userprofile%\AppData\Roaming\telepresence\

**Comment by plucmoquin** [comment]
Same issue on windows here.

I don't have a config.yml, i did a full search of my system.

**Comment by mausch** [comment]
I just got this on Windows too. Fix: run as admin.

**Comment by thallgren** [comment]
@mausch what version are you on?

**Comment by mausch** [comment]
v2.16.1
