### ISSUE TITLE
Failure intercepting with multiline env vars

### ISSUE THREAD

**Issue by deedubs** [telepresenceio/telepresence#2837]
**Describe the bug**
We are attempting to intercept a service which has a multi-line env var.  When this is being written via `--env-file` it's incorrectly written as:

```
FIRST_VAR=abc
MY_LONG_VAR=line1
line2
line3
ANOTHER_VAR=123
```

**Expected behavior**
Multiline env vars should be double-quoted and have their line breaks replaced with `\n`
```
FIRST_VAR=abc
MY_LONG_VAR="line1\nline2\nline3"
ANOTHER_VAR=123
```
**Versions (please complete the following information):**
```
Client: v2.8.2 (api v3)
Root Daemon: v2.8.2 (api v3)
User Daemon: v2.8.2 (api v3)
```

**Comment by thallgren** [comment]
When you write `--env-var`, do you mean the `telepresence intercept` flag `--env-file`? I don't think we use `--env-var` anywhere.

**Comment by deedubs** [comment]
Updated, Apologies, I was indeed referring to `--env-file`

**Comment by cindymullins-dw** [comment]
HI @deedubs , could you check [this issue](https://github.com/telepresenceio/telepresence/issues/2718) and perhaps we link these together?

**Comment by deedubs** [comment]
Yep. My bad
