### ISSUE TITLE
No Remote IP in Teperesence V2

### ISSUE THREAD

**Issue by naty88** [telepresenceio/telepresence#2868]
I'm using telepresence v2.8.5 (have also tested with v2.6.8)  on Ubuntu 20.04, in status I see that Remote IP is `<nill>` and 
additionally, there is a Local IP `127.0.0.53`. 
```
Root Daemon: Running
  Version   : v2.8.5 (api 3)
  DNS       :
    Local IP        : 127.0.0.53
    Remote IP       : <nil>
    Exclude suffixes: [.com .io .net .org .ru .fritz.box]
    Include suffixes: []
    Timeout         : 8s
```
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9949836/telepresence_logs.zip)

If I call `curl -ik https://kubernetes.default`, it's failed: `curl: (7) Failed to connect to kubernetes.default port 443: Connection refused`

Some other outputs, that might be helpful:
<details>
<summary>resolvectl</summary>
<br>
`<pre><b>Global</b>
       LLMNR setting: no                  
MulticastDNS setting: no                  
  DNSOverTLS setting: no                  
      DNSSEC setting: no                  
    DNSSEC supported: no                  
          DNSSEC NTA: 10.in-addr.arpa     
                      16.172.in-addr.arpa 
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa 
                      18.172.in-addr.arpa 
                      19.172.in-addr.arpa 
                      20.172.in-addr.arpa 
                      21.172.in-addr.arpa 
                      22.172.in-addr.arpa 
                      23.172.in-addr.arpa 
                      24.172.in-addr.arpa 
                      25.172.in-addr.arpa 
                      26.172.in-addr.arpa 
                      27.172.in-addr.arpa 
                      28.172.in-addr.arpa 
                      29.172.in-addr.arpa 
                      30.172.in-addr.arpa 
                      31.172.in-addr.arpa 
                      corp                
                      d.f.ip6.arpa        
                      home                
                      internal            
                      intranet            
                      lan                 
                      local               
                      private             
                      test                

<b>Link 5 (docker0)</b>
      Current Scopes: none
DefaultRoute setting: no  
       LLMNR setting: yes 
MulticastDNS setting: no  
  DNSOverTLS setting: no  
      DNSSEC setting: no  
    DNSSEC supported: no  

<b>Link 4 (br-0d113d246fa5)</b>
      Current Scopes: none
DefaultRoute setting: no  
       LLMNR setting: yes 
MulticastDNS setting: no  
  DNSOverTLS setting: no  
      DNSSEC setting: no  
    DNSSEC supported: no  

<b>Link 3 (wlp4s0)</b>
      Current Scopes: DNS                      
DefaultRoute setting: yes                      
       LLMNR setting: yes                      
MulticastDNS setting: no                       
  DNSOverTLS setting: no                       
      DNSSEC setting: no                       
    DNSSEC supported: no                       
  Current DNS Server: 192.168.178.1            
         DNS Servers: 192.168.178.1            
                      fd00::de39:6fff:fe15:447c
          DNS Domain: ~.                       
                      fritz.box                

<b>Link 2 (enp2s0)</b>
      Current Scopes: none
DefaultRoute setting: no  
       LLMNR setting: yes 
MulticastDNS setting: no  
  DNSOverTLS setting: no  
      DNSSEC setting: no  
    DNSSEC supported: no  
</pre>`
</details>

<details open>
<summary>iptables -t nat -L -n -v</summary>
<br>
<pre>Chain PREROUTING (policy ACCEPT 1 packets, 291 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   57  9794 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 1 packets, 291 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 152 packets, 12347 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  180 14902 TELEPRESENCE_DNS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 166 packets, 12814 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
   75  7565 MASQUERADE  all  --  *      !br-0d113d246fa5  172.20.0.0/16        0.0.0.0/0           

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-0d113d246fa5 *       0.0.0.0/0            0.0.0.0/0           

Chain TELEPRESENCE_DNS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    1    71 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:42993
    1    71 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:60136
    1    96 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:52579
    1    71 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:41465
    1    86 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:60578
    1    71 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:51808
    1    71 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:39535
    1    71 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:45032
    1    72 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:52003
    1    80 RETURN     udp  --  *      *       127.0.0.1            0.0.0.0/0            udp spt:52260
   28  2555 DNAT       udp  --  *      *       0.0.0.0/0            127.0.0.53           udp dpt:53 to:127.0.0.1:48169</pre>
</details>

<details open>
<summary>lsb_release -a</summary>
<br>
<pre>No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
</pre>
</details>

<details open>
<summary>uname -a</summary>
<br>
<pre>Linux nataliia-XMG-CORE-REN-E21 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</pre>
</details>

**Comment by thallgren** [comment]
Is this giving you any problems besides what's shown in the status output?

**Comment by cindymullins-dw** [comment]
Hi @naty88 , if it was working previously, it could be the connection to the Traffic Manger has broken due to connectivity issues or going idle, and DNS resolution stops working.  In that case you could try re-installing the Traffic Manger.  Also just a note that the [new client struct that was added to the Helm chart in 2.8.0](https://www.getambassador.io/docs/telepresence/latest/release-notes/#2.8.0) might help.  It contains a connectionTTL that controls how long the traffic manager will retain a client connection while client is idle.

**Comment by thallgren** [comment]
Closing this as no further info was provided.
