### ISSUE TITLE
Traffic-agent container is never ready

### ISSUE THREAD

**Issue by petr-buchyn** [telepresenceio/telepresence#2869]
**Describe the bug**
I'm trying to intercept the service in my EKS cluster. Telepresence injects `traffic-agent` container to the pod. However, this container never becomes ready, since it fails readiness probes. When i run `kubectl describe pod my-pod-name`, I can see, what readiness probes are failing:

```
  Warning  Unhealthy  104s              kubelet            Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
  Warning  Unhealthy  5s (x9 over 75s)  kubelet            Readiness probe failed: Get "http://10.0.103.16:80/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

When I ran `kubectl logs my-pod-name -c traffic-agent` before `telepresence loglevel debug` I saw the following error:

```
2022-11-07 13:32:36.6256 info    sidecar : supportsHTTP2: probing for HTTP/2 support... : base-url="http://127.0.0.1:80"
2022-11-07 13:32:38.1276 info    sidecar : supportsHTTP2: result =  false : base-url="http://127.0.0.1:80"
2022-11-07 13:32:38.1313 info    sidecar : Connected to Manager 2.8.5
2022-11-07 13:33:26.5769 error   sidecar/lookupDNSWait : LookupDNS _dns.resolver.arpa. SVCB: rpc error: code = Unimplemented desc = unsupported DNS query type SVCB
```

**To Reproduce**
1. When I run `telepresence intercept my-service-name --namespace=my-namespace --preview-url=false --port=33003 --http-header=all --mount=false`
2. I see message that intercept is successfull
3. So I look at `kubectl get pods`
4. See that `my-pod` has 1 of 2 containers ready, and `traffic-agent` container never becomes ready

**Expected behavior**
`traffic-agent` container becomes ready, intercept is working

**Versions (please complete the following information):**
 - Output of `telepresence version`:
 ```
Client: v2.8.5 (api v3)
Root Daemon: v2.8.5 (api v3)
User Daemon: v2.8.5 (api v3)
```

 - Operating system of workstation running `telepresence` commands - **MacOs Ventura**
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine] **- Amazon EKS**
 
Logs:

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9952627/telepresence_logs.zip)

**Comment by thallgren** [comment]
Can you please try  `telepresence install --upgrade --set agent.logLevel=debug` and then try again, and the check the logs of the traffic-agent once more?

**Comment by petr-buchyn** [comment]
@thallgren looks like Telepresence is not working for me anymore :)

Now when I'm trying to intercept service, it exits with error:

```
telepresence: error: rpc error: code = Canceled desc = grpc: the client connection is closing
```

As far as I understand, this has something to do with the message on Ambassador site "You have reached the limit of services for this account".

But I don't want to upgrade my plan just to debug, why Telepresence is not working :)

Me and company I work for will probably look for an alternative to Telepresence, so you may close this issue. 

Thanks!

**Comment by cindymullins-dw** [comment]
HI @petr-buchyn , I don't think you're being hard-limited here, it's just a usage notification so should not be the cause of the error. Usually a readiness error means the Traffic Agent can’t community with the Traffic Manager. The only error we see in the logs is about the DNS Resolver.  

Checking with Support, we haven’t seen this kind of error being cued by unsupported query type (in this case SVCB) but think it can be resolved.  In 2.8 Thomas added a number query types that are supported by the DNS Resolver but SVCB is not on the list.  So we'd suggest adding it to `include suffixes` manually. (_Suffixes for which the DNS resolver will always attempt to do a lookup. Includes have higher priority than excludes. Can be globally configured in the Helm chart._) That’s a config adjustment you can make in the Helm chart.

You can refer to [Allow specifying host IP with an intercept](https://www.getambassador.io/docs/telepresence/latest/reference/config/#dns-and-routing)

We'd be happy to check your debug logs as well if the above doesn't work.

**Comment by petr-buchyn** [comment]
@thallgren @cindymullins-dw thank you very much for your answers. Unfortunately, Telepresence did not give me a chance to debug this issue, so for now I'm trying to replace Telepresence with another solution.

I greatly appreciate your hard work on an open-source project. Thank you, and may your project be successful.
