### ISSUE TITLE
Limit CPU usage

### ISSUE THREAD

**Issue by james-atwill-hs** [telepresenceio/telepresence#287]
While #20 limited the memory requested, it did not limit the CPU requested. It'd be handy to specify some limit (our dev cluster forbids requesting pods without request/limit cpu/memory).

Without it, --run appears to hang and I have to kubectl edit the deployment to add a cpu limit.

**Comment by plombardi89** [comment]
Thanks for the feedback. Definitely looks like omission to not limit the CPU. We will look to address this soon.

**Comment by ark3** [comment]
@james-atwill-hs Does release 0.68 or later fix this issue for you?
