### ISSUE TITLE
Check permissions before performing actions

### ISSUE THREAD

**Issue by james-atwill-hs** [telepresenceio/telepresence#288]
It would be a nice feature if telepresence did a quick check to see if the user has permissions to perform all the operations needed to do the command they're running before it starts to make changes (I think `kubectl auth can-i` may help?)

**Comment by plombardi89** [comment]
Hi James,

Thanks for the feedback. This is a good idea and we will look into this soon.

Cheers,
Phil

**Comment by donnyyung** [comment]
We should still do this for Telepresence 2.
