### ISSUE TITLE
support manually add volume to mounts of my-app container  in addition to auto-generate it

### ISSUE THREAD

**Issue by losingwind** [telepresenceio/telepresence#2881]
We are using vault to manage our configs, and these configs are mounted to contains by vault-agent sidecar, which all are 
 declared in pod's annotations.  So the traffic-manager cannot perceive them during intecepting.

Can you pls add a function that we can manaully add it?

**Comment by thallgren** [comment]
Can you please try using the Helm chart value `agentInjector.webhook.reinvocationPolicy=IfNeeded` and see if that makes a difference? It should result in that the webhook is called again after the vault-agent sidecar has made its additions.

**Comment by losingwind** [comment]
@thallgren Thank you, it works! I'll close this issue.
