### ISSUE TITLE
telepresence: error: intercepts are disabled because the traffic-manager is unable to determine what image to use for injected traffic-agents.

### ISSUE THREAD

**Issue by SomeAkk** [telepresenceio/telepresence#2882]
**Describe the bug**
Try to run:
`telepresence intercept ...`

Got:
`telepresence: error: intercepts are disabled because the traffic-manager is unable to determine what image to use for injected traffic-agents.`

Also in traffic-manager logs i see:
`2022-11-11 18:43:39.1957 warning unable to get Ambassador Cloud preferred agent image: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 104.155.181.163:443: connect: connection refused"`

Server without internet, but i download and then copied to it and then deploy that images:

- datawire/tel2:2.8.5 
- datawire/ambassador-telepresence-agent:1.13.3 

Also on laptop i got same client version.
This mean that on server no any traffic-agents which need to traffic-manager?
As i need to configure anything?

**Comment by thallgren** [comment]
It means that your traffic-manager is unable to contact Ambassador Cloud to get the name of the image to use. You'll need to tell the traffic-manager explicitly. Try using:
```
telepresence helm install --upgrade --set agent.image.name=ambassador-telepresence-agent,agent.image.tag=1.13.3
```
You'll find more info about this here: https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config/#image-configuration
