### ISSUE TITLE
Where laptop-side configuration saved?

### ISSUE THREAD

**Issue by SomeAkk** [telepresenceio/telepresence#2886]
MacOS. Catalina. Intel.

I install telepresence like in [guide](https://www.getambassador.io/docs/telepresence/latest/install/) via `brew`.

Then i found, that i need to increase untercept timeout value: so i need to change config.yaml.
In [doc](https://www.getambassador.io/docs/telepresence/latest/install/) config.yaml file location for MacOS is 
`$HOME/Library/Application Support/telepresence/config.yml`. 

Then, i open that path and found that there is no any `config.yml`. I thing that i must create it, so i create `config.yml` and restart telepresence on my laptop (with laptop). But when i start use telepresence it didn't use settings from my `$HOME/Library/Application Support/telepresence/config.yml`.

So:
- using brew where i need to search config.yml?
- as i need to create it?
- where i need to locate it to start telepresence use settings from it?
- is need some specials rigth and ovners for that file?

**Comment by craftey** [comment]
The path is correct. I have created a config.yml there:
```
$ cat "$HOME/Library/Application Support/telepresence/config.yml"
logLevels:
  userDaemon: debug
  rootDaemon: debug
```
In my case to enable some debug logging. This works, at least on my machine, MacOS Monterey.

I have learned the suffix must be yml, if you use yaml it wont be found.

**Comment by thallgren** [comment]
This is works as intended. You'll need to create the file if it's not there. If it doesn't work, please check that the file is where you think it is, and that you're quoting the path correctly as in the above example (there's a space in "Application Support" which sometimes causes confusion when editing it).
