### ISSUE TITLE
Allow other shells to join existing telepresence session.

### ISSUE THREAD

**Issue by james-atwill-hs** [telepresenceio/telepresence#289]
With `vpn-tcp`, my whole machine is teleported into the pod. It would speed up debugging if I could open another shell and have it "join" the existing session such that the command I run has `PRESENCE_ROOT` and the various other Kubernetes environment variables without having to do the heavy lifting of VPN again.

I imagine a usecase where I do `telepresence --swap-deployment myservice --run-shell` in a shell, but in my IDE I run my application as `telepresence --join ./myapp`.

**Comment by ark3** [comment]
See also #257.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
