### ISSUE TITLE
split proxyCluster to proxyPod and proxyService

### ISSUE THREAD

**Issue by j2gg0s** [telepresenceio/telepresence#2911]
We set proxyCluster to false when manager pod is accessible.
However, this can't represent service is accessible and don't need proxy.
Under most circumstance, access to service depends on kube-proxy and kube-proxy does not exists locally.

So let we split proxyCluster into proxyPod and proxyService?

Besides this, alsoProxySubnets should be omit when we don't need proxy pod.

**Comment by cindymullins-dw** [comment]
Hi @j2gg0s , sorry to ask but is proxyCluster a kubernetes spec or specifically related to your deployment?  I don't find this in the Helm chart for Telepresence.  Can you give us some more context?

**Comment by j2gg0s** [comment]
@cindymullins-dw 

Set here
https://github.com/telepresenceio/telepresence/blob/2dd5b5b431888348c5287234fa2331df5fd97541/pkg/client/rootd/session.go#L649

Used here
https://github.com/telepresenceio/telepresence/blob/2dd5b5b431888348c5287234fa2331df5fd97541/pkg/client/rootd/session.go#L600

**Comment by thallgren** [comment]
@j2gg0s you write "Besides this, alsoProxySubnets should be omit when we don't need proxy pod". I'm not so sure of that. The fact that the client has access to the pod subnets doesn't necessarily mean that it has access to all networks that the pod has access to.

I agree though, that a more fine grained selection could be made here. Right now, you need to control this with `neverProxySubnets` and `alsoProxySubnets`.

**Comment by j2gg0s** [comment]
@thallgren 
According to my understanding, 
if traffic-manager pod is accessible, and proxyCluster will be set to false,  and we will ignore alsoProxySubnets.
So alsoProxySubnets cant let telepresence proxy service subnet

**Comment by j2gg0s** [comment]
@thallgren will we split this config? If the plan is determined, can i provide PR?

**Comment by thallgren** [comment]
@j2gg0s I haven't had time to make a deeper assessment about what's needed here yet. If you have modifications that solve your use case, then I'd be happy to review them.

**Comment by j2gg0s** [comment]
> @j2gg0s I haven't had time to make a deeper assessment about what's needed here yet. If you have modifications that solve your use case, then I'd be happy to review them.

@thallgren I offer a simple solution, https://github.com/telepresenceio/telepresence/pull/2946

**Comment by cindymullins-dw** [comment]
@j2gg0s , are you a member of our Slack community at a8r.io/slack?  If you please join the #telepresence-dev channel there.    You're also welcome to join our [Monthly Contributors meeting](https://github.com/telepresenceio/telepresence/blob/release/v2/MEETING_SCHEDULE.md).

**Comment by thallgren** [comment]
Closed by #3074
