### ISSUE TITLE
Intercept DNS resolution

### ISSUE THREAD

**Issue by s1apped** [telepresenceio/telepresence#2921]
**Describe the bug**

After successfull connection when I run intercept and then try debug using intellij and env variables It’s not able to resolve DNS service name e.g config-service.mynamespace.svc.cluster.local and getting Unknow Host Exception.
Is telepresence able to resolve it or only IP?
I’m using MacOS and Minikube.

**Comment by cindymullins-dw** [comment]
Hi @s1apped, Telepresence should be able to resolve.  Could you check our [docs here on DNS resolution](https://www.getambassador.io/docs/telepresence/latest/reference/dns#dns-resolution)?  "The DNS resolver will always be able to resolve services using `<service-name>.<namespace> `regardless of intercepts."  We're also making some updates to Telepresence with Minikube which will be available soon.

**Comment by cindymullins-dw** [comment]
See [release notes for 2.13.2](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.13.2) for details on 'Enhanced Local Cluster Discovery for macOS and Windows'.
