### ISSUE TITLE
Intercepts in multiple namespaces simultaneously

### ISSUE THREAD

**Issue by echozio** [telepresenceio/telepresence#2923]
**Please describe your use case / problem.**
We're using telepresence to intercept projects deployed to private virtual clusters, in which most of them will have their own namespace.
Prior to v2.8.2 we had taken this for granted as we generally had no reliance on namespace-scoped DNS queries, or at least when we did it would be the "last" deployment to be intercepted and remain unaffected.
However we soon realized after upgrading that not being able to intercept services in multiple namespaces simultaneously would be a problem.

**Describe the solution you'd like**
An option to run intercepts without a namespace (i.e. no namespace-scoped DNS resolution) or to pin all intercepts to a namespace different to where the intercepted workload resides, thereby simply requiring all DNS resolution to use FQDN's would work perfectly for our use-cases.

**Describe alternatives you've considered**
 - Currently our work-around is to use an older version of telepresence.
 - Deploy all services to the same namespace (this is something we would like to avoid).

**Versions (please complete the following information)**
 - \>= v2.8.2

**Comment by thallgren** [comment]
Telepresence will always logically place the workstation in a namespace, and being able to do namespace-scoped DNS resolution is just one of the reasons for doing so. Another is that outbound network requests that originate on the workstation must appear to originate from the intercepted namespace in the cluster, or many use-cases that have various rules in place that limits who can connect to where, will brake.

The fact that your use-case "worked" prior to 2.8.1, was because the workstation was, quite literally, placed in a random namespace, and you didn't have any such rules limiting the connections. I would recommend against continuing using a setup like that, because it's prone to unexpected errors.

What I would recommend, if intercepting multiple namespaces simultaneously from the same workstation is a requirement, is to use Telepresence in a VM (vagrant controlled perhaps), or from a docker container. That will enable multiple telepresence clients to run simultaneously, one for each namespace.

As a side note (and admittedly not so easy to find), I should mention that the footnotes on this page have always been there (page here is from 2.7): https://www.getambassador.io/docs/telepresence/2.7/reference/routing

**Comment by Symbianx** [comment]
@thallgren just came across your reply to this issue.

I completely understand the reasoning to only allow intercepts to the same namespace but I'm wondering if you would be open to adding a flag to bypass this behavior. 

While I understand that running things in a docker container could be an acceptable workaround, in our case it means we would need to start developing and connecting our IDEs the the docker containers which we would like to avoid.

**Comment by thallgren** [comment]
@Symbianx it's not trivial to bypass. Telepresence does not resolve the names. It delegates the DNS resolution to an agent in the namespace that it is connected to. The pods in that namespace has a `/etc/resolv.conf` file that contains a search path similar to `search <namespace>.svc.cluster.local svc.cluster.local cluster.local`.

You can read more about Kubernetes DNS resolution [here](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/).

**Comment by Symbianx** [comment]
@thallgren thanks for the quick response.
I understand that bypass was not the best choice of word. By that I meant to add a flag to the intercept command to allow the intercept to be done in a separate namespace from the connect, accepting that DNS resolution will not work exactly as expected.

**Comment by thallgren** [comment]
I think that is a somewhat unclean solution, and as such, I'm concerned that it will cause problem in other areas.

Do you know that you can run one intercept without a Docker container, and then another with a Docker container? That way, you'll only need to use Docker when you indeed do multiple simultaneous intercepts that span multiple namespaces, and you won't need it for the first intercept.

**Comment by thallgren** [comment]
@Symbianx you might find this blogpost helpful, should you decide to try docker containers after all: https://www.getambassador.io/blog/docker-and-jetbrains-telepresence-integrations

**Comment by Mattie112** [comment]
If I start telepresence without the namespace flag (so the default namespace) should I then be able to intercept in two namespaces? We have a namespace for each microservice and I needed to do some black-magic debugging. Thought of telepresence as a great way do to this but I am only getting it to work in a single namespace. The `--namespace` flag (deprecated apparently) does not seem to help. It would be a bit strange to run two docker containers, install telepresence there, intercept one app in each and make sure all the port forwards are still correct so you can run a debugger. 

If this used to be possible I might rollback to see if it works in an older version.

**Comment by Symbianx** [comment]
Hey @thallgren, sorry I only had time to get back to this now.

> Do you know that you can run one intercept without a Docker container, and then another with a Docker container?

I gave this a try but if I'm try to connect with `--docker` after connecting without it I get this error:
```
telepresence connect: error: option --docker cannot be used as long as a daemon is running on the host. Try telepresence quit -s
```

I connected with the simple commands:
``` shell
telepresence connect --namespace default
telepresence connect --docker --namespace kafka
# error happens
```

Am I missing something?

**Comment by Mattie112** [comment]
Initial state: telepresence not running:

```
telepresence connect
# I now have a docker container (see docker ps) running
<switch context to 2nd cluster>
telepresence connect
# I now have a second docker container running
```

Not sure yet how this would be useful though. Perhaps if you then run the intercept commands and expose the ports or use the `--net` option to have your local containers connect via that telepresence container?
