### ISSUE TITLE
Traffic Manager keeps getting "stuck" and needs to be restarted

### ISSUE THREAD

**Issue by aaccioly** [telepresenceio/telepresence#2931]
Every few days Telepresence V2 starts throwing the following error when one tries to intercept a service:

```
❯ telepresence intercept my-service-http --workload my-service --namespace my-namespace --port 8080:http --env-file ~/myconfig.env
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /Users/aaccioly/Library/Logs/telepresence '/Users/aaccioly/Library/Application Support/telepresence'
Password:
Launching Telepresence User Daemon
Connected to context my-cluster ([https://my-cluster-5de32eb8.hcp.eastus.azmk8s.io:443](https://my-cluster-5de32eb8.hcp.eastus.azmk8s.io/))
telepresence intercept: error: connector.CreateIntercept: rpc error: code = DeadlineExceeded desc = request timed out while waiting for agent my-service to arrive
```

This is happening both on Azure and GCP.

Looking at server side logs we can always find a log like the one bellow before traffic-manager goes unresponsive:

```
  "_source": {
    "@timestamp": "2022-12-04T20:05:12.936Z",
    "log": "I1204 20:05:12.936129       1 request.go:601] Waited for 1.006730828s due to client-side throttling, not priority and fairness, request: GET:https://10.0.0.1:443/apis/path/to/one/of/our/own/services",
    "kubernetes_pod_name": "traffic-manager-7c4585bdcf-krd9k",
    "kubernetes_namespace_name": "ambassador",
    "kubernetes_host": "aks-default-42385751-vmss000000",
    "kubernetes_container_name": "traffic-manager",
    "kubernetes_container_image": "docker.io/datawire/tel2:2.6.6",
    "kubernetes_labels_app": "traffic-manager"
  }
```

Restarting traffic manager fixes the problem (for a few days until Traffic Manager gets stuck again):

```
kubectl rollout history deployment/traffic-manager
```

The theory from our DevOps team so far is that the underlying errors are expected (throttling is outside of our control as those are managed  clusters). Assuming that this is true, the ask would be to introduce some sort of retrial logic in Traffic Manager, or at least a way for traffic-manager to recover when the underlying requests fail.

**Expected behavior**

I would expect Traffic Manager to recover / self-heal without a manual restart.

**Versions:**

- Telepresence:
```
❯ telepresence version
Enhanced Client: v2.9.3
Root Daemon    : v2.9.3
User Daemon    : v2.9.3
Traffic Manager: v2.6.6
```
 - Client OS: macOS 13.0.1 (22A400)
 - Kubernetes clusters running in Azure and GCP:
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", 
GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", 
GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", 
GitCommit:"3396beebcd97ed3b01f57127fba1b8565b311acb", GitTreeState:"clean", BuildDate:"2022-06-04T17:58:54Z", 
GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by thallgren** [comment]
@aaccioly can you please try upgrading to 2.9.5 (and also upgrade the traffic-manager, a lot has happened since 2.6.6) and see if this problem persists? If it does, would it be possible for you to examine the current state of the traffic-manager pod? What type of resource consumption does it have? Does the event log offer any additional info?

**Comment by aaccioly** [comment]
@thallgren, Happy Boxing day! Sure. Updating the client to 2.9.5 didn't fix it for me, DevOps is currently working on updating traffic-manager to version 2.9.5. Assuming that it fails again I'll send you a fresh batch of Telepresence logs.

AFAIK everything is fine in terms of resource consumptions (as in CPU, Memory, IO, etc) all looks to be fine. Other than the usual throttling going on in Azure and GKE clusters. 

I couldn't find anything relevant on the logs other than variations of the message above just before Traffic Manager gets stuck, but if you do have any commands that you would like me to run on the cluster to get more info about the pods or specific logs please do let me know and I'll try to get authorization to share this information with Ambassador.

**Comment by jsalem-brex** [comment]
I'm seeing the same behavior in my `traffic-manager`s. We're on 2.7.6 (client and server). It seems less consistent to repro, but I'm assuming this is based on "time to throttle" which will vary by traffic and control plane configuration. Similarly, a restart of the `traffic-manager` appears to rectify things. @aaccioly have you tested with the newer version and seen an improvement? In the interim, I think we'll set up something to periodically restart the `traffic-manager` deployments to preempt the issue.

**Comment by aaccioly** [comment]
@jsalem-brex, the traffic-manager update is looking promising. It has been 10 days without a restart (before I had to restart it about once every couple of days). 

I'll still keep this ticket open for a couple of week, as today I've started getting frequent connection timeouts during intercept, which was one of the known symptoms before traffic-manager went kaboom. Also, the last 10 days where very quiet (not a lot of traffic in the clusters). If it lasts another 10 days with most devs now back in the office I'll close this issue.

```
❯ telepresence connect
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /Users/aaccioly/Library/Logs/telepresence '/Users/aaccioly/Library/Application Support/telepresence'
Password:
Launching Telepresence User Daemon
Connected to context my-cluster (https://my-cluster-7a0401d3.hcp.eastus.azmk8s.io:443)
❯ telepresence intercept my-deployment-http --workload my-workload --namespace my-namespace --port 8080:http --env-file ~/myconfig.env
telepresence intercept: error: connector.CreateIntercept: request timed out while waiting for agent my-workload.my-namespace to arrive
❯ telepresence intercept my-deployment-http --workload my-workload --namespace my-namespace --port 8080:http --env-file ~/myconfig.env
Using Deployment my-deployment
intercepted
   Intercept name         : my-deployment-http
   State                  : ACTIVE
   Workload kind          : Deployment
   Destination            : 127.0.0.1:8080
   Service Port Identifier: http
   Volume Mount Point     : /var/folders/44/96yq09r13dq_k5zn63pt82nr0000gn/T/telfs-3883217245
   Intercepting           : all TCP requests
```

**Comment by cindymullins-dw** [comment]
@aaccioly , @jsalem-brex , just checking in on how the traffic-manager update is working for you?

**Comment by jsalem-brex** [comment]
I haven't attempted an upgrade yet since there are breaking changes to CLI arguments between minor revisions, e.g., removing `-r` and `-u` in favor of some new argument, which would require tooling changes on our part. May get around to it later this month.

For now, I'm going to look into scheduling a cronjob that will restart the traffic-managers periodically. I'll be keeping an eye on this ticket in the hopes there is a solution.

**Comment by aaccioly** [comment]
@cindymullins-dw, on my side same deal as before. I still haven't had to restart the cluster, but it looks like the number of times that I'm getting `telepresence intercept: error: connector.CreateIntercept:` is creeping up. I need a couple of weeks to say for sure if 2.9.5 has fully fixed the problem, but it has certainly helped with it (as in, by now traffic-manager 2.6.6 would certainly have required several restarts).

**Comment by jsalem-brex** [comment]
@aaccioly any updates since upgrading? We're eyeing upgrading to the newest version to get out of our cronjob restarting traffic-managers regularly.

**Comment by aaccioly** [comment]
@jsalem-brex . It didn't fully fix the problem, but it has certainly helped quite a bit. It went from having to restart the traffic-manager every 3 days to once a month or so.

The solution for us was a combination of updating to Telepresence v2.9.5 + a job that restarts traffic-manager every once in a while (should be pretty safe to to it every second Sunday or whatever schedule you see fit).

**Comment by xzhang-brex** [comment]
@aaccioly just want to let you know that we resolved this capacity issue by installing the namespace scoped traffic manager instead of the global scoped one inside the ambassador namespace.

**Comment by cindymullins-dw** [comment]
Client-side throttling happens when you have a huge cluster, owing to the large number of requests.  We've made some improvements to help with that in [2.13.0](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.13.0). See: https://github.com/telepresenceio/telepresence/pull/3116.  Please reopen if issues persist.
