### ISSUE TITLE
dns resolution on windows always requires suffix even with active intercept

### ISSUE THREAD

**Issue by tedchang77** [telepresenceio/telepresence#2939]
**Describe the bug**
services can only be reached using dns suffix and not the short name.

**To Reproduce**
PS C:\WINDOWS> telepresence loglevel debug
PS C:\WINDOWS> telepresence intercept local-deployment --namespace thx --local-only
PS C:\WINDOWS> curl http://ujm:8000
curl : The remote name could not be resolved: 'ujm'
At line:1 char:1
+ curl http://ujm:8000
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExcept
   ion
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\WINDOWS> telepresence gather-logs --output-file [telepresence_logs.zip](url)
**Expected behavior**
be able to connect to the service using the shortname (without dns suffix)

**Versions (please complete the following information):**
 - Output of `telepresence version`
 PS C:\WINDOWS> telepresence version
Enhanced Client: v2.9.5
Root Daemon    : v2.9.5
User Daemon    : v2.9.5
Traffic Manager: v2.9.5
 - Operating system of workstation running `telepresence` commands
 windows 10
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - gke autopilot 1.24PS C:\WINDOWS> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.5-gke.600", GitCommit:"fb4964ee848bc4d25d42d60386c731836059d1d8", GitTreeState:"clean", BuildDate:"2022-09-22T09:24:55Z", GoVersion:"go1.18.6b7", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
short names also don't work with global intercepts. 
short names work on wsl2 when using local only or global intercepts

**Comment by tedchang77** [comment]
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10200290/telepresence_logs.zip)

**Comment by mkirouac** [comment]
**Workaround**
To work around this issue, the added our namespace to the list of Windows DNS Suffixes search list. This does work and does not require any intercept. However, it is a workaround and would prefer a proper solution.

**Comment by simmsim** [comment]
Are there any updates to this? We're also facing the same issue on Windows 10 with Telepresence version 2.10.6.
