### ISSUE TITLE
Errors with determining the proper OpenShift context

### ISSUE THREAD

**Issue by jmcshane** [telepresenceio/telepresence#294]
When attempting to connect to a remote Openshift cluster, I am running into an issue because it continues to attempt to use the minishift binary to locate the IP address of the cluster. After doing some reading of the code, it appears that in the `check_if_in_local_vm` method here:

https://github.com/datawire/telepresence/blob/e739a1c69e507804a8c68eb86c572ca4088c2fe7/cli/telepresence#L2289

it only uses the presence of the minishift binary on the path to determine if the Openshift context is in a local VM. This is undocumented behavior and, honestly, not optimal for a workflow where I often switch between using a local minishift cluster and a remote Openshift cluster.

I would be willing to help discuss the problem further if there is a desire to do a more thorough job determining the proper context or contribute documentation if that is the way forward.

**Comment by ark3** [comment]
Thanks for the bug report. We could use help with better Openshift support for Telepresence. Can you suggest a good way to detect a Minishift context vs a remote cluster?

**Comment by jmcshane** [comment]
Looking at the docs about openshift contexts, it doesn't appear that there is anything immediate that would distinguish a remote cluster from a local cluster immediately. Here are some of the options I discovered:

- Arbitrary properties can be set on cluster contexts, so we could read a `cluster.local=true` property that is set using `oc config set`.
- Minishift spins up a local VM that it references with a `192-168-99-*` URL. We could use this base URL (or `127.0.0.1`) to determine if there is local

Let me know your thoughts on these two options.

**Comment by ark3** [comment]
Perhaps I've misunderstood the issue. Are you seeing Telepresence crash because `minishift ip` fails? Or is Telepresence doing the wrong thing because `check_if_in_local_vm()` returns the wrong answer?

**Comment by jmcshane** [comment]
Telepresence is doing the wrong thing because `check_if_in_local_vm()` returns the `true` when the current context is not pointing locally, as the method checks just for presence of the `minishift` binary rather than inspecting the context itself.

**Comment by ark3** [comment]
The method also checks whether the IP address returned by `minishift ip` is present in the `server` field of the cluster info associated with the specified context (or the current context, if no context is specified). I would have guessed that the context server IP check would have avoided Telepresence getting confused. 

If you can paste the output of `oc config view` (redacted as needed) here, I can walk through those steps manually to figure out why Telepresence might be getting it wrong. What I'd do is look at `oc config view`'s output, find the correct context in the contexts section to see what cluster is listed, and then find that cluster in the clusters section to see the server field. The contents of that field should not have MiniShift's IP address, but rather that of your remote cluster. I'll need the output of `minishift ip` and the name of the context you're passing to Telepresence too. 

As you've probably identified, the relevant code is in lines 2254-2264 and then lines 2289-2298.

Thanks for helping to debug this.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
