### ISSUE TITLE
address family not supported by protocol family

### ISSUE THREAD

**Issue by pangengteng** [telepresenceio/telepresence#2940]
use k8s with minikube run on mac 13.0
when I run telepresence connect, it connected and status is the same too
![Screenshot 2022-12-13 at 17 17 13](https://user-images.githubusercontent.com/31791826/207277033-90bc13e5-c3ce-4ac9-94e2-6aef177735fe.png)

but soon it changed to  Not connected when check status again
![Screenshot 2022-12-13 at 17 18 57](https://user-images.githubusercontent.com/31791826/207277438-8244ea87-0ff8-478b-828f-4293c77d0c28.png)

here is my log, please help

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10216274/telepresence_logs.zip)

**Comment by wduncanfraser** [comment]
I'm seeing the same on MacOS 13.1 using minikube. Telepresence connects and appears to be working at first, and then after a short while drops connection. Logs show:

```
2022-12-15 12:13:23.9885 error   connector/session : Error with k8sPortForwardDialer dial: Get "https://192.168.64.19:8443/api/v1/namespaces/ambassador/services/traffic-manager": dial tcp 192.168.64.19:8443: connect: address family not supported by protocol family
2022-12-15 12:13:23.9887 error   connector/session/remain : failed to depart from manager: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing Get \"https://192.168.64.19:8443/api/v1/namespaces/ambassador/services/traffic-manager\": dial tcp 192.168.64.19:8443: connect: address family not supported by protocol family"
```

On an attempt to reconnect. Telepresence shows connected for a short while before `telepresence status` showing disconnected again. During this window, kubectl is unable to connect to the cluster, giving "address family not supported by protocol family" error. Kubectl works fine again after telepresence gives up trying to connect in the logs.

**Comment by cindymullins-dw** [comment]
@pangengteng , @wduncanfraser , we have connectionTTL that helps extend connectivity. This value was introduced in [v2.8.0](https://www.getambassador.io/docs/telepresence/latest/release-notes/). Setting that value might help keep connection.  We're also making some updates to Telepresence with Minikube which will be available soon.

**Comment by yijiuping** [comment]
I have same issue with k8s in CentOS VM on my MacOS.

Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context kubernetes-admin@cluster.local (https://192.168.51.28:6443)
telepresence intercept: error: Unable to report intercept creation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing Get \"https://192.168.51.28:6443/api/v1/namespaces/ambassador/services/traffic-manager\": dial tcp 192.168.51.28:6443: connect: address family not supported by protocol family"

**Comment by Rylab** [comment]
I am also having this problem with telepresence since the Mac OS 13 update. Currently on Mac OS 13.1, minikube 1.28.0, and telepresence 2.10.3, and issue persists. It will connect to my local cluster, but errors out when trying to setup an intercept, with `Unable to connect to the server: dial tcp 192.168.64.21:8443: connect: address family not supported by protocol family`

EDIT: gather-logs output attached
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10460332/telepresence_logs.zip)

**Comment by l33t0** [comment]
> @pangengteng , @wduncanfraser , we have connectionTTL that helps extend connectivity. This value was introduced in [v2.8.0](https://www.getambassador.io/docs/telepresence/latest/release-notes/). Setting that value might help keep connection. We're also making some updates to Telepresence with Minikube which will be available soon.

Any updates on this @cindymullins-dw?

**Comment by cindymullins-dw** [comment]
@l33t0 , we made [this improvement ](https://github.com/telepresenceio/telepresence/pull/3165)to Telepresence in May.  Release notes[ here](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.13.2). If you try this could you let us know if it works better for you?
