### ISSUE TITLE
telepresence connect: error: daemon service did not start on windows

### ISSUE THREAD

**Issue by WhiteEraser** [telepresenceio/telepresence#2960]
telepresence connect:
 for daemon to start

**Describe the bug**
I install telepresence  v2.9.5 on windows 7. 
when i run commond "telepresence   connect ",i got the following result :

Launching Telepresence Root Daemon
telepresence connect: error: daemon service did not start: timeout while waiting
 for daemon to start
failed to scan connector logs: open C:\Users\Administrator\AppData\Local\telepre
sence\logs\connector.log: The system cannot find the file specified.
If you think you have encountered a bug, please run `telepresence gather-logs` a
nd attach the telepresence_logs.zip to your github issue or create a new one: ht
tps://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .

After,I created the file myself,then i run commond "telepresence   connect ",i got the following result :

Launching Telepresence Root Daemon
telepresence connect: error: daemon service did not start: timeout while waiting
 for daemon to start
If you think you have encountered a bug, please run `telepresence gather-logs` a
nd attach the telepresence_logs.zip to your github issue or create a new one: ht
tps://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .

logs file (cli.log  connector.log daemon.log ) is 0Bytes. And i do  not kow how  to make it work.

**Comment by thallgren** [comment]
Windows 7 is not a supported platform. Please upgrade to at least Windows 10.
