### ISSUE TITLE
daemon/session : PANIC: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by WhiteEraser** [telepresenceio/telepresence#2965]
i  got the fllowing result ,when i run the cmmond "telepresence version".

telepresence connect: error: connector.Connect: failed to connect to root daemon: rpc error: code = Unknown desc = PANIC: runtime error: invalid memory address or nil pointer dereference

deamon.log's  info :

2023-01-06 09:49:08.3748 info    ---
2023-01-06 09:49:08.3753 info    Telepresence daemon v2.9.5 (api v3) starting...
2023-01-06 09:49:08.3753 info    PID is 8932
2023-01-06 09:49:08.3753 info    
2023-01-06 09:49:08.4948 info    daemon/server-grpc : gRPC server started
2023-01-06 09:49:08.9886 info    daemon/session : -- Starting new session
2023-01-06 09:49:08.9934 info    daemon/session : Connected to Manager 2.9.5
2023-01-06 09:49:11.3521 error   daemon/session : PANIC: runtime error: invalid memory address or nil pointer dereference
github.com/telepresenceio/telepresence/v2/pkg/vif.openTun.func1
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/vif/device_windows.go:34
runtime.gopanic
	runtime/panic.go:884
runtime.panicmem
	runtime/panic.go:260
runtime.sigpanic
	runtime/signal_windows.go:255
golang.org/x/sys/windows.UTF16PtrToString
	golang.org/x/sys@v0.2.0/windows/syscall_windows.go:131
golang.zx2c4.com/wintun.logMessage
	golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/wintun.go:51
runtime.callbackWrap
	runtime/syscall_windows.go:396
runtime.cgocallbackg1
	runtime/cgocall.go:316
runtime.cgocallbackg
	runtime/cgocall.go:235
runtime.cgocallback
	runtime/asm_amd64.s:994
runtime.systemstack_switch
	runtime/asm_amd64.s:459
runtime.cgocall
	runtime/cgocall.go:168
syscall.SyscallN
	runtime/syscall_windows.go:557
syscall.Syscall
	runtime/syscall_windows.go:495
golang.zx2c4.com/wintun.CreateAdapter
	golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/wintun.go:92
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID
	golang.zx2c4.com/wireguard@v0.0.0-20220920152132-bb719d3a6e2c/tun/tun_windows.go:69
golang.zx2c4.com/wireguard/tun.CreateTUN
	golang.zx2c4.com/wireguard@v0.0.0-20220920152132-bb719d3a6e2c/tun/tun_windows.go:63
github.com/telepresenceio/telepresence/v2/pkg/vif.openTun
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/vif/device_windows.go:40
github.com/telepresenceio/telepresence/v2/pkg/vif.OpenTun
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/vif/device.go:52
github.com/telepresenceio/telepresence/v2/pkg/client/rootd.NewSession
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/client/rootd/session.go:255
github.com/telepresenceio/telepresence/v2/pkg/client/rootd.(*Service).startSession
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/client/rootd/service.go:300
github.com/telepresenceio/telepresence/v2/pkg/client/rootd.(*Service).manageSessions
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/client/rootd/service.go:269
github.com/datawire/dlib/dgroup.(*Group).goWorkerCtx.func1
	github.com/datawire/dlib@v1.3.1-0.20220715022530-b09ab2e017e1/dgroup/group.go:385
github.com/datawire/dlib/derrgroup.(*Group).Go.func2
	github.com/datawire/dlib@v1.3.1-0.20220715022530-b09ab2e017e1/derrgroup/errgroup.go:132
runtime.goexit
	runtime/asm_amd64.s:1594
2023-01-06 09:56:47.0800 info    daemon/session : -- Starting new session
2023-01-06 09:56:47.0866 info    daemon/session : Connected to Manager 2.9.5
2023-01-06 09:56:48.5718 error   daemon/session : PANIC: runtime error: invalid memory address or nil pointer dereference
github.com/telepresenceio/telepresence/v2/pkg/vif.openTun.func1
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/vif/device_windows.go:34
runtime.gopanic
	runtime/panic.go:884
runtime.panicmem
	runtime/panic.go:260
runtime.sigpanic
	runtime/signal_windows.go:255
golang.org/x/sys/windows.UTF16PtrToString
	golang.org/x/sys@v0.2.0/windows/syscall_windows.go:131
golang.zx2c4.com/wintun.logMessage
	golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/wintun.go:51
runtime.callbackWrap
	runtime/syscall_windows.go:396
runtime.cgocallbackg1
	runtime/cgocall.go:316
runtime.cgocallbackg
	runtime/cgocall.go:235
runtime.cgocallback
	runtime/asm_amd64.s:994
runtime.systemstack_switch
	runtime/asm_amd64.s:459
runtime.cgocall
	runtime/cgocall.go:168
syscall.SyscallN
	runtime/syscall_windows.go:557
syscall.Syscall
	runtime/syscall_windows.go:495
golang.zx2c4.com/wintun.CreateAdapter
	golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/wintun.go:92
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID
	golang.zx2c4.com/wireguard@v0.0.0-20220920152132-bb719d3a6e2c/tun/tun_windows.go:69
golang.zx2c4.com/wireguard/tun.CreateTUN
	golang.zx2c4.com/wireguard@v0.0.0-20220920152132-bb719d3a6e2c/tun/tun_windows.go:63
github.com/telepresenceio/telepresence/v2/pkg/vif.openTun
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/vif/device_windows.go:40
github.com/telepresenceio/telepresence/v2/pkg/vif.OpenTun
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/vif/device.go:52
github.com/telepresenceio/telepresence/v2/pkg/client/rootd.NewSession
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/client/rootd/session.go:255
github.com/telepresenceio/telepresence/v2/pkg/client/rootd.(*Service).startSession
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/client/rootd/service.go:300
github.com/telepresenceio/telepresence/v2/pkg/client/rootd.(*Service).manageSessions
	github.com/telepresenceio/telepresence/v2@v2.9.5/pkg/client/rootd/service.go:269
github.com/datawire/dlib/dgroup.(*Group).goWorkerCtx.func1
	github.com/datawire/dlib@v1.3.1-0.20220715022530-b09ab2e017e1/dgroup/group.go:385
github.com/datawire/dlib/derrgroup.(*Group).Go.func2
	github.com/datawire/dlib@v1.3.1-0.20220715022530-b09ab2e017e1/derrgroup/errgroup.go:132
runtime.goexit
	runtime/asm_amd64.s:1594

How can I solve this problem？

**Comment by thallgren** [comment]
You probably have an incorrect version of wintun.dll installed. Installing the version that is bundled with the telepresence installer will most likely solve the problem.

**Comment by thallgren** [comment]
Closing this since no more info was provided.
