### ISSUE TITLE
Manager namespace hint (UI/UX)

### ISSUE THREAD

**Issue by guyguy333** [telepresenceio/telepresence#2968]
**Please describe your use case / problem.**

I deployed telepresence helm chart v2.9.5 scoped to a namespace. CLI uses same version. traffic-manager pod is running and chart is listed in helm list. However, everytime I try to connect, I'm getting this error:
telepresence connect --mapped-namespaces mynamespace
telepresence connect: error: connector.Connect: traffic manager not found, if it is not installed, please run 'telepresence helm install'
In the end the issue was a missing manager namespace set to mynamespace. 

**Describe the solution you'd like**

It could be useful to add a hint in output message to suggest checking manager namespace. Another solution could be to use values from mapped-namespaces.

**Describe alternatives you've considered**

Manually debug

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions) : 2.9.5
  - Kubernetes Environment and Version : 1.25

**Additional context**
Add any other context about the feature request here.

**Comment by amine7536** [comment]
Hi @guyguy333, I'm having the same issue trying to run the `traffic-manager` scoped to a namespace.

> In the end the issue was a missing manager namespace set to mynamespace.

Where do you set this parameter? Can you share how to solve it 🙏 .

**Comment by guyguy333** [comment]
> Hi @guyguy333, I'm having the same issue trying to run the `traffic-manager` scoped to a namespace.
> 
> > In the end the issue was a missing manager namespace set to mynamespace.
> 
> Where do you set this parameter? Can you share how to solve it 🙏 .

Yes sure, here is the documentation : https://github.com/telepresenceio/telepresence.io/blob/master/docs/v2.4/reference/config.md#manager

**Comment by amine7536** [comment]
Awesome, thanks!

So it's stored in the `$KUBECONFIG` file. Not super convenient if you have multiple `traffic-manager` in the same cluster, I was looking for a flag or something else.

**Comment by guyguy333** [comment]
> Awesome, thanks!
> 
> So it's stored in the `$KUBECONFIG` file. Not super convenient if you have multiple `traffic-manager` in the same cluster, I was looking for a flag or something else.

I agree. I opened this ticket to improve UI/UX of this config, I hope this case will be considered.

**Comment by josecv** [comment]
Closed by #2990
