### ISSUE TITLE
python3: can't open file 'podinfo.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by PaulisMatrix** [telepresenceio/telepresence#2970]
### What were you trying to do?

ssh into remote k8s pod via local using telepresence.

### What did you expect to happen?

connection being established successfully and able to exec into the pod. 

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

Full log: https://gist.github.com/PaulisMatrix/bf08fa1acda79997597f5969901a09f2 

### Automatically included information

Command line: `['./usr/local/bin/telepresence', '--mount=false', '--also-proxy=10.0.0.0/8', '--run', 'zsh']`
Version: `0.73-1694-g146d6ec`
Python version: `3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.24.0 // Kustomize Version: v4.5.4 // Server Version: v1.23.13-gke.900`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin 192.168.1.2 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 x86_64`

```
Traceback (most recent call last):
  File "/Users/rushiyadwade/tele/telepresence/./usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/Users/rushiyadwade/tele/telepresence/./usr/local/bin/telepresence/telepresence/main.py", line 71, in main
    env, pod_info = get_remote_env(runner, ssh, remote_info)
  File "/Users/rushiyadwade/tele/telepresence/./usr/local/bin/telepresence/telepresence/remote_env.py", line 32, in get_remote_env
    json_data = runner.get_output(
  File "/Users/rushiyadwade/tele/telepresence/./usr/local/bin/telepresence/telepresence/runner/runner.py", line 479, in get_output
    output = self._run_command_sync(
  File "/Users/rushiyadwade/tele/telepresence/./usr/local/bin/telepresence/telepresence/runner/runner.py", line 437, in _run_command_sync
    raise CalledProcessError(
subprocess.CalledProcessError: Command '['kubectl', '--context', 'dev', '--namespace', 'default', 'exec', 'telepresence-1673358306-759237-26882', '--container', 'telepresence', '--', 'python3', 'podinfo.py']' returned non-zero exit status 2.

```

Logs:

```
e. You can use the --expose option to specify which ports you want to forward.
  24.1 >>> | 
  24.1 TEL | Launching Web server for proxy poll
  24.1 TEL | [16] Launching SSH port forward (socks and proxy poll): ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 55110 telepresence@127.0.0.1 -L127.0.0.1:55120:127.0.0.1:9050 -R9055:127.0.0.1:55121
  24.1 TEL | END SPAN connect.py:37(connect)    0.7s
  24.2 TEL | BEGIN SPAN remote_env.py:29(get_remote_env)
  24.2 TEL | [17] Capturing: kubectl --context dev --namespace default exec telepresence-1673358306-759237-26882 --container telepresence -- python3 podinfo.py
  24.2  13 | Handling connection for 55110
  24.6  17 | python3: can't open file 'podinfo.py': [Errno 2] No such file or directory
  24.6  17 | command terminated with exit code 2
  24.6 TEL | [17] exit 2 in 0.42 secs.
  24.6 TEL | END SPAN remote_env.py:29(get_remote_env)    0.4s

```
Just fyi, yes I'm already using telepresence v2 installed via this : https://www.telepresence.io/docs/latest/quick-start/

**Comment by cindymullins-dw** [comment]
Hi @PaulisMatrix , I don't think we've seen this exact error although [zsh is supported](https://github.com/telepresenceio/telepresence/issues/191) ([w/auto-completion scripts in 2.7.2](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.7.2)).  Does [this help](https://github.com/readthedocs/readthedocs.org/issues/3322)?  It seems like it would be something with having that file available in your virtual environment, if relevant?

**Comment by PaulisMatrix** [comment]
Hey @cindymullins-dw, thanks I did check your comment but what helped eventually was the telepresence legacy version. Installed that one and it worked. 

`brew install --cask osxfuse`
`brew install datawire/blackbird/telepresence-legacy`

I guess we can mark this issue as closed.
