### ISSUE TITLE
traffic agent should be able to preserve http header casing

### ISSUE THREAD

**Issue by tedchang77** [telepresenceio/telepresence#2972]
**Please describe your use case / problem.**
The traffic agent sidecar envoy proxy is converting http headers to lowercase which is breaking our application and downstream services that are case-sensitive.

**Describe the solution you'd like**
Introduce a traffic-manager flag that will preserve the HTTP header casing in the traffic-agent envoy sidecar.  envoy has exposed this configuration in their configs: https://github.com/envoyproxy/envoy/issues/14363

**Describe alternatives you've considered**
we have upstream services that we are propagating HTTP headers to. these services aren't owned by us, so we can't change them. 
we looked at modifying/replacing the envoy config _bootstrap-ads.pb_ in traffic agent sidecar using a configmap volumemount or an init-container, but it looks like this config is generated dynamically when the agent is started.

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)
Enhanced Client: v2.9.5
Root Daemon    : v2.9.5
User Daemon    : v2.9.5
Traffic Manager: v2.9.5
  - Kubernetes Environment and Version
 GKE Autopilot:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.900", GitCommit:"e35c4457f66187eff006dda6d2c0fe12144ef2ec", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:34Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
**Additional context**
Add any other context about the feature request here.
Without this feature, we cannot use telepresence.

**Comment by thallgren** [comment]
Closing this and deferring to Ambassador support. The envoy based traffic-agent is not open source.
