### ISSUE TITLE
nightly builds are forbidden

### ISSUE THREAD

**Issue by nicks** [telepresenceio/telepresence#2973]
**Describe the bug**
I went to this page to install telepresence: https://www.getambassador.io/docs/telepresence/latest/install?os=gnu-linux

That page gives me a link to the nightly build: https://app.getambassador.io/download/tel2/linux/amd64/nightly/telepresence

AFAICT, this link is broken? Not sure if this is a release bug or a docs bug.

**To Reproduce**

```
curl -sSL https://app.getambassador.io/download/tel2/linux/amd64/nightly/telepresence
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F6GEVZSAPM8V2MVW</RequestId><HostId>m7ju+LtcoJOZwV5IlOrffY1myPR9DlnVI6nAhvVO3DxAHvLZ6bgV6jz7Hmk3rEDisickEVPV2nQ=</HostId></Error>
```

**Expected behavior**
A working binary!

**Comment by thallgren** [comment]
The nightly build was broken, but restored a long time ago (for the enterprise version of Telepresence) and the above link is now functional.
