### ISSUE TITLE
telepresence intercept: rpc error: desc = unknown service telepresence.pro.manager.ProManager

### ISSUE THREAD

**Issue by lukaso** [telepresenceio/telepresence#2980]
**Describe the bug**
Telepresence does not connect when calling for intercept.

```bash
$ telepresence intercept account-ts --port 3000:80 --env-file .env
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /Users/user/Library/Logs/telepresence '/Users/user/Library/Application Support/telepresence'
Password:
Launching Telepresence User Daemon
Connected to context gke_cluster (https://redacted)
telepresence intercept: error: Unable to report intercept creation: rpc error: code = Unimplemented desc = unknown service telepresence.pro.manager.ProManager
```

**To Reproduce**

0. Install telepresence via `brew` and from the web site. Both exhibit the same behavior.
1. When I run 'telepresence interc
ept account-ts --port 3000:80 --env-file .env'
2. I see 'telepresence intercept: error: Unable to report intercept creation: rpc error: code = Unimplemented desc = unknown service telepresence.pro.manager.ProManager'

**Expected behavior**

Telepresence connects to my kubernetes cluster and forwards traffic.

**Fix**

Downgrade to 2.9.1 which works.

**Versions (please complete the following information):**
 - Output of `telepresence version`
Client         : v2.10.3
Root Daemon    : v2.10.3
User Daemon    : v2.10.3
Traffic Manager: v2.9.3
 - Operating system of workstation running `telepresence` commands
 MacOS Ventura 13.1 arm64
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
GKE  1.23.14-gke.401

```bash
$ gcloud version
Google Cloud SDK 413.0.0
bq 2.0.84
core 2023.01.06
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.4.0
gsutil 5.17
```

**VPN-related bugs:**

N/A

**Additional context**
This started occurring after reinstalling my mac from scratch. So there are no legacy versions of anything on the machine. I upgraded from v2.10.2 to v2.10.3 but this didn't change anything.

```bash
$ telepresence status
User Daemon: Running
  Version           : v2.10.3
  Executable        : /usr/local/bin/telepresence
  Install ID        : redacted
  Status            : Connected
  Kubernetes server : https://redacted
  Kubernetes context: gke_redacted
  Intercepts        : 0 total
Root Daemon: Running
  Version    : v2.10.3
  DNS        :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - redacted but same as Kubernetes Server/32
Ambassador Cloud:
  Status      : Logged out
Traffic Manager: Connected
  Version : v2.9.3
```

**Comment by Farrukhjon** [comment]
I also faced with this issue in my MAC and also downgraded to a lower telepresence version (to 2.9.5) to fix it.

```
~ sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
```

```
~ telepresence version
An update of telepresence from version 2.9.5 to 2.10.3 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Enhanced Client: v2.9.5
Root Daemon    : v2.9.5
User Daemon    : v2.9.5
Traffic Manager: v2.7.6
```

**Comment by abhilashkar** [comment]
@Farrukhjon  Can you let me know how did u install 2.9.5 version? I don't see a straightforward way to do it. Any help appreciated

**Comment by lukaso** [comment]
It's on the same page as the regular installation instructions. You have to put the version numbers in the right place in the URL.

**Comment by abhilashkar** [comment]
@lukaso  sudo curl -fL https://app.getambassador.io/download/tel2/darwin/arm64/v2.9.5/telepresence -o /usr/local/bin/telepresence didnt work for me. I am on macOS

**Comment by abhilashkar** [comment]
@lukaso Never mind. I guess I should remove v from it :-). Got it. Thanks

**Comment by lukaso** [comment]
So for all who just want to cut and paste:

```bash
sudo curl -fL https://app.getambassador.io/download/tel2/darwin/arm64/2.9.5/telepresence -o /usr/local/bin/telepresence
sudo chmod a+x /usr/local/bin/telepresence
```

**Comment by thallgren** [comment]
2.10.4 has been released. It contains the fix.
