### ISSUE TITLE
running intercept inside a container messes up DNS

### ISSUE THREAD

**Issue by grzn** [telepresenceio/telepresence#2981]
**Describe the bug**
We have the following setup:
* ubuntu 20.04 x64 vm
* minikube v1.27.1, kubernetes v1.21.14
* telepresence2 running telepresence2 inside a docker container with ```--network host --cap-add=NET_ADMIN --cap-add=NET_BIND_SERVICE --device=/dev/net/tun:/dev/net/tun```

When we run intercepts inside the container, DNS resolutions inside the container and on the host is messed up, all name resolutions to 127.0.0.53 (systemd-resolved stub resolver) fail.

**To Reproduce**
1. run `telepresence intercept ...` inside the container
2. nslookup cluster services or public dns records, all fails

**Expected behavior**

**Versions (please complete the following information):**
happens w/ telepresence 2.9.3 and 2.10,1

**Comment by grzn** [comment]
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10450562/telepresence_logs.zip)

**Comment by cindymullins-dw** [comment]
@grzn , I don't know if it makes a difference but I notice our example config has --network=host, if you're referencing [this page](https://www.getambassador.io/docs/telepresence/latest/reference/inside-container).  Wonder if it could be related to the local minikube env.

**Comment by grzn** [comment]
Yes we're using network host as well.

**Comment by cindymullins-dw** [comment]
[Docker Mode](https://www.getambassador.io/docs/telepresence/latest/docker/cli) is now available and should work better than running inside a container.  Please reopen if issues persist.
