### ISSUE TITLE
Crash trying to --swap-deployment (openshift)

### ISSUE THREAD

**Issue by ghaskins** [telepresenceio/telepresence#299]
### What were you trying to do?

Wanted to swap an existing deployment with telepresence so that I would have access to its Secrets/ConfigMaps and could debug it.

### What did you expect to happen?

I expected a telepresence shell in the context of the swapped application

### What happened instead?

telepresence crashes immediately.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'xxx']`
Version: `0.67`
Python version: `3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]`
kubectl version: `Client Version: v1.7.6`
oc version: `oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7`
OS: `Darwin MacBook-Pro.haskins.net 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2350, in go
    runner, args
  File "/usr/local/bin/telepresence", line 1486, in start_proxy
    swap_deployment_openshift(runner, args)
  File "/usr/local/bin/telepresence", line 1402, in swap_deployment_openshift
    )[0].split("/", 1)[1]
IndexError: list index out of range

```

Logs:

```
   0.0 TL | Telepresence launched at Thu Sep 21 19:18:21 2017
   0.0 TL |   ['/usr/local/bin/telepresence', '--swap-deployment', 'xxx']
   0.0 TL | Scout info: {'latest_version': '0.63', 'application': 'telepresence', 'notices': []}
   0.0 TL | Context: myproject/127-0-0-1:8443/developer, namespace: myproject, kubectl_command: oc
   0.0 TL | [1] Capturing: (['oc', '--context', 'myproject/127-0-0-1:8443/developer', 'status'],)...
   0.3 TL | [1] captured.
   0.3 TL | [2] Capturing: (['ssh', '-V'],)...
   0.3 TL | [2] captured.
   0.3 TL | [3] Capturing: (['which', 'torsocks'],)...
   0.3 TL | [3] captured.
   0.3 TL | [4] Capturing: (['which', 'sshfs'],)...
   0.3 TL | [4] captured.
   0.3 TL | [5] Capturing: (['oc', '--context', 'myproject/127-0-0-1:8443/developer', '--namespace', 'myproject', 'get', 'rc', '-o', 'name', '--selector', 'openshift.io/deployment-config.name=xxx'],)...
   0.6 TL | [5] captured.

```

**Comment by ark3** [comment]
Thanks for the bug report. This is a case of Telepresence crashing instead of reporting an error. Sorry about that!

In this case, Telepresence is running 

    oc --context myproject/127-0-0-1:8443/developer --namespace myproject get rc -o name --selector openshift.io/deployment-config.name=xxx

to try to find the replication controller associated with the deployment you're trying to swap. It's parsing the output of that command and blowing up. Could you please paste the output of that command here so I can see what's going wrong? Thanks!

**Comment by zeonin** [comment]
@ark3

I've hit this issue running telepresence<=0.9.0 (0.9.1 is where I start hitting #781 / #762). The error occurs when trying to swap k8s Deployments. Telepresence seems to assume that only DeploymentConfigs are used on OpenShift.
