### ISSUE TITLE
Error "uninstall --everything" command

### ISSUE THREAD

**Issue by asoleimanibo** [telepresenceio/telepresence#2993]
Hello
I swap deployment which is located in the Istio service mesh with this  command:
`telepresence --swap-deployment test --expose 8087:8087 --namespace test`
then I want to leave the swap and remove the agent sidecar with this command:
`telepresence uninstall --everything`
but I got an error:
```
telepresence uninstall --everything
Connected to context kubernetes-admin@kubernetes (https://apiserver:6443)
telepresence: error: traffic Manager in namespace ambassador is not owned by cli, will not uninstall
```
What should I do?

**Comment by cakuros** [comment]
Can you uninstall via `helm`?

i.e. `helm uninstall traffic-manager -n ambassador`

**Comment by cindymullins-dw** [comment]
Right, if you've installed the Traffic Manager with Helm, then you also have to use Helm to uninstall it, to prevent a user from deleting it by mistake/without authorization.  To remove one agent you can run ‘telepresence uninstall -d {agent}’. To uninstall all agents you can run ‘telepresence uninstall -a’.

**Comment by thallgren** [comment]
Closing due to lack of response.
