### ISSUE TITLE
use telepresence with multiple engineers, w/out using hosted cloud

### ISSUE THREAD

**Issue by drewfish** [telepresenceio/telepresence#2996]
Hi!

**Please describe your use case / problem.**
I'm trying to use telepresence, along with my work peers, to tunnel multiple local services into our shared environment. It's an AWS EKS cluster, not sure if that's relevant.

I initially ran into this error:
```
$ telepresence intercept drewfish-service1 --namespace drewfish --port 3000:80
There are 2 clients connected to this traffic manager.

We recommend you switch Traffic Manager to team mode.
Team mode changes the default intercept type from global to personal intercepts, allowing more than one developer to intercept the same service and enabling the easier sharing of work-in-progress via
secure preview URLs.
Enable team mode with the command: telepresence helm upgrade --team-mode
```

I then did the `telepresence helm upgrade --team-mode`. After that, all `telepresence intercept` command opens a browser tab asking to login to some cloud system. For security & compliance reasons, we absolutely cannot use that hosted system.

**Describe the solution you'd like**
A way for multiple developers (dozens) to be able to setup tunnels into a kubernetes cluster, without requiring cloud login.

**Describe alternatives you've considered**
Would it work to fork the telepresence repo and comment-out the cloud stuff ? How painful would that be (quantity of changes, build toolchain to make executables/images/etc) ?

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)
  - Kubernetes Environment and Version

```
$ telepresence version
Client         : v2.10.4
Root Daemon    : v2.10.4
User Daemon    : v2.10.4
Traffic Manager: v2.10.4
```

```
$ kubectl --context work-staging cluster-info
Kubernetes control plane is running at https://--ELIDED--.eks.amazonaws.com
CoreDNS is running at https://--ELIDED--.eks.amazonaws.com/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

From looking at our AWS EKS cluster:
* Kubernetes version `1.23`
* Platform version `eks.5`
(... not sure what else might be useful)

**Additional context**
--none--

**Comment by luciaarguello** [comment]
Hi Drew,

Lucia from Telepresence! Feel free to reach out via our Open Source Slack or reach out to our team so we can help solve your issues.

**Comment by cindymullins-dw** [comment]
Hi @drewfish , actually you can use an '[air gapped license](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config#air-gapped-cluster)' for this use case.  You'd just need to connect once to get your license and you can use that license as a K8s secret or pass it to the Helm chart where it creates a secret for you.  You would include the ‘skip login’ key so you won’t have to log in going fwd.  If you'd like to join a Telepresence help session please let me know and you can join our Slack at a8r.io/slack.

**Comment by thallgren** [comment]
This seems to be resolved by using the suggested approach. Feel free to open if that didn't work.
