### ISSUE TITLE
Encountering "operation not permitted" when executing commands from a Development Container

### ISSUE THREAD

**Issue by finite8** [telepresenceio/telepresence#3000]
**Describe the bug**
All my attempts to execute any meaningful commands fails with `error: connector.Connect: failed to connect to root daemon: rpc error: code = Unknown desc = operation not permitted`. This includes "telepresence connect" as well as "telepresence loglevel debug".

I was able to execute "telepresence helm install" fine. 

**Important note of my setup**: I am working from a "Development Container", essentially meaning that the entire linux environment I am running from is a docker container. The "Kind" cluster I am trying to connect to is on the same host, but it is NOT a docker-in-docker scenario. They are both essentially running as containers on the same host (peers) and are networked together, with the Development Containers docker commands using the hosts Docker API. All "kubectl", "helm" and other kubernetes related commands work fine. Because Kind runs as a container itself, it encapsulates the entire kube environment so if i run "docker ps", I will only get two results: my Development Container, and the Kind cluster.

**To Reproduce**
1. execute "telepresence helm install"
2. execute "telepresence connect"

**Expected behavior**
Not sure, but I assume that Telepresence agent would connect. This is the first time I have tried it.

**Versions (please complete the following information):**
Telepresence Versions:
- Client         : v2.10.4
- Root Daemon    : v2.10.4
- User Daemon    : v2.10.4
- Traffic Manager: not connected
OS Version
 - Debian GNU/Linux 11 (bullseye)
KIND version
 - kind v0.16.0 go1.17.13 linux/amd64

**Additional context**
Please note the environment details as mentioned above.
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10545018/telepresence_logs.zip)

**Comment by thallgren** [comment]
I don't see any errors in the connect.log suggesting that the connect failed. On the contrary. I see `Connected to traffic-manager v2.10.4` which indicates success. The logs are not produced with loglevel debug.

**Comment by finite8** [comment]
> I don't see any errors in the connect.log suggesting that the connect failed. On the contrary. I see `Connected to traffic-manager v2.10.4` which indicates success. The logs are not produced with loglevel debug.

Yes, the logs are very deceptive. Attached is the console output from my attempts to execute that command.
![Screenshot 2023-02-01 093909](https://user-images.githubusercontent.com/7815382/215900243-57147607-8d87-4d59-bcf7-b59fb0ed5664.png)

**Comment by finite8** [comment]
> I don't see any errors in the connect.log suggesting that the connect failed. On the contrary. I see `Connected to traffic-manager v2.10.4` which indicates success. The logs are not produced with loglevel debug.

Yes, unfortunately the logs seem to be a bit deceptive here. This is the output from the console.
![Screenshot 2023-02-01 093909](https://user-images.githubusercontent.com/7815382/215900545-6e81023b-8b4d-4661-89a9-a94014534701.png)
When i execute it, i see the logs populate in response, but the don't contain the details of this error I am encountering.

I get the same error when I execute `telepresence connect` and `telepresence list`. Is there an alternate way to enable debug logging? Some kind of behind-the-scenes config file?

**Comment by finite8** [comment]
I have found this issue. Working through it to see if it helps.
https://github.com/telepresenceio/telepresence/issues/2456

**Comment by finite8** [comment]
After some battling, I have managed to get it working. Not sure if all of it was needed, but these changes seemed to have made an improvement (I am not a linux expert so apologies if some of this was obvious):

1. Added the following into the "runArgs" in "devcontainer.json"
```
"--cap-add=NET_ADMIN",
"--device","/dev/net/tun",
"--privileged"
```

2. Ensured SUDO support was enabled (via Dockerfile). If not using the current standard templates, this should hopefully still work for others.
```
    # [Optional] Add sudo support
RUN apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
```

3. Ensure that the KubeConfig kind creates is using the internal name and not assuming local host (127.0.0.1).
`kind export kubeconfig --internal`

These are the makefile targets I set up to make the setup easy. I already had some of the dependencies figured out with my first attempts, but I added the sudo which I should have tried before raising in the first place (sorry).

**MAKEFILE.MK (relevant bits)**
```
TELEPRESENCE_PATH=/usr/local/bin/telepresence

$(TELEPRESENCE_PATH):
	apt install -y iproute2
	sudo curl -fL https://app.getambassador.io/download/tel2/linux/amd64/latest/telepresence -o telepresence
	sudo install -o root -g root -m 0755 telepresence $(TELEPRESENCE_PATH)

telepresence-install: $(TELEPRESENCE_PATH)
	sudo $(TELEPRESENCE_PATH) helm --kubeconfig=$(KUBECONFIG) install || true

telepresence-connect: telepresence-install
	sudo $(TELEPRESENCE_PATH) --kubeconfig=$(KUBECONFIG) connect
```

Note: the --kubeconfig is needed as my environment is set up so that the kubeconfig is in a temp dir specific for the terminal session and not globally so as to make sure that other terminal sessions don't mess with eachother. Without that, you will get the missing kube context error when executed as SUDO.

now the `connect` and `list` commands work and are giving me things that I can work with.
