### ISSUE TITLE
bind: function not implemented

### ISSUE THREAD

**Issue by cerebrate** [telepresenceio/telepresence#3004]
**Describe the bug**

Attempting to do anything requiring networking (thus far) with the Telepresence CLI produces variations on the above error. For example, after attempting to use `telepresence connect`, which fails with the following error attempting to start the root daemon:

`telepresence connect: error: daemon service did not start: timeout while waiting for daemon to start`

daemon.log contains the following error:

```
2023-02-01 13:49:49.8009 info    ---
2023-02-01 13:49:49.8010 info    Telepresence daemon v2.10.4 (api v3) starting...
2023-02-01 13:49:49.8010 info    PID is 1274448
2023-02-01 13:49:49.8010 info
telepresence: error: listen unix /var/run/telepresence-daemon.socket: bind: function not implemented
```

An identical error occurs with any command attempting to start the Telepresence daemon, even `telepresence loglevel debug`. Meanwhile, `telepresence login` fails with the similar error:

```
Login failure.
telepresence login: error: listen tcp :0: bind: function not implemented
```

**To Reproduce**

Unknown. This behavior began immediately on installing Telepresence.

**Expected behavior**

Normal operation.

**Versions (please complete the following information):**
 - Output of `telepresence version`

Client     : v2.10.4
Root Daemon: not running
User Daemon: not running

 - Operating system of workstation running `telepresence` commands

Linux; specifically, Debian sid running under WSL

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

k3s v1.25.5+k3s2

**Comment by cindymullins-dw** [comment]
Hi @cerebrate , I'm not finding references to this error previously and am wondering if it could be unique to your OS.  Wonder if you have another machine perhaps you could test on to see if your environment results in the same error?

**Comment by cerebrate** [comment]
Yes, it appears that there is some problem that causes certain local-socket-related syscalls to fail unexpectedly on all our machines running one particular kernel build. (This just happened to be the first and most prominent issue resulting from that, alas.) Thanks for your help.
