### ISSUE TITLE
Installing telepresence version 1

### ISSUE THREAD

**Issue by bigshr** [telepresenceio/telepresence#3008]
How do I install telepresence version 1 in ubuntu 22.04?

**Comment by cindymullins-dw** [comment]
HI @bigshr, Telepresence version 1 is no longer supported but you can install the new version [here](https://www.getambassador.io/docs/telepresence/latest/quick-start).  Feel free also to join our Slack at a8r.io/slack and we have a help session weekly on Telepresence if you'd like assistance.
