### ISSUE TITLE
Traffic manager ambassador agent panic due to k8s API v1.Ingress

### ISSUE THREAD

**Issue by HoangViet144** [telepresenceio/telepresence#3009]
**Describe the bug**
I have deployed Telepresence v2.10.4 on my kubernetes cluster.
However the pod `traffic-manager-ambassador-agent-...` in namespace `ambassador` have restarted over and over due to panic

**To Reproduce**
1. I deployed Telepresence to kubernetes cluster 
2. I went to `ambassador` namespace
3. I looked at the log of pod `traffic-manager-ambassador-agent-...`

**Expected behavior**
Pod should not be panic and restart.

**Versions**
 - Client             : v2.10.4
Root Daemon        : v2.10.4
User Daemon        : v2.10.4
OSS Traffic Manager: v2.10.4
 - Operating system of workstation running `telepresence` commands: MacOS 13.0.1
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]: Google Kubernetes Engine 1.22

**Additional context**
The log of pod:
time="2023-02-06T06:58:24Z" level=info msg="ambassador-agent v1.0.8"
time="2023-02-06T06:58:24Z" level=info msg="Using cluster domain \"cluster.local\""
time="2023-02-06T06:58:25Z" level=info msg="metrics service listening on :8080"
time="2023-02-06T06:58:25Z" level=info msg="Will lease with id a833a80b-ab37-42b0-b700-0ff1790f1fec" THREAD=/lease-lock-watch
I0206 06:58:25.031876       1 leaderelection.go:248] attempting to acquire leader lease ambassador/ambassador-agent-lease-lock...
time="2023-02-06T06:58:25Z" level=info msg="a different agent acquired the lease-lock: 853961fc-0664-4eac-830b-83deb521b5c5" THREAD=/lease-lock-watch
I0206 06:59:34.579738       1 leaderelection.go:258] successfully acquired lease ambassador/ambassador-agent-lease-lock
time="2023-02-06T06:59:34Z" level=info msg="Lease-lock acquired, watching cluster" THREAD=/lease-lock-watch
time="2023-02-06T06:59:34Z" level=info msg="Agent is running..." THREAD=/lease-lock-watch
time="2023-02-06T06:59:34Z" level=info msg="Setting cloud connect token from configmap: traffic-manager-agent-cloud-token" THREAD=/lease-lock-watch
time="2023-02-06T06:59:36Z" level=info msg="ambassador-admin not detected, creating own snapshots." THREAD=/lease-lock-watch
time="2023-02-06T06:59:36Z" level=info msg="Beginning to watch and report resources to ambassador cloud" THREAD=/lease-lock-watch
time="2023-02-06T06:59:36Z" level=info msg="Setting cloud connect token from configmap: traffic-manager-agent-cloud-token" THREAD=/lease-lock-watch
time="2023-02-06T06:59:36Z" level=info msg="Fetching cluster ID from namespace default" THREAD=/lease-lock-watch
time="2023-02-06T06:59:36Z" level=info msg="Using root ID f6a92a6d-415a-443b-8f42-d559228b99cf" THREAD=/lease-lock-watch
time="2023-02-06T06:59:36Z" level=info msg="Using computed cluster ID fb71288f-232b-58c2-9e91-4a82d5078cdd" THREAD=/lease-lock-watch
panic: interface conversion: interface {} is *v1.Ingress, not *networking.Ingress

goroutine 13 [running]:
github.com/datawire/k8sapi/pkg/k8sapi.(*Watcher[...]).List(0xc0004c8000, {0x23cab20, 0xc000060c00?})
	github.com/datawire/k8sapi@v0.1.2/pkg/k8sapi/watcher.go:198 +0x225
github.com/datawire/k8sapi/pkg/k8sapi.WatcherGroup[...].List(0x2500, {0x23cab20?, 0xc000060c00})
	github.com/datawire/k8sapi@v0.1.2/pkg/k8sapi/watcher_group.go:51 +0x135
github.com/datawire/ambassador-agent/pkg/agent/watchers.(*networkWatcher).List(0xc000c7f500, {0x23cab20?, 0xc000060c00?})
	github.com/datawire/ambassador-agent/pkg/agent/watchers/ingress_watcher.go:115 +0x59
github.com/datawire/ambassador-agent/pkg/agent/watchers.(*FallbackWatchers).LoadSnapshot(0xc000cc0a20, {0x23cab20, 0xc000060c00}, 0xc000a58400)
	github.com/datawire/ambassador-agent/pkg/agent/watchers/fallback_watchers.go:72 +0x216
github.com/datawire/ambassador-agent/pkg/agent.(*Agent).ProcessSnapshot(0xc0003d4580, {0x23cab20, 0xc000060c00}, 0xc000a58400)
	github.com/datawire/ambassador-agent/pkg/agent/agent.go:759 +0x1a7
github.com/datawire/ambassador-agent/pkg/agent.(*Agent).watch(0xc0003d4580, {0x23cab20, 0xc000060c00}, 0xc000db4000, 0xc003d200c0)
	github.com/datawire/ambassador-agent/pkg/agent/agent.go:542 +0x4f1
github.com/datawire/ambassador-agent/pkg/agent.(*Agent).Watch(0xc0003d4580, {0x23cab20?, 0xc000060c00})
	github.com/datawire/ambassador-agent/pkg/agent/agent.go:330 +0x1b3
main.main.func2.2({0x23cab20, 0xc000133b40})
	./main.go:144 +0xc5
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	k8s.io/client-go@v0.26.0/tools/leaderelection/leaderelection.go:211 +0x11b

**Comment by knlambert** [comment]
Hello, do you still have the issue ? It should have been fixed with versions > 2.12.

**Comment by thallgren** [comment]
Closing due to lack of response.
