### ISSUE TITLE
ambassador-telepresence-agent Dockerfile location?

### ISSUE THREAD

**Issue by Jeansen** [telepresenceio/telepresence#3011]
I cannot find the Dockerfile for ambassador-telepresence-agent. I wanted to add a PR regarding the iptables Problem with legacy and nft, but without a SRC I cannot do such a PR. Any search on my side without success. Where can I find it?

**Comment by cindymullins-dw** [comment]
Hi @Jeansen , it seems this is in a private repo and so not accessible for community PRs.  Are you in our #telepresence-dev channel in [our Slack](a8r.io/slack)?  That would be a good place to discuss the issue.

**Comment by cindymullins-dw** [comment]
Please let us know if you can join our Slack - thanks!
