### ISSUE TITLE
Unable to intercept Golang service running in AWS based K8s cluster from local development environment in MAC

### ISSUE THREAD

**Issue by nikileshsa** [telepresenceio/telepresence#3035]
**Describe the bug**

1)We are trying to use telepresence V2 in our development workflows. 
2) A typical developer uses Mac as development host to makes changes to his golang based service code and starts the service locally and the service is expose an HTTP endpoint at port 8080. 
3) The developer has access to AWS based k8s cluster where the service is running as a deployment in a certain namespace. The k8s cluster has Telepresence agents running in the ambassador namespace
4) When we run the intercept command locally, the intercept is getting created for the service. But when call the local service REST endpoints, the requests are not forwarded to the remote k8s cluster. 

**To Reproduce**
1. telepresence login
2. telepresence intercept <deployment name> --http-header=all --namespace <namespace> -e <env file which has all the pod env's >
3. start the local golang service ---> go run main.go which will expose a REST endpoint in localhost:8080
4. Call the Rest endpoint

Telepresence Technical assistance team was involved in initial troubleshooting during the office hours support call.

**Expected behavior**

We expect the requests to be forwarded to the remote endpoint.

**Versions (please complete the following information):**

➜  issue telepresence version
An update of telepresence from version 2.10.5 to 2.10.6 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client         : v2.10.5
Root Daemon    : v2.10.5
User Daemon    : v2.10.5
Traffic Manager: v2.10.5

Mac OS version:
13.0.1 (22A400)

 - Kubernetes environment and Version [e.g. k8s deployed on AWS]

**VPN-related bugs:**
not enough information. We are using Cisco VPN

**Additional context**
Telepresence support team were on a 1 hour call to 
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10761549/telepresence_logs.zip)
debug this issue. They suggested to raise this issue for further assistance.

**Comment by thallgren** [comment]
From the looks of it, the telepresence client that runs on the workstation, is never able to connect to the traffic-manager. My guess would be that there's some kind of permission problem.
Can you list the pods in the "ambassador" namespace with kubectl, e.g. `kubectl -n ambassador get pods`?
If so, can you do a port-forward to the traffic-manager pod? `kubectl -n ambassador port-forward deployment/traffic-manager 8081:8081`?

**Comment by thallgren** [comment]
Closing this due to lack of response from reporter.
