### ISSUE TITLE
Helm chart ambassador agent : duplicated labels break FluxCD deployment

### ISSUE THREAD

**Issue by guyguy333** [telepresenceio/telepresence#3046]
**Describe the bug**

Hello. I found ambassador-agent chart is having some issues.

It generates multiple times label [app.kubernetes.io/name](http://app.kubernetes.io/name) but also [app.kubernetes.io/instance](http://app.kubernetes.io/instance) with same value in a same labels field. It breaks deployment with fluxcd. 

Related issue on FluxCD: https://github.com/fluxcd/helm-controller/issues/283

<img width="568" alt="Screenshot 2023-02-20 at 17 21 26" src="https://user-images.githubusercontent.com/4040959/221409047-76c80653-38b3-476d-9745-1d4f270b79a4.png">

**To Reproduce**
1. Download helm chart and run helm template

**Expected behavior**

No duplicated labels for [app.kubernetes.io/name](http://app.kubernetes.io/name) and [app.kubernetes.io/instance](http://app.kubernetes.io/instance)

**Comment by thallgren** [comment]
Closed by datawire/ambassador-agent#97
