### ISSUE TITLE
Question about Intercepting service with multiple ports

### ISSUE THREAD

**Issue by s1apped** [telepresenceio/telepresence#3058]
Hi. I'm wondering if it's possible to intercept service that listens on multiple ports? In my case one is  for REST communication and second for gRPC and I would like to intercept whole traffic. I read it should be possible from version 2.6.0 up using workloads but I'm still getting  `AGENT_ERROR: Conflicts`. Is this feature only available when using Ambassador Cloud?

**Comment by thallgren** [comment]
It is possible, but you'll need to use multiple intercepts where the port and/or service is specified.

**Comment by cindymullins-dw** [comment]
Telepresence will only intercept on one port by default, the one that it detects on your Service.  If you have multiple ports, like REST or gRPC, you'll likely need two intercept commands to the same Service, where you're passing in the different port numbers.
