### ISSUE TITLE
vpn-tcp method requires iptables so Tel should test for it

### ISSUE THREAD

**Issue by richarddli** [telepresenceio/telepresence#306]
[telepresence.log](https://github.com/datawire/telepresence/files/1345172/telepresence.log)

**Comment by ark3** [comment]
What user are you? Does `sudo` work? The log file indicates that `sshuttle` is failing to run `iptables` because it's not running as root.

**Comment by richarddli** [comment]
shopbox@32826ab37942:/workspace$ sudo telepresence
The connection to the server localhost:8080 was refused - did you specify the right host or port?
No current-context set. Please use the --context option to explicitly set the context.

**Comment by ark3** [comment]
That's an error from `kubectl`, because it's not set up to run as root. In general, the shopbox environment is really weird. I suggest using `-m inject-tcp`.

**Comment by plombardi89** [comment]
Yea this is... weird:

```
shopbox@e1fd531e6646:/workspace$ iptables --list
iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
shopbox@e1fd531e6646:/workspace$ sudo -s
root@e1fd531e6646:/workspace# iptables --list
iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
root@e1fd531e6646:/workspace# whoami
root
```

**Comment by ark3** [comment]
It turns out that `iptables` doesn't work from within an unprivileged Docker container, which means `sshuttle` doesn't work. Telepresence should test `iptables --list` as part of its startup sanity checks.

**Comment by ark3** [comment]
Also need to document the iptables requirement
