### ISSUE TITLE
BUG: Relying on undefined behavior - parsing kubernetes resource names

### ISSUE THREAD

**Issue by thockin** [telepresenceio/telepresence#3063]
https://github.com/telepresenceio/telepresence/blob/release/v2/pkg/client/cli/cmd_gather_logs.go#L490

The random suffix of a pod or other resource is not guaranteed to be 5 characters, nor is the characterset defined. Those are implementation details, not to be depended on. This is brittle and could change at any time.

You should be using labels to extract metadata, not parsing the name. That's literally why they exist.

**Comment by thockin** [comment]
Almost a year later this bug still exists.  If kubernetes changes this behavior you will break.

**Comment by thallgren** [comment]
@thockin this is open source. Feel free to submit a PR with a fix if this is important to you.

**Comment by thockin** [comment]
I appreciate the intent, but I think you misunderstood me. This is a bug in telepresence. I don't use telepresence, so I don't have an "itch" to scratch.

I am just warning you that you are well outside the bounds of supported behavior and that Kubernetes may well change those details and break you _and your users_. Will this particular break matter to them?  I don't know. I don't use telepresence.

The fact that we have not "fixed" kubernetes already is because we try NOT to break people, even those downstream projects that are relying on undefined behavior. In this case, that's more of a grace period than a promise.

Consider the project warned. When kubernetes fixes our own bugs, I don't want to hear about how we broke telepresence.

**Comment by thallgren** [comment]
Yes, I misunderstood, and we will consider us warned. Thanks, and my apologies.
