### ISSUE TITLE
"How it works" on front page isn't quite accurate

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#309]
It talks about LD_PRELOAD, but default was (and presumably still is?) sshuttle method.

**Comment by richarddli** [comment]
Ah. Abhay or Itamar, could you help with a more accurate description?

**Comment by ark3** [comment]
We should update the home page example and probably the asciinema (terminal video) too.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since our docs should be up-to-date.
