### ISSUE TITLE
telepresence client version subcommand should work without a defined cluster

### ISSUE THREAD

**Issue by amengcs** [telepresenceio/telepresence#3090]
To automate the installation of the telepresence client, we rely on the reported version number.
It would be helpful if the telepresence version subcommand would report the client version even when no kubeconfig is present.

Doing this with no defined kubeconfig:

   telepresence version

yields this:

   telepresence version: error: kubeconfig has no context definition

Would like to see this instead:

  telepresence version
  Client     : v2.12.0
  Root Daemon: not running
  User Daemon: not running

with at least the client version info populated.

**Comment by thallgren** [comment]
Superseded by #3095
