### ISSUE TITLE
Unable to determine cluster domain

### ISSUE THREAD

**Issue by gleant** [telepresenceio/telepresence#3114]
**Describe the bug**
When install or restart Traffic manager in kubernetes we are seeing the following error in the Traffic manager's logs:
```
2023-04-03 06:54:00.6575 info    Unable to determine cluster domain from CNAME of %!s(<nil>): kubernetes.default"
2023-04-03 06:54:00.6576 info    Using cluster domain "cluster.local."
```

**Expected behavior**
I would expect that cluster domain to be resolved successfully. 

**Versions (please complete the following information):**
```
Client         : v2.12.1
Root Daemon    : v2.12.1
User Daemon    : v2.12.1
Traffic Manager: v2.12.1
```
 - Operating system: OSX 12.6.3(intel)
 - Kubernetes environment and Version: Bare metal v1.26.2

**Additional context**
Earlier version results when resolving cluster domain:
```
2023-04-03 06:42:05.9488 info    Using cluster domain "cuumadev-green."
```

**Comment by thallgren** [comment]
Interesting. The approach we're using there obviously doesn't work very well. Can you please provide the output of this command?
```
kubectl -n ambassador exec -it deploy/traffic-manager -- nslookup agent-injector
```

**Comment by gleant** [comment]
```
Server:		169.254.25.10
Address:	169.254.25.10:53

Name:	agent-injector.ambassador.svc.cuumadev-green
Address: 10.233.42.15

** server can't find agent-injector.cuuma.fi: NXDOMAIN

** server can't find agent-injector.svc.cuumadev-green: NXDOMAIN

** server can't find agent-injector.cuuma.fi: NXDOMAIN

** server can't find agent-injector.cuumadev-green: NXDOMAIN


** server can't find agent-injector.ccn.fi: NXDOMAIN

** server can't find agent-injector.svc.cuumadev-green: NXDOMAIN

** server can't find agent-injector.cuumadev-green: NXDOMAIN

** server can't find agent-injector.ccn.fi: NXDOMAIN
```

I guess that the problem is in file https://github.com/telepresenceio/telepresence/blob/v2.12.1/cmd/traffic/cmd/manager/internal/cluster/info.go on row 98. You are checking that domain ends with `.svc.` but in our case it ends with `svc.cuumadev-green`

**Comment by thallgren** [comment]
Thanks for confirming the result of that lookup. PR #3118 with a fix for this will be included in the next release.

**Comment by gleant** [comment]
Thank you for the fix.
