### ISSUE TITLE
Cannot intercept/list services after successful connect

### ISSUE THREAD

**Issue by patdlanger** [telepresenceio/telepresence#3123]
**Describe the bug**
I can connect to my cluster successfully but apart from that dns resolution seems to fail and I cannot list or intercept any services

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/11159983/telepresence_logs.zip)

**To Reproduce**
1. When I run 'telepresence connect'
2. I see 'Connected to context xyz'
3. So I look at 'telepresence list -n myNamespace'
4. and I get 'No Workloads (Deployments, StatefulSets, or ReplicaSets)'

**Expected behavior**
I expect things to work afterwards.

even simple things such as 
```
➜  ~ curl -ik https://kubernetes.default
curl: (6) Could not resolve host: kubernetes.default
```
fail after I connect

**Versions (please complete the following information):**
 - Output of `telepresence version`
 -  Client             : v2.12.1
Root Daemon        : v2.12.1
User Daemon        : v2.12.1
OSS Traffic Manager: v2.11.1

 - Operating system of workstation running `telepresence` commands
   - Ubuntu 22.04.2 LTS
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
   - v1.24.9-gke.3200

**Comment by thallgren** [comment]
From the looks of it, you don't have sufficient RBAC permissions. You can, for instance, not list the clusters namespaces. You can test this using:
```console
$ kubectl auth can-i list namespaces -A
```
Please read [Cluster-wide telepresence user access](https://www.getambassador.io/docs/telepresence/latest/reference/rbac#cluster-wide-telepresence-user-access) for more info about required permissions.

**Comment by patdlanger** [comment]
Looking at https://www.getambassador.io/docs/telepresence/latest/reference/rbac#namespace-only-telepresence-user-access listing cluster namespaces should not be required when you are only interested in certain namespaces as far as I understand.

In addition to the namespace permissions I do have the permissions listed here https://www.getambassador.io/docs/telepresence/latest/reference/rbac#traffic-manager-connect-permission 

My namespaced permissions also seem fine
```
➜  ~ kubectl auth can-i list services                        
yes
➜  ~ kubectl auth can-i watch services
yes
➜  ~ kubectl auth can-i get services
yes
➜  ~ kubectl auth can-i get deployments
yes
➜  ~ kubectl auth can-i list deployments
yes
➜  ~ kubectl auth can-i watch deployments
yes
```

**Comment by patdlanger** [comment]
works fine after granting the list namespaces permission
