### ISSUE TITLE
Facing dns resolution issue when intercepting the service

### ISSUE THREAD

**Issue by kunal131196** [telepresenceio/telepresence#3135]
**Describe the bug**
When we are intercepting 2 services of remote cluster we are facing dns resolution issue. please find logs below 
Unable to connect to the server: dial tcp: lookup [dev2-k8smaster.test.in](http://dev2-k8smaster.test.in/) on [127.0.0.53:53](http://127.0.0.53:53/): no such host However this host "dev2-k8smaster.test.in" gets resolve properly when not using telepresence.

**To Reproduce**
1. configure local dns server on the laptop using resolvconf 
2. connect to remote cluster using telepresence connect
3. check logs for the resolution error

**Expected behavior**
dns resolution should work so that other urls should work for the user on laptop

**Versions (please complete the following information):**
 - v2.12.2
 - Ubuntu 20
 - Kubernetes environment - kubeadm version : 1.24

**Additional context**
I am not sure if any other setting required on laptop for local dns server to work with telepresence.

**Comment by cindymullins-dw** [comment]
Hi @kunal131196 , I do see [this comment](https://github.com/telepresenceio/telepresence/issues/1182#issuecomment-1208329496) about resolveconf you might check out.  On Linux, Telepresence uses [this DNS resolver](https://www.getambassador.io/docs/telepresence/latest/reference/routing#linux-systemd-resolved-resolver).

**Comment by thallgren** [comment]
@kunal131196 I think you forgot to provide the logs.

I'm curious to why you configure your workstation using `resolvconf` instead of [resolvectl](https://manpages.ubuntu.com/manpages/impish/man1/resolvectl.1.html).

**Comment by thallgren** [comment]
Closing due to lack of response.
