### ISSUE TITLE
Cannot connect to cluster with telepresence docker extension

### ISSUE THREAD

**Issue by vbode** [telepresenceio/telepresence#3155]
**Describe the bug**
When trying to connect with to my locally running minikube cluster, I get the error:

![image](https://user-images.githubusercontent.com/81425543/235592867-9990ce6d-8966-490e-8de7-c441ad7e2653.png)

I do see the traffic manager pods being installed:
![image](https://user-images.githubusercontent.com/81425543/235592943-94d205d8-56f6-4ebc-8c70-a1c8afdecec8.png)

I am also able to connect to the cluster with kubectl from powershell:

![image](https://user-images.githubusercontent.com/81425543/235593004-72303084-cfda-442b-9e3e-e388b2e479f6.png)

**To Reproduce**
1. I click 'Connect' in the Docker Extension
2. I see the error in the above screenshot

**Expected behavior**
I should be able to connect since kubectl has no issues connecting

**Versions (please complete the following information):**
 - Output of `telepresence version`
 - Windows 10
 - Kubernetes 1.21 running in Minikube

**Comment by jcornick-alabs** [comment]
Team to test extension more with minikube running on the host machine.

**Comment by jcornick-alabs** [comment]
@vbode can you try setting the server: in your config to use the special Docker hostname for reaching the host from a container.  In your case I'd expect it to be https//host.docker.internal:8443.  8443 would be the default minikube port.

In the error you posted here the address of https://127.0.0.1:41181 refers to the container that telepresence is running in, not your host machine (where minikube is running), so connection refused would be expected.

**Comment by vbode** [comment]
Hi @jcornick-alabs. I have tried the suggestion but then I get:

connector.Connect: initial cluster check failed: Get "https://host.docker.internal:46179/version": tls: failed to verify certificate: x509: certificate is valid for minikubeCA, control-plane.minikube.internal, kubernetes.default.svc.cluster.local, kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not host.docker.internal

So I proceeded to add 'kubernetes' to my hosts file with the same ip as set for host.docker.internal. This leads to:
connector.Connect: initial cluster check failed: Get "https://kubernetes:46179/version": dial tcp: lookup kubernetes on 127.0.0.11:53: read udp 127.0.0.1:41471->127.0.0.11:53: i/o timeout

I am however able to curl it:
$ curl -k https://kubernetes:46179/version
{
  "major": "1",
  "minor": "21",
  "gitVersion": "v1.21.9",
  "gitCommit": "b631974d68ac5045e076c86a5c66fba6f128dc72",
  "gitTreeState": "clean",
  "buildDate": "2022-01-19T17:45:53Z",
  "goVersion": "go1.16.12",
  "compiler": "gc",
  "platform": "linux/amd64"
}

**Comment by vbode** [comment]
As before the telepresence pods are present however:
![image](https://user-images.githubusercontent.com/81425543/236169566-2b8dabe0-a12d-4755-bd7e-cd453b9a713f.png)

**Comment by njayp** [comment]
> So I proceeded to add 'kubernetes' to my hosts file with the same ip as set for host.docker.internal

unfortunately, this is not enough, the ip address in the docker vm is different from the ip address on the host. if you start an alpine container and run `nslookup host.docker.internal`, you will get the correct ip address. Adding this address to your hosts file will allow you to connect. Unfortunately, the extension will not function correctly because the extension also uses kubectl on the user's machine, which we have broken with our changes.

I suggest using k8s in docker desktop https://docs.docker.com/desktop/kubernetes/, as docker has added dns magic to make `kubernetes.docker.internal` resolve to different ip addresses depending on if you are in a container or not.

**Comment by vbode** [comment]
Ok I see, thanks for the answer @njayp 
We actually have a development environment tool which uses minikube, so switching to the kubernetes in docker desktop is not an option. 
I was recommended to use the plugin as an alternative to the regular application since for the regular application I am running into a different issue:
https://github.com/telepresenceio/telepresence/issues/2801

**Comment by thallgren** [comment]
We did fix some issues related to running a docker based daemon using minikube a while back, so that Telepresence automatically detects the `minikube` network that minikube uses by default. So, if minikube uses the docker driver and no special network config, everything should work out-of-the-box.

This is the PR where this was addressed: https://github.com/telepresenceio/telepresence/pull/3104

**Comment by vbode** [comment]
I use the following command to startup minikube:
`minikube --profile "ejvoe1kj12" start --extra-config=apiserver.service-node-port-range=1-65535 --kubernetes-version=v1.21.9 --cni=true --network ejvoe1kj12 --ports=54167:8443 --memory 8492 --cpus 2`

This leads the minikube to have these networks:
```
"Networks": {
                "ejvoe1kj12": {
                    "IPAMConfig": {
                        "IPv4Address": "192.168.49.2"
                    },
                    "Links": null,
                    "Aliases": [
                        "2015f4667bb2",
                        "ejvoe1kj12"
                    ],
                 ...omitted
                }
```
                
If I leave out the --network flag when starting minikube, the network I end up with is the same. Looks like minikube uses the name of the profile for the network for the docker container.

If I leave out the --profile flag, I end up with below network, but I still get the initial cluster check failed error:
```
"Networks": {
                "minikube": {
                    "IPAMConfig": {
                        "IPv4Address": "192.168.49.2"
                    },
                    "Links": null,
                    "Aliases": [
                        "b78f878dcf0a",
                        "minikube"
                    ],
                    ...omitted
}
```

The last thing I tried was to drop the --ports flag, but this still leads to the same issue.
@thallgren, the PR you mentioned was I guess tested on Linux?

**Comment by thallgren** [comment]
@vbode what does your kubeconfig look like?

**Comment by vbode** [comment]
@thallgren the kubeconfig minikube prepares looks like:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\VincentB\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Sat, 06 May 2023 12:13:29 CEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://127.0.0.1:55831
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 06 May 2023 12:13:29 CEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
```

As mentioned in this thread before, this will not work due to the server being the localhost address. However, if I try to replace the server with something the telepresence container could resolve:
`https://kubernetes:8443`
Where kubernetes is an entry in my host file pointing to the same address as host.docker.internal, then I get:
`connector.Connect: initial cluster check failed: Get "https://kubernetes:8443/version": dial tcp: lookup kubernetes on 127.0.0.11:53: read udp 127.0.0.1:60539->127.0.0.11:53: i/o timeout`

So pretty much the same result as in https://github.com/telepresenceio/telepresence/issues/3155#issuecomment-1534420836

**Comment by thallgren** [comment]
Hmm, yes. On my Linux box, the IP address is a 192.168.x.x:8443 address. Works from within the cluster as well as outside. I'll do some research using macOS. This should be solvable.
