### ISSUE TITLE
Telepresence website is broken in places

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#316]
Some parts of the Telepresence website broke during the transition from Jekyll to GitBook.

Some pages use the Telepresence version number as part of an example. Instead of the correct version number the site has `{{ site.data.version.version }}`. 

https://www.telepresence.io/reference/connecting
https://www.telepresence.io/reference/limitations 

What is the Gitbook way of doing the equivalent? An alternate solution might be to do an additional mass substitution in `build-website.sh`.

There are other pages with issues too. For example, https://www.telepresence.io/discussion/why-telepresence has code in place of a graph.

We should take a careful, critical look at each page. The website is not that big.

**Comment by richarddli** [comment]
I don't see the issue with the code in place of a graph. I see 3 graphs on the aforementioned URL?

**Comment by ark3** [comment]
It looks like the above issues have been addressed. Thanks!

However, problems remain. I have discovered that the release process is broken starting from the GitBook commit. Also, there is no automation around bumping the version number in the docs (in `docs/book.json`. I can address those two problems, but I need to know:

1. How does automated doc building work now? What scripts are run? Where do they run? What triggers the build?
2. Has someone looked at every page of the website to make sure there aren't more issues like the ones I found?

Thanks.

**Comment by ceridwen** [comment]
https://www.telepresence.io/tutorials/openshift

This page still has code in place of a graph.

**Comment by exarkun** [comment]
https://www.telepresence.io/tutorials/kubernetes also has code in place of a couple graphs near "You've gone from this..."

**Comment by richarddli** [comment]
@sipplified can you take a look at this?
