### ISSUE TITLE
Envoy in telepresence agent rejects http 1.0

### ISSUE THREAD

**Issue by nicks** [telepresenceio/telepresence#3169]
**Describe the bug**
When I intercept traffic under certain conditions, Telepresence kills all traffic, even traffic that's not being intercepted.

**To Reproduce**
See this repro:
https://github.com/nicks/telepresence-sandbox
which has a detailed setup

Once I get into this state, all HTTP requests return error code 426

**Expected behavior**
I expect Telepresence to intercept the traffic that matches my header, and leave all other traffic alone.

Once telepresence gets into this state, the only way to fix it is to uninstall the agent.

```
telepresence uninstall -d my-proxy
```

Notably, `telepresence leave` does not fix the problem.t

**Versions (please complete the following information):**

```
telepresence version
An update of telepresence from version 2.12.2 to 2.13.1 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client         : v2.12.2
Root Daemon    : v2.12.2
User Daemon    : v2.12.2
Traffic Manager: v2.12.2
```

see attached repo for kubernetes 

kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.25.7+k3s1

**Comment by nicks** [comment]
Ok, narrowed down the bug: telepresence uses envoy to manage agent traffic. envoy, by default, rejects all http 1.0 requests. https://github.com/envoyproxy/envoy/issues/170

nginx, by default, sends http 1.0 requests. http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version

it would be good if telepresence updated the agent's envoy config to accept http 1.0.

**Comment by thallgren** [comment]
Closing this and deferring to Ambassador support. The envoy based traffic-agent is not open source.
