### ISSUE TITLE
some pods ip can not access

### ISSUE THREAD

**Issue by chixianliangGithub** [telepresenceio/telepresence#3170]
![image](https://user-images.githubusercontent.com/11659305/237036528-d9c37ff9-3bd7-4fd2-b355-fdad66064c2f.png)
![image](https://user-images.githubusercontent.com/11659305/237036658-145e5fcd-d851-4c5d-9dc9-6ff00ea8f763.png)

Strange thing encountered: my pods 10.42.153.104 and 10.42.21.251
  One can be accessed and one cannot be accessed

**Comment by chixianliangGithub** [comment]
![image](https://user-images.githubusercontent.com/11659305/237037750-6522dc8f-37f6-4bda-bd6f-49bf16af756b.png)
This is my corresponding pod ip

**Comment by cindymullins-dw** [comment]
Hi @chixianliangGithub , it looks like the 153.104 address is the one that cannot be accessed?  Could you try adding that to your [alsoProxy](https://www.getambassador.io/docs/telepresence/latest/reference/config#alsoproxysubnets) configuration so that Telepresence knows to route to it?
