### ISSUE TITLE
relative kubeconfig path breaks `telepresence helm` commands

### ISSUE THREAD

**Issue by nicks** [telepresenceio/telepresence#3176]
**Describe the bug**

Using a relative KUBECONFIG path breaks telepresence helm commands

**To Reproduce**

```
$ KUBECONFIG=./.secrets/my-kubeconfig.yaml telepresence helm upgrade
telepresence helm upgrade: error: kubeconfig has no context definition
```

**Expected behavior**

Telepresence to connect to the cluster

Note that using the same KUBECONFIG with kubectl works fine:

```
$ KUBECONFIG=./.secrets/my-kubeconfig.yaml
No resources found in default namespace.
```

Also, using an absolute path for the KUBECONFIG works fine (`KUBECONFIG=$(pwd)/.secrets/my-kubeconfig.yaml`)

**Versions (please complete the following information):**

```
telepresence version
Client         : v2.13.1
Root Daemon    : v2.13.1
User Daemon    : v2.13.1
```

**Additional context**
My hunch is that the CLI is propagating the env var to the daemon, but doesn't take into account that they have different working directories.

As a side note, it would be good if telepresence used the same error messaging as kubectl for this case (something like: `Config not found: ./.secrets/my-kubeconfig.yaml`), the current error message seems pretty weird.

**Comment by thallgren** [comment]
Closed by #3363
