### ISSUE TITLE
telepresence connect: error: "C:\\Users\\030T0029\\AppData\\Local\\telepresence\\rootd.socket" is not a socket

### ISSUE THREAD

**Issue by zhangwanlong** [telepresenceio/telepresence#3189]
本地是win10 系统，去用telepresence.exe connect 链接的时候，提示is not a socket

PS E:\goweb\kubesphere2\cmd\ks-apiserver> telepresence gather-logs
telepresence gather-logs: error: "C:\\Users\\030T0029\\AppData\\Local\\telepresence\\userd.socket" is not a socket

**Comment by cindymullins-dw** [comment]
Have you tried running 'telepresence connect' without using the .exe suffix?

**Comment by thallgren** [comment]
Duplicate of #3191

**Comment by felixliulei** [comment]
Requesting help with an error encountered while using telepresence connect: "Launching Telepresence User Daemon"

telepresence connect: error: connector service did not start: "C:\Users\cd\AppData\Local\telepresence\userd.socket" is not a socket

The telepresence version you are using is v2.19.6.

**Comment by thallgren** [comment]
@felixliulei this is a bug in Windows and it was fixed a long time ago. You'll need to update your windows version.
