### ISSUE TITLE
DNS lookup failure with `telepresence connect --docker`

### ISSUE THREAD

**Issue by phoban01** [telepresenceio/telepresence#3190]
**Describe the bug**

DNS lookups are not resolved to KinD cluster when using `telepresence connect --docker`

**To Reproduce**
1. When I run `telepresence connect --docker`
2. Followed by `curl http://kubernetes.default`
3. I see `curl: (6) Could not resolve host: kubernetes.default`

**Expected behavior**

DNS lookup to resolve to services in KinD cluster.

**Versions**
 - Telepresence:
```
Client             : v2.13.2
Daemon in container: v2.13.2
Traffic Manager    : v2.13.2
```
 - Operating system: `Linux 6.2.10-arch1-1 x86_64 GNU/Linux`
 - Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"2023-03-19T19:47:22Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:03:40Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Kind version: `kind v0.19.0 go1.20.3 linux/amd64`

**Other details**

When using the host daemon (ie non-docker) DNS lookups work as expected.

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/11515200/telepresence_logs.zip)

**Comment by thallgren** [comment]
When you use `telepresence connect --docker`, you'll get a daemon that runs in a docker container. It sets up a private network for that container that has access to the cluster. Subsequent containers can then attach to that container, but the host will not have access to that network, so what you describe in your example is not supposed to work. What you should be able to do, is this:

```console
$ docker run --rm -it --network container:tp-kind-aws-demo curlimages/curl http://kubernetes.default
```

**Comment by phoban01** [comment]
Thank you for clarifying @thallgren.
