### ISSUE TITLE
--never-proxy doesn't work if there are multiple network interfaces.

### ISSUE THREAD

**Issue by david9991** [telepresenceio/telepresence#3196]
**Describe the bug**
After running `telepresence connect --never-proxy="192.168.72.0/24"`, incorrect static route added if there are multiple network interfaces.
<img width="518" alt="Screenshot 2023-05-24 at 16 55 06" src="https://github.com/telepresenceio/telepresence/assets/123219/5fb62351-90ac-4cd1-b17f-a6b080989bff">
actually the correct route table should be (which I modified manually and works for me):
<img width="504" alt="Screenshot 2023-05-24 at 16 57 22" src="https://github.com/telepresenceio/telepresence/assets/123219/5fa861ba-f35b-4770-a6b6-64474c711292">

**To Reproduce**
1. There are multiple network interfaces.
2. Run the command `telepresence connect --never-proxy="192.168.72.0/24"`

**Expected behavior**
Correct static route added.

**Versions (please complete the following information):**
- Client         : v2.13.2
  Root Daemon    : v2.13.2
  User Daemon    : v2.13.2
  Traffic Manager: v2.13.2
- macOS 13.4
- k8s v1.27.1

**VPN-related bugs:**
VPN: Surge

**Additional context**

**Comment by cindymullins-dw** [comment]
Hi @david9991 , we have users with multiple networks and are using `never-proxy` successfully.  Could you try setting the `never-proxy` in the config file instead of passing it in as a flag (which is fairly new)?  You can do that in the traffic manager values or in the kubeconfig.

**Comment by david9991** [comment]
Thank you for your response. You are right, `telepresence helm install --set client.routing.neverProxySubnets=192.168.72.0/24` works perfectly.
