### ISSUE TITLE
add a flag to disable requests to app.getambassador.io

### ISSUE THREAD

**Issue by kamikaze** [telepresenceio/telepresence#3199]
When installing with helm there is no way to disable such requests, while they are flooding in our logging due to blocking

**Comment by cindymullins-dw** [comment]
Hi @kamikaze , are you using the OSS version or the licensed version?  The OSS version doesn't make requests to Ambassador Cloud.

**Comment by jcornick-alabs** [comment]
You can set the SCOUT_DISABLE=1 env variable to disable this call.

**Comment by cindymullins-dw** [comment]
Closing as addressed.
