### ISSUE TITLE
kubectl under Telepresence vpn-tcp & Kubernaut doesn't work

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#320]
When using Telepresence with a [Kubernaut][k] cluster, the DNS lookup that the `kubectl` command performs to find the Kubernetes master gets the EC2-internal IP address because all DNS lookups are done in the cluster. Said `kubectl` command then fails because it cannot reach the master at that IP address from the local network.

This bug might apply to all Kops/EC2 Kubernetes clusters. We should find out.

[k]: https://github.com/datawire/kubernaut#kubernaut

**Comment by richarddli** [comment]
I don't see this?
```
lost-cause:qotm richard$ kubectl get svc
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.96.0.1       <none>        443/TCP   1h
qotm         10.110.20.176   <none>        80/TCP    4s
lost-cause:qotm richard$ telepresence
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see http://www.telepresence.io/reference/methods.html.
Volumes are rooted at $TELEPRESENCE_ROOT. See http://www.telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

Guessing that Services IP range is 10.96.0.0/12. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

@admin@kubernetes|bash-4.4$ curl qotm
{
  "hostname": "qotm-108851151-jmzpr",
  "ok": true,
  "quote": "The light at the end of the tunnel is interdependent on the relatedness of motivation, subcultures, and management.",
  "time": "2017-10-10T20:09:07.552793",
  "version": "1.1"
}
@admin@kubernetes|bash-4.4$ kubectl cluster-info
Kubernetes master is running at https://i-03c5184c782a8983c.kubernaut.io:6443
```

**Comment by richarddli** [comment]
I should note that I am running 0.64, if that makes a difference.

**Comment by ark3** [comment]
@richarddli If I follow your script, I can get to where you got, but my `kubectl` commands hang on master access. So, for example, I'll see that the Kubernetes master is running at blah.kubernaut.io but then my `kubectl` hangs there for a while, then times out.

```shell
@admin@kubernetes|bash-3.2$ kubectl cluster-info
Kubernetes master is running at https://i-0fc08e0a9da249549.kubernaut.io:6443
^C
@admin@kubernetes|bash-3.2$ kubectl get svc
Unable to connect to the server: dial tcp 10.10.76.7:6443: i/o timeout
@admin@kubernetes|bash-3.2$ exit
exit
><> kubectl get svc
NAME                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
kubernetes                                  ClusterIP   10.96.0.1        <none>        443/TCP    9h
qotm                                        ClusterIP   10.110.154.70    <none>        80/TCP     4m
><> 
```

Do `kubectl` commands actually finish and succeed for you under Telepresence?

**Comment by richarddli** [comment]
Ah, I misunderstood the headline. I changed the subject to "kubectl doesn't work with telepresence vpn-tcp and Kubernaut"

**Comment by plombardi89** [comment]
I was thinking about this a bit just now... if we're running a VPN shouldn't the private IP space of the VPC be routable since we're essentially a host inside of it. We may just need to add additional routing config?

Sadly networking has never been my strong suit.

**Comment by ark3** [comment]
FWIW, @plombardi89 worked around this issue (and #391) in Kubernaut by putting an IP address in the generated Kubernetes configuration for Kubernaut clusters. This avoids the DNS lookup entirely. Regardless, we should think about how to fix this for other users of typical configurations, possibly by special-casing the DNS lookup of the master to return the original address or by proactively forwarding the internal address to the cluster too.

**Comment by marun** [comment]
I experienced this same problem when using telepresence vpn-tcp and trying to access an openshift cluster deployed on aws. In my case, replacing the host name with the resolved ip address in my kubeconfig did not solve the problem because the api endpoint for a cluster managed by `try.openshift.com` is virtualhost-based. The fix for me was adding an entry in /etc/hosts, so that the dns resolution was performed in aws and the endpoint for the cluster received the host name it required.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
