### ISSUE TITLE
Telepresence connect --docker broken on Linux with Docker Desktop

### ISSUE THREAD

**Issue by knlambert** [telepresenceio/telepresence#3201]
**Describe the bug**

I was building the release/v2 branch when I noticed that I have an issue using the Docker mode on Linux, with Docker Desktop.

If I do 
```cli
➜  telepresence git:(ac8324b66) ✗ telepresence connect --docker                        
telepresence connect: error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

See logs for details (13 errors found): "/home/kevin/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

It seems that the cli isn't able to find the docker daemon, although docker ps works : 

```cli
➜  telepresence git:(ac8324b66) ✗ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

It seems that the commit which broke it for me is this [one](https://github.com/telepresenceio/telepresence/commit/ac8324b6624940e11248644e05eea9baf19c1731#diff-ffebb30f222645518c9db41fb6c55d407c20cd75124ece6243017e4542e2f024) . 

It works if I use the GA of Telepresence, or a commit before, although it prints a warning: 

```cli
➜  ~ telepresence connect --docker
Connected to context default (https://klambert.cluster.bakerstreet.io)
Warning: DNS doesn't seem to work properly
```

**To Reproduce**
1. Use Linux with Docker Desktop
2. `git checkout ac8324b6624940e11248644e05eea9baf19c1731 && make build`
3. telepresence connect --docker

**Expected behavior**

I've tried previous commits (the one just before) but also telepresence 2.13.2, and it's working fine.

**Versions (please complete the following information):**
- NA

**Comment by thallgren** [comment]
The error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` suggests that you're using the wrong docker context. What is the output of?
```
docker context ls
```

**Comment by knlambert** [comment]
Note that with Docker Desktop, even on Linux, it's a VM, so I have a context for the normal docker, but that's not the one used : 

```cli
ambassador@ambassador-ThinkPad-X1-Carbon-7th:~/dev/telepresence$ docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                       KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                                 
desktop-linux *     moby                                                          unix:///home/ambassador/.docker/desktop/docker.sock           
```
