### ISSUE TITLE
IP defined via NODE_NAME is not correctly being forwarded

### ISSUE THREAD

**Issue by Taik** [telepresenceio/telepresence#321]
A few of our internal  services uses the downwards API to access NODE_NAME, so that we can talk to the daemonset running on the local node. It seems like telepresence is only forwarding the service IP range. 

Unfortunately, we can't use `--method inject-tcp` as our services are in go. Following the default suggestion of using `--method vpn-tcp`, we can fall back to using `--also-proxy=<HOST_NAME>`, but is flakey as we can't guarantee that the pod will land on the same node  every time.

Would it make sense to have a special rule that always forwards IPs defined via `NODE_NAME`, or maybe modify `--also-proxy` to take in CIDR's (possibly related to https://github.com/datawire/telepresence/issues/264)?

**Comment by ark3** [comment]
Thanks for the feature request. We are looking into generally broadening what gets proxied from the client, including pods and nodes. That would cover your case as well as help with #264 and maybe #320. Stay tuned!

**Comment by donnyyung** [comment]
I'm not sure if this still applies to Telepresence 2, so going to label this as a Telepresence 2 issue until we confirm that it's not an issue.
