### ISSUE TITLE
Accessing a swapped out service results in a lost connection

### ISSUE THREAD

**Issue by lucyli** [telepresenceio/telepresence#322]
Telepresence seems to be able to successfully swap out a service with my local development version, but when I try to load a webpage served by the swapped out service, I get the error: `Connection to localhost closed by remote host`, ultimately resulting in `Proxy to Kubernetes exited.`

Using version 0.67, the verbose version of the telepresence log shows  this when I try accessing the webpage (line 685 in the full logs, attached):

```
166.3 18 | debug1: client_input_channel_open: ctype forwarded-tcpip rchan 2 win 87380 max 32768
 166.3 18 | debug1: client_request_forwarded_tcpip: listen  port 3000, originator 172.17.0.9 port 48980
 166.3 18 | debug2: fd 7 setting O_NONBLOCK
 166.3 18 | debug2: fd 7 setting TCP_NODELAY
 166.3 18 | debug1: connect_next: host 127.0.0.1 ([127.0.0.1]:3000) in progress, fd=7
 166.3 18 | debug1: channel 0: new [172.17.0.9]
 166.3 18 | debug1: confirm forwarded-tcpip
 166.3 18 | debug1: channel 0: connected to 127.0.0.1 port 3000
 166.3 18 | debug1: client_input_channel_open: ctype forwarded-tcpip rchan 3 win 87380 max 32768
 166.3 18 | debug1: client_request_forwarded_tcpip: listen  port 3000, originator 172.17.0.1 port 55202
 166.3 18 | debug2: fd 8 setting O_NONBLOCK
 166.3 18 | debug2: fd 8 setting TCP_NODELAY
 166.3 18 | debug1: connect_next: host 127.0.0.1 ([127.0.0.1]:3000) in progress, fd=8
 166.3 18 | debug1: channel 1: new [172.17.0.1]
 166.3 18 | debug1: confirm forwarded-tcpip
 166.3 18 | debug1: channel 1: connected to 127.0.0.1 port 3000
 166.3 18 | debug1: client_input_channel_open: ctype forwarded-tcpip rchan 4 win 87380 max 32768
 166.3 18 | debug1: client_request_forwarded_tcpip: listen  port 3000, originator 172.17.0.1 port 55204
 166.3 18 | debug2: fd 9 setting O_NONBLOCK
 166.3 18 | debug2: fd 9 setting TCP_NODELAY
 166.3 18 | debug1: connect_next: host 127.0.0.1 ([127.0.0.1]:3000) in progress, fd=9
 166.3 18 | debug1: channel 2: new [172.17.0.1]
 166.3 18 | debug1: confirm forwarded-tcpip
 166.3 18 | debug1: channel 2: connected to 127.0.0.1 port 3000
 ```

The channel number increases until it hits 1016, then everything seems to shut down. Eventually, I get the error `Connection to localhost closed by remote host` (line 14886 of full logs).

And shortly after, this error:
`A subprocess (['ssh', '-N', '-oServerAliveInterval=1', '-oServerAliveCountMax=10', '-F', '/dev/null', '-vv', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '54963', 'telepresence@localhost', '-R', '*:3000:127.0.0.1:3000']) died with code 255, killed all processes...`.

Full logs: [telepresence-app.log](https://github.com/datawire/telepresence/files/1380193/telepresence-app.log)

Please let me know if I can provide more info. Thanks!

**Comment by ark3** [comment]
Thank you for the detailed report. This looks like a forwarding loop. Minikube, right? If so, can you try your test with a remote cluster? I will try to replicate this at my end.

**Comment by lucyli** [comment]
Yup, using minikube. Just tested with a remote cluster, and everything worked as expected.

I recently upgraded my OS to Mac High Sierra (10.13), so this could point to a minikube issue on the new OS. The remote cluster I connected to was actually minikube on a coworker's machine (older OS version).

**Comment by gogwilt** [comment]
Any progress on this?

**Comment by ark3** [comment]
Sorry, we have not made much progress on this yet. Minikube + MacOS + vpn-tcp is still flaky for some users and non-working for a few others, though many users are having success with that combination. If it's not working for you, we suggest trying the other methods (the container method is quite solid) or using a remote cluster. [Kubernaut](https://github.com/datawire/kubernaut#kubernaut) can give you quick access to an ephemeral remote cluster for dev/testing work.

**Comment by jacobsee** [comment]
I am hitting this exact problem `Connection to localhost closed by remote host` causing the entire thing to die when running against GKE, not minikube. It occurs regardless of whether I'm using vpn-tcp or inject-tcp. I am using MacOS though. Could something other than minikube weirdness be causing this same issue?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
