### ISSUE TITLE
Remove everything that concerns licensed features.

### ISSUE THREAD

**Issue by thallgren** [telepresenceio/telepresence#3242]
Remove all configurations and all code dealing with login, licensed features, and connections to the Ambassador cloud app from the OSS code-base.

**Comment by thallgren** [comment]
Closed by #3251

**Comment by Har-sha-256** [comment]
Is this not possible anymore post the change in #3251 : https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config#air-gapped-cluster
