### ISSUE TITLE
New Telepresence Windows executable is broken

### ISSUE THREAD

**Issue by vbode** [telepresenceio/telepresence#3243]
**Describe the bug**
The new telepresence Windows executable is broken, the executable is from the telepresence version: 2.14.0-gotest.z84df773, rather than a release version

**To Reproduce**
1. Download the executable on the telepresence home page (https://app.getambassador.io/download/tel2oss/releases/download/v2.14.0/telepresence-windows-amd64.exe)
2. Do a `telepresence version`:
An update of telepresence from version 2.14.0-gotest.z84df773 to 2.14.0 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
OSS Client : v2.14.0-gotest.z84df773
3. Try a `telepresence helm install`
{"cmd":"install","err":"failed to install traffic manager: the helm operation timed out.  The current timeout 30s can be configured as \"timeouts.helm\" in \"C:\\\\Users\\\\VincentB\\\\AppData\\\\Roaming\\\\telepresence\\\\config.yml\""}
4. In the cluster I see the following error while the traffic-manager pod is trying to be installed:
rpc error: code = Unknown desc = Error response from daemon: manifest for datawire/tel2:2.14.0-gotest.z84df773 not found: manifest unknown: manifest unknown

**Expected behavior**
The executable on the main page should be of a proper released version and would work

**Comment by jacoblbeck** [comment]
@vbode thank you for reporting this, we've remediated the windows link and you should be able to redownload the binary and it will work as expected with v2.14.0

**Comment by vbode** [comment]
Hi @jacoblbeck, thanks, the binary looks better now, and I can succesfully install the traffic manager
Just one problem, when connecting to my cluster I get:
_Could not connect to Telepresence in the cluster. Error message was {"cmd":"connect","err":"connector.Connect: NewTunnelVIF: failed to create TUN device: Error creating interface: Error loading wintun.dll DL
L: Unable to load library: The specified module could not be found."}_

In before versions, the wintun.dll was provided by the powershell installer script. The new download only provides the exe and not this dll, leading to above error.

If I place the dll (from my earlier install) in the same directory as I have the exe, then everything works again.

**Comment by vbode** [comment]
Hi @jacoblbeck, did you by any chance see my last message?

**Comment by vbode** [comment]
Hey @jacoblbeck, the same also applies by the way to 'sshfs' 
https://github.com/winfsp/sshfs-win

**Comment by knlambert** [comment]
This issue should be fixed with next 2.15 release. You can [already try with the rc.](https://github.com/telepresenceio/telepresence/releases/tag/v2.15.0-rc.1)

**Comment by vbode** [comment]
Seems to work fine now with the rc version!
