### ISSUE TITLE
Extra included DNS suffix does not get resolved, but direct query to kube-dns succeeds

### ISSUE THREAD

**Issue by james-masson** [telepresenceio/telepresence#3250]
**Describe the bug**

On Mac, When adding an additional `include-suffixes` as per https://www.getambassador.io/docs/telepresence-oss/latest/reference/config ...

```
User Daemon: Running
  Version           : v2.14.0
  Executable        : /opt/homebrew/bin/telepresence
  Install ID        : 0a5a235f-3dd8-4c8b-b8cb-45a5e58c589d
  Status            : Connected
  Kubernetes server : https://127.0.0.1:32784
  Kubernetes context: minikube
  Manager namespace : ambassador
  Intercepts        : 0 total
Root Daemon: Running
  Version    : v2.14.0
  Version    : v2.14.0
  DNS        : 
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.com .io .net .org .ru]
    Include suffixes: [.adaptive.local]
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - 127.0.0.1/32
Ambassador Cloud:
  Status      : Logged out
Traffic Manager: Connected
  Version : v2.14.0
  Mode    : single-user
Intercept Spec: Not running

```

... the include suffix is correctly added to `/etc/resolver/`, but a DNS query on the host ( and to 127.0.0.1:port ) returns an empty response.

```
#$ dig +short  argo-cd.dev.platform-exchange.adaptive.local
#$ cat /etc/resolver/telepresence.adaptive.local.local 
# Generated by telepresence

port 55975
domain adaptive.local
nameserver 127.0.0.1

#$ dig +short @127.0.0.1 -p 55975 argo-cd.dev.platform-exchange.adaptive.local
#$
```

Querying kube-dns service direct yields the correct answer.

```
#$ dig +short @kube-dns.kube-system.svc.cluster.local  argo-cd.dev.platform-exchange.adaptive.local
dev-emissary-ingress.dev-emissary-ingress.svc.cluster.local.
10.96.171.240
#$
```

Note: these returned records are extra injected records into coredns, not part of standard k8s resources.

you can add these locally by adding...

```
data:
  Corefile: |
    adaptive.local:53 {
        template ANY A adaptive.local {
            answer "{{ .Name }} 60 IN CNAME my-service.my-namespace.svc.cluster.local"
        }
    }
    ..existing..config...here
```

via
```
kubectl -n kube-system edit configmap coredns
```

**Expected behavior**

I expect all `include-suffix` to be forwarded to kube-dns.kube-system for resolution.

**Versions**
```
Client         : v2.14.0
Root Daemon    : v2.14.0
User Daemon    : v2.14.0
Traffic Manager: v2.14.0
```

Mac Ventura 13.4

Minikube / docker / orbstack / k8s v1.25.6

**Additional context**

**Comment by cindymullins-dw** [comment]
In your case is this impacting functionality?  I notice [this issue](https://github.com/telepresenceio/telepresence/issues/2599) where kube-dns.kube-system service is not available and the workaround there seems to be to create one.

**Comment by thallgren** [comment]
Please note that `dig` on a mac[ won't use the DNS properly](https://random.ac/cess/2018/04/12/macos-dig-vs-dscacheutil-while-using-split-dns-with-viscosity-vpn-client/). It has it's own built-in DNS resolver. Try using `dscacheutil -q host -a name your.domain.xx`

**Comment by th3fallen** [comment]
@james-masson did you ever find a solution to this? i seem to be running into the same issue?

**Comment by thallgren** [comment]
@th3fallen I don't think there's a solution as such. Telepresence does what it's supposed to do. The `dig` command however, doesn't. This is noted in their [man page for dig](https://ss64.com/mac/dig.html).
 
 > macOS NOTICE
The dig command does not use the host name and address resolution or the DNS query routing mechanisms used by other processes running on macOS. The results of name or address queries printed by dig might differ from those found by other processes that use the macOS native name and address resolution mechanisms. The results of DNS queries can also differ from queries that use the macOS DNS routing library.

**Comment by th3fallen** [comment]
@thallgren perhaps i just have a misunderstanding but I assumed by setting a domain as an included suffix it would resolve to the cluster. i see the etc/resolver file but any attempts to resolve the domain go nowhere.

**Comment by thallgren** [comment]
@th3fallen what happens if you try resolving a name in the domain using this command?
```
dscacheutil -q host -a name <your name>
```
