### ISSUE TITLE
Why not linux-arm64 client?

### ISSUE THREAD

**Issue by audacioustux** [telepresenceio/telepresence#3259]
**Please describe your use case / problem.**
As i'm using devcontainer - on aarch64 machine remotely, linux-arm64 binary is required for me.
I see there's darwin-arm64 (considering apple silicon hardware), but arm64 hardware exists in other niche places too - and growing fast.

**Describe the solution you'd like**
please consider including linux/arm64 as compilation target

**Describe alternatives you've considered**
moving the whole dev environment / devcontainer to amd64 - not much viable option for me

**Comment by audacioustux** [comment]
https://github.com/actions/runner-images/issues/5631 i see why :)
any workaround?

**Comment by thallgren** [comment]
I think this is simply an oversight, given that our CI actually test building the [linux-arm64 client](https://github.com/telepresenceio/telepresence/blob/release/v2/.github/workflows/unit_tests.yaml#L100-L101).

**Comment by audacioustux** [comment]
@thallgren i see... but that's just unit testing... not in release workflow... my last comment i think is the reason

![Screenshot 2023-07-14 at 9 01 13 PM](https://github.com/telepresenceio/telepresence/assets/7238675/c8a10e5e-3e96-4f1d-85f7-7e773435fde4)

**Comment by sarabrajsingh** [comment]
@audacioustux - i'm looking into extending our builds to include aarch64 binaries built on a fedora38-arm64 image. one issue might be exactly what you mentioned above -https://github.com/actions/runner-images/issues/5631

but there are some marketplace images that we can try and leverage in lieu of an office gh runner image. i'll keep you posted here.
