### ISSUE TITLE
Telepresence command throws exception when connecting to the socket

### ISSUE THREAD

**Issue by f-f** [telepresenceio/telepresence#326]
### What were you trying to do?

Trying out `telepresence`, following [this tutorial](https://www.telepresence.io/tutorials/kubernetes-rapid).

Command I ran last: `telepresence --deployment devserver --expose 8080 --run-shell`

### What did you expect to happen?

A kubernetes-connected shell spawning. 

### What happened instead?

Python exception.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--deployment', 'devserver', '--expose', '8080', '--run-shell']`
Version: `0.68`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.8.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin trajan 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2383, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 2125, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/bin/telepresence", line 1917, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence", line 1904, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence", line 395, in get_output
    result = unicode(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence5')"]' returned non-zero exit status 1.

```

Logs:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

```

**Comment by ark3** [comment]
Sorry about the crash. Telepresence needs to be better about reporting errors instead of crashing.

In this case, Telepresence has initiated a connection with its proxy in your cluster and is trying to validate that connection by testing whether name resolution is correctly making it to the proxy. It appears to have tried this test for twenty seconds, only getting four name requests done in that time, and then timed out and given up.

May I have your `telepresence.log` file for this session? The log snippet present in the report is too narrow to learn anything. You should feel free to redact any private names/IP addresses if that is a concern.

Thanks for the bug report!

**Comment by f-f** [comment]
Thanks for the quick reply!

As you noticed, I redacted the `telepresence.log` due to containing sensitive data (like DNS history).
However, it's not _that_ sensitive, so here's the last part of it:
```
  54.4 29 | c : DNS request from ('10.1.2.6', 53476) to None: 27 bytes
  54.5 8 | 2017-10-16T11:25:17+0000 [stdout#info] A query: b'slack.com'
  54.5 8 | 2017-10-16T11:25:17+0000 [stdout#info] Result for b'slack.com' is ['52.222.162.224']
  56.1 29 | c : DNS request from ('10.1.2.6', 52733) to None: 44 bytes
  56.2 8 | 2017-10-16T11:25:19+0000 [stdout#info] Result for b'hellotelepresence7.openvpn' is ['127.0.0.1']
  70.7 29 | c : DNS request from ('10.1.2.6', 60774) to None: 58 bytes
  70.7 29 | c : DNS request from ('10.1.2.6', 60136) to None: 55 bytes
  70.8 8 | 2017-10-16T11:25:33+0000 [stdout#info] 12 query: b'lb._dns-sd._udp.0.1.168.192.in-addr.arpa'
  70.8 8 | 2017-10-16T11:25:33+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 62523
  70.8 8 | 2017-10-16T11:25:33+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fdd606c6940>
  70.8 8 | 2017-10-16T11:25:33+0000 [stdout#info] 12 query: b'lb._dns-sd._udp.6.2.1.10.in-addr.arpa'
  70.8 8 | 2017-10-16T11:25:33+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 43552
  70.8 8 | 2017-10-16T11:25:33+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fdd606c6ac8>
  71.0 8 | 2017-10-16T11:25:34+0000 [-] (UDP Port 43552 Closed)
  71.0 8 | 2017-10-16T11:25:34+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fdd606c6ac8>
  71.0 8 | 2017-10-16T11:25:34+0000 [-] (UDP Port 62523 Closed)
  71.0 8 | 2017-10-16T11:25:34+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fdd606c6940>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

Additional detail that might be of help: I didn't expose the service to the internet (as I don't really feel like exposing the service I'm developing to the internet, I just want to talk with the other services in the cluster).

**Comment by ark3** [comment]
Is that from the same session? In the traceback above, I see a timeout crash (line 1917) on hellotelepresence5. In the log file, I see a successful response for hellotelepresence7, which would never have been sent if there were a timeout at 5. 

Two other questions:
1. Are you using a cluster running on your local machine, e.g., Minikube?
2. Are you running a VPN other than Telepresence?

Thanks for working with me to debug this. I appreciate your help!

**Comment by f-f** [comment]
Oh sorry, you're right. I accidentally copied the `telepresence.log` from a later session. I think I lost the previous one.

For completeness, here's the exception from this session:
```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2383, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 2125, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/bin/telepresence", line 1917, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence", line 1904, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence", line 395, in get_output
    result = unicode(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence7')"]' returned non-zero exit status 1.
```
To answer your questions:
1. No Minikube, running this against a cluster on GKE.
2. Yes I have another OpenVPN running. Company VPN, not forwarding all traffic, but just some routes.

Thanks!

**Comment by kai5263499** [comment]
I'm seeing this behavior as well. I also have a company VPN (Palo Alto Global Protect) running.

**Comment by ark3** [comment]
Telepresence's vpn-tcp mode is [not compatible with VPNs](https://www.telepresence.io/reference/methods#limitations---method-vpn-tcp). We recommend [container mode](https://www.telepresence.io/tutorials/docker) as a robust and broadly-compatible solution. You may also want to give inject-tcp mode a try. 

I should have responded to this a month ago. My apologies for having missed it.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
