### ISSUE TITLE
The OSS install instructions don't mention wintun.dll and it's not part of the release package

### ISSUE THREAD

**Issue by garrmark** [telepresenceio/telepresence#3268]
**Describe the bug**
following https://www.getambassador.io/docs/telepresence-oss/latest/install doesn't work since wintun.dll is missing and isn't mentioned in the instuctions

**To Reproduce**
download exe from github
run telepresence helm install
run telepresence connect

see error

telepresence connect: error: connector.Connect: NewTunnelVIF: failed to create TUN device: Error creating interface: Error loading wintun.dll DLL: Unable to load library: The specified module could not be found.

**Expected behavior**
connect properly

**Versions (please complete the following information):**
OSS Client     : v2.14.1
OSS Root Daemon: v2.14.1
OSS User Daemon: v2.14.1

Windows 11 Pro

rke

**Comment by knlambert** [comment]
Thanks for reporting the issue. The OSS part of the doc is fairly new, we need to improve it :)

As a workaround, you can download the DLL [here ](https://www.wintun.net/builds/wintun-0.14.1.zip)and extract it in the same folder than the telepresence binary :)

**Comment by knlambert** [comment]
Should be available with Telepresence 2.15.0 :)
