### ISSUE TITLE
docs bug:  client.routing.allowConflictingSubnets missing from helm chart README

### ISSUE THREAD

**Issue by drewfish** [telepresenceio/telepresence#3270]
**Describe the bug**
In the README for the `telepresence` chart, I don't see a reference to the `client.routing.allowConflictingSubnets`. I do see it in `values.yaml` and also on this [Telepresence and VPNs](https://www.getambassador.io/docs/telepresence/latest/reference/vpn) page.

https://github.com/telepresenceio/telepresence/blob/v2.14.1/charts/telepresence/README.md

**Versions (please complete the following information):**
- Output of `telepresence version`
  - Client         : v2.14.1
  - Root Daemon    : v2.14.1
  - User Daemon    : v2.14.1
  - Traffic Manager: v2.14.1
- Operating system of workstation running `telepresence` commands
- Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
  - AWS EKS, with kubernetes version 1.23

**VPN-related bugs:**
no VPN

**Comment by cindymullins-dw** [comment]
@drewfish , thanks for the catch.  We’ll update the README.
