### ISSUE TITLE
Traffic agent looking for datawire/tel2:latest which doesn't exist

### ISSUE THREAD

**Issue by garrmark** [telepresenceio/telepresence#3271]
**Describe the bug**
traffic manager 2.14.1 is trying to inject agent pods with:
image: docker.io/datawire/tel2:latest

that image doesn't exist, so it fails until I change it to:
docker.io/datawire/tel2:2.14.1

**To Reproduce**
1. intercept a service
2. See failure to pull the agent pod 

**Expected behavior**
pod runs properly

**Versions (please complete the following information):**
OSS Client         : v2.14.1
OSS Root Daemon    : v2.14.1
OSS User Daemon    : v2.14.1
OSS Traffic Manager: v2.14.1

**Comment by garrmark** [comment]
![image](https://github.com/telepresenceio/telepresence/assets/2669864/3df60a47-82b3-4e49-8c51-941222eedd5b)

Looks like the version isn't passed corrctly when doing:
telepresence helm install

**Comment by garrmark** [comment]
the workaround is:

`telepresence helm install --set agent.image.tag=2.14.1,agent.image.name=tel2`

**Comment by cindymullins-dw** [comment]
Thank, @garrmark , for raising this as an issue.

**Comment by knlambert** [comment]
Fixed with Telepresence 2.14.2
