### ISSUE TITLE
Couldn't intercet sevices with telepresence 

### ISSUE THREAD

**Issue by asoleimanibo** [telepresenceio/telepresence#3277]
I want to intercet services on a Kubernetes cluster via Telepresence but there is an error:
`telepresence intercept: error: rpc error: code = Unimplemented desc =`
This version of Telepresence is intalled:
```
$ telepresence version
Client             : v2.14.1
Root Daemon        : v2.14.1
User Daemon        : v2.14.1
OSS Traffic Manager: v2.14.1
```
This the output of `status` command:
```
$ telepresence status
User Daemon: Running
  Version           : v2.14.1
  Executable        : C:\Program Files (x86)\Ambassador\Telepresence\telepresence.exe
  Install ID        : 752c629f-60fe-49d6-b4a1-94d063a7ecee
  Status            : Connected
  Kubernetes server : https://apiserver:6443
  Kubernetes context: kubernetes-admin@kubernetes
  Manager namespace : ambassador
  Intercepts        : 0 total
Root Daemon: Running
  Version    : v2.14.1
  Version    : v2.14.1
  DNS        :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - 192.168.166.241/32
Ambassador Cloud:
  Status      : Logged out
OSS Traffic Manager: Connected
  Version : v2.14.1
Intercept Spec: Not running
```
When I try to intercept a service I faced with this issue:
```
telepresence intercept servicetest --port 8088:8088 --namespace dev
telepresence intercept: error: rpc error: code = Unimplemented desc =
```
The applicarion is runnig locally on `8088` port.

**Comment by knlambert** [comment]
Hi,

Your cluster is using the OSS version of the traffic manager, but your command line is the pro version. 

The OSS cli can work with a pro traffic-manager, but a pro cli won't run properly with an OSS traffic manager since some endpoints are missing.

**Comment by asoleimanibo** [comment]
@knlambert 
Thank you. I will change my client release. But now I have another error when I try to run OSS trafic manager into my cluster.
```
2023-07-26 06:25:11.6092 info    OSS Traffic Manager v2.14.0 [uid:1000,gid:0]
2023-07-26 06:25:11.6096 error   quit: failed to LoadEnv: 3 errors:
 1. invalid InterceptDisableGlobal (aborting): is not set
 2. invalid AgentEnvoyServerPort (aborting): is not set
 3. invalid AgentEnvoyAdminPort (aborting): is not set
```
What should I do? I deployed the traffic manager from [here](https://github.com/telepresenceio/telepresence/tree/release/v2/charts/telepresence).

**Comment by knlambert** [comment]
This is version 2.14.0, you have the 2.14.2 which should be available.

What is the exact helm command that you used ? Did you try using the `telepresence helm install` command too ?

**Comment by cindymullins-dw** [comment]
Closing for lack of response.  Please let us know if assistance is needed.
