### ISSUE TITLE
Telepresence crashes when pod is not available

### ISSUE THREAD

**Issue by richarddli** [telepresenceio/telepresence#332]
### What were you trying to do?

Use Telepresence with --run-docker and --swap-deployment.

### What did you expect to happen?

An error message saying that the pod could not be found. (My deployment got horked, so the pod never started, which is why Telepresence crashed).

```
lost-cause:blackbird richard$ kubectl get pods
NAME                       READY     STATUS    RESTARTS   AGE
busybox-2098674512-9r5w7   1/1       Running   1          1h
lost-cause:blackbird richard$ kubectl get deploy
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
busybox   1         1         1            1           1h
qotm      1         0         0            0           2m
```

### What happened instead?

Telepresence crashed.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'qotm', '--docker-run', '--rm', '-it', '-v', '/tmp/qotm:/service', 'qotm-dev:latest']`
Version: `0.68`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.7.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin lost-cause.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2370, in go
    runner, args
  File "/usr/local/bin/telepresence", line 1533, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence", line 906, in get_remote_info
    format(deployment_name)
RuntimeError: Telepresence pod not found for Deployment 'qotm'.

```

Logs:

```
 {'pod-template-hash': '2098674512', 'run': 'busybox'} (phase Running)...
 121.4 TL | Labels don't match.
 121.4 TL | Checking {'app': 'qotm-dev-rdl-end-to-end', 'pod-template-hash': '3927315610'} (phase Running)...
 121.4 TL | Labels don't match.
 121.4 TL | Checking {'app': 'qotm-dev-rdl-end-to-end', 'pod-template-hash': '3927315610'} (phase Running)...
 121.4 TL | Labels don't match.
 122.4 TL | [102] Capturing: (['kubectl', '--context', 'gke_datawireio_us-east1-b_rdl-mini-cluster', '--namespace', 'default', 'get', 'pod', '-o', 'json', '--export'],)...
 122.6 TL | [102] captured.
 122.6 TL | Checking {'pod-template-hash': '2098674512', 'run': 'busybox'} (phase Running)...
 122.6 TL | Labels don't match.
 122.6 TL | Checking {'app': 'qotm-dev-rdl-end-to-end', 'pod-template-hash': '3927315610'} (phase Running)...
 122.6 TL | Labels don't match.
 122.6 TL | Checking {'app': 'qotm-dev-rdl-end-to-end', 'pod-template-hash': '3927315610'} (phase Running)...
 122.6 TL | Labels don't match.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
