### ISSUE TITLE
No Connection could be made with Root Daemon to K8s

### ISSUE THREAD

**Issue by LubSve** [telepresenceio/telepresence#3321]
Hello!

We've been trying hard to solve an issue with a newly setup Win10 Dev machine, where we've got Docker Desktop with Kubernetes running. The Issue is that, when executing _telepresence connect_, we get the following 
![image](https://github.com/telepresenceio/telepresence/assets/143066249/cf5a91da-26fa-47ce-9fc2-0955b9dac0d8)

In the Connector logs we get the following
![image](https://github.com/telepresenceio/telepresence/assets/143066249/d5518fa1-9938-4ce1-be99-ba8ae9443acc)

In the Daemon logs we get this
![image](https://github.com/telepresenceio/telepresence/assets/143066249/abd991c7-726f-4a72-9cfd-426541793acf)

If we delete the file specified in the Daemon Logs entry, we same issue still occurs, but without the _error socket_ entry in the Daemon logs.
Additionally, we do not know if this influences the issue, but the rootd.socket in the Daemon log entry is actually situated in the admin accounts AppData, not in the normal Users AppData.

Additional Information: We've got a complete environment running in K8s locally, which we can access, as well as control with kubectl commands.

**Comment by thallgren** [comment]
From the looks of it, you must have once started Telepresence once as an admin user, and then as a normal user.
Try `telepresence quit -s`. That should quit any processes that are running. To be sure, check if there are any telepresence processes still running, and if so, kill them. Then start telepresence as a normal user.

**Comment by LubSve** [comment]
@thallgren Thank you for your input.
We've tried it with same result. Interestingly, when we tried the following now, it worked. 

1. Copied .kube folder from normal User to Admin User.
2. We've started PowerShell as administrator.
3. Run Telepresence helm install
4. Could connect finally intercept service.

**Comment by thallgren** [comment]
In general, you should never use an admin account when running Telepresence, because it will make caches and configs end up under that account.

**Comment by cindymullins-dw** [comment]
Can you try cleaning up the files under AppData like the below:
[\\AppData\\Local\\telepresence\\rootd.socket

We've found with other users that if you install Telepresence as an admin user, that establishes admin privileges and then you have to access w/ those admin privileges as well.  You can either try removing anything that appears under those folders or uninstall and start over as a non-admin user.
