### ISSUE TITLE
Cannot run teleresence on a Kind cluster on windows

### ISSUE THREAD

**Issue by dragon74** [telepresenceio/telepresence#3333]
Using latest versions of Telepresence and docker. Kubernetis 1.27.
Getting the errors in the log at all stages ...
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/12497393/telepresence_logs.zip)

**Comment by cindymullins-dw** [comment]
Hi @dragon74, are you using Docker Desktop or are you running Telepresence in [Docker mode](https://www.getambassador.io/docs/telepresence/latest/docker/cli#:~:text=Telepresence%20Docker%20Mode%20enables%20you,admin%20access%20on%20their%20machines.)?

**Comment by thallgren** [comment]
I see this in the traffic-manager log:
```
2023-09-01 11:27:48.4395 info    agent-injector/conn=10.244.3.4:443 : Pod calcdep-77f77db4b5-.default already has container traffic-agent and it isn't modified
```
so from the looks of it, you have intercepted a pod in this cluster before and have some success connecting to it. Can you please tell us more about what happened that made things break?

**Comment by cindymullins-dw** [comment]
Please reopen with additional details if issues persist.
