### ISSUE TITLE
Add namespace flag to connect or intercept

### ISSUE THREAD

**Issue by dennis-rall** [telepresenceio/telepresence#3340]
I have a service A and a service B running in a namespace N. When they are running in the cluster, it is enough to use A as the host url, because the DNS lookup in kubernetes adds the namespace of the requester to it automatically, so it searches for A.N.svc.cluster.local.

But when I intercept the service B, I have to change the host url to A.N, because the service is no longer running in the namespace N.

Is there a workaround for this or is it possible to add a namespace attribute to the connect method, so that one can connect to a specific namespace?

(Permanently changing the host url to A.N is not an option, because I have multiple instances of A and B running in different namespaces and only want to communicate with the services in the same namespace)

**Comment by cindymullins-dw** [comment]
Hi @dennisrall ,  can you clarify which service is no longer running in namespace N?  And 'no longer running' means the Service is terminated or just that you're not connecting to it?  You should be able to access either of those services [in the same namespace](https://www.getambassador.io/docs/telepresence/latest/reference/dns) once you make an intercept.

**Comment by dennis-rall** [comment]
Hi @cindymullins-dw thanks for your response. The link you provided was exactly what I was looking for.

Sadly it doesn't work. That's what I did:
1. set-up the quick-start cluster
2. `telepresence connect`
3. `telepresence intercept dataprocessingservice --port 3000`

When I am understanding the documentation correctly, after intercepting `curl verylargedatastore:8080` should work. However it returns `curl: (6) Could not resolve host: verylargedatastore`. `curl verylargedatastore.default:8080` seems to be working as it returns `{"timestamp":"2023-09-13T07:51:50.244+00:00","status":404,"error":"Not Found","message":"","path":"/"}`

I am running telepresence version v2.15.0

**Comment by thallgren** [comment]
@dennisrall the behavior with respect to connections and namespaces will soon change. Please see the linked PR for more info.

**Comment by dennis-rall** [comment]
Ah thanks for your response, then I'll wait for the next release :)
