### ISSUE TITLE
`telepresence list` hangs -- failed to list *v1.Service

### ISSUE THREAD

**Issue by hylowaker** [telepresenceio/telepresence#3344]
### Describe the bug

Running `telepresence list` hangs, then I see lots of **failed to list \*v1.Service** errors in the log.

```
➜  ~ telepresence version               
OSS Client : v2.15.1
Root Daemon: not running
User Daemon: not running

➜  ~ telepresence loglevel trace        
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
Connected to context prem++ (https://master.my.kube.cluster.domain)

➜  ~ curl -ik https://kubernetes.default
HTTP/2 403 
audit-id: 3f193940-27d6-481a-b784-94d9df43b3c9
cache-control: no-cache, private
content-type: application/json
x-content-type-options: nosniff
x-kubernetes-pf-flowschema-uid: 99230206-8f93-4993-898a-d916e2324c96
x-kubernetes-pf-prioritylevel-uid: a6a28336-1768-4fbf-934c-8da50e18ab6a
content-length: 217
date: Mon, 11 Sep 2023 06:55:13 GMT

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}%                                                                                                                                                                                               

➜  ~ telepresence list    # This hangs! 😫
^C

➜  ~ telepresence gather-logs 
Logs have been exported to /Users/jaeheunghan/telepresence_logs.zip

➜  ~ telepresence quit -s
Telepresence Daemons quitting...telepresence quit: error: error when quitting connector: timeout while waiting for user daemon to exit

See logs for details (1 error found): "/Users/jaeheunghan/Library/Logs/telepresence/daemon.log"
See logs for details (17 errors found): "/Users/jaeheunghan/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

### Logs

[connector.log](https://github.com/telepresenceio/telepresence/files/12573295/connector.log)

[daemon.log](https://github.com/telepresenceio/telepresence/files/12573361/daemon.log)

(Cluster domain name `my.kube.cluster.domain` is different from real one. Some logs are intentionally redacted.)

### Versions
 - OS: macOS 13.5.2
 - Telepresence: 2.15.1
 - Kubernetes: 1.25.6
 - Kubernetes environment: Bare metal (deployed by Kubespray)

**Comment by cindymullins-dw** [comment]
Hi @hylowaker , so the daemons not running and the error on telepresence quit suggests Telepresence did not connect properly.  Can you try [disconnecting](https://www.notion.so/datawire/Telepresence-commands-are-hanging-072b78fa62a84adfb450d7011f45e2bb) manually?

Then try `telepresence connect `and `telepresence list `again.

**Comment by thallgren** [comment]
The server is at host `https://master.my.kube.cluster.domain`. That's a bit odd given that your cluster domain name is `my.kube.cluster.domain`. It's like you assume that the your cluster is available from DNS even before Telepresence connects to it. Maybe that's because you've made changes to the log? In any case, it makes it a bit hard to see what the real problem is.

**Comment by hylowaker** [comment]
@thallgren You are right. I have a proxy in front of the API servers, and there is a DNS record `master.my.kube.cluster.domain` for that proxy.

I changed the context so that the client connects directly to the API server instead of connecting through the proxy. Now It's working.

**Comment by thallgren** [comment]
Closing this as resolved.
