### ISSUE TITLE
Cannot close popup and cannot uninstall telepresence

### ISSUE THREAD

**Issue by saicharanp** [telepresenceio/telepresence#3347]
**Describe the bug**

I have 15 days left on my trail period. An ugly popup keeps coming on to my screen and I cannot close it until I click "Upgrade plan". This is extremely annoying and a clear sign of a shitty product trying to enforce stuff.

<img width="568" alt="Screenshot 2023-09-15 at 7 08 27 AM" src="https://github.com/telepresenceio/telepresence/assets/4889980/da4a5606-350e-4fbf-8384-d252b89ebb81">

Also running `telepresence uninstall --all-agents` gives me the following error 
```
telepresence uninstall: error: connector.Connect: initial cluster check failed: the server has asked for the client to provide credentials
```

Can you please tell me how to get rid of this software on my laptop?

**Comment by thallgren** [comment]
Try `telepresence helm uninstall` and `telepresence logout`. Then remove the installed binary.

**Comment by thallgren** [comment]
Then, if you don't want "shittyness" (i.e. us trying to make a living), you can try installing the [open source version](https://www.telepresence.io/) instead.
