### ISSUE TITLE
Multiple/inconsistent release binaries for same os/arch

### ISSUE THREAD

**Issue by jessesuen** [telepresenceio/telepresence#3357]
**Describe the bug**

On the releases page, there are two different download URLs to download the OSS telepresence binary for the same os/arch (darwin/amd64 in my example):
* https://app.getambassador.io/download/tel2oss/releases/download/v2.15.1/telepresence-darwin-arm64
* https://github.com/telepresenceio/telepresence/releases/download/v2.15.1/telepresence-darwin-arm64

<img width="939" alt="image" src="https://github.com/telepresenceio/telepresence/assets/12677113/04b7e182-2f12-46e1-aae0-e7743bb95ad8">

It turns out that they have different file sizes:
```
$ ls -l telepresence-github*
-rwxr-xr-x  1 jesse  wheel  105299346 Sep 27 13:47 telepresence-github
-rwxr-xr-x  1 jesse  wheel  109252208 Sep 27 13:36 telepresence-github2
```

**Expected behavior**

I'm confused about which version is the correct one to use, and what differences exist between the two binaries. Is there a difference? If not, I suggest that the same binary be uploaded to both locations to avoid confusion.

**Versions (please complete the following information):**

 - Output of `telepresence version`

The output is the same for both binaries:

```
$ ./telepresence-github version
OSS Client     : v2.15.1
Root Daemon    : v2.15.1
User Daemon    : v2.15.1
Traffic Manager: not connected

$ ./telepresence-github2 version
OSS Client     : v2.15.1
Root Daemon    : v2.15.1
User Daemon    : v2.15.1
Traffic Manager: not connected
```

 - Operating system of workstation running `telepresence` commands

darwin/amd64

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

N/A

**Additional context**

**Comment by thallgren** [comment]
I only see one binary per arch. One is for amd64 (the Intel chip), the other for arm64 (Silicon chip). Both are likely to function on a macOS with amd64 due to arm64 emulation.

**Comment by jessesuen** [comment]
Hmm, I just re-downloaded them again and the filesize/checksum matches between the URLs:
* https://app.getambassador.io/download/tel2oss/releases/download/v2.15.1/telepresence-darwin-arm64
* https://github.com/telepresenceio/telepresence/releases/download/v2.15.1/telepresence-darwin-arm64

I must have misclicked the first time. Sorry for the noise!
