### ISSUE TITLE
Cannot install traffic manager

### ISSUE THREAD

**Issue by hosseio** [telepresenceio/telepresence#3373]
Telepresence version
```
$ telepresence version
Launching Telepresence Root Daemon
OSS Client     : v2.15.1
OSS Root Daemon: v2.15.1
OSS User Daemon: v2.15.1
Traffic Manager: not connected
```
Installation in my cluster (where I have cluster admin role)
```
$ telepresence helm install
telepresence helm install: error: failed to install traffic manager: failed to clean up leftover release history: uninstall: Release not loaded: ambassador: release: not found
```
Not sure what is going on. I would appreciate any help.

Maybe related to this, from a while, which is closed https://github.com/telepresenceio/telepresence/issues/3192

**Comment by knlambert** [comment]
Do you have any leftover in the ambassador namespace ? When I run into an helm issue like that usually, just uninstalling it fixes the issue.

So can you run `telepresence helm uninstall`, and if doesn't help, do you see secrets in your namespace which could refer to a broken helm release ? Like : 

```cli
➜  telepresence-pro git:(thallgren/metriton-annotations) ✗ k get secrets
NAME                                    TYPE                 DATA   AGE
mutator-webhook-tls                     Opaque               3      42s
sh.helm.release.v1.traffic-manager.v1   helm.sh/release.v1   1      42s
```

I would delete the release secrets to see if it helps.

**Comment by hosseio** [comment]
@knlambert I much appreciate your help. That did the trick, thank you

**Comment by mby-maofeiyu** [comment]
why can't  find the image from docker hub , i search in the docker ,nothing,only extension    
Error from server (BadRequest): container "traffic-manager" in pod "traffic-manager-7d4c58498-hjzfn" is waiting to start: trying and failing to pull image
