### ISSUE TITLE
Removal of `upgrade-legacy` helm hook from chart

### ISSUE THREAD

**Issue by Piroddi** [telepresenceio/telepresence#3393]
The current helm chart runs a helm hook job called `upgrade-legacy`. 

The purpose of this hook is to fix deployments that were affected by telepresence versions prior to 2.6.0. 
Since versions < 2.6.0 are no longer supported, this hook can be removed.

**Comment by cindymullins-dw** [comment]
Thanks, @Piroddi for the contribution!
