### ISSUE TITLE
"DNS doesn't seem to work properly"  error when telepresence connect

### ISSUE THREAD

**Issue by lillyqian** [telepresenceio/telepresence#3414]
**To Reproduce**
1. When I run "telepresence connect"
2. I see 'DNS doesn't seem to work properly' warning
3. Then  I run  'telepresence connect -n default'
4. I see
telepresence connect: error: connector.Connect: Cluster configuration changed, please quit telepresence and reconnect 
See logs for details (49 errors found): "C:\\Users\\..\\AppData\\Local\\telepresence\\logs\\daemon.log"
See logs for details (51 errors found): "C:\\Users\\..\\AppData\\Local\\telepresence\\logs\\connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
5. I run "telepresence gather-logs"
6. please see attached log file for details 
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/13242131/telepresence_logs.zip)

**Expected behavior**

**Versions (please complete the following information):**
 - Output of `telepresence version`:  v2.16.1
 - Operating system of workstation running `telepresence` commands: Windows 11 Enterprise
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, 
telepresence test-vpn
telepresence test-vpn: error: the test-vpn command is deprecated. Please see https://www.getambassador.io/docs/telepresence/latest/reference/vpn to learn how to configure telepresence for your VPN.

and the following information:
 - Which VPN client are you using? Cisco Secure Client

 - Which VPN server are you using?
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf

**Additional context**
telepresence status
User Daemon: Running
  Version           : v2.16.1
  Executable        : C:\Program Files (x86)\Ambassador\Telepresence\telepresence.exe
  Install ID        : f2a35f3b-8894-4062-8822-8804b5238926
  Status            : Not connected
  Kubernetes server :
  Kubernetes context:
  Connection name   :
  Namespace         :
  Manager namespace :
  Intercepts        : 0 total
Root Daemon: Running
  Version: v2.16.1
  Version: v2.16.1
Ambassador Cloud:
  Status      : Logged in
  User ID     : XXXX
  Account ID  : YYYYY
  User Name   : Lilly
  Email       : xxxx@somemail.com
  Account Name: Lilly
  Plan        : Free Trial
Traffic Manager: Not connected
Intercept Spec: Not running

**Comment by cindymullins-dw** [comment]
Hi @lillyqian, can you try running `telepresence quit -s`, then try connecting again to the namespace you want? It might have failed /flaked the first time, it'd be useful to confirm if the error persists.

**Comment by lillyqian** [comment]
Hi Cindy,
I tried and got the same error. I also tried telepresence helm uninstall and telepresence helm install.

**Comment by thallgren** [comment]
The connect error is correct (but the text in the error message could certainly be improved). If you switch namespace, then you need to quit the current session.
The "DNS does not seem to work properly" warning is common on Windows. In many cases everything works as expected despite this warning.

Are you seeing any problems with normal operation besides this?

**Comment by lillyqian** [comment]
If I ignore the "DNS doesn't seem to work properly" and do a telepresence intercept, I get the following error:

>telepresence connect -n default
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
Connected to context simk8slily, namespace default (https://simk8slily-d4bc2e5b.hcp.eastus.azmk8s.io:443)
Warning: DNS doesn't seem to work properly

>telepresence intercept sas-sim-client --port 8000:80 --env-file "C:\telepresence\env\myapp\client.env"
Warning: DNS doesn't seem to work properly
telepresence intercept: error: workload "sas-sim-client.default" not found

**Comment by lillyqian** [comment]
It seems if I use
telepresence connect -n simk8slily
instead of
telepresence connect -n default
everything works fine, even the "DNS does not seem to work properly" warning still shows up.

Thank you all for the help!

**Comment by mausch** [comment]
I'm having the same issue on Windows 10.0.19045. Changing the namespace doesn't help. Using Tailscale (not sure if that makes any difference).
I get the "DNS does not seem to work properly" warning and and I can't resolve anything in svc.cluster.local.
I already tried `ipconfig /flushdns` after connecting.

**Comment by cindymullins-dw** [comment]
It looks like Tailscale shouldn't be the problem here, closing 3414 as resolved.  Issue opened by @mausch is [#3439] which is ongoing. (https://github.com/telepresenceio/telepresence/issues/3439).
