### ISSUE TITLE
Panic on slice bounds out of range

### ISSUE THREAD

**Issue by mausch** [telepresenceio/telepresence#3418]
**Describe the bug**

Same as https://github.com/telepresenceio/telepresence/issues/3015 . 
Though this is in the agent pod so maybe the same bug needs fixing there now?

logs:

```
panic: runtime error: slice bounds out of range [23:9]
goroutine 1 [running]:
github.com/datawire/ambassador-agent/pkg/agent.NewAgent({0x22664b8, 0xc000680810}, {0x0?, 0x0?}, 0x2088ed0?, 0x2088ed8?, 0xc0004203c0)
 github.com/datawire/ambassador-agent/pkg/agent/agent.go:145 +0x66b
main.main()
 ./main.go:51 +0x427
```

Just as described in https://github.com/telepresenceio/telepresence/issues/3015 this is on a vcluster. I tried a few recent versions and they all crashed with that same stacktrace: 2.16.1, 2.15.1, 2.14.4
Ultimately I installed 2.10.4 just as mentioned in that original issue which doesn't crash at startup.

kubernetes version: v1.28.2+k3s1

**Comment by thallgren** [comment]
What makes you think that this is the same as #3015? I don't see any similarities. This panic is in a different binary.

**Comment by mausch** [comment]
The similarities are:

- Both errors happen on vclusters
- In both cases we've had to go back to 2.10.4 to get things to work.

**Comment by thallgren** [comment]
The failing ambassador-agent is not crucial for the operation of Telepresence. It just reports information about your services to the Ambassador Cloud. You can try installing the traffic-manager without the ambassador agent:
```
telepresence helm install --set ambassador-agent.enabled=false
```
or upgrade it:
```
telepresence helm upgrade --set ambassador-agent.enabled=false
```

**Comment by alextricity25** [comment]
> The failing ambassador-agent is not crucial for the operation of Telepresence. It just reports information about your services to the Ambassador Cloud. You can try installing the traffic-manager without the ambassador agent:
> 
> ```
> telepresence helm install --set ambassador-agent.enabled=false
> ```
> 
> or upgrade it:
> 
> ```
> telepresence helm upgrade --set ambassador-agent.enabled=false
> ```

@thallgren Is there anyway to do this through the values.yaml file? We install telepresence through helm directly and would like to disable the ambassador-agent since it's failing with this error on our vcluster.

**Comment by alextricity25** [comment]
For anyone wondering how to disable the ambassador-agent with `values.yaml`:
```
  values: {
    'ambassador-agent': {
      replicaCount: 0,
    },
  },
```
