### ISSUE TITLE
`telepresence connect` in Codespaces breaks all DNS

### ISSUE THREAD

**Issue by mausch** [telepresenceio/telepresence#3439]
**Describe the bug**
From a [Codespaces](https://github.com/features/codespaces) terminal run `telepresence connect`.
It prints out the usual successful messages:

```
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
Connected to context something (https://something)
```

After that no hostnames can be resolved, not even localhost:

```
$ nslookup localhost
;; communications error to 100.100.100.100#53: timed out
;; communications error to 100.100.100.100#53: timed out
;; communications error to 100.100.100.100#53: timed out
;; no servers could be reached
```

Running `telepresence quit -s` restores normal behaviour.

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
$ telepresence version
OSS Client             : v2.15.1
OSS Root Daemon        : v2.15.1
OSS Daemon in container: v2.15.1
Traffic Manager        : v2.10.4
```

(I'm running Traffic Manager 2.10.4 due to https://github.com/telepresenceio/telepresence/issues/3418 )

 - Operating system of workstation running `telepresence` commands
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
Kubernetes 1.28 on vcluster on EKS.

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:

```
$ telepresence test-vpn
telepresence test-vpn: error: the test-vpn command is deprecated. Please see https://www.getambassador.io/docs/telepresence/latest/reference/vpn to learn how to configure telepresence for your VPN.
```

 - Which VPN client are you using?
 - Which VPN server are you using?

I'm using Tailscale, though Tailscale+Telepresence works fine on my Ubuntu box.

 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf

```
$ cat /etc/resolv.conf 
# resolv.conf(5) file generated by tailscale
# For more info, see https://tailscale.com/s/resolvconf-overwrite
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search elevate.develop.internal elevate.direct elevate.internal amazonaws.com lweooo02fg0efcrf5g0nbghaqb.zx.internal.cloudapp.net
```

I noticed that unlike my Ubuntu box this doesn't say include `tel2-search.cluster.local` in the `search` line.

**Additional context**

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/13474076/telepresence_logs.zip)

Just noticed that this same issue happens on a NixOS box.
As I said above it works fine on Ubuntu.

Many thanks 🙂

**Comment by cindymullins-dw** [comment]
Hi @mausch , I notice that your Traffic Manager is several versions behind your Telepresence client, so we'd recommend updating that.  Telepresence will add DNS entries on ‘telepresence connect’ so there may be an issue with integration with Codespaces.  Is this your primary dev environment?

**Comment by mausch** [comment]
I can't update Traffic Manager due to https://github.com/telepresenceio/telepresence/issues/3418

**Comment by mausch** [comment]
I upgraded Traffic Manager to v2.17.1 (without agent). Issue is still present.

**Comment by thallgren** [comment]
I tried just creating a codespace using this repository, then a `make build` followed by a `build-output/bin/telepresence connect`. It works like a charm, DNS and all.

Some differences that can be noted, the latter especially:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
```

```
$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.53
search knfuj350pqxujjpph1jr1pqtmc.ax.internal.cloudapp.net
options timeout:1 attempts:5
nameserver 168.63.129.16
```

**Comment by mausch** [comment]
Thanks for looking into this.

Sounds like tailscale and telepresence are not playing nice with each other?

For reference here's my devcontainer.json:

```
{
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu-22.04",
  "features": {
    "ghcr.io/tailscale/codespace/tailscale": {},
  },

  // Configure tool-specific properties.
  "customizations": {
    // Configure properties specific to VS Code.
    "vscode": {
      "settings": {
        "editor.fontFamily": "'Andale Mono', 'monospace', monospace"
      },
      "extensions": [
      ]
    }
  },
  "forwardPorts": [],
  "privileged": true,
  "runArgs": ["--device=/dev/net/tun"]
}
```

**Comment by thallgren** [comment]
I have been using Tailscale and telepresence together without problems, so them not playing nice together is not a general fact, but maybe you run into some corner case when using Tailscale with Codespaces that Telepresence is unable to handle. How do you configure with respect to DNS?

**Comment by thallgren** [comment]
Closing this due to lack of more info.

**Comment by surajstaabi** [comment]
Any updates on this issue?
