### ISSUE TITLE
`telepresence connect --docker`: container dies in 10 seconds

### ISSUE THREAD

**Issue by mausch** [telepresenceio/telepresence#3440]
**Describe the bug**

Following the description in https://www.getambassador.io/docs/telepresence/latest/reference/inside-container I run `telepresence connect --docker`.

Output is:

```
Connected to context my-context (https://some-context)
```

However the docker container `tp-my-context` dies in 10 seconds and gets deleted automatically.
I ran `docker logs tp-my-context` within those 10 seconds and got not output.

[telepresence-logs.zip](https://github.com/telepresenceio/telepresence/files/13477238/telepresence-logs.zip)

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
$ telepresence version
OSS Client             : v2.15.1
OSS Root Daemon        : v2.15.1
OSS Daemon in container: v2.15.1
Traffic Manager        : v2.10.4
```
 - Operating system of workstation running `telepresence` commands
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

on bare metal.

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
Kubernetes 1.28 on vcluster on EKS.

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
 - Which VPN client are you using?
 - Which VPN server are you using?
Tailscale
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf
```
$ cat /etc/resolv.conf
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
search elevate.develop.internal elevate.direct elevate.internal amazonaws.com cust.communityfibre.co.uk communityfibre.co.uk
```

**Additional context**

`telepresence connect` works fine on this box.

**Comment by thallgren** [comment]
This is due to a mismatch between the CLI and the docker container. The CLI is OSS (and hence does not start a cloud-daemon) but the container that it uses is PRO, and expects such a container. I'd recommend using version 2.17.0 where this problem has been fixed.
