### ISSUE TITLE
Telepresence managerRbac not restricted to namespace scope

### ISSUE THREAD

**Issue by nishasati6oct** [telepresenceio/telepresence#3443]
**Describe the bug**
Recently I have installed telepresence OSS with latest helm chart and it is installed successfully via Flux kustomization (GitOps way) in AKS cluster. We are able to do the curl on internal kubernetes DNS URL's
My concern is that right now telepresence can access all the namespaces in our AKS cluster
I would like to restrict the access to certain namespaces
I tried with managerRbac section as below, but still telepresence can access all the other namespaces as well. What else I can do for namespace restriction?
 
managerRbac:
      create: true
      namespaced: true
      namespaces:
      - ambassador
      - ns1
      - ns2
      - ns3

We have used helm chart for the installation. Here is the helm values file:

apiVersion: [helm.toolkit.fluxcd.io/v2beta1](http://helm.toolkit.fluxcd.io/v2beta1)
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  chart:
    spec:
      chart: telepresence
      version: "2.17.0"
      sourceRef:
        kind: HelmRepository
        name: telepresence
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 10m0s
  values:
    ################################################################################
    ## Deployment Configuration
    ################################################################################
    image:
      registry: [docker.io/datawire](http://docker.io/datawire)
      name: tel2
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
    apiPort: 8081
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    nodeSelector:
      agentpool: systemnp
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    ################################################################################
    ## Traffic Manager Service Configuration
    ################################################################################
    service:
      type: ClusterIP
    ################################################################################
    ## Traffic Manager Configuration
    ################################################################################
    # The log level of the Traffic Manager.
    logLevel: info
    # GRPC configuration for the Traffic Manager.
    # This is identical to the grpc configuration for local clients.
    # See https://www.telepresence.io/docs/latest/reference/config/#grpc for more info
    grpc:
      # maxReceiveSize is a quantity that configures the maximum message size that the traffic
      # manager will service.
      maxReceiveSize: 4Mi
    managerRbac:
      # Default: true
      create: true
    ################################################################################
    ## Agent Injector Configuration
    ################################################################################
    agentInjector:
      name: agent-injector
      secret:
        name: mutator-webhook-tls
      certificate:
        regenerate: false
        # The method used to generate the TLS certificate for the agent-injector.
        #
        # Possible options: helm or certmanager
        #
        # Default: helm
        method: helm
        # The certmanager configuration block
        #
        certmanager:
          commonName: agent-injector
          duration: 2160h0m0s
          issuerRef:
            name: telepresence
            kind: Issuer
      injectPolicy: OnDemand
      webhook:
        name: agent-injector-webhook
        admissionReviewVersions: ["v1"]
        servicePath: /traffic-agent
        port: 443
        failurePolicy: Ignore
        reinvocationPolicy: IfNeeded
        sideEffects: None
        timeoutSeconds: 5
        namespaceSelector:
          matchExpressions:
            - key: [kubernetes.io/metadata.name](http://kubernetes.io/metadata.name)
              operator: NotIn
              values:
                - kube-system
                - kube-node-lease
      agentImage: {}
    ################################################################################
    ## Telepresence traffic-agent configuration
    ################################################################################
    agent:
      logLevel:
      resources: {}
      initResources: {}
      appProtocolStrategy: http2Probe
      port: 9900
      image:
        registry: [docker.io/datawire](http://docker.io/datawire)
        name:
        tag:
        pullSecrets: []
        pullPolicy: IfNotPresent
    ################################################################################
    ## Tracing configuration
    ################################################################################
    tracing:
      # The port on which a grpc server will be exposed for traces
      # To disable, set tracing to an empty object ("tracing: {}")
      grpcPort: 15766
    # Values specific to the helm chart hooks for managing upgrade/deleting
    hooks:
      busybox:
        registry: [docker.io](http://docker.io/)
        image: busybox
        tag: latest
        imagePullSecrets: []
      curl:
        registry: [docker.io](http://docker.io/)
        image: "curlimages/curl"
        tag: 8.1.1
        imagePullSecrets: []
    client:
      # Max time that the traffic-manager will keep a client connection alive when it doesn't receive
      # any calls to Remain.
      connectionTTL: 24h
      routing:
        allowConflictingSubnets: []
      dns:
        # Tell client's DNS resolver to never send names with these suffixes to the cluster side resolver
        excludeSuffixes: [".com", ".io", ".net", ".org", ".ru"]
    managerRbac:
      create: true
      namespaced: true
      namespaces:
      - ambassador
      - ns1
      - ns2
      - ns3 

**To Reproduce**
Steps to reproduce the behaviour:
1. When I run 'telepresence status'
2. I see  
OSS User Daemon: Running
  Version           : v2.16.1
  Executable        : /usr/local/bin/telepresence
  Install ID        : 079eb03c-1ab1-4dad-9ed0-xxxxxxxxx
  Status            : Connected
  Kubernetes server : https://xxxxxxxx
  Kubernetes context: aks
  Connection name   : aks-admin-default
  Namespace         : default
  Manager namespace : ambassador
  Mapped namespaces : [ns1 ns2 ns3]
  Intercepts        : 0 total
OSS Root Daemon: Running
  Version    : v2.16.1
  Version    : v2.16.1
  DNS        : 
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - x.x.x.x/32

**Expected behaviour**
if i run curl on the above mapped namespaces kubernetes internal URL, it is working fine.
If i run curl on the other namespaces (like ns4) which is not mapped in managerRbac, then it should give me error which is not happening.

**Versions (please complete the following information):**
 - Output of `telepresence version`
OSS Client         : v2.16.1
OSS Root Daemon    : v2.16.1
OSS User Daemon    : v2.16.1
OSS Traffic Manager: v2.17.0 

 - Operating system of workstation running `telepresence` commands - macOS
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine] - AKS 1.26.6

**Additional context**

**Comment by thallgren** [comment]
When you say "can access", do you mean that you workstation is able to connect to services in other namespaces?

If so, then this is per design. When you connect with telepresence, you effectively give it the same network access as a pod in the namespace that you connect to. This is regardless of what namespaces telepresence is managing. You can restrict what namespaces a pod in another namespace can access using Kubernetes network policies.

A namespaced traffic manager ensures that you can intercept services in a restricted set of namespaces. It does not impose limitations on kubernetes networking.

**Comment by nishasati6oct** [comment]
You mean, if I add this in my helm file
managerRbac:
      create: true
      namespaced: true
      namespaces:
      - ambassador
      - ns1
      - ns2
Does it mean, I cannot create any intercept except for ns1 and ns2 but still can use curl for all the services in cluster?
  
I tested this in my cluster and seems like it works this way only (I cannot create any intercept except for ns1 and ns2 but still can use curl for all the services in cluster).

I have used these commands and able to create the intercept:
telepresence connect -n ns1
telepresence intercept ns1-svc --port 80 --env-file example-service-intercept.env 
Output:
Using Deployment analytics
   Intercept name        : analytics
   State                 : ACTIVE
   Workload kind         : Deployment
   Destination           : x.x.x.x:80
   Service Port Identifier: http
   Volume Mount Error    : sshfs is not installed on your local machine
   Intercepting          : all TCP connections

If I am trying to intercept the service (in ns4 namespace) which is not present in managerRBAC, then getting the below error.
telepresence connect -n ns4
telepresence intercept ns4-svc --port 80 --env-file example-service-intercept.env 
Output:
telepresence intercept: error: connector.CreateIntercept: deployments.apps "ns4-svc" is forbidden: User "system:serviceaccount:ambassador:traffic-manager" cannot get resource "deployments" in API group "apps" in the namespace "ns4": Azure does not have opinion for this user.

Please confirm.

**Comment by thallgren** [comment]
> Does it mean, I cannot create any intercept except for ns1 and ns2 but still can use curl for all the services in cluster?

Yes.

**Comment by nishasati6oct** [comment]
Thanks for the confirmation.
