### ISSUE TITLE
Can't intercept a service which appear this info

### ISSUE THREAD

**Issue by meo-father** [telepresenceio/telepresence#3444]
telepresence intercept admin --port 6010:6010
telepresence intercept: error: connector.CreateIntercept: intercepts are disabled because the traffic-manager is unable to determine what image to use for injected traffic-agents.

![image](https://github.com/telepresenceio/telepresence/assets/145689181/1021eb5b-5cf1-4f0f-948c-503129f160b5)
connector.log 

I used it on windows to connect to linux k8s

![image](https://github.com/telepresenceio/telepresence/assets/145689181/9e90bed3-3689-41d0-9eef-e2f26d2c8ee4)
connected to k8s already.

version 
![image](https://github.com/telepresenceio/telepresence/assets/145689181/5ef322b8-90d6-4d56-8266-50c783914965)

**Comment by thallgren** [comment]
From the looks of it, you are using the traffic-manager in an air-gapped cluster. This means that it is unable to query the Ambassador Cloud for the correct agent, so you must specify the agent as a Helm value when installing/upgrading the traffic-manager. Try something like:
```
telepresence helm install --set agent.image.name=ambassador-telepresence-agent,agent.image.tag=1.14.2,agent.image.registry=docker.io/datawire
```
In order to upgrade an existing cluster, just swap `install` for `upgrade`.

**Comment by meo-father** [comment]
> From the looks of it, you are using the traffic-manager in an air-gapped cluster. This means that it is unable to query the Ambassador Cloud for the correct agent, so you must specify the agent as a Helm value when installing/upgrading the traffic-manager. Try something like:
> 
> ```
> telepresence helm install --set agent.image.name=ambassador-telepresence-agent,agent.image.tag=1.14.2,agent.image.registry=docker.io/datawire
> ```
> 
> In order to upgrade an existing cluster, just swap `install` for `upgrade`.

I did.  I found the problem. its about the verison is different ..
