### ISSUE TITLE
IntelliJ/JetBrains plugin does not show "intercepts" window in run configuration for Rust or Rails projects

### ISSUE THREAD

**Issue by SimenB** [telepresenceio/telepresence#3445]
**Describe the bug**

For reference, this is the plugin I've installed: https://plugins.jetbrains.com/plugin/22844-telepresence, both into IDEA Ultimate (where I write Ruby on Rails) and RustRover (where I write Rust). The behavior is the same in both IDEs.

I correctly get the Telepresence tool window

<img width="505" alt="image" src="https://github.com/telepresenceio/telepresence/assets/1404810/40907ba0-f683-4c96-b27e-375859b57ed7">

And I can use this to set up intercepts - this works 👍 

However, when I try to use the run configuration shown in a gif on the plugin page, it does not appear for me (this is a screenshot from your docs, _not_ my machine)

![image](https://github.com/telepresenceio/telepresence/assets/1404810/446c0aae-4b1a-4646-a128-382a8c8c7e95)

I do get this if I create a run configuration of type "Application" (like shown in the screenshot), but not for .e.g. Rust or RoR projects.

<img width="1285" alt="image" src="https://github.com/telepresenceio/telepresence/assets/1404810/fa247f02-ace9-4fac-98aa-7b811d4cf1e1">

My current workaround is to run `telepresence intercept` on the command line using `--env`, and then copypasting the env output into the "Environment variables" builtin field. But I'd love to be able to skip that step and select an intercept right from the run configuration

**To Reproduce**
1. Install Telepresence plugin into a JetBrains IDE
2. See that the Telepresence tool window shows up and allows you to setup intercepts
3. Go to run configuration to select and intercept to use as basis for environment variables
4. It is nowhere to be seen

**Expected behavior**

I expect to see the tool window in run configurations

**Versions (please complete the following information):**

```sh-session
$ telepresence version
Client         : v2.17.1
Root Daemon    : v2.17.1
User Daemon    : v2.17.1
Traffic Manager: v2.17.0
```

macOS 14.1.1, arm64

Kubernetes is running in EKS

```sh-session
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.15-eks-4f4795d
```

**VPN-related bugs:**
 N/A

**Additional context**
I originally brought this up on your Slack, and was asked to file a bug report here 🙂

**Comment by thallgren** [comment]
What are the versions of your IDEs?
You specificly mention Rust and Rails. Have you seen this workin OK with other languages? I'm asking because the plug-in is supposed to be languag agnostic, so if that's working, then it might also point to some compatibility issues with different versions of the IDE.

**Comment by SimenB** [comment]
I only see the "intercept" section for "Application" run configuration (which is Java), I don't see it for any others (checked RoR, Rust and Node.js). I haven't _tried_ it though, as I don't have any Java projects

```
IntelliJ IDEA 2023.3 Beta (Ultimate Edition)
Build #IU-233.11799.67, built on November 22, 2023
```

```
RustRover 2023.3 EAP
Build #RR-233.10527.212, built on November 25, 2023
```

**Comment by Strayfe** [comment]
My findings align with @SimenB, this is affecting the adoption of this product for our typical workflow of **JetBrains Rider** and **dotnet** solutions.

For completeness, I have tested the following IDE's; ticked are those I have found the `intercepts` option to be available in at least one type of run/debug configuration:

| IDE |  |
|--------|--------|
| IntelliJ IDEA Ultimate | ✔ |
| IntelliJ IDEA Community | ✔ |
| GoLand | ✔ |
| WebStorm |  |
| PyCharm Professional |  | 
| PyCharm Community |  |
| CLion |  |
| CLion Nova |  |
| RustRover |  |
| PhpStorm |  |
| RubyMine |  |
| MPS |  |
| Rider |  |
