### ISSUE TITLE
`/consume-here` endpoint always returns `true` in the cluster

### ISSUE THREAD

**Issue by Strayfe** [telepresenceio/telepresence#3460]
# Description
It would appear that the `/consume-here` endpoint in the cluster always returns `true` regardless of there being any running intercepts.

# HTR
1. Create a new cluster (`minikube`, `kind`, `AKS`, etc.)
2. Clone the `emojivoto` repo: https://github.com/BuoyantIO/emojivoto
3. Apply the resources to the cluster `kubectl kustomize kustomize/deployment | kubectl apply -f -`
4. Install telepresence with the API enabled: `telepresence helm install --set telepresenceAPI.port=9980`
5. Connect to the cluster `telepresence connect --namespace emojivoto`
6. Start a global intercept `telepresence intercept web`
7. Curl the locally running API server, it responds accurately based on specified headers
8. Curl the API server in the cluster (from the pod) and it will always respond `true`

# Expectations
Based on the documentation, I would expect that when an intercept is detected by the `traffic-agent` in the cluster, the RESTful API will respond with `false` to the service running in the cluster when the proxy conditions of the intercept are met, i.e. matching headers.

# Versions
 - telepresence v2.17.0
 - fedora workstation 38
 - minikube v1.32.0
 - kind v0.17.0 go1.19.2 linux/amd64
 - Azure Kubernetes Services (AKS) 1.26.10

# Additional context
I have tested global and personal intercepts, providing and omitting the `x-telepresence-caller-intercept-id` headers, in 3 different clusters (`minikube`, `kind` and `AKS`).

Step 6 can be any kind of intercept: global, personal or an intercept specification, the outcome is the same.

## Local Machine (Working As Expected)

```shell
telepresence connect --namespace emojivoto

Launching Telepresence User Daemon
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /home/strayfe/.cache/telepresence/logs /home/strayfe/.config/telepresence
[sudo] password for strayfe: 
Connected to context kind-kind, namespace emojivoto (https://127.0.0.1:35669)
```

```shell
telepresence intercept web

Using Deployment web
   Intercept name         : web
   State                  : ACTIVE
   Workload kind          : Deployment
   Destination            : 127.0.0.1:8080
   Service Port Identifier: http
   Volume Mount Error     : sshfs is not installed on your local machine
   Intercepting           : all TCP requests
```

```shell
telepresence list --debug

emoji : ready to intercept (traffic-agent not yet installed)
voting: ready to intercept (traffic-agent not yet installed)
web   : intercepted
   Intercept name         : web
   State                  : ACTIVE
   Workload kind          : Deployment
   ID                     : 599c8f73-f297-4612-9b18-6325469a69c5:web
   Destination            : 127.0.0.1:8080
   Service Port Identifier: http
   Mechanism              : tcp
   Mechanism Command      : "all TCP requests"
   Metadata               : map[]
   Intercepting           : all TCP requests
```

```shell
curl -v 'localhost:9980/consume-here'

*   Trying 127.0.0.1:9980...
* Connected to localhost (127.0.0.1) port 9980 (#0)
> GET /consume-here HTTP/1.1
> Host: localhost:9980
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 20 Dec 2023 00:42:28 GMT
< Content-Length: 6
< 
false
* Connection #0 to host localhost left intact
```

```shell
curl -v 'localhost:9980/consume-here' -H 'x-telepresence-caller-intercept-id: 599c8f73-f297-4612-9b18-6325469a69c5:web'

*   Trying 127.0.0.1:9980...
* Connected to localhost (127.0.0.1) port 9980 (#0)
> GET /consume-here HTTP/1.1
> Host: localhost:9980
> User-Agent: curl/8.0.1
> Accept: */*
> x-telepresence-caller-intercept-id: 599c8f73-f297-4612-9b18-6325469a69c5:web
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 20 Dec 2023 00:42:46 GMT
< Content-Length: 5
< 
true
* Connection #0 to host localhost left intact
```

## Cluster Pod (Not Working)
```shell
root@web-7c49f45df4-q9mbz:/usr/local/bin# curl -v 'localhost:9980/consume-here'

*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x563c958fbf50)
* Expire in 200 ms for 4 (transfer 0x563c958fbf50)
* Connected to localhost (::1) port 9980 (#0)
> GET /consume-here HTTP/1.1
> Host: localhost:9980
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 20 Dec 2023 00:47:46 GMT
< Content-Length: 5
< 
true
* Connection #0 to host localhost left intact
```

```shell
root@web-7c49f45df4-q9mbz:/usr/local/bin# curl -v 'localhost:9980/consume-here' -H 'x-telepresence-caller-intercept-id: 599c8f73-f297-4612-9b18-6325469a69c5:web'

*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x559feb07bf50)
* Expire in 200 ms for 4 (transfer 0x559feb07bf50)
* Connected to localhost (::1) port 9980 (#0)
> GET /consume-here HTTP/1.1
> Host: localhost:9980
> User-Agent: curl/7.64.0
> Accept: */*
> x-telepresence-caller-intercept-id: 599c8f73-f297-4612-9b18-6325469a69c5:web
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 20 Dec 2023 00:48:52 GMT
< Content-Length: 5
< 
true
* Connection #0 to host localhost left intact
```

**Comment by Strayfe** [comment]
After some further testing, I can get the `/consume-here` endpoint in the cluster to return `false` in the following scenario:

- manually downgrade the agent sidecar to v1.14.0
`telepresence helm upgrade --set telepresenceAPI.port=9980,agent.image.name=ambassador-telepresence-agent,agent.image.tag=1.14.0`
- perform an intercept that proxies `HTTP requests with headers` instead of `all TCP requests`
`telepresence intercept web --http-header=x=y`

This indicates that patch versions of the agent sidecar of `1.14.1+` have changed in their logic for determining under which conditions the cluster should not consume a message.

Also, as a side note, it would appear that you cannot set the helm value for `agent.image.tag` independently of the `agent.image.name`.

**Comment by Strayfe** [comment]
After some further testing, I can get the `/consume-here` endpoint in the cluster to return `false` in the following scenario:

- manually downgrade the agent sidecar to v1.14.0
`telepresence helm upgrade --set telepresenceAPI.port=9980,agent.image.name=ambassador-telepresence-agent,agent.image.tag=1.14.0`
- perform an intercept that proxies `HTTP requests with headers` instead of `all TCP requests`
`telepresence intercept web --http-header=x=y`

This indicates that patch versions of the agent sidecar of `1.14.1+` have changed in their logic for determining under which conditions the cluster should not consume a message.

In addition, it seems it is not possible to return `false` for global intercepts in any of the versions I tested.

I tested versions: 
| Sidecar Version | Global Intercept | Header Intercept |
|--------|--------|--------|
| 1.14.3 |  |  |
| 1.14.2 |  |  |
| 1.14.1 |  |  |
| 1.14.0 |  | ✔ | 
| 1.13.22 |  | ✔ |

Also, is there not a mechanism that informs the `traffic-agent` or `agent` sidecar that the intercept has been left or terminated? 

I noticed during my testing, that after leaving an intercept or quitting telepresence entirely, the `/consume-here` endpoint in the cluster never seems to realise that the intercept is no longer running and always returns `false` because it thinks an intercept is still running.

_Also also, as a side note, it would appear that you cannot set the helm value for `agent.image.tag` independently of the `agent.image.name`, not a pressing matter but a bit of a nitpick._

**Comment by thallgren** [comment]
Thanks @Strayfe, for a very elaborate bug-report. I'll create a reproducer for this and investigate what's gone wrong.

> Also also, as a side note, it would appear that you cannot set the helm value for agent.image.tag independently of the agent.image.name, not a pressing matter but a bit of a nitpick.

Would you mind please create a separate ticket for this? It's easier to track that way.

**Comment by Strayfe** [comment]
> Would you mind please create a separate ticket for this? It's easier to track that way.

Roger that.

**Comment by thallgren** [comment]
I just pushed `datawire/ambassador-telepresence-agent:1.14.4-rc.0` that addresses this problem. Please give it a try.

**Comment by Strayfe** [comment]
Thank you, @thallgren, for looking at this so promptly.

> Please give it a try.

I would love to but my trial has expired and I have exhausted my connects for the month.
We are in the process of acquiring an enterprise license for our team but this may not occur now until the new year.

**Comment by thallgren** [comment]
I released 1.14.4 now. I ran through your HTR and it works OK.

**Comment by Strayfe** [comment]
That's great, thank you.
I apologise I have not had the time to test this, it is on my agenda for the next few days when I get a moment!

**Comment by Strayfe** [comment]
Just found a moment to test this, I am happy can confirm this is now working as expected.

**Comment by Strayfe** [comment]
I have just found a moment to test this and I am happy to confirm this is working as expected.
