### ISSUE TITLE
Bad appVersion in chart

### ISSUE THREAD

**Issue by guyguy333** [telepresenceio/telepresence#3482]
**Describe the bug**

Helm chart 2.18.0 https://artifacthub.io/packages/helm/datawire/telepresence/2.18.0 has an appVersion value equals to 2.18.0. appVersion is used as tag value if not defined. Thus, deployment tries to download datawire/tel2:2.18.0, which does not exist. Same issue with 2.18.1.

As far as I understand, appVersion is overwritten during CI according to https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/Chart.yaml

But I don't think it makes sense to sync chart version with appVersion. Sometimes you can deploy a chart fix without deploying a new version of the app. 

**To Reproduce**
1. Download chart (eg: 2.18.1) https://datawire-static-files.s3.amazonaws.com/charts/telepresence-2.18.1.tgz
2. Check Chart.yaml

**Expected behavior**

appVersion must always point to an existing app version.

**Comment by thallgren** [comment]
I think there's some confusion here. A 2.18.1 version does indeed exist, but only as an enterprise version. Things pointing to "datawire" is typically enterprise.
