### ISSUE TITLE
Failed to install on Debian Jessie

### ISSUE THREAD

**Issue by blak3mill3r** [telepresenceio/telepresence#349]
```bash
curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | sudo bash
sudo apt install --no-install-recommends telepresence
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package telepresence
```

The script did seem to add the repo correctly (as far as I can tell) under `/etc/apt/sources.list.d/` and fetched the package indexes. There just doesn't seem to be a package available called `telepresence`.

**Comment by blak3mill3r** [comment]
```bash# cat /var/lib/apt/lists/packagecloud.io_datawireio_telepresence_debian_dists_jessie_main_*
```

**Comment by ark3** [comment]
We should look at supporting Debian 8 (Jessie) onward, at least as far as what packages to install for Telepresence dependencies if installing from source. Recently we had a request for Debian 9 (Stretch) on Gitter.

**Comment by Dobiasd** [comment]
I'm having the same issue on Linux Mint 18.2, which is based on Ubuntu 16.04. Is there any workaround despite installing from source?

**Comment by ark3** [comment]
Can you open a separate issue for Mint 18.2? Given that Ubuntu 16.04 is supported with the PackageCloud packages, I think we should be able to get Mint 18.2 to work as well.

**Comment by Dobiasd** [comment]
OK, just opened a [new issue for Linux Mint](https://github.com/datawire/telepresence/issues/486).

Regarding the workaround: I'm fine. Installing from source worked without any problem. :+1:

**Comment by ark3** [comment]
The Telepresence documentation has a [list of dependencies](https://www.telepresence.io/reference/install.html#dependencies), but it does not explain how to install these dependencies on common platforms. We could use your help to fix this! Can someone please suggest how to install those dependencies on Debian?

**Comment by blak3mill3r** [comment]
```
/usr/local/share/telepresence/libexec/bin/python3 -Im ensurepip --upgrade --default-pip
/usr/local/share/telepresence/libexec/bin/python3: No module named ensurepip
```

**Comment by ark3** [comment]
Excellent work, thanks! 

It looks like I need to add `pip` and `venv` to the list. Debian and friends package them separately even though they are considered part of Python 3.5 upstream.

**Comment by blak3mill3r** [comment]
For the record, it works fine for me on Jessie if I do a user-install:

```
env PREFIX=/home/blake/tpinstall ./install.sh
```

This is because my own `python3` binary comes from `pyenv` and isn't on `root`'s `$PATH`. This is fine for me.

**Comment by donnyyung** [comment]
I don't think anybody has reported issues install Telepresence 2 on Jessie, here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/). 

I'm going to close for now but please re-open if it is an issue!
