### ISSUE TITLE
Telepresence scans kubeconfig to gather information and connect to multiple clusters

### ISSUE THREAD

**Issue by 0x6a77** [telepresenceio/telepresence#3492]
**Describe the bug**
Telepresence scans the kubeconfig to gather information. This presents a few problems:

1. It gathers information not related to the work at-hand from other clusters
2. With OIDC validation you get a browser pop-up every few minutes for every cluster in kubeconfig

* reproduce the error *

**To Reproduce**
1. Setup OIDC login (e.g. [kube-login](https://github.com/int128/kubelogin))
2. Have several clusters, including some not related to the current Telepresence session
3. Connect to one cluster
4. See browser pop-ups every few minutes for all clusters

**Expected behavior**
Telepresence probably shouldn't access kubeconfig because this leads to collecting sensitive information not relevant to the current session. For example, a devops consultancy may have multiple client environments configured there. Maybe the right answer is to evolve to a better security posture and remove the need for Telepresence to have root access — instead use a group permission with the ability to do `ifconfig` and whatnot without it being able to also read sensitive config files. This would also mitigate damage in case of a Telepresence breach on the developer's machine.

**Versions (please complete the following information):**
 - v2.18.1
 - osx
 - EKS — multiple versions

**Additional context**
[Threat Matrix for Kubernetes — Kubeconfig file](https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/Kubeconfig%20file/)

**Comment by thallgren** [comment]
Thanks for reporting this. It will be addressed in the upcoming 2.9.0 release.
