### ISSUE TITLE
Cannot intercept service ( traffic-manager is unable to determine what image to use for injected traffic-agents)

### ISSUE THREAD

**Issue by traugott** [telepresenceio/telepresence#3509]
**Describe the bug**
When trying to intercept a service with the command
_telepresence.exe intercept ServiceName --port 8080_
i get the error message

telepresence intercept: error: connector.CreateIntercept: intercepts are disabled because the traffic-manager is unable to determine what image to use for injected traffic-agents.

**To Reproduce**

Execute
_telepresence.exe intercept ServiceName --port 8080_

**Expected behavior**
Service gets intercepted as described in https://www.getambassador.io/docs/telepresence/latest/howtos/intercepts

**Versions (please complete the following information):**
telepresence version:
OSS Client     : v2.17.0
OSS Root Daemon: v2.17.0
OSS User Daemon: v2.17.0
Traffic Manager: v2.15.1

Operating system of workstation running `telepresence` commands
Windows 10 Enterprise Version 22H2 (19045.3930)

Kubernetes environment:
k3s (v1.26.3+k3s1)

**Comment by thallgren** [comment]
From the looks of it, you're using an enterprise version of the traffic-manager. Unless explicitly told not to, it will query Ambassador Cloud for the image to use, and for some reason that query is failing. Perhaps your cluster is air-gapped?

Our [docs](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config#agent-configuration) explains what Helm values (`agent.image.registry`, `agent.image.name`, and `agent.image.tag`) to use when configuring the traffic-manager.
