### ISSUE TITLE
`telepresence intercept run`/`validate`: `commands to be run with intercept must come after options`

### ISSUE THREAD

**Issue by RobertFischer** [telepresenceio/telepresence#3510]
**Describe the bug**

Following the docs here: https://www.getambassador.io/docs/telepresence/latest/reference/intercepts/specs#running-your-specification-from-the-cli

When running `telepresence intercept validate ./tp-spec.yaml`, I get this response:
```
$ telepresence intercept validate ./tp-spec.yaml
telepresence intercept: error: commands to be run with intercept must come after options
```

Same with `run`:

```
$ telepresence intercept run ./tp-spec.yaml
telepresence intercept: error: commands to be run with intercept must come after options
```

**To Reproduce**

1. Create an empty file named `./tp-spec.yaml`.
1. Attempt to run `telepresence intercept validate ./tp-spec.yaml`
1. See the error.

**Expected behavior**

The file would be validated, as described in the docs

**Versions**
```
$ telepresence version
OSS Client         : v2.17.0
OSS Root Daemon    : v2.17.0
OSS User Daemon    : v2.17.0
OSS Traffic Manager: v2.17.0
```

Ubuntu 22.04

K8s is K3s, but I doubt that matters.

**Comment by RobertFischer** [comment]
Same thing happens if the `tp-spec.yaml` file is populated with what seems to be a valid file, but since it happens with an empty file, I figured we'd start there.

**Comment by thallgren** [comment]
The `run` and `validate` sub-commands are is only included in our enterprise version. The OSS version that you're using knows nothing about intercept specifications.

**Comment by alextricity25** [comment]
@thallgren Does that mean that the docker compose intercept is impossible with the OSS version? Or is it still possible with using the `x-telepresence` extension?
