### ISSUE TITLE
telepresnece helm install is not working properly.

### ISSUE THREAD

**Issue by Ra-hul-Roy** [telepresenceio/telepresence#3513]
**Describe the bug**
Helm install commands fail with below error:

telepresence helm install: error: failed to install traffic manager: failed to clean up leftover release history: uninstall: Release not loaded: ambassador: release: not found

See logs for details (2 errors found): "/Users/raroy/Library/Logs/telepresence/daemon.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/14236766/telepresence_logs.zip)

I have not found any pods with ambassador name space as well
cmd: kubectl get pods -n ambassador                                                                                                          
output: No resources found in ambassador namespace.

**Expected behavior**
Traffic manager should get isntalled

**Versions (please complete the following information):**
version:
Client         : v2.14.1
Root Daemon    : v2.14.1
User Daemon    : v2.14.1
Traffic Manager: not connected
Status:
User Daemon: Running
  Version           : v2.14.1
  Executable        : /usr/local/bin/telepresence
  Install ID        : 6bb0c69a-44ff-4e76-a933-7fb363140c05
  Status            : Not connected
  Kubernetes server : 
  Kubernetes context: 
  Manager namespace : 
  Intercepts        : 0 total
Root Daemon: Running
  Version: v2.14.1
  Version: v2.14.1
Ambassador Cloud:
  Status      : Logged in
  User ID     : *****
  Account ID  : **********
  User Name   : Rahul Roy
  Email       : *******
  Account Name: manh.com
Traffic Manager: Not connected

**Comment by thallgren** [comment]
Please try and uninstall first using `telepresence helm uninstall` and then retry the install. It's likely that there are some residues from a failed previous install.

Also, I strongly suggest that you update to the latest version.
