### ISSUE TITLE
Error creating intercept when using `--replace`

### ISSUE THREAD

**Issue by bpfoster** [telepresenceio/telepresence#3514]
**Describe the bug**
I am trying to use the newly added `--replace` feature which sounds like it will help us immensely.  However when trying to run telepresence with this flag, I receive an error when attempting to intercept, relating to the liveness probe.

**To Reproduce**
1. When I run `telepresence intercept "${SERVICE}" --replace`
2. I see `telepresence intercept: error: connector.CreateIntercept: Error creating: Internal error occurred: replace operation does not apply: doc is missing path: /spec/containers/0/livenessProbe/httpGet/port: missing value`

**Expected behavior**
I expect the intercept to run successfully

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
OSS Client         : v2.18.0
OSS Root Daemon    : v2.18.0
OSS User Daemon    : v2.18.0
OSS Traffic Manager: v2.18.0
Traffic Agent      : docker.io/datawire/tel2:2.18.0
```
 - Operating system of workstation running `telepresence` commands
```
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
```
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
```
kind v0.21.0 go1.20.13 linux/amd64
```

**Additional context**
Is this perhaps because the agent_injector has removed the probes (`disableAppContainer()`) and then shortly thereafter tries to hide the probes' ports (`hideContainerPorts()`)?

**Comment by thallgren** [comment]
Yes. I think your guess might be correct. I'll look into that.

**Comment by thallgren** [comment]
@bpfoster I tested this, and yes, a replace in combination with using symbolic port names in readiness- and liveness-probes fail. A workaround for this problem is to change the probe's port to a number.

**Comment by bpfoster** [comment]
Thanks @thallgren for confirming.  It looks like this would also apply to startup probes?

For a more robust solution, could we update `agent_injector` to not add a `replace` patch to the probes if they've been removed?  This seems like a pretty straightforward change, I'm happy to submit a PR if you'd like.

**Comment by thallgren** [comment]
Thanks for offering to submit a PR. I didn't see that until just now.

**Comment by bpfoster** [comment]
No worries, thanks for the quick turnaround!
