### ISSUE TITLE
Error installing telepresence

### ISSUE THREAD

**Issue by jonboylailam** [telepresenceio/telepresence#352]
### What were you trying to do?

Hi, I am hoping to use telepresence to improve the way I work with kubernetes.
I am trying to run telepresence on my mac book pro OSX 10.13.1
I installed telepresence using homebrew
I then ran telepresence 

### What did you expect to happen?

I was hoping to be in a shell which proxies connections to my Kubernetes cluster.

### What happened instead?

I got the following messages and was prompted for my password.
```
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.
```

After providing my password, I got:

```
Guessing that Services IP range is 10.0.0.0/24. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.


Looks like there's a bug in our code. Sorry about that!
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.71`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.7.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin localhost 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 259, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2399, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 2128, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/bin/telepresence", line 1920, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence", line 1907, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence", line 397, in get_output
    result = unicode(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence132')"]' returned non-zero exit status 1.

```

Logs:

```
"import socket; socket.gethostbyname('hellotelepresence129')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  30.8 TL | [164] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence130')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  31.0 TL | [165] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence131')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  31.2 TL | [166] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence132')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

```

**Comment by ark3** [comment]
Thank you for the bug report. It looks like Telepresence did not successfully set up its DNS forwarding. Sorry that you got a crash rather than an error message; we're working on improving Telepresence error reporting.

1. Can you upload the full telepresence.log as a GitHub gist from a failed connection attempt such as the one that generated this bug report? If there is sensitive information in the log, please manually redact whatever you do not wish to expose.
2. By default, Telepresence runs in vpn-tcp mode. While this mode makes it easy to get started, container mode is much more reliable. Could you please try container mode? Something like `telepresence --docker-run --rm -it alpine sh` will get you a shell prompt on an Alpine container that is running on your own machine, proxied to your Kubernetes cluster.

**Comment by jonboylailam** [comment]
Hi, thanks for the reply 

1. I have uploaded my telepresence.log file as a [GitHub gist](https://gist.github.com/jonboylailam/09bea6f606a788dcc1244f6522c18848)
2. ```telepresence --docker-run --rm -it alpine sh``` works as expected, thanks

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
