### ISSUE TITLE
Automatically mount /var/run/secrets/kubernetes.io

### ISSUE THREAD

**Issue by wallrj** [telepresenceio/telepresence#353]
Thanks for Telepresence!
I'm hoping to use it to test and develop an in-cluster golang process, which expects to find `/var/run/secrets/kubernetes.io/serviceaccount/`.
I couldn't find a packaged version of `proot` for Fedora. 
Only a 2y old copr repo:
 * https://copr.fedorainfracloud.org/coprs/jlaska/proot/

But @ericchiang, in https://github.com/kubernetes/client-go/issues/328 suggested trying `unshare` .instead.

And it works!

```
telepresence --verbose --run-shell
unshare --map-root-user --mount
mount --bind $TELEPRESENCE_ROOT/var/run /var/run
cat /var/run/secrets/kubernetes.io/serviceaccount/token
```

Would it make sense for Telepresence perform that bind mount automatically?

See:
 * https://github.com/kubernetes/client-go/issues/328

**Comment by ark3** [comment]
Thanks for your very interesting suggestion! 

If we set up an `unshare`/`mount --bind`-based mount for `/var/run/secrets` for the process or shell executed by Telepresence and set `TELEPRESENCE_ROOT` to the empty string, then services developed _only on Linux_ could ignore the environment variable entirely. On MacOS, things would stay the same and processes would still have to pay attention to the environment variable. This is definitely an enhancement we can pursue in the future as long as the _only on Linux_ caveat is made clear.

In the meantime, we encourage developers to use container mode, which is the most robust and reliable way to use Telepresence. Shortly we will add a Telepresence feature to mount secrets in the container in the standard place.

Of course, container mode may not be for you. Can you tell us about your use case? Telepresence development is driven by users. Thank you!

**Comment by wallrj** [comment]
Thanks @ark3  I'll try out container mode and get back to you.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
