### ISSUE TITLE
telepresence intercept timed out [v2.17]

### ISSUE THREAD

**Issue by aleboulanger** [telepresenceio/telepresence#3548]
**Describe the bug**
Unable to intercept traffic from macOS with telepresence 2.17

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/14603528/telepresence_logs.zip)

**To Reproduce**
I followed the steps from the website

* telepresence helm install
* telepresence connect
* curl -ik https://kubernetes.default
* telepresence list
* kubectl get service data-processing-pipeline-launcher --output yaml
* telepresence intercept data-processing-pipeline-launcher --port 8080:8080 --env-file ~/data-processing-pipeline-launcher-intercept.env

**Expected behavior**
intercept the calls from the service 

**Versions (please complete the following information):**
 - Output of `telepresence version`
OSS Client         : v2.17.0
OSS Root Daemon    : v2.17.0
OSS User Daemon    : v2.17.0
OSS Traffic Manager: v2.17.0
 - Operating system of workstation running `telepresence` commands
MACOS 14.3.1 
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - VMWARE with Kubernetes 1.26.14

**VPN-related bugs:**

**Additional context**

**Comment by cindymullins-dw** [comment]
Looking at the cli.log, I think it could be this problem (sshfs need to be installed for volume mounts ).  Could you try following [these instructions](https://www.getambassador.io/docs/telepresence/latest/troubleshooting#volume-mounts-are-not-working-on-macos) in the docs?

**Comment by cindymullins-dw** [comment]
You can probably disregard the advice on volume mounts.  Instead, to follow up on this, the first thing to try would be to [[increase the timeout](https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/values.yaml#L131)], to allow more time for the agent to arrive.

**Comment by cindymullins-dw** [comment]
@aleboulanger, curious if you've tried increasing the timeout?  We do think that would help.

**Comment by thallgren** [comment]
Closing due to lack of response.
