### ISSUE TITLE
Specify resources for ambassador-agent

### ISSUE THREAD

**Issue by mskhor** [telepresenceio/telepresence#3552]
Is there an option to specify resources for ambassador-agent via helm values ?

`   spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: info
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: AGENT_CONFIG_RESOURCE_NAME
              value: traffic-manager-ambassador-agent-cloud-token
            - name: RPC_CONNECTION_ADDRESS
          image: 'docker.io/ambassador/ambassador-agent:1.0.21'
          imagePullPolicy: IfNotPresent
          name: ambassador-agent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}`

Only seeing below in helm values, but its not applied for ambassador-agent

`agent:
  logLevel:
  resources: {}
  initResources: {}
  appProtocolStrategy: http2Probe
  port: 9900
  image:
    registry:
    name:
    tag:
    pullSecrets: []
    pullPolicy: IfNotPresent`

**Comment by alextricity25** [comment]
Have you tried putting it under the `ambassador-agent` directive? For example, I use these values to disable the ambassador agent:
```yaml
ambassador-agent:
  enabled: false
  ```
  So maybe you're looking for something like:
  ```yaml
  ambassador-agent:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi

**Comment by cindymullins-dw** [comment]
@mskhor , @alextricity25 , I believe the ambassador-agent for Telepresence is disabled by default.  It's used to report your cluster to Ambassador so you could do things like have a service catalog.

As for the resource limits, would you want to adjust them for adherence to company policy perhaps?  Is there another reason?  This spec is not currently available so I don't think the above config example would work - this would probably be a feature request.

**Comment by thallgren** [comment]
In the coming version 2.20.0, the `ambassador-agent` will be disabled by default. Please reopen this ticket if you still have an issue with it.
