### ISSUE TITLE
IntelliJ/JetBrains plugin pops up message to upgrade although i'm in advanced version already

### ISSUE THREAD

**Issue by yitzhtal** [telepresenceio/telepresence#3557]
**Describe the bug**

Installing telepresence on Mac M1 ; and the plugin for the IntelliJ ; causing my telepresence plugin to pop up a message:
"Upgrade to the proprietary version of Telepresence 2.16.0+."

But I'm:
```
talyitzhak@h-MacBook-Pro-sl-Tal lightrun-k8s-solutions-cluster % telepresence version
Client     : v2.19.0
Root Daemon: not running
User Daemon: not running
```
<img width="1715" alt="Screenshot 2024-03-29 at 22 43 40" src="https://github.com/telepresenceio/telepresence/assets/15890481/f8bbed0a-63c0-4861-92c2-ba7bc4eb19ef">

* reproduce the error *

Download telepresence IntelliJ plugin version 0.2.0, and telepresence for mac M1.

**Versions (please complete the following information):**
```
talyitzhak@h-MacBook-Pro-sl-Tal lightrun-k8s-solutions-cluster % telepresence version
Client     : v2.19.0
Root Daemon: not running
User Daemon: not running
```

**Comment by cindymullins-dw** [comment]
HI @talitz , that sounds like a bug. For the record, our Support has tested this successfully but on Intel, not on Mac M1.
Re-installing Telepresence might be worth a try.  Did you install via the QuickStart?  We haven’t seen this error but your version does indeed show you're running the Enterprise version, so would be good to figure out the source of this error.

**Comment by inakiabt** [comment]
Same here on an Intel Mac.

```
❯ telepresence version
OSS Client : v2.18.0
Root Daemon: not running
User Daemon: not running
```

**Comment by ferencgyenezs** [comment]
Same on windows

plugin version: 0.2.0

JetBrains Rider 2024.1.2
Build #RD-241.15989.179, built on May 6, 2024

```
OSS Client         : v2.18.0
OSS Root Daemon    : v2.18.0
OSS User Daemon    : v2.18.0
OSS Traffic Manager: v2.18.0
Traffic Agent      : docker.io/datawire/tel2:2.18.0
```

**Comment by cindymullins-dw** [comment]
@inakiabt , @ferencgyenezsenio, this feature is only available on Telepresence Enterprise, the licensed version.  It might indeed be a bug per the first user.  If you could [install Telepresence Enterprise](https://www.getambassador.io/products/telepresence) and try to use the plugin and get the same error, that would help in determining whether this is a bug.
