### ISSUE TITLE
"Connection refused" with Telepresence 2.19.3

### ISSUE THREAD

**Issue by gseva** [telepresenceio/telepresence#3579]
**Describe the bug**

I installed the latest version of telepresence with brew, and all my attempts to connect to the cluster failed with

```
telepresence connect: error: connection error: desc = "transport: error while dialing: dial tcp [::]:57677: connect: connection refused"
```

I got this error with different ports trying to do `telepresence --run-shell` and `telepresence list`.

Then I rolled back to 2.10.4, and was able to connect.

I'm behind a VPN. I currently don't have the latest version to provide debug logs, but let me know if they are required.

**Versions:**

 - Output of `telepresence version`:

```
An update of telepresence from version 2.10.4 to 2.19.3 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
OSS Client     : v2.10.4
OSS Root Daemon: v2.10.4
OSS User Daemon: v2.10.4
Traffic Manager: v2.4.11
```

 - Operating system of workstation running `telepresence` commands

I'm on a m2 mac, following is my `uname -r`.

```
Darwin ip-192-168-0-193.us-west-2.compute.internal 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64
```

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

```
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7-eks-b9c9ed7
```

**Comment by cindymullins-dw** [comment]
@gseva , can you let us know what VPN you're using?  Also, more importantly, did you only upgrade the client to 2.19?  If the Traffic Manager is still at 2.4.11 then it's not likely they will work together.  We recommend they be no more than 3 versions apart.

**Comment by gseva** [comment]
@cindymullins-dw What information can I provide about the VPN that would be useful to you? Also, since it worked after rolling back the version, it's probably not a VPN problem, right?
I'll see if we can upgrade the traffic manager, thank you for the suggestion.

**Comment by thallgren** [comment]
You run a very old version of Telepresence in your cluster. I would suggest that you uninstall that version first. We don't support version diffs that large.

**Comment by gseva** [comment]
@thallgren Understood, thanks for your response. We will try to upgrade ASAP, feel free to close this issue.
