### ISSUE TITLE
Building without "-tags embed_fuseftp" still errors out due to "pattern fuseftp.bits: no matching files found"

### ISSUE THREAD

**Issue by johanneskastl** [telepresenceio/telepresence#3591]
I am trying to package this for openSUSE, but the build fails:

```
[   36s] + cd telepresence-2.18.0
[   36s] + CGO_ENABLED=0
[   36s] + go build -mod=vendor -buildmode=pie -ldflags=-X=github.com/telepresenceio/telepresence/v2/pkg/version.Version=2.18.0 -o bin/telepresence ./cmd/telepresence
[   37s] pkg/client/remotefs/fuseftp.go:26:12: pattern fuseftp.bits: no matching files found
[   37s] error: Bad exit status from /var/tmp/rpm-tmp.FC6fFl (%build)

```

As far as I understood the `build-aux` file, it should be possible to build without embeding the fuseftp binary. But even without the `-tags embed_fuseftp` flag the error appears.

https://github.com/telepresenceio/telepresence/blob/release/v2/build-aux/main.mk#L189

I failed to build the fuseftp file, so as a first step I wanted to avoid packaging binary code by download the file from Github...

Any ideas?

**Comment by thallgren** [comment]
From the looks of it, you're compiling the wrong version of the source. Line 26 in fuseftp.go no longer contains that reference.

**Comment by johanneskastl** [comment]
Aaah, yes, you are right, I looked at the build-aux file from `release/v2` while I was trying to package the latest stable release.

My bad, sorry for the noise....
