### ISSUE TITLE
Why do I keep getting reminded about identity verification?

### ISSUE THREAD

**Issue by zouchengli** [telepresenceio/telepresence#3599]
❯ telepresence version
Client         : v2.19.5
Root Daemon    : v2.19.5
User Daemon    : v2.19.5
Traffic Manager: not connected

sudo telepresence connect --namespace default
An Ambassador Cloud account is required to use Telepresence.
Have questions? Please see our FAQ at https://a8r.io/tp-faq
Press enter to sign in or sign up...

Launching browser authentication flow...
Successfully signed in.
An Ambassador Cloud account is required to use Telepresence.
Have questions? Please see our FAQ at https://a8r.io/tp-faq
Press enter to sign in or sign up...

Launching browser authentication flow...
Successfully signed in.
An Ambassador Cloud account is required to use Telepresence.
Have questions? Please see our FAQ at https://a8r.io/tp-faq
Press enter to sign in or sign up...

Launching browser authentication flow...
Successfully signed in.
An Ambassador Cloud account is required to use Telepresence.
Have questions? Please see our FAQ at https://a8r.io/tp-faq
Press enter to sign in or sign up...

**Comment by thallgren** [comment]
What type of license do you have? Is the license still valid?

**Comment by thallgren** [comment]
Please don't use `sudo` when starting telepresence. That will mess up the permissions of config files and cached files (the license among other things).

**Comment by cindymullins-dw** [comment]
Can you try running `telepresence status` and share that output?  That will help us check whether you're actually logged in and also your subscription type.

**Comment by zouchengli** [comment]
> Can you try running `telepresence status` and share that output? That will help us check whether you're actually logged in and also your subscription type.
`❯ telepresence status
Ambassador Cloud: Connected
  User ID     : 08c828a1-fa96-4db6-b340-8ae7ffa5a0a9
  Account ID  : 9042a214-3cc7-4142-9c4f-084b7c5c8385
  User Name   : chengli.zou
  Email       : chengli.zou@gmail.com
  Account Name: 鄒成立
  Plan        : Unable to get plan from Ambassador Cloud: no cloudd client in context
User Daemon: Not running
Root Daemon: Not running
Traffic Manager: Not connected
❯ telepresence helm install

Traffic Manager installed successfully
❯ telepresence status
Ambassador Cloud: Connected
  User ID     : 08c828a1-fa96-4db6-b340-8ae7ffa5a0a9
  Account ID  : 9042a214-3cc7-4142-9c4f-084b7c5c8385
  User Name   : chengli.zou
  Email       : chengli.zou@gmail.com
  Account Name: 鄒成立
  Plan        : Unable to get plan from Ambassador Cloud: no cloudd client in context
User Daemon: Not running
Root Daemon: Not running
Traffic Manager: Not connected
❯ telepresence connect
telepresence connect: error: connection error: desc = "transport: error while dialing: dial tcp [::]:50918: connect: connection refused"`

**Comment by zouchengli** [comment]
I tried fixing the authorization cache directory myself as well as adjusting the file permissions and it finally worked for me

**Comment by zouchengli** [comment]
Taking my user directory as an example, just clear the cache directory and re-authorize it.
`sudo rm -rf /Users/chengli.zou/Library/Caches/telepresence`
The best way is to log in to [ambassador](url) first to get the token
<img width="928" alt="image" src="https://github.com/telepresenceio/telepresence/assets/27568522/5e517b39-869a-4e76-8918-20f9dff50649">

**Comment by zouchengli** [comment]
<img width="518" alt="image" src="https://github.com/telepresenceio/telepresence/assets/27568522/cbab5d20-5a79-4553-98e5-971d9dad3eb7">
