### ISSUE TITLE
telepresence crashes

### ISSUE THREAD

**Issue by kgignatyev-inspur** [telepresenceio/telepresence#360]
### What were you trying to do?
just trying telepresence, doing step 3
(please tell us)

### What did you expect to happen?

expected shell 

### What happened instead?

crashed

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '-m', 'inject-tcp', '-n', 'test', '--run-shell']`
Version: `0.71`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.8.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin kgi-mbp-i7-2.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 259, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2399, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 2125, in run_local_command
    setup_torsocks(runner, env, socks_port, unsupported_tools_path)
  File "/usr/local/bin/telepresence", line 2083, in setup_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
e.com.
  23.2 31 | 	
1512694859 ERROR torsocks[7964]: Unable to resolve. Status reply: 4 (in socks5_recv_resolve_reply() at socks5.c:683)
  23.2 39 | Traceback (most recent call last):
  23.2 39 |   File "<string>", line 1, in <module>
  23.2 39 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  23.2 TL | [39] exit 1.
  23.3 TL | [40] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  28.5 31 | 2017-12-08T01:01:04+0000 [-] Unhandled Error
  28.5 31 | 	Traceback (most recent call last):
1512694864 ERROR torsocks[7975]: Unable to resolve. Status reply: 4 (in socks5_recv_resolve_reply() at socks5.c:683)
  28.5 31 | 	Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: google.com.
  28.5 31 | 	
  28.5 40 | Traceback (most recent call last):
  28.5 40 |   File "<string>", line 1, in <module>
  28.5 40 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  28.5 TL | [40] exit 1.

```

**Comment by ark3** [comment]
Could you please pass along the full telepresence.log as a gist? Thanks.

**Comment by kgignatyev-inspur** [comment]
https://gist.github.com/kgignatyev-inspur/3b261be0fd7eb4754916e08a3f87c4be

**Comment by kgignatyev-inspur** [comment]
Just a thought, I noticed that there is problem in my kubernetes environment: external domain named do NOT get resolved from within containers, so the crash might be caused by my environment.

**Comment by ark3** [comment]
Yes, that is almost certainly the issue. I’m glad you thought of that; I was somewhat confused.

**Comment by kgignatyev-inspur** [comment]
well, upon careful review it seems that dns resolution works, but it a bit slow and includes IPv6 info. So, if I run busybox like this:
 kubectl run busybox -t -i --image=busybox

and then do 
wget google.com 

it works, I get index.html file of google's home page. 
Although DNS resolution is slow, it takes 25 seconds:
/ # date; nslookup google.com; date
Sun Dec 10 06:07:31 UTC 2017
Server:    100.64.0.10
Address 1: 100.64.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2607:f8b0:400a:808::200e sea15s11-in-x0e.1e100.net
Address 2: 216.58.216.142
Sun Dec 10 06:07:56 UTC 2017
/ # 


I am running 1.8.5 cluster in AWS created with kops, and only deviation is that I am using CentOS host machines (ami-e535c59d for us-west-2)

**Comment by kgignatyev-inspur** [comment]
Just FYI, here is info about my issue https://github.com/kubernetes/kops/issues/4040.
You seem to be knowledgeable about networking in kubernetes, if you have any clue please chime in.

**Comment by ark3** [comment]
Sorry, I don’t know much about Flannel and Kubenet stuff. Certainly we can make Telepresence have a longer timeout but I don’t think that’s the correct solution to this problem.

**Comment by kgignatyev-inspur** [comment]
Agreed, longer timeout is not a solution for the problem. But if in your error handler you add reaction on timeouts and provide suggestion to check K8S networking and DNS resolution times that would look classy in Telepresense :)

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
