### ISSUE TITLE
Provide Homebrew release of OSS version "tel2oss" of Telepresence

### ISSUE THREAD

**Issue by tonur** [telepresenceio/telepresence#3609]
I have implemented a sample Homebrew formula for the "tel2oss" here: https://github.com/tonur/homebrew-telepresence-oss

**Please describe your use case / problem.**
Installing from a binary download link is not preferred, as the [Telepresence install page](https://www.getambassador.io/docs/telepresence/latest/install?os=macos) for the standard release also suggests installation via brew.
My use case would be much improved if I could install the "tel2oss" version of Telepresence with such a command:
`brew install datawire/blackbird/telepresence-oss`

**Describe the solution you'd like**
Add the "tel2oss" as a separate Homebrew formula as part of the [release build](https://github.com/telepresenceio/telepresence/blob/52b5ce0103371b49da26ebc1a68c554e3955e52f/build-aux/main.mk#L336) which currently uses [packaging/homebrew-package.sh](https://github.com/telepresenceio/telepresence/blob/release/v2/packaging/homebrew-package.sh) to only release the "tel2" standard version.

The best solution would be to host this Homebrew formula on a Datawire controlled repository, likely the current Homebrew tap location for this: https://github.com/datawire/homebrew-blackbird as a formula called "telepresence-oss".
As mentioned, this formula for the "tel2oss" can perhaps serve as inspiration: https://github.com/tonur/homebrew-telepresence-oss.
This requires changes to the [packaging/homebrew-package.sh](https://github.com/telepresenceio/telepresence/blob/release/v2/packaging/homebrew-package.sh) file to automate new releases.

**Describe alternatives you've considered**
Hosting the formula myself, but this is undesirable for other users, as a random Github users private repository is less trusted than the official Datawire controlled repository.

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)
```
> telepresence version
OSS Client     : v2.18.0
OSS Root Daemon: v2.18.0
OSS User Daemon: v2.18.0
Traffic Manager: v2.17.0
Traffic Agent  : not currently available
```
  - Kubernetes Environment and Version
  AKS Version 1.28

**Additional context**
This applies only to MacBook and perhaps Linux, as these are the only users of Homebrew.

**Comment by tonur** [comment]
I could try my luck at adding this feature by modifying the same files as in #3282.
I can make a Pull Request this afternoon, if this is something Telepresence/DataWire is okay with.

**Comment by thallgren** [comment]
The final destination for the homebrew tap is no longer at datawire. Use:
```
brew install telepresenceio/telepresence/telepresence-oss
```
