### ISSUE TITLE
Telepresence abruptly crashed during demo

### ISSUE THREAD

**Issue by richarddli** [telepresenceio/telepresence#362]
### What were you trying to do?

Just running Telepresence

### What did you expect to happen?

it to keep on running

### What happened instead?

After a few HTTP requests, it crashed

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'dashboard', '--swap-deployment', 'api-dev-foo', '--docker-run', '--rm', '-i', '-t', '-v', '/Users/richard/dw/dashboard/api:/service', 'api-dev-dev']`
Version: `0.68`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.7.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin lost-cause.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2379, in go
    ssh,
  File "/usr/local/bin/telepresence", line 2051, in run_docker_command
    wait_for_exit(runner, p, subprocesses)
  File "/usr/local/bin/telepresence", line 1602, in wait_for_exit
    dead_process = processes.any_dead()
  File "/usr/local/bin/telepresence", line 958, in any_dead
    self.killall()
  File "/usr/local/bin/telepresence", line 944, in killall
    killer()
  File "/usr/local/bin/telepresence", line 1934, in kill
    runner.check_call(sudo + ["docker", "stop", "--time=1", name])
  File "/usr/local/bin/telepresence", line 384, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['docker', 'stop', '--time=1', 'telepresence-1513091423-483957-43850'],)' returned non-zero exit status 1.

```

Logs:

```
l manager: --->   File "/root/.pex/install/sshuttle-0.78.2.dev42+g8f881d1-py2.py3-none-any.whl.1d5a47f7578c0db2926126f89a2e00157b601b71/sshuttle-0.78.2.dev42+g8f881d1-py2.py3-none-any.whl/sshuttle/firewall.py", line 50, in restore_etc_hosts
  53.8 24 | firewall manager: --->     rewrite_etc_hosts({}, port)
  53.8 24 | firewall manager: --->   File "/root/.pex/install/sshuttle-0.78.2.dev42+g8f881d1-py2.py3-none-any.whl.1d5a47f7578c0db2926126f89a2e00157b601b71/sshuttle-0.78.2.dev42+g8f881d1-py2.py3-none-any.whl/sshuttle/firewall.py", line 29, in rewrite_etc_hosts
  53.8 24 | firewall manager: --->     os.link(HOSTSFILE, BAKFILE)
  53.8 24 | firewall manager: ---> OSError: [Errno 18] Cross-device link: '/etc/hosts' -> '/etc/hosts.sbak'
  53.9 24 | c : fatal: server died with error code 255
  53.9 24 | [INFO  tini (1)] Main child exited normally (with status '0')
  54.5 TL | [27] Running: (['docker', 'stop', '--time=1', 'telepresence-1513091423-483957-43850'],)...
  54.6 TL | [27] exit 1.

```

**Comment by richarddli** [comment]
[telepresence.log](https://github.com/datawire/telepresence/files/1552063/telepresence.log)

**Comment by ark3** [comment]
Hmm. Sshuttle crashed. I haven’t seen that before. But it looks like there was a connectivity problem right before the crash, a ”broken pipe” mentioned in the logs. I’ll need to investigate further.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
