### ISSUE TITLE
Add copy-deployment and swap-service as a way to use Telepresence

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#363]
See also #257 and PR #407

**Comment by ofpiyush** [comment]
Our use case/experience report:

We already have openvpn added to our cluster. Simplifying that would be sweet but isn't required as such. https://github.com/pieterlange/kube-openvpn

Having a separate openvpn instance allows us to add other kind of urls to be forwarded without needing `--also-proxy`.
eg: `c.<project_id>.internal` urls with GCP.

Separating out the VPN part makes it straight forward to have multiple different services running locally. It also makes the network very very stable. I run into cases where urls sometimes do not get proxied with telepresence. Those class of issues can be completely avoided by allowing a separate VPN setup.

If you baked that configurability into telepresence, that would be cool.

I envision separate `telepresence config(s)` tied to `kubectl config current-context`.

Different kind of needs we regularly run into:

1. Add a local process as a pod parallel to the ones running, some traffic comes to my pod. This has added benefit of being useful in really bad cases of production debugging as well.

2. Let the cluster pods deal with partial background functionality, redirect all active service traffic to my local.

We have rabbitmq listeners etc in some of our services, they can continue to operate in the cloud while we debug some API level stuff/dev locally, but we want requests to the service to come to the local instance.

3. Stop everything and let us completely take over. This is the current behaviour of `--swap-deployment`

We would not be opposed to having an always on, telepresence deployment with it's own URL and such if that made things easier, esp around networking and managing everyone's connection / multiple swappable shells.

This central deployment would also help you to keep 1 source of truth and return the cluster to it's original state if things went sideways on someone's local.

**Comment by donnyyung** [comment]
This seems to be pretty much how Telepresence 2 works. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
