### ISSUE TITLE
Unable to intercept services when using telepresence intercept

### ISSUE THREAD

**Issue by dcwire** [telepresenceio/telepresence#3630]
**Describe the bug**
I was running optscale ([optscale](https://github.com/hystax/optscale)) an opensource project and wanted to make some changes on it and wanted to setup a development environment. I was successfully able to deploy optscale on an EC2 instance but Im facing issues while trying to intercept a service. There’s a service called ngui which is the frontend for optscale, which also shows up when I use the command telepresence list but when I do telepresence intercept it says the server could not find the requested resource. The other services also show the same issues so basically I cannot intercept any service.

**Telepresence logs**
[telepresence_logs.zip](https://github.com/user-attachments/files/16008939/telepresence_logs.zip)

**To Reproduce**
1. I installed telepresence using the steps mentioned in the link [Telepresence Quickstart | Ambassador Telepresence (getambassador.io)](https://www.getambassador.io/docs/telepresence-oss/latest/quick-start?os=gnu-linux)
2. On typing `telepresence connect` : 
![Untitled](https://github.com/telepresenceio/telepresence/assets/60493038/ce833514-ea1a-4bf1-8999-982373d99c18)

3. Then `telepresence helm install`
`telepresence helm upgrade` gives me:
![Untitled (1)](https://github.com/telepresenceio/telepresence/assets/60493038/5b1575d0-7cf2-4f45-beec-d568323a8e8c)

4. `telepresence intercept ngui --port 4000:ngui`
`telepresence intercept ngui` gives me an error : 
![Untitled (2)](https://github.com/telepresenceio/telepresence/assets/60493038/70ea01f2-2eb6-425b-9983-20532a0ee9e2)

**Expected behavior**
I should have been able to intercept the required services successfully. 

**Versions:**
 - `telepresence version`  : 
![Untitled (7)](https://github.com/telepresenceio/telepresence/assets/60493038/02feebcb-b6df-4252-91c6-a66510e09a3d)

 - Operating system : Running `Ubuntu 20.04.6 LTS`
 - Kubernetes environment and Version: 
![Untitled (4)](https://github.com/telepresenceio/telepresence/assets/60493038/34585474-57cf-404c-9e55-ee446e2339a0)

**Additional context**
1. `telepresence list`  gives me:
![Untitled (5)](https://github.com/telepresenceio/telepresence/assets/60493038/139c27ad-b860-40f9-b633-b3aeca33751a)

2. `kubectl  get service ngui --output yaml`  gives me :
![Untitled (6)](https://github.com/telepresenceio/telepresence/assets/60493038/e1b3d015-a6d9-460b-95e4-6ef75c023bf9)

**Comment by cindymullins-dw** [comment]
You can try using symbolic port name.  with a numeric port, telepresence is forced to inject an init-container to modify iptables. That is known to fail in some situations. Please see[this section](https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#injected-init-container-doesnt-function-properly) in our troubleshooting guide.

If that doesn't help, can you please run telepresence loglevel debug, then reproduce the problem and provide the logs from telepresence gather-logs.

**Comment by thallgren** [comment]
You are using a Kubernetes cluster of a version that precedes the introduction of `events.k8s.io/v1` (1.19). Telepresence can not run in clusters that old. You'll need to upgrade.
