### ISSUE TITLE
telepresence intercept: error: unknown flag: --http-header

### ISSUE THREAD

**Issue by fgarciacode** [telepresenceio/telepresence#3631]
**Describe the bug**
I'm try to use Personal Intercepts with Telepresence OSS, with the command in the documentation.

https://www.getambassador.io/docs/telepresence/latest/concepts/intercepts

```
telepresence intercept SERVICENAME --http-header=Personal-Intercept=126a72c7-be8b-4329-af64-768e207a184b

telepresence intercept: error: unknown flag: --http-header
```

**Versions (please complete the following information):**
 - OSS Client : v2.19.0
 - MacOS Sonoma v14.5
 - Kubernetes v1.28.9

**Comment by cindymullins-dw** [comment]
Personal intercepts are only available with Telepresence Enterprise, the licensed version.  With the OSS version you can only do global intercepts.  You can try Telepresence Enterprise for free by following the [quick start on Ambassador Cloud](https://www.getambassador.io/docs/cloud) (we provision a temporary cluster for you to test with or you can use your own.) Alternatively, you can follow the Telepresence Enterprise Quick Start[ here.](https://www.getambassador.io/docs/telepresence/latest/quick-start)

**Comment by ozozgun** [comment]
Is there a documentation specific to the OSS version ?
I have not found any mention to this on the documentations
https://www.getambassador.io/docs/telepresence/latest/reference/intercepts/cli#:~:text=Creating%20a%20personal%20intercept,be%20affected%20by%20your%20intercept.

**Comment by thallgren** [comment]
You'll find the OSS docs here: https://www.telepresence.io/
