### ISSUE TITLE
telepresence helm install: error: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/root/.config/telepresence/config.yml"

### ISSUE THREAD

**Issue by romanticlie** [telepresenceio/telepresence#3635]
**Describe the bug**

Additionally, if you are using Telepresence 2.4.4 and above, please use
`telepresence loglevel debug` to ensure we have the most helpful logs,
reproduce the error, and then run `telepresence gather-logs` to create a
zip file of all logs for Telepresence's components (root and user daemons,
traffic-manager, and traffic-agents) and attach it to this issue. See an
example command below:
```
telepresence loglevel debug

* reproduce the error *

telepresence gather-logs --output-file /tmp/telepresence_logs.zip

# To see all options, run the following command
telepresence gather-logs --help
```

**To Reproduce**
1. When I run '...'
2. I see '....'
3. So I look at '....'

**Expected behavior**

**Versions (please complete the following information):**
 - Output of `telepresence version`
 - Operating system of workstation running `telepresence` commands
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
 - Which VPN client are you using?
 - Which VPN server are you using?
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf

**Additional context**

**Comment by cindymullins-dw** [comment]
Are you also seeing  "failed to clean up leftover release history" error when using telepresence helm commands, b/c former secrets from previous installs may contribute to this issue. Have you tried `telepresence helm uninstall` then `telepresence helm install`.

With Openshift, some users have reported success with this error by running

oc project ambassador
oc adm policy add-scc-to-user anyuid -z traffic-manager

If you’re on 2.4.4 that version is pretty old now.  Can you try with the latest and let us know if the error persists?

**Comment by thallgren** [comment]
@cindymullins-dw I don't think the user is on 2.4.4. The comment is just the template, untouched, which is somewhat annoying. I'm closing this ticket because it doesn't contain any description besides the title, and the title itself contains the solution for its own problem.

**Comment by mderazon** [comment]
Also getting this
```
$ telepresence version
OSS Client     : v2.22.4
OSS Root Daemon: v2.22.4
OSS User Daemon: v2.22.4
Traffic Manager: not connected

$ telepresence helm uninstall
Traffic Manager uninstalled successfully

$ telepresence helm install
telepresence helm install: error: the helm operation timed out.  The current timeout 30s can be configured as "timeouts.helm" in "/home/user/.config/telepresence/config.yml"
```

**Comment by thallgren** [comment]
@mderazon, start a `kubectl -n ambassador get events -w` before you start the install. It's very likely that the events that get logged will reveal you problem. If you conclude that Telepresence is to blame, then please open a new ticket.

**Comment by mderazon** [comment]
For fututre reference, the 30s timeout was too short, I had to change the timeout to 
```yml
# ~/.config/telepresence/config.yml
timeouts:
  helm: 2m
```
And then it worked.
It took me time to find the right timeout to set

**Comment by iirekm** [comment]
why this is unfixed? IMHO the default 30s timeout is too low for Helm to download large binaries. Websites with artifacts often have issues, it should be at least 5 minutes!

**Comment by thallgren** [comment]
The binary (there's only one) is about 136Mb in size, so you'll need a download speed that's less than 40Mbit/sec in order to run into a timeout. That's not very common nowadays, and especially not from GitHub where we publish our binaries.

The reason the default timeout is 30s as opposed to, say, 5 minutes, is that there are many other reasons why a Helm install might fail, and it's annoying to have to wait 5 minutes until the failure is apparent.

The default is configurable. If you think it's too short, just change it.

**Comment by d0zingcat** [comment]
> For fututre reference, the 30s timeout was too short, I had to change the timeout to
> 
> # ~/.config/telepresence/config.yml
> timeouts:
>   helm: 2m
> And then it worked. It took me time to find the right timeout to set

For me, the path should be: "/Users/{username}/Library/Application Support/telepresence/config.yml"

**Comment by nsu700** [comment]
I am deploying it into OpenShift, and need this command to finish the installation, as it requires to run as uid 1000

```
oc adm policy add-scc-to-user anyuid -z traffic-manager
```
