### ISSUE TITLE
Upload-traces command sends gRPC messages larger than the default max size

### ISSUE THREAD

**Issue by sam-wbcx** [telepresenceio/telepresence#3647]
**Describe the bug**
The `telepresence upload-traces` command sends gRPC messages larger than the default max size of 4M.

**To Reproduce**
1. When I run `telepresence gather-traces` after a normal telepresence operation,
2. I see a new file `traces.gz`, in my test the compressed file was 1.7M and uncompressed it was 18M
3. To view the collected traces, I run Jaeger with the following command: `docker run --rm --name jaeger -d -e COLLECTOR_OTLP_ENABLED=true -p 16686:16686 -p 4317:4317 jaegertracing/all-in-one:latest`
4. To upload the traces, I use the command `telepresence upload-traces traces.gz localhost:4317`
5. I see the following error:
```
telepresence upload-traces: error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (19071854 vs. 4194304)
```

**Expected behavior**
I expected the `upload-traces` command to send the trace data to Jaeger using messages that are smaller than the default max size.

**Versions (please complete the following information):**
 - Output of `telepresence version`: 
 ```
OSS Client         : v2.18.0
OSS Root Daemon    : v2.18.0
OSS User Daemon    : v2.18.0
OSS Traffic Manager: v2.18.0
Traffic Agent      : docker.io/datawire/tel2:2.18.0
```
 - Operating system of workstation running `telepresence` commands
```
macOS 14.3.1 (Sonoma)
```
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 ```
Amazon EKS, v1.29.4-eks-036c24b
```

**Comment by cindymullins-dw** [comment]
HI @sam-wbcx , there’s a client-side configuration that allows you to set gRPC message size [here](https://www.getambassador.io/docs/telepresence/latest/reference/config#grpc). 'The maxReceiveSize determines how large a message that the workstation receives via gRPC can be.'  Can you try this and let us know if it helps?

**Comment by thallgren** [comment]
Closing this, because a solution was provided.

**Comment by sam-wbcx** [comment]
@cindymullins-dw That one didn't work for me, I think that my collector (Jaeger in my example) is the one complaining about message size and not my workstation. It's possible I'm using it wrong though, do you expect that behavior to affect the upload-traces command?

I'm happy to contribute code for this if that's needed, I'm not sure why this trace data couldn't be broken up into smaller chunks for a collector.
