### ISSUE TITLE
Helm Chart Deployment Fails with Nil Pointer Errors on Nullable Values

### ISSUE THREAD

**Issue by Kr1Kr1** [telepresenceio/telepresence#3649]
**Describe the bug**

We deploy Telepresence using the Helm chart provided in the repository (charts/telepresence) via ArgoCD. In our latest version bump, we encountered multiple issues with `nil pointer evaluating interface {}.volsTemplate` and `nil pointer evaluating interface {}.envTemplate`. These values are not present in the default values file and can be nullable. We managed to deploy Telepresence by modifying the deployment and allowing those values to be null, such as` {{- if and (.trafficManager) (.trafficManager.envTemplate) }}`.

**Expected behavior**
Telepresence should be deployed successfully without nil pointer errors for nullable values.

**Comment by cindymullins-dw** [comment]
Hi @Kr1Kr1 , it sounds like you haven't changed anything with the deployment, but which versions did you upgrade to and from?

**Comment by thallgren** [comment]
The code under charts/telepresence is a template for a helm chart. It's not intended to be deployed, so your expectation is wrong.

If you want to produce a proper Helm chart to use with Argo-CD, you'll need to run code similar to [this code](https://github.com/telepresenceio/telepresence/blob/release/v2/integration_test/itest/cluster.go#L566-L581). It uses that template and creates a proper Helm chart.
