### ISSUE TITLE
Volumes mounted only from one container

### ISSUE THREAD

**Issue by jckos** [telepresenceio/telepresence#3653]
Hello,
I am having difficulties with (locally) mounting the pod volumes as described in the docs (https://www.getambassador.io/docs/telepresence/latest/reference/volume)

Attaching telepresence logs and intercepted pod description. The problem is that only the volumes from the nginx container are mounted. I would need mount all volumes (or at least the php container - actually i need only the php container volumes)

**To Reproduce**
When intercepted the service (pod description attached):
`telepresence intercept tps-front-575ff95464  --service tps-front --port 80:80 --mount=./tps/ --env-file tps.env`

in env(attached) I see that there are only nginx container mounts.

**Expected behaviour**
All volumes from pod are mounted

**Versions (please complete the following information):**
OSS Client         : v2.17.0
OSS Root Daemon    : v2.17.0
OSS User Daemon    : v2.17.0
OSS Traffic Manager: v2.17.0
Apple M1 14.4.1 (23E224)
cluster: AKS

**Comment by cindymullins-dw** [comment]
Hi @jckos, can you share your tps front service yaml and also your pod yaml?  We’d like to see what containers you have and which one is being intercepted by Telepresence.  If you're intercepting the nginx container you could be pulling the volume mounts from there and you'd need to intercept the php container instead or possibly both.

**Comment by jckos** [comment]
Hello Cindy, 
thank you for the answer. Now (I had to redeploy) I have:
`telepresence list -o`
```
tps-admin-7bd4fc66   : ready to intercept (traffic-agent not yet installed)
tps-front-7554d86c55 : intercepted
   Intercept name    : tps-front-7554d86c55
   State             : ACTIVE
   Workload kind     : ReplicaSet
   Destination       : 127.0.0.1:80
   Volume Mount Point: /Users/me/tps
   Intercepting      : all TCP connections
tps-sap-api-6d5685966: ready to intercept (traffic-agent not yet installed)
```

**Comment by thallgren** [comment]
Telepresence will mount the volumes of the intercepted container, not all containers in a pod. The documentation is incorrect when it states "mounts the Pod's volumes". A better wording would be "mounts the volumes of the intercepted container".

**Comment by jckos** [comment]
Is there any way to get the php container volumes (actually I need the the credentials mounted to the php container)? The thing is that we need to run both apps (nginx+php) locally and therefore we need the mounted secrets from the php-fpm container (nginx and php are communicating through the unix socket).

**Comment by thallgren** [comment]
You can intercept both containers, but you'll need to use the [enterprise version](https://www.getambassador.io/telepresence-pricing) in order to do that, because the OSS version will only support one simultaneous intercept per pod.

The alternative is to move one of the containers to another pod so that you can intercept both using the OSS version.

I'm closing this issue, because Telepresence does what it's supposed to do. @cindymullins-dw, perhaps you can create a ticket for getambassador.io to correct the docs?

**Comment by jckos** [comment]
Thank you for clarification and suggestion.
