### ISSUE TITLE
Helm upgrade issue 2.19.6

### ISSUE THREAD

**Issue by vstepko** [telepresenceio/telepresence#3654]
**Describe the bug**
If you have installed the telepresence version 2.19.6 and try to use the command:
`telepresence helm upgrade`
The upgrade is stuck because Helm generated the k8s manifest try to download the image
`docker.io/datawire/tel2:2.19.6`

But can't 
because the last image that for now exists on docker hub is 2.19.1:

![image](https://github.com/user-attachments/assets/e87b3ae3-09d8-4a6c-b183-885eecd3f2f1)

**To Reproduce**
1. install telepresence client version 2.19.6
2. use `telepresence helm upgrade`
3. See the error on k8s cluster

**Expected behavior**
Helm Chart generates manifests with the correct image version.

**Versions (please complete the following information):**
 - 2.19.6

**Comment by thallgren** [comment]
There seem to be some confusion between OSS and Enterprise versions here. The datawire/tel2 is the OSS version of the traffic-manager. There's no 2.19.6 version of OSS released just yet.
Perhaps try a telepresence helm uninstall first to resolve this confusion?

**Comment by thallgren** [comment]
Closing this since no further info was provided.
