### ISSUE TITLE
helm chart version 2.19.1 missing secret list and watch for mutator-webhook-tls

### ISSUE THREAD

**Issue by GuyCarmy** [telepresenceio/telepresence#3657]
looks like the helm chart was uploaded to the repo (im using helm repo add datawire https://getambassador.io/) before [this](https://github.com/telepresenceio/telepresence/commit/96c8de8f753b5f1147ca2f97e9a8da424c4f35c4) commit. 
so the version in the chart is without the list and watch permissions but the code from the image of 2.19.1 includes the logic that use this permissions.

(i was getting `failed to list *v1.Secret: secrets "mutator-webhook-tls" is forbidden` and `Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "mutator-webhook-tls" is forbidden`)

since this is the last stable OSS version of telepresence, this is the version of helm chart i install in this version in the cluster.

any chance to re-upload the chart with the fix?
or is there another source to install the chart from? (i see the repo is under "getambassador.io" and im getting a little confused what is OSS and what is for enterprise customers).

**Comment by GuyCarmy** [comment]
@thallgren if I have to rephrase- is there an helm repo with the OSS versions of the chart? or should i package and upload it to my own?

**Comment by thallgren** [comment]
We don't currently publish a OSS helm-repo. You can use `telepresence helm install/update` to use the helm chart that is embedded with the binary.

**Comment by thallgren** [comment]
If you must use a helm chart, then my last comment in #3649 may provide some guidance.
