### ISSUE TITLE
Setup telepresence

### ISSUE THREAD

**Issue by dvorobiov** [telepresenceio/telepresence#366]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'hive', '--namespace', 'dev', '--docker-run', '--rm', '-it', '-v', '/Users/user/Code/hive:/service', 'frolvlad/alpine-oraclejdk8']`
Version: `0.72`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.8.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ip-192-168-1-141.eu-central-1.compute.internal 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.72/libexec/lib/python3.6/site-packages/telepresence/main.py", line 255, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.72/libexec/lib/python3.6/site-packages/telepresence/main.py", line 2382, in go
    runner, args
  File "/usr/local/Cellar/telepresence/0.72/libexec/lib/python3.6/site-packages/telepresence/main.py", line 1531, in start_proxy
    run_id=run_id,
  File "/usr/local/Cellar/telepresence/0.72/libexec/lib/python3.6/site-packages/telepresence/main.py", line 904, in get_remote_info
    format(deployment_name)
RuntimeError: Telepresence pod not found for Deployment 'hive'.

```

Logs:

```
don't match.
 121.8 TL | [106] Capturing: (['kubectl', '--context', 'eucentral1.dev.perseus.de', '--namespace', 'dev', 'get', 'pod', '-o', 'json', '--export'],)...
 122.0 TL | [106] captured.
 122.0 TL | Checking {'app': 'perseus', 'component': 'gophish', 'pod-template-hash': '3512513114'} (phase Running)...
 122.0 TL | Labels don't match.
 123.0 TL | [107] Capturing: (['kubectl', '--context', 'eucentral1.dev.perseus.de', '--namespace', 'dev', 'get', 'pod', '-o', 'json', '--export'],)...
 123.2 TL | [107] captured.
 123.2 TL | Checking {'app': 'perseus', 'component': 'gophish', 'pod-template-hash': '3512513114'} (phase Running)...
 123.2 TL | Labels don't match.
 124.2 TL | [108] Capturing: (['kubectl', '--context', 'eucentral1.dev.perseus.de', '--namespace', 'dev', 'get', 'pod', '-o', 'json', '--export'],)...
 124.5 TL | [108] captured.
 124.5 TL | Checking {'app': 'perseus', 'component': 'gophish', 'pod-template-hash': '3512513114'} (phase Running)...
 124.5 TL | Labels don't match.

```

**Comment by ark3** [comment]
I'm sorry you got a crash instead of a proper error message; we're working on that! 

It looks like Telepresence tried to swap your deployment but could not find its pod. Please send the full telepresence.log as a Github gist.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
