### ISSUE TITLE
Root daemon does not start (socket does not exist)

### ISSUE THREAD

**Issue by b-abel** [telepresenceio/telepresence#3660]
**Describe the bug**

The root daemon does not start. When using version 2.19.1 the output looks like the following:

```
$ telepresence connect
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /Users/bub1be/Library/Logs/telepresence '/Users/babel/Library/Application Support/telepresence'
Password:
telepresence connect: error: daemon service did not start: dial unix /var/run/telepresence-daemon.socket: file does not exist; this usually means that the process is not running
```

With older versions of telepresence, the root daemon also did not start but the error message was swallowed.

**Expected behavior**
The root daemon starts.

**Versions**
```
$ telepresence version
OSS Client     : v2.19.1
Root Daemon    : not running
OSS User Daemon: v2.19.1
Traffic Manager: not connected
```

Running on ARM based Mac with macOS Ventura 

**VPN-related bugs**
The bug does not seem to be VPN related but I use Cisco AnyConnect

**Comment by thallgren** [comment]
This is probably due to your settings in the sudoers file. Do you have a timestamp_timeout=0?
More info in #3551

**Comment by b-abel** [comment]
Hi @thallgren, thank you for your answer. This was very helpful! I have this setting indeed. Starting the root daemon manually as described in the linked ticket works.
