### ISSUE TITLE
User Daemon: Not running

### ISSUE THREAD

**Issue by yuridekim** [telepresenceio/telepresence#3672]
**Describe the bug**

I managed to manually start the root daemon but it seems like the user daemon is not running as well. Is there any way to solve this?
Because of this I cannot either connect, gather-logs, or call status for telepresence.

When I look at the logs, nothing is there in daemon.log or connector.log

```
**To Reproduce**
Steps to reproduce the behavior:
1. sudo telepresence daemon-foreground /Users/name/Library/Logs/telepresence '/Users/name/Library/Application Support/telepresence'
2. telepresence connect

**Versions (please complete the following information):**
➜  ~ telepresence version
Client     : v2.19.6
Root Daemon: v2.19.6
User Daemon: not running

**Comment by thallgren** [comment]
My guess is that you have dormant processes running as a result of previous attempts, and that telepresence is unable to contact them. Check for processes name telepresence and kill all of them, then try again.
The reason you need to start the root daemon manually is probably related to this [PR](/telepresenceio/telepresence/pull/3669).
