### ISSUE TITLE
telepresence connect: error: connector.Connect: failed to connect to root daemon

### ISSUE THREAD

**Issue by roman-bober-rmb** [telepresenceio/telepresence#3690]
[telepresence_logs.zip](https://github.com/user-attachments/files/17179278/telepresence_logs.zip)
**Describe the bug**
Failed to Connect to my cluster

telepresence connect: error: connector.Connect: failed to connect to root daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded

See logs for details (2 errors found): "/home/roman/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .

**Comment by cindymullins-dw** [comment]
Can you enable debug logs and run the connect again?  Those logs should provide more information.
`telepresence loglevel debug` will enable debug logs for about 30 minutes which should be enough time to capture this issue.

**Comment by thallgren** [comment]
This was resolved in our community slack. Apparently a problem with WSL `networkingMode` (use NAT, not mirrored).
