### ISSUE TITLE
Add back arm64 docker builds

### ISSUE THREAD

**Issue by applike-ss** [telepresenceio/telepresence#3696]
**Describe the bug**
There was arm64 docker support for telepresence in 2.19, please add it back to 2.20.

refs:
* https://hub.docker.com/r/datawire/tel2/tags?name=2.19
* https://github.com/telepresenceio/telepresence/pkgs/container/tel2

before:
![image](https://github.com/user-attachments/assets/4b22e43d-f460-40aa-bc89-666318cc8cec)

now:
<img width="1052" alt="Bildschirmfoto 2024-10-07 um 16 18 02" src="https://github.com/user-attachments/assets/8d3ede1c-aabc-461f-a8d8-842c26a8a475">

**Comment by thallgren** [comment]
The image ghcr.io/telepresenceio/tel2:2.20.0 is supposed to be multi-platform (amd64 and arm64). I just republished it and retested on my M1, and it works fine. Based on that, I'm closing this ticket. Feel free to reopen if you still experience problems with it.

**Comment by applike-ss** [comment]
I did get am exec error with the image yesterday. After that the sha256 of that image has changes and now in fact it is arm64 compatible. Thanks!
