### ISSUE TITLE
Homebrew for OSS version not working

### ISSUE THREAD

**Issue by mkantzer** [telepresenceio/telepresence#3697]
**Describe the bug**

Looking at https://github.com/telepresenceio/telepresence/issues/3609, there should be an OSS version available for installation via:

`brew install datawire/blackbird/telepresence-oss`

However, there don't seem to be any present:

```
❯ brew search telepresence
==> Formulae
datawire/blackbird/telepresence ✔                         datawire/blackbird/telepresence-arm64                     datawire/blackbird/telepresence-legacy

==> Casks
teleport-connect

❯ brew install datawire/blackbird/telepresence-oss
Warning: No available formula or cask with the name "datawire/blackbird/telepresence-oss". Did you mean datawire/blackbird/telepresence, datawire/blackbird/telepresence-arm64 or datawire/blackbird/telepresence-legacy?
```

Which means there isn't one there?

**To Reproduce**

1. Run `brew search telepresence`
2. Observe no OSS formula
3. Run `brew install datawire/blackbird/telepresence-oss`
4. See warning above

**Expected behavior**

`brew install datawire/blackbird/telepresence-oss` results in an installed OSS version of telepresence.

**Additional context**

**Comment by thallgren** [comment]
We have moved the tap to telepresenceio. Try:
```
brew install telepresenceio/telepresence/telepresence-oss
```
I'll update the documentation with this info.

**Comment by thallgren** [comment]
Docs updated.
