### ISSUE TITLE
Install specific version of OSS telepresence via brew

### ISSUE THREAD

**Issue by FarhanSajid1** [telepresenceio/telepresence#3703]
Hey all, I saw this [changeset](https://github.com/telepresenceio/telepresence/commit/6cc5de6604b89357cae5e0789dbe9adb686bb290#diff-39c2a7f9969b328c0d95f4fd6be37cc802a5d5f40706aee8c73d6329542db86aR6)

which enables the OSS version of telepresence on brew. However, how do we install a specific version? For example, I would like to install version 2.19.0, but I don't see a way to install this, I have tried the following:

```
 brew install telepresenceio/telepresence/telepresence-oss@2.19.0
Warning: No available formula or cask with the name "telepresenceio/telepresence/telepresence-oss@2.19.0". Did you mean telepresenceio/telepresence/telepresence-oss?
``` 

The only thing that would work is:
```
brew edit telepresenceio/telepresence/telepresence-oss
# This script is generated automatically by the release automation code in the
# Telepresence repository:
class TelepresenceOss < Formula
  desc "Local dev environment attached to a remote Kubernetes cluster"
  homepage "https://telepresence.io/"
  version "2.20.1-rc.0" <- change this
```

And then install. However this seems hacky. What is the correct way of doing this? Seems like we can allow version to be a variable of some sort that we can override when installing

Alternatively we can install this via curl

```
sudo curl -fL https://app.getambassador.io/download/tel2oss/releases/download/v2.19.0/telepresence-darwin-arm64 -o /usr/local/bin/telepresence
sudo chmod +x /usr/local/bin/telepresence
```

However it's a bit simpler to just manage via brew

**Comment by thallgren** [comment]
The 2.19.0 version has never been published to that tap. It only contains versions >= 2.20.0.

**Comment by thallgren** [comment]
I read up on brew. It has virtually no support for versions, and that is per design. I found [this comment](https://github.com/orgs/Homebrew/discussions/155#discussioncomment-134587) particularly enlightening.

We will keep the tap tagged (with version tags), so you should be able to checkout the tag that you want and install that.
