### ISSUE TITLE
Support policy for Telepresence

### ISSUE THREAD

**Issue by shazib-summar** [telepresenceio/telepresence#3709]
Hello. I'm looking to understand any Support policy or End of Life policy for Telepresence. For example, Crossplane supports N-2 releases ([ref](https://docs.crossplane.io/latest/learn/release-cycle/)). Is there any such policy for Telepresence. 

I came across https://github.com/telepresenceio/telepresence/security#security-policy which refers to "Security updates", but I'm not sure if this can be used as the EOL policy as well. 

Thanks in advance.

**Comment by thallgren** [comment]
The OSS product is completely free of charge and is supported by its community. There's no formal support or EOL policy. For regular support, EOL, and other license questions, I recommend that you contact sales at [Ambassador](https://www.getambassador.io/products/telepresence) and look at their enterprise offering.
