### ISSUE TITLE
developing.md suggested disused, non-working local testing strategy

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#371]
developing.md says:

```
When doing local development you will typically run all tests by doing:

> `make minikube-test`
```

but this results in a number of failures and "minikube support is untested" now (@ark3 ).  

Minikube support should be repaired (minikube support is a requirement).  This will also have the benefit that `make minikube-test` can again be used for local testing.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
