### ISSUE TITLE
Feature Request: Intercept Service while opting out of live traffic

### ISSUE THREAD

**Issue by sruffatti** [telepresenceio/telepresence#3713]
**Please describe your use case / problem.**
We are trying to figure out the best way to handle app config for local development. Telepresence being able to retrieve env vars and secrets for a given pod is very intriguing. However, we do not want to intercept a service to get the env vars because we don't want to receive live traffic. If we need to intercept a service to get the env vars, then we'd like to opt-out of receiving live traffic. 

**Describe the solution you'd like**
The ability to intercept a Pod to get env vars and opt-out of receiving live traffic.

**Comment by thallgren** [comment]
@sruffatti , while looking at this, I'm contemplating adding a new command. Sure, we could just add a `--traffic=false` flag or similar to the existing intercept command, but the term "intercept" is very much about that traffic. In addition to this, a `--traffic=false` would also invalidate existing flags like `--port`, `--address`, and `--mechanism`.

Being the reporter here, do you have any proposals for a name for this new command?

**Comment by sruffatti** [comment]
New command makes the most sense to me and I agree "intercept" is very much about the traffic. 

Here are a few ideas, "inspect", "import", "ingest", "environment"... @thallgren

**Comment by thallgren** [comment]
Thanks. Those a all good. My favourite is "ingest". It's not loaded with other meanings in the developer world and it covers something that provides an environment, mounts, and the ability to map ports to a remote localhost fairly well.

**Comment by thallgren** [comment]
Closed by #3736
