### ISSUE TITLE
arm64 support for windows 🚀 

### ISSUE THREAD

**Issue by soerennielsen** [telepresenceio/telepresence#3720]
**Please describe your use case / problem.**
I would like an arm64 build of telepresence. 

While arm64 windows 11 can certainly emulate and run amd64 binaries it cannot do so for drivers, namely the tun driver, therefore it is not possible (afaik) to run telepresence on my snapdragon elite PC. 

I do not believe that there is any workaround.

**Describe the solution you'd like**
A new build target and output for arm64 on win.

**Describe alternatives you've considered**
None.

**Versions (please complete the following information)**
Telepresence 2.20.2 (though I cannot run this!)
Kubernetes 1.30.1

**Additional context**
I searched quite a bit. 
It seems that wintun does support arm64 in their current release (0.14.1).
 
I checked _.github/workflows/release.yaml_ and it seems to explixitly exclude arm64 :( 
I checked _build-aux/main.mk_ file and there is a special windows clause that locks the win build to amd64 regardless of architecture it runs on (but that will likely only be amd64 because of the release.yaml file). 

There might well be a good reason for these provisions but I could not find any issues or comments about it. Perhaps it is simply the age-old confusion with "x86_64" versus "amd64" that has been canonilized this way.

I will be happy to assist in testing, however my makefile/go skills is probably not up for the task of fixing it myself :-|

**Comment by thallgren** [comment]
This seems like a very reasonable request. It would be great if someone with an arm64 windows could help out and provide a PR.

**Comment by P0lip** [comment]
@soerennielsen would you be so kind and give [v2.21.0-rc.2](https://github.com/telepresenceio/telepresence/releases/tag/v2.21.0-rc.2) a try?
It's the first release that contains Windows arm64 TP client.

**Comment by soerennielsen** [comment]
Yes, Will give it a go and let you know :-)

**Comment by thallgren** [comment]
Telepresence 2.21.0 has been released.

**Comment by soerennielsen** [comment]
Sorry to be late in, I can confirm that it worked perfectly for me :-)

Tested on win11, arm64. 

Tested that local workloads can connect to cluster resources through Ambassedor. DNS works, remappings, tunnelling, network policies (had to open a few for Ambassedor).
I have not tested interception as my workflow is not that, but I see no reason it shouldn't work.


THANKS!
