### ISSUE TITLE
Requests from same sessions are not getting load balanced across pods when sent via telepresence

### ISSUE THREAD

**Issue by VasaviMadhurima** [telepresenceio/telepresence#3721]
**Describe the bug**
Requests from a single session sent to k8s services via telepresence are not getting load balanced across service pods. Telepresence is introducing some sort of sticky sessions.

**To Reproduce**
1. Deploy a simple service in k8s with minReplicas set to atleast 2
2. Install telepresence locally and run `telepresence connect --manager-namespace <telepresence-namespace> --mapped-namespaces <service-namespace>`
3. Using curl to send multiple requests to the service on the same connection via telepresence - `curl http://<service-name>.<service-namespace>:<service-port>/ping http://<service-name>.<service-namespace>:<service-port>/ping http://<service-name>.<service-namespace>:<service-port>/ping http://<service-name>.<service-namespace>:<service-port>/ping http://<service-name>.<service-namespace>:<service-port>/ping http://<service-name>.<service-namespace>:<service-port>/ping http://<service-name>.<service-namespace>:<service-port>/ping http://<service-name>.<service-namespace>:<service-port>/ping`
4. Notice that all requests are routed to the same pod.
5. Send multiple requests in separate curl commands. In this case the requests are load balanced across the pods.
6. Hit the service directly instead of telepresence and notice that requests are load balanced again.

**Expected behavior**
Telepresence should not introduce sticky sessions.

```
❯ telepresence version
OSS Client     : v2.18.0
OSS Root Daemon: v2.18.0
OSS User Daemon: v2.18.0
Traffic Manager: not connected
```

**Comment by thallgren** [comment]
My guess is that this is due to curl honoring a connection keep-alive somehow. Not sure why Telepresence would alter that though, as the OSS version of TP doesn't care about http headers at all. What version are you using for the traffic-agent? (a `telepresence version` while connected will reveal this).

**Comment by VasaviMadhurima** [comment]
```
❯ telepresence version
OSS Client     : v2.18.0
OSS Root Daemon: v2.18.0
OSS User Daemon: v2.18.0
Traffic Manager: v2.19.0
Traffic Agent  : docker.io/datawire/ambassador-telepresence-agent:1.14.5
```

**Comment by thallgren** [comment]
Ok, you're using an OSS client to access an Enterprise traffic-manager/traffic-agent. Then this stickyness makes more sense, because the enterprise traffic-agent uses Envoy and http-header based routing. I'll therefore close this ticket and kindly ask you to bring this up with Ambassador support.

**Comment by VasaviMadhurima** [comment]
@thallgren I am seeing the same issue with OSS traffic manager
```
❯ telepresence version
OSS Client         : v2.17.0
OSS Root Daemon    : v2.17.0
OSS User Daemon    : v2.17.0
OSS Traffic Manager: v2.20.3
```

**Comment by thallgren** [comment]
It's not the traffic-manager that is responsible for this behavior. It's the traffic-agent. A more recent version of the client will show you what traffic-agent you're using.
