### ISSUE TITLE
Telepresence chart cannot be included as a child Helm chart unless parent chart is called "traffic-manager"

### ISSUE THREAD

**Issue by dansimone** [telepresenceio/telepresence#3731]
**Please describe your use case / problem.**

I saw this mentioned in another [issue](https://github.com/telepresenceio/telepresence/issues/2329) that was closed almost 2 years ago regarding the ability to include Telepresence as the child chart of another Helm chart.

It would be useful to be able to include the Telepresence Helm chart as the child Helm chart.  Today, this is only possible if the parent chart is literally called "traffic-manager", due to [this](https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/templates/_helpers.tpl#L14) check in `_helpers.tpl`.

I saw a justification for why this was done in https://github.com/telepresenceio/telepresence/issues/2329, but it seems that an alternative would be to:
- Allow a top-level `name` to be specified in the [values.yaml](https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/values.yaml), defaulting to "".
- $name can be set to the value of `.name` if set, otherwise fall back to `.Release.Name`.

But actually, in the RBAC setup yamls, I don't see anywhere where it matters what the Release.Name was, unless I am missing something.  Is there some other use for this constraint?

**Versions (please complete the following information)**
- v1.20.3

**Comment by thallgren** [comment]
This seems very reasonable. @dansimone would you be able to help with this and create a PR?

**Comment by dansimone** [comment]
@thallgren, absolutely.  Please have a look at this: https://github.com/telepresenceio/telepresence/pull/3737/files.  I'll send this to the Slack channel shortly.

**Comment by dansimone** [comment]
Ok, looks like I can't join the Slack channel (datawire-oss) mentioned in the PR template because of: 
```
You can use any account with the domain:
canstar.com.au
box.com
```

@thallgren, would you mind sending this out for review?

**Comment by thallgren** [comment]
The link in the PR template was out of date. I've changed it to:

> in #telepresence-oss channel on the [CNCF Slack](https://slack.cncf.io/)

Closing this now, since your PR has been merged and will be included in the next release.
