### ISSUE TITLE
DNS not working properly when using telepresence with VPN

### ISSUE THREAD

**Issue by gabrielpulga** [telepresenceio/telepresence#3735]
**Describe the bug**
When using Telepresence with the NordLayer VPN, DNS resolution for cluster-local addresses (e.g., `*.svc.cluster.local`) fails. For example, attempting to resolve `service-api.service.svc.cluster.local` results in a timeout. This issue occurs only when the VPN is active; DNS resolution works correctly without the VPN.  

I've already set the cluster subnect using the **allowConflicting** configuration

**To Reproduce**
1. Start the NordLayer VPN and connect to the Kubernetes cluster using `telepresence connect`.  
2. Run `nslookup service-api.service.svc.cluster.local`.  
3. Observe the DNS resolution timeout.  

## Expected behavior  
Cluster-local DNS names (e.g., `*.svc.cluster.local`) should resolve correctly when using Telepresence with NordLayer VPN, as they do without the VPN.  

## Versions  
- Telepresence Version: v2.20.0  
- Operating System: Windows 10 Pro  
- Kubernetes Environment: AKS (Azure Kubernetes Service)  
- Kubernetes Version: 1.26.6  

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
## VPN-related bugs  
- VPN Client: NordLayer  
- How the VPN pushes DNS: Replaces local DNS servers with internal resolvers on the network.

**Comment by thallgren** [comment]
Please enable loglevel debug and provide the daemon.log and traffic-manager log.
Initial guess is that the Northlayer VPN overrides DNS in a somewhat intrusive way, so that the Telepresence DNS never comes into play. The requested logs will reveal if that guess is accurate.

**Comment by thallgren** [comment]
Hey @gabrielpulga , any progress on this?

**Comment by thallgren** [comment]
Closing due to lack of response from reporter.
