### ISSUE TITLE
unknown service telepresence.pro.manager.ProManager

### ISSUE THREAD

**Issue by iszhangsc** [telepresenceio/telepresence#3747]
The following diagram shows me how to do it

![image](https://github.com/user-attachments/assets/645f299a-604a-402f-80eb-64668380b465)

**Comment by thallgren** [comment]
You're using the enterprise version of Telepresence and questions for that version must be answered by the Ambassador support.
If that's not what you intended, then please look [here](https://www.telepresence.io/docs/install/client) for instructions on how to install the Open Source version.
