### ISSUE TITLE
Container method should let the user set the container name

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#376]
The goal is to let the user set the name of the container launched by Telepresence running the user's code, thereby making it comfortable for the user to `docker exec` or `docker kill` this container as needed.

Setting the name of the _proxy_ container, which is responsible for maintaining the Telepresence network setup, is _not_ the goal here.

The current code explicitly sets a random name for the user's container, rather than letting the user or Docker pick one. We should figure out why this is the case. If setting the name from within Telepresence is not necessary, then simply leaving out the explicit `--name=` in our code will take care of this.

**Comment by ark3** [comment]
Telepresence sets the name explicitly so that it can address that container explicitly as part of the shutdown process. Perhaps Telepresence can capture the container ID on launch and use that instead.

**Comment by ark3** [comment]
Or use a label.

**Comment by donnyyung** [comment]
This is no longer a problem in Telepresence 2 since you can pass in docker args directly to `--docker-run`: https://www.telepresence.io/docs/latest/reference/docker-run/
