### ISSUE TITLE
"--also-proxy hostname" finds one address for the hostname but misses any more

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#379]
`--also-proxy` is not much documented but https://www.telepresence.io/reference/methods suggests using it with a domain name to have traffic destined for that domain proxied via telepresence.

The implementation resolves names given in this way on the cluster, turning them into IPs which can be given to sshuttle which will do the developer-local part of the proxying.  But the implementation only looks up one IP per hostname:

```
import socket, sys, json
result = []
for host in sys.argv[1:]:
    result.append(socket.gethostbyname(host))
sys.stdout.write(json.dumps(result))
sys.stdout.flush()
```

because `socket.gethostbyname` only returns one result.  If there are multiple addresses associated with the domain name then all but one are missed and will not be proxied.

`socket.getaddrinfo` can be used to get all the addresses (at least at the time of its call; if DNS is reconfigured afterwards, telepresence won't notice but the user's application might; separate issue):

```
>>> pprint(set(x[-1] for x in socket.getaddrinfo('duckduckgo.com', 0) if x[:2] == (socket.AF_INET, socket.SOCK_STREAM)))
set([('107.21.1.61', 0),
     ('184.72.106.52', 0),
     ('184.72.115.86', 0),
     ('23.21.193.184', 0)])
>>> 
```

**Comment by ark3** [comment]
Fixed by #1167
