### ISSUE TITLE
Tests sometimes fail with KUBERNETES_SERVICE_HOST KeyError

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#386]
A couple builds on travis have had a test fail with this:

```
Traceback (most recent call last):
  File "/home/travis/build/datawire/telepresence/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/home/travis/build/datawire/telepresence/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/home/travis/build/datawire/telepresence/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/home/travis/build/datawire/telepresence/telepresence/vpn.py", line 198, in connect_sshuttle
    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
KeyError: 'KUBERNETES_SERVICE_HOST'
```

Most recently the test was `test_disconnect` but I think a previous failure happened in a different test, perhaps `test_swapdeployment`.

**Comment by ark3** [comment]
The value of that environment variable is used by `get_proxy_cidrs(...)` as the IP address of a service. 

In the future, we may be able to get the underlying answer from the API server:
https://github.com/kubernetes/kubernetes/issues/25533
https://github.com/kubernetes/kubernetes/issues/46508

I have not seen this failure in a while. Then again, we don't run Telepresence as often in CI now, thanks to improvements in the test suite.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
