### ISSUE TITLE
Cannot install on RedHat 7

### ISSUE THREAD

**Issue by AssafKatz3** [telepresenceio/telepresence#388]
Hi,
I am getting the log:
Detected operating system as rhel/7.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/datawireio/telepresence/config_file.repo?os=rhel&dist=7&source=script
curl: (6) Could not resolve host: packagecloud.io; Name or service not known

Unable to run: 
    curl https://packagecloud.io/install/repositories/datawireio/telepresence/config_file.repo?os=rhel&dist=7&source=script

Double check your curl installation and try again.

Thanks

**Comment by plombardi89** [comment]
That's odd... as it's a DNS issue resolving [packagecloud.io](https://packagecloud.io/) which is a 3rd party service for hosting RPMs. 

What do you get if you `nslookup packagecloud.io` and `dig packagecloud.io`?

**Comment by AssafKatz3** [comment]
Hi,
Both aren't found. I set the http_proxy HTTP_PROXY and HTTPS_PROXY to company proxy and can access to https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz for example.
BTW, if it requires phyton3 as the installation script, it will fail anyway...
Thanks

**Comment by richarddli** [comment]
Telepresence does not require Python 3. It seems that this isn't a Telepresence issue, but an issue with how your company proxy is configured. Is it possible for you to do the installation outside of your company proxy?

**Comment by AssafKatz3** [comment]
Hi,
I found the problem with the proxy (It failed due to sudo) so I simply added -E to sudo command and it was successful:

> Generating yum cache for datawireio_telepresence...
> ...
> The repository is setup! You can now install packages.

But now I still have problem with next step:

> sudo -E yum install telepresence

Returns:

> datawireio_telepresence/x86_64/signature                                                                             |  836 B  00:00:00     
> datawireio_telepresence/x86_64/signature                                                                             |  951 B  00:00:00 !!! 
> datawireio_telepresence-source/signature                                                                             |  836 B  00:00:00     
> datawireio_telepresence-source/signature                                                                             |  951 B  00:00:00 !!! 
> No package telepresence available.
Thanks

**Comment by ark3** [comment]
It appears that Fedora packages do not work on Enterprise Linux. Can you help us figure out how to support EL/7? Please try installing from source. You'll need the EL/7 equivalents of the following Fedora packages to run Telepresence:

`python3 torsocks openssh-clients sshfs socat conntrack-tools`

Instructions to install from source are on [the installation page](https://www.telepresence.io/reference/install).

**Comment by AssafKatz3** [comment]
Hi,
I had tried to install from source, but the requirement of python3 cause conflicts with python2 which already installed as part of RedHat. I will rerun it and will send the details of the exact problem (I didn't save the log).
Thanks

**Comment by ark3** [comment]
Ah. Worst case, you'll have to install Python3 from source. Telepresence requires Python 3.5 or later. 

Thank you for your help with this.

**Comment by ark3** [comment]
The Telepresence documentation has a [list of dependencies](https://www.telepresence.io/reference/install.html#dependencies), but it does not explain how to install these dependencies on common platforms. We could use your help to fix this! Can someone please suggest how to install those dependencies on RedHat?

**Comment by donnyyung** [comment]
I'm not sure if this is still an issue on Telepresence 2 so adding a v2 label to this until we confirm it is or is not an issue.

**Comment by AssafKatz3** [comment]
Any update on it?
