### ISSUE TITLE
this connect-test should be able to use config parameter or alternatives

### ISSUE THREAD

**Issue by oreasono** [telepresenceio/telepresence#389]
https://github.com/datawire/telepresence/blob/271d8ca2295991177ac26ec9780219b92fa0a5a6/telepresence/local.py#L107

in many occasions there has no effective connection to google.com
for example enterprise's private cluster, military, or north Korea.

**Comment by ark3** [comment]
We could also try `kubernetes.default` for the connectivity test, though not every RBAC setup will allow that either.

**Comment by benmullin333** [comment]
This test set off security alarms at my work... :( . Please remove this ping to google.com 80

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
