### ISSUE TITLE
Telepresence should send all traffic to the cluster (container method)

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#391]
It seems #320 is also an issue in container mode. We should consider having all container traffic go to the cluster, much like inject-tcp mode works.

**Comment by ark3** [comment]
FWIW, @plombardi89 worked around this issue (and #320) in Kubernaut by putting an IP address in the generated Kubernetes configuration for Kubernaut clusters. This avoids the DNS lookup entirely. Regardless, we should still consider sending all container traffic to the cluster. Among other things, that would avoid some cluster analysis on startup, thereby speeding things up.

**Comment by ark3** [comment]
Plan:
- [ ] Use `kubectl exec` to grab the hostname and resolv.conf of the proxy pod. See `telepresence.remote_env._get_remote_env(...)` for an example. Perhaps even do this in the same place; these are components of the remote environment in some sense.
- [ ] Use the captured info to modify the appropriate `docker run` command with `--hostname` and `--dns*` flags as described in the options link above. You will need to figure out whether these flags need to be used for the network container or the user container (or both).
- [ ] Replace the sshuttle invocation in the network container with one that proxies `0/0` instead of a subset of the IP space. You should not need `--dns` if the above DNS configuration step worked correctly for the user container.
- [ ] Actively disallow (by erroring out) Telepresence options that are intended for the vpn-tcp method.

**Comment by ptemmer** [comment]
How can I direct traffic to a specific IP address to NOT go to the cluster, and instead go to my local machine (which in the end gets routed through a VPN)?
