### ISSUE TITLE
telepresence startup error trying to detect minishift

### ISSUE THREAD

**Issue by bnusunny** [telepresenceio/telepresence#396]
### What were you trying to do?

run telepresence

### What did you expect to happen?

telepresence shell come up

### What happened instead?

the follow error messages are printed out.

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.73`
Python version: `3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]`
kubectl version: `Client Version: v1.5.1`
oc version: `oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.linkdesk.tk:443
openshift v1.5.1
kubernetes v1.5.2+43a9be4`
OS: `Linux harold-pc 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/main.py", line 432, in go
    args.in_local_vm = check_if_in_local_vm()
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/main.py", line 427, in check_if_in_local_vm
    ip = runner.get_output(["minishift", "ip"]).strip()
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 95, in get_output
    result = str(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['minishift', 'ip']' returned non-zero exit status 1.

```

Logs:

```
   0.0 TL | Telepresence launched at Tue Jan  9 10:57:09 2018
   0.0 TL |   ['/usr/bin/telepresence']
   0.0 TL | Scout info: {'latest_version': '0.72', 'application': 'telepresence', 'notices': []}
   0.0 TL | Context: linkdesk-staging/openshift-linkdesk-tk:443/sunh, namespace: linkdesk-staging, kubectl_command: oc
   0.0 TL | [1] Capturing: (['minishift', 'ip'],)...
Error getting IP: Host does not exist: "minishift"

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
