### ISSUE TITLE
Documentation shows that of latest master, rather than released version

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#4]
We should switch to Netlify (and enable HTTPS) instead of Github Pages since if we can figure out how to make it only build on tagged builds. Or perhaps push to netlify from Travis in the release process, instead of relying on Netlify's github hooks

**Comment by ark3** [comment]
FWIW, we have since switched to Netlify and do have HTTPS, but this issue still stands. Netlify is configured to deploy from master.
