### ISSUE TITLE
Project based configuration

### ISSUE THREAD

**Issue by tristanpemble** [telepresenceio/telepresence#411]
I would like to define and version control a configuration file that Telepresence can use, similar to Forge's `service.yaml`.

Ideally if I am fully bought into the Datawire ecosystem, my developers can do something as straight forward as this to begin development with Kubernetes:

```
git clone git@github.com:my-org/my-project.git
cd my-project
minikube start
forge deploy
telepresence run web
```

and begin editing code locally to see changes as they work. being able to define different scenarios would be helpful -- basically all the same usecase for Telepresence:

- running a daemon from your local project folder
- entering an interactive shell for debugging
- etc.

it might also be worth considering letting Telepresence integrate with Forge, somehow. that way we could reuse the environment configuration/Jinja2 variables to configure Telepresence.

this type of use case also might be better suited for another tool. I was considering writing a simple wrapper if it does not seem like an appropriate addition to Datawire's toolset.

this could easily be done with a Makefile. I created this issue for a discussion generally on how Datawire sees bridging a gap between these tools

**Comment by ofpiyush** [comment]
I would also love some variant of this. We've not tried forge out yet, but the ability to set 1 global and 1 local config file is high in our list of needs as well.

See #363

**Comment by richarddli** [comment]
The use case makes perfect sense. We've been exploring ways to integrate Forge and Telepresence together. Our users seem to be pretty happy with the Forge/Ambassador integration which uses Jinja2 etc like you propose.

If you're following the commits right now, we're mostly working on speeding up the development cycle for Telepresence, which requires disentangling us from Travis and revamping the test suite. In the meantime, we can use this issue to discuss requirements & design in more detail.

**Comment by donnyyung** [comment]
I think forge has been mostly discontinued? But otherwise, Telepresence 2 does have a notion of a config file: https://www.getambassador.io/docs/telepresence/latest/reference/config . Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
