### ISSUE TITLE
Telepresence issue on high sierra with Minikube

### ISSUE THREAD

**Issue by gcmalloc** [telepresenceio/telepresence#424]
I am telepresence on osx high-sierra with minikube using the following command:
```
telepresence --run-shell
```

This results in loss of connectivity to the minikube vm.

I checked the packet going out of the host, they are sent with the minikube vm ip address without `nat` taking place. 

The firewall rules dumped with `sudo pfctl -sr` are as followed:

Before:

```
No ALTQ support in kernel
ALTQ related functions disabled
scrub-anchor "com.apple.internet-sharing" all fragment reassemble
pass on lo all flags S/SA keep state
anchor "sshuttle6-12300" all
anchor "sshuttle-12300" all```
```
After running `telepresence --run-shell`:
```
pass on lo all flags S/SA keep state
anchor "sshuttle6-12300" all
anchor "sshuttle-12300" all
```

Resetting my external facing network interface restore the connectivity of the vm. 
I am running telepresence 0.73 and minikube v0.24.1.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
