### ISSUE TITLE
Container tests aren't run on macOS CI

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#433]
macOS users actually use Telepresence, though, and presumably also the container method.  If we want them to have a good experience, we need CI for this case.

Unfortunately <https://discuss.circleci.com/t/macos-and-docker-support/10097> but maybe we don't actually need explicit support from CircleCI.  See <https://docs.docker.com/docker-for-mac/install/> and <https://apple.stackexchange.com/questions/73926/is-there-a-command-to-install-a-dmg>.

**Comment by donnyyung** [comment]
We should still do this + I think we'll have a way to do this once we support Windows in CI since it'll use a similar mechanism for macOS.

**Comment by josecv** [comment]
Yep, we are planning on delivering #92 , which will include support for running Windows in CI -- at that point it should be easy to add tests for MacOS
