### ISSUE TITLE
error: Scaling the resource failed with: serializer for text/plain; charset=utf-8 doesn't exist; Current resource version Unknown

### ISSUE THREAD

**Issue by liangzuohua** [telepresenceio/telepresence#445]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'frontend', '--expose', '8081:80', '--run-shell']`
Version: `0.75`
Python version: `3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.8.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin localhost 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/main.py", line 480, in go
    runner, args
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/main.py", line 274, in start_proxy
    runner, args
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/deployment.py", line 128, in swap_deployment
    apply_json(new_deployment_json)
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/deployment.py", line 101, in apply_json
    ["delete", "deployment", deployment_name],
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 130, in check_kubectl
    self.kubectl(context, namespace, kubectl_args), **kwargs
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 84, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['kubectl', '--context', 'ops', '--namespace', 'default', 'delete', 'deployment', 'frontend'],)' returned non-zero exit status 1.

```

Logs:

```
 '8081:80', '--run-shell']
   0.0 TL | Scout info: {'latest_version': '0.72', 'application': 'telepresence', 'notices': []}
   0.0 TL | Context: ops, namespace: default, kubectl_command: kubectl
   0.0 TL | [1] Capturing: (['kubectl', '--context', 'ops', 'cluster-info'],)...
   0.3 TL | [1] captured.
   0.3 TL | [2] Capturing: (['ssh', '-V'],)...
   0.3 TL | [2] captured.
   0.3 TL | [3] Capturing: (['which', 'torsocks'],)...
   0.3 TL | [3] captured.
   0.3 TL | [4] Capturing: (['which', 'sshfs'],)...
   0.3 TL | [4] captured.
   0.3 TL | [5] Capturing: (['kubectl', '--context', 'ops', '--namespace', 'default', 'get', 'deployment', '-o', 'json', '--export', 'frontend'],)...
   0.6 TL | [5] captured.
   0.6 TL | [6] Running: (['kubectl', '--context', 'ops', '--namespace', 'default', 'delete', 'deployment', 'frontend'],)...
   3.2 6 | error: Scaling the resource failed with: serializer for text/plain; charset=utf-8 doesn't exist; Current resource version Unknown
   3.2 TL | [6] exit 1.

```

**Comment by ark3** [comment]
Sorry about the crash. What is the version of your Kubernetes cluster server (`kubectl version --short`)? Is there something special about the `frontend` deployment? Does running the crashing command manually work for you? `kubectl --context ops delete deployment frontend`

I'm not sure what's going with `kubectl`'s odd message (`serializer for text/plain; charset=utf-8 doesn't exist`), but my first guess would be that there's an incompatibility between your `kubectl` and your cluster. This is entirely a guess. Thoughts?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
