### ISSUE TITLE
Container method doesn't work while a vpn-tcp session is running

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#456]
For this specific issue, figure out why, and whether we can make it work. 

See #447 for a broader discussion and a lot of useful logs.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
