### ISSUE TITLE
Document Telepresence dependencies

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#458]
Telepresence depends on a number of other executables (kubectl/oc, docker, socat, torsocks, sshuttle, conntrack, etc.). We should

- [x] List them all in one place in the documentation (1e44a1a)
- [x] Refer to this list on the installation page, particularly for installing from source (f868725)
- [ ] Suggest how to install them for various operating systems
- [ ] Explain what they do, in what circumstances they are needed, and why
- [x] Point to this info when Telepresence reports that a dependency is missing (d773051)

**Comment by donnyyung** [comment]
We've gotten rid of a lot of these dependencies in Telepresence 2, the only dependency I can think of that isn't noted is macfuse / sshfs, but the binary informs you that it's missing and turns off mounts when it isn't present, so I believe we can close this as it doesn't appear to be an issue with Telepresence 2. 

Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
