### ISSUE TITLE
Add a Minikube-specific vpn-like method

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#461]
Add another method that behaves similarly to the vpn-tcp method but only works when your cluster is running in a VM on your machine. See https://github.com/kubernetes/minikube/issues/38#issuecomment-351516904 and other examples in that issue comment thread. This approach might also help with Kubernetes for Docker for Mac (#449).

**Comment by plombardi89** [comment]
Can we perform any type of environment detection that just does the right thing so we don't need to add yet another mode?

**Comment by ark3** [comment]
Yes, we can detect when we're in MInikube, and we can maybe tell when network conditions are okay. And as I explained in #455, I'm against adding a bazillion switches to the command line; it's too complicated already. That said, auto-detection is not where I would want to start. 

Let's implement the feature as an explicit option (`--method vpn-tcp --force-minikube-mode`) first. Then we can figure out how to enable it automatically.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
