### ISSUE TITLE
Crash when context is unavailable/incorrect

### ISSUE THREAD

**Issue by bryantidd** [telepresenceio/telepresence#469]
### What were you trying to do?

telepresence --context cluster --namespace default --docker-run -i -t alpine /bin/sh

### What did you expect to happen?

get a shell in a container

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--context', 'cluster', '--namespace', 'default', '--docker-run', '-i', '-t', 'alpine', '/bin/sh']`
Version: `0.75`
Python version: `3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.9.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin eusadminssmbp3.corp.jmfamily.com 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/main.py", line 394, in go
    if cluster_setting["name"] == cluster:
UnboundLocalError: local variable 'cluster' referenced before assignment

```

Logs:

```
Not available
```

**Comment by ark3** [comment]
It looks like Telepresence did not find the Kubernetes context you specified; instead of reporting an error (something like `Could not find Kubernetes context 'cluster'`) it crashed. Sorry about that!

You can use `kubectl config get-contexts` to list the available contexts, and `kubectl config use-context` to choose one so you don't have to specify it subsequently.

**Comment by ark3** [comment]
This was fixed at some point:

```shell
$ telepresence --context bogus-context
T: Error: Unable to find cluster information

$ 
```
