### ISSUE TITLE
Failed to install on Linux Mint 18.2

### ISSUE THREAD

**Issue by Dobiasd** [telepresenceio/telepresence#486]
Linux Mint 18.2 basically is Ubuntu 16.04, so I expected it to work, however:
```bash
$ curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | sudo bash
sudo apt install --no-install-recommends telepresence
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package telepresence
```
Installing from source however works fine. :+1:

**Comment by ark3** [comment]
Given the workaround mentioned in #485, we could probably get away with pushing the Ubuntu Xenial (16.04) package to Mint Sonya (18.2). 

The core problem here is that on platforms that are unsupported by Telepresence, the PackageCloud script succeeds but does not do anything useful. Trying to install then fails mysteriously.

**Comment by donnyyung** [comment]
I think this might still be an issue on Telepresence 2. Attaching the `v2` label until we confirm it is / is not an issue.
