### ISSUE TITLE
Report problems when using --expose with an existing deployment

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#496]
A user [creates a Telepresence deployment manually](https://www.telepresence.io/reference/connecting#running-telepresence-manually) and launches `telepresence --deployment ...`. If any `--expose` argument in this invocation is incompatible with the existing deployment, Telepresence should report an error. At the moment, incompatibilities are ignored and no errors are reported.

- [ ] When you use an existing deployment, Telepresence does not create services. As a result, if you try to `--expose` ports that are not already fronted by existing services, there will be no way to reach them. Telepresence should report this.

- [ ] If you try to `--expose` a privileged port (port < 1024) and the existing deployment does not run as root, the underlying port forwarding fails silently. Telepresence should report this. 

- [ ] Telepresence runs as a non-root user by default to support running on OpenShift and generally work better with privilege management via Kubernetes Security Contexts. See #131 for more information. To run the Telepresence image as root, the pod spec must contain the following. The documentation should mention this.

    ``` yaml
    "securityContext": {
        "runAsUser": 0
    }
    ```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
