### ISSUE TITLE
End-to-end tests should be able to test an installed Telepresence

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#503]
The tests should install Telepresence once using install.sh, add the install directory to the front of the PATH, make sure that's the Telepresence that will be run, and then use that one for the tests.

**Comment by ark3** [comment]
Doing this would cover #437 too.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since we do install telepresence in the end-to-end tests. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
