### ISSUE TITLE
The --swap-deployment auto-expose tests for containerPort != hostPort are skipped

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#505]
These should be unskipped.  They're skipped because they fail.  So, they should also be made to pass.

**Comment by exarkun** [comment]
Here's a configuration that results from the failing test I tried to add to cover X != Y.



  * The tests declare a new `HTTPServer(local_port=12330, remote_port=12331)` .

  * `run_telepresence_probe` respects this and passes an extra `--http-port 12330` to Telepresence but does not pass any `--expose` argument for this server

  * `prepare_service` creates a `Service` including a `ports` element with `port` of remote_port and `targetPort` of remote_port

  * `prepare_deployment` creates a `Deployment` which includes a `ports` element with a `containerPort` of local_port and a `hostPort` of remote_port

  * Telepresence swaps that out for a `Deployment` which includes a `ports` element with a `containerPort` of `remote_port` and a `hostPort` of remote_port (1)

  * `Pod` belonging to the `Deployment` includes a `ports` element that agrees with the `Deployment`

  * Telepresence proxy pod is actually listening on local_port

  * Local Docker container (--container) is actually listening on local_port

  * Test tries to connect to remote_port and fails



(1) This is actually due to a fix I tried to implement earlier which is probably wrong.  The unmodified behavior is very similar, the only difference is the `Deployment` and `Pod` have a `ports` element with `containerPort` set to `local_port` instead of `remote_port`.  Or, more verbosely:



  * Telepresence swaps that out for a `Deployment` which includes a `ports` element with a `containerPort` of `local_port` and a `hostPort` of remote_port

  * `Pod` belonging to the `Deployment` includes a `ports` element that agrees with the `Deployment`

  * Telepresence proxy pod is actually listening on local_port

  * Local Docker container (--container) is actually listening on local_port

  * Test tries to connect to remote_port and fails

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
