### ISSUE TITLE
Telepresence should give a useful error when its pod fails to start

### ISSUE THREAD

**Issue by julianiristv** [telepresenceio/telepresence#516]
### What were you trying to do?

Create a telepresence session into the `dev` namespace of my cluster

### What did you expect to happen?

`telepresence --namespace=dev`

### What happened instead?

Traceback below

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'dev']`
Version: `0.73`
Python version: `3.6.4 (default, Jan  6 2018, 11:49:38) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]`
kubectl version: `Client Version: v1.8.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Julians-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/main.py", line 480, in go
    runner, args
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/main.py", line 297, in start_proxy
    run_id=run_id,
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/remote.py", line 217, in get_remote_info
    format(deployment_name)
RuntimeError: Telepresence pod not found for Deployment 'telepresence-1521572357-878846-77936'.

```

Logs:

```
L | Checking {'app': 'hammer', 'pod-template-hash': '726881399'} (phase Running)...
 126.0 TL | Labels don't match.
 126.0 TL | Checking {'app': 'ims', 'pod-template-hash': '3462213945'} (phase Running)...
 126.0 TL | Labels don't match.
 126.0 TL | Checking {'app': 'mongo', 'pod-template-hash': '1042826073'} (phase Running)...
 126.0 TL | Labels don't match.
 126.0 TL | Checking {'app': 'pylon', 'pod-template-hash': '1183972510'} (phase Running)...
 126.0 TL | Labels don't match.
 126.0 TL | Checking {'pod-template-hash': '556097239', 'run': 'resource-consumer'} (phase Running)...
 126.0 TL | Labels don't match.
 126.0 TL | Checking {'app': 'ropes', 'pod-template-hash': '2339559931'} (phase Running)...
 126.0 TL | Labels don't match.
 126.0 TL | Checking {'app': 'sclera', 'pod-template-hash': '1414142427'} (phase Running)...
 126.0 TL | Labels do

**Comment by julianiristv** [comment]
Adding a note that our `ResourceQuota` implementation on our k8s cluster was the cause of this issue.  We had a min CPU and min memory set too high, preventing the creation of a telepresence deployment.  A more descriptive error message would be great but I found the issue by looking at the actual pod description using:

`kubectl get <pod_name> --output=yaml` 

which displayed the actual issue.  Kubernetes was preventing the pod from being created on the cluster.

**Comment by ark3** [comment]
I'm reopening this so we resolve the crash / no useful error message problem.
