### ISSUE TITLE
Telepresence crashes when it can't find its pod

### ISSUE THREAD

**Issue by dsyer** [telepresenceio/telepresence#522]
### What were you trying to do?

Run telepresence

### What did you expect to happen?

A shell and a VPN

### What happened instead?

Ugly stack trace

### Automatically included information

Command line: `['/usr/bin/telepresence', '-s', 'doubler:main', '--expose', '10382']`
Version: `0.75`
Python version: `3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.7.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux tower 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 480, in go
    runner, args
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 297, in start_proxy
    run_id=run_id,
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/remote.py", line 215, in get_remote_info
    format(deployment_name)
RuntimeError: Telepresence pod not found for Deployment 'doubler'.

```

Logs:

```
341951'} (phase Running)...
 125.5 TL | Labels don't match.
 125.5 TL | Checking {'function': 'hello', 'pod-template-hash': '2990062686'} (phase Running)...
 125.5 TL | Labels don't match.
 126.5 TL | [71] Capturing: (['kubectl', '--context', 'gke', '--namespace', 'default', 'get', 'pod', '-o', 'json', '--export'],)...
 127.7 TL | [71] captured.
 127.7 TL | Checking {'component': 'function-controller', 'release': 'demo', 'app': 'riff', 'pod-template-hash': '2973641237'} (phase Running)...
 127.7 TL | Labels don't match.
 127.7 TL | Checking {'component': 'http-gateway', 'release': 'demo', 'app': 'riff', 'pod-template-hash': '351612125'} (phase Running)...
 127.7 TL | Labels don't match.
 127.7 TL | Checking {'component': 'topic-controller', 'release': 'demo', 'app': 'riff', 'pod-template-hash': '4121341951'} (phase Running)...
 127.7 TL | Labels don't match.
 127.7 TL | Checking {'function': 'hello', 'pod-template-hash': '2990062686'} (phase Running)...
 127.7 TL | Labels don't match.

```

**Comment by ark3** [comment]
Sorry for the crash. Can you pass along the telepresence.log file as a gist? It looks like Telepresence did not swap out the original deployment successfully. Does Telepresence work for you in the simplest case, just `telepresence` to create a new deployment and get a shell?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
