### ISSUE TITLE
Feature request: bash completion

### ISSUE THREAD

**Issue by cv** [telepresenceio/telepresence#538]
Please consider using https://argcomplete.readthedocs.io/en/latest/ to generate an autocomplete script for bash. It's an easy win for teh fat-fingered among us :)

**Comment by ark3** [comment]
See also [how pip 10 does it](https://github.com/pypa/pip/blob/master/src/pip/_internal/__init__.py), though using argcomplete is probably a lot less work.

**Comment by donnyyung** [comment]
This is still a feature we should add to Telepresence 2.

**Comment by jef** [comment]
Since we're using cobra, could we leverage https://github.com/spf13/cobra/blob/master/shell_completions.md?

**Comment by sgreene570** [comment]
This feature would be greatly appreciated, and has already been implemented in `kubectl` and `oc`. IMO telepresence should have full feature parity with `kubectl` and `oc`'s bash completions (e.g. tab complete service names).


Is there anything I could hack on or look into to help this effort?

**Comment by thallgren** [comment]
@sgreene570 if you'd like to contribute, I believe you should start looking at our cobra command structure: https://github.com/telepresenceio/telepresence/tree/release/v2/pkg/client/cli

**Comment by thallgren** [comment]
Implemented
