### ISSUE TITLE
Telepresence inject-tcp method doesn't play nicely with CPython for pointer lookup

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#546]
Lookup of valid pointers fails like `[Errno 97] Address family not supported by protocol`.

This is because of an incompatibility between CPython and torsocks.  The torsocks issue is tracked upstream at https://trac.torproject.org/projects/tor/ticket/25586

**Comment by ark3** [comment]
Re #195, I see [this behavior](https://gist.github.com/ark3/95ea11bec7f368d8e2a73a7e2f383f34) on macOS with Python 3.6 and Torsock 2.2.0 from Homebrew. On Linux with Python 3.5 and Torsocks 2.1.0 from Debian, things look the same without Telepresence but yield a segfault for either query under Telepresence. More investigation is required.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
