### ISSUE TITLE
Telepresence inject-tcp method doesn't report pointer lookup failures to applications correctly

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#547]
Any pointer lookup which would normally fail is instead made to succeed by Telepresence with a result equal to the human-readable form of the query.  That is, a pointer lookup for the address "192.0.2.3" results in "192.0.2.3".  This differs from glibc behavior (though aligns with musl libc behavior) and is generally less useful than the alternative - returning an error indicating lookup failure.

This is done as a work-around to avoid a crash bug in Torsocks when handling lookup errors.  The bug is tracked upstream at https://trac.torproject.org/projects/tor/ticket/25627.

**Comment by ark3** [comment]
Re #195, I see [this behavior](https://gist.github.com/ark3/95ea11bec7f368d8e2a73a7e2f383f34) on macOS with Python 3.6 and Torsock 2.2.0 from Homebrew. On Linux with Python 3.5 and Torsocks 2.1.0 from Debian, things look the same without Telepresence but yield a segfault for either query under Telepresence. More investigation is required.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
