### ISSUE TITLE
DNS: inject-tcp not working on mac, working on linux

### ISSUE THREAD

**Issue by blaketastic2** [telepresenceio/telepresence#553]
I try to netcat to my service while running the below command:
`$ telepresence -m inject-tcp --run nc -zv service-name 8080`

The command times out for me on mac, but linux is fine. So I did an environment dump:
`$ telepresence -m inject-tcp --run env | sort`
and notice that mac has the `DYLD_INSERT_LIBRARIES` variable set. Linux didn't have the `LD_PRELOAD` in the dump. Based on the reading/documentation I've found [here](https://www.datawire.io/code-injection-on-linux-and-macos/), I'd expected to see this environment variable set, but since it's not, I don't quite understand how the DNS is working(or not).

From what I understand, the `inject-tcp` is resolving DNS through `/etc/resolve.conf`. Are there MacOS settings that I need to be aware of?

**Comment by ark3** [comment]
The inject-tcp method uses `torsocks` to override TCP connections and DNS requests by intercepting the associated C library calls. See [the documentation](https://www.telepresence.io/discussion/how-it-works#inject-tcp-method-in-detail) for more details. Telepresence does not modify `/etc/resolve.conf`.

I can replicate the symptom you see, that `nc` is not able to connect to a service under Telepresence inject-tcp on the Mac. But this is not a DNS problem. Under `telepresence -m inject-tcp --run-shell`,

1. `nc -zv bogus_name` fails immediately with a DNS error.
2. `nc -zv $KUBERNETES_SERVICE_HOST 443` fails with the same timeout behavior even though `$KUBERNETES_SERVICE_HOST` is an IP address, not a hostname, i.e. no DNS is involved.
3. Other tools (e.g., system `curl`, Homebrew `socat`) can resolve and connect fine.

I'm not sure what it is about Mac `nc` that behaves oddly here. The DNS portion of inject-tcp's magic appears to be working fine, yet the connection portion is not. 

In any case, I don't think running `nc` is your ultimate goal. What I remember from Gitter chat is that we were trying to get a database connection working on port 5432. We found that `telnet` connects, but `nc`, `psql`, and (most importantly) your Java app do not. Is that a fair summary of the situation?

**Comment by blaketastic2** [comment]
@ark3 Yes, that's a fair summary of my problem.
