### ISSUE TITLE
Question: How to attach a go debugger to swapped docker container from k8s with telepresence

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#554]
Hi

I am trying to see if it is possible to attach a go debugger(Delve) to a container started by telepresence from `vs code`.

The steps would be:
1. Start telepresence with`--new-deployment or --swap-deployment` with `--docker-run`.
2. Then in the container started by telepresence, I would start dlv(Delve debugger)
3. Then from outside the telepresence docker container, attach dlv(Delve debugger) to a port on the telepresence docker container - and then use vs code.
4. Then hit a service on Kubernetes that expose an EXTERNAL-IP

Is that possible?

Thanks

**Comment by ark3** [comment]
In concept, this should work. As you point out, Delve on the host will need to reach Delve in the container, so your `--docker-run` command must include a `--publish` option for the right port.

Please give it a try and let us know how it goes.

**Comment by JCzz** [comment]
Thanks I am glad to here that it should work - really a cool tool for the dev process on K8s.


First attempt is the following, where I want a go app running in a container - with no delve debugger just jet. 

So fare I am not able to connect and have the container respond?

Setup:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Running on Docker for Mac(Edge with Kubernetes)
```
docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	kubernetes

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

I am trying this:

Steps:
1. 
With a service like this - to select the pod that telepresence will create:
```
apiVersion: v1
kind: Service
metadata:
  name: telepresence
  labels:
    run: telepresence
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    telepresence: exists
  type: LoadBalancer
```
Note: `telepresence: exists`, maybe this is the problem?
This give me the a service I can hit on localhost:8080

kubectl get services
`telepresence                LoadBalancer   10.98.97.233    localhost     8080:31982/TCP   12m`

2. Then I start telepresence:
```
telepresence --expose 80 --new-deployment telepresence --docker-run \
  --rm -it -v $(pwd)/src:/go/src golang:alpine
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Password:
/go # cd src/app/
/go/src/app # go run app.go 
```

```
3. With this go code in src/app:
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello, you've requested: %s\n", r.URL.Path)
	})

	fmt.Println("Come one")
	err := http.ListenAndServe(":80", nil)
	if err != nil {
		log.Fatal(err)
	}
}
```

kubectl get deployments --show-labels
`telepresence                1         1         1            1           8m        telepresence=e201bd05-9211-4df0-a707-a2df825d155b`
kubectl get pods --show-labels
`telepresence-59fd7b64d-qhhlp                 1/1       Running   0          9m        pod-template-hash=159836208,telepresence=e201bd05-9211-4df0-a707-a2df825d155b`

**Comment by rhs** [comment]
Fair warning, I haven't played with your setup personally, but I can suggest a couple things you could try:

1. I'm not sure offhand how the selector stuff will work. You could try doing a `kubectl get endpoints telepresence` to see if your service is actually finding the telepresence pods as it is defined.

2. It might be simpler/easier to define a working service and deployment pair that runs your container in kubernetes, and verify that it is all defined properly and working without telepresence, and then use the `--swap-deployment` option to point telepresence at that.

**Comment by ark3** [comment]
I ran your code by launching Telepresence like this:

```shell
telepresence --expose 80 --new-deployment test1 --docker-run --rm -it -v $(pwd)/src:/go/src golang:alpine
```

and then, after `go run app.go`, tested it successfully from the cluster:

```shell
$ kubectl run test2 --rm -it --image=fedora --restart=Never -- curl -s http://test1/asdf
Hello, you've requested: /asdf
```

You will probably want to start with a working deployment and service as @rhs suggested. But for new code, you don't need to define a service separately. If you use `telepresence --expose --new-deployment`, Telepresence (or really `kubectl run` under the covers) makes a service for you. That's why the above works by itself.

**Comment by JCzz** [comment]
Thanks @rhs it helped me getting to realise that I needed to creating a service and a deployment - and that did work.
Thanks @ark3 for verifying

Now I am able to get into the container and access it via the service.

Next step and the original question: To be able to use the Delve debugger.

The problem is now that when starting delve(dlv) it stops working.

Steps:

1. 
```
telepresence --expose 80 --expose 2345 --swap-deployment hello-deployment --docker-run \
  --rm -it -p 2345:2345 -p 80:80 --privileged -v $(pwd)/src:/go/src golang:latest
```
2. 
And then in the container started by telepresence:
`go run app.go`
This is working so fare, but now when running Delve:
Note: installing delve with: `go get -u github.com/derekparker/delve/cmd/dlv`
`dlv debug --listen=0.0.0.0:2345 --headless=true --log=true`
Now it logs:
```
2018/04/03 10:32:44 server.go:73: Using API v1
2018/04/03 10:32:44 debugger.go:98: launching process with args: [/go/src/app/debug]
API server listening at: [::]:2345
```

And is is not responding via K8s service.
This might have to do with Delve, but if you have any comment I am very interested :-)

Thanks

**Comment by JCzz** [comment]
Thanks @rhs it helped me getting to realise that I needed to creating a service and a deployment - and that did work.

Thanks @ark3 for verifying

Now I am able to get into the container and access it via the service.
Next step and the original question - to be able to use the Delve debugger. I will get back if any issues.

You are welcome to close this one - thanks and keep up the good work.

Regards

**Comment by ark3** [comment]
@JCzz I think it's great that you're documenting your effort in this issue. Please keep us in the loop here. Thank you!
