### ISSUE TITLE
Make suffix stripping more robust (vpn-tcp)

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#557]
Based on the discussion around #192 and the results from #548, it seems reasonable to disable and subsequently remove suffix stripping entirely. This will simplify the code. Until we are confident about this change, we should allow the old (stripping) behavior to be turned back on somehow.

**Comment by ark3** [comment]
Due to the DNS regression issue, #578, I am changing the scope of this issue. First, we must address #578 by reverting the new behavior added by #548. Then, this issue can solve the problem cited in https://github.com/datawire/telepresence/pull/548#issuecomment-377542708 by returning NXDOMAIN until the proxy has a full set of suffixes. That should make suffix stripping more robust as initially intended.

We need to figure out how to simulate different networking environments for testing before we land any further changes to DNS behavior.

**Comment by ark3** [comment]
Still an issue. Next step: evaluate suffix stripping via nxdomain as described above.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
