### ISSUE TITLE
Issue while setting up development environment with kubernetes 

### ISSUE THREAD

**Issue by rayanimesh** [telepresenceio/telepresence#562]
### What were you trying to do?

Following tutorial -- https://www.telepresence.io/tutorials/docker. Swapping deployment of `qotm` from local machine to `kubernetes` cluster.
 
### What did you expect to happen?

Deployement should have been swapped to local docker image `qotm-dev:latest` and after which I can make local changes reflecting at `kubernetes` pod.

### What happened instead?
Got the following error -- which prompted me to file this issue. I searched for related issues at Github -- couldn't find one and hence filing this. 

![image](https://user-images.githubusercontent.com/5434024/38348738-2e71a748-38c1-11e8-8b88-a087b9171b9a.png)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'qotm', '--docker-run', '--rm', '-it', '-v', '/home/animeshray/Paytm/repos/qotm:/service', 'qotm-dev:latest']`
Version: `0.78`
Python version: `3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.10.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux thinkpad 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 488, in go
    runner, args
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 305, in start_proxy
    processes, socks_port, ssh = connect(runner, remote_info, args)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 205, in connect
    ssh.wait()
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/ssh.py", line 71, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
v/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '37127', 'telepresence@localhost', '/bin/true']...
  57.9 TL | [157] exit 255.
  58.1 TL | [158] Running: ['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '37127', 'telepresence@localhost', '/bin/true']...
  58.1 TL | [158] exit 255.
  58.4 TL | [159] Running: ['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '37127', 'telepresence@localhost', '/bin/true']...
  58.4 TL | [159] exit 255.
  58.6 TL | [160] Running: ['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '37127', 'telepresence@localhost', '/bin/true']...
  58.7 TL | [160] exit 255.
  58.9 TL | [161] Running: ['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '37127', 'telepresence@localhost', '/bin/true']...
  58.9 TL | [161] exit 255.

```

**Comment by ark3** [comment]
Sorry about the crash! I will need information from earlier in the logfile to see what's going on. Can you link to a gist containing telepresence.log, please?

**Comment by rayanimesh** [comment]
@ark3 : Thanks for replying on this. I have attached the `telepresence.log` in gist [here](https://gist.github.com/rayanimesh/b24309d1c30bdd5867a13a9dc38ace2b).   Let me know if anything else is required from my side.

**Comment by ark3** [comment]
It looks like the problem occurs when Telepresence tries to run port forward. In this case, it ran 
```
kubectl --context kubelet --namespace default port-forward qotm-b5d47b4b7-j2dm2 38071:8022
```
and got the error
```
error: error upgrading connection: Upgrade request required
```

Telepresence should not crash when this occurs; we'll fix that in an upcoming release. 

We still need to resolve the underlying problem. Can you try port forwarding manually to see whether that works? If you still have QotM running in your cluster, figure out the pod name (`kubectl get pods`), then try port forward (`kubectl port-forward qotm-1371672344-2xwwl 5000:5000` in my cluster), and let us know what happens. Thanks for your help.
