### ISSUE TITLE
Detaching from a --docker-run command kills the telepresence container

### ISSUE THREAD

**Issue by CMajeri** [telepresenceio/telepresence#567]
Sending Ctrl+P-Ctrl+Q to a docker container detaches from it without killing it.

When using this on a container started with telepresence, the container keeps running, but its buddy is killed, leaving the main container without a network, and no connection to the cluster.

To replicate:
```
$ telepresence --docker-run -it busybox
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

/ # (sent ctrl+P-ctrl+Q) $ 
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
21332cbb310d        busybox             "sh"                39 seconds ago      Up 37 seconds                           telepresence-1523006684-8896372-17356
```

Before sending the detach signal :
```
$ docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS               NAMES
21332cbb310d        busybox                            "sh"                     5 seconds ago       Up 3 seconds                            telepresence-1523006684-8896372-17356
ea5bbf3424c8        datawire/telepresence-local:0.78   "/sbin/tini -v -- ..."   12 seconds ago      Up 10 seconds                           telepresence-1523006677-8483868-17356
```

I have tested this on Fedora boxes, and the behaviour is the same with any image launched and most docker options I pass (typically `--rm`).

It's fairly easy to workaround this but it's odd behaviour.

I'll start investigating when I have more time, but if anyone already knows or has any pointers on where to look, it'd be nice.

**Comment by ark3** [comment]
Telepresence uses the lifetime of the `docker run` command as the lifetime of the session. When you detach from the container, the `docker run` command exits, so Telepresence cleans things up. 

Please describe the behavior you would like to see. When should Telepresence perform cleanup? I have some ideas, but I'm curious to know what you had expected. Thank you!

**Comment by CMajeri** [comment]
I just expected telepresence to be tied to the lifetime of the container rather than the run command itself.
This also means telepresence doesn't support passing the `-d` argument to docker, which feels a bit weird to me, although I now understand why.

Would you be up for adding support for background containers? I can look around and see how/what I would change to implement that, if that's a change you're interested in.
Thanks!
