### ISSUE TITLE
Unable to swap deployment on OpenShift

### ISSUE THREAD

**Issue by concaf** [telepresenceio/telepresence#582]
### What were you trying to do?

I was following the guide at https://www.telepresence.io/tutorials/docker, and the traceback occurred when I ran the step to swap the deployment - `telepresence --swap-deployment qotm --docker-run --rm -it -v $(pwd):/service qotm-dev:latest`

### What did you expect to happen?

I was expected the swap to happen :)

### What happened instead?

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'qotm', '--docker-run', '--rm', '-it', '-v', '/home/concaf/telepresence/qotm:/service', 'qotm-dev:latest']`
Version: `0.81`
Python version: `3.6.4 (default, Mar 13 2018, 18:18:20) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]`
kubectl version: `Client Version: v1.9.0 // Server Version: v1.7.6+a08f5eeb62`
oc version: `oc v3.7.1+ab0f056 // kubernetes v1.7.6+a08f5eeb62 // features: Basic-Auth GSSAPI Kerberos SPNEGO //  // Server https://192.168.42.188:8443 // openshift v3.7.2+5eda3fa-5 // kubernetes v1.7.6+a08f5eeb62`
OS: `Linux containscafeine 4.15.14-300.fc27.x86_64 #1 SMP Thu Mar 29 16:13:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/cli.py", line 74, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/main.py", line 494, in go_too
    runner, args
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/main.py", line 277, in start_proxy
    swap_deployment_openshift(runner, args)
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/deployment.py", line 252, in swap_deployment_openshift
    )[0].split("/", 1)[1]
IndexError: list index out of range

```

Logs:

```
 Context: telepresence/192-168-42-188:8443/system:admin, namespace: telepresence, kubectl_command: oc
   0.1 TEL | [4] Capturing: minishift ip
   0.3 TEL | Looks like we're in a local VM, e.g. minikube.
   0.3 TEL | [5] Capturing: oc --context telepresence/192-168-42-188:8443/system:admin status
   0.3   1 | Client Version: v1.9.0
   0.3   1 | Server Version: v1.7.6+a08f5eeb62
   0.4   2 | oc v3.7.1+ab0f056
   0.4   2 | kubernetes v1.7.6+a08f5eeb62
   0.4   2 | features: Basic-Auth GSSAPI Kerberos SPNEGO
   0.4   2 | 
   0.4   2 | Server https://192.168.42.188:8443
   0.4   2 | openshift v3.7.2+5eda3fa-5
   0.4   2 | kubernetes v1.7.6+a08f5eeb62
   0.6 TEL | [6] Capturing: ssh -V
   0.6 TEL | [7] Capturing: which torsocks
   0.6 TEL | [8] Capturing: which sshfs
   0.6 TEL | BEGIN SPAN main.py:232(start_proxy)
   0.6 TEL | [9] Capturing: oc --context telepresence/192-168-42-188:8443/system:admin --namespace telepresence get rc -o name --selector openshift.io/deployment-config.name=qotm

```

**Comment by ark3** [comment]
When we fix this, let's also update the swap-deployment methodology to be consistent with that under Kubernetes, i.e. PR #605 prompted by issue #575.
