### ISSUE TITLE
Add an OpenShift cluster to CI

### ISSUE THREAD

**Issue by richarddli** [telepresenceio/telepresence#584]
Telepresence works with OpenShift, but we don't regularly run our tests against an OpenShift cluster. Since OpenShift is "not-quite-Kubernetes", we should do this. First step is to get an OpenShift cluster, preferably one maintained by the OpenShift folks. Note that the public OpenShift clusters don't grant cluster admin privileges to users, so this might not work.

**Comment by ark3** [comment]
Let’s see about getting the local cluster going as suggested.

**Comment by donnyyung** [comment]
We should still do this for Telepresence 2.
