### ISSUE TITLE
Windows: Telepresence crashes when running vpn-tcp instead of informing the user about Windows-specific limitations

### ISSUE THREAD

**Issue by Disturbing** [telepresenceio/telepresence#595]
Using Telepresence 0.82 -

Currently its erroring below.

➜  Owner telepresence
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per
 machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see htt
ps://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports y
ou want to forward.

Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see http
s://github.com/datawire/telepresence/issues/115, otherwise please report a bug, attaching telepresence.log to the bug report: https://gi
thub.com/datawire/telepresence/issues/new

Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 74, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 507, in go_too
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/vpn.py", line 300, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/vpn.py", line 284, in get_hellotelepresence
    format(next(counter))
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 234, in get_output
    track, "Capturing", "captured", out_cb, err_cb, args, **kwargs
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 212, in run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence50')"]' returned non-ze
ro exit status 1

And here are the last few lines of the logfile (see /mnt/c/Users/Owner/telepresence.log for the complete logs):

  23.0 TEL | [68] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence47'"'"')'
  23.4  68 | Traceback (most recent call last):
  23.4  68 |   File "<string>", line 1, in <module>
  23.4  68 | socket.gaierror: [Errno -2] Name or service not known
  23.4 TEL | [68] exit 1 in 0.35 secs.
  23.5 TEL | [69] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence48'"'"')'
  23.8  69 | Traceback (most recent call last):
  23.8  69 |   File "<string>", line 1, in <module>
  23.8  69 | socket.gaierror: [Errno -2] Name or service not known
  23.8 TEL | [69] exit 1 in 0.36 secs.
  23.9 TEL | [70] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence49'"'"')'
  24.2  70 | Traceback (most recent call last):
  24.2  70 |   File "<string>", line 1, in <module>
  24.2  70 | socket.gaierror: [Errno -2] Name or service not known
  24.3 TEL | [70] exit 1 in 0.33 secs.
  25.4 TEL | [71] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence50'"'"')'
  25.7  71 | Traceback (most recent call last):
  25.7  71 |   File "<string>", line 1, in <module>
  25.7  71 | socket.gaierror: [Errno -2] Name or service not known
  25.7 TEL | [71] exit 1 in 0.34 secs.

**Comment by Disturbing** [comment]
Same issue with this command:

➜  Owner telepresence --method vpn-tcp --swap-deployment loader --namespace local

**Comment by richarddli** [comment]
You're using `vpn-tcp`. Per https://www.telepresence.io/reference/windows, the only method supported on Windows is `inject-tcp`.

**Comment by ark3** [comment]
... and maybe default to inject-tcp, which does work.
