### ISSUE TITLE
Support for CentOS 

### ISSUE THREAD

**Issue by nakulshukla08** [telepresenceio/telepresence#600]
Is there any plan to add support for CentOS? if not ,  which method should I follow to install it? Is building from source the only option?

**Comment by ark3** [comment]
I suggest that you [install from source](https://www.telepresence.io/reference/install#install-from-source). That process is simple using the supplied script. 

The tricky part is getting the [dependencies](https://www.telepresence.io/reference/install#dependencies) installed. I didn't see an obvious way to get Python 3.5 or later installed with a one-liner, but Digital Ocean has a [page describing the process](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-centos-7). 

If you succeed, please let us know what worked for you. We could definitely use help improving our documentation, e.g., with package names for the listed dependencies. Thanks!

See also #457.
