### ISSUE TITLE
is it possible to forward outgoing traffic from a pod to my local environment?

### ISSUE THREAD

**Issue by sht5** [telepresenceio/telepresence#611]
I have a pod running an image which publishes zmq messages to tcp://localhost:6199.
i want my local app running on my laptop to receive these messages. 
is it possible to forward outgoing traffic on a certain port on the pod to my local host to make this possible?
thanks

**Comment by ark3** [comment]
Let's say you have an image my_zmq_pub that is running in your cluster in a deployment called pub-deployment. Based on a suggestion on Gitter by @rhs, perhaps try something like

```
telepresence --method swap-deployment pub-deployment --docker-run -p 127.0.0.1:6199:6199 my_zmq_pub
```

This will run your image on your local Docker daemon, but the running container will have connectivity to your cluster in a manner that's similar to when it runs in Kubernetes. Then you can make connections to localhost:6199 and pull down outgoing traffic from that port.

Did I understand your goal correctly? Please let us know how it goes!

**Comment by webular** [comment]
If I understand your question correctly - you can do this with an ExternalName service.  Something like this should work.

```
kind: Service
apiVersion: v1
metadata:
  name: external-db-service
  namespace: default
spec:
  type: ExternalName
  externalName: external.db

```
Then add this line to your `/etc/hosts` file on your development machine
`127.0.0.1 external-db-service`

This is how we use an external db for development.
