### ISSUE TITLE
--method inject-tcp does not resolve dns names on mac

### ISSUE THREAD

**Issue by vijay-js** [telepresenceio/telepresence#615]
Started the shell with --method inject-tcp on mac.

The shell would not resolve the service names. If i try to call a rest api with http://service-name/api - this would not give any output. 

The error after a while would be " Unable to connect to remote host"

However if i start the shell with default method i.e --method vpn-tcp . The api works and all the service name dns resolutions work fine

What could be the issue? We need to use --method inject-tcp  so that we can connect to the cluster even in case of another vpn connection

**Comment by ark3** [comment]
Can you please run this simple example

```
sudo killall -HUP mDNSResponder

telepresence --method inject-tcp --run curl -svk https://kubernetes.default.svc.cluster.local/api/
```

and post a gist containing the output and the associated telepresence.log?

If it works, then the output will be roughly the same as running

```
kubectl run curl-test -it --rm --image=fedora --restart=Never -- curl -svk https://kubernetes.default.svc.cluster.local/api/
```

More interesting would be if it didn't work. Then the log file may provide clues as to what's going wrong.

Thanks!

**Comment by vijay-js** [comment]
This is not working. Here's the stack trace

Command line: `['/usr/local/bin/telepresence', '--method', 'inject-tcp', '--run', 'curl', '-svk', 'https://kubernetes.default.svc.cluster.local/api/']`
Version: `0.82`
Python version: `3.6.5 (default, Mar 30 2018, 06:41:49) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]`
kubectl version: `Client Version: v1.9.3 // Server Version: v1.9.2-gke.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin GVKUMAR-M-V32L 15.6.0 Darwin Kernel Version 15.6.0: Tue Jan  9 20:12:05 PST 2018; root:xnu-3248.73.5~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.82/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 74, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.82/libexec/lib/python3.6/site-packages/telepresence/main.py", line 507, in go_too
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/Cellar/telepresence/0.82/libexec/lib/python3.6/site-packages/telepresence/local.py", line 151, in run_local_command
    setup_torsocks(runner, env, socks_port, unsupported_tools_path)
  File "/usr/local/Cellar/telepresence/0.82/libexec/lib/python3.6/site-packages/telepresence/local.py", line 114, in setup_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs: Last few lines

```
77] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  52.6  77 | Traceback (most recent call last):
  52.6  77 |   File "<string>", line 1, in <module>
  52.6  77 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  52.6 TEL | [77] exit 1 in 0.08 secs.
  52.7 TEL | [78] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  52.8  78 | Traceback (most recent call last):
  52.8  78 |   File "<string>", line 1, in <module>
  52.8  78 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  52.8 TEL | [78] exit 1 in 0.08 secs.
  52.9 TEL | [79] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  53.0  79 | Traceback (most recent call last):
  53.0  79 |   File "<string>", line 1, in <module>
  53.0  79 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  53.0 TEL | [79] exit 1 in 0.08 secs.

```

Logs : First few lines 

```
26.2  14 | Handling connection for 59794
  39.1  14 | E0426 02:28:50.866949   83131 portforward.go:331] an error occurred forwarding 59794 -> 8022: error forwarding port 8022 to pod 3641b5250591d732289758ede1843b3037fbc70ce3540b7e60f8fdd97149127e, uid : exit status 1: 2018/04/25 20:58:49 socat[14580] E write(5, 0x5576abfd8b70, 28): Broken pipe
  39.1  24 | Connection to localhost closed by remote host.
  39.1 TEL | [24] exit 255
  40.9 TEL | [26] ran in 14.75 secs.
  40.9 TEL | END SPAN remote.py:240(mount_remote_volumes)   14.8s
  43.1 TEL | [27] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
1524689934 PERROR torsocks[83236]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:202)
  43.2  27 | Traceback (most recent call last):
  43.2  27 |   File "<string>", line 1, in <module>
  43.2  27 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  43.2 TEL | [27] exit 1 in 0.10 secs.
  43.3 TEL | [28] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
1524689935 PERROR torsocks[83250]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:202)
  43.4  28 | Traceback (most recent call last):
  43.4  28 |   File "<string>", line 1, in <module>
  43.4  28 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  43.4 TEL | [28] exit 1 in 0.09 secs.
  43.5 TEL | [29] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
1524689935 PERROR torsocks[83260]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:202)
  43.6  29 | Traceback (most recent call last):
  43.6  29 |   File "<string>", line 1, in <module>
  43.6  29 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  43.6 TEL | [29] exit 1 in 0.08 secs.
  43.7 TEL | [30] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
1524689935 PERROR torsocks[83269]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:202)
  43.7  30 | Traceback (most recent call last):
  43.7  30 |   File "<string>", line 1, in <module>
  43.7  30 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  43.7 TEL | [30] exit 1 in 0.09 secs.
  43.9 TEL | [31] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
1524689935 PERROR torsocks[83278]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:202)
  43.9  31 | Traceback (most recent call last):
  43.9  31 |   File "<string>", line 1, in <module>
```

**Comment by ark3** [comment]
Also, I should note that this session is crashing in a way that would break `--run-shell` entirely. I wonder why it worked before but isn't working now.

**Comment by vijay-js** [comment]
Sure . Thanks @ark3. I will message you the full stack trace over gitter

**Comment by vijay-js** [comment]
@ark3 : The strange thing is currently the following works on mac .The telepresence version is same as before. 
```
telepresence --method inject-tcp --run curl -svk https://kubernetes.default.svc.cluster.local/api/
```

The main issue is this - In the telepresence shell which is running - I am able to access my service by service name and able to get the API working. 

But since my IDE runs in a different process , it's unable to resolve the servicename and hence the API fails,

This is however not the case with default method ( --method vpn-tcp ). With default method - all the process on the local machine were able to resolve the service name.  But since --method vpn-tcp does not work with a VPN already set - we are trying to get --method inject-tcp  working .

Any pointers on how to get this working?

**Comment by ark3** [comment]
We don't have a _simple_ solution for IDE + VPN situations. Maybe you can convince your IDE to debug code running in Docker, in which case the container method might work for you. 

Or you might be able to have your IDE set up the `DYLD*` and `TOR*` environment variables for the running code to be same as in your inject-tcp Telepresence shell:

In the first terminal:
```shell
$ telepresence --method inject-tcp --run-shell
Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom DNS implementations are not supported. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

@tel-testing-1-7|bash-3.2$ env | egrep "TOR|DYLD"
TORSOCKS_CONF_FILE=/var/folders/kw/qdk542sj7gn_1zr1nb57nyzm0000gn/T/tmps22htaq0
TORSOCKS_LOG_FILE_PATH=/Users/ark3/datawire/telepresence/telepresence.log
DYLD_INSERT_LIBRARIES=/usr/local/Cellar/torsocks/2.2.0/lib/torsocks/libtorsocks.dylib
DYLD_FORCE_FLAT_NAMESPACE=1
@tel-testing-1-7|bash-3.2$ env | egrep "TOR|DYLD" > /tmp/tel-env
```

You can see the relevant environment variables are saved into a file. You would have to get your IDE to run your process with the same variables. Here I'll use the `env` command to run Python3. This will only work while the above Telepresence is still running:

```shell
$ env $(cat /tmp/tel-env) /usr/local/bin/python3
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.request
>>> import ssl
>>> conn = urllib.request.urlopen("https://kubernetes/api", context=ssl.SSLContext())
>>> print(str(conn.read(), "utf-8"))
{"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"35.184.12.241"}]}

>>> 
```

On the Mac you have to be careful not to run things from `/usr/bin` and other system directories because of SIP. See [the docs](https://www.telepresence.io/reference/methods#macos-system-integrity-protection) for more info. That's why I didn't use `curl` in this example.

If you make progress doing this sort of thing with your IDE, please let us know!

**Comment by vijay-js** [comment]
Thanks @ark3 . This is exactly what I do with my IDE process currently even with method --vpn-tcp. I push all my required env variables to a file and source it in my Intellij using this plugin (https://plugins.jetbrains.com/plugin/7861-env-file)  before running it and this works perfectly.

But the problem is with method--inject-tcp . Even with sourcing "TOR|DYLD" variables . It is unable to fetch the API or resolve any service. I guess SIP on Mac might be the culprit.

**Comment by kobyepistema** [comment]
Looks like it's written on the docs:
https://www.telepresence.io/reference/proxying#networking-access-to-cloud-resources
