### ISSUE TITLE
Ubuntu Bionic Beaver repo

### ISSUE THREAD

**Issue by valeriano-manassero** [telepresenceio/telepresence#622]
According docs, I just tried to install Telepresence using command: 
`curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | sudo bash`

While this is working on Ubuntu Artful, in Ubuntu Bionic Beaver (18.04 LTS) the resulting repo is:
`https://packagecloud.io/datawireio/telepresence/ubuntu bionic Release` resulting in a 404 error.

I just tested last Telepresence version I manually installed on a Bionic and looks good to me so it's only a matter of creating the repository url.

**Comment by ark3** [comment]
I've manually added Bionic Beaver packages for 0.87 and 0.88. We will fix this the right way in #643.

**Comment by ark3** [comment]
This should be fixed as of release 0.90.
