### ISSUE TITLE
Support for Non-Deployment Type Pods

### ISSUE THREAD

**Issue by jordanwilson230** [telepresenceio/telepresence#624]
Are there any plans to implement support for pods launched via statefulsets? The majority of our workloads are statefulsets, so being able to run e.g: ```telepresence --swap-pod cassandra-2 --docker-run --hostname cassandra-2 -it cassandra:local-v1``` would be very useful.

**Comment by astratto** [comment]
👋 this feature would be very interesting for me as well.

If it's not on your radar, do you happen to have thoughts on what would be the best way to tackle this if I wanted to implement it myself?

**Comment by richarddli** [comment]
We're in the middle of a bit of a refactor at the moment so I think it would be a little complicated, but please hop on our Slack in a week and ping if you're interested in helping -- we are making some good progress and could probably be able to provide some guidance soon.

**Comment by darxkies** [comment]
Are there any updates regarding telepresence support?

**Comment by sporkins** [comment]
Bump ... this would be very helpful.  For now I'm having to use a deployment service type for local development.

**Comment by ark3** [comment]
For `--swap-deployment` Tel does the following:

1. Use `kubectl scale` to remove all the existing Pods for the original deployment.
2. Create a new deployment for the Telepresence Proxy that has the same labels as the original deployment. By virtue of having the same labels, k8s Services will route to the proxy just like they routed to the original.
3. Connect to the proxy and run your session.

How would a `--swap-pod` or similar work?

**Comment by tenitski** [comment]
What about `--swap-statefulset` - is there something else needed apart from the mentioned above steps?

**Comment by shaharyakir** [comment]
In addition to statefulset support, I found myself creating a deployment mimicking a daemonset just so I could get the env vars and volumes that the daemonset sees while developing locally, so perhaps an option like that (e.g. `--from-daemonset`) could be nice.

**Comment by cfontes** [comment]
Bump again, this would be extremelly helpful

**Comment by isra17** [comment]
I did a quick implementation here: https://github.com/telepresenceio/telepresence/commit/bb7473fbf19ed4f61796a5e32747e23de6ab03da with `--deployment-type` that used most of the existing code.

Does it look like a valid solution? It works on my machine for `--swap-deployment`.

**Comment by ToonvanStrijp** [comment]
@richarddli any update on this, this issue has been open for way to long now? This would be a nice feature to have.

**Comment by isra17** [comment]
For what it's worth, we have been using our patch above in-house daily without issues for a few weeks!

**Comment by ToonvanStrijp** [comment]
@isra17 how can I install telepresence with your patch? :)

**Comment by ark3** [comment]
Sorry we haven't had time to get to this already. @ToonvanStrijp you can check out the source at tag 0.104, apply @isra17's patch, and then use the [Install from source](https://www.telepresence.io/reference/install#install-from-source) instructions.

**Comment by isra17** [comment]
> @isra17 how can I install telepresence with your patch? :)

`pip install -e git+https://github.com/Flared/telepresence.git@bb7473fbf19ed4f61796a5e32747e23de6ab03da#egg=telepresence`

**Comment by puneetguptanitj** [comment]
Hello, any update on including the patch from @isra17? 
Hi @isra17, i tried using the pip install above but am facing the following issue while trying to run it
```
puneet.gupta2@ACTIVESOONHOT ~/Downloads/sdet_cluster $ telepresence
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 11, in <module>
    load_entry_point('telepresence', 'console_scripts', 'telepresence')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/puneet.gupta2/Downloads/sdet_cluster/src/telepresence/telepresence/main.py", line 20, in <module>
    from telepresence import connect, mount, outbound, proxy, remote_env
  File "/Users/puneet.gupta2/Downloads/sdet_cluster/src/telepresence/telepresence/connect/__init__.py", line 15, in <module>
    from .connect import connect, setup
  File "/Users/puneet.gupta2/Downloads/sdet_cluster/src/telepresence/telepresence/connect/connect.py", line 29
    runner: Runner, remote_info: RemoteInfo, is_container_mode: bool,
          ^
SyntaxError: invalid syntax
```
Could you please help me with it, what I might be doing wrong? thanks a lot !

**Comment by isra17** [comment]
@puneetguptanitj  You are using Python2, which is not compatible with telepresence. If you want to use `pip install` you should use virtualenv and the right python version (> 3.6 I believe).

Also, I've rebased my patch on master so you might want to use `pip install -e git+https://github.com/Flared/telepresence.git@866e7679b80a214712156cea711b50be267a681e#egg=telepresence` now instead.

**Comment by puneetguptanitj** [comment]
Thanks @isra17, I got your branch and built from source as that automatically uses python3. I am no longer getting any error while running telepresence, I would try with statefulset swap next and let you know. Thanks a lot for your patch!

**Comment by puneetguptanitj** [comment]
Hi reviewers is there any update regarding @isra17's patch above. I have been using it for a while now and haven't seen any issues. Could you please include it in necessary ci and merge if things look ok. Much appreciate your consideration. Thanks again @isra17 for your patch!

**Comment by buttairfly** [comment]
Thanks @isra17 for the patch!

Note that the cmd option `--deployment-type` must be put BEFORE the `--swap-deployment` flag

**Comment by marun** [comment]
@isra17 Can you provide any insight into your use of telepresence with statefulsets? My understanding of their utility is related to stable identity for things like databases (e.g. sharding), and I would appreciate knowing how you would debug that kind of thing locally.

**Comment by isra17** [comment]
Few use case. One of our components use a statefuldisk to store archives that are uploaded daily to cloud bucket. Sometime I might want to debug this component and don't mind having a new empty volume. Of course this only work with provisionned volume.

Another use case I actually use a lot is for us to replace some pods with a simple container running a proxy to another VPN or cluster. We call it `teleproxy` and pretty much run a `kubectl port-forward ...` inside telepresence to forward a cluster service to another cluster. Being able to do so for statefulset is quite useful to proxy databases.

**Comment by aniekgul** [comment]
We also use deployment like CRDs for many of our services where something like this would be really useful

**Comment by mrgzar** [comment]
Is there any news regarding this feature to be incorporated in some of next TP releases?
Btw, quickly test @isra17 's patch and it worked out with statefulsets :)

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2 since we support statefulsets, replicasets, and deployments. Please open an issue if you have a request for a new workload to be supported. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/).
