### ISSUE TITLE
It is hard to add features to Telepresence without causing a combinatorial explosion of testing

### ISSUE THREAD

**Issue by plombardi89** [telepresenceio/telepresence#628]
We want to add features to Telepresence without causing a combinatorial explosion of testing in the Telepresence project. We will measure our success by the ability to add copy-deployment, method=none, and tests for the mount argument.

**Comment by ark3** [comment]
Stages that need to be tested include:

- intent (argument parsing, etc.)
- setup (inspecting local and cluster state, other stuff)
- proxy (e.g., swap-deployment) #657 
- connection (set up port forward, ssh tunnel)
- environment
- filesystem
- outbound (e.g., vpn-tcp)
- launch
- wait
- cleanup

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
