### ISSUE TITLE
telepresence on alpine

### ISSUE THREAD

**Issue by Kranthi-kavuri-randstad** [telepresenceio/telepresence#635]
Do you have telepresence binaries for alpine ?
If yes, info please !!

**Comment by ark3** [comment]
Not at the moment, though [installing from source](https://www.telepresence.io/reference/install#install-from-source) works fine on Alpine. Out of curiosity, what is your use case? Are you doing development work from a machine running Alpine Linux?

**Comment by draganrakas** [comment]
@ark3 Would love to see an Alpine version! Our use case is we have an Alpine-based Docker container for our CI, and use telepresence for integration testing.

**Comment by ark3** [comment]
Installing from source still works fine in Alpine. 

```shell
$ docker run --privileged --rm -it alpine sh                
/ # cd                                                                                                              
~ # apk -qU add bash git python3 openssh-client sshfs conntrack-tools torsocks docker sudo                             
~ # git clone -q http://github.com/datawire/telepresence                            
~ # cd telepresence/                                              
~/telepresence # PREFIX=/usr ./install.sh                             
Installing Telepresence in /usr                                                                                 
Built /tmp/tmp.GnAiCN/dist/telepresence                                                                       
warning: no previously-included files matching '*' found under directory 'docs/_build'                                 
You are using pip version 10.0.1, however version 18.1 is available.                                                   
You should consider upgrading via the 'pip install --upgrade pip' command.                                             
Built /tmp/tmp.GnAiCN/dist/sshuttle-telepresence                                                                 
Downloaded /tmp/tmp.GnAiCN/dist/teleproxy                                                                          
Installed Telepresence 0.94-74-gb59307e                                                  
~/telepresence # cd
~ # 

# install kubectl and set up access to your cluster somehow

~ # telepresence --mount=False --run curl -sk https://kubernetes/api
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one 
T: telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless 
T: services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html

T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to 
T: specify which ports you want to forward.

{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "35.184.12.241"
    }
  ]
}T: Exit cleanup in progress
~ # 

```

**Comment by richarddli** [comment]
@draganrakas do you mind sharing here (or on our slack, https://d6e.co/slack) how you're using Telepresence for integration testing? we're working on a presentation for KubeCon and listing different use cases that people use Telepresence for.

**Comment by draganrakas** [comment]
@richarddli For integration testing, we use telepresence for service dependencies rather than mocking, and deploy the service as if it were a local instance within a telepresence session. On PRs and certain branches, commits trigger integration tests to run as if we were running it against localhost using the telepresence session. The main advantage for us is that the integration testing on local dev environments & within CI is identical.

@ark3 After setting up our context, I tried `telepresence --mount=False` just to test, and got this stack trace:

```
T: Background process(es) failed during setup:
T: sshuttle exit 99

Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 84, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 61, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 279, in connect_sshuttle
    for _ in runner.loop_until(20, 0.1):
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 263, in loop_until
    self.bg_process_crash()
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 447, in bg_process_crash
    raise RuntimeError("Background process(es) failed during setup")
RuntimeError: Background process(es) failed during setup


And here are the last few lines of the logfile (see telepresence.log for the complete logs):

   9.7  45 | Traceback (most recent call last):
   9.7  45 |   File "<string>", line 1, in <module>
   9.7  45 | socket.gaierror: [Errno -2] Name does not resolve
   9.7 TEL | [45] exit 1 in 0.04 secs.
   9.7 TEL | [24] exit 99
   9.8 TEL | [46] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence21'"'"')'
   9.9  46 | Traceback (most recent call last):
   9.9  46 |   File "<string>", line 1, in <module>
   9.9  46 | socket.gaierror: [Errno -2] Name does not resolve
   9.9 TEL | [46] exit 1 in 0.04 secs.
   9.9 >>> | Background process(es) failed during setup:
   9.9 >>> | sshuttle exit 99
```

After looking into telepresence.log, the stacktrace started after this line:

```   6.7 TEL | [24] Launching sshuttle: sshuttle-telepresence -v --dns --method nat -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence -v --dns --method nat -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence@localhost:42391 100.64.0.0/13 100.96.0.0/19```

About 30 lines or so down, there was also an `iptables` error, although this command was explicitly run under root:

``` 24 | iptables v1.6.1: can't initialize iptables table `nat': Permission denied (you must be root)
9.5  24 | Perhaps iptables or your kernel needs to be upgraded.
9.5  24 | iptables v1.6.1: can't initialize iptables table `nat': Permission denied (you must be root)
9.5  24 | Perhaps iptables or your kernel needs to be upgraded.```

**Comment by ark3** [comment]
Did you run this in a privileged container? Are you using Docker?

**Comment by draganrakas** [comment]
@ark3 Yes, we are using the base Alpine docker image. Everything worked without issue when running the container with the `--privileged` flag. Is there an alternative to this? Our CI platform doesn't allow us to run containers with such permissions. :(

**Comment by ark3** [comment]
The vpn-tcp and container methods require `iptables`, which means using a privileged container is necessary. Can you use the inject-tcp method for your application?

**Comment by draganrakas** [comment]
Update: Although the telepresence session worked, ultimately a non-privileged container still didn't work for us. It looks like the `inject-tcp` method isn't compatible with Node and kept crashing our service at runtime...

https://github.com/telepresenceio/telepresence/issues/708
https://github.com/telepresenceio/telepresence/issues/195
