### ISSUE TITLE
Telepresence 0.88 on buntu bionic

### ISSUE THREAD

**Issue by artur-ba** [telepresenceio/telepresence#648]
### What were you trying to do?

Run service http service via telepresence

### What did you expect to happen?

Service starts

### What happened instead?

Telepresence fails with error below

### Automatically included information

Version: `0.88`
Python version: `3.6.5 (default, May  3 2018, 10:08:28) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.8.3 // Server Version: v1.8.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux arturb-VB 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/main.py", line 105, in main
    mount_dir,
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/container.py", line 132, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 168, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 157, in run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1526621960-2011213-7636', '--rm', 'datawire/telepresence-local:0.88', 'wait']' returned non-zero exit status 1.

```

Logs:

```
 '/etc/hosts.sbak'
  34.4  38 | c : fatal: server died with error code 255
  34.4  38 |    2.5 TEL | Main process (['sshuttle-telepresence', '-v', '--dns', '--method', 'nat', '-e', 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null', '--to-ns', '127.0.0.1:9053', '-r', 'telepresence@172.17.0.1:37889', '0.0.0.0/0', '10.244.1.0/24', '10.96.0.0/12', '10.244.2.0/24', '10.244.0.0/24'])
  34.4  38 |    2.5 TEL |  exited with code 99.
  34.4  38 |    2.5 TEL | END SPAN cleanup.py:98(wait_for_exit)    2.5s
  34.4  38 |    2.5 TEL | Success. Starting cleanup.
  34.4  38 |    2.5 TEL | [4] exit 0
  34.4  38 | [INFO  tini (1)] Main child exited normally (with status '99')
  34.9 TEL | [38] exit 99
  51.7 TEL | (proxy checking local liveness)
  51.8  23 | 2018-05-18T05:39:40+0000 [Poll#info] Checkpoint
  62.7  39 | Failed to connect to proxy in remote cluster.
  62.8  39 | [INFO  tini (1)] Main child exited normally (with status '1')
  63.1 TEL | [39] exit 1 in 32.13 secs.

```

**Comment by ark3** [comment]
I'll need to see more of the telepresence log to troubleshoot this. Can you reply with a link to a GitHub gist of the log file contents, please? Feel free to redact the file contents as needed; I need to see what happens with process 38 in more detail, for example, but I don't need the list of all the other pods that winds up in the log. If you prefer, you can message me privately (e.g., in Gitter) with the log file contents.

Thank you for helping to debug this.

**Comment by artur-ba** [comment]
Hi. This is link to telepresence log: https://gist.github.com/artur-ba/c9d1ffbe15441a54df239a6e6c394bff

**Comment by ark3** [comment]
Thank you for the additional info. Does Telepresence launch successfully if you leave out `--also-proxy 0.0.0.0/0` from your command? It seems like you're trying to work around #391, and I wonder whether that's fouling things up.

**Comment by artur-ba** [comment]
I removed `--also-proxy 0.0.0.0/0` and it works. Thanks for help with this

**Comment by artur-ba** [comment]
Removing `--alos-proxy` help to start the docker container, but still from inside container I don't have access to the internet. I forgot to mention that I am behind corporate proxy
