### ISSUE TITLE
Make the project root (more) reader-friendly

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#654]
- [ ] Populate files in the project root with real content instead of pointing the reader to other documents deeper in the tree (changelog, developing, building, etc.)
- [ ] Add missing files that readers would expect to find (contributing, code of conduct, etc.)
- [ ] Update the website build process to pull the appropriate content into the website from the project root

**Comment by ark3** [comment]
Let's make sure #656 doesn't get lost in the shuffle.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
