### ISSUE TITLE
The proxy stage is not tested independently

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#657]
Let's make the proxy stage independently testable outside of end-to-end tests and write tests for it. This is in service of #628.

The proxy stage is responsible for making sure the Telepresence proxy pod exists and is known. Depending on the specified operation, that might include getting information from the cluster, creating a new deployment, scaling an existing deployment, and other steps.

### Conditions of Satisfaction

- [ ] The data processing pieces of that code are separated from the parts that interact with the cluster
- [ ] There exist unit tests for the data processing steps, like the existing `test_swap_deployment_changes()` test
- [ ] There exist system tests to exercise the parts of the code that talk to the cluster

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
