### ISSUE TITLE
Telepresence with Docker for Mac Kubernetes

### ISSUE THREAD

**Issue by alexei-led** [telepresenceio/telepresence#660]
I'm trying to work with teleprecense and Docker for Mac Kubernetes. Once I start telepresence session `teleprecense --run-shell` I can connect to intenal services, but all external DNS names are not avaiable. Looks like teleprecence intercepts all DNS requests on host and send them to DNS in cluster, than it asks host and host send them again - kind of infinite loop without actual resolving.

**Comment by ark3** [comment]
We intend to move vpn-tcp DNS resolution out of the cluster (#559). That will avoid this DNS loop issue and solve a few other problems. See also #394 and #449. It's in the works!

**Comment by ark3** [comment]
FWIW, you should be able to use the other methods on Docker for Mac with Kubernetes.

**Comment by webular** [comment]
>Looks like teleprecence intercepts all DNS requests on host and send them to DNS in cluster, than it asks host and host send them again - kind of infinite loop without actual resolving.

Did you ever figure out a way around this?  I think I'm seeing the same thing.  [#707](https://github.com/telepresenceio/telepresence/issues/707)

**Comment by sgandon** [comment]
I am also experimenting this unfortunatly also making the cluster unreachable :(
