### ISSUE TITLE
Why my telepresence need password on mac

### ISSUE THREAD

**Issue by ettwz** [telepresenceio/telepresence#662]
my command is:

```shell
telepresence \
--swap-deployment spring-boot-simple-server \
--docker-run \
--rm -v$(pwd):/build \
-v .m2/repository:/m2 \
-p 8080:8080 \
maven:3.5.3-jdk-8-slim \
mvn -Dmaven.repo.local=/m2 -f /build spring-boot:run
```

and logs:

```
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Password:
```
I don't wanna enter password every time. Should I config some value in my command?
Thanks.

**Comment by ark3** [comment]
Telepresence relies on your system's `sudo` command to elevate privileges. There is no Telepresence configuration around this.

You can [adjust the`sudo` configuration](https://askubuntu.com/a/636095) on your machine to increase the timeout beyond the default or even make it infinite. The linked document is an Ubuntu StackExchange article, but the instructions appear to work fine on my Mac as well.
