### ISSUE TITLE
Telepresence - Quick example

### ISSUE THREAD

**Issue by ivanako** [telepresenceio/telepresence#667]
### What were you trying to do?

telepresence --docker-run -it alpine /bin/sh

### What did you expect to happen?

alpine#

### What happened instead?

Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Looks like there's a bug in our code. Sorry about that!

### Automatically included information

Command line: `['/usr/bin/telepresence', '--docker-run', '-it', 'alpine', '/bin/sh']`
Version: `0.88`
Python version: `3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.6.0 // Server Version: v1.9.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux x101172-Ubuntu 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 79, in main
    subprocesses, socks_port, ssh = connect(runner, remote_info, args)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/proxy.py", line 122, in connect
    ssh.wait()
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/ssh.py", line 85, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
in/true
  33.1 TEL | [129] exit 255 in 0.01 secs.
  33.3 TEL | [130] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36512 telepresence@localhost /bin/true
  33.3 TEL | [130] exit 255 in 0.01 secs.
  33.6 TEL | [131] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36512 telepresence@localhost /bin/true
  33.6 TEL | [131] exit 255 in 0.01 secs.
  33.8 TEL | [132] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36512 telepresence@localhost /bin/true
  33.8 TEL | [132] exit 255 in 0.01 secs.
  34.1 TEL | [133] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36512 telepresence@localhost /bin/true
  34.1 TEL | [133] exit 255 in 0.01 secs.
  34.3 TEL | [134] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36512 telepresence@localhost /bin/true
  34.4 TEL | [134] exit 255 in 0.01 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! Can you link to a gist of the full telepresence.log? That will help us figure out what went wrong. I'm curious to see whether the divergent client and server versions are part of the problem -- Telepresence could detect that and warn about it. Thanks for your help.

**Comment by ametad** [comment]
A search result got me here. Just wanted to say I had the same error. But when you re-run the _telepresence_ command, it probably does run correctly. That is what happens in my case anyway. Perhaps this helps a bit.
