### ISSUE TITLE
On lost or failed connection, Telepresence should report proxy pod status/info to simplify troubleshooting

### ISSUE THREAD

**Issue by yuzumikan15** [telepresenceio/telepresence#673]
### What were you trying to do?
I tried to swap a remote k8s deployment with my local docker image.
```
$ docker pull udacity/example-hello:1.0.0
$ telepresence --swap-deployment hello --docker-run \
  --rm -it udacity/example-hello:1.0.0
```

- The source code that I used for my k8s cluster is here: https://github.com/udacity/ud615/tree/master/kubernetes .
- I created the cluster on AWS EC2.
- I could access to my cluster on EC2 via telepresence: `telepresence --docker-run -i -t alpine /bin/sh` and curl command.

### What did you expect to happen?
I wanted to swap only `hello` deployment ([docker image](https://hub.docker.com/r/udacity/example-hello/)) just like the tutorial [here](https://www.telepresence.io/tutorials/docker).

### What happened instead?

`RuntimeError: SSH isn't starting.`
- It look like a pod was recreated on the remote cluster, but it said ssh is not starting.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'hello', '--docker-run', '--rm', '-it', 'udacity/example-hello:1.0.0']`
Version: `0.88`
Python version: `3.6.5 (default, Apr 25 2018, 14:23:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]`
kubectl version: `Client Version: v1.9.6 // Server Version: v1.9.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin yuzuco.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/main.py", line 79, in main
    subprocesses, socks_port, ssh = connect(runner, remote_info, args)
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/proxy.py", line 122, in connect
    ssh.wait()
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/ssh.py", line 85, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
null -p 55626 telepresence@localhost /bin/true
  42.3  18 | Handling connection for 55626
  42.4  18 | E0604 20:24:03.134396   26425 portforward.go:331] an error occurred forwarding 55626 -> 8022: error forwarding port 8022 to pod af315d8cd7649f5efba1cf2edb7ac334b0155f84e826ef38c9564f480e4a9540, uid : exit status 1: 2018/06/04 11:24:03 socat[30381] E connect(5, AF=2 127.0.0.1:8022, 16): Connection refused
  42.4 TEL | [86] exit 255 in 0.15 secs.
  42.7 TEL | [87] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 55626 telepresence@localhost /bin/true
  42.7  18 | Handling connection for 55626
  42.8  18 | E0604 20:24:03.549504   26425 portforward.go:331] an error occurred forwarding 55626 -> 8022: error forwarding port 8022 to pod af315d8cd7649f5efba1cf2edb7ac334b0155f84e826ef38c9564f480e4a9540, uid : exit status 1: 2018/06/04 11:24:03 socat[30382] E connect(5, AF=2 127.0.0.1:8022, 16): Connection refused
  42.8 TEL | [87] exit 255 in 0.16 secs.

```

- [Whole logs](https://gist.github.com/yuzumikan15/b6bb5ddf47ffa8c5aba22bf1e28fd9c2)

Could you help me how to fix it?

**Comment by ark3** [comment]
From the telepresence.log I see that subprocess 17, `kubectl logs`, reports `killed` almost immediately and then quits. This implies that the proxy running the cluster was killed for some reason. That explains why subprocess 18, `kubectl port-forward`, repeatedly reports a "Connection refused" failure when it tries to forward.

The direct error reporting from Telepresence to the user is abysmal here. Sorry about that! You (or I) should not have to dig through the log file to figure out what's going on. We are working to fix this. 

1. Does this failure occur every time you try this?
2. Is [this](https://github.com/udacity/ud615/blob/master/kubernetes/deployments/hello.yaml) the Kubernetes manifest that you're using for your deployment? 

I wonder if the problem is caused by a failing liveness/health probe convincing Kubernetes to kill the pod.

Thank you for submitting the detailed and complete report. We appreciate your help!

**Comment by ark3** [comment]
I tried this myself using the deployment I linked. It turns out that Kubernetes kills the proxy pod because it exceeds the 10Mi memory limit. Can you increase the limit and try again? 

The looping then crashing behavior exhibited by Telepresence could be much better. Telepresence could, upon noticing a dropped connection, query the state of the proxy pod and report if it has been terminated. That much would at least help with troubleshooting.

**Comment by yuzumikan15** [comment]
Thank you so much for your advice.
After I increased the memory limit like 100Mi, the proxy pod successfully started running!

Please let me ask one more thing... Could it be able to use the host names that are the same as ones which I could successfully executed before running the proxy pod?

When I hit the cURL command which I could execute before running the proxy pod, it returned `502 Bad Gateway`.
- Before proxying (from host machine)
```
$ curl -k https://ad634794e72ab11e8803a06c1d0cddde-753528049.ap-northeast-1.elb.amazonaws.com/
{"message": "Hello"}
```

- After proxying (from host machine)
```
$ curl -k curl -k https://ad634794e72ab11e8803a06c1d0cddde-753528049.ap-northeast-1.elb.amazonaws.com/
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.14</center>
</body>
</html>
```

Also, I tried to run it from an alpine image on the k8s cluster, but the same error occurred
- After proxying (from alpine pod)
```/ # curl -k https://ad634794e72ab11e8803a06c1d0cddde-753528049.ap-northeast-1.elb.amazonaws.com/
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.14</center>
</body>
</html>

/ # curl -k https://frontend/
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.14</center>
</body>
</html>
```

I looked up the proxy pod, and I found nginx could not find the hello service.
```
$ kubectl logs hello-0f13de9b-46d7-4967-ba50-1e5c04b9370b-5cb6c67bd6-6f4rr
2018/06/18 04:12:01 [error] 5#5: *154 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.65.63, server: , request: "GET / HTTP/1.1", upstream: "http://100.71.176.107:80/", host: "ad634794e72ab11e8803a06c1d0cddde-753528049.ap-northeast-1.elb.amazonaws.com"
```
- Above, `100.71.176.107` is the Cluster IP of the hello service.

Here, do I need to add some host to nginx.conf to execute the API?

Please let me know if I should close this issue and open another one for this question.

**Comment by ark3** [comment]
Yes, you should be able to use the same DNS names to access your services, and (I think) the `curl` above should work. Can you please open a separate issue to chase that down? It would be handy to have a bit more background info, i.e. what the various names are and how you launched them.

However, please do not close _this_ issue. I would like to use it to track a fix for the original problem, that Telepresence crashes without telling you any useful info. I'll re-title this issue to reflect that.

Thank you!

**Comment by yuzumikan15** [comment]
Ok, I will open a new issue with some logs for this question.
Anyway, I really appreciate you investigating and fixing the problem.

**Comment by yuzumikan15** [comment]
FYI:
I opened the new issue here: https://github.com/telepresenceio/telepresence/issues/689

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
