### ISSUE TITLE
Telepresence requires Python >= 3.5 on the system

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#675]
All the current ways to install Telepresence rely on there being an easy way to install Python 3.5 (or newer). This works fine in many cases and allows Telepresence to be a relatively small download. However, there are plenty of cases (RHEL 6?) where installing Python can be complicated or can cause problems elsewhere on the system. 

For those cases, we should offer a PyInstaller-based distributable binary. See [Kubernaut Agent](https://github.com/datawire/kubernaut-agent/blob/master/build.sh) for an example. We would almost certainly want to produce a binary that supports most glibc-based Linux distributions, probably by starting with the [Python ManyLinux](https://github.com/pypa/manylinux) image. We can also consider offering musl-based Linux (Alpine/Busybox) binaries and MacOS binaries as needed.

**Comment by ark3** [comment]
Note: Telepresence calls `python3 -c ...` here and there. We'll need to see whether `sys.executable` will work for those cases. Otherwise, we'll need to subsume those commands into the Telepresence executable itself. This is not a big deal, but let's not forget.

Note 2: Telepresence uses sshuttle, which also require Python, and which does some weird introspective stuff with its source code. We'll need to see how well _that_ works with PyInstaller.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
