### ISSUE TITLE
Proxy to Kubernetes exited. This is typically due to a lost connection.

### ISSUE THREAD

**Issue by slim-hmidi** [telepresenceio/telepresence#679]
I'm using `telepresence` to debug node.js services. However, I'm not able to debug the program running in my service due to crash of telepresence and I got these errors:
```
Proxy to Kubernetes exited. This is typically due to a lost connection.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/mount.py", line 82, in cleanup
    sudo_prefix + ["fusermount", "-z", "-u", mount_dir]
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 168, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 157, in run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['fusermount', '-z', '-u', '/tmp/tmpm5oun_p0']' returned non-zero exit status 1.
```
**telepresence:** 0.88
**minikube:** 0.25.2
**OS:** 17.10 (64bit).
How can I fix this problem?

**Comment by ark3** [comment]
Telepresence doesn't make it so easy to tell what's going on in this sort of situation, at least not yet! May I take a look at the telepresence.log file from this session? Can give me a link to a Gist? Redacting service names, hostnames, etc. is totally fine.

Thanks for your help!

**Comment by slim-hmidi** [comment]
Actually I don't understand very well your question. I try to explain the service in which I run telepresence: 
The application contains a text field in which I enter a string and each 500ms a query will be sent to a database to fetch data and then returned it to the interface and show the list of data to the user.
I don't understand you very well but does the communication of the service in which the telepresence was run with another service containing the database was the source of the problem?
When I debug with telepresence it took a long time to return results from database to the screen.

**Comment by pandeybk** [comment]
I am seeing the same error message. It works for sometimes approx (30sec), I can browse services also. After that it breaks.

Here is my client log
```
@flagship|bash-3.2$ 
T: Background process (sshuttle) exited with return code 99. Command was:
T:   sshuttle-telepresence -v --dns --method auto -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null' -r telepresence@127.0.0.1:51989 --to-ns 127.0.0.1:9053 10.96.0.0/16 10.25.0.0/24

T: Recent output was:
T:   c : DNS request from ('192.168.64.2', 53452) to None: 34 bytes
T:   c : DNS request from ('192.168.64.2', 40817) to None: 34 bytes
T:   c : DNS request from ('192.168.64.2', 49756) to None: 34 bytes
T:   c : DNS request from ('192.168.64.2', 57104) to None: 34 bytes
T:   >> pfctl -a sshuttle6-12300 -F all
T:   >> pfctl -X 16483679620548383017
T:   >> pfctl -a sshuttle-12300 -F all
T:   >> pfctl -X 16483679620548383113
T:   c : fatal: server died with error code 1


T: Proxy to Kubernetes exited. This is typically due to a lost connection.

T: Exit cleanup in progress
```

Here is my log from pod,

https://gist.github.com/pandeybk/189e4914b9833a3e6756fdf63ff4ba3e

**Comment by ark3** [comment]
@pandeybk Thanks for your report. The pod log seems to show a DNS loop. Are you using a local Kubernetes cluster, like Minikube or Docker? When Telepresence is running, for that 30 seconds or so, are you able to reach your local network or the Internet from your machine?

**Comment by pandeybk** [comment]
Hi @ark3  I am using local kubernetes cluster. Also I was not able to reach to internet during that period.

**Comment by ark3** [comment]
@pandeybk Okay, then DNS loop it is. What type of local Kubernetes cluster is this? Telepresence should detect it and apply the workaround it uses.

**Comment by pandeybk** [comment]
@ark3  when you say what type, you mean how we are creating cluster? It's a custom in-house project we are working.

**Comment by ark3** [comment]
@pandeybk My question was regarding whether you use Minikube or Docker or some other local (entirely on your machine) Kubernetes cluster. Since you have your own variant, the key questions for Telepresence are

1. does the cluster defer to the host machine for DNS queries? This is what causes the DNS loop.
2. how can Telepresence detect your setup to apply its DNS loop workaround?

Thanks!

**Comment by azinneera** [comment]
I encounter the same issue when running Telepresence in default vpn-tcp mode on a local kubeadm setup. How can I resolve this?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
