### ISSUE TITLE
Missing exec bits on telepresence 0.89 binary

### ISSUE THREAD

**Issue by mykarlsson** [telepresenceio/telepresence#682]
Hello.

It looks like the telepresence binary lost some execution bits after updating to 0.89 on Fedora.

At 0.88:
`-rwxr-xr-x. 1 root root 431 May 16 19:59 /usr/bin/telepresence`

After updatung to 0.89:
`-rwxr--r--. 1 root root 48587 Jun 12 00:13 /usr/bin/telepresence`

**Comment by ark3** [comment]
Yikes. Thanks for the issue. We'll cut another release soon.
