### ISSUE TITLE
Telepresence cannot communicate with a  service with istio-sidecars injected into them

### ISSUE THREAD

**Issue by jeson114** [telepresenceio/telepresence#691]
Issue on stackoverflow : [`Issue`](https://stackoverflow.com/questions/50982340/communicating-with-services-deployed-with-istio-sidecar-using-telepresence)

Followed the instructions on https://www.telepresence.io/tutorials/docker
I got QOTM up and i was able to curl it from my local  . But other services in the same pod which were using istio-proxy did not respond . I just got Empty response from server . 
Is there a compatibility issue with Istio  ?

**Comment by ark3** [comment]
You mentioned "other services in the same pod" were not responding via Telepresence. I'm going to assume you meant "same cluster" but please let me know if I misunderstood.

Can you successfully `curl` an Istio service from a shell running in the cluster? If that works, then Telepresence should work as well.

```shell
$ kubectl run curl-test -it --rm --image=fedora --restart=Never -- bash
[root@curl-test /]# curl qotm
{
  "hostname": "qotm-4110712359-9t5xx", 
  "ok": true, 
  "quote": "Non-locality is the driver of truth. By summoning, we vibrate.", 
  "time": "2018-06-22T16:41:07.066532", 
  "version": "1.1"
}
[root@curl-test /]# 
```

To our knowledge, Telepresence should just work with Istio. Can you give us a minimal reproducer so we can try this ourselves? Thank you.

**Comment by jeson114** [comment]
Here is my yaml file 
`apiVersion: v1
kind: ServiceAccount
metadata:
  name: reservoir
---
##################################################################################################
# Reservoir service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reservoir
  labels:
    app: reservoir
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: reservoir
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reservoir-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reservoir
        version: v1
    spec:
      serviceAccountName: reservoir
      containers:
      - name: reservoir
        image: "drpal/acquia-reservoir:1.0.1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
---
##################################################################################################
# Mysql Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-api-test
---
##################################################################################################
# Node Api Service 1
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: node-api-test
  labels:
    app: node-api-test
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: node-api-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-api-test-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-api-test
        version: v1
    spec:
      serviceAccountName: node-api-test
      containers:
      - name: node-api-test
        image: "jeson114/node-api-test:0.0.4"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortio
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fortio-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fortio
    spec:
      serviceAccountName: fortio
      containers:
      - name: fortio
        image: istio/fortio:latest_release
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.* 
        backend:
          serviceName: node-api-test
          servicePort: 3000
          
---`
deploy using istioctl (manual sidecar injection).
`kubectl create -f <(istioctl kube-inject -f ../deployment.yaml)`

`export GATEWAY_URL=$(kubectl get po -l istio=ingress -n istio-system -o 'jsonpath={.items[0].status.hostIP}'):$(kubectl get svc istio-ingress -n istio-system -o 'jsonpath={.spec.ports[0].nodePort}')
`
once the services are up you can  test by hitting the ingress path (follow istio quick setup)
`curl http://$GATEWAY_URL`

now follow install steps for telepresence  from (setup)[https://www.telepresence.io/tutorials/docker]

Now i am able to talk to qotm from my telepresence shell if i set up the qotm service in my cluster . But not to `node-api-test` or any other services that are deployed with istio manual sidecar injection
you can test this by sneaking  into any of the services. 
Test this by calling node-api-test from telepresence  `curl http://node-api-test:3000`
this return no response .
What does work is istio-ingress . But since i need to access some services without going through ingress it is important that this works

**Comment by ark3** [comment]
Thanks for the detailed info about your setup. I will try to reproduce this when I get a chance. In the meantime, an answer to my other question would be helpful too: Can you successfully `curl` an Istio service from a shell running in the cluster? Thank you.

**Comment by JCzz** [comment]
Any progress, I have the same issue?

**Comment by richarddli** [comment]
Thanks for your interest! It's something we want to do, but Istio is a lot of work to set up and debug (as I'm sure you know) and the majority of our customers aren't running Istio. So, it'll be awhile longer before we can get to this. If you're interested in helping to accelerate this, feel free to hop on our Slack and we can chat about ways to help!

**Comment by JCzz** [comment]
Hi @richarddli 

I can make it work with Istio for 10 seconds `telepresence --new-deployment debug-deployment-v1  ...`
If I make a `kubectl patch deployment debug-deployment-v1 --patch "$(cat kube/debug/patch.yaml)"`

```
# K8s - Deployment
spec:
  template:
    metadata:
      labels:
        app: debug-deployment
        version: v1
```

But then the container is killed and new one is starting, and I then have to `kubectl patch` all over again.

I start telepresence with this:
```
telepresence --new-deployment debug-deployment-v1 --docker-run \
  	--rm -it \
	-v $(pwd)/site/build/:/usr/share/nginx/html \
  	nginx bash;
```

Is there any way to define the deployment? 
Because it works if I I set the labels defined in the patch!

Thanks

**Comment by YourTechBud** [comment]
Any progress on this. I'm facing a similar issue
