### ISSUE TITLE
Telepresence 0.9 not working on MAC over VPN 

### ISSUE THREAD

**Issue by manojgoyal04** [telepresenceio/telepresence#692]
### What were you trying to do?

telepresence --new-deployment tele-proxy --also-proxy 192.168.0.0/21 --expose 8080 --namespace xyx --run-shell
### What did you expect to happen?

Deployment shall be created in the cluster

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--new-deployment', 'tele-proxy', '--also-proxy', '192.168.0.0/21', '--expose', '8080', '--namespace', 'maglev-system', '--run-shell']`
Version: `0.90`
Python version: `3.6.5 (default, Jun 17 2018, 12:13:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.10.5 // Server Version: v1.7.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin MAGOYAL-M-V2U6 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 313, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 297, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence11')"]' returned non-zero exit status 1.

```

Logs:

```
17 | 2018-06-23T01:28:52+0000 [stdout#info] Result for b'hellotelepresence11.cisco.com' is ['127.0.0.1']
  44.3  26 | c : DNS request from ('10.65.34.30', 50479) to None: 47 bytes
  44.3  17 | 2018-06-23T01:28:53+0000 [stdout#info] Result for b'hellotelepresence11.cisco.com' is ['127.0.0.1']
  45.6 TEL | (proxy checking local liveness)
  45.6  17 | 2018-06-23T01:28:55+0000 [Poll#info] Checkpoint
  49.3  26 | c : DNS request from ('10.65.34.30', 50479) to None: 47 bytes
  49.3  17 | 2018-06-23T01:28:58+0000 [stdout#info] Result for b'hellotelepresence11.cisco.com' is ['127.0.0.1']
  53.3  26 | c : DNS request from ('10.65.34.30', 50479) to None: 47 bytes
  53.3  17 | 2018-06-23T01:29:02+0000 [stdout#info] Result for b'hellotelepresence11.cisco.com' is ['127.0.0.1']
  73.3  38 | Traceback (most recent call last):
  73.3  38 |   File "<string>", line 1, in <module>
  73.3  38 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  73.3 TEL | [38] exit 1 in 30.22 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! Can you link to a gist with the full telepresence.log file, please? The snippet of the end of the logs in the crash report is confusing; it looks like DNS requests are being handled successfully yet Telepresence crashes on failed DNS. Getting a look at what has already occurred would be helpful.

Thank you.

**Comment by manojgoyal04** [comment]
I tried following command

telepresence --new-deployment tele-proxy --also-proxy 10.60.0.0/21 --expose 8080 --namespace maglev-system --run-shell



 112.3  26 | c : DNS request from ('10.65.33.214', 49646) to None: 43 bytes
 112.3  17 | 2018-07-03T16:43:35+0000 [stdout#info] A query: b'ci5.googleusercontent.com'
 112.3  17 | 2018-07-03T16:43:35+0000 [stdout#info] AAAA query, sending back A instead: b'ci5.googleusercontent.com'
 112.3  17 | 2018-07-03T16:43:35+0000 [stdout#info] A query: b'ci5.googleusercontent.com'
 112.3  17 | 2018-07-03T16:43:35+0000 [stdout#info] Result for b'ci5.googleusercontent.com' is ['172.217.7.161']
 112.4  17 | 2018-07-03T16:43:35+0000 [stdout#info] Result for b'ci5.googleusercontent.com' is ['172.217.7.161']
 115.3  41 | Traceback (most recent call last):
 115.3  41 |   File "<string>", line 1, in <module>
 115.3  41 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
 115.3 TEL | [41] exit 1 in 30.15 secs.
 116.9  26 | c : DNS request from ('10.65.33.214', 21136) to None: 33 bytes
 116.9  17 | 2018-07-03T16:43:40+0000 [stdout#info] A query: b'mail.google.com'
 117.3  26 | c : DNS request from ('10.65.33.214', 63923) to None: 43 bytes
 117.3  26 | c : DNS request from ('10.65.33.214', 49646) to None: 43 bytes
 117.3  17 | 2018-07-03T16:43:40+0000 [stdout#info] A query: b'ci5.googleuser
 127.7  26 | c : DNS request from ('10.65.33.214', 63948) to None: 41 bytes
 127.7  17 | 2018-07-03T16:43:50+0000 [stdout#info] A query: b'googlemail.l.google.com'
 127.8  17 | 2018-07-03T16:43:50+0000 [stdout#info] Result for b'googlemail.l.google.com' is ['172.217.7.165']
 130.7  26 | c : DNS request from ('10.65.33.214', 61400) to None: 33 bytes
 130.7  26 | c : DNS request from ('10.65.33.214', 54161) to None: 33 bytes
 130.7  17 | 2018-07-03T16:43:53+0000 [stdout#info] A query: b'conv-a.wbx2.com'
 130.7  17 | 2018-07-03T16:43:53+0000 [stdout#info] AAAA query, sending back A instead: b'conv-a.wbx2.com'
 130.7  17 | 2018-07-03T16:43:53+0000 [stdout#info] A query: b'conv-a.wbx2.com'
 130.7  17 | 2018-07-03T16:43:53+0000 [stdout#info] Result for b'conv-a.wbx2.com' is ['13.59.223.19', '13.59.223.252', '13.59.223.29', '13.59.223.250', '13.59.223.32', '13.59.223.31', '13.59.223.249', '13.59.223.86']
 130.7  17 | 2018-07-03T16:43:53+0000 [stdout#info] Result for b'conv-a.wbx2.com' is ['13.59.223.249', '13.59.223.86', '13.59.223.19', '13.59.223.252', '13.59.223.29', '13.59.223.250', '13.59.223.32', '13.59.223.31']
 131.7  26 | c : DNS request from ('10.65.33.214', 63948) to None: 41 bytes
 131.7  17 | 2018-07-03T16:43:54+0000 [stdout#info] A query: b'googlemail.l.google.com'
 131.7  17 | 2018-07-03T16:43:54+0000 [stdout#info] Result for b'googlemail.l.google.com' is ['172.217.7.165']
 134.0  26 | c : DNS request from ('10.65.33.214', 56497) to None: 41 bytes
 134.0  17 | 2018-07-03T16:43:57+0000 [stdout#info] AAAA query, sending back A instead: b'googlemail.l.google.com'
 134.0  17 | 2018-07-03T16:43:57+0000 [stdout#info] A query: b'googlemail.l.google.com'
 134.0  17 | 2018-07-03T16:43:57+0000 [stdout#info] Result for b'googlemail.l.google.com' is ['172.217.7.165']
 134.7 TEL | [42] Capturing: umount -f /tmp/tmpf1f5_dw_
 134.7  26 | c : DNS request from ('10.65.33.214', 61400) to None: 33 bytes
 134.7  26 | c : DNS request from ('10.65.33.214', 54161) to None: 33 bytes
 134.7 TEL | [17] exit -15
 134.7  26 | Connection to localhost closed by remote host.
 134.7  22 | Connection to localhost closed by remote host.
 134.7 TEL | [18] exit -15
 134.7  23 | Connection to localhost closed by remote host.
 134.7 TEL | [23] exit 255
 134.7 TEL | [22] exit 255
 134.7  26 | >> pfctl -a sshuttle6-12300 -F all
 134.7  26 | >> pfctl -X 6579903123504905805
 134.8  26 | >> pfctl -a sshuttle-12300 -F all
 134.8  26 | >> pfctl -X 6579903123504906957
 134.8  26 | c : fatal: server died with error code 255
 134.8 TEL | [26] exit 99
 134.9 TEL | [43] Capturing: kubectl --context kubernetes-admin@kubernetes --namespace maglev-system delete --ignore-not-found svc,deploy --selector=telepresence=bffa9f43-7bc5-41f4-947f-e54efbfcd779
 140.8 TEL | [43] captured in 5.92 secs.
 140.8 TEL | END SPAN main.py:51(main)  140.2s

**Comment by manojgoyal04** [comment]
One observation, If my MAC is connected to the same network directly, it works fine. Above problem is observed only when MAC is connected to cluster over VPN. So please provide a solution for Telepresence to work over VPN connection.

I tried following methods,
. tcp-inject - with this method, it works over VPN also, but due to limitations of this method some DNS resolution of cluster services doesnt happen, so service running on my MAC not able to connect to cluster services.

. vpn-tcp - didn't work

**Comment by manojgoyal04** [comment]
In my use case, we want to run cluster service in MAC as a process not as a container. Container method works only with docker-run, if my understanding is correct.

--docker-run' is required when using '--method container

**Comment by Solleys9808** [comment]
So here's an idea many months ago my brand new Galaxy S9+ was hacked and possibly rooted through my Solleys6@gmail.com account Google locked my brand new phone so I had to get a new phone, list my email I have had for years with all my kids photos attached to. I have been following Google take over my account that they said they couldn't help me recover and now I'm seeing this. I searched for ip address and it brought me here your dns request I attached to the email and have been monitoring so that could be the glitch. I would greatly appreciate access back to my Google/Gmail account and would think it would be illegal to access someone's computer and change their passwords locking them out in order to gain access to their files or emails/accounts. I worked on this for months. My home alarm was compromised someone was remotely turning it off and on and changing password. Taking pictures from smart TVs and even using Geo location on my car pictures of my kids. Very sad to see this. Shame on you!! Someone please call me so I can have my account back. 682-220-2499

**Comment by Kawabaumga** [comment]
Hi all,
Any update about a method working over VPN please?

**Comment by ark3** [comment]
No news here. Telepresence works fine with VPNs if you use the inject-tcp or container methods. It does not work with the vpn-tcp method.

**Comment by ipleten** [comment]
`telepresence --swap-deployment pipe-test-902 --namespace ps --docker-run --rm -it pipe-test --method container`
Get the same error.

**Comment by ark3** [comment]
@ipleten Can you please file that as a separate issue and include the full telepresence.log as a GitHub gist? Thank you.

**Comment by ipleten** [comment]
We found the problem.
Due to project specific things 'ndot' value of DnsConfig section is changed to  '1'
So if we set it something higher everything works:
>   dnsConfig:
>     options:
>       - name: ndots
>         value: "1"

(Gihub breaks the YAML syntax above)
Sorry I didn't post earlier.

**Comment by anil-venkata** [comment]
Hi Team,

Any news about this , we are also facing the same issue. Our scenario is different.

We are using AWS EKS. we are able to use telepresence with vpn-tcp method till the cluster is available for public, but based on the infosec requirements we are making the cluster as private and can be accessible via VPN. With the VPN we can able to access cluster via Private IP. So we have to connect to the VPN to access
and with the VPN we can't use the telepresence with method vpn-tcp.
Our main use case is we need to access the services http://service-name:port  from the tools like postman. and we tried with the inject-tcp and container but we can able to ping the service from the container/from that terminal, but not from the other tab or from the postman where as it is working with vpn-tcp.

Can you please guide us  if we have any work-around solutions or and other alternatives. 

Thanks a lot in advance.

**Comment by ipleten** [comment]
I was able to make vpn-tcp working on MacOs via https://github.com/stormbeta/telepresence-wrapper

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
