### ISSUE TITLE
sudo: no tty and no askpass fails the run

### ISSUE THREAD

**Issue by utrack** [telepresenceio/telepresence#693]
### What were you trying to do?

`telepresence --docker-run -i -t alpine /bin/sh`

### What did you expect to happen?
Open console inside k8s cluster

### What happened instead?
Crash :)

### Automatically included information

Command line: `['/opt/telepresence/telepresence-venv/bin/telepresence', '--docker-run', '-i', '-t', 'alpine', '/bin/sh']`
Version: `0.88`
Python version: `3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]`
kubectl version: `Client Version: v1.10.3 // Server Version: v1.10.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux galley 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/main.py", line 105, in main
    mount_dir,
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/container.py", line 132, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 168, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 157, in run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['sudo', 'docker', 'run', '--network=container:telepresence-1530030359-89293-28778', '--rm', 'datawire/telepresence-local:0.88', 'wait']' returned non-zero exit status 1.

```

Logs:

```
AN mount.py:36(mount_remote_volumes)    0.1s
   9.1 TEL | BEGIN SPAN vpn.py:84(get_proxy_cidrs)
   9.1 TEL | END SPAN vpn.py:84(get_proxy_cidrs)    0.0s
   9.1 TEL | BEGIN SPAN container.py:113(run_docker_command)
   9.1 TEL | [28] Launching: sudo docker run --rm --privileged --name=telepresence-1530030359-89293-28778 datawire/telepresence-local:0.88 proxy '{"port": 35151, "cidrs": ["10.20.26.192/26", "10.20.26.0/26", "10.20.24.128/26", "10.20.24.0/26", "10.20.24.64/26", "10.20.24.192/26", "10.20.27.0/26", "10.20.26.128/26", "10.20.25.0/26", "10.20.25.128/26", "10.20.26.64/26", "10.96.0.0/12", "10.20.25.192/26", "10.20.25.64/26"], "expose_ports": []}'
   9.2 TEL | [29] Running: sudo docker run --network=container:telepresence-1530030359-89293-28778 --rm datawire/telepresence-local:0.88 wait
   9.2  28 | sudo: no tty present and no askpass program specified
   9.2 TEL | [28] exit 1
   9.2  29 | sudo: no tty present and no askpass program specified
   9.2 TEL | [29] exit 1 in 0.03 secs.

```

**Comment by utrack** [comment]
When I try to do `SSH_ASKPASS=ssh-askpass telepresence --docker-run -i -t alpine /bin/sh` it still doesn't work - `ssh-askpass` is present at $PATH.
Forwarding an envvar should work.

**Comment by ark3** [comment]
Does your sudo setup require a password every single time? If not, a quick workaround would be to run `sudo -v` or `sudo true` immediately prior to running Telepresence.

Telepresence does not try to cleanse the environment before launching Docker, so your `SUDO_ASKPASS` trick should work. (Note that you wrote `SSH_ASKPASS` instead of `SUDO_ASKPASS`, but I suspect that's just a typo here in GitHub.)

**Comment by utrack** [comment]
Oops, that was a typo indeed - `SUDO_ASKPASS` works nicely. Thank you :)
