### ISSUE TITLE
Question: specify k8s deployment / sidecars / etc

### ISSUE THREAD

**Issue by utrack** [telepresenceio/telepresence#694]
We're using linkerd over k8s, which requires us to use companion pod and an initContainer for any container that gets deployed.
Is there any way to specify k8s deployment for a `telepresence --docker-run`, or I'll need to make an autoinjector per namespace?

**Comment by ark3** [comment]
If you're swapping a deployment, you can specify a specific container to swap. Telepresence will replicate the original manifest contents and modify only the portions that are relevant. 

If the default mechanism for launching a new deployment does not do the right thing, you can also [set up a deployment manually](https://www.telepresence.io/reference/connecting#running-telepresence-manually).

I'm not sure whether I've answered your question, so please follow up here. Also, you may wish to join [our public Slack](https://d6e.co/slack).
