### ISSUE TITLE
telepresence doesn't start

### ISSUE THREAD

**Issue by gawen** [telepresenceio/telepresence#698]
### What were you trying to do?

Running the following command to my GCP cluster,

```bash
telepresence
```

The version is 0.90, compiled from the source.

### What did you expect to happen?

To finish its initialization

### What happened instead?

A traceback is raised

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.90`
Python version: `3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]`
kubectl version: `Client Version: v1.10.0 // Server Version: v1.8.10-gke.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux XXX 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence/telepresence/main.py", line 110, in main
    mount_dir
  File "/usr/local/bin/telepresence/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/bin/telepresence/telepresence/vpn.py", line 313, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence/telepresence/vpn.py", line 297, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence108')"]' returned non-zero exit status 1.

```

Logs:

```
known
  32.9 TEL | [132] exit 1 in 0.06 secs.
  33.0 TEL | [133] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence106'"'"')'
  33.1 133 | Traceback (most recent call last):
  33.1 133 |   File "<string>", line 1, in <module>
  33.1 133 | socket.gaierror: [Errno -2] Name or service not known
  33.1 TEL | [133] exit 1 in 0.08 secs.
  33.2 TEL | [134] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence107'"'"')'
  33.3 134 | Traceback (most recent call last):
  33.3 134 |   File "<string>", line 1, in <module>
  33.3 134 | socket.gaierror: [Errno -2] Name or service not known
  33.3 TEL | [134] exit 1 in 0.09 secs.
  34.5 TEL | [135] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence108'"'"')'
  34.6 135 | Traceback (most recent call last):
  34.6 135 |   File "<string>", line 1, in <module>
  34.6 135 | socket.gaierror: [Errno -2] Name or service not known
  34.6 TEL | [135] exit 1 in 0.08 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! Telepresence does not (yet) do a good job of detecting and reporting problems during startup. Can you pass along the entire telepresence.log file as a GitHub gist?

Thanks for your help.

**Comment by blak3mill3r** [comment]
https://gist.github.com/blak3mill3r/37fcf344be339947da9a7061e14fdfd5

Same symptom for me, as of today (it was working yesterday), on Debian Jessie with the Xenial `.deb` packages from `telepresence.io`, and with my from-source `0.75` build that I had been using successfully up until yesterday.

It struck me as interesting that this same symptom occurs for me using either `0.75` or `0.90`, and my cluster is on AWS whereas @Gawen is on GCE.

Also I'm using `python3` from Debian Jessie which is

```
 ➢$ python3 --version
Python 3.5.2

```

```
 ➢$ uname -a
Linux manticore 4.9.88 #1 SMP Tue Jul 3 00:56:21 UTC 2018 x86_64 GNU/Linux
```

**Comment by blak3mill3r** [comment]
Ah, interesting...

Yesterday I updated my kernel, to `4.9.88`, that broke it with the same symptom as @Gawen reported.

I downgraded back to `3.16.0-6-amd64` from Debian Jessie, and it works fine again. HTH

**Comment by Gawen** [comment]
@ark3, thank you for the support !

> Can you pass along the entire telepresence.log file as a GitHub gist?

[Here's my `telepresence.log`](https://gist.github.com/Gawen/364b76c549f5fb00ed325da5e7e4b4b6).

**Comment by ark3** [comment]
I'm a bit out of my depth here and could use some help (@rhs any ideas?), but out of curiosity, can you try disabling `firewalld` to see whether that allows things to work? Something like `sudo systemctl disable firewalld`, depending on your system.

If that works, that may be a viable work-around in the short run. Either way, please let us know here.

**Comment by scotte** [comment]
Same problem here, trying telepresence for the first time and it bombs out with:

```
Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 85, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 61, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 287, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 273, in get_hellotelepresence
    format(next(counter))
  File "/usr/bin/telepresence/telepresence/runner/__init__.py", line 368, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence75')"]' returned non-zero exit status 1.
```
I suspect the problem is because of the k8s cluster running in gossip mode with a ".local" domain, which doesn't work with **--method vpn-tcp** per the docs. If I run with **--method inject-tcp** I get the expected response.
