### ISSUE TITLE
telepresence could not find pod on k8s cluster

### ISSUE THREAD

**Issue by vgupta1519** [telepresenceio/telepresence#703]
Trying to check network proxy using wiki-link https://www.telepresence.io/tutorials/kubernetes-client
On Running curl-command (telepresence --run curl http://myservice:8000/)
telepresence throw an error 

It looks like the telepresence-proxy container start was initated but somehow could not be connected and finally terminated. It seems that even the termination got stuck for quite-long.
 kubectl get pods 
NAME                                                    READY     STATUS        RESTARTS   AGE
myservice-5d99696d49-lsdvc                              1/1       Running       0          2d
qotm-6795b8b47b-x98z4                                   1/1       Running       0          6d
sleep-776b7bcdcd-fpg98                                  1/1       Running       0          23d
telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7   1/1       Terminating   0          7m
vikashs-mbp:~ Vikash$ kubectl get pods 
NAME                                                    READY     STATUS        RESTARTS   AGE
myservice-5d99696d49-lsdvc                              1/1       Running       0          2d
qotm-6795b8b47b-x98z4                                   1/1       Running       0          6d
sleep-776b7bcdcd-fpg98                                  1/1       Running       0          23d
telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7   1/1       Terminating   0          13m
vikashs-mbp:~ Vikash$ 

telepresence --run curl http://myservice:8000 
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/main.py", line 76, in main
    remote_info = start_proxy(runner, args)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/proxy.py", line 222, in start_proxy
    run_id=run_id,
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/remote.py", line 233, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/remote.py", line 145, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2018-07-12T18:43:17Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-07-12T18:43:17Z', 'message': 'containers with unready status: [telepresence-1531420994-432918-16244]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-07-12T18:43:17Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.90', 'imageID': '', 'lastState': {}, 'name': 'telepresence-1531420994-432918-16244', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'ContainerCreating'}}}], 'hostIP': '10.99.0.3', 'phase': 'Pending', 'qosClass': 'Burstable', 'startTime': '2018-07-12T18:43:17Z'}

And here are the last few lines of the logfile (see /Users/Vikash/telepresence.log for the complete logs):

 111.6 TEL | [185] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 112.2 TEL | [186] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 112.8 TEL | [187] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 113.4 TEL | [188] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 114.0 TEL | [189] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 114.5 TEL | [190] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 115.1 TEL | [191] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 115.7 TEL | [192] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 116.3 TEL | [193] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 117.0 TEL | [194] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 117.8 TEL | [195] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 118.4 TEL | [196] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 119.0 TEL | [197] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 119.7 TEL | [198] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 120.2 TEL | [199] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 120.8 TEL | [200] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 121.4 TEL | [201] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 121.9 TEL | [202] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 122.5 TEL | [203] Capturing: kubectl --context gke_alto-dev-200221_us-central1-a_alto-dev-k8s --namespace default get pod telepresence-1531420994-432918-16244-5bc6dd6567-rtzn7 -o json
 123.1 TEL | END SPAN remote.py:122(wait_for_pod)  120.2s

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd reallvikavikashvikashs-mbp:~vikasvvvikashs-mbp:~ Vivikvikavvvvvikashs-mbp:~ Vikash$

**Comment by ark3** [comment]
Sorry about the crash! What happens if you [run the Telepresence proxy manually](https://www.telepresence.io/reference/connecting#running-telepresence-manually)?

Thanks for your help.

**Comment by vgupta1519** [comment]
Hi Abhay,

Thanks a lot for your response.

I tried to run telepresence proxy manually .

I am not getting stack-trace but I am getting the login-prompt asking to input password.
Here is the screen-dump for telepresense manual-run.

I am trying to run telepresence from a macbook. I read that macbook has some limiations “MacOS System Integrity Protection” and not sure if I am hitting one of those.
Any information regarding this will be a big-help ( Link I am following is https://www.telepresence.io/reference/methods https://www.telepresence.io/reference/connecting#running-telepresence-manually

Regards
Vikash
================================
vikashs-mbp:telepresence-test Vikash$ pwd
/tmp/telepresence-test
vikashs-mbp:telepresence-test Vikash$ vi telepresence.yaml
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$ kubectl apply -f telepresence.yaml
deployment "myservice" created
vikashs-mbp:telepresence-test Vikash$ kubectl get deployments
NAME        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
myservice   1         1         1            1           14s    =====> Telepresence proxy
sleep       1         1         1            1           24d
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$ kubectl get pods
NAME                                                     READY     STATUS        RESTARTS   AGE
myservice-7946bbdb46-f8fbw                               1/1       Running       0          19s
sleep-776b7bcdcd-fpg98                                   1/1       Running       0          24d
telepresence-1531422194-7568572-17442-7f86d6f9db-4j9dt   0/1       Terminating   0          1d
telepresence-1531422194-7568572-17442-7f86d6f9db-thxv4   1/1       Terminating   0          15m
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$ telepresence --deployment myservice --run-shell
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.


Password:
Sorry, try again.
Password:
Sorry, try again.
=====================


Here is my telepresence proxy yaml file

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myservice
spec:
  replicas: 1  # only one replica
  template:
    metadata:
      labels:
        name: myservice
    spec:
      containers:
      - name: myservice
        image: datawire/telepresence-k8s:0.90  # new image

====================

**Comment by vgupta1519** [comment]
Hi Abhinav,

I could run the shell after providing my system password at below prompt.

Thanks
Vikash

From: "Gupta, Vikash" <Vikash.Gupta@arris.com>
Date: Friday, July 13, 2018 at 12:20 PM
To: telepresenceio/telepresence <reply@reply.github.com>, telepresenceio/telepresence <telepresence@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [telepresenceio/telepresence] telepresence could not find pod on k8s cluster (#703)

Hi Abhay,

Thanks a lot for your response.

I tried to run telepresence proxy manually .

I am not getting stack-trace but I am getting the login-prompt asking to input password.
Here is the screen-dump for telepresense manual-run.

I am trying to run telepresence from a macbook. I read that macbook has some limiations “MacOS System Integrity Protection” and not sure if I am hitting one of those.
Any information regarding this will be a big-help ( Link I am following is https://www.telepresence.io/reference/methods https://www.telepresence.io/reference/connecting#running-telepresence-manually

Regards
Vikash
================================
vikashs-mbp:telepresence-test Vikash$ pwd
/tmp/telepresence-test
vikashs-mbp:telepresence-test Vikash$ vi telepresence.yaml
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$ kubectl apply -f telepresence.yaml
deployment "myservice" created
vikashs-mbp:telepresence-test Vikash$ kubectl get deployments
NAME        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
myservice   1         1         1            1           14s    =====> Telepresence proxy
sleep       1         1         1            1           24d
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$ kubectl get pods
NAME                                                     READY     STATUS        RESTARTS   AGE
myservice-7946bbdb46-f8fbw                               1/1       Running       0          19s
sleep-776b7bcdcd-fpg98                                   1/1       Running       0          24d
telepresence-1531422194-7568572-17442-7f86d6f9db-4j9dt   0/1       Terminating   0          1d
telepresence-1531422194-7568572-17442-7f86d6f9db-thxv4   1/1       Terminating   0          15m
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$
vikashs-mbp:telepresence-test Vikash$ telepresence --deployment myservice --run-shell
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.


Password:
Sorry, try again.
Password:
Sorry, try again.
=====================


Here is my telepresence proxy yaml file

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myservice
spec:
  replicas: 1  # only one replica
  template:
    metadata:
      labels:
        name: myservice
    spec:
      containers:
      - name: myservice
        image: datawire/telepresence-k8s:0.90  # new image

====================

**Comment by ark3** [comment]
It looks like your manual deployment runs successfully. Telepresence is using `sudo`; that is asking you for your password. If you type correct password, you should get a shell running under Telepresence with direct access to the cluster.

Telepresence definitely needs work around `sudo`: https://github.com/telepresenceio/telepresence/issues/262#issuecomment-355658866

The command you're running uses the default vpn-tcp method. This method is not limited by Mac SIP.

**Comment by vgupta1519** [comment]
Hey Abhay,

Yes that worked for me with run-shell and deployment option.

What is still not working is swap-deployment

**Comment by ark3** [comment]
Does your original example work now? `telepresence --curl http://myservice:8000`

**Comment by vgupta1519** [comment]
Hi Abhay,

Well my original example of swapping service is not working.
It still gives me error the moment any traffic needs to be back-routed from k8s cluster to my laptop .
I get a tcp-connection reset error. ( Pls. note that I am not on VPN).

Thanks
Vikash

**Comment by vgupta1519** [comment]
Hi Abhay,

Wondering if there is any workaround required if my K8S cluster is running in GKE.
Also can you suggest how can I check which tunnels/routes/firewall rules get added/modified when telepresence tries to swap a deployment.

May be I can try to check at what stage it get stuck and help better to debug it.

Regards
Vikash

From: "Gupta, Vikash" <Vikash.Gupta@arris.com>
Date: Tuesday, July 17, 2018 at 10:40 AM
To: telepresenceio/telepresence <reply@reply.github.com>, telepresenceio/telepresence <telepresence@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [telepresenceio/telepresence] telepresence could not find pod on k8s cluster (#703)

Hi Abhay,

Well my original example of swapping service is not working.
It still gives me error the moment any traffic needs to be back-routed from k8s cluster to my laptop .
I get a tcp-connection reset error. ( Pls. note that I am not on VPN).

Thanks
Vikash
