### ISSUE TITLE
Container method to use images from minikube's docker daemon

### ISSUE THREAD

**Issue by oohjayjay** [telepresenceio/telepresence#705]
I have an application running in minikube. I pushed the container images to minikube's docker daemon by using `eval $(minikube docker-env)` and deployed it in minikube.

When I try to run telepresence using --docker-run <image>, I am getting this error:

`docker: Error response from daemon: exec: "docker-init": executable file not found in $PATH.`

If I'm not mistaken, when telepresence executes a "docker run" it adds "--init" automatically but it seems like minikube complains, hence the error.

When I switched back to use my host registry using `eval $(minikube docker-env -u), obviously this will produce an error as it wont be able to find the image.

I can potentially build the image in my host registry (and that works), but it seems like an additional overhead to build and push the images in 2 places. Is there a way to get around this?

**Comment by ark3** [comment]
You can pass `--init=false` as part of your Docker arguments. That will override the hard-coded `--init` inserted by Telepresence. 

```shell
$ telepresence --docker-run --rm -it ubuntu bash -c "ps -xf"

T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
  PID TTY      STAT   TIME COMMAND
    1 pts/0    Ss     0:00 /dev/init -- bash -c ps -xf
    8 pts/0    R+     0:00 ps -xf
T: Exit cleanup in progress
$ 
$ telepresence --docker-run --rm -it --init=false ubuntu bash -c "ps -xf"

T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
  PID TTY      STAT   TIME COMMAND
    1 pts/0    Rs+    0:00 ps -xf
T: Exit cleanup in progress
```

Note that using Minikube's Docker daemon will work, but Docker bind mounts will not work as expected. You will not be able to see remote volumes in your container because Docker will be mounting the MInikube VM's filesystem, not your host filesystem.

**Comment by oohjayjay** [comment]
Thank you for your reply. Unfortunately, I need the mount (-v) to be able to make changes in the code locally and see the change instantly: 

`telepresence --swap-deployment sample-app:app --docker-run --rm -v $(pwd)/app:/app sample-app-image:v1`

**Comment by ark3** [comment]
Yes, of course. That's one of the best ways to use Telepresence. But I don't see how you'll be able to achieve useful volume mounts while using Minikube's Docker daemon. This doesn't really have anything to do with Telepresence.

**Comment by oohjayjay** [comment]
Ok, I'm just wondering if there is a way (as I might have missed it in the documentation). I will just create the image in my host registry as well. Thanks again!
