### ISSUE TITLE
crash running node process

### ISSUE THREAD

**Issue by djMax** [telepresenceio/telepresence#708]
### What were you trying to do?

Run telepresence with a node workload

### What did you expect to happen?

The service to start

### What happened instead?

telepresence went kaboom

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'inject-tcp', '--run', 'node', 'node_modules/.bin/start-server', '--module', '@gasbuddy/gb-services', '--className', 'GbService']`
Version: `0.90`
Python version: `3.7.0 (default, Jul 20 2018, 13:26:15) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.8.3 // Server Version: v1.9.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Maxs-MBP.pyralis.com 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/local.py", line 164, in run_local_command
    setup_torsocks(runner, env, socks_port, unsupported_tools_path)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/local.py", line 128, in setup_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
86] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  36.9  86 | Traceback (most recent call last):
  36.9  86 |   File "<string>", line 1, in <module>
  36.9  86 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  36.9 TEL | [86] exit 1 in 0.16 secs.
  37.0 TEL | [87] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  37.2  87 | Traceback (most recent call last):
  37.2  87 |   File "<string>", line 1, in <module>
  37.2  87 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  37.2 TEL | [87] exit 1 in 0.14 secs.
  37.3 TEL | [88] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  37.4  88 | Traceback (most recent call last):
  37.4  88 |   File "<string>", line 1, in <module>
  37.4  88 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  37.4 TEL | [88] exit 1 in 0.15 secs.

```

**Comment by richarddli** [comment]
I don't believe inject-tcp works with Node. Is there a particular reason you're trying to use it?

**Comment by ark3** [comment]
Sorry about that crash! The inject-tcp method does not work with most versions of Node in many configurations, but I do not think your session is getting that far.

Are you able to resolve google.com from within the cluster? That's how Telepresence checks on connectivity to the proxy running in the cluster. Here's a quick way to check:

```shell
$ kubectl run dns-test -it --rm --image=fedora --restart=Never -- curl -I google.com
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: unable to upgrade connection: container dns-test not found in pod dns-test_default
HTTP/1.1 301 Moved Permanently
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Thu, 26 Jul 2018 17:07:03 GMT
Expires: Sat, 25 Aug 2018 17:07:03 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

pod "dns-test" deleted
$ 
```

Please let me know if you see something similar. If it doesn't work, you might see "Could not resolve host" or "Connection refused" or some other error.

It is true that inject-tcp has trouble with Node, due to #195 and its related issues, which we cannot fix in Telepresence code alone. We're considering a `torsocks` modification to fix things; this is tracked in #576, along with a quick summary of the situation.

**Comment by djMax** [comment]
This crash is sporadic, so while yes, I can resolve google.com, perhaps our cluster DNS is flaking. Wouldn't be the first time, and it may be tied to ambassador. We're tracking something that smells like https://github.com/datawire/ambassador/issues/568

**Comment by djMax** [comment]
The VPN version gives all sorts of "disclaimers" so I figured I didn't want that. When it doesn't crash, inject-tcp does work with node.

**Comment by felipellrocha** [comment]
Is the incompatibility between node and `inject-tcp` documented somewhere?
