### ISSUE TITLE
Can't connect to cluster

### ISSUE THREAD

**Issue by NoraCodes** [telepresenceio/telepresence#710]
### What were you trying to do?

Connect to a cluster using Telepresence (`telepresence --run-shell`)

### What did you expect to happen?

Spawn a shell connected to the cluster

### What happened instead?

I was asked for my password for `sudo`, then got the traceback below.

### Automatically included information

Command line: `['/opt/telepresence/telepresence-venv/bin/telepresence', '--run-shell']`
Version: `0.88`
Python version: `3.6.6 (default, Jun 27 2018, 13:11:40) 
[GCC 8.1.1 20180531]`
kubectl version: `Client Version: v1.10.0 // Server Version: v1.10.5-gke.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux rochallor 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/vpn.py", line 281, in connect_sshuttle
    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 208, in popen
    track, out_cb, err_cb, args, done=done, **kwargs
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 138, in launch_command
    process = launch_command(args, out_cb, err_cb, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 274, in launch_command
    process = Popen(args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

```

Logs:

```
ocol starting on 9053
  16.9  22 | 2018-07-25T19:30:31+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f36c02cd0b8>
  16.9  22 | 2018-07-25T19:30:31+0000 [-] Loaded.
  17.0  22 | 2018-07-25T19:30:31+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.4.0 (/usr/bin/python3.6 3.6.1) starting up.
  17.0  22 | 2018-07-25T19:30:31+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  21.8 TEL | BEGIN SPAN vpn.py:258(connect_sshuttle)
  21.8 TEL | BEGIN SPAN vpn.py:84(get_proxy_cidrs)
  21.8 TEL | END SPAN vpn.py:84(get_proxy_cidrs)    0.0s
  21.8 TEL | [34] Launching: sshuttle-telepresence -v --dns --method nat -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence@localhost:46553 10.60.1.0/24 10.60.2.0/24 10.63.240.0/20
  21.8 TEL | [34] [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

```

**Comment by jonnyt886** [comment]
I have the same issue. Arch Linux, up to date, running Telepresence 0.88 on Minikube 0.28.0.

	$ telepresence --deployment telepresence --run-shell
	vpn-tcp method doesn't work with minikube/minishift when using --deployment. Use --swap-deployment or --new-deployment instead.
	$ telepresence --swap-deployment telepresence --run-shell
	Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
	Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

	No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

	sudo: no tty present and no askpass program specified

	Looks like there's a bug in our code. Sorry about that!

	Here's the traceback:

	Traceback (most recent call last):
	  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
	    return f(*args, **kwargs)
	  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/main.py", line 110, in main
	    mount_dir
	  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/local.py", line 167, in run_local_command
	    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
	  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/vpn.py", line 281, in connect_sshuttle
	    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
	  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 208, in popen
	    track, out_cb, err_cb, args, done=done, **kwargs
	  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 138, in launch_command
	    process = launch_command(args, out_cb, err_cb, **kwargs)
	  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 274, in launch_command
	    process = Popen(args, **kwargs)
	  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
	    restore_signals, start_new_session)
	  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)
	FileNotFoundError: [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'


	And here are the last few lines of the logfile (see /home/jonny/git/shepd/telepresence.log for the complete logs):

	  19.1  34 | 2018-07-26T06:38:54+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
	  19.1 TEL | [40] exit 255 in 0.01 secs.
	  19.1  35 | Forwarding from 127.0.0.1:37393 -> 8022
	  19.3 TEL | [41] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 37393 telepresence@localhost /bin/true
	  19.3  35 | Handling connection for 37393
	  19.5 TEL | [42] Launching: ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 37393 telepresence@localhost -L127.0.0.1:37479:127.0.0.1:9050 -R9055:127.0.0.1:33075
	  19.5 TEL | END SPAN proxy.py:42(connect)    1.5s
	  19.5 TEL | BEGIN SPAN remote_env.py:46(get_env_variables)
	  19.5 TEL | [43] Capturing: kubectl --context minikube --namespace default exec telepresence-55f67cc7-59a4-451a-9f6b-7db2ffa1bbf8-646656d8v4wpn --container telepresence -- python3 -c 'import json, os; print(json.dumps(dict(os.environ)))'
	  19.5  35 | Handling connection for 37393
	  20.0 TEL | END SPAN remote_env.py:46(get_env_variables)    0.5s
	  20.0 TEL | BEGIN SPAN mount.py:36(mount_remote_volumes)
	  20.0 TEL | [44] Capturing: sshfs -p 37393 -F /dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null telepresence@localhost:/ /tmp/tmputv15z38
	  20.0  35 | Handling connection for 37393
	  20.1 TEL | END SPAN mount.py:36(mount_remote_volumes)    0.2s
	  20.2 TEL | BEGIN SPAN vpn.py:258(connect_sshuttle)
	  20.2 TEL | BEGIN SPAN vpn.py:84(get_proxy_cidrs)
	  20.2 TEL | END SPAN vpn.py:84(get_proxy_cidrs)    0.0s
	  20.2 TEL | [45] Launching: sshuttle-telepresence -v --dns --method nat -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence@localhost:37393 10.96.0.0/12
	  20.2 TEL | [45] [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

	Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]:

Before trying manually I tried `--method container` too, to no avail.

**Comment by jonnyt886** [comment]
Actually, although the I said Telepresence 0.88, the deployment is actually Telepresence 0.90; locally it is 0.88. I'm going to try upgrading my local install to see if that helps...

**Comment by jonnyt886** [comment]
Nope, no dice. Fails with the same error. I did a `find /opt -name sshuttle-telepresence` and found nothing, so I wondered whether this file even exists? I found the code that calls it (`vpn.py:265`) and changed `sshuttle-telepresence` to just `sshuttle` and the error disappeared, though I hit DNS lookup errors which may or not not be caused by my hacking:

    And here are the last few lines of the logfile (see /home/jonny/telepresence.log for the complete
     logs):

      39.3 TEL | [123] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'helloteleprese
    nce82'"'"')'
      39.3 123 | Traceback (most recent call last):
      39.3 123 |   File "<string>", line 1, in <module>
      39.3 123 | socket.gaierror: [Errno -5] No address associated with hostname
      39.3 TEL | [123] exit 1 in 0.06 secs.
      39.4 TEL | [124] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'helloteleprese
    nce83'"'"')'
      39.5 124 | Traceback (most recent call last):
      39.5 124 |   File "<string>", line 1, in <module>
      39.5 124 | socket.gaierror: [Errno -5] No address associated with hostname
      39.5 TEL | [124] exit 1 in 0.07 secs.
      39.6 TEL | [125] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'helloteleprese
    nce84'"'"')'
      39.7 125 | Traceback (most recent call last):
      39.7 125 |   File "<string>", line 1, in <module>
      39.7 125 | socket.gaierror: [Errno -5] No address associated with hostname
      39.7 TEL | [125] exit 1 in 0.07 secs.
      40.8 TEL | [126] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'helloteleprese
    nce85'"'"')'
      40.8 126 | Traceback (most recent call last):
      40.8 126 |   File "<string>", line 1, in <module>
      40.8 126 | socket.gaierror: [Errno -5] No address associated with hostname
      40.9 TEL | [126] exit 1 in 0.06 secs.

**Comment by ark3** [comment]
Sorry about the crashes!

I suspect both of you have installed from an outdated AUR. We're tracking Arch support in #135. In the meantime, I suggest you clone the source tree, check out the tag `0.90`, and [install from source](https://www.telepresence.io/reference/install#install-from-source).

There is [an AUR that installs from master](https://aur.archlinux.org/packages/telepresence-git/) as an alternate option, but you'll get the bleeding edge if you use that.
