### ISSUE TITLE
Cant access environment variables in remote pod

### ISSUE THREAD

**Issue by stanleyawang** [telepresenceio/telepresence#727]
When using telepresence to run as per below : 
telepresence --swap-deployment some-service --run npm run local

Was expecting to be able to get the environmental variable set from the deployment.yml (such as NODE_ENV) in kubernetes
However it is empty.

The operating system I'm using to run telepresence is Ubuntu 18.04, telepresence v 0.90

**Comment by avik-so** [comment]
@stanleyawang  What was the issue?
