### ISSUE TITLE
failure to swap deployment with securityContext set

### ISSUE THREAD

**Issue by rokroskar** [telepresenceio/telepresence#737]
### What were you trying to do?

use telepresence to swap a deployment with the local development version

```
telepresence --swap-deployment <deployment> --namespace <namespace> --method inject-tcp --expose <port>:<port>
```

### What did you expect to happen?

the deployment to be swapped

### What happened instead?

the container in the pod created by telepresence fails to start

The logs in the failed container are:

```
/usr/src/app/run.sh: line 7: can't create /etc/passwd: Permission denied
```

My guess is that this happens because of the `securityContext` set in the deployment:

```yaml
securityContext:
  runAsUser: 1000
```

Does the `securityContext` need to be removed in order to use telepresence?

**Comment by ark3** [comment]
Thanks for filing an issue. At the moment, removing the `securityContext` is a good workaround. This issue is related to #723 in that swap-deployment would be more robust to special security configurations if the container didn't try to write anything at all.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
