### ISSUE TITLE
Swapping CoreDNS deployment causes "RuntimeError: SSH isn't starting" error

### ISSUE THREAD

**Issue by ZachEddy** [telepresenceio/telepresence#740]
### What were you trying to do?

To test some changes that I made locally, I tried swapping my CoreDNS deployment in Minikube with a Telepresence shell using the command below.

```
telepresence --swap-deployment coredns --namespace kube-system --expose=53 --expose=8080 --expose=9153
```

### What did you expect to happen?

I was expecting Telepresence to launch a shell in place of my CoreDNS deployment.

### What happened instead?

The Telepresence pod spins-up without issue, but my Telepresence shell hangs for ~30 seconds before throwing an exception and crashing.

```
NAME                                                            READY     STATUS    RESTARTS   AGE
coredns-c0e2e323-b610-4adb-8d6a-0e1b08d42f0a-55c875496c-lfznh   1/1       Running   0          14s
default-http-backend-59868b7dd6-qc8x7                           1/1       Running   0          4d
etcd-minikube                                                   1/1       Running   0          4d
```

### Steps to Reproduce
1. Run Minikube using `minikube start`
2. Replace KubeDNS with CoreDNS in the `kube-system` namespace by following [these](https://github.com/coredns/deployment/tree/master/kubernetes) steps
3. Comment out or delete the read-only fields in the CoreDNS manifest ([here](https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L106) and [here](https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L124)) and reapply the deployment (otherwise the issue described #723 will cause the pod to crash)
4. Run the `telepresence` command mentioned above
5. The Telepresence shell should crash

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'coredns', '--namespace', 'kube-system', '--expose=53', '--expose=8080', '--expose=9153']`
Version: `0.90`
Python version: `3.6.5 (default, Jun 17 2018, 12:26:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.10.5 // Server Version: v1.10.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/main.py", line 79, in main
    subprocesses, socks_port, ssh = connect(runner, remote_info, args)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/proxy.py", line 122, in connect
    ssh.wait()
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/ssh.py", line 85, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
21 | Handling connection for 53914
  30.0 TEL | [56] exit 255 in 0.54 secs.
  30.3 TEL | [57] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 53914 telepresence@localhost /bin/true
  30.3  21 | Handling connection for 53914
  30.8 TEL | [57] exit 255 in 0.53 secs.
  31.1 TEL | [58] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 53914 telepresence@localhost /bin/true
  31.1  21 | Handling connection for 53914
  31.6 TEL | [58] exit 255 in 0.53 secs.
  31.9 TEL | [59] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 53914 telepresence@localhost /bin/true
  31.9  21 | Handling connection for 53914
  32.4 TEL | [59] exit 255 in 0.53 secs.
  32.7 TEL | [60] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 53914 telepresence@localhost /bin/true
  32.7  21 | Handling connection for 53914
  33.2 TEL | [60] exit 255 in 0.53 secs.

```

**Comment by ark3** [comment]
Nothing in the gist jumped out at me as being the cause of the problem. I will need to follow your steps and replicate this more precisely. Thank you for the detailed instructions. I'll get back to you when I get further along.

**Comment by ark3** [comment]
Sorry I haven't had a chance to chase this down. Some changes I've made elsewhere may help here too. If you have a moment, can you please try the `0.94-36-gf8e3b12` image off of the master branch? It (or a descendant based on feedback) will end up in 0.95.

For example:

    TELEPRESENCE_VERSION=0.94-36-gf8e3b12 telepresence -m inject-tcp --run curl -sk https://kubernetes.default/api

Thank you.
