### ISSUE TITLE
brew install not working on mac

### ISSUE THREAD

**Issue by tomasAlabes** [telepresenceio/telepresence#746]
Hi! I cant install telepresence the way it is recommended on the tutorial (https://www.telepresence.io/reference/install). 

Same as #686

```
$ brew install datawire/blackbird/telepresence
==> Installing telepresence from datawire/blackbird
==> Downloading https://github.com/telepresenceio/telepresence/archive/0.91.tar.gz
==> Downloading from https://codeload.github.com/telepresenceio/telepresence/tar.gz/0.91
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: bd32cd156b9bba85be31ba44daf0f8f831c2cdb50e911b2ed9703714b4cc1de6
Actual: 18adb89229e35429b77a2606bf843fee91eb59db125d7cc2c20a5cffeef7c929
Archive: /Users/talabes/Library/Caches/Homebrew/telepresence--0.91.tar.gz
To retry an incomplete download, remove the file above.
```
(I tried removing the brew cache).

Thanks!

**Comment by ark3** [comment]
This should be fixed now. Can you please try again? You should get version 0.92. Thank you.

**Comment by tomasAlabes** [comment]
Fixed. Thanks!

**Comment by ssleptsov** [comment]
Hey
I'm getting same error, but now for 0.92 version. I have tried delete file and clear brew cache but still error.
Thanks!

`brew install datawire/blackbird/telepresence
==> Installing telepresence from datawire/blackbird
==> Downloading https://github.com/telepresenceio/telepresence/archive/0.92.tar.gz
==> Downloading from https://codeload.github.com/telepresenceio/telepresence/tar.gz/0.92
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c93bfe7e7591aa24b241d13effab6cf0fddbe66e139a75beffb25fa9971cd50b
Actual: 3ad4978333bbf69dc6e2f394054e43925e0025f3ff55b0480b5d5a3b18d9046c
Archive: /Users/cyberss/Library/Caches/Homebrew/telepresence--0.92.tar.gz
To retry an incomplete download, remove the file above.`
