### ISSUE TITLE
Documentation reorganization 

### ISSUE THREAD

**Issue by richarddli** [telepresenceio/telepresence#765]
The Telepresence documentation has grown organically over time, and it really takes a determined user to figure out how to use Telepresence. Reviewing the existing doc structure, I'm thinking the following:

**1. Introduction**

- Intro: Problem Telepresence solves, How it Works, Alternatives
- Getting Started: Installing, Quickstart (simplify from the Docker quickstart)

**2. Developing with Telepresence**

This section should create a mental model for how to use Telepresence. We don't have anything that really covers this area today, and it seems a lot of people stumble in this section. The concepts are generally buried somewhere in the reference material.

* The proxying methods -- when to use one vs another
* The deployment -- this would cover the different ways we use the deployment as a unit of abstraction
* Once we have Teleproxy, we can put the conceptual docs here as well

Currently:

* Debug a K8S service locally is a big swap-deployment tutorial
* Connect to a remote K8S cluster is a telepresence --run tutorial
* Rapid development with K8S covers new-deployment

I think we can refactor all these tutorials into more of a general doc on "deployment".

**3. Tutorials**

This should cover how to use Telepresence in different setups and environments.

* OpenShift
* Minikube
* Golang
* Java/IntelliJ

**4. Reference**
**5. Community**
**6. Help**

**Comment by ark3** [comment]
Development info (how to improve Telepresence) is under Community at the moment as one large page. It is already divided into sections that can be split up into separate pages. And those docs need some work and significant additional information. Eventually, I'll make a separate issue for that.

**Comment by ark3** [comment]
I don't think the user docs should conflate tutorials and how-tos. Tutorials should be about accomplishing something simple with minimal background knowledge assumed. How-tos should focus on getting a (possibly more complex) task done from the perspective of a user who has some knowledge and a specific goal in mind. 

However, in the short run, we don't have time to write _all the things_. What you've described above seems like how-to style stuff, other than the "getting started" bit. 

I think this a good starting point, makes the docs easier to navigate, and leaves clear places to extend and expand things.
