### ISSUE TITLE
Log error message when waiting for "CreateContainerConfigError"

### ISSUE THREAD

**Issue by andrewrothman** [telepresenceio/telepresence#774]
I noticed that Telepresence wouldn't give me much warning when a pod I tried to swap out had a container in the "CreateContainerConfigError" state.

I will be submitting a PR to improve this. Let me know what you think!

Andrew

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
