### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by blackrez** [telepresenceio/telepresence#781]
### What were you trying to do?

Just try to launch.

### What did you expect to happen?

Just works

### What happened instead?

crash

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.92`
Python version: `3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `oc v3.9.0 // kubernetes v1.9.1+cbc5b49 // features: Basic-Auth GSSAPI Kerberos SPNEGO`
OS: `Linux localhost.localdomain 4.17.14-202.fc28.x86_64 #1 SMP Wed Aug 15 12:29:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 43, in main
    runner.kubectl = KubeInfo(runner, args)
  File "/usr/bin/telepresence/telepresence/startup.py", line 135, in __init__
    self.in_local_vm = self._check_if_in_local_vm(runner)
  File "/usr/bin/telepresence/telepresence/startup.py", line 167, in _check_if_in_local_vm
    if ip and ip in runner.kubectl.server:
AttributeError: 'NoneType' object has no attribute 'server'

```

Logs:

```
Not available
```

**Comment by kaerimichi** [comment]
Same here. Happening on macOS as well (version 0.92).
