### ISSUE TITLE
Pod deployment swap failed

### ISSUE THREAD

**Issue by NicolaiSchmid** [telepresenceio/telepresence#784]
### What were you trying to do?
I was trying to swap a deployment

### What did you expect to happen?
My local docker container should have been attached to the pod in kubernetes

### What happened instead?
An error log was printed to the console

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'finance', '--expose', '80:80', '--docker-run', '--rm', '-it', '-v', '/home/xxx/git/xxx/xxx:/app', 'xxx/xxx/xxx.io:development-latest']`
Version: `0.92`
Python version: `3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.9.2 // Server Version: v1.10.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux u48349u8 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 90, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 205, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 136, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2018-09-21T15:16:34Z', 'message': '0/1 nodes are available: 1 node(s) had disk pressure.', 'reason': 'Unschedulable', 'status': 'False', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'BestEffort'}

```

Logs:

```
965f4da300-75f8648fc6-twxn9 -o json
 123.7 TEL | [239] Capturing: kubectl --context minikube --namespace default get pod finance-d666640e3e024233b3d78a965f4da300-75f8648fc6-twxn9 -o json
 124.1 TEL | [240] Capturing: kubectl --context minikube --namespace default get pod finance-d666640e3e024233b3d78a965f4da300-75f8648fc6-twxn9 -o json
 124.5 TEL | [241] Capturing: kubectl --context minikube --namespace default get pod finance-d666640e3e024233b3d78a965f4da300-75f8648fc6-twxn9 -o json
 125.0 TEL | [242] Capturing: kubectl --context minikube --namespace default get pod finance-d666640e3e024233b3d78a965f4da300-75f8648fc6-twxn9 -o json
 125.4 TEL | [243] Capturing: kubectl --context minikube --namespace default get pod finance-d666640e3e024233b3d78a965f4da300-75f8648fc6-twxn9 -o json
 125.8 TEL | [244] Capturing: kubectl --context minikube --namespace default get pod finance-d666640e3e024233b3d78a965f4da300-75f8648fc6-twxn9 -o json
 126.5 TEL | END SPAN remote.py:112(wait_for_pod)  120.5s

```

**Comment by ark3** [comment]
Sorry about the crash. Telepresence should be better about reporting errors. 

The crash message says "0/1 nodes are available: 1 node(s) had disk pressure." Can you try clearing up additional resources on your cluster?

**Comment by NicolaiSchmid** [comment]
The issue has since been resolved at my machine and since it's a minikube and not telepresence issue, there shouldn't be any further intervention necessary from you.
