### ISSUE TITLE
Allow use with restricted sudo access

### ISSUE THREAD

**Issue by stevenjm** [telepresenceio/telepresence#785]
Hi there,

First, background as to what I'm trying to accomplish: I would like to use Telepresence in Docker to connect pods on one Kubernetes cluster (Minikube) to another. Because this container requires `CAP_NET_ADMIN`, I want to run Telepresence as an unprivileged user with sudo rules to allow only the commands necessary to run as root. However, sshuttle always sets `PYTHONPATH` when invoking sudo, which in the case of the PEX distribution with Telepresence is within the invoking user's home directory, so it would be pointless to restrict access with sudo because the user can write any Python code to that location anyway.

I have already fixed the sshuttle issue [upstream](https://github.com/sshuttle/sshuttle/pull/271), but Telepresence uses its own fork of sshuttle which is missing more than a year of upstream development. I can see three possible solutions here:

1. Resolve https://github.com/telepresenceio/telepresence/issues/247 and stop using a forked version of sshuttle.
1. Rebase the sshuttle fork against upstream to pull in all the latest changes. I would be reluctant to do this without first adjusting the Telepresence build process, since `packaging/build-sshuttle.py` just clones the current `telepresence` branch of the sshuttle fork and builds whatever it finds, so updating that repo will cause old versions of Telepresence to suddenly use a much newer version of sshuttle at build time.
1. Backport my fix to sshuttle to the old version used by Telepresence. This shouldn't be too hard (though it is non-trivial since that part of the code has changed in other ways in the past year), but I'm not sure endlessly backporting features is the optimal approach here.

I'm happy to work on option 2 or 3, depending on how the project maintainers want to approach this. I don't think I'm the right person to work on option 1 because I am completely unfamiliar with Telepresence's modifications to sshuttle.

Once this issue is resolved, enabling restricted sudo access is simply a case of passing the `--no-sudo-pythonpath` flag to sshuttle. I'll raise a PR for that when the time comes.

**Comment by ark3** [comment]
Thanks for the issue and for digging into the details. We're working on a new mechanism for outbound connectivity (laptop out to the cluster), so we're not likely to spend a lot of time on sshuttle stuff in the short run. I suggest pursuing option 3 so that you can get up and running. I'm happy to land that on our fork of sshuttle. Thank you!

**Comment by ark3** [comment]
Our new mechanism _still_ hasn't landed, for various reasons, but it's still in the works. Did you make any progress on your sshuttle changes?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
