### ISSUE TITLE
Cluster DNS names unresolvable unless method inject-tcp is selected

### ISSUE THREAD

**Issue by logicbomb421** [telepresenceio/telepresence#786]
Our cluster has a few core services, such as rabbitmq, mongodb, etc.  These are exposed at simple service names corresponding to their full name (e.g.: `rabbitmq`).

When running `--swap-deployment` with no `--method`, `vpn-tcp` is auto-selected, and these services are unreachable via DNS name. 

Here is an example of the full command attempted:
```bash
telepresence --swap-deployment <deployment_name> --run node index.js
```

However, when running with method `inject-tcp`, DNS names are resolvable with no issue:
```bash
telepresence --method inject-tcp --swap-deployment <deployment_name> --run node index.js
```

After reading the [documentation on what gets proxied for each type](https://www.telepresence.io/reference/proxying#the-complete-list-what-telepresence-proxies), I feel both should be proxying the service DNS names, no?

### Environment
macOS: 10.12.6
kubectl (client): v1.10.4
kubernetes: v1.9.7-gke.6
telepresence: 0.90 

Please let me know if more context is needed.

Thanks!

**Comment by ark3** [comment]
Thanks for the issue. Out of curiosity, are these [headless services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services)?

**Comment by edclement** [comment]
same here. service dns addresses only resolve to the proper ip when using `inject-tcp`. Let me know what I can provide to help troubleshoot this issue. Thanks.

**Comment by ark3** [comment]
Can you run a session using the 0.97 release and do a few lookups, including 

    curl -sk https://kubernetes.default/api

and

    curl -sk https://kubernetes.default.svc.cluster.local/api

If you could pass along the log file as a [GitHub Gist](https://gist.github.com/), that would be very helpful. Thank you!

**Comment by abbotteric** [comment]
Hi, I am also seeing this issue when running a node application through telepresence. 

We are running kafka in our cluster and it is exposed with the name `kafka`. When running in `vpn-tcp` mode, the client code is able to resolve the initial connection to kafka at `kafka:9092` but then kafka redirects the client to connect to one of its broker nodes (ours look like `kafka-1.kafka-headless.local`). DNS resolution fails for this request. When running in `inject-tcp` mode, after redirect, the subsequent lookup and then request is successful. 

Unfortunately we aren't able to easily run in `inject-tcp` mode as it does not seem to be compatible with ts-node which is part of our pipeline. 

I also see this same issue when running the kafka command line tools in a `--run-shell` session in `vpn-tcp` mode. The initial DNS resolution works but resolving the redirects fails.

Note, the Kubernetes cluster I'm tunneling into is running locally using docker-for-desktop.

I ran the `curl` commands you asked for in your previous response @ark3. I ran both commands in a `--run-shell` with method `inject-tcp` and then with method `vpn-tcp` all 4 runs gave the same result:

```
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "192.168.65.3:6443"
    }
  ]
}
```

**Environment**
macOS: 10.14.3
kubectl (client): v1.13.4
kubernetes: v1.10.11
telepresence: 0.99

**Comment by alnr** [comment]
`inject-tcp` is compatible with `ts-node`, but caveats apply on macOS: https://www.telepresence.io/reference/methods -> "MacOS System Integrity Protection"
In short: run `node -r ts-node/register foo.ts` or `node node_modules/.bin/ts-node foo.ts` instead of `ts-node foo.ts` or `npm run` or similar.
The `#!/usr/bin/env node` line on top of node scripts (or any other scripts for that matter) cannot be used with `inject-tcp` on macOS. You must specify `node` as the interpreter on the command line explicitly.

To understand the difference, try:
```
$ telepresence -n test -m inject-tcp --run-shell
T: Warning: kubectl 1.14.1 may not work correctly with cluster version 1.11.7 due to the version discrepancy. See
T: https://kubernetes.io/docs/setup/version-skew-policy/ for more information.

T: Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs,
T: and custom DNS implementations are not supported. For a full list of method limitations see
T: https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Deployment test

T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify
T: which ports you want to forward.

T: Setup complete. Launching your command.
@k8s.***.com|bash-3.2$ curl -sk https://kubernetes.default.svc.cluster.local/api
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

@k8s.***.com|bash-3.2$ /usr/bin/env curl -skv https://kubernetes.default.svc.cluster.local/api
* Could not resolve host: kubernetes.default.svc.cluster.local
* Closing connection 0
```

**Comment by aholbreich** [comment]
I would love to be able to access kafka cluster as well 

i'm using:
`telepresence --namespace kafka --also-proxy main-cluster-kafka-0.main-cluster-kafka-brokers.kafka.svc --also-proxy main-cluster-kafka-1.main-cluster-kafka-brokers.kafka.svc --also-proxy main-cluster-kafka-2.main-cluster-kafka-brokers.kafka.svc
`
and it's interestign that dns seem to resolve right ip

ig main-cluster-kafka-0.main-cluster-kafka-brokers.kafka.svc

```
; <<>> DiG 9.11.27-RedHat-9.11.27-1.fc33 <<>> main-cluster-kafka-0.main-cluster-kafka-brokers.kafka.svc
....
;; ANSWER SECTION:
main-cluster-kafka-0.main-cluster-kafka-brokers.kafka.svc. 0 IN	A 10.200.8.54
```

but 

accessting the nodes by that dns name is not working

```
telnet main-cluster-kafka-0.main-cluster-kafka-brokers.kafka.svc 9092
telnet: main-cluster-kafka-0.main-cluster-kafka-brokers.kafka.svc: Name or service not known
main-cluster-kafka-0.main-cluster-kafka-brokers.kafka.svc: Unknown host

```
However it works by ip

```
telnet 10.200.8.54 9092
Trying 10.200.8.54...
Connected to 10.200.8.54.
Escape character is '^]'.
```

so something is missing in the telepresence setup :( any idea?

**Comment by sebaszczen** [comment]
@abbotteric is kafka working for you with inject-tcp? I have te sam probelm as you desribed when using inject-tcp. Thanks.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since telepresence 2 doesn't have methods. We do have one other open ticket on Kafka that we believe has been resolved but it may be worth checking out + adding comments if you have problems using Telepresence 2: https://github.com/telepresenceio/telepresence/issues/1722 Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
