### ISSUE TITLE
Selected context not respected when checking if namespace exists

### ISSUE THREAD

**Issue by rootmos** [telepresenceio/telepresence#787]
During startup when checking if the selected namespace exists, the context is not supplied to the `kubectl get ns` command:
https://github.com/telepresenceio/telepresence/blob/c6a5e56c5d85d06252d01cf150ed43d014ba010e/telepresence/startup.py#L127

That is, it'll use your global context, which not necessarily is the desired context. Reproduce by setting the global context to a cluster without the selected namespace.

I propose the following fix (read: works for me, was broken before): https://github.com/toknapp/telepresence/commit/571a862a275b6f172d812957329b151d30558942

**Comment by kooba** [comment]
This issue still exists. Workflows that supply both `--context` and `--namespace` and don't have `current-context` set in kube/config do not work at the moment and error `T: Error: Namespace 'mynamespace' does not exist` is raised.
