### ISSUE TITLE
Container Mode not working

### ISSUE THREAD

**Issue by callingashley** [telepresenceio/telepresence#796]
Container Mode does not seem to work, while shell works fine...used this command telepresence --docker-run -i -t alpine /bin/sh

396.8 TEL | [41] Capturing: docker run --help
 396.9 TEL | END SPAN container.py:106(run_docker_command)    7.8s
 396.9 TEL | Everything launched. Waiting to exit...
 396.9 TEL | BEGIN SPAN __init__.py:497(wait_for_exit)
 399.6 TEL | Main process (sudo -E docker run --name=telepresence-1538985118-9715738-7019 --network=container:telepresence-1538985111-2748733-7019 -e=TELEPRESENCE_POD -e=TELEPRESENCE_CONTAINER -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP_PORT -e=KUBETESTERSERVICE_PORT_8080_TCP_ADDR -e=QOTM_PORT_5000_TCP -e=KUBERNETES_PORT -e=HTTP1_5788969549_RBV9T_SERVICE_HOST -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP -e=KUBETESTERSERVICE_PORT -e=KUBETESTERSERVICE_PORT_8080_TCP -e=QOTM_PORT -e=QOTM_PORT_5000_TCP_ADDR -e=KUBERNETES_SERVICE_PORT -e=KUBERNETES_SERVICE_PORT_HTTPS -e=KUBERNETES_PORT_443_TCP_PROTO -e=KUBETESTERSERVICE_SERVICE_PORT -e=KUBETESTERSERVICE_SERVICE_PORT_KUBESTERSRV -e=KUBETESTERSERVICE_PORT_8080_TCP_PROTO -e=QOTM_PORT_5000_TCP_PROTO -e=KUBERNETES_PORT_443_TCP_PORT -e=KUBETESTERSERVICE_PORT_8080_TCP_PORT -e=QOTM_PORT_5000_TCP_PORT -e=HTTP1_5788969549_RBV9T_PORT -e=KUBERNETES_SERVICE_HOST -e=HTTP1_5788969549_RBV9T_SERVICE_PORT -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP_ADDR -e=KUBERNETES_PORT_443_TCP -e=KUBETESTERSERVICE_SERVICE_HOST -e=QOTM_SERVICE_HOST -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP_PROTO -e=QOTM_SERVICE_PORT -e=KUBERNETES_PORT_443_TCP_ADDR -e=TELEPRESENCE_ROOT -e=TELEPRESENCE_METHOD --volume=/tmp/tel-7l68lqfk/fs:/tmp/tel-7l68lqfk/fs --init -i -t /adi/88714-gts:kubetester08)
 399.6 TEL |  exited with code 127.
 399.6 TEL | END SPAN __init__.py:497(wait_for_exit)    2.7s
 399.6 TEL | Success. Starting cleanup.
 399.6 >>> | Exit cleanup in progress
 399.6 TEL | (Cleanup) Terminate local container
 399.6 TEL | Shutting down containers...
 399.6 TEL | (Cleanup) Unmount remote filesystem

**Comment by callingashley** [comment]
cann also see 0.8 TEL | Scout info: {'latest_version': '0.92-dirty', 'FAILED': '<urlopen error Tunnel connection failed: 403 Forbidden>'}

**Comment by callingashley** [comment]
Full Logs

[root@master1 ~]# cat fulllogs.log
   0.0 TEL | Telepresence 0.92-dirty launched at Mon Oct  8 11:27:06 2018
   0.0 TEL |   /usr/local/bin/telepresence --docker-run -i -t alpine /bin/sh
   0.0 TEL |   Using images version 0.92 (dev)
   0.0 TEL | Platform: linux
   0.0 TEL | Python 3.6.6 (default, Aug 13 2018, 18:24:23)
   0.0 TEL | [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
   0.0 TEL | [1] Running: uname -a
   0.0   1 | Linux master1.k8s6.cloudlab.****.net 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
   0.0 TEL | BEGIN SPAN main.py:41(main)
   0.0 TEL | BEGIN SPAN startup.py:57(__init__)
   0.0 TEL | [2] Capturing: kubectl version --short
   0.2 TEL | [3] Capturing: kubectl config current-context
   0.4 TEL | [4] Capturing: kubectl config view -o json
   0.5 TEL | Command: kubectl 1.11.2
   0.5 TEL | Context: admin-k8s4, namespace: default, version: 1.11.2
   0.5 TEL | END SPAN startup.py:57(__init__)    0.5s
   0.5 TEL | [5] Capturing: ssh -V
   0.6 TEL | [6] Running: sudo -n echo -n
   0.6 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   0.6 TEL | [7] Capturing: kubectl --context admin-k8s4 --namespace default get pods telepresence-connectivity-check --ignore-not-found
   0.9 TEL | Scout info: {'latest_version': '0.92-dirty', 'FAILED': '<urlopen error Tunnel connection failed: 403 Forbidden>'}
   0.9 TEL | BEGIN SPAN deployment.py:44(create_new_deployment)
   0.9 TEL | [8] Capturing: kubectl --context admin-k8s4 --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=e2349b14e6cc48a0a71a1f79a2996883
   1.2 TEL | [9] Capturing: kubectl --context admin-k8s4 --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1538998026-107106-14974 --image=datawire/telepresence-k8s:0.92 --labels=telepresence=e2349b14e6cc48a0a71a1f79a2996883
   1.4 TEL | END SPAN deployment.py:44(create_new_deployment)    0.5s
   1.4 TEL | BEGIN SPAN remote.py:153(get_remote_info)
   1.4 TEL | BEGIN SPAN remote.py:74(get_deployment_json)
   1.4 TEL | [10] Capturing: kubectl --context admin-k8s4 --namespace default get deployment -o json --export --selector=telepresence=e2349b14e6cc48a0a71a1f79a2996883
   1.6 TEL | END SPAN remote.py:74(get_deployment_json)    0.2s
   1.6 TEL | Searching for Telepresence pod:
   1.6 TEL |   with name telepresence-1538998026-107106-14974-*
   1.6 TEL |   with labels {'telepresence': 'e2349b14e6cc48a0a71a1f79a2996883'}
   1.6 TEL | [11] Capturing: kubectl --context admin-k8s4 --namespace default get pod -o json --export --selector=telepresence=e2349b14e6cc48a0a71a1f79a2996883
   1.8 TEL | Checking telepresence-1538998026-107106-14974-6c64467f94-tv9lr
   1.8 TEL | Looks like we've found our pod!
   1.8 TEL | BEGIN SPAN remote.py:112(wait_for_pod)
   1.8 TEL | [12] Capturing: kubectl --context admin-k8s4 --namespace default get pod telepresence-1538998026-107106-14974-6c64467f94-tv9lr -o json
   2.3 TEL | [13] Capturing: kubectl --context admin-k8s4 --namespace default get pod telepresence-1538998026-107106-14974-6c64467f94-tv9lr -o json
   2.7 TEL | [14] Capturing: kubectl --context admin-k8s4 --namespace default get pod telepresence-1538998026-107106-14974-6c64467f94-tv9lr -o json
   3.0 TEL | END SPAN remote.py:112(wait_for_pod)    1.2s
   3.0 TEL | END SPAN remote.py:153(get_remote_info)    1.6s
   3.0 TEL | BEGIN SPAN __init__.py:38(connect)
   3.0 TEL | [15] Launching kubectl logs: kubectl --context admin-k8s4 --namespace default logs -f telepresence-1538998026-107106-14974-6c64467f94-tv9lr --container telepresence-1538998026-107106-14974
   3.0 TEL | [16] Launching kubectl port-forward: kubectl --context admin-k8s4 --namespace default port-forward telepresence-1538998026-107106-14974-6c64467f94-tv9lr 36150:8022
   3.0 TEL | [17] Capturing: ip addr show dev docker0
   3.0 TEL | [18] Launching socat for docker: socat TCP4-LISTEN:36150,bind=172.17.0.1,reuseaddr,fork TCP4:127.0.0.1:36150
   3.0 TEL | [19] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36150 telepresence@localhost /bin/true
   3.1 TEL | [19] exit 255 in 0.03 secs.
   3.3  16 | Forwarding from 127.0.0.1:36150 -> 8022
   3.3 TEL | [20] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36150 telepresence@localhost /bin/true
   3.3  16 | Handling connection for 36150
   3.8 TEL | Launching Web server for proxy poll
   3.8 TEL | [21] Launching SSH port forward (socks and proxy poll): ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 36150 telepresence@localhost -L127.0.0.1:35973:127.0.0.1:9050 -R9055:127.0.0.1:38234
   3.8 TEL | END SPAN __init__.py:38(connect)    0.9s
   3.8 TEL | BEGIN SPAN remote_env.py:66(get_remote_env)
   3.8 TEL | [22] Capturing: kubectl --context admin-k8s4 --namespace default exec telepresence-1538998026-107106-14974-6c64467f94-tv9lr --container telepresence-1538998026-107106-14974 -- python3 -c 'import json, os; print(json.dumps(dict(os.environ)))'
   3.8  16 | Handling connection for 36150
   5.5 TEL | [22] captured in 1.70 secs.
   5.6 TEL | END SPAN remote_env.py:66(get_remote_env)    1.8s
   5.6 TEL | BEGIN SPAN mount.py:32(mount_remote_volumes)
   5.6 TEL | [23] Capturing: sudo sshfs -p 36150 -F /dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o allow_other telepresence@localhost:/ /tmp/tel-rg9u5mrg/fs
   5.7  16 | Handling connection for 36150
   6.2 TEL | END SPAN mount.py:32(mount_remote_volumes)    0.6s
   6.2 TEL | BEGIN SPAN vpn.py:80(get_proxy_cidrs)
   6.2 TEL | END SPAN vpn.py:80(get_proxy_cidrs)    0.0s
   6.2 TEL | BEGIN SPAN container.py:106(run_docker_command)
   6.2 TEL | [24] Launching Network container: docker run --rm --privileged --name=telepresence-1538998032-343926-14974 datawire/telepresence-local:0.92 proxy '{"port": 36150, "cidrs": ["169.72.128.0/17"], "expose_ports": []}'
   6.2 TEL | [25] Running: docker run --network=container:telepresence-1538998032-343926-14974 --rm datawire/telepresence-local:0.92 wait
   6.5  24 | [INFO  tini (1)] Spawned child process 'python3' with pid '8'
   6.6  25 | [INFO  tini (1)] Spawned child process 'python3' with pid '8'
   6.6  24 |    0.0 TEL | Telepresence 0+unknown launched at Mon Oct  8 11:27:12 2018
   6.6  24 |    0.0 TEL |   /usr/bin/entrypoint.py proxy '{"port": 36150, "cidrs": ["169.72.128.0/17"], "expose_ports": []}'
   6.6  24 |    0.0 TEL | Platform: linux
   6.6  24 |    0.0 TEL | Python 3.6.5 (default, Aug 22 2018, 14:30:18)
   6.6  24 |    0.0 TEL | [GCC 6.3.0]
   6.6  24 |    0.0 TEL | [1] Running: uname -a
   6.6  24 |    0.0   1 | Linux fefed501269b 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 Linux
   6.6  24 |    0.0 TEL | Everything launched. Waiting to exit...
   6.7  24 |    0.0 TEL | BEGIN SPAN __init__.py:497(wait_for_exit)
   6.9  24 | Starting sshuttle proxy.
   7.1  24 | firewall manager: Starting firewall with Python version 3.6.5
   7.1  24 | firewall manager: ready method name nat.
   7.1  24 | IPv6 enabled: False
   7.1  24 | UDP enabled: False
   7.1  24 | DNS enabled: True
   7.1  24 | TCP redirector listening on ('127.0.0.1', 12300).
   7.1  24 | DNS listening on ('127.0.0.1', 12300).
   7.1  24 | Starting client with Python version 3.6.5
   7.1  24 | c : connecting to server...
   7.1  16 | Handling connection for 36150
   7.3  24 | Warning: Permanently added '[172.17.0.1]:36150' (ECDSA) to the list of known hosts.
   8.9  24 | Starting server with Python version 3.6.1
   8.9  24 |  s: latency control setting = True
   9.0  24 | c : Connected.
   9.0  24 | firewall manager: setting up.
   9.0  24 |  s: available routes:
   9.0  24 | >> iptables -t nat -N sshuttle-12300
   9.0  24 | >> iptables -t nat -F sshuttle-12300
   9.0  24 | >> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
   9.0  24 | >> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
   9.0  24 | >> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
   9.0  24 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 169.72.128.0/17 -p tcp --to-ports 12300 -m ttl ! --ttl 42
   9.0  24 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.128.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
   9.1  24 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 224.0.0.252/32 -p udp --dport 5355 --to-ports 12300 -m ttl ! --ttl 42
   9.1  24 | conntrack v1.4.4 (conntrack-tools): 0 flow entries have been deleted.
  10.7  15 | Listening...
  10.7  15 | 2018-10-08T11:27:15+0000 [-] Loading ./forwarder.py...
  10.7  15 | 2018-10-08T11:27:16+0000 [-] /etc/resolv.conf changed, reparsing
  10.7  15 | 2018-10-08T11:27:16+0000 [-] Resolver added ('169.72.128.3', 53) to server list
  10.7  15 | 2018-10-08T11:27:16+0000 [-] SOCKSv5Factory starting on 9050
  10.7  15 | 2018-10-08T11:27:16+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7fce1efdc4a8>
  10.7  15 | 2018-10-08T11:27:16+0000 [-] DNSDatagramProtocol starting on 9053
  10.7  15 | 2018-10-08T11:27:16+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fce1efdc908>
  10.7  15 | 2018-10-08T11:27:16+0000 [-] Loaded.
  10.7  15 | 2018-10-08T11:27:16+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.7.0 (/usr/bin/python3.6 3.6.1) starting up.
  10.7  15 | 2018-10-08T11:27:16+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  11.9  24 | c : DNS request from ('172.17.0.2', 59855) to None: 62 bytes
  11.9  15 | 2018-10-08T11:27:18+0000 [stdout#info] Set DNS suffix we filter out to: [(b'k8s6', b'cloudlab', b'*****', b'net')]
  11.9  15 | 2018-10-08T11:27:18+0000 [stdout#info] Result for b'hellotelepresence.k8s6.cloudlab.****.net' is ['127.0.0.1']
  12.9  25 | [INFO  tini (1)] Main child exited normally (with status '100')
  13.0 TEL | [25] exit 100 in 6.78 secs.
  13.0 TEL | [26] Capturing: docker run --help
  13.0 TEL | END SPAN container.py:106(run_docker_command)    6.8s
  13.0 TEL | Everything launched. Waiting to exit...
  13.0 TEL | BEGIN SPAN __init__.py:497(wait_for_exit)
  13.3 TEL | Main process (docker run --name=telepresence-1538998039-1241634-14974 --network=container:telepresence-1538998032-343926-14974 -e=TELEPRESENCE_POD -e=TELEPRESENCE_CONTAINER -e=KUBETESTERSERVICE_PORT_8080_TCP -e=KUBETESTERSERVICE_PORT_8080_TCP_PROTO -e=KUBETESTERSERVICE_PORT_8080_TCP_PORT -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP_ADDR -e=QOTM_PORT_5000_TCP_ADDR -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP_PROTO -e=KUBETESTERSERVICE_SERVICE_PORT_KUBESTERSRV -e=QOTM_PORT_5000_TCP -e=KUBERNETES_PORT_443_TCP -e=KUBETESTERSERVICE_SERVICE_PORT -e=KUBETESTERSERVICE_PORT -e=KUBETESTERSERVICE_PORT_8080_TCP_ADDR -e=QOTM_PORT_5000_TCP_PORT -e=HTTP1_5788969549_RBV9T_SERVICE_PORT -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP_PORT -e=KUBERNETES_PORT -e=QOTM_PORT_5000_TCP_PROTO -e=HTTP1_5788969549_RBV9T_SERVICE_HOST -e=KUBERNETES_SERVICE_PORT_HTTPS -e=KUBERNETES_PORT_443_TCP_PROTO -e=KUBERNETES_PORT_443_TCP_ADDR -e=KUBETESTERSERVICE_SERVICE_HOST -e=HTTP1_5788969549_RBV9T_PORT -e=HTTP1_5788969549_RBV9T_PORT_8000_TCP -e=KUBERNETES_SERVICE_HOST -e=KUBERNETES_SERVICE_PORT -e=QOTM_SERVICE_HOST -e=KUBERNETES_PORT_443_TCP_PORT -e=QOTM_SERVICE_PORT -e=QOTM_PORT -e=TELEPRESENCE_ROOT -e=TELEPRESENCE_METHOD --volume=/tmp/tel-rg9u5mrg/fs:/tmp/tel-rg9u5mrg/fs --init -i -t alpine /bin/sh)
  13.3 TEL |  exited with code 127.
  13.3 TEL | END SPAN __init__.py:497(wait_for_exit)    0.3s
  13.3 TEL | Success. Starting cleanup.
  13.3 >>> | Exit cleanup in progress
  13.3 TEL | (Cleanup) Terminate local container
  13.3 TEL | Shutting down containers...
  13.3 TEL | (Cleanup) Unmount remote filesystem
  13.4 TEL | [27] Running: sudo fusermount -z -u /tmp/tel-rg9u5mrg/fs
  13.4 TEL | (Cleanup) Delete new deployment
  13.4 TEL | [28] Capturing: kubectl --context admin-k8s4 --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=e2349b14e6cc48a0a71a1f79a2996883
  13.6 TEL | (Cleanup) Kill background items
  13.6 TEL | Killing BackgroundProcess [24] Network container
  13.6 TEL | [29] Running: docker stop --time=1 telepresence-1538998032-343926-14974
  13.6  24 | [INFO  tini (1)] Main child exited with signal (with signal 'Terminated')
  13.7  29 | telepresence-1538998032-343926-14974
  13.7 TEL | Killing BackgroundProcess [21] SSH port forward (socks and proxy poll)
  13.7 TEL | [21] exit 0
  13.7 TEL | Killing BackgroundThread Web server for proxy poll
  13.7 TEL | [24] exit 143
  13.8 TEL | Killing BackgroundProcess [18] socat for docker
  13.8 TEL | [18] exit 143
  13.8 TEL | Killing BackgroundProcess [16] kubectl port-forward
  14.8 TEL | Killing BackgroundProcess [15] kubectl logs
  14.8 TEL | [16] exit -9
  15.9 TEL | Killing BackgroundThread sudo privileges holder
  15.9 TEL | [15] exit -9
  16.7 TEL | (sudo privileges holder thread exiting)
  16.7 TEL | (Cleanup) Stop time tracking
  16.7 TEL | END SPAN main.py:41(main)   16.6s
  16.7 TEL | SPAN SUMMARY:
  16.7 TEL |   16.6s main.py:41(main)
  16.7 TEL |    0.5s   startup.py:57(__init__)
  16.7 TEL |    0.2s     2 kubectl version --short
  16.7 TEL |    0.2s     3 kubectl config current-context
  16.7 TEL |    0.2s     4 kubectl config view -o json
  16.7 TEL |    0.0s   5 ssh -V
  16.7 TEL |    0.0s   6 sudo -n echo -n
  16.7 TEL |    0.2s   7 kubectl --context admin-k8s4 --namespace default get pods telepresence-connect
  16.7 TEL |    0.5s   deployment.py:44(create_new_deployment)
  16.7 TEL |    0.2s     8 kubectl --context admin-k8s4 --namespace default delete --ignore-not-found svc
  16.7 TEL |    0.2s     9 kubectl --context admin-k8s4 --namespace default run --restart=Always --limits
  16.7 TEL |    1.6s   remote.py:153(get_remote_info)
  16.7 TEL |    0.2s     remote.py:74(get_deployment_json)
  16.7 TEL |    0.2s       10 kubectl --context admin-k8s4 --namespace default get deployment -o json --exp
  16.7 TEL |    0.2s     11 kubectl --context admin-k8s4 --namespace default get pod -o json --export --s
  16.7 TEL |    1.2s     remote.py:112(wait_for_pod)
  16.7 TEL |    0.2s       12 kubectl --context admin-k8s4 --namespace default get pod telepresence-1538998
  16.7 TEL |    0.2s       13 kubectl --context admin-k8s4 --namespace default get pod telepresence-1538998
  16.7 TEL |    0.2s       14 kubectl --context admin-k8s4 --namespace default get pod telepresence-1538998
  16.7 TEL |    0.9s   __init__.py:38(connect)
  16.7 TEL |    0.0s     17 ip addr show dev docker0
  16.7 TEL |    0.0s     19 ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null
  16.7 TEL |    0.5s     20 ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null
  16.7 TEL |    1.8s   remote_env.py:66(get_remote_env)
  16.7 TEL |    1.7s     22 kubectl --context admin-k8s4 --namespace default exec telepresence-1538998026
  16.7 TEL |    0.6s   mount.py:32(mount_remote_volumes)
  16.7 TEL |    0.5s     23 sudo sshfs -p 36150 -F /dev/null -o StrictHostKeyChecking=no -o UserKnownHost
  16.7 TEL |    0.0s   vpn.py:80(get_proxy_cidrs)
  16.7 TEL |    6.8s   container.py:106(run_docker_command)
  16.7 TEL |    6.8s     25 docker run --network=container:telepresence-1538998032-343926-14974 --rm data
  16.7 TEL |    0.0s     26 docker run --help
  16.7 TEL |    0.3s   __init__.py:497(wait_for_exit)
  16.7 TEL |    0.0s   27 sudo fusermount -z -u /tmp/tel-rg9u5mrg/fs
  16.7 TEL |    0.2s   28 kubectl --context admin-k8s4 --namespace default delete --ignore-not-found sv
  16.7 TEL |    0.1s   29 docker stop --time=1 telepresence-1538998032-343926-14974
  16.7 TEL | (Cleanup) Remove temporary directory
  16.7 TEL | (Cleanup) Save caches

**Comment by callingashley** [comment]
Yes sudo -E docker run -i -t alpine /bin/sh works fine....the docker version is 1.13.1 on RHEL

**Comment by ark3** [comment]
Is there no output at the command line? I would expect to see something from Docker after "Volumes are rooted ..." and before "Exit cleanup in progress." The output from the main command is not captured into telepresence.log.

Also, I notice you're running a custom version of Telepresence. Does the released version work in your environment?

**Comment by callingashley** [comment]
We are running a custom version (0.92) of telepresence since we have built it for RHEL.

the console logs are below
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Guessing that Services IP range is 169.72.128.0/17. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.
exec -- failed: No such file or directory
T: Exit cleanup in progress
