### ISSUE TITLE
telepresence doesn't automatically reconnect

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#8]
If the connection is lost, telepresence doesn't reconnect, the user needs to restart it completely.

**Comment by itamarst** [comment]
It appears that torsocks starts spinning when a disconnect happens; might need to get fix into upstream torsocks before this is feasible.

**Comment by itamarst** [comment]
Oh, hm, this was blocked due to `torsocks`, but that's not the default now. So maybe with sshuttle as default mode reconnects are possible? We'd need to... restart sshuttle I guess if it dies. Might work!

**Comment by thallgren** [comment]
I believe this was fixed in #1857.
