### ISSUE TITLE
Telepresence python error 

### ISSUE THREAD

**Issue by npatilCTP** [telepresenceio/telepresence#804]
### What were you trying to do?

(please tell us)
Trying to test out telepresence for our project. 
I have python 3.7 installed. Is that causing this issue ? or 
is there a pre-requisite to use a particular Python version ?

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'ihm-rbac-api', '--namespace', 'default', '--expose', '8080', '--docker-run', '-e', 'JAVA_OPTS=-Xms500m -Xmx762m -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n', '-p', '8080:8080', '-p', '5005:5005', 'ihm-rbac-api:1539377902']`
Version: `0.93`
Python version: `3.7.0 (default, Aug 24 2018, 10:00:32) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.9.9`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin NIRPAT 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/__init__.py", line 88, in launch
    args.also_proxy, env, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 125, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/local/bin/telepresence/telepresence/runner/__init__.py", line 337, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/local/bin/telepresence/telepresence/runner/__init__.py", line 326, in _run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1539377969-067708-99176', '--rm', 'datawire/telepresence-local:0.93', 'wait']' returned non-zero exit status 1.

```

Logs:

```
 | [61] Running: docker run --network=container:telepresence-1539377969-067708-99176 --rm datawire/telepresence-local:0.93 wait
  34.9  59 | Starting sshuttle proxy.
  35.1  59 | firewall manager: Starting firewall with Python version 3.6.5
  35.1  59 | firewall manager: ready method name nat.
  35.1  59 | IPv6 enabled: False
  35.1  59 | UDP enabled: False
  35.1  59 | DNS enabled: True
  35.1  59 | TCP redirector listening on ('127.0.0.1', 12300).
  35.1  59 | DNS listening on ('127.0.0.1', 12300).
  35.1  59 | Starting client with Python version 3.6.5
  35.1  59 | c : connecting to server...
  35.3  61 | [INFO  tini (1)] Spawned child process 'python3' with pid '8'
  60.1 TEL | (proxy checking local liveness)
  60.1  47 | 2018-10-12T20:59:55+0000 [Poll#info] Checkpoint
  61.8 TEL | [62] Running: sudo -n echo -n
  65.5  61 | Failed to connect to proxy in remote cluster.
  65.5  61 | [INFO  tini (1)] Main child exited normally (with status '1')
  65.9 TEL | [61] exit 1 in 31.11 secs.

```

**Comment by LukeShu** [comment]
My Python is 3.7.1, and telepresence works for me, so that's not the issue (at least by itself).

**Comment by ark3** [comment]
It looks like the network container didn't finish connecting to the server. Can you pass along the entire log file as a [Gist](https://gist.github.com/)? Thank you.
