### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by x1mroepke** [telepresenceio/telepresence#807]
### What were you trying to do?

telepresence --verbose --namespace $NS --swap-deployment $DEPLOYMENT --docker-run --rm -it -v $(pwd)/app/src:/app/src brokerme:$DEPLOYMENT

### What did you expect to happen?

no exception

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--verbose', '--namespace', 'staging', '--swap-deployment', 'staging', '--docker-run', '--rm', '-it', '-v', '/home/michael/dersalvador/BrokerMeApp/app/src:/app/src', 'brokerme:staging']`
Version: `0.93`
Python version: `3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]`
kubectl version: `Client Version: v1.12.1 // Server Version: v1.10.6-gke.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux michael-VirtualBox 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 84, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 127, in supplant_deployment
    "deployment",
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 86, in get_deployment_json
    stderr=STDOUT
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
ation-log",
   2.2   9 |                         "terminationMessagePolicy": "File"
   2.2   9 |                     }
   2.2   9 |                 ],
   2.2   9 |                 "restartPolicy": "Always",
   2.2   9 |                 "schedulerName": "default-scheduler",
   2.2   9 |                 "securityContext": {},
   2.2   9 |                 "terminationGracePeriodSeconds": 30,
   2.2   9 |                 "volumes": [
   2.2   9 |                     {
   2.2   9 |                         "name": "cvs-env-svc-acc-vol",
   2.2   9 |                         "secret": {
   2.2   9 |                             "defaultMode": 256,
   2.2   9 |                             "secretName": "staging-cvs"
   2.2   9 |                         }
   2.2   9 |                     }
   2.2   9 |                 ]
   2.2   9 |             }
   2.2   9 |         }
   2.2   9 |     },
   2.2   9 |     "status": {}
   2.2   9 | }
   2.2 TEL | END SPAN remote.py:73(get_deployment_json)    0.3s

```

**Comment by ark3** [comment]
Sorry about the crash! Does this happen if you leave off `--verbose` from your command line? Thanks for your help.

**Comment by sjentzsch** [comment]
I can reproduce. Same cluster than my collegue @x1mroepke, but telepresence executed from another machine. @ark3: Not related to `--verbose`.

We have the suspicion it could be related to what's inside our cluster, which is a deployed kubed from appscode, as it yields an error in the `telepresence.log`:
`I1014 23:58:37.477340    7080 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request`

Let me share my trace too:

### Automatically included information

Command line: `['/usr/bin/telepresence', '--verbose', '--namespace', 'staging', '--swap-deployment', 'staging', '--docker-run', '--rm', '-it', '-v', '/home/sjentzsch/brokerme/BrokerMeApp/app/src:/app/src', 'brokerme:master']`
Version: `0.93`
Python version: `3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]`
kubectl version: `Client Version: v1.12.1 // Server Version: v1.10.6-gke.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux sjentzsch-VirtualBox 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 84, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 127, in supplant_deployment
    "deployment",
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 86, in get_deployment_json
    stderr=STDOUT
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
ation-log",
   7.3  10 |                         "terminationMessagePolicy": "File"
   7.3  10 |                     }
   7.3  10 |                 ],
   7.3  10 |                 "restartPolicy": "Always",
   7.3  10 |                 "schedulerName": "default-scheduler",
   7.3  10 |                 "securityContext": {},
   7.3  10 |                 "terminationGracePeriodSeconds": 30,
   7.3  10 |                 "volumes": [
   7.3  10 |                     {
   7.3  10 |                         "name": "cvs-env-svc-acc-vol",
   7.3  10 |                         "secret": {
   7.3  10 |                             "defaultMode": 256,
   7.3  10 |                             "secretName": "staging-cvs"
   7.3  10 |                         }
   7.3  10 |                     }
   7.3  10 |                 ]
   7.3  10 |             }
   7.3  10 |         }
   7.3  10 |     },
   7.3  10 |     "status": {}
   7.3  10 | }
   7.4 TEL | END SPAN remote.py:73(get_deployment_json)    1.4s

```

**Comment by ark3** [comment]
The result of the `kubectl get deployment` command is dumped into telepresence.log when running in verbose mode, as you are. You can see the end of that output in the crash reporter's snippet. Is the non-JSON stuff you identified present in your telepresence.log prior to the JSON?

**Comment by x1mroepke** [comment]
Here it is:

`   2.9 TEL | BEGIN SPAN deployment.py:120(supplant_deployment)
   2.9 TEL | BEGIN SPAN remote.py:73(get_deployment_json)
   2.9 TEL | [9] Capturing: kubectl --v=4 --context gke_plucky-door-200208_europe-west1-b_brokerme --namespace staging get deployment -o json --export staging
   2.9   9 | I1015 10:09:13.890803   20991 cached_discovery.go:77] skipped caching discovery info due to the server is currently unable to handle the request
   2.9   9 | I1015 10:09:13.893904   20991 cached_discovery.go:77] skipped caching discovery info due to the server is currently unable to handle the request
   2.9   9 | I1015 10:09:13.894197   20991 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
   3.0   9 | I1015 10:09:13.895436   20991 cached_discovery.go:77] skipped caching discovery info due to the server is currently unable to handle the request
   3.1   9 | {
   3.1   9 |     "apiVersion": "extensions/v1beta1",
   3.1   9 |     "kind": "Deployment",
   3.1   9 |     "metadata": {
   3.1   9 |         "annotations": {
   3.1   9 |             "deployment.kubernetes.io/revision": "2"
   3.1   9 |         },
   3.1   9 |         "creationTimestamp": null,
   3.1   9 |         "generation": 1,
   3.1   9 |         "labels": {
   3.1   9 |             "app": "staging",
   3.1   9 |             "chart": "brokerme-app-0.1.0",
   3.1   9 |             "heritage": "Tiller",
   3.1   9 |             "release": "staging",
   3.1   9 |             "tier": "web",
   3.1   9 |             "track": "stable"
   3.1   9 |         },
   3.1   9 |         "name": "staging",
   3.1   9 |         "selfLink": "/apis/extensions/v1beta1/namespaces/staging/deployments/staging"
   3.1   9 |     },
   3.1   9 |     "spec": {
   3.1   9 |         "progressDeadlineSeconds": 600,
   3.1   9 |         "replicas": 1,
   3.1   9 |         "revisionHistoryLimit": 10,
   3.1   9 |         "selector": {
   3.1   9 |             "matchLabels": {
   3.1   9 |                 "app": "staging"
   3.1   9 |             }
   3.1   9 |         },
   3.1   9 |         "strategy": {
   3.1   9 |             "rollingUpdate": {
   3.1   9 |                 "maxSurge": "25%",
   3.1   9 |                 "maxUnavailable": "25%"
   3.1   9 |             },
   3.1   9 |             "type": "RollingUpdate"
   3.1   9 |         },
   3.1   9 |         "template": {
   3.1   9 |             "metadata": {
   3.1   9 |                 "creationTimestamp": null,
   3.1   9 |                 "labels": {
   3.1   9 |                     "app": "staging",
   3.1   9 |                     "release": "staging",
   3.1   9 |                     "tier": "web",
   3.1   9 |                     "track": "stable"
   3.1   9 |                 }
   3.1   9 |             },
   3.1   9 |             "spec": {
   3.1   9 |                 "containers": [
   3.1   9 |                     {
   3.1   9 |                         "envFrom": [
   3.1   9 |                             {
   3.1   9 |                                 "configMapRef": {
   3.1   9 |                                     "name": "staging-base"
   3.1   9 |                                 }
   3.1   9 |                             }
   3.1   9 |                         ],
   3.1   9 |                         "image": "registry.filekeys.com/brokerme/brokermeapp/master:fb0cefa8d6def42c3c69e9ca3f0e677b1ab2df35",
   3.1   9 |                         "imagePullPolicy": "IfNotPresent",
   3.1   9 |                         "livenessProbe": {
   3.1   9 |                             "failureThreshold": 3,
   3.1   9 |                             "httpGet": {
   3.1   9 |                                 "path": "/",
   3.1   9 |                                 "port": 3000,
   3.1   9 |                                 "scheme": "HTTP"
   3.1   9 |                             },
   3.1   9 |                             "initialDelaySeconds": 15,
   3.1   9 |                             "periodSeconds": 10,
   3.1   9 |                             "successThreshold": 1,
   3.1   9 |                             "timeoutSeconds": 15
   3.1   9 |                         },
   3.1   9 |                         "name": "brokerme-app",
   3.1   9 |                         "ports": [
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 3434,
   3.1   9 |                                 "name": "dashboard",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 3000,
   3.1   9 |                                 "name": "landingpage",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4000,
   3.1   9 |                                 "name": "api",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 5656,
   3.1   9 |                                 "name": "queuing",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4300,
   3.1   9 |                                 "name": "robot",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4200,
   3.1   9 |                                 "name": "mailer",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4500,
   3.1   9 |                                 "name": "pdfbrander",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 9229,
   3.1   9 |                                 "name": "nodedebug",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             }
   3.1   9 |                         ],
   3.1   9 |                         "readinessProbe": {
   3.1   9 |                             "failureThreshold": 3,
   3.1   9 |                             "httpGet": {
   3.1   9 |                                 "path": "/",
   3.1   9 |                                 "port": 3000,
   3.1   9 |                                 "scheme": "HTTP"
   3.1   9 |                             },
   3.1   9 |                             "initialDelaySeconds": 5,
   3.1   9 |                             "periodSeconds": 10,
   3.1   9 |                             "successThreshold": 1,
   3.1   9 |                             "timeoutSeconds": 3
   3.1   9 |                         },
   3.1   9 |                         "resources": {},
   3.1   9 |                         "terminationMessagePath": "/dev/termination-log",
   3.1   9 |                         "terminationMessagePolicy": "File",
   3.1   9 |                         "volumeMounts": [
   3.1   9 |                             {
   3.1   9 |                                 "mountPath": "/var/secrets/cvs",
   3.1   9 |                                 "name": "cvs-env-svc-acc-vol",
   3.1   9 |                                 "readOnly": true
   3.1   9 |                             }
   3.1   9 |                         ]
   3.1   9 |                     }
   3.1   9 |                 ],
   3.1   9 |                 "dnsPolicy": "ClusterFirst",
   3.1   9 |                 "imagePullSecrets": [
   3.1   9 |                     {
   3.1   9 |                         "name": "gitlab-registry"
   3.1   9 |                     }
   3.1   9 |                 ],
   3.1   9 |                 "initContainers": [
   3.1   9 |                     {
   3.1   9 |                         "command": [
   3.1   9 |                             "sh",
   3.1   9 |                             "-c",
   3.1   9 |                             "while mongostat --uri=mongodb://${MONGODB_REPLICA_LAST}/${MONGODB_APPLICATION_DATABASE}?replicaSet=${MONGODB_REPLICASET} -o uptime,repl.primary -n 1 --noheaders | grep INVALID; do :; done;"
   3.1   9 |                         ],
   3.1   9 |                         "envFrom": [
   3.1   9 |                             {
   3.1   9 |                                 "configMapRef": {
   3.1   9 |                                     "name": "staging-base"
   3.1   9 |                                 }
   3.1   9 |                             }
   3.1   9 |                         ],
   3.1   9 |                         "image": "registry.filekeys.com/brokerme/mongohelper:latest",
   3.1   9 |                         "imagePullPolicy": "Always",
   3.1   9 |                         "name": "mongohelper",
   3.1   9 |                         "resources": {},
   3.1   9 |                         "terminationMessagePath": "/dev/termination-log",
   3.1   9 |                         "terminationMessagePolicy": "File"
   3.1   9 |                     }
   3.1   9 |                 ],
   3.1   9 |                 "restartPolicy": "Always",
   3.1   9 |                 "schedulerName": "default-scheduler",
   3.1   9 |                 "securityContext": {},
   3.1   9 |                 "terminationGracePeriodSeconds": 30,
   3.1   9 |                 "volumes": [
   3.1   9 |                     {
   3.1   9 |                         "name": "cvs-env-svc-acc-vol",
   3.1   9 |                         "secret": {
   3.1   9 |                             "defaultMode": 256,
   3.1   9 |                             "secretName": "staging-cvs"
   3.1   9 |                         }
   3.1   9 |                     }
   3.1   9 |                 ]
   3.1   9 |             }
   3.1   9 |         }
   3.1   9 |     },
   3.1   9 |     "status": {}
   3.1   9 | }
   3.2 TEL | END SPAN remote.py:73(get_deployment_json)    0.3s
   3.2 TEL | CRASH: Expecting value: line 1 column 1 (char 0)
   3.2 TEL | Traceback (most recent call last):
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
   3.2 TEL |     yield
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
   3.2 TEL |     remote_info = start_proxy(runner)
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 84, in start_proxy
   3.2 TEL |     runner_, deployment_arg, image_name, args.expose, add_custom_ns
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 127, in supplant_deployment
   3.2 TEL |     "deployment",
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 86, in get_deployment_json
   3.2 TEL |     stderr=STDOUT
   3.2 TEL |   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
   3.2 TEL |     return _default_decoder.decode(s)
   3.2 TEL |   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
   3.2 TEL |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   3.2 TEL |   File "/usr/lib/python3.6/json/decoder.py", line 362, in raw_decode
   3.2 TEL |     raise JSONDecodeError("Expecting value", s, err.value) from None
   3.2 TEL | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   3.2 TEL | (calling crash reporter...)
  31.2 TEL | [10] Running: sudo -n echo -n
  61.3 TEL | [11] Running: sudo -n echo -n
  91.3 TEL | [12] Running: sudo -n echo -n
 121.4 TEL | [13] Running: sudo -n echo -n
 151.5 TEL | [14] Running: sudo -n echo -n
 181.5 TEL | [15] Running: sudo -n echo -n
 211.6 TEL | [16] Running: sudo -n echo -n
 241.6 TEL | [17] Running: sudo -n echo -n
 271.7 TEL | [18] Running: sudo -n echo -n
 301.7 TEL | [19] Running: sudo -n echo -n
 331.8 TEL | [20] Running: sudo -n echo -n
 361.8 TEL | [21] Running: sudo -n echo -n
 391.8 TEL | [22] Running: sudo -n echo -n
 421.9 TEL | [23] Running: sudo -n echo -n
 452.0 TEL | [24] Running: sudo -n echo -n
 482.1 TEL | [25] Running: sudo -n echo -n
 512.1 TEL | [26] Running: sudo -n echo -n
 518.9 >>> | Exit cleanup in progress
 518.9 TEL | (Cleanup) Kill background items
 518.9 TEL | Killing BackgroundThread sudo privileges holder
 519.2 TEL | (sudo privileges holder thread exiting)
 519.2 TEL | (Cleanup) Stop time tracking
 519.2 TEL | END SPAN main.py:41(main)  519.1s
 519.2 TEL | (Cleanup) Remove temporary directory
 519.2 TEL | (Cleanup) Save caches
michael@michael-VirtualBox ~/dersalvador/BrokerMeApp (michael_dev)-local-dev
$ 
`

**Comment by x1mroepke** [comment]
>    2.9 TEL | BEGIN SPAN deployment.py:120(supplant_deployment)
   2.9 TEL | BEGIN SPAN remote.py:73(get_deployment_json)
   2.9 TEL | [9] Capturing: kubectl --v=4 --context gke_plucky-door-200208_europe-west1-b_brokerme --namespace staging get deployment -o json --export staging
   2.9   9 | I1015 10:09:13.890803   20991 cached_discovery.go:77] skipped caching discovery info due to the server is currently unable to handle the request
   2.9   9 | I1015 10:09:13.893904   20991 cached_discovery.go:77] skipped caching discovery info due to the server is currently unable to handle the request
   2.9   9 | I1015 10:09:13.894197   20991 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
   3.0   9 | I1015 10:09:13.895436   20991 cached_discovery.go:77] skipped caching discovery info due to the server is currently unable to handle the request
   3.1   9 | {
   3.1   9 |     "apiVersion": "extensions/v1beta1",
   3.1   9 |     "kind": "Deployment",
   3.1   9 |     "metadata": {
   3.1   9 |         "annotations": {
   3.1   9 |             "deployment.kubernetes.io/revision": "2"
   3.1   9 |         },
   3.1   9 |         "creationTimestamp": null,
   3.1   9 |         "generation": 1,
   3.1   9 |         "labels": {
   3.1   9 |             "app": "staging",
   3.1   9 |             "chart": "brokerme-app-0.1.0",
   3.1   9 |             "heritage": "Tiller",
   3.1   9 |             "release": "staging",
   3.1   9 |             "tier": "web",
   3.1   9 |             "track": "stable"
   3.1   9 |         },
   3.1   9 |         "name": "staging",
   3.1   9 |         "selfLink": "/apis/extensions/v1beta1/namespaces/staging/deployments/staging"
   3.1   9 |     },
   3.1   9 |     "spec": {
   3.1   9 |         "progressDeadlineSeconds": 600,
   3.1   9 |         "replicas": 1,
   3.1   9 |         "revisionHistoryLimit": 10,
   3.1   9 |         "selector": {
   3.1   9 |             "matchLabels": {
   3.1   9 |                 "app": "staging"
   3.1   9 |             }
   3.1   9 |         },
   3.1   9 |         "strategy": {
   3.1   9 |             "rollingUpdate": {
   3.1   9 |                 "maxSurge": "25%",
   3.1   9 |                 "maxUnavailable": "25%"
   3.1   9 |             },
   3.1   9 |             "type": "RollingUpdate"
   3.1   9 |         },
   3.1   9 |         "template": {
   3.1   9 |             "metadata": {
   3.1   9 |                 "creationTimestamp": null,
   3.1   9 |                 "labels": {
   3.1   9 |                     "app": "staging",
   3.1   9 |                     "release": "staging",
   3.1   9 |                     "tier": "web",
   3.1   9 |                     "track": "stable"
   3.1   9 |                 }
   3.1   9 |             },
   3.1   9 |             "spec": {
   3.1   9 |                 "containers": [
   3.1   9 |                     {
   3.1   9 |                         "envFrom": [
   3.1   9 |                             {
   3.1   9 |                                 "configMapRef": {
   3.1   9 |                                     "name": "staging-base"
   3.1   9 |                                 }
   3.1   9 |                             }
   3.1   9 |                         ],
   3.1   9 |                         "image": "registry.filekeys.com/brokerme/brokermeapp/master:fb0cefa8d6def42c3c69e9ca3f0e677b1ab2df35",
   3.1   9 |                         "imagePullPolicy": "IfNotPresent",
   3.1   9 |                         "livenessProbe": {
   3.1   9 |                             "failureThreshold": 3,
   3.1   9 |                             "httpGet": {
   3.1   9 |                                 "path": "/",
   3.1   9 |                                 "port": 3000,
   3.1   9 |                                 "scheme": "HTTP"
   3.1   9 |                             },
   3.1   9 |                             "initialDelaySeconds": 15,
   3.1   9 |                             "periodSeconds": 10,
   3.1   9 |                             "successThreshold": 1,
   3.1   9 |                             "timeoutSeconds": 15
   3.1   9 |                         },
   3.1   9 |                         "name": "brokerme-app",
   3.1   9 |                         "ports": [
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 3434,
   3.1   9 |                                 "name": "dashboard",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 3000,
   3.1   9 |                                 "name": "landingpage",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4000,
   3.1   9 |                                 "name": "api",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 5656,
   3.1   9 |                                 "name": "queuing",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4300,
   3.1   9 |                                 "name": "robot",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4200,
   3.1   9 |                                 "name": "mailer",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 4500,
   3.1   9 |                                 "name": "pdfbrander",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             },
   3.1   9 |                             {
   3.1   9 |                                 "containerPort": 9229,
   3.1   9 |                                 "name": "nodedebug",
   3.1   9 |                                 "protocol": "TCP"
   3.1   9 |                             }
   3.1   9 |                         ],
   3.1   9 |                         "readinessProbe": {
   3.1   9 |                             "failureThreshold": 3,
   3.1   9 |                             "httpGet": {
   3.1   9 |                                 "path": "/",
   3.1   9 |                                 "port": 3000,
   3.1   9 |                                 "scheme": "HTTP"
   3.1   9 |                             },
   3.1   9 |                             "initialDelaySeconds": 5,
   3.1   9 |                             "periodSeconds": 10,
   3.1   9 |                             "successThreshold": 1,
   3.1   9 |                             "timeoutSeconds": 3
   3.1   9 |                         },
   3.1   9 |                         "resources": {},
   3.1   9 |                         "terminationMessagePath": "/dev/termination-log",
   3.1   9 |                         "terminationMessagePolicy": "File",
   3.1   9 |                         "volumeMounts": [
   3.1   9 |                             {
   3.1   9 |                                 "mountPath": "/var/secrets/cvs",
   3.1   9 |                                 "name": "cvs-env-svc-acc-vol",
   3.1   9 |                                 "readOnly": true
   3.1   9 |                             }
   3.1   9 |                         ]
   3.1   9 |                     }
   3.1   9 |                 ],
   3.1   9 |                 "dnsPolicy": "ClusterFirst",
   3.1   9 |                 "imagePullSecrets": [
   3.1   9 |                     {
   3.1   9 |                         "name": "gitlab-registry"
   3.1   9 |                     }
   3.1   9 |                 ],
   3.1   9 |                 "initContainers": [
   3.1   9 |                     {
   3.1   9 |                         "command": [
   3.1   9 |                             "sh",
   3.1   9 |                             "-c",
   3.1   9 |                             "while mongostat --uri=mongodb://${MONGODB_REPLICA_LAST}/${MONGODB_APPLICATION_DATABASE}?replicaSet=${MONGODB_REPLICASET} -o uptime,repl.primary -n 1 --noheaders | grep INVALID; do :; done;"
   3.1   9 |                         ],
   3.1   9 |                         "envFrom": [
   3.1   9 |                             {
   3.1   9 |                                 "configMapRef": {
   3.1   9 |                                     "name": "staging-base"
   3.1   9 |                                 }
   3.1   9 |                             }
   3.1   9 |                         ],
   3.1   9 |                         "image": "registry.filekeys.com/brokerme/mongohelper:latest",
   3.1   9 |                         "imagePullPolicy": "Always",
   3.1   9 |                         "name": "mongohelper",
   3.1   9 |                         "resources": {},
   3.1   9 |                         "terminationMessagePath": "/dev/termination-log",
   3.1   9 |                         "terminationMessagePolicy": "File"
   3.1   9 |                     }
   3.1   9 |                 ],
   3.1   9 |                 "restartPolicy": "Always",
   3.1   9 |                 "schedulerName": "default-scheduler",
   3.1   9 |                 "securityContext": {},
   3.1   9 |                 "terminationGracePeriodSeconds": 30,
   3.1   9 |                 "volumes": [
   3.1   9 |                     {
   3.1   9 |                         "name": "cvs-env-svc-acc-vol",
   3.1   9 |                         "secret": {
   3.1   9 |                             "defaultMode": 256,
   3.1   9 |                             "secretName": "staging-cvs"
   3.1   9 |                         }
   3.1   9 |                     }
   3.1   9 |                 ]
   3.1   9 |             }
   3.1   9 |         }
   3.1   9 |     },
   3.1   9 |     "status": {}
   3.1   9 | }
   3.2 TEL | END SPAN remote.py:73(get_deployment_json)    0.3s
   3.2 TEL | CRASH: Expecting value: line 1 column 1 (char 0)
   3.2 TEL | Traceback (most recent call last):
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
   3.2 TEL |     yield
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
   3.2 TEL |     remote_info = start_proxy(runner)
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 84, in start_proxy
   3.2 TEL |     runner_, deployment_arg, image_name, args.expose, add_custom_ns
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 127, in supplant_deployment
   3.2 TEL |     "deployment",
   3.2 TEL |   File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 86, in get_deployment_json
   3.2 TEL |     stderr=STDOUT
   3.2 TEL |   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
   3.2 TEL |     return _default_decoder.decode(s)
   3.2 TEL |   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
   3.2 TEL |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   3.2 TEL |   File "/usr/lib/python3.6/json/decoder.py", line 362, in raw_decode
   3.2 TEL |     raise JSONDecodeError("Expecting value", s, err.value) from None
   3.2 TEL | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   3.2 TEL | (calling crash reporter...)
  31.2 TEL | [10] Running: sudo -n echo -n
  61.3 TEL | [11] Running: sudo -n echo -n
  91.3 TEL | [12] Running: sudo -n echo -n
 121.4 TEL | [13] Running: sudo -n echo -n
 151.5 TEL | [14] Running: sudo -n echo -n
 181.5 TEL | [15] Running: sudo -n echo -n
 211.6 TEL | [16] Running: sudo -n echo -n
 241.6 TEL | [17] Running: sudo -n echo -n
 271.7 TEL | [18] Running: sudo -n echo -n
 301.7 TEL | [19] Running: sudo -n echo -n
 331.8 TEL | [20] Running: sudo -n echo -n
 361.8 TEL | [21] Running: sudo -n echo -n
 391.8 TEL | [22] Running: sudo -n echo -n
 421.9 TEL | [23] Running: sudo -n echo -n
 452.0 TEL | [24] Running: sudo -n echo -n
 482.1 TEL | [25] Running: sudo -n echo -n
 512.1 TEL | [26] Running: sudo -n echo -n
 518.9 >>> | Exit cleanup in progress
 518.9 TEL | (Cleanup) Kill background items
 518.9 TEL | Killing BackgroundThread sudo privileges holder
 519.2 TEL | (sudo privileges holder thread exiting)
 519.2 TEL | (Cleanup) Stop time tracking
 519.2 TEL | END SPAN main.py:41(main)  519.1s
 519.2 TEL | (Cleanup) Remove temporary directory
 519.2 TEL | (Cleanup) Save caches
michael@michael-VirtualBox ~/dersalvador/BrokerMeApp (michael_dev)-local-dev
$

**Comment by ark3** [comment]
Good find! However, the `--v=4` is added by the `--verbose` option to Telepresence. I would expect things to work fine without `--verbose`. Could you try that again, please?

Of course, I don't want `--verbose` to be broken for you. On the other hand, `--v=4` has helped us find and fix bugs in the past. Perhaps we need _yet another option_ or a configuration file or ...

**Comment by sjentzsch** [comment]
Good find, too! You are right. Leaving out `verbose` works now (for me).

Sorry for mentioning previously `verbose` would not be related to it. I though I would have executed it without `verbose`, though my logs clearly spoke the contrary.
