### ISSUE TITLE
Error in Get started with OpenShift

### ISSUE THREAD

**Issue by thorwolpert** [telepresenceio/telepresence#808]
### What were you trying to do?

Follow the *Get started with OpenShift* documentation

### What did you expect to happen?

The intro tutorial to work

### What happened instead?
Ran these commands:
oc new-app --docker-image=datawire/hello-world --name=hello-world
oc expose service hello-world
telepresence --swap-deployment hello-world --expose 8000 \
--run python3 -m http.server 8000 &

which produced the trace below.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'hello-world', '--expose', '8000', '--run', 'python3', '-m', 'http.server', '8000']`
Version: `0.93`
Python version: `3.6.5 (default, Jun 17 2018, 12:13:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.10.3 // Server Version: v1.10.0+b81c8f8`
oc version: `oc v3.10.0+dd10d17 // kubernetes v1.10.0+b81c8f8 // features: Basic-Auth //  // Server https://console.pathfinder.gov.bc.ca:8443 // openshift v3.10.34 // kubernetes v1.10.0+b81c8f8`
OS: `Darwin mjolnir.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 43, in main
    runner.kubectl = KubeInfo(runner, args)
  File "/usr/local/bin/telepresence/telepresence/startup.py", line 153, in __init__
    self.in_local_vm = self._check_if_in_local_vm(runner)
  File "/usr/local/bin/telepresence/telepresence/startup.py", line 185, in _check_if_in_local_vm
    if ip and ip in runner.kubectl.server:
AttributeError: 'NoneType' object has no attribute 'server'

```

Logs:

```
Not available
```

**Comment by tellisnz** [comment]
Dupe of #781?

**Comment by thorwolpert** [comment]
It looks like the same issue. - closing
