### ISSUE TITLE
Swapping service does not work on Mac OS

### ISSUE THREAD

**Issue by astefanutti** [telepresenceio/telepresence#809]
### What were you trying to do?

Use Telepresence with a Go program, to run a Kubernetes service locally on Mac OS. I've been following the _Kubernetes talks to a Go program_ section of the documentation. 

### What did you expect to happen?

The local service is deployed with Telepresence and requests are forwarded to it. 

### What happened instead?

The error above happens. It seems `socat` is not found, while it's been installed as per the documentation using brew. 

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'vpn-tcp', '--swap-deployment', 'custom-metrics-apiserver', '--namespace', 'custom-metrics', '--expose', '8080:80', '--run', '_output/amd64/test-adapter']`
Version: `0.93`
Python version: `3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]`
kubectl version: `Client Version: v1.10.1 // Server Version: v1.11.0-alpha.0.8844+90f82d3a450a35`
oc version: `oc v3.10.0+dd10d17 // kubernetes v1.10.0+b81c8f8 // features: Basic-Auth //  // Server https://10.1.2.3:6443/ // kubernetes v1.11.0-alpha.0.8844+90f82d3a450a35`
OS: `Darwin mbp 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 64, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 158, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 115, in connect
    ssh.wait()
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 79, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
ed.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  10.3 TEL | [26] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 54456 telepresence@localhost /bin/true
  10.3  21 | Handling connection for 54456
  10.3  21 | E1016 11:59:18.801175   16250 portforward.go:331] an error occurred forwarding 54456 -> 8022: error forwarding port 8022 to pod f94a902047cf843117d58035af39a837dec458caf1a0732e0dc6e4eed783108d, uid : unable to do port forwarding: socat not found.
  10.3 TEL | [26] exit 255 in 0.04 secs.
  10.6 TEL | [27] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 54456 telepresence@localhost /bin/true
  10.6  21 | Handling connection for 54456
  34.0 TEL | [28] Running: sudo -n echo -n
  40.6  21 | E1016 11:59:49.081494   16250 portforward.go:271] error creating error stream for port 54456 -> 8022: Timeout occured
  40.6 TEL | [27] exit 255 in 30.03 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. Telepresence needs to be better about handling failures and reporting useful error messages.

The socat-related message is coming from `kubectl port-forward`, not from Telepresence. Is there anything in [this issue](https://github.com/kubernetes/kubernetes/issues/19765) that helps? Are you able to use `kubectl port-forward` manually? Something like:

    kubectl port-forward --namespace custom-metrics deployment/custom-metrics-apiserver 8080:80

Can you please pass along the full telepresence.log as a [GitHub gist](https://gist.github.com/)?

**Comment by tellisnz** [comment]
Dupe of #781?

**Comment by astefanutti** [comment]
Thanks a lot. Installing `socat` on the node host fixes the issue. I had it installed on the client host instead.
