### ISSUE TITLE
Possibility of running telepresence in a docker container

### ISSUE THREAD

**Issue by rverma-nikiai** [telepresenceio/telepresence#811]
Team,
Tried to use telepresence within a debain base image container, but couldn't make it work. Is there a way to run telepresence as a container which also allows the local ide to use the env.json.
One challenge I see is since telepresence relies on local iptables, it would be hard to syncup the iptables within container to iptables on host.

Any workaround would be awesome.

Thanks

**Comment by ark3** [comment]
What happens when you try it? We have successfully run Telepresence in (privileged) containers.

**Comment by ark3** [comment]
Can you pass along the full telepresence.log as a [GitHub Gist](https://gist.github.com/) please? Thank you.

**Comment by ark3** [comment]
@DoctahPopp871 The log file in your Gist says

      17.8 TEL | FileNotFoundError: [Errno 2] No such file or directory: 'yarn'

Sorry about the crash! This absolutely should not crash Telepresence. But in this case, it seems like there's a problem with the PATH or similar, since Telepresence was unable to launch your command.

**Comment by graememross** [comment]
We managed to get this working using the following docker file

```
FROM ubuntu:18.04

RUN apt-get update &&\
    apt-get install -y curl &&\
    curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh |  bash

RUN apt install -y --no-install-recommends telepresence &&\
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg |  apt-key add -
RUN touch /etc/apt/sources.list.d/kubernetes.list &&\
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update &&\
    apt-get install -y kubectl \
                         sudo  \
                         iptables \
                         openjdk-8-jdk \
                         dnsutils \
                         nginx \
                         unzip \
                         jq &&\
    apt-get clean && apt-get autoclean && apt-get autoremove
```
There are some extra utilities in here to suit our mode of working (nginx, jdk, jq) which help our developers in connecting and controlling the system.

This seems to work well, the only problem is that if the connection is dropped for some reason (network flakiness) then telepresence does not try and re-establish the links (that would be a really nice feature)
