### ISSUE TITLE
Crash while exiting / starting at the same time

### ISSUE THREAD

**Issue by ritch** [telepresenceio/telepresence#812]
### What were you trying to do?

Running through this guide: https://www.telepresence.io/tutorials/docker

On the "We'll use Telepresence to swap the QOTM deployment with the local Docker image" step.

I had `telesprecence` running in a separate terminal window:

```sh
telepresence --docker-run -i -t alpine /bin/sh
```

So I tried...

```sh
exit
```

Immediately went to another terminal tab and...

```sh
telepresence --swap-deployment qotm --docker-run \
  --rm -it -v $(pwd):/service qotm-dev:latest
```

### What did you expect to happen?

Just running through the getting started, so not quite sure, not throw an exception though.

### What happened instead?

This page opened in my browser, pretty slick.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'qotm', '--docker-run', '--rm', '-it', '-v', '/Users/ritch/Projects/amazon/qotm:/service', 'qotm-dev:latest']`
Version: `0.93`
Python version: `3.7.0 (default, Oct  2 2018, 09:20:07) 
[Clang 10.0.0 (clang-1000.11.45.2)]`
kubectl version: `Client Version: v1.12.0 // Server Version: v1.10.3-eks`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Ritchies-MBP-2 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/__init__.py", line 88, in launch
    args.also_proxy, env, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 125, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/local/bin/telepresence/telepresence/runner/__init__.py", line 337, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/local/bin/telepresence/telepresence/runner/__init__.py", line 326, in _run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1540043565-0319638-33013', '--rm', 'datawire/telepresence-local:0.93', 'wait']' returned non-zero exit status 1.

```

Logs:

```
| Starting sshuttle proxy.
  12.1  27 | firewall manager: Starting firewall with Python version 3.6.5
  12.1  27 | firewall manager: ready method name nat.
  12.1  27 | IPv6 enabled: False
  12.1  27 | UDP enabled: False
  12.1  27 | DNS enabled: True
  12.1  27 | TCP redirector listening on ('127.0.0.1', 12300).
  12.1  27 | DNS listening on ('127.0.0.1', 12300).
  12.1  27 | Starting client with Python version 3.6.5
  12.1  27 | c : connecting to server...
  12.4 TEL | [29] Running: docker run --network=container:telepresence-1540043565-0319638-33013 --rm datawire/telepresence-local:0.93 wait
  12.8  29 | [INFO  tini (1)] Spawned child process 'python3' with pid '8'
  35.1 TEL | [30] Running: sudo -n echo -n
  38.4 TEL | (proxy checking local liveness)
  38.4  17 | 2018-10-20T13:53:12+0000 [Poll#info] Checkpoint
  43.0  29 | Failed to connect to proxy in remote cluster.
  43.0  29 | [INFO  tini (1)] Main child exited normally (with status '1')
  43.3 TEL | [29] exit 1 in 30.90 secs.

```

**Comment by ark3** [comment]
Sorry about the crash and thank you for the detailed explanation of what you did to get this crash. I believe you're seeing the problem described in #735. The same fix should handle this case too.

**Comment by ark3** [comment]
Telepresence 0.95 includes #726, which I believe fixes the issue you were seeing. Can you please give it a try?

**Comment by ark3** [comment]
I believe this is fixed. Please re-open if you find otherwise. Thank you!
