### ISSUE TITLE
Explain environmental sensitivity of Tel in the documentation

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#816]
Telepresence is sensitive to the user's environment in many ways. We should elaborate on this in the documentation. That will allow us to improve the explanation of our rationale for Scout reporting (in [the docs](https://github.com/telepresenceio/telepresence/blob/master/docs/reference/usage_reporting.md) and [the readme](https://github.com/telepresenceio/telepresence/blob/master/README.md)).

See also https://github.com/telepresenceio/telepresence/pull/814#issuecomment-434029344 and #285.

**Comment by donnyyung** [comment]
We should probably still do this in Telepresence 2.
