### ISSUE TITLE
Internet connection apparently required for DNS to work

### ISSUE THREAD

**Issue by vemv** [telepresenceio/telepresence#818]
Hi there,

say I `telepresence --run-shell` and then try to `curl myservice:3000`. It works, but as soon as I disconnect from the internet (e.g. run `sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -z`), DNS resolution will stop working.

I vaguely recall this problem being common to other (unrelated) technologies. Perhaps there's a common workaround, which if found would be worth recommending in the docs.

### Versions

```
$ minikube version
minikube version: v0.28.2
$ docker -v
Docker version 18.03.1-ce, build 9ee9f40
$ telepresence --version
0.93
```

Thanks - Victor

**Comment by nomcopter** [comment]
This is definitely frustrating for me as well. I want to work on the plane!

**Comment by donnyyung** [comment]
I don't quite understand the use-case here. If you are using telepresence for a remote cluster than an internet connection is a must. I'm going to close for now, but here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), so if you still encounter this issue / have more details about how you'd expect it to work, please re-open!

**Comment by nomcopter** [comment]
I use telepresence with [minikube](https://minikube.sigs.k8s.io/docs/) - a local cluster. It would be nice to be able to develop entirely locally using telepresence without an external internet connection.

**Comment by thallgren** [comment]
@nomcopter that should be possible. Do you have problems doing that using v2?

**Comment by nomcopter** [comment]
Oh that's exciting - haven't tried it yet. Right now v2 has some issues with our stack, so I won't be able to test that, but will add that to the list of reasons to upgrade.
