### ISSUE TITLE
[RFE] There should be a way to have the test suite emit TAP13

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#835]
It would be good for the test suite to (have an option to) emit a [TAP v13](https://testanything.org/tap-version-13-specification.html) stream (Test Anything Protocol), rather than the ad-hoc output that it emits currently.  This would allow for it to be hooked in to a test harness (such as https://github.com/datawire/testbench) that can do interesting reporting on the parse-able test results.

While many TAP proponents will tell you that you should stream your TAP output as tests run, I should note that `testbench` does not support streaming, and reads the output all at once (I do not expect that to ever change).  So if streaming introduces any complexity, it can be ignored.

**Comment by ark3** [comment]
I plan to try [pytest-tap](https://github.com/python-tap/pytest-tap).

**Comment by LukeShu** [comment]
Yeah, I'm happy enough with the TAP functionality already in pytest. Closing.
