### ISSUE TITLE
`ci/setup-gclould.sh` doesn't work with `docker` > 18.03

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#836]
Not a huge deal, but the Docker bit at the end of `./ci/setup-gcloud.sh` will eventually need to be modified to work with recent versions of Docker:

```console
$ ./ci/setup-gcloud.sh datawireio lukeshu us-central1-a linux
…
+ gcloud --quiet docker --authorize-only
WARNING: `gcloud docker` will not be supported for Docker client versions above 18.03.

As an alternative, use `gcloud auth configure-docker` to configure `docker` to
use `gcloud` as a credential helper, then use `docker` as you would for non-GCR
registries, e.g. `docker pull gcr.io/project-id/my-image`. Add
`--verbosity=error` to silence this warning: `gcloud docker
--verbosity=error -- pull gcr.io/project-id/my-image`.

See: https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker
```
And indeed, my docker is already newer than that:
```console
$ docker --version
Docker version 18.09.0-ce, build 4d60db472b
```

**Comment by ark3** [comment]
Is that "does not work" or "will stop working"? Perhaps this is an easy fix as suggested by the warning, or perhaps this will prompt us to stop using gcloud in CI entirely...

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
