### ISSUE TITLE
Crash while starting swap

### ISSUE THREAD

**Issue by motek80** [telepresenceio/telepresence#851]
Environment:

- Ubuntu 18.04 (VM on Hyper-V)
- Windows 10 Pro host

- MicroK8s (1.12)
- Docker (18.06.1-ce)
- Telepresence 0.94

Executing the following command:
`telepresence --docker-run --rm -e JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -p 8080:8080 -p 5005:5005 crypto-service`

Getting the following error:
`Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 85, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 89, in launch
    args.also_proxy, env, ssh, mount_dir
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 146, in run_docker_command
    "Waiting for network container timed out. File a bug, please!"
RuntimeError: Waiting for network container timed out. File a bug, please!

And here are the last few lines of the logfile (see /home/digi/telepresence.log for the complete logs):

 120.9 TEL | [123] exit 125 in 0.20 secs.
 121.9 TEL | [124] Running: docker run --network=container:telepresence-1544010121-9234562-3214 --rm datawire/telepresence-local:0.94 wait
 122.0 TEL | [125] Running: sudo -n echo -n
 122.0 124 | docker: Error response from daemon: No such container: telepresence-1544010121-9234562-3214.
 122.0 TEL | [124] exit 125 in 0.17 secs.
 123.0 TEL | [126] Running: docker run --network=container:telepresence-1544010121-9234562-3214 --rm datawire/telepresence-local:0.94 wait
 123.2 126 | docker: Error response from daemon: No such container: telepresence-1544010121-9234562-3214.
 123.2 TEL | [126] exit 125 in 0.20 secs.
 124.2 TEL | [127] Running: docker run --network=container:telepresence-1544010121-9234562-3214 --rm datawire/telepresence-local:0.94 wait
 124.4 127 | docker: Error response from daemon: No such container: telepresence-1544010121-9234562-3214.
 124.4 TEL | [127] exit 125 in 0.19 secs.
 125.4 TEL | [128] Running: docker run --network=container:telepresence-1544010121-9234562-3214 --rm datawire/telepresence-local:0.94 wait
 125.6 128 | docker: Error response from daemon: No such container: telepresence-1544010121-9234562-3214.
 125.6 TEL | [128] exit 125 in 0.19 secs.
 126.6 TEL | [129] Running: docker run --network=container:telepresence-1544010121-9234562-3214 --rm datawire/telepresence-local:0.94 wait
 126.8 129 | docker: Error response from daemon: No such container: telepresence-1544010121-9234562-3214.
 126.8 TEL | [129] exit 125 in 0.17 secs.
 127.8 TEL | [130] Running: docker run --network=container:telepresence-1544010121-9234562-3214 --rm datawire/telepresence-local:0.94 wait
 127.9 130 | docker: Error response from daemon: No such container: telepresence-1544010121-9234562-3214.
 127.9 TEL | [130] exit 125 in 0.17 secs.`

**Comment by ark3** [comment]
Sorry about the crash. It looks like the network container failed to start for some reason. If you share the entire telepresence.log file as a [GitHub Gist](https://gist.github.com/), we can take a look.

However, a bit of troubleshooting at your end may get you running quickly. Open the log file and search for `Launching Network container`. You may be able to see what's going on. 

It may look something like this:

```
  26.1 TEL | [54] Launching Network container: docker run -p=8080:8080 --rm --privileged --name=telepresence-1544017690-552902-63319 datawire/telepresence-local:0.94 proxy '{"port": 64512, "cidrs": ["10.0.1.0/24", "10.0.0.0/24", "10.3.240.0/20", "10.0.38.0/24", "10.0.2.0/24"], "expose_ports": [], "ip": "198.18.0.254"}'
... other stuff ...
  26.9  54 | docker: Error response from daemon: driver failed programming external connectivity on endpoint telepresence-1544017690-552902-63319 (9da90cfd8e4f64a3e5284d004c2d314ad3c71ec7a56e6a2c9158571d54310eb8): Bind for 0.0.0.0:8080 failed: port is already allocated.                              
  26.9 TEL | [54] exit 125         
```

In this example, the network container is process `54`. You can see from the message `Bind for 0.0.0.0:8080 failed: port is already allocated` that my `-p` argument has caused the launch to fail. Something similar may be happening at your end. I'm working to improve error reporting on this for the next release.

**Comment by motek80** [comment]
Hi, Unfortunately I already removed Microk8s and instead I installed Kubeadm. Now it works. Later I will try to investigate this deeper. Thanks

**Comment by ark3** [comment]
Ah, interesting. It looks like [MicroK8s uses port 8080](https://microk8s.io/docs/#accessing-kubernetes). That would conflict with your `-p` argument to Docker. I'm glad you have things running. Best wishes.
