### ISSUE TITLE
Telepresence with Kubernetes Java Client

### ISSUE THREAD

**Issue by motek80** [telepresenceio/telepresence#852]
Inside my container i have to access Kubernetes API and perform some actions (for example, listing secrets).
For communicating with Kubernetes API I'm using official Java client (3.0.0.0).

When I running my container via Telepresence, any call to api results in "404 Not Found".

Any ideas?

This is how I initializing Client API:
`ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);
CoreV1Api api = new CoreV1Api();`

**Comment by ark3** [comment]
https://www.telepresence.io/tutorials/java#kubernetes-client

**Comment by motek80** [comment]
Yep it works with "mount". Thanks.

Just curious - why not mount "always"?
