### ISSUE TITLE
Telepresence can't attach to running telepresence deployment pod and execute podinfo.py script 

### ISSUE THREAD

**Issue by Dimss** [telepresenceio/telepresence#857]
### What were you trying to do?
Telepresence 0.95 is deployed in the K8S cluster. 
Telepresence deployment name: `tel`
Locally I'm execute: `telepresence -d tel` to connect to cluster, but getting error (see logs) 

### What did you expect to happen?
Telepresence client successfully connect to the telepresence deployment 

### What happened instead?
While running `telepresence -d tel`, I'm getting error (see logs). 

The actually issue related to the fact that I'm unable to attach and execute any command on telepresence pod. Even simple docker attach command is failing.
For example:
`docker ps`
```
1fcc7e6c9eb1        docker.io/datawire/telepresence-k8s@sha256:59e7a7822fc55056003a4107007e2c079c509a7a98f77b87bec2d19a94e71ddd                 "/bin/sh -c /usr/s..."   9 minutes ago       Up 9 minutes                            k8s_tel_tel-1-8wwjd_kubis_825122c1-fa4a-11e8-946b-42010a9c0002_0
```
` docker exec -it 1fcc7e6c9eb1 /bin/sh`
```
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "process_linux.go:110: decoding init error from pipe caused \"read parent: connection reset by peer\""
```
**But, that issue is happening only with following docker version:** 
```
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-84.git07f3374.el7.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Tue Nov  6 18:41:32 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```  

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '-d', 'tel']`
Version: `0.95`
Python version: `3.7.1 (default, Nov  6 2018, 18:45:35) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.12.2 // Server Version: v1.11.0+d4cacc0`
oc version: `oc v3.11.0+0cbc58b // kubernetes v1.11.0+d4cacc0 // features: Basic-Auth //  // Server https://master.c.ocp-222806.internal:8443 // openshift v3.11.43 // kubernetes v1.11.0+d4cacc0`
OS: `Darwin dimasmac 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 73, in main
    env, pod_info = get_remote_env(runner, ssh, remote_info)
  File "/usr/local/bin/telepresence/telepresence/remote_env.py", line 34, in get_remote_env
    remote_info.container_name, "--", "python3", "podinfo.py"
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 354, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['oc', '--context', 'kubis/master-c-ocp-222806-internal:8443/system:admin', '--namespace', 'kubis', 'exec', 'tel-1-8wwjd', '--container', 'tel', '--', 'python3', 'podinfo.py']' returned non-zero exit status 126.

```

Logs:

```
> | 
   6.2 >>> | No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.
   6.2 >>> | 
   6.2 TEL | Launching Web server for proxy poll
   6.2 TEL | [20] Launching SSH port forward (socks and proxy poll): ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 50340 telepresence@localhost -L127.0.0.1:50357:127.0.0.1:9050 -R9055:127.0.0.1:50358
   6.2 TEL | END SPAN connect.py:36(connect)    1.9s
   6.2 TEL | BEGIN SPAN remote_env.py:28(get_remote_env)
   6.2 TEL | [21] Capturing: oc --context kubis/master-c-ocp-222806-internal:8443/system:admin --namespace kubis exec tel-1-8wwjd --container tel -- python3 podinfo.py
   6.2  14 | Handling connection for 50340
   7.3  21 | command terminated with exit code 126
   7.3 TEL | [21] exit 126 in 1.16 secs.
   7.3 TEL | END SPAN remote_env.py:28(get_remote_env)    1.2s

```

**Comment by ark3** [comment]
You might be seeing a bug in that old version of Docker. Can you try [this hack](https://github.com/moby/moby/issues/14203#issuecomment-204976854) for your `docker exec` command? If that works, then at least we know the problem.

**Comment by ark3** [comment]
Or maybe it's not an old bug... See this [StackOverflow entry](https://stackoverflow.com/questions/53605666/cannot-run-command-in-docker-container).

**Comment by Dimss** [comment]
@ark3 , I think you are right, it's a new bug in RHEL's docker package. Cuz, I'm running OpenShift on top of RHEL7, and when I'm downgrade the docker everything works as expected. 
And now, I just updated the docker by `yum -y update docker` and got different version than previous:
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-88.git07f3374.el7.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Thu Dec  6 07:01:49 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-88.git07f3374.el7.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Thu Dec  6 07:01:49 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```
It's looks like the go version is different as well as the build time. 
Anyhow, with this version, I'm able to attach to the pod, and as a result telepresence works as expected. 
Thank you for you help!

**Comment by ark3** [comment]
I'm glad you're up and running now.
