### ISSUE TITLE
Telepresence doesn't work - SSH isn't starting 

### ISSUE THREAD

**Issue by dveoz** [telepresenceio/telepresence#860]
### What were you trying to do?

Run the $ telepresence command. This was freshly installed on a new machine.

### What did you expect to happen?

It would create a connection into the cluster

### What happened instead?

I get the traceback below.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'one-service', '--namespace=develop', '--docker-run', '--rm', '-e', 'MAVEN_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005', '-v/Users/eugene/kuber/one:/build', '-v', '/Users/eugene/.m2/repository:/m2', '-p', '9001:9001', '-p', '5005:5005', 'maven-build:jdk8', 'mvn', '-Dmaven.repo.local=/m2', '-f', '/build', 'spring-boot:run']`
Version: `0.95`
Python version: `3.7.1 (default, Nov 28 2018, 11:51:54) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.13.0 // Server Version: v1.10.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin home.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 84, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 75, in launch
    args.also_proxy, env, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 122, in run_docker_command
    local_ssh.wait()
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 82, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
xit 255 in 0.00 secs.
  32.9 TEL | [139] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 52795 root@localhost /bin/true
  32.9 TEL | [139] exit 255 in 0.02 secs.
  33.1  28 |   28.8 TEL | [116] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 38023 telepresence@localhost /bin/true
  33.1  28 |   28.8 TEL | [116] exit 255 in 0.00 secs.
  33.2 TEL | [140] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 52795 root@localhost /bin/true
  33.2 TEL | [140] exit 255 in 0.02 secs.
  33.4  28 |   29.0 TEL | [117] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 38023 telepresence@localhost /bin/true
  33.4  28 |   29.0 TEL | [117] exit 255 in 0.00 secs.
  33.4 TEL | [141] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 52795 root@localhost /bin/true
  33.5 TEL | [141] exit 255 in 0.02 secs.

```

**Comment by DoctahPopp871** [comment]
Currently facing the same error when attempting to connect to an EKS cluster in AWS from my local machine. Works fine outside of the container, inside of the container I receive the error above. I am on .95

**Comment by capjdcoder** [comment]
I tried with both versions (v.0.95 and v.0.94) but still had the same issue. Read about possible solutions  of removing `::1.  localhost` from `/etc/hosts` didn't help so looking into the source code to configure system another way and make it work with minikube.

**Comment by ark3** [comment]
Can you pass along the full telepresence.log as a [GitHub Gist](https://gist.github.com/) please? Thank you.

**Comment by capjdcoder** [comment]
Here's the log: https://gist.github.com/capjdcoder/bafae6fa7283a33e43b7c9adfa72142c

**Comment by capjdcoder** [comment]
@ark3 what could be wrong here? Do I have to change my local setup?

**Comment by ark3** [comment]
@capjdcoder Thanks for the trace. As you guessed, you might be running into #783, or a Mac variant thereof. But the workaround there didn't work for you. Another possibility is that Docker port forwarding broke recently. Can you try your command without the `-p` options just to see whether things start? Can you try an even simpler command?

    telepresence --docker-run --rm -it fedora curl -sk https://kubernetes.default

**Comment by capjdcoder** [comment]
@ark3 I also though about that, it might happen because I was using the following command with Docker:
```
eval $(qinikube docker-env)
```
to switch registry. I will try it out without port forwarding and post the result. 

Thank you for help!

**Comment by capjdcoder** [comment]
@ark3 unfortunately didn't help. I tried this command:
```
telepresence --docker-run --rm -it fedora curl -sk https://kubernetes.default
```
but the result is the same. I attached log file here. 
[telepresence.log](https://github.com/telepresenceio/telepresence/files/2665120/telepresence.log)

**Comment by ark3** [comment]
I'm glad you thought of that. Using Minikube's Docker daemon, which is running in a VM, will not work with Telepresence's container method. I suppose Telepresence should check for this (Docker talking to a non-local daemon) and report to the user.

**Comment by capjdcoder** [comment]
Agree about checking for that. However last time I used the system docker, not Minikube's without `::1 localhost` in my `/etc/hosts` and still have the issue.

It looks like it tries to open the connection to `root@localhost`. I might try to enable it on my laptop and will see what happen.

**Comment by ark3** [comment]
Yup, it runs sshd in the network container, exposes that port, and then runs ssh from the host to the container to set up port forwarding.

**Comment by capjdcoder** [comment]
@ark3 after enabling SSH for `root` user on Mac and do not evaluating the `eval $(minikube docker-env)` this command:
```
telepresence --docker-run --rm -it fedora curl -sk https://kubernetes.default
```
showed me the following output in Terminal window:
```
T: Invoking sudo. Please enter your sudo password.
Password:
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
Unable to find image 'fedora:latest' locally
latest: Pulling from library/fedora
d0483bd5a554: Pull complete
Digest: sha256:4a861283a7f0a8ce3d19b42f4c0a10d7012a4d12f785149d82a0800cdb4498b0
Status: Downloaded newer image for fedora:latest
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}T: Exit cleanup in progress
```

**Comment by ark3** [comment]
That looks like it worked. Does your original Telepresence command work this way?

**Comment by capjdcoder** [comment]
@ark3 Sorry for my absence here. Have issues with my Mac as well :) I made it work fully on my Mac with minikube without any issues.

I need probably a day or two to describe the solution (all the things are environmental - the telepresence code is OK, but `localhost`?), and then paste it here.

@ark3 - thank you for been with me, your thoughts and good logs made me think in right direction.

**Comment by ervitis** [comment]
Hi, I am having the same issue as @capjdcoder using xubuntu "cosmic" distro.
The difference from @capjdcoder log is that it's trying to log with the user "telepresence".

Here it is the log: https://gist.github.com/ervitis/9c417b45473960fe5743be75fe0800aa

**Comment by Dean-Coakley** [comment]
I'm experiencing the exact same issue, Mac & Minikube environment

**Comment by rvit34** [comment]
Hi guys,

I've just faced with the same problem as well. 
Ubuntu 18.04 LTS
Last version of Telepresence

ssh is available for su
For me the problem appears with/without port-forwarding option.

My command is
```
telepresence --verbose --namespace mynamespace --swap-deployment mydeployment --run java -jar my-spring-boot-service.jar --spring.config.location=classpath:/application.yml,file:./override.yml 
```

@capjdcoder How did you manage to fix it?

Soft versions:
```
   0.0 TEL | Platform: linux   
   0.0 TEL | Python 3.6.7 (default, Oct 22 2018, 11:32:17)  
   0.0 TEL | [GCC 8.2.0]  
   0.0 TEL | [1] Running: uname -a  
   0.0   1 | Linux workstation 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux  
   0.0 TEL | BEGIN SPAN main.py:40(main)  
   0.0 TEL | BEGIN SPAN startup.py:74(__init__)  
   0.0 TEL | Found kubectl -> /usr/local/bin/kubectl  
   0.0 TEL | Found oc -> /usr/local/bin/oc  
   0.0 TEL | [2] Capturing: kubectl version --short  
   0.6   2 | Client Version: v1.11.0+d4cacc0  
   0.6   2 | Server Version: v1.10.0+b81c8f8  
```

**Comment by ark3** [comment]
If you're using OpenShift, please see the security context constraint information in the [documentation](https://www.telepresence.io/tutorials/openshift.html#debugging-a-service-locally-with-telepresence). This is something that Telepresence should detect rather than failing mysteriously. If this fixes it for you, please let us know here. Thank you!

Not using OpenShift? In that case, can you please file a separate issue and include a Gist with your full telepresence.log file? Feel free to block out any sensitive information using search-and-replace. Thanks for your help debugging this.

**Comment by rvit34** [comment]
@ark3 Thanks. Properly defining security context in OpenShift fixed my issue
