### ISSUE TITLE
How to connect to cloud services such as BigQuery?

### ISSUE THREAD

**Issue by johanhaleby** [telepresenceio/telepresence#863]
I have an app and the requests are successfully routed to my local instance when doing:

```
$ telepresence --swap-deployment my-deployment --env-file ~/file.env
```

I load up intellij and point to the `file.env` to load up the environment. The app is deployed on GKE and connects to BigQuery. It does this by simply invoking this initialization code from within my application (using Kotlin):

```kotlin
val bigQuery = BigQueryOptions.getDefaultInstance().service
```

I well aware that this only work when running inside GKE but my hope was that it would also work with Telepresence. But instead it yields this error when communicating with BigQuery:

```java
com.google.cloud.bigquery.BigQueryException: 400 Bad Request
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:99)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:175)
	at com.google.cloud.bigquery.BigQueryImpl$4.call(BigQueryImpl.java:216)
	at com.google.cloud.bigquery.BigQueryImpl$4.call(BigQueryImpl.java:213)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:212)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:187)
```

Is this expected?

**Comment by ark3** [comment]
I think your swap will work if you tell Telepresence to proxy the cloud service as well, using the `--also-proxy` option. Based on [these API docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/) I suggest trying `--also-proxy www.googleapis.com`, but I might not have that address right.

**Comment by johanhaleby** [comment]
@ark3 Thanks! I've tried `--also-proxy www.googleapis.com` but it doesn't seem to work, I still get the same error. Might be the wrong address then. According to the API docs that you found that seems to be the correct address. Should I close the issue and just try to find the right address?

**Comment by ark3** [comment]
The other thing to check is that your credentials are available. If they come from an environment variable, then that should already be covered with the env file, but double-check the file to make sure everything you expect is there. If they come from the filesystem, then some additional configuration with TELEPRESENCE_ROOT might be required. [This example](https://www.telepresence.io/tutorials/java#kubernetes-client) is for the Kubernetes client, but the same principle applies.

**Comment by johanhaleby** [comment]
They should be read from the environment afaict. I'm looking in the BigQuery client library source code and it seem to imply that for example the project id should be available in an environment variable called `GOOGLE_CLOUD_PROJECT` and credentials in `GOOGLE_APPLICATION_CREDENTIALS`. Neither of these are present in the generated env file.
