### ISSUE TITLE
Container method fails mysteriously when Docker daemon is remote or in a VM

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#873]
Telepresence should detect this case and report an error rather than crashing after a timeout. A remote daemon (running on another machine) or a daemon running in a VM (such as when using `eval $(minikube docker-env)`) fail the same way. Maybe we should run something like the network container and check whether we can connect to it. This would also be an opportunity to catch other things that can break launching the network container.

**Comment by ark3** [comment]
A fairly quick and easy check is something like

```console
$ docker run --rm --entrypoint "" -v /tmp/tel-xto32c_c:/tel datawire/telepresence-local:0.99 cat /tel/session_id.txt
3abf700c6bbe482b9c350572fbd8de38
```

where `/tmp/tel-xto32c_c` is `runner.temp` and the hex blob that comes back should be `runner.session_id`.

This test will take maybe 1.5 seconds once the image is pulled, and that image pull cost has to be paid anyhow.

**Comment by levindoneto** [comment]
I'm still having this issue on Ubuntu 18.04 and Telepresence 0.109.
![image](https://user-images.githubusercontent.com/12832687/128451465-80b0df00-7042-49c8-a011-b2ed584c934f.png)
