### ISSUE TITLE
Newest Linux distro releases are not supported

### ISSUE THREAD

**Issue by ervitis** [telepresenceio/telepresence#876]
Is there a new version of telepresence for ubuntu "cosmic" version?

**Comment by ark3** [comment]
Need to add support for
- Ubuntu 18.10 Cosmic Cuttlefish
- Fedora 29
- ~~Debian 9.6~~ It seems this is still Debian Stretch and is thus already covered.

**Comment by ervitis** [comment]
Also, there is a problem and it looks like the https://github.com/telepresenceio/telepresence/issues/860 issue using that version of ubuntu with minishift and kubectl installed.
