### ISSUE TITLE
Permit exposing multiple services (ie: --swap-deployment X --swap-deployment Y) or run multiple telepresences in parallel

### ISSUE THREAD

**Issue by rkr-kununu** [telepresenceio/telepresence#888]
I'd like to be able to run multiple services locally on my machine, but have them replace certain remote deployments on k8s.

A bit more detail about my use-case:  I've got two microservices I'd like to develop in parallel w/ telepresence.  It's a simple publish/subscribe application... with the message bus daemon residing in k8s.  I'd like to develop the publish code locally, have the message send to the message bus daemon residing on k8s, and develop the consumer on another services running on my local machine.

I've tried to run multiple telepresences (once for service X and another for service Y) and the results "sort of" worked.  I was able to replace multiple deployments, but when I tried to exit service X.  It broke the DNS resolution for service Y (ie: the clean-up code for X, wiped the changes for both X and Y).

I looked through the source code for telepresence and it does not appear to be designed to handle this use-case.  Is my use-case something that telepresence can/should/will cover?  Or is there a more obvious solution?

**Comment by ark3** [comment]
Can you give us more information? What did you run that partly worked? As far as I have seen, multiple simultaneous Telepresence sessions run fine when using the container method.

**Comment by rkr-kununu** [comment]
Certainly.  For my use case I wasn't using `--method container` as I wanted run multiple services locally (they're Node apps and are easier to debug when ran natively on my Mac host).  The only way I could do this was by running multiple telepresence sessions with `--method vpn-tcp` (which clearly says you shouldn't).

The result was I could run multiple `telepresence --swap-deployment X --expose 9090:80 --run XYZ` and `telepresence --swap-deployment Y --expose 9091:80 --run-shell`.  However when I terminate one of the sessions, the dns-tunnel to k8s is destroyed and "reverted".  Hence the dns does not resolve even though I left the second telepresence session open.

I assume whatever garbage collection happen when telepresence terminates, does not take into account that there maybe other telepresence sessions running (with using the vpn-tcp method).

**Comment by deadtrickster** [comment]
Also seems to be rather relevant to me. I hope someone will pick this one up.

**Comment by tvvignesh** [comment]
While telepresence is awesome. This is the only issue I have with it since I am not using container method. Would be great to have this.

**Comment by Tarjei400** [comment]
Any news on this one ? This tool sortof looses point if doesnt support swapping of multiple services out of a box :/

**Comment by ark3** [comment]
@Tarjei400 What behavior are you looking for?

**Comment by Tarjei400** [comment]
something like `~ telepresence --swap-deployment service1 --swap-deployment service2--expose 8002:8080 --expose 5000:8080` 
Suprisingly exposing multiple ports works (at least according to logs)

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since you can intercept multiple services at once on one workstation. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
