### ISSUE TITLE
Subprocesses started in telepresence shell should be killed when telepresence exits

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#89]
Keeping them around is confusing.

**Comment by exarkun** [comment]
It looks like if `--run` is used then that process is also left around sometimes.  I just had telepresence exit like:

```
Proxy to Kubernetes exited. This is typically due to a lost connection.                                                                                                                                            
Error in atexit._run_exitfuncs:                     
Traceback (most recent call last):                  
  File "/usr/bin/telepresence", line 2134, in terminate_if_alive                                                                                                                                                   
    mount_cleanup()                                 
  File "/usr/bin/telepresence", line 1671, in cleanup                                                                                                                                                              
    sudo_prefix + ["fusermount", "-z", "-u", mount_dir]                                                  
  File "/usr/bin/telepresence", line 384, in check_call                                                                                                                                                            
    raise CalledProcessError(retcode, args)                                                              
subprocess.CalledProcessError: Command '(['fusermount', '-z', '-u', '/tmp/tmpth707bk0'],)' returned non-zero exit status 1.           
```

and the process started with `--run` was left running.

Not sure if the fusermount error is relevant or not.  even for normal exit (ie Control-C) it seems like that error pops up (and on Control-C the process doesn't seem to leak).

**Comment by jody-frankowski** [comment]
I just had the same stack trace when hitting C-c:
```
$ telepresence --swap-deployment hello-world --expose 8000 --run python3 -m http.server 8000
[...]
127.0.0.1 - - [15/Jan/2018 11:14:16] "HEAD /test.txt HTTP/1.0" 200 -
127.0.0.1 - - [15/Jan/2018 11:14:16] "HEAD /test.txt HTTP/1.0" 200 -
127.0.0.1 - - [15/Jan/2018 11:14:16] "HEAD /test.txt HTTP/1.0" 200 -
^C
Keyboard interrupt received, exiting.Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/bin/telepresence", line 2137, in terminate_if_alive
    mount_cleanup()
  File "/usr/bin/telepresence", line 1673, in cleanup
    sudo_prefix + ["fusermount", "-z", "-u", mount_dir]
  File "/usr/bin/telepresence", line 386, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['fusermount', '-z', '-u', '/tmp/tmpz805s9du'],)' returned non-zero exit status 1.
```

**Comment by exarkun** [comment]
One possible solution would be use sessions and process groups.  If telepresence were a session leader and the processes it launched were members of its process group then when telepresence exits (for any reason) those processes would receive SIGHUP which would normally be sufficient to cause them to exit.  This isn't a guarantee that the processes will exit - they could handle SIGHUP and do something else.

Another possible solution would be for telepresence to launch a cleanup sidecar.  The sidecar would watch for telepresence to exit and then clean up the other processes.  This cleanup would only be as reliable as the cleanup sidecar.  It's probably not _too_ hard to make a pretty-reliable sidecar that is responsible for cleanup (sending one or more signals) and nothing else.  If the sidecar fails, though, then we're still left with some leaked processes.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
