### ISSUE TITLE
inject-tcp stopped working

### ISSUE THREAD

**Issue by pocorschi** [telepresenceio/telepresence#891]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell', '--method', 'inject-tcp']`
Version: `0.95`
Python version: `3.7.1 (default, Nov 28 2018, 11:51:54) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.10.1 // Server Version: v1.10.9-gke.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Mihais-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 84, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 33, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 99, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 69, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket().connect(('"'"'google.com'"'"', 80))'
  35.6  73 | Traceback (most recent call last):
  35.6  73 |   File "<string>", line 1, in <module>
  35.6  73 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  35.6 TEL | [73] exit 1 in 0.13 secs.
  35.7 TEL | [74] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  35.9  74 | Traceback (most recent call last):
  35.9  74 |   File "<string>", line 1, in <module>
  35.9  74 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  35.9 TEL | [74] exit 1 in 0.14 secs.
  36.0 TEL | [75] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'google.com'"'"', 80))'
  36.1  75 | Traceback (most recent call last):
  36.1  75 |   File "<string>", line 1, in <module>
  36.1  75 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  36.1 TEL | [75] exit 1 in 0.14 secs.
  36.1 TEL | END SPAN local.py:42(set_up_torsocks)   10.0s

```

**Comment by pocorschi** [comment]
as a followup, I have discovered that neither methods work reliably. i keep random disconnects or errors out. the only fix being closing the iterm tab and trying in another one or even restarting the machine

**Comment by ark3** [comment]
Sorry about the crash and flakiness. Can you please link the full log as a [Gist](https://gist.github.com/) from a crash? Thanks.
