### ISSUE TITLE
index out of range: get_deployment_json attemps to return the first item when there is none

### ISSUE THREAD

**Issue by lichuan0620** [telepresenceio/telepresence#892]
### What were you trying to do?

I have a running remote cluster. I want to replace the remote deployment `awesome-app` so I ran:
```
telepresence -s awesome-app --expose 8080 --docker-run -e "SOME_ENV=passwd123" -i awesome-image:latest
```
(the command above, as well as the log below, are modified to hide company's info)

### What did you expect to happen?

That the deployment is correctly replaced

### What happened instead?

telepresence crashed due to unhandled index-out-of-range error, apparently because get_deployment_json is expected to find at least one deployment but it found none

Related log:

   8.2 TEL | Scout info: {'latest_version': '0.96', 'application': 'telepresence', 'notices': []}
   8.2 TEL | BEGIN SPAN deployment.py:140(supplant_deployment)
   8.2 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   8.2 TEL | [10] Capturing: kubectl --context default --namespace default get deployment -o json --export awesome-app
   8.9 TEL | END SPAN remote.py:78(get_deployment_json)    0.6s
   8.9 TEL | [11] Running: kubectl --context default --namespace default delete deployment awesome-app-6b9630544573424c872c4fa885360a13 --ignore-not-found
   9.4 TEL | [12] Running: kubectl --context default --namespace default apply -f -
  10.1  12 | deployment.extensions/awesome-app-6b9630544573424c872c4fa885360a13 created
  10.1 TEL | [13] Running: kubectl --context default --namespace default scale awesome-app --replicas=0
  11.5  13 | deployment.extensions/awesome-app scaled
  11.5 TEL | [13] ran in 1.35 secs.
  11.5 TEL | END SPAN deployment.py:140(supplant_deployment)    3.2s
  11.5 TEL | BEGIN SPAN remote.py:154(get_remote_info)
  11.5 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
  11.5 TEL | [14] Capturing: kubectl --context default --namespace default get deployment -o json --export --selector=telepresence=6b9630544573424c872c4fa885360a13
  12.2 TEL | END SPAN remote.py:78(get_deployment_json)    0.7s
  14.2 TEL | CRASH: list index out of range
  14.2 TEL | Traceback (most recent call last):
  14.2 TEL |   File "/usr/local/bin/telepresence/telepresence/cli.py", line 131, in crash_reporting
  14.2 TEL |     yield
  14.2 TEL |   File "/usr/local/bin/telepresence/telepresence/main.py", line 67, in main
  14.2 TEL |     remote_info = start_proxy(runner)
  14.2 TEL |   File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 90, in start_proxy
  14.2 TEL |     run_id=run_id,
  14.2 TEL |   File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 156, in get_remote_info
  14.2 TEL |     runner, deployment_name, deployment_type, run_id=run_id
  14.2 TEL |   File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 103, in get_deployment_json
  14.2 TEL |     )["items"][0]
  14.2 TEL | IndexError: list index out of range

**Comment by ark3** [comment]
Sorry about the crash! Job [12] is the `kubectl` command that creates the deployment. Job [14] is the `kubectl` command that tries to fetch the new deployment's information for further processing. I'm not sure why the latter command would not find the deployment when the former succeeded.

Could you please try this again, with `--verbose` for additional logging? That will yield more information in the log file, so you will probably need to examine that yourself and then summarize what you see. Alternatively, you could send the log file through a private channel (e.g., hello@datawire.io). Either way I'm curious to learn more. Thank you.

**Comment by lichuan0620** [comment]
I have tried with verbose, but that lead to https://github.com/telepresenceio/telepresence/issues/807 and crashed before the problem in this issue could be reproduced; thus I was unable to gain any insight from the log.

> I'm not sure why the latter command would not find the deployment when the former succeeded.

Me neither. I saw the new container created by telepresence before it was quickly terminated, so Job[12] indeed created something. I could be something in my company's cluster changed or deleted the new deployment but the possibility is very low (I have deployed many toys there with no problem), and even if it does, I feel like there should be some mechanism to detect and report this, instead of just assuming the list is not empty and fetching the first item.

**Comment by ark3** [comment]
Does Telepresence work if you use a new deployment, the default? E.g., 

    telepresence --docker-run --rm -it fedora curl -svk https://kubernetes.default/api

Trying this may help us determine whether there is something about the Telepresence proxy deployment that your cluster doesn't like.
