### ISSUE TITLE
CRASH: vpn-tcp tunnel did not connect

### ISSUE THREAD

**Issue by ghost** [telepresenceio/telepresence#896]
### What were you trying to do?

telepresence --run-shell 

(OSX Mojave 10.14.2/minikube vbox kube 1.11.5)

### What did you expect to happen?

DNS access to services running in minikube from localhost

### What happened instead?

don't know, but I'll send the log.
https://gist.github.com/oceaneer/1e78f9bd549bdb143eeaebf365e34a8f

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell']`
Version: `0.96`
Python version: `3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]`
kubectl version: `Client Version: v1.13.1 // Server Version: v1.11.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin dsdev 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 131, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 84, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 290, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
.dns.DNSDatagramProtocol object at 0x7ff6bf4b4ef0>
  43.3  27 | c : DNS request from ('10.154.47.190', 62200) to None: 34 bytes
  43.3  20 | 2019-01-11T17:44:42+0000 [stdout#info] A query: b'www.facebook.com'
  45.1  20 | 2019-01-11T17:44:44+0000 [-] DNSDatagramProtocol starting on 2022
  45.2  20 | 2019-01-11T17:44:44+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7ff6bf49fd30>
  45.2  20 | 2019-01-11T17:44:44+0000 [-] (UDP Port 54317 Closed)
  45.2  20 | 2019-01-11T17:44:44+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7ff6bf4da6d8>
  46.2  20 | 2019-01-11T17:44:45+0000 [-] DNSDatagramProtocol starting on 43208
  46.3  20 | 2019-01-11T17:44:45+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7ff6bf4da6d8>
  46.3  20 | 2019-01-11T17:44:45+0000 [-] (UDP Port 39934 Closed)
  46.3  20 | 2019-01-11T17:44:45+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7ff6bf4da898>

```

**Comment by popaaaandrei** [comment]
[telepresence.log](https://github.com/telepresenceio/telepresence/files/3167655/telepresence.log)
This is my log. I tried as well with/without sudo.

**Comment by ark3** [comment]
@popaaaandrei Your log is different from that of the original poster. In your case, it looks like the remote end sees DNS queries and responds, but the local end does not see the responses. Does DNS start failing for all applications when you run Telepresence?

**Comment by popaaaandrei** [comment]
Sorry... Should I open a new issue? I thought it was related. For me, Telepresence crashes every time, regardless if it's `--new-deployment`, `--swap-deployment` or `--run-shell`.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
