### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#92]
It would be good to support Windows.

Options:

* Windows Subsystem for Linux.
* `torsocks` equivalent.
* Other implementation strategies, e.g. #76.

**Comment by ark3** [comment]
Possibly helpful: 
https://reqrypt.org/tallow.html
https://github.com/basil00/TorWall

**Comment by itamarst** [comment]
https://en.wikipedia.org/wiki/Comparison_of_proxifiers list some more possibilities.

**Comment by itamarst** [comment]
Also http://alternativeto.net/software/sockscap/ surprisingly.

**Comment by itamarst** [comment]
Also:
* https://github.com/VahidN/Process-Proxifier
* https://github.com/shadowsocks/shadowsocks-windows (basically, changes Windows system proxy to use SOCKS 5 proxy I guess)

**Comment by itamarst** [comment]
It appears that Windows Subsystem for Linux can successfully run `torsocks`, so plausibly it can support Telepresence.

By default, at least in VM I obtained, it uses Ubuntu 14.04 as basis, which is rather out of date, so I had to compile newer torsocks. Supposedly updates switched to Ubuntu 16.04, so next will investigate if it's actually possible to upgrade WSL.

**Comment by itamarst** [comment]
Supposedly "The Creators Update", coming April 11th, will have the updated WSL.

**Comment by itamarst** [comment]
Testing WSL with Creators Update.

Notes:
* Telepresence installs just fine.
* However, sshfs does not work on WSL. That means dropping volume support or using cruder mechanism (copy the files, say, which shouldn't be a problem if we limit copying to secrets, configmaps and the /var/run/secrets one).
* ... more as I try stuff ...

**Comment by itamarst** [comment]
Apparently forgot to mention update to above: on Windows, lack of sshfs results in warning, but telepresence should work in WSL. I haven't tested in recently though.

**Comment by maver1ck** [comment]
@itamarst 
Could you tell me how to run telepresence on WSL ?
Normal run:
```
fatal: ['iptables', '-t', 'nat', '-nL'] returned 3
```

Docker-run
```
 CRASH: Command '['ip', 'addr', 'show', 'dev', 'docker0']' returned non-zero exit status 1
```

**Comment by ark3** [comment]
Using `--method inject-tcp` has worked in the past; there is a bit of [documentation](https://www.telepresence.io/reference/windows). To be clear, we have not tried this in a long time, since before Itamar's comment (July 2017). Please let us know how it goes.

**Comment by remoe** [comment]
I try to run telepresence on WSL with "--docker-run --method container" in a minikube environment:

```telepresence --docker-run --method container --new-deployment app --expose 8080```

It throws the following error:

```

Background process (Network container) exited with return code 1. Command was:
  docker run --publish=127.0.0.1:50576:38022/tcp --hostname=telepresence-1551607778-1786397-3560-f5c4f484b-27tvf --dns=10.96.0.10 --dns-search=default.svc.cluster.local --dns-search=svc.cluster.local --dns-search=cluster.local --dns-opt=ndots:5 --rm --privileged --name=telepresence-1551607785-1683218-3560 datawire/telepresence-local:0.97 proxy '{"cidrs": ["0/0"], "expose_ports":
[]}'

Recent output was:
  Traceback (most recent call last):
    File "/usr/bin/entrypoint.py", line 127, in <module>
      main()
    File "/usr/bin/entrypoint.py", line 65, in main
      proxy(loads(sys.argv[2]))
    File "/usr/bin/entrypoint.py", line 83, in proxy
      "SSH from local container to the cluster failed to start."
```

I don't want to use ```--method inject-tcp```, because I need Kube DNS.

**Comment by reegnz** [comment]
WSL2 should be examined, I assume telepresence would work much better with it. https://devblogs.microsoft.com/commandline/announcing-wsl-2/

**Comment by AlexisDucastel** [comment]
I'm also intrested in Windows support ! Is WSL2 test good enough to let us use telepresence on Win ?

**Comment by robross0606** [comment]
From what I've read, WSL2 runs on top of Hyper-V which is a beast.  No better than running Docker for Windows.  Dubious design choice.

**Comment by mausch** [comment]
IIRC I tested Telepresence on WSL1 a long time ago and it worked.
But now I've switched to WSL2 and Telepresence doesn't seem to work proxying to Windows processes (WSL2 processes would work fine I think). Using `inject-tcp`.

Possibly related WSL2 github issue: https://github.com/microsoft/WSL/issues/4150

**Comment by pmorch** [comment]
Doesn't (some of) telepresence work on Windows? Can this be closed? See also #1787

**Comment by pmorch** [comment]
@mauch: I have no idea how it worked or not in WSL1 a long time ago.

But `inject-tcp` is documented in https://www.telepresence.io/reference/methods.html as:

> `--method inject-tcp` works by injecting a shared library into the subprocess run by Telepresence using `--run` and `--run-shell`.

If this sets up `LD_LIBRARY_PATH` to inject an `.so` shared library, then there is no way this is going to work for a Windows binary.

[Windows support](https://www.telepresence.io/reference/windows) says (among other [confusing things](https://github.com/telepresenceio/telepresence/issues/1787)):

> Only the `inject-tcp` method is supported. Network proxying won't affect Windows binaries.

@mauch writes:

> But now I've switched to WSL2 and Telepresence doesn't seem to work proxying to Windows processes (WSL2 processes would work fine I think). Using inject-tcp.

In light of the above, isn't this the documented and therefore expected behavior?

**Comment by mauch** [comment]
@pmorch  I think you have the wrong @mausch :wink:

**Comment by mausch** [comment]
So yes this bit of docs is correct :

>  Only the inject-tcp method is supported. Network proxying won't affect Windows binaries.

Though to be a bit more clear the docs IMHO should say "Windows processes" instead of "Windows binaries".

Now, back to the original issue of "Windows support", it depends on whether you consider WSL part of Windows or not :slightly_smiling_face: 

And also whether you want to support Windows processes.

WSL is not my daily driver tbh but I'm pretty sure telepresence already works just fine when everything is within WSL.
