### ISSUE TITLE
Support bastion connections

### ISSUE THREAD

**Issue by nfrush** [telepresenceio/telepresence#921]
I don’t know if this is relevant, but I have kubernetes clusters that sit in rodouction environments only reachable by tunneling through a bastion host. Is this something you guys support? Or would it need to be added?

**Comment by ark3** [comment]
If `kubectl` works, then Telepresence should work too. Telepresence communicates with the cluster entirely using `kubectl` commands. If tunneling uses a VPN, then the vpn-tcp method probably won't work, but the other methods should be fine. Please let us know how it goes. Thank you!
