### ISSUE TITLE
Deployment Swap DNS Fails

### ISSUE THREAD

**Issue by seivad** [telepresenceio/telepresence#922]
Hey guys

When trying to swap out a deployment with a telepresence proxy, it works and loads but inside the application the calls to local DNS services (other microservices in K8s) can't connect to it.

Deployments:
laravel-test-1
laravel-test-2

laravel-test-2 sends a payload json response (1 sentence)
laravel-test-1 receives the payload using a Guzzle call on http://laravel-test-2/api/payload

For development purposes, the example would be I need to add additional data sent back from the payload on laravel-test-2. 

So I fire up telepresence:

```
telepresence --swap-deployment laravel-test-2 --expose 8080 --run php artisan serve --port=8080
```

I can access the application at ```http://localhost:8080/api/payload``` and receive something like:

```
{
  "message": "Sending back the payload!",
  "users": [
    "mick",
    "nick",
    "jono"
  ],
}
```

I can update this application response and then hitting same url receive:

```
{
  "message": "Sending back the payload!",
  "users": [
    "mick",
    "nick",
    "jono"
  ],
  "companies": [
    "apple",
    "dell",
    "microsoft"
  ]
}
```

Excellent, so now I load up laravel-test-1 in the browser for instance ```minikube service --url laravel-test-1``` and get ```http://192.168.99.103:31010/``` but it only receives an error saying laravel-test-2 url cannot be found from Guzzle. Example:

```
Route::get('/', function () {
    $client = new GuzzleHttp\Client();
    $res = $client->request('GET', 'http://laravel-test-2/api/payload');
    $body = json_decode($res->getBody()->getContents());

    return response()->json([
        'status' => $res->getStatusCode(),
        'content-type' => $res->getHeader('content-type')[0],
        'response' => collect($body),
    ], 200);
});
```

I'm not sure how to get this to work, I want to be able to edit a microservice locally whilst it still can communicate with other microservices on their DNS name.

**Comment by ark3** [comment]
To summarize, you're saying that a service running in Kubernetes (l-t-1) can find your service (l-t-2) normally, but cannot find your service (l-t-2) when you've swapped it. Is that summary correct?

If so, that is most unusual, as Telepresence does not modify _cluster_ DNS at all, and swap-deployment does not affect the k8s Service that would be responsible for creating the DNS entries.

Can you verify that accessing your service (l-t-2) works from inside the cluster? Something like `kubectl run curl-test -it --rm --image=fedora:latest --restart=Never -- curl http://laravel-test-2/api/payload`? Please try that with and without the swap. I'm curious to hear what happens.

Thank you for your help debugging this.

**Comment by seivad** [comment]
Thanks for the swift reply, your summary is correct. When I replace l-t-2 with a local development (working on / testing) version, l-t-1 which does a Guzzle call to it fails, the DNS dies. It's still active in the K8s Dashboard.

I'll try your test on Monday morning and report back with the results.

My goal is to be able to swap out any microservice in minikube with a local version of the app, so my team and I can make changes etc... and still test (integration even) against the whole environment.

**Comment by seivad** [comment]
Yeah I can't get it to work, doing your curl test fails when it's under --swap-deployment mode. 

I can't access the site that's been swapped either by the minikube & port number whilst in "swap" mode. If I ```ctrl + c```, it then allows me to access it without error using the minikube + port number. 

I've tried so many port variations on the --expose flag, nothing works. 

Latest try was ```telepresence --swap-deployment laravel-test-2 --expose 9000 --run php artisan serve --port=9000``` but I have also tried ```telepresence --swap-deployment laravel-test-2 --expose 80:80 --run php artisan serve --port=9000``` and ```telepresence --swap-deployment laravel-test-2 --expose 9000:80 --run php artisan serve --port=9000``` and other variations like that.

Any ideas?

**Comment by seivad** [comment]
Slight progress update, if I delete the deployment of l-t-2 from the Dashboard then do a new deployment with telepresence ```telepresence --new-deployment laravel-test-2 --expose 8080``` allows me to run commands in the cluster on an alpine box ```wget -O - -q http://laravel-test-2:8080/api/payload``` and it works but accessing the l-t-1 from the web browser just keeps spinning / timing out. But from the alpine box on the cluster, it can hit it.

**Comment by ark3** [comment]
Most unusual. As I said, Telepresence does not modify DNS in the cluster. It _does_ modify DNS on your local machine. Because you are running Minikube, which runs locally, I wonder if something we're doing to DNS is confusing the cluster. What platform is your local machine? And what VM driver are you using for Minikube?

**Comment by seivad** [comment]
Hey I'm on Mojave (OSX), I turn off Laravel's Valet functionality too ```valet stop``` before running and I kill any ports open on 8080 / 80 before trying. VirtualBox for the VM too. This is a new MBP15 as well I ordered on Xmas eve, so it's relatively untainted with months of developer type hacks, it's fresh.

The ```--new-deployment``` does work fine, I wrote up a medium article about it yesterday but swapping would be ideal.

**Comment by ark3** [comment]
I didn't realize you were using another tool to modify DNS too. This comes down to my unfamiliarity with Laravel. Sorry about that! I wouldn't be surprised if `valet`'s DNS caching (really `DNSMasq`, I think) was interacting with MacOS's DNS caching in a way that confuses Telepresence (really `sshuttle`). 

Can you try resetting the OS cache with `sudo killall -HUP mDNSResponder` before starting Telepresence? Or after starting it from another shell?

I appreciate your continued assistance with debugging this. Also, could you pass along a link to your Medium article? Thank you for that!
