### ISSUE TITLE
docker-run failed to connect to remote cluster

### ISSUE THREAD

**Issue by rawenous** [telepresenceio/telepresence#923]
### What were you trying to do?

sudo telepresence --docker-run -i -t alpine /bin/sh

### What did you expect to happen?

expected to get an interactive shell in the context of the running pod

### What happened instead?

It crashed.

### Automatically included information

Command line: `['/usr/bin/telepresence', '--docker-run', '-i', '-t', 'alpine', '/bin/sh']`
Version: `0.97`
Python version: `3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.10.0 // Server Version: v1.11.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 95, in launch
    mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 168, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 346, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 335, in _run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1549610113-0592515-2326', '--rm', 'datawire/telepresence-local:0.97', 'wait']' returned non-zero exit status 1

```

Logs:

GIST: https://gist.github.com/rawenous/f7e4448685ef7a2406aae171b8950ed0

```
: 80 bytes
  19.2  26 | c : DNS request from ('172.17.0.2', 59406) to None: 80 bytes
  21.8  26 | c : DNS request from ('172.17.0.2', 55842) to None: 80 bytes
  24.3  26 | c : DNS request from ('172.17.0.2', 55842) to None: 80 bytes
  26.9  26 | c : DNS request from ('172.17.0.2', 40596) to None: 80 bytes
  29.4  26 | c : DNS request from ('172.17.0.2', 40596) to None: 80 bytes
  30.5 TEL | [35] Running: sudo -n echo -n
  32.0  26 | c : DNS request from ('172.17.0.2', 57436) to None: 80 bytes
  34.5  26 | c : DNS request from ('172.17.0.2', 57436) to None: 80 bytes
  37.1  26 | c : DNS request from ('172.17.0.2', 44331) to None: 80 bytes
  39.6  26 | c : DNS request from ('172.17.0.2', 44331) to None: 80 bytes
  41.9 TEL | (proxy checking local liveness)
  41.9  19 | 2019-02-08T07:15:48+0000 [Poll#info] Checkpoint
  42.2  34 | Failed to connect to proxy in remote cluster.
  42.2  34 | [INFO  tini (1)] Main child exited normally (with status '1')
  42.8 TEL | [34] exit 1 in 31.78 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. This is unusual, as the container method is usually quite robust. Do you always see this failure? Is `firewalld` running on your machine? Is there any other interesting or unusual network configuration? Is it possible that you're running into [this issue](https://www.telepresence.io/reference/limitations#ec2)?

**Comment by rawenous** [comment]
Thanks for the reply. Yes I always see this failure. Yes ```firewalld``` is running on my machine.
Interesting or unusual network configurations? I'm afraid I am not knowledgeable enough to answer this what I can say is that it is a computer that is maintained by puppet so I guess most of my network configurations would come from there.

About the EC2 limitation I don't think I am running into that issues. I am not using ec2 and also I am not seeing any issues resolving hostnames?

**Comment by ark3** [comment]
Telepresence is trying to resolve the hostname kubernetes.default.svc.cluster.local from within a Docker container whose network is being forwarded to the cluster. This is the step that is failing, which is why I asked about the EC2 DNS issue, but upon further reflection I don't think that's relevant in this case.

Just as a sanity check, can you verify that resolving that hostname is possible in your cluster?

```
kubectl run sanity-check -it --rm --image=python:alpine --restart=Never -- python -c "import socket; print(socket.gethostbyname('kubernetes.default.svc.cluster.local'))"
```

Can you try running Telepresence with `firewalld` temporarily disabled? Something like `sudo service firewalld stop` or `sudo systemctl stop firewalld` should do it. Replace `stop` with `start` to get things back to normal.

Thank you for your help debugging this.

**Comment by rawenous** [comment]
Hi, thanks and sorry for the really late reply. 

Here are the logs with firewalld disabled.

https://gist.github.com/rawenous/7c7cf1a18a921b807fedb65fe340d3e2

And the sanity check.
```
kubectl run sanity-check -it --rm --image=python:alpine --restart=Never -- python -c "import socket; print(socket.gethostbyname('kubernetes.default.svc.cluster.local'))"
10.96.0.1
pod "sanity-check" deleted

```

**Comment by vetmik** [comment]
@ark3 hi, i have the same issue. Maybe you can help me.
It's not possible to resolve kubernetes.default.svc.cluster.local in my cluster. It's overwritten by kubernetes.default.svc.my-company-name. Can i use telepresence with such host name? Or there is misconfiguration in my kubernetes cluster.
