### ISSUE TITLE
RuntimeError: vpn-tcp tunnel did not connect

### ISSUE THREAD

**Issue by M0nsieurChat** [telepresenceio/telepresence#924]
### What were you trying to do?

First time using telepresence, just wanted to give it a try

### What did you expect to happen?

I think the correct behaviour is the binary correctly starts up and I'd be able to reach pods and services from my computer.

### What happened instead?

 It crashed and told me to open this issue.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.97`
Python version: `3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]`
kubectl version: `Client Version: v1.13.2 // Server Version: v1.11.5-gke.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux frl16 4.18.1-041801-generic #201808151233 SMP Wed Aug 15 16:39:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 295, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
n-tcp connection: hellotelepresence-165
  36.1 TEL | Wait for vpn-tcp connection: hellotelepresence-166
  36.3 TEL | Wait for vpn-tcp connection: hellotelepresence-167
  36.9 TEL | Wait for vpn-tcp connection: hellotelepresence-168
  37.0 TEL | Wait for vpn-tcp connection: hellotelepresence-169
  37.1 TEL | Wait for vpn-tcp connection: hellotelepresence-170
  37.2 TEL | Wait for vpn-tcp connection: hellotelepresence-171
  37.4 TEL | Wait for vpn-tcp connection: hellotelepresence-172
  37.5 TEL | Wait for vpn-tcp connection: hellotelepresence-173
  37.7 TEL | Wait for vpn-tcp connection: hellotelepresence-174
  37.8 TEL | Wait for vpn-tcp connection: hellotelepresence-175
  38.2 TEL | Wait for vpn-tcp connection: hellotelepresence-176
  38.7 TEL | Wait for vpn-tcp connection: hellotelepresence-177
  38.8 TEL | Wait for vpn-tcp connection: hellotelepresence-178
  39.0 TEL | Wait for vpn-tcp connection: hellotelepresence-179
  39.3 TEL | Wait for vpn-tcp connection: hellotelepresence-180

```

**Comment by M0nsieurChat** [comment]
telepresence. log : https://gist.github.com/M0nsieurChat/199a7343e860dcd219306eb9a9c5716e

**Comment by ark3** [comment]
Sorry about the crash, and thank you for including the full log file. It looks like DNS lookups are not getting intercepted by sshuttle at all (neither single-segment lookups like `test`, nor multi-segment lookups like `test.a.long.name.telepresence.io`). Are you running another VPN? Is there anything else interesting or unusual about your network setup?

**Comment by popaaaandrei** [comment]
I have the same experience on MacOS Mojave 10.14.4. Running as administrator with sudo rights but still the same thing. Installed through Homebrew.

**Comment by cauli** [comment]
I'm having a similar experience.

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.99`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.10.11 // Server Version: v1.12.7-gke.10`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin c02y10uljgh8-c 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 311, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
k: b'hellotelepresence-3.a.sanity.check.telepresence.io'
  31.0 TEL | [31] exit 1 in 0.24 secs.
  31.0 TEL | [32] Running: sudo -n echo -n
  31.0 TEL | [32] ran in 0.03 secs.
  31.1 TEL | Wait for vpn-tcp connection: hellotelepresence-4
  31.1 TEL | [33] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-4")'
  36.1 TEL | [33] timed out after 5.01 secs.
  36.1 TEL | [34] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-4.a.sanity.check.telepresence.io")'
  36.1  23 | c : DNS request from ('192.168.43.28', 59618) to None: 68 bytes
  36.2  15 | 2019-06-11T07:16:51+0000 [stdout#info] Sanity check: b'hellotelepresence-4.a.sanity.check.telepresence.io'
  36.2 TEL | [34] exit 1 in 0.13 secs.
  36.5  23 | c : DNS request from ('192.168.43.28', 65423) to None: 28 bytes
  36.7  15 | 2019-06-11T07:16:51+0000 [stdout#info] A query: b'github.com'
  36.7  15 | 2019-06-11T07:16:52+0000 [stdout#info] Result for b'github.com' is ['140.82.118.4']

```

**Comment by cauli** [comment]
I'm not running in another VPN .

- Tried multiple networks.
- Tried clearing DNS cache `sudo killall -HUP mDNSResponder`
- Tried clearing `~/.ssh/known_hosts`
- Tried changing to google DNS `8.8.8.8`
- Tried restarting the computer 🥇 

Nothing worked.

**Comment by ark3** [comment]
@cauli What MacOS is that?

**Comment by cauli** [comment]
@ark3 macOS 10.14.5 (18F203)

**Comment by ark3** [comment]
In this case it turned out to be a conflict with some Consul configuration in `/etc/resolvers/`. Telepresence should pay attention to that sort of thing, at least when it fails to connect. #1049 will get us moving in that direction.

**Comment by kamalrajv** [comment]
was there a resolution for this issue, for me it starts working for the first request and i could debug it locally but on the terminal i see this error. i am using a swap-deployment

```
T: Forwarding remote port 4000 to local port 4000.


Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/Users/kr/homebrew/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/Users/kr/homebrew/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/Users/kr/homebrew/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/Users/kr/homebrew/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/Users/kr/homebrew/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect
```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
