### ISSUE TITLE
telepresence intellij issue

### ISSUE THREAD

**Issue by fengchangfight** [telepresenceio/telepresence#925]
The tutorial looks easy, but when I try to swap one of my deployment from my cluster, and export the yaml file which was used by intellij env file tab, it doesn't work, the remote cluster cannot sense the existence of my local env, and vice versa, any ideas?

**Comment by ark3** [comment]
Could you please pass along your session's telepresence.log file as a [Gist](https://gist.github.com/)? Thank you.
