### ISSUE TITLE
got an error while running pod shell

### ISSUE THREAD

**Issue by AndriiOpryshko** [telepresenceio/telepresence#927]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--deployment', 'myserver', '--expose', '8080', '--run-shell', '--namespace', 'apollo']`
Version: `0.97`
Python version: `3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.10.11 // Server Version: v1.10.9`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin PLUA18004-MC.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 295, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
21.60.40']
  23.8  26 | c : DNS request from ('172.20.60.51', 64259) to None: 44 bytes
  23.8  13 | 2019-02-19T13:22:38+0000 [stdout#info] A query: b'centrifypod19.cloudapp.net'
  23.9  13 | 2019-02-19T13:22:38+0000 [stdout#info] Result for b'centrifypod19.cloudapp.net' is ['40.121.60.40']
  28.8  26 | c : DNS request from ('172.20.60.51', 64259) to None: 44 bytes
  28.8  13 | 2019-02-19T13:22:43+0000 [stdout#info] A query: b'centrifypod19.cloudapp.net'
  28.9  13 | 2019-02-19T13:22:43+0000 [stdout#info] Result for b'centrifypod19.cloudapp.net' is ['40.121.60.40']
  30.9 TEL | [27] Running: sudo -n echo -n
  32.8  26 | c : DNS request from ('172.20.60.51', 64259) to None: 44 bytes
  32.8  13 | 2019-02-19T13:22:47+0000 [stdout#info] A query: b'centrifypod19.cloudapp.net'
  32.9  13 | 2019-02-19T13:22:47+0000 [stdout#info] Result for b'centrifypod19.cloudapp.net' is ['40.121.60.40']
  36.6 TEL | (proxy checking local liveness)
  36.7  13 | 2019-02-19T13:22:51+0000 [Poll#info] Checkpoint

```

**Comment by ark3** [comment]
It looks like you're running MacOS Mojave. Is that right? As a sanity check, can you try `telepresence -m inject-tcp --run curl -k https://kubernetes.default/api/`?

**Comment by AndriiOpryshko** [comment]
@ark3 
Yes, macOS Mojave 10.14.3 .

T: Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom 
T: DNS implementations are not supported. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Deployment telepresence-1551970496-919016-9268

T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports 
T: you want to forward.

T: Setup complete. Launching your command.
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}T: Your process has exited.
T: Exit cleanup in progress
T: Cleaning up Deployment telepresence-1551970496-919016-9268
