### ISSUE TITLE
Telepresense stopped working out of nowhere: "SSH from local container to the cluster failed to start"

### ISSUE THREAD

**Issue by borremosch** [telepresenceio/telepresence#928]
### What were you trying to do?

I was trying to swap one of my containers into my local Minikube cluster. This has been working for some weeks now, but all of a sudden it has stopped working and I cannot seem to get it working again. A reboot has not helped, trying to swap different images/pods has not helped either.

### What did you expect to happen?

I expected my local docker image to be deployed into my Minikube cluster.

### What happened instead?

Telepresence apologized for containing a bug and sent me to this form.

telepresence.log can be found here: https://gist.github.com/borremosch/829a7371c3b349b7fcad1bab56d100a6

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'middleware', '--expose', '4000', '--docker-run', '-v', '/home/username/companyname/scripts/../components/middleware:/usr/src/app', '-v', '/home/username/companyname/scripts/../lib/git-url-parser:/usr/src/app/node_modules/git-url-parser', 'middleware:latest', '-p', '4000', 'npm', 'start']`
Version: `0.97`
Python version: `3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]`
kubectl version: `Client Version: v1.13.3 // Server Version: v1.12.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 95, in launch
    mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 154, in run_docker_command
    raise RuntimeError("SSH to the network container failed to start.")
RuntimeError: SSH to the network container failed to start.

```

Logs:

```
36.9  33 |   29.7 TEL | [117] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  36.9  33 |   29.7 TEL | [117] exit 255 in 0.01 secs.
  37.2  33 |   29.9 TEL | [118] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38023 telepresence@127.0.0.1 /bin/true
  37.2  33 |   29.9 TEL | [118] exit 255 in 0.00 secs.
  37.2  33 | Traceback (most recent call last):
  37.2  33 |   File "/usr/bin/entrypoint.py", line 127, in <module>
  37.2  33 |     main()
  37.2  33 |   File "/usr/bin/entrypoint.py", line 65, in main
  37.2  33 |     proxy(loads(sys.argv[2]))
  37.2  33 |   File "/usr/bin/entrypoint.py", line 83, in proxy
  37.2  33 |     "SSH from local container to the cluster failed to start."
  37.2  33 | RuntimeError: SSH from local container to the cluster failed to start.
  37.2  33 | [INFO  tini (1)] Main child exited normally (with status '1')
  37.4 TEL | [33] exit 1

```

**Comment by ark3** [comment]
Telepresence launches a container ("the network container") with `docker run --publish=127.0.0.1:46747:38022/tcp ...` and runs an SSH daemon in that container on port 38022. The intent is to be able to `ssh` into the container to set up port forwarding, etc. 

In your logfile, attempts to ssh into the container (via 127.0.0.1:46747) are failing immediately. It is as if ssh were getting "Connection refused" from the attempt. Can you add `--verbose` to your command and pass along the logfile? That will cause `ssh` (and everything else) to emit more information and may shed some light on what's going on.

As to why this would start failing all of a sudden, I'm not sure. Might a recent update have changed Docker or the kernel? Have you recently added `minikube docker-env` to your process?

Can you try an even simpler command? `telepresence --docker-run --rm -it fedora curl -k https://kubernetes.default/api/`

**Comment by borremosch** [comment]
Hey @ark3,

Thanks for your reply. It was my bad. I was still connected to the Minikube docker daemon rather than my local docker daemon by running `eval $(minikube docker-env)` rather than `eval $(minikube docker-env -u)` prior to running telepresence.

Maybe it would be nice if the error message can be a bit less cryptical (perhaps it's possible detecting that Telepresence is trying to connect to a docker daemon instance inside Minikube?) but the issue is resolved for me, thanks!

**Comment by ark3** [comment]
Yup, that's #873. I'm glad to know you're up and running again.
