### ISSUE TITLE
swap deployment with docker-run error

### ISSUE THREAD

**Issue by zhujian7** [telepresenceio/telepresence#945]
### What were you trying to do?

as described in title

### What did you expect to happen?

swapping deployment with docker-run works well

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'devops-admin-admin-v1-0', '--docker-run', '--rm', '-it', 'insight.caicloudprivatetest.com/release/devops-admin:zj-v1']`
Version: `0.97`
Python version: `3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.12.0 // Server Version: v1.12.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin zhujiandeMacBook-Air.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 104, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 156, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 103, in get_deployment_json
    )["items"][0]
IndexError: list index out of range

```

Logs:

```
_deployment_json)    0.6s
   4.7 TEL | [10] Running: kubectl --context dev-96 --namespace default delete deployment devops-admin-admi-0cdf9bb85665430a81d4b270cb7a7669 --ignore-not-found
   5.6 TEL | [11] Running: kubectl --context dev-96 --namespace default apply -f -
   6.4  11 | deployment.extensions/devops-admin-admi-0cdf9bb85665430a81d4b270cb7a7669 created
   6.4 TEL | [12] Running: kubectl --context dev-96 --namespace default scale deployment devops-admin-admin-v1-0 --replicas=0
   7.5  12 | deployment.extensions/devops-admin-admin-v1-0 scaled
   7.5 TEL | [12] ran in 1.11 secs.
   7.5 TEL | END SPAN deployment.py:150(supplant_deployment)    3.4s
   7.5 TEL | BEGIN SPAN remote.py:154(get_remote_info)
   7.5 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   7.5 TEL | [13] Capturing: kubectl --context dev-96 --namespace default get deployment -o json --export --selector=telepresence=0cdf9bb85665430a81d4b270cb7a7669
   8.4 TEL | END SPAN remote.py:78(get_deployment_json)    0.9s

```

**Comment by ark3** [comment]
Sorry about the crash. Telepresence should not be crashing here. However, it seems there's something special about your cluster. This issue and #944 are the same crash. Can you tell me about your cluster? Thank you.
