### ISSUE TITLE
telepresence kubernetes ribbonclient issue

### ISSUE THREAD

**Issue by fengchangfight** [telepresenceio/telepresence#947]
I was using ribbon client within kubernetes to do the service discovery work, it works fine , but when I swap the deployment A with telepresence , let's say deployment A calls deployment B,  it's complaining "Did not find any endpoints in ribbon in namespace [null] for name [B] and portName [null], what should I do? I've been wasting a lot of time on this, please help!!!

**Comment by fengchangfight** [comment]
why it's looking for B service within in null namespace? and null port? isn't that telepresence works like vpn and every value should be transparent?

**Comment by ark3** [comment]
Can you please link to the ribbon client documentation? I'm not sure what it does, but I'll take a look.

**Comment by tryelse** [comment]
@fengchangfight possibly you need to set env variable like
`KUBERNETES_NAMESPACE=default` or other if you have a non-default namespace.
Take a look to a warn logs during start of the application
