### ISSUE TITLE
DNS Problems with CompanyIntranet

### ISSUE THREAD

**Issue by qux42** [telepresenceio/telepresence#957]
Using Telepresence with the --vpn-tcp Option routes all dns-traffic to the DNS-Server on Kubernetes. Because of this, DNS-Resolve for hostnames located in the intranet don't work anymore.

I'm not familiar with sshuttle, but "--auto-hosts" sounds like a possible solution for this. 
Or is it possible to use the default dns-server for specified hostnames? 

Thanks :)

**Comment by LukeShu** [comment]
`telepresence outbound`/`teleproxy` does this (it runs a DNS server locally; proxying requests either to kubernetes or to the system DNS server); I'm not sure what the roadmap is for making that the standard mode of operation
