### ISSUE TITLE
vpn tunnel sometimes fails on Mac Mojave

### ISSUE THREAD

**Issue by sgandon** [telepresenceio/telepresence#958]
I am using telepresence on MacOS Mojave to swap deployment on a remote cluster and I have quite often trouble making the vpn work.
for instance I have a redis instance running on my cluster so I can easily check the routing works or not issueing this command
```redis-cli -h redis``` in the telepresence shell.
Sometime is works sometimes it fails.
when I am using the `dig redis` command it always succeeds.

I spend quite some time trying to findout the issue with ark3 on slack whithout any success.
see : https://datawire-oss.slack.com/conversation/CAUBBJSQZ/p1549989010032100

**Comment by coffenbacher** [comment]
Also seeing this; `dig` works for me as well.
