### ISSUE TITLE
Cannot start telespresence

### ISSUE THREAD

**Issue by pklink** [telepresenceio/telepresence#963]
### What were you trying to do?

trying to start telepresence with `sudo telepresence --docker-run -i -t alpine /bin/sh`

### What did you expect to happen?

telepresence starts

### What happened instead?

it crashed

### Automatically included information

https://gist.github.com/pklink/a1c1539e9364c03bb2ef7fc91dd8ba05

Command line: `['/usr/local/bin/telepresence', '--docker-run', '-i', '-t', 'alpine', '/bin/sh']`
Version: `0.97`
Python version: `3.7.2 (default, Feb 20 2019, 12:15:24) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.13.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Pierres-iMac.fritz.box 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 104, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 156, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 101, in get_deployment_json
    stderr=STDOUT
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
=telepresence=567f1d07a5c44099b40e50042c054fa6
   1.5 TEL | [10] Capturing: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25

**Comment by pklink** [comment]
if i try it without the sudo (just `telepresence --docker-run -i -t alpine /bin/sh`) it returns `Failed to open logfile (/usr/local/telepresence.log): [Errno 13] Permission denied: '/usr/local/telepresence.log'
`

**Comment by edclement** [comment]
experiencing the same issue, problem seems to be related to using kubectl 1.14.0. I ended up reverting back to 1.13.x

**Comment by pklink** [comment]
> experiencing the same issue, problem seems to be related to using kubectl 1.14.0. I ended up reverting back to 1.13.x

works for me. ty

**Comment by ptemmer** [comment]
The reason for this happening is the fact that Telepresence uses a kubectl option (--export) that is deprecated. As of kubectl 1.14 the first line of the returned output is a deprecation warning message, instead of the actual JSON string. This results in Telepresence not being able to parse the message, as it ain't valid JSON

"Guilty" line in Telepresence code:
`kubectl  get deployment DEPLOYMENT_NAME -o json --export`

https://github.com/kubernetes/kubernetes/pull/73787

**Comment by ark3** [comment]
Handling this in #966
