### ISSUE TITLE
After 1 sec when telepresence Connected to k8s, it lost connection

### ISSUE THREAD

**Issue by JoeCao** [telepresenceio/telepresence#969]
### What were you trying to do?

when i using telepresence connect to k8s 
### What did you expect to happen?

It connected and work as usually

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)
[telepresence.log](https://github.com/telepresenceio/telepresence/files/3020683/telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'dev', '--swap-deployment', 'dev-easysale', '--env-json', 'easysale_env.json']`
Version: `0.97`
Python version: `3.7.3 (default, Mar 28 2019, 19:58:34) 
[Clang 8.0.0 (clang-800.0.42.1)]`
kubectl version: `Client Version: v1.12.0 // Server Version: v1.10.5-tke.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin joemacbook-2.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64`

```
Background process (kubectl logs) exited with return code 0. Command was:
  kubectl --context default-system --namespace dev logs -f dev-easysale-ed2cc88571134fdd9cc993884733a193-6fb8bd86bc-v6psm --container easysale --tail=10

Recent output was:
  2019-03-29T00:25:10+0000 [-] Resolver added ('172.31.255.38', 53) to server list
  2019-03-29T00:25:10+0000 [-] SOCKSv5Factory starting on 9050
  2019-03-29T00:25:10+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7ff9a0a21c88>
  2019-03-29T00:25:10+0000 [-] DNSDatagramProtocol starting on 9053
  2019-03-29T00:25:10+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7ff9a09aa048>
  2019-03-29T00:25:10+0000 [-] Loaded.
  2019-03-29T00:25:10+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.9.0 (/usr/bin/python3.6 3.6.5) starting up.
  2019-03-29T00:25:10+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  failed to watch file "/var/log/pods/11aaaca6-51b9-11e9-b87c-0a587f824e2c/easysale/0.log": no space left on device
```

Logs:

```
 redirector listening on ('::1', 12300, 0, 0).
  29.0  62 | TCP redirector listening on ('127.0.0.1', 12300).
  29.0  62 | DNS listening on ('::1', 12300, 0, 0).
  29.0  62 | DNS listening on ('127.0.0.1', 12300).
  29.0  62 | Starting client with Python version 3.7.3
  29.0  62 | c : connecting to server...
  29.0  52 | Handling connection for 49883
  29.1  62 | Warning: Permanently added '[127.0.0.1]:49883' (ECDSA) to the list of known hosts.
  29.5  62 | Starting server with Python version 3.6.5
  29.5  62 |  s: latency control setting = True
  29.5  62 |  s: available routes:
  29.5  62 |  s:   2/172.31.1.0/24
  29.5  62 | c : Connected.
  29.5  62 | firewall manager: setting up.
  29.5  62 | >> pfctl -s Interfaces -i lo -v
  29.5  62 | >> pfctl -s all
  29.5  62 | >> pfctl -a sshuttle6-12300 -f /dev/stdin
  29.5  62 | >> pfctl -E
  29.5  62 | >> pfctl -s Interfaces -i lo -v
  29.5  62 | >> pfctl -s all
  29.5  62 | >> pfctl -a sshuttle-12300 -f /dev/stdin
  29.5  62 | >> pfctl -E

```
and this is the k8s status 

[k8sstatus.txt](https://github.com/telepresenceio/telepresence/files/3020682/k8sstatus.txt)

**Comment by ark3** [comment]
Sorry about the crash! That "no space left on device" message from `kubectl logs` usually means there are no more inodes left. Your k8s status output seems to indicate there's plenty of free space (though to be fair, I haven't seen one of those before and may be reading it wrong...), so I suspect that's the issue.

Ultimately this boils down to the fact that a `kubectl logs` failure is fatal to Telepresence, and probably shouldn't be. This is tracked in #598.

**Comment by JoeCao** [comment]
thanks a lot
