### ISSUE TITLE
vpn-tcp connect times out too soon

### ISSUE THREAD

**Issue by jeff-knurek** [telepresenceio/telepresence#972]
### What were you trying to do?

`telepresence --namespace my-ns --method vpn-tcp --swap-deployment my-app --run-shell`

### What did you expect to happen?

no errors

### What happened instead?

`
Looks like there's a bug in our code. Sorry about that!`

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'my-ns', '--method', 'vpn-tcp', '--swap-deployment', 'my-app', '--run-shell']`
Version: `0.97`
Python version: `3.7.2 (default, Feb 12 2019, 16:46:33) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.11.7 // Server Version: v1.11.7-gke.12`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ta-scuzzolin-pc.int.travelaudience.com 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 295, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
._twistd_unix.UnixAppLogger#info] twistd 18.9.0 (/usr/bin/python3.6 3.6.5) starting up.
  54.0  21 | 2019-04-01T12:59:25+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  56.0  30 | c : DNS request from ('172.19.27.222', 2023) to None: 28 bytes
  56.0  21 | 2019-04-01T12:59:27+0000 [stdout#info] A query: b'github.com'
  56.3  21 | 2019-04-01T12:59:27+0000 [stdout#info] Result for b'github.com' is ['140.82.118.4', '140.82.118.3']
  63.7  30 | c : DNS request from ('172.19.27.222', 59648) to None: 33 bytes
  63.7  21 | 2019-04-01T12:59:35+0000 [stdout#info] A query: b'ssl.gstatic.com'
  63.8  21 | 2019-04-01T12:59:35+0000 [stdout#info] Result for b'ssl.gstatic.com' is ['74.125.133.94']
  65.4 TEL | [32] Running: sudo -n echo -n
  67.3  30 | c : DNS request from ('172.19.27.222', 49285) to None: 69 bytes
  67.4  21 | 2019-04-01T12:59:38+0000 [stdout#info] Sanity check: b'hellotelepresence-50.a.sanity.check.telepresence.io'

```

Output of `telepresence -m inject-tcp --run curl -k https://kubernetes.default/api/`
```
T: Setup complete. Launching your command.
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "35.___.___.___:443"
    }
  ]
}T: Your process has exited.
```

**Comment by jeff-knurek** [comment]
I've updated to `0.99` and still experience this issue

For more information, this is on MacOS Mojave, I'm not running a VPN. I even tried running the cmd on a hotspot network to confirm that it's not impacted by the office firewall

**Comment by ark3** [comment]
May I have a look at your (redacted-as-needed) telepresence.log file for a failing vpn-tcp session please? I can see that DNS requests are getting through, so this _should_ be working...

**Comment by jeff-knurek** [comment]
I sent the logs via direct email

**Comment by ark3** [comment]
Thank you for the logs and for making the effort to sanitize/redact them for my consumption. I appreciate that Telepresence probably logs too much sensitive information (#523).

Frustratingly, it looks like DNS requests start making it through right around the 25-second mark, which is when Telepresence times out and gives up. So everything was working fine, just a bit more slowly than anticipated. I expect if you ran Telepresence, waited for the crash report, and then in another window tried `curl -k https://kubernetes.default`, it would probably work. Note that once you hit yes/no on the crash reporter, Telepresence cleans up and puts things back the way they were, so you'd have to try this before responding to the crash reporter.

Anyhow, the straightforward answer is to increase that timeout (now: this issue) and make it configurable (soon: #985). Thanks for your help debugging this.

**Comment by ark3** [comment]
Release 0.101 will have a longer timeout here (35 seconds instead of 25).

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, we also have docs on how to configure timeouts in Telepresence: https://www.telepresence.io/docs/latest/reference/config/. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
