### ISSUE TITLE
e2e tests rely on external httpbin.org

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#973]
... and that service, which we do not control, changes. 

1. We used three different IPs for httpbin.org to test three different `--also-proxy` invocations, relying on the existence of those three non-overlapping IPs to avoid masking a failure in one case with a success in another. But httpbin.org no longer has three different IPs (as of April 1, 2019). So https://github.com/telepresenceio/telepresence/commit/1de52bcf0ac29a9510d09640f7e03c6fd238a145 doubles the _two_ IPs we get, so that tests pass. This means masking of a failure is possible. Also, if two IPs turns into one, tests will start failing again.

    This is not so bad. We can test that the different `--also-proxy` invocations yield the correct underlying data structure with unit tests. Then we can use just one `--also-proxy` in end-to-end tests to reduce the scope of this problem.

2. The format of the answer returned by http://httpbin.org/ip has changed. It may change again. https://github.com/telepresenceio/telepresence/commit/2ba42e54729e8335b5a0c256f58f5fa7e2dbdcc4 handles the current (as of April 1, 2019) result as well as the prior one. But this sort of thing may break tests again in the future.

**Comment by ark3** [comment]
Let's address this like so: https://github.com/telepresenceio/telepresence/pull/1167#issuecomment-549055271

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
