### ISSUE TITLE
telepresence --swap-deployment --run failing

### ISSUE THREAD

**Issue by aaronz1414** [telepresenceio/telepresence#977]
### What were you trying to do?

Swap a local node app with a deployment in a kubernetes cluster using
`telepresence --swap-deployment deployment-1 --run node src/app.js`

### What did you expect to happen?

The deployment to swap successfully and the node app to start running

### What happened instead?

The deployment swap failed and exited with the included output. It may be worth noting that I've also experienced this issue when running swap-deployment with minikube, but the logs provided here are for use with a gke cluster.

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'deployment-1', '--run', 'node', 'src/app.js']`
Version: `0.97`
Python version: `3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.11.7-gke.12`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux my-hostname 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 98, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 162, in supplant_deployment
    "deployment",
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    stderr=STDOUT
  File "/home/user1/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/user1/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user1/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
 headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
   0.8 TEL | Found sshfs -> /usr/bin/sshfs
   0.9 TEL | Found fusermount -> /bin/fusermount
   0.9 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   0.9 TEL | [8] Capturing: kubectl --context cluster-1 --namespace development get pods telepresence-connectivity-check --ignore-not-found
   1.4 TEL | Scout info: {'latest_version': '0.97', 'application': 'telepresence', 'notices': []}
   1.4 TEL | BEGIN SPAN deployment.py:150(supplant_deployment)
   1.4 >>> | Starting network proxy to cluster by swapping out Deployment deployment-1 with a proxy
   1.4 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   1.4 TEL | [9] Capturing: kubectl --context cluster-1 --namespace development get deployment -o json --export deployment-1
   1.7 TEL | END SPAN remote.py:78(get_deployment_json)    0.3s

```

**Comment by ark3** [comment]
Sorry about the crash. This #966, which will be fixed in the next release (tonight or tomorrow). In the meantime, you can work around this by dropping back to kubectl version 1.13.

**Comment by aaronz1414** [comment]
Thanks, sorry for missing the duplicate issue!
