### ISSUE TITLE
Can't build on CentOS 7.6, fails connect to clone sshuttle

### ISSUE THREAD

**Issue by davidmichaelkarr** [telepresenceio/telepresence#980]
I'm trying to build telepresence on a CentOS 7.6 VM, which is behind a firewall.  I start the "install.sh" script as prescribed, and after it sitting and not doing much for a while, I finally see this:

`fatal: unable to access 'https://github.com/datawire/sshuttle.git/': Failed connect to github.com:443; Operation now in progress
Traceback (most recent call last):
  File "packaging/build-sshuttle.py", line 77, in <module>
    main()
  File "packaging/build-sshuttle.py", line 73, in main
    build_sshuttle(output)
  File "packaging/build-sshuttle.py", line 30, in build_sshuttle
    str(code)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '-q', 'https://github.com/datawire/sshuttle.git', '/tmp/tmpysl38n98/sshuttle']' returned non-zero exit status 128.
`
I then went to another shell on the VM and did "git clone https://github.com/datawire/sshuttle.git".  This worked perfectly fine.

What might be wrong here?

**Comment by ark3** [comment]
I haven't seen this issue before, but it seems like "Operation now in progress" errors (`EINPROGRESS`) have to do with connectivity issues, proxy configurations, and other such things. Is it possible that the other shell has a different setting for the `http_proxy` environment variable? 

Possible poorly-documented workaround:

    wget https://s3.amazonaws.com/datawire-static-files/telepresence/telepresence-0.98.tar.gz

**Comment by davidmichaelkarr** [comment]
At this point, I've given up on this, as I think that using CentOS is not worth the trouble at this point.  I've moved to an Ubuntu VM, but I'm having different problems with that, but it may come back to the same problem.

This is what I see:

```
$ curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | sudo bash
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/datawireio_telepresence.list...
curl: (7) Failed to connect to packagecloud.io port 443: Connection timed out

Unable to run: 
    curl https://packagecloud.io/install/repositories/datawireio/telepresence/config_file.list?os=Ubuntu&dist=xenial&source=script

Double check your curl installation and try again.
```

**Comment by ark3** [comment]
Most peculiar. Does other stuff work as expected on these VMs?

**Comment by davidmichaelkarr** [comment]
I was able to get package updates from apt (and yum).  I thought perhaps it might be due to the network adapter setting, so I tried changing it from NAT to Bridged, but that made no difference.

**Comment by davidmichaelkarr** [comment]
Hmm, I just tried to install kubectl, and I saw it do this:

```
Hit:1 http://ubuntumirror.it.att.com/ubuntu xenial InRelease
Hit:2 http://ubuntumirror.it.att.com/ubuntu xenial-updates InRelease
Hit:3 http://ubuntumirror.it.att.com/ubuntu/xenial ato_tools InRelease
Hit:4 http://ubuntumirror.it.att.com/ubuntu xenial-security InRelease
Err:5 https://apt.kubernetes.io kubernetes-xenial InRelease
  Connection timed out after 120000 milliseconds
```

In both cases, it was a ".io" url that failed. Don't know if that means anything.

**Comment by davidmichaelkarr** [comment]
Never mind. I don't set up new systems often enough. I forget the dumb stuff, like setting proxy vars in /etc/environment.
