### ISSUE TITLE
Runner's get_output(...) elides the beginning of captured output that's too long

### ISSUE THREAD

**Issue by Chaitanya-Veluvolu-Randstad** [telepresenceio/telepresence#981]
### What were you trying to do?

Trying to telepresence into kube cluster

### What did you expect to happen?

I get a kube deployment and my laptop is added into the namespace and i can access kube objects in that namespace as if i was in the cluster

### What happened instead?
i get an error message saying there is a bug in your code.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'vpn-tcp', '--namespace', 'svc-edtest-stable-test', '--expose', '9090']`
Version: `0.98`
Python version: `3.7.3 (default, Apr  4 2019, 17:04:14) 
[Clang 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.9.6 // Server Version: v1.8.15-1+9f66f5c998b397`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Chaitanya.bose.com 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 256, in connect_sshuttle
    ] + get_proxy_cidrs(runner, remote_info, hosts_or_ips),
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 82, in get_proxy_cidrs
    result.update(context_cache.lookup("podCIDRs", lambda: podCIDRs(runner)))
  File "/usr/local/bin/telepresence/telepresence/runner/cache.py", line 105, in lookup
    value = function()
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 82, in <lambda>
    result.update(context_cache.lookup("podCIDRs", lambda: podCIDRs(runner)))
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 156, in podCIDRs
    runner.get_output(runner.kubectl("get", "nodes", "-o", "json"))
  File "/Users/chaitanyaveluvolu/.pyenv/versions/3.7.3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/chaitanyaveluvolu/.pyenv/versions/3.7.3/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 21 (char 20)

```

Logs:

```
 Listening...
  20.5  30 | 2019-04-05T14:26:20+0000 [-] Loading ./forwarder.py...
  20.5  30 | 2019-04-05T14:26:22+0000 [-] /etc/resolv.conf changed, reparsing
  20.5  30 | 2019-04-05T14:26:22+0000 [-] Resolver added ('100.64.0.10', 53) to server list
  20.5  30 | 2019-04-05T14:26:22+0000 [-] SOCKSv5Factory starting on 9050
  20.5  30 | 2019-04-05T14:26:22+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7fed4ae65240>
  20.5  30 | 2019-04-05T14:26:22+0000 [-] DNSDatagramProtocol starting on 9053
  20.5  30 | 2019-04-05T14:26:22+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fed48fddd30>
  20.5  30 | 2019-04-05T14:26:22+0000 [-] Loaded.
  20.5  30 | 2019-04-05T14:26:22+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.9.0 (/usr/bin/python3.6 3.6.5) starting up.
  20.5  30 | 2019-04-05T14:26:22+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.

```

**Comment by ark3** [comment]
Sorry about the crash. Can you please pass along the full telepresence.log as a Gist? Thank you.

**Comment by Chaitanya-Veluvolu-Randstad** [comment]
here is the gist .  [](https://gist.github.com/Chaitanya-Veluvolu-Randstad/1f500bff8bc907e70963fed6d1cdf047.js)

**Comment by ark3** [comment]
Is that the right file? It says it's from Telepresence 0.92 from September. And it looks like a successful session that ends cleanly.

**Comment by Chaitanya-Veluvolu-Randstad** [comment]
Hey sorry about that!! Here is today's https://gist.github.com/Chaitanya-Veluvolu-Randstad/235b4fc6055f6fe09a09b3c73175ab86

**Comment by ark3** [comment]
Thanks. What does this return?

    /usr/local/bin/kubectl --context live-aws-useast1-chaitanya_veluvolu@bose.com --namespace svc-edtest-stable-test get nodes -o json

It seems to be invalid JSON for some reason.

**Comment by ark3** [comment]
Thanks to lots of help and patience from @Chaitanya-Veluvolu-Randstad, I discovered the source of this error: 

```python
        self.capture = deque(
            maxlen=max_capture
        )  # type: typing.MutableSequence[str]
```

where `max_capture` happens to be too small to hold the entire result. As such, the top of the output was being thrown away, causing the JSON decoder to blow up. I'll have this fixed for the next release. Sorry for the dumb bug!
