### ISSUE TITLE
Optional configuration

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#985]
Users want to configure many aspects of Telepresence. However, the Telepresence command line experience is already too complicated; adding even more options would be overwhelming. It might be useful to offer **completely optional** configuration from another source (not the cli) for Telepresence. 

- configuration of the proxy Pod
  - resources (#1422)
  - node selector (#1096)
  - others?
- hosts/URLs for connectivity checks #389
- various timeouts #777 and #939 (cli `--timeout` option PR)
- executable to use in place of kubectl https://github.com/telepresenceio/telepresence/issues/914#issuecomment-479951009
  - use a specific executable (e.g., `kubectl1.10` for an old cluster)
  - use command line options Tel doesn't support (e.g., `kubectl --server foo --token $BLAH`)
  - force `kubectl` vs `oc` vs ...
- mount options
  - mount to a known directory
  - no volume mounting at all
- how `--verbose` modifies the helpers called by Telepresence
  - `ssh -vv` #1015
  - `kubectl --v=4` https://github.com/telepresenceio/telepresence/issues/807#issuecomment-430334967
- proxy to host polling interval
- default logfile location
- cache location, expiration times
- default method?
- other logging configuration (#1226)

Tel already uses environment variables for optional configuration (TELEPRESENCE_VERSION and TELEPRESENCE_REGISTRY). It could also look for a configuration file. 

See also #411 and #455.

**Comment by davidmichaelkarr** [comment]
I'm trying to consider the POV of whether adding additional options could be "overwhelming".  Certainly when a list of options is considered from the POV of the entire list of options, the more options you have, the more difficult it is to find the ones you need.

The simple solution implemented in numerous tools is simply to present the options list in groups.  I'm sure tp is already doing this.  kubectl already has many options. I don't find it "overwhelming". I look through the docs for what I need and ignore the rest.

Compare this with the steps that people might have to take to work around the lack of certain options. In my case, putting an "alternate" kubectl in the PATH really won't be helpful. That will be quite a bit messier than simply accepting the fact that I'll have to move to using contexts, which isn't as convenient in my situation.

However, if as in the description of this issue, you were able to implement some unusual method of supplying ANOTHER command-line argument that points tp to some sort of alternate "command-line processor" so I can still have "--server" and "--token" on the tp command line and not having those options added to tp itself, then I guess it's entirely possible that could work, but I don't see how this could be possible.

**Comment by tobiasfriden** [comment]
When can we expect the ability to manually configure timeout to be merged? (As mentioned in #939)
After switching to AWS Fargate (which has longer startup times) telepresence is currently unusable without this option

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. since Telepresence now supports client configuration: https://www.telepresence.io/docs/latest/reference/config/ Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
