### ISSUE TITLE
server and token command-line parameters?

### ISSUE THREAD

**Issue by davidmichaelkarr** [telepresenceio/telepresence#987]
I see that telepresence doesn't have some of the command-line parameters that kubectl has, for specifying details that would usually go into a context. Kubectl can use contexts, but you don't have to. If you want to specify the server, namespace, and token parameters on the command line, you can. For how I use it, that's actually more convenient, because I implemented a simple facade on top of kubectl that lets me select a different cluster very easily.

Now that I'm trying to use telepresence, it looks like it doesn't have the "server" or "token" command-line parameters.  Looking at the definition of a context, I'm sure I can do everything I need to do with a context, it's just not as convenient as what kubectl provides.

Is there a reason why telepresence doesn't have "server" or "token" command-line parameters?

**Comment by ark3** [comment]
No particular reason! Presumably the original author added `--context` and `--namespace` because those seemed like the commonly-used options, or those were the ones he used, or those were the ones that were asked for by early users. You're the first person to ask for `--server` and `--token` as far as I remember. 😄 

I'm hesitant to add _more_ options to Telepresence now, as it already has a rather complicated command line invocation. Rather than add every relevant `kubectl` option to Telepresence (`--as`, `--client-key`, and `--cluster` seem useful too), I'd prefer to let the user specify how to invoke `kubectl`. See https://github.com/telepresenceio/telepresence/issues/914#issuecomment-479612957 and #985. I'd appreciate your feedback on #985 regarding how it might be convenient to specify a `kubectl` invocation.

Until we have that feature, I can suggest using the workaround I mentioned in that comment. where you take advantage of Telepresence's use of the PATH environment variable. Essentially you'd create a one-line script that calls `/path/to/real/kubectl --token ... --server ...` with the passed-in arguments, name that script `kubectl`, and put it at the beginning of Telepresence's path.

**Comment by davidmichaelkarr** [comment]
I added a comment on #985. The workaround you describe really won't help. I'd have to have different kubectl scripts for each server/token combination representing each of our clusters and move each one in when I needed to use it. That will be much more painful than simply adapting what I do to use contexts, which isn't as convenient for me.

Those useful kubectl command-line options are useful because they are useful.  Making more options available doesn't make anyone's command-line invocation of tp more complicated, only if they end up having a use for those options, and if they did have a use for those options, what they're doing now instead of using those options is probably more complicated than the command line with those useful options added.

**Comment by ark3** [comment]
To clarify, I intended the `kubectl` scripts thing as a _temporary_ workaround, not as a good, user-friendly long-term solution. Anyhow, I'm coming around to your way of thinking and want to explore this further.

At present, Telepresence computes the implied `--context` and `--namespace` arguments for `kubectl` by querying the cluster (unless they are explicitly specified by the user at the command line). Once that is done, Telepresence includes those arguments in every call to `kubectl` that it makes. This allows Telepresence to behave sanely even if someone changes contexts or namespaces during a session.

If Telepresence accepts `--server` and passes that on to `kubectl`, then also passing `--context` no longer makes sense. Do I understand that correctly? More generally, we'll have to figure out a set of rules that Telepresence can use to construct a `kubectl` command that it can then use consistently through a session. The current rules will no longer be sufficient or correct. This is perfectly do-able, though I could use help!

The solution I originally had in mind was to use the `rsync` approach. The `rsync` command uses `ssh` under the hood (originally `rsh`), but lets the user specify the exact `ssh` invocation if desired with the `-e`/`--ssh` argument. We could do the same thing with Telepresence by offering a `--kubectl` argument. If the user includes `--kubectl` then Telepresence would use that command as-is, without adding `--context` or anything else. 

Doing things this way (the `rsync` approach) would allow me to skip the work of figuring out how to call `kubectl` in every case. Instead, I would be laying that burden upon the user. This is not as friendly or convenient for the user, though I would be able to get it out the door much sooner.

Thoughts?

**Comment by davidmichaelkarr** [comment]
I would also think it's unlikely that anyone would ever combine "--context" with any of the other parameters whose values are typically set in the context, but I also have not really used contexts yet, because they weren't convenient for what I was trying to do. I can see other situations where they would be more useful.

Your basic approach seems right. It's reasonable to assume the use of contexts by default, but allowing a simple mechanism to override that.

So this "--kubectl" option would have a single value, holding the entire kubectl command line?  I wouldn't think it's the entire "command line", but simply the general kubectl options, not specifying a kubectl subcommand, or any options to a subcommand. What arguments would telepresence typically add to that skeleton command line?

**Comment by ark3** [comment]
Telepresence computes the first part of its `kubectl` commands, something like

    kubectl --context minikube --namespace default

and then appends the subcommand and arguments whenever it makes a call, such as

    get nodes
    get deployment -o json --selector=telepresence=blah
    logs -f telepresence-blah --container telepresence-blah --tail=10
    port-forward telepresence-blah 50770:8022

etc. My proposed `--kubectl` option would let the user replace the computed portion above.

    telepresence --kubectl="/usr/bin/kubectl1.10 --token $TOKEN --server $SERVER" --docker-run [...]

Would that address your use-case?

**Comment by davidmichaelkarr** [comment]
I also use the "--insecure-skip-tls-verify" flag.  I don't know if that
would already be available.

With that, I believe that would address my use case.

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
