### ISSUE TITLE
T: Mount error was: mount_osxfuse: the file system is not available (1)

### ISSUE THREAD

**Issue by Castro-711** [telepresenceio/telepresence#988]
### What were you trying to do?

telepresence --run curl http://myservice:8000/

### What did you expect to happen?

print "Hello, World" to the console

### What happened instead?

The command failed and the following traceback was printed...

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--mount', '/Users/eric.cassells/Scylla/telepresence', '--run', 'curl', 'http://myservice:8000/']`
Version: `0.98`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.12.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ASSIGNREALTINY.workdayinternal.com 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 295, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
600
  50.5 TEL | Wait for vpn-tcp connection: hellotelepresence-142
  50.6 TEL | Wait for vpn-tcp connection: hellotelepresence-143
  50.8 TEL | Wait for vpn-tcp connection: hellotelepresence-144
  50.9 TEL | Wait for vpn-tcp connection: hellotelepresence-145
  51.1 TEL | Wait for vpn-tcp connection: hellotelepresence-146
  51.2  27 | Warning: Permanently added '[127.0.0.1]:54600' (ECDSA) to the list of known hosts.
  51.2 TEL | Wait for vpn-tcp connection: hellotelepresence-147
  52.7  27 | Starting server with Python version 3.6.5
  52.7  27 |  s: latency control setting = True
  52.7  27 |  s: available routes:
  52.7  27 | c : Connected.
  52.7  27 | firewall manager: setting up.
  52.7  27 | >> pfctl -s Interfaces -i lo -v
  52.7  27 | >> pfctl -s all
  52.7  27 | >> pfctl -a sshuttle6-12300 -f /dev/stdin
  52.7  27 | >> pfctl -E
  52.8  27 | >> pfctl -s Interfaces -i lo -v
  52.8  27 | >> pfctl -s all
  52.8  27 | >> pfctl -a sshuttle-12300 -f /dev/stdin
  52.8  27 | >> pfctl -E

```

**Comment by ark3** [comment]
From the log snippet it looks like the vpn-tcp tunnel was very slow to connect, so Telepresence gave up and crashed just as it started to come up. The mount error seems unrelated; failure to mount is not fatal to Telepresence.

Does this happen every time? Can you pass along the full telepresence.log as a Gist?
