### ISSUE TITLE
error dialing backend: dial tcp 10.0.2.146:6443: i/o timeout

### ISSUE THREAD

**Issue by lukewhiting** [telepresenceio/telepresence#994]
### What were you trying to do?

Connecting to the cluster in VPN mode

### What did you expect to happen?

Was connected to cluster in VPN mode

### What happened instead?

It crashed

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--namespace', 'production']`
Version: `0.98`
Python version: `3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.13.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux bananya 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 66, in main
    env, pod_info = get_remote_env(runner, ssh, remote_info)
  File "/usr/bin/telepresence/telepresence/remote_env.py", line 34, in get_remote_env
    remote_info.container_name, "--", "python3", "podinfo.py"
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 401, in get_output
    env,
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 367, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['kubectl', '--context', 'testing', '--namespace', 'production', 'exec', 'telepresence-1555337367-6072743-20168-7b4bff49c5-fjlfs', '--container', 'telepresence-1555337367-6072743-20168', '--', 'python3', 'podinfo.py']' returned non-zero exit status 1.

```

Logs:

```
ded ('10.43.0.10', 53) to server list
  17.9  19 | 2019-04-15T14:09:45+0000 [-] SOCKSv5Factory starting on 9050
  17.9  19 | 2019-04-15T14:09:45+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f10f42990b8>
  17.9  19 | 2019-04-15T14:09:45+0000 [-] DNSDatagramProtocol starting on 9053
  17.9  19 | 2019-04-15T14:09:45+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f10f0dc3c50>
  17.9  19 | 2019-04-15T14:09:45+0000 [-] Loaded.
  17.9  19 | 2019-04-15T14:09:45+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.9.0 (/usr/bin/python3.6 3.6.5) starting up.
  17.9  19 | 2019-04-15T14:09:45+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  27.8  25 | error: unable to upgrade connection: error dialing backend: dial tcp 10.0.2.146:6443: i/o timeout
  27.8 TEL | [25] exit 1 in 16.73 secs.
  27.8 TEL | END SPAN remote_env.py:28(get_remote_env)   16.7s

```

**Comment by ark3** [comment]
Sorry about the crash. Does this happen every time?

Can you try replicating this manually, by [creating a deployment](https://www.telepresence.io/reference/connecting#running-telepresence-manually) and then running the same `exec`? I am curious as to whether this is a permission problem outside of Kubernetes. The command would be

    kubectl --context testing --namespace production exec myservice -- python3 podinfo.py

assuming you kept the "myservice" name for your deployment.

**Comment by lukewhiting** [comment]
It seems to happen very infrequently... I have been trying to replicate it without success. Will update if I find any kind of pattern and will pull as many logs as I can.

**Comment by ark3** [comment]
Got it. Thanks for clarifying.
