### ISSUE TITLE
Swap deployment with args

### ISSUE THREAD

**Issue by sebglon** [telepresenceio/telepresence#997]
I want to swap a deployment.
all seems good by on the pod, i not found args available on my deployment.

Is it possible to concat them on a env variable or add them on the pod definition?

**Comment by LukeShu** [comment]
Let me make sure I understand you correctly.  Are you asking for the `deployment.spec.template.spec.containers[n].args` (and/or `.command`) array to be exposed to your local (on-your-laptop) process as an environment variable?

**Comment by sebglon** [comment]
Yes it's that. to run the app whit the same args

**Comment by donnyyung** [comment]
I think this is still a feature we could add to Telepresence v2

**Comment by momom-i** [comment]
Is this issue already done?
